### PR TITLE
Tweaked the StyleCop utility output

### PR DESCRIPTION
**Pull request by Mailaender**
to enhance readability as you only care for what went wrong not has been checked okay.

### CODE REVIEW

**Comment by pchote** [comment]
Good idea to cut out the redundant information. :+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by Phrohdoh** [comment]
I wish I would have seen this earlier to ask for better/sensible commit message for the second commit. :(

**Comment by Mailaender** [comment]
Try constructive criticism. Better give direct replacement solutions in those cases.

**Pull request merged**
