### PR TITLE
Remove Bloody Delta from the ra map pool

### LINKED ISSUE #12282: Suggestion: Remove Map "Blody Delta" from official maps (RA)
I talked to some pro players and they all confirmed that this map doesn't satisfies the standard map quality anymore.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #12282.

I tend to agree with #12282 because we have a lot of other good 1v1 maps in the pool thanks to the RA GL maps. Although `Bloody Delta` has some nice visuals, I also don't really like the bottle neck (only one mud bridge) and the slightly imbalanced spawns (east is nearer to the shore).

Also see https://www.youtube.com/watch?v=OgYJpaPtlNI.

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by obrakmann** [comment]
This map's layout isn't really suited for good gameplay, I agree. 👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/cac3b5dc263cdf9d2f6729ee47f0dc6b1fab927f)

**Comment by TheRaffy** [comment]
:+1: :

**Pull request merged**
