### PR TITLE
Fix crash with dead cargo.

### LINKED ISSUE #15261: If a passenger somehow dies in cargo, it causes crashes
We should implement proper support for passengers dying in a cargo for stuff like General's Garrison Cleaning weapons. Related to #14989.

### LINKED ISSUE #16405: Dead units can enter transports (Crashes when unloaded)
There's a tight race condition that is allowing units to die and enter transports on the same tick. This will cause the game to crash when that transport tries to unload.

Engine version: release-20190314

Replay: [OpenRA-2019-04-12T191227Z.zip](https://github.com/OpenRA/OpenRA/files/3075621/OpenRA-2019-04-12T191227Z.zip) - happens just before 14:00, replay is 14:04 long.

Stacktrace:
```
OpenRA engine version release-20190314
Tiberian Dawn mod version release-20190314
on map 1823885808927deb9fbb4c746ea9e8693fd6428e (Renegade 2D (C&C 0.93) by hamb).
Date: 2019-04-12 19:26:30Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (e6 244 (not in world))
   в OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   в OpenRA.TraitDictionary.Get[T](Actor actor)
   в OpenRA.Actor.Trait[T]()
   в OpenRA.Mods.Common.Traits.Cargo.<CanUnload>c__AnonStorey2.<>m__0(Actor p)
   в System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   в OpenRA.Mods.Common.Traits.Cargo.<CanUnload>m__4(CPos c)
   в System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   в OpenRA.Mods.Common.Traits.Cargo.CanUnload()
   в OpenRA.Mods.Common.Traits.Cargo.ResolveOrder(Actor self, Order order)
   в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   в OpenRA.Network.OrderManager.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Game.InitializeAndRun(String[] args)
   в OpenRA.WindowsLauncher.RunGame(String[] args)
```

We can confirm this happens by adding an `a.IsDead` check to the beginning of `Cargo.Load(self, a)`. I'm not sure of the best way to fix this though.

### LINKED ISSUE #17015: Crash caused by dead cargo
Reported by eskimo [on the forum](https://forum.openra.net/viewtopic.php?p=310677#p310677):
```
OpenRA engine version playtest-20190825
Red Alert mod version playtest-20190825
on map 97e53df23fb9fddb54d096d62f3cc49054250a58 (Promising Hills by km).
Date: 2019-08-29 19:45:42Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (e2 144 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.Get[T](Actor actor)
   at OpenRA.Mods.Common.Traits.Cargo.<>c__DisplayClass35_1.<CanUnload>b__1(Actor p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.Cargo.<>c__DisplayClass35_0.<CanUnload>b__0(CPos c)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Mods.Common.Traits.Cargo.<get_Orders>b__29_0()
   at OpenRA.Mods.Common.Orders.DeployOrderTargeter.CanTarget(Actor self, Target target, List`1 othersAtTarget, TargetModifiers& modifiers, String& cursor)
   at OpenRA.Orders.UnitOrderGenerator.OrderForUnit(Actor self, Target target, List`1 actorsAt, CPos xy, MouseInput mi)
   at OpenRA.Orders.UnitOrderGenerator.<>c__DisplayClass5_0.<GetCursor>b__0(Actor a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenRA.Exts.CompareBy[T,U](IEnumerable`1 ts, Func`2 selector, Int32 modifier, Boolean throws)
   at OpenRA.Orders.UnitOrderGenerator.GetCursor(World world, CPos cell, int2 worldPixel, MouseInput mi)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.<>c__DisplayClass14_0.<GetCursor>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor(int2 screenPos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

### PR DESCRIPTION
**Pull request by tovl**
Fixes #17015 
Fixes #16405
Fixes #15261

### CODE REVIEW

**Comment by teinarss** [comment]
Think it would be better to add the dead check here, because right now with this fix its possible to have a transport with dead actors(?).
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/RideTransport.cs#L54

**Comment by tovl** [comment]
Added the check on both ends, just in case.

**Comment by abcdefg30** [comment]
Out of curiosity: Do we actually remove passengers dying inside the transport from blocking space?

**Comment by tovl** [comment]
As far as I can tell, we don't.

**Comment by teinarss** [comment]
> 
> 
> Out of curiosity: Do we actually remove passengers dying inside the transport from blocking space?

With the check in place in the FrameEndTask there should be no cases where the cargo is dead, or am i missing some other case?

**Comment by abcdefg30** [comment]
Cargo dying inside the transport. I have to retest if this is still possible to do with negative self healing.

**Review by pchote — APPROVED** [review]
Looks reasonable, but I haven't tested the various edge cases.

**Review by abcdefg30 — APPROVED** [review]
Cargo dying inside a transport is removed as well.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a1fa3e4b733de59d9abdf609021ca82b7396d4ee...10b0e427ce12a79f5f76e63d50edb6e51133251a)

https://github.com/OpenRA/OpenRA/commit/3b1a9534f7c870ef261ec99ce32a8ba333db62c8

**Pull request merged**
