### PR TITLE
Add support for disabling IIssueDeployOrders.

### LINKED ISSUE #14729: Command bar deploy button flashes for TD aircraft
It flashes when the hotkey is pressed for example, but the deploy doesn't do anything.
Noticed while testing #14649 but left to this ticket as discussed on IRC.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14729

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
@MustaphaTR @ltem could one of you review this? The code changes are fairly simple and it's easy to verify in-game (just check that the button is disabled/doesn't flash in TD and still works in RA for helis).

**Comment by pchote** [comment]
Should also test this on an actor with a conditional `Transforms` trait.

**Review by MustaphaTR — APPROVED** [review]
Done the said tests, works fine. 👍

**Comment by ltem** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/05dc8474cb0b3051b1752c46d7ad7232c03cfe21...2bf1f1b662a8f704571075c4428fdc5b60737f0a)

pushed to `prep-1801`: [ae03c6605](https://github.com/OpenRA/OpenRA/commit/ae03c660596f6f345ed7ea53a30957aaba394ed9)

**Pull request merged**
