### PR TITLE
Removed the unused movie lists

### PR DESCRIPTION
**Pull request by Mailaender**
This is redundant since https://github.com/OpenRA/OpenRA/pull/6643 and https://github.com/OpenRA/OpenRA/pull/3305.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Are the "names" with the "description" available somewhere else?
(Those descriptions could be useful for mappers/modders.)

**Comment by obrakmann** [comment]
[They are now](https://github.com/OpenRA/OpenRA/wiki/List-of-FMVs)

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
Also http://freecnc.org/dev/video-lists/

**Comment by abcdefg30** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/46b12eaed7ea8b71312b00b0873f527bfc05a1fb...e379847e086c9724e17260d1de593d29e306ef73)

**Pull request merged**
