### PR TITLE
Fixed indentions of weapon documentation table of contents

### PR DESCRIPTION
**Pull request by Mailaender**
Same as https://github.com/OpenRA/OpenRA/pull/13873. See the [Diff](https://github.com/OpenRA/OpenRA/wiki/Weapons/_compare/ffb37b28a3b35d1fb151e6ca0391c2e983e94ecb...8ce39b76fc00bc3e33f7574d43fb24e718fc267e?short_path=1bf0826#diff-1bf0826a16a1d7a1358b50a5daeab933).

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by GraionDilach** [comment]
Should be merged to Next imo, not Next+1. Along with #13873.

**Comment by Mailaender** [comment]
You are right. https://github.com/OpenRA/OpenRA/pull/11913 was for stable as well.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c6b10d6bba66401f4eb20e04c3da8f49e38bf49f

The version of `ExtractWeaponDocsCommand.cs` that was cherry-picked to prep-1707 has a number of changes compared to the version on bleed, so this does not cleanly pick onto it.  What is going on?

**Comment by reaperrr** [comment]
Seems my git GUI cherry-picked from a slightly stale revision of #11913, so it was missing a few style-fixes.

Fixed and cherry-picked this PR.

**Pull request merged**
