### PR TITLE
Remove a forgotten TilesetBuilder reference from the Makefile

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenRA/OpenRA/pull/7772.

### CODE REVIEW

**Comment by penev92** [comment]
:+1:

**Comment by obrakmann** [comment]
Ok, rgrep shows that's the last occurance of "TilesetBuilder" in the tree. Should be fine after this. :+1:

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/rdiff/games:openra/playtest?linkrev=base&rev=13 fixes it.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/780501e1f9723cb4e6fb8ac13a9da2cec3f0e8db%5E...780501e1f9723cb4e6fb8ac13a9da2cec3f0e8db)

**Pull request merged**
