### PR TITLE
Add IdleSpeed setting to Aircraft

### PR DESCRIPTION
**Pull request by reaperrr**
We already have `IdleTurnSpeed`, and this has been requested before.

### CODE REVIEW

**Comment by pchote** [comment]
The sudden jerk from one speed to the other is really jarring, IMO. I expect this will generate complaints ingame.

It would feel much better if we could transition between the two speeds over a few ticks, controlled by an acceleration parameter.  This would then also resolve #10672.

**Comment by reaperrr** [comment]
Added (de-)acceleration.

**Comment by pchote** [comment]
Thinking out loud: doesn't `IdleSpeed` effectively supersede `CanHover`? IMO it is intuitive that `IdleSpeed: 0` implies that the aircraft should hover when idle.

This then also folds nicely into predicting deceleration rates, which is something I plan to comment more about when I have time to dig in the code.

**Comment by reaperrr** [comment]
> Thinking out loud: doesn't IdleSpeed effectively supersede CanHover? IMO it is intuitive that IdleSpeed: 0 implies that the aircraft should hover when idle.

Updated (and rebased).

**Comment by reaperrr** [comment]
This would likely break the D2k Carryall if merged before #16483, because AutoCarryalls on bleed still need `CanHover` but an idle speed > 0.
Adding 'Has dependencies' as I don't feel like investing time to find a temporary work-around.

**Comment by pchote** [comment]
I expect we'll need to tweak the approach here so that units can plan ahead and decelerate before reaching the target - best to get the other low hanging fruit out of the way, and then come back to this with hopefully a lot less aircraft activities to deal with.

**Comment by pchote** [comment]
Closing to help clean up the PR queue. We can reopen this once the prereqs are merged and we've thought about how will work with the height prediction logic (which needs to be able to slow down if the aircraft will otherwise hit a cliff) and D2k's carryalls.

**Pull request closed without merging**
