### PR TITLE
Don't allow tanya to automatically target, but allow her to move within a attack-moving/guarding group

### PR DESCRIPTION
**Pull request by abcdefg30**
Guarding makes her kind of a walking turret as well (as did attack-move).

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
I don't like this because it is baking in a bug (#9383) with specific code.  The "proper" technique for disabling attacks without breaking group movement is to remove `AutoTarget` while keeping the `AttackMove` trait.

**Comment by abcdefg30** [comment]
Updated. This makes the yaml changes needed so that #9383 is fixed entirely together with #11637.

**Comment by abcdefg30** [comment]
Sorry, @Mailaender I think I have to remove your 👍 .

**Comment by Mailaender** [comment]
Allies01 now crashes with
```
[2016-08-29T07:08:58] Game started
line not found
line not found
line not found
Fatal Lua Error: 
Stack Traceback
===============
(2) global C function 'error'
(3) Lua function '(anonymous)' at file '/home/matthias/Entwicklung/OpenRA//lua/sandbox.lua:150' (best guess)
	Local variables:
	 arg = nil
	 ok = boolean: false
	 result = string: "[string \"BindingSupport.lua\"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Actor does not have trait of type `OpenRA.Mods.Common.Traits.PlayerExperience`\
  at OpenRA.TraitDictionary+TraitContainer`1[T].Get (UInt32 actor) [0x0003e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/TraitDictionary.cs:153 \
  at OpenRA.TraitDictionary.Get[T] (OpenRA.Actor actor) [0x00013] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/TraitDictionary.cs:89 \
  at OpenRA.Actor.Trait[T] () [0x0000d] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Actor.cs:247 \
  at OpenRA.Mods.Common.Scripting.PlayerExperienceProperties..ctor (OpenRA.Scripting.ScriptContext context, OpenRA.Player player) <0x41e3d6c0 + 0x00033> in <filename unknown>:0 \
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)\
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/mcs/class/corlib/System.Reflection/MonoMethod.cs:644 \
  --- End of inner exception stack trace ---\
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00013] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/mcs/class/corlib/System.Reflection/MonoMethod.cs:650 \
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00089] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/mcs/class/corlib/System.Reflection/MonoMethod.cs:635 \
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/mcs/class/corlib/System.Reflection/MonoMethod.cs:663 \
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:62 \
  at OpenRA.Scripting.ScriptPlayerInterface+<ScriptPlayerInterface>c__AnonStorey0.<>m__0 (System.Type cg) [0x0002f] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Scripting/ScriptPlayerInterface.cs:33 \
  at System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () [0x0004d] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/external/referencesource/System.Core/System/Linq/Enumerable.cs:327 \
  at OpenRA.Scripting.ScriptObjectWrapper.Bind (IEnumerable`1 clrObjects) [0x000ad] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Scripting/ScriptObjectWrapper.cs:34 \
  at OpenRA.Scripting.ScriptPlayerInterface..ctor (OpenRA.Scripting.ScriptContext context, OpenRA.Player player) [0x00043] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Scripting/ScriptPlayerInterface.cs:36 \
  at OpenRA.Player+<OnScriptBind>c__AnonStorey4.<>m__0 () [0x0000c] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Player.cs:221 \
  at System.Lazy`1[T].CreateValue () [0x00075] in /home/abuild/rpmbuild/BUILD/mono-4.4.2/external/referencesource/mscorlib/system/Lazy.cs:437 "
(4) tail call
(5) Lua function '?' at line 15 of chunk '"scriptwrapper.lua"]'
(6) global C function 'xpcall'
(7) Lua upvalue 'TryRunSandboxed' at line 15 of chunk '"scriptwrapper.lua"]'
	Local variables:
	 fn = Lua function '?' (defined at line 165 of chunk "allies01.lua"])
(8) Lua function '?' at line 23 of chunk '"scriptwrapper.lua"]'
```

**Comment by GraionDilach** [comment]
This needs a rebase to fix that, I guess.

**Comment by abcdefg30** [comment]
Rebased.

**Comment by pchote** [comment]
This plus #11637 (which is now merged on latest bleed) finally remove the confusion from using Tanya at these difficulty levels.  :+1: and nominating for playtest.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c859970cf11f0dacc11a6d9d417aeebddc966ff0)

**Pull request merged**
