### PR TITLE
Make all of mininuke's SpreadDamage warheads affect the parent

### LINKED ISSUE #7327: dtrk - tsla bug
release-20141029
demo-truck is doing no damage on a enemy tesla-coil 
demo tesla

cant reproduce 

map is called "The Earth 2064" http://resource.openra.net/maps/1119
replay : https://www.dropbox.com/s/gxo3rpuh6q0k6lb/demo%20tesla%20bug.rep?dl=0
here is a screenshot for the exact time , and position ... on the map 

openra 2015-01-13 01-17-21-16

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7689981-dtrk-tsla-bug?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #7327 again.

### CODE REVIEW

**Comment by chrisforbes** [comment]
:+1:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by Mailaender** [comment]
Fixed as promised. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4f9c6631ceeacbfba463741f5cd84698842434b6...768c233eaa73a2b47312ed2e1c280552c5472c48)

**Pull request merged**
