### PR TITLE
Fix Concrete placement on invalid terrain.

### LINKED ISSUE #19097: D2kBuilding & removal of LaysTerrain means D2k concrete no longer functions correctly
Since LaysTerrain was removed, and merged into D2kBuilding, the functionality required for Dune 2000's concrete is no longer met.

D2kBuilding that has "AllowInvalidPlacement: true" means it will place the concrete on ANY terrain type below the foundation. Previously LaysTerrain had a check of its own for suitable terrain to override, but with D2kBuilding the concrete shares that check with the building itself.

In the intended functionality is that concrete only gets placed on clear rock tiles, and any invalid tiles are ignored.

invalid

### PR DESCRIPTION
**Pull request by pchote**
Fixes #19097.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
We probably need the same check in line 112/113?

**Comment by reaperrr** [comment]
> We probably need the same check in line 112/113?

Looks like it.

**Comment by pchote** [comment]
🤦

Updated.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/189dd7591576941914eb7ef2a7156da746fd6dbc...7de8e936cbad5ac16f437c62d4060f133881e9b1)

https://github.com/OpenRA/OpenRA/commit/503a434a4b1078c7e46bd82cd6034be781c53bf0

**Pull request merged**
