### PR TITLE
Custom Sprite support for mods.

### PR DESCRIPTION
**Pull request by IceReaper**
This allows mods to extend the Sprite class without modifying the OpenRA.Game or OpenRA.Common project.

In my current project, i have per-frame offset-points, which need to be stored for every sprite. With this modification i can implement it purely on the mod-side.

### CODE REVIEW

**Comment by pchote** [comment]
I asked this in IRC when you first brought up this topic, but I didn't see a response: what is our existing mod-defined `ISpriteSequence` / `ISpriteSequenceLoader` code missing for your use case?

The sequence loaders can return `Sprite` subclasses that contain extra data, which is how we handle the per-image depth maps in the gen2 mods ([DefaultSpriteSequence.cs#L207](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs#L207)).

**Comment by pchote** [comment]
While it doesn't affect this PR directly, I have a strong caution about how I assume you are using this in your mod code:  You said in IRC that you want to use this for positioning turrets on actors.  Turret positions are important for the simulation code (since it impacts where projectiles are fired from), but Sprite objects are only available from the rendering code.  Rendering is decoupled from simulation, and the game will desync in multiplayer if you try to modify simulation state from render code.

**Comment by IceReaper** [comment]
About the usage: We talked about that on IRC, and i will find a better way to archive my goal. However, the usage for this PR is simple: Allow per-frame custom properties to be set. Here is an usecase:
spriteswithpoints
This vehicle for example "hops" while moving. The turret has to be reposition for every frame - but should not affect the logic. For the logic part, the turret has to stay at the center to have the same range in all directions. This custom data has to be present on frame level, which is what this PR allows you to do. This PR is an requirement before i can teach the renderer how to correctly handle this information.

**Comment by GraionDilach** [comment]
I don't see why it shouldn't affect the logic. Fire-on-the-move (which all turreted units are capable of in OpenRA) with that hopping means that the turret offset should also hop along with the artwork.

**Comment by pchote** [comment]
As mentioned above, we already support the goals of this PR with the custom sequence loaders, and adding a repeat of that feature to sprites isn't practical because of the simulation/render split.

I don't think there's much more to do here, so i'm going to close this.

**Pull request closed without merging**
