### PR TITLE
Refactor resource harvesting logic.

### LINKED ISSUE #13260: Harvesters sometimes mine resources it can't harvest
https://www.youtube.com/watch?v=Zl7j4hSTW6g

Steps to reproduce
* Create a map like this to confine ore growth with gems.
* Disallow harvesters to mine gems using map rules
* Build enough harvesters so that they will fight over resources
* Make ore grow really fast.
Harvesters will fight over the narrow ore patch and eventually, they will mine the gem patch.

The sample map is here:
https://github.com/forcecore/OpenRA/tree/HarvDeadlock/mods/ludicrous

### LINKED ISSUE #16412: Harvesters refusing all mining orders on bleed
When an ore patch is mined out some harvesters seem to enter a state in which they start to refuse ALL mining orders. One can still issue move orders and set them to a return trip to refineries

Harvester bug

A replay where it happens (last bleed commit #16241):
[OpenRA-2019-04-13T211331Z.zip](https://github.com/OpenRA/OpenRA/files/3076756/OpenRA-2019-04-13T211331Z.zip)
 it was first found in RV.

Also I heavily dislike that when an ore patch is mined out Harvesters start a suicide mission to mine ore all the way across the map

@tovl

### PR DESCRIPTION
**Pull request by tovl**
Split from #16408.

Fixes #16412 
Fixes #13260

Added a temporary workaround for #12817, because otherwise without the pathfinding changes in #16408 this would make the  problem worse.

### CODE REVIEW

**Review by pchote — APPROVED** [review]
Code changes look good, and I didn't notice any bad behaviour testing in TD.

**Comment by matjaeck** [comment]
What's the plan with the temporary fix here? Revert it in #16408? Then I would like too keep #13260 open and and a comment about the temporary fix.

**Comment by tovl** [comment]
The temporary fix to #12817 will be reverted in #16408. This temporary fix does not unfix #13260 because there is now an explicit check for harvestable resources after the move as well.

**Comment by matjaeck** [comment]
What I request is that we don't close #13260 here (remove the "Fixes ..." from this PR'S description) when the plan is to revert this change later. I don't really understand what you mean with "does not unfix". Do you mean that reverting the fix does not "unifx" the issue? The problem I have is that currently this PR and #16408 "fix" #13260, and only the "real" fix should close the issue IMO.

**Comment by matjaeck** [comment]
Sorry my bad, I misunderstood what issues this PR closes.

**Review by PunkPun — APPROVED** [review]
I ran some tests and harvesters only get temporally stuck when they exceed the 3 harvs per refinery limit. As intended.

**Review by ghost — APPROVED** [review]
Created a test map and #13260 seems fixed, too.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/dbc7881ca7964cfed62490b3b81699554c9adf72...0740ee7c0e2893911efbcd9c374b935ee3f2895e

**Pull request merged**
