### PR TITLE
Fix crash when the mouse-overed support power loses all instances.

### LINKED ISSUE #14639: Game crash when hovering over a support power while its providing building is destroyed
If you hover over a support power's icon in the top left of the screen while the building that provides it gets destroyed, it crashes the game. This happened in the current playtest - I haven't tried the release version to see if it happens there.

In case it helps - I was testing this with a Ukraine Airstrip and Parabombs.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14639.

### CODE REVIEW

**Comment by LipkeGu** [comment]
I was also on this :D atm but when adding your line and recompiling and retesting fixes the crash. :+1:
I tested it with the RA Nuke

**Review by Arular101 — APPROVED** [review]
👍 Crash is fixed.

Something unrelated: just noticed if I keep my mouse on the side bar at for example the ore truck, and the war factory gets destroyed, the tooltip stays.

image

It's not a problem, just wondered if that is similar and easy to fix.

**Comment by pchote** [comment]
Should be easy enough to fix, but out of scope for this PR.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/0cbf2b25e5b2a986c15a0de11a05ba5f10e7a3d4...9ca2b4c319c7d33fe8623b478419ff69745c0c99)

**Pull request merged**
