### PR TITLE
Lobby Chat - host is searching for map #9569

### PR DESCRIPTION
**Pull request by rob-v**
Chat message when host is browsing map.

obrazok

### CODE REVIEW

**Comment by pchote** [comment]
IMO this looks like it will just add noise to the chat without solving any real problems?

**Comment by rob-v** [comment]
Maybe something simpler than this text to indicate host is searching for map - it can take a minute and during this time host does not see messages so users would know they need to wait and not to spam the chat (it can look host is afk while changing map). @kyrreso could comment it.

**Comment by pchote** [comment]
This is one of many reasons why players may not read the chat, so I think it is a bad idea to give this (and only this) case its own specific UI.

**Comment by kyrreso** [comment]
Would a star after host's name, or changed name to be in _italics_ help? Or the button <change map> change color? Can the text be "pinnned" and removed when host is done? 
In my case, when I change map as host, I hear a lot of ppl chatting or just joining, and I cannot tell them what I am doing. When I return, they are gone...

**Comment by rob-v** [comment]
@pchote I agree. Anyway changing map in MP should take few seconds as host usually knows the map he wants to play.
@kyrreso Once agreed, I can update it to something simpler than chat messages, else let's close it.

**Comment by pchote** [comment]
> Once agreed, I can update it to something simpler than chat messages, else let's close it.

Probably best to keep the discussion in #9569, and only then open a new PR if an adequate solution is found.

**Pull request closed without merging**
