### PR TITLE
Fixed the TS mod crashing on startup and oh trains!

### PR DESCRIPTION
**Pull request by Mailaender**
:bullettrain_side:

### CODE REVIEW

**Comment by pchote** [comment]
I like trains. :+1:

**Comment by LipkeGu** [comment]
:+1:

**Comment by Phrohdoh** [comment]
Can you give us a test commit?
Or should this depend on #9211?

**Comment by Mailaender** [comment]
Use the map editor to place the units into a map. There is nothing else to test yet.

**Pull request merged**
