### PR TITLE
Replaced Ticks with Delay/Duration

### PR DESCRIPTION
**Pull request by colonelpopcorn**
Per issue #9810: refactored ticks to delay in all the specified files pointed out by @atlimit8.

### CODE REVIEW

**Comment by GraionDilach** [comment]
You have to write your own upgrade rule, not modifying an existing one.

**Comment by penev92** [comment]
Thanks for the refactor.
These renamings will need upgrade rules, which you may want to see us on IRC about.

**Comment by colonelpopcorn** [comment]
Will do, I'll see about writing an upgrade rule tomorrow.

**Comment by colonelpopcorn** [comment]
Is there any documentation on upgrade rules? It looks look it's a program built to output a proper .yaml file for maps and mods based on version #, but I can't make heads or tales of it. In lieu of documentation could I get an output .yaml file?

**Comment by pchote** [comment]
Superseded by #10711.

**Pull request closed without merging**
