### PR TITLE
Fix collision detection for Missiles and Bullets.

### LINKED ISSUE #5294: High velocity bullets shooting through walls
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2123330-high-velocity-bullets-shooting-through-walls?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #5294.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
The repeated code makes me feel that pulling out an `IBlockableProjectile` interface or some such and some helper methods may be useful.

**Comment by pchote** [comment]
Rebased.  @RoosterDragon: all the actual useful code is already factored into a helper, so the remaining duplication is just plumbing the input and output variables.  Its not clear to me how we could reduce that any further.

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by reaperrr** [comment]
This now needs the upgrade rule from #9800 to be run (or yamls fixed manually).

**Comment by reaperrr** [comment]
:+1: after rebase & adaption to #9800.

**Comment by pchote** [comment]
Rebased and adapted.  The collision point doesn't look correct for the square hit shape, so I suspect something may be wrong with the underlying logic from that PR.

**Comment by reaperrr** [comment]
> The collision point doesn't look correct for the square hit shape

As discussed on IRC, this is a cosmetic issue in the line damage code and nothing in urgent need of fixing.

:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/aabdc5c9b95bca254f3e548ea3a90bca96155be1...bab4da04555db1a769d70d2d33d166ad812ba5c7)

**Pull request merged**
