### PR TITLE
Prevent shellmap Chinook wobble

### LINKED ISSUE #15245: Shellmap Chinook wobbles on entry
RA: The desert-shellmap Chinook wobbles on entry. Adding +1 to the entry points will resolve it. Chinook1Entry: Location: (44,126)->(45,126) & Chinook2Entry: Location: (47,126)->(48,126)
https://github.com/OpenRA/OpenRA/blob/0fc466daee53d4e0e3c157ce023844e311644dc5/mods/ra/maps/desert-shellmap/map.yaml#L1209-L1214

### PR DESCRIPTION
**Pull request by Smittytron**
Works around an existing issue, but I think it's important to keep the shellmap as polished as possible as it's the first thing a new player will see.

Closes #15245

### CODE REVIEW

**Comment by GraionDilach** [comment]
The Travis error had nothing to do with you though.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]
We should eventually find and fix the cause for the wobble in the aircraft code, but as work-around for the shellmap this is fine.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/078bfc257f24b98d0537c262ee1627e29efcfbfe...4f4958008f0aae8d870568515f1c66269f3b6424)

**Pull request merged**
