### PR TITLE
Fixed Mono slowing down the build process

### PR DESCRIPTION
**Pull request by Mailaender**
This is just an experiment. We are already using the .NET reference assemblies so this might just work?

### CODE REVIEW

**Comment by teinarss** [comment]
Cant we wait until #17989 ? (Which will make some changes on this.)

**Comment by Mailaender** [comment]
I am an impatient person.

**Comment by deleted-user-1** [comment]
> this might just work?

No.

**Comment by Mailaender** [comment]
Actually it does build just fine. I just didn't know that .NET Core requires Mono to run .NET Framework apps: https://github.com/dotnet/sdk/pull/11883 which kinda defeats the purpose. I am not sure how to fix that `TypeLoadException` though.

**Pull request closed without merging**
