### PR TITLE
Fixed AppVeyor deployment

### PR DESCRIPTION
**Pull request by Mailaender**
This fixes the recent problem introduced in https://github.com/OpenRA/OpenRA/pull/7510 and the one I introduced in https://github.com/OpenRA/OpenRA/pull/7351 myself. This will also fix our build badge as for some reason 

``` yaml
deploy:
    on:
      branch: master
      appveyor_repo_tag: true
```

is ignored.

### CODE REVIEW

**Comment by DeadlySurprise** [comment]
Looks fine :+1:

**Comment by obrakmann** [comment]
Changes look fine, :+1: 

But looking at the whole file, I noticed that deployment is configured to only happen on the master branch, not playtest. Surely we want to change that? Reading the docs section, I got the impression that the `branch:` line can only have one value, so the whole `provider` stanza would probably need to be duplicated.

**Comment by Phrohdoh** [comment]
The commit message `yes to all` tells me absolutely nothing.
Could we get something that is actually somewhat of an explanation?

**Comment by Mailaender** [comment]
@obrakmann I removed the branch exclusiveness to also deploy playtests.

See http://www.dotnetperls.com/7-zip-examples on the `-y` switch. It currently asks "file already exists, overwrite no, yes, yes to all" etc. which is stopping and the timing out the build.

**Comment by Phrohdoh** [comment]
That isn't my problem. My issue is that reading through the git log and seeing "yes to all" is not helpful in any way.

**Comment by Mailaender** [comment]
Added an explanatory commit message.

**Comment by Phrohdoh** [comment]
This looks logical to me, though I don't know the AppVeyor configuration too well, I will trust that you and @obrakmann understand what's happening here. :+1:

**Pull request merged**
