### PR TITLE
Added map Hidden Valley

### PR DESCRIPTION
**Pull request by Mailaender**
http://resource.openra.net/maps/22844/ Simple map that should already be playable. #12518

### CODE REVIEW

**Comment by reaperrr** [comment]
I think it would be better to move up the bottom border from 188 to 186, to hide the elevated cell edges. The area loss is negligible, and it looks much better.
👍 after that.

**Comment by Mailaender** [comment]
Tweaked the lower boundaries as suggested.

**Review by reaperrr — APPROVED** [review]

**Comment by pchote** [comment]
This map has a waterfall, so depends on #13932?

**Comment by Mailaender** [comment]
It is more like the other way round. For #13932 I need more maps with test cases for waterfalls as I determine the correct offsets from in-game screenshots.

**Comment by pchote** [comment]
Ok, fair enough then.

**Pull request merged**
