### PR TITLE
Fix death sequences of Chan, Einstein, and Delphi

### LINKED ISSUE #15472: chan, einstein, and delphi have incorrect death sequences
(RA)
Chan & Einstein should be:
die1:
->Start: 120
die2:
->Start: 128
die3:
->Start: 136
die4:
->Start: 136
die5:
->Start: 148

Delphi should be:
die1:
->Start: 329
die2:
->Start: 337
die3:
->Start: 345
die4:
->Start: 345
die5:
->Start: 357

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #15472

### CODE REVIEW

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by SoScared — APPROVED** [review]
Looks good

**Review by chrisforbes — APPROVED** [review]

**Comment by chrisforbes** [comment]
What do we think about PR:For Stable on this? It's pretty low risk.

**Comment by GraionDilach** [comment]
Feel free going with that.

**Comment by reaperrr** [comment]
[changelog(https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5851d8a5172482fab9897122b5241ed89096b6cd...deb5085502cc0d74d9b19c6c97fc44414935645d)

**Pull request merged**
