### PR TITLE
Fix a NRE in DeliverUnit.ReleaseUnit.OnFirstRun

### LINKED ISSUE #19279: NRE in DeliverUnit.ReleaseUnit after player surrendered
Reported by user Evulant on the community Discord:

```
OpenRA engine version release-20210321
Dune 2000 mod version release-20210321
on map 3f0adb12512918b6f6a0a6666c117b750c589e3d (The Great Flat by Westwood Studios).
Date: 2021-03-24 22:53:21Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Activities.DeliverUnit.ReleaseUnit.OnFirstRun(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Activities.Activity.TickChild(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)
```

[d2k-2021-03-24T222912Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/6201083/d2k-2021-03-24T222912Z.orarep.zip)

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #19279.

### CODE REVIEW

**Comment by pchote** [comment]
How does that happen in practice?

**Review by Mailaender — DISMISSED** [review]
It makes sense that this could be null. `self` would probably crash due to being dead.

**Comment by pchote** [comment]
Checking the source replay confirmed my suspicion that something more subtle was happing there.

The problem is that actors may run their activity in the time after being killed but before the end-tick disposal cleanup happening (`IsDead: true`, `WillDispose: true`, `Disposed: false`). The carryall (ActorID 900) is killed at the start of the tick, and its death handler disposes `Carryable` and sets it to null. The activity then runs and crashes due to the null actor.

We have two options here:
1) Keep the `DeliverUnit` null check, but change the comment to explain this behaviour - this does fix the specific crash, but won't help with any other crashes of this type that haven't been discovered yet.
2) Add a more general `if (WillDispose) return` in `Actor.Tick` - this is a more general fix, but might cause regressions if we have any code that relied on activities ticking while being disposed.

**Comment by abcdefg30** [comment]
Updated as discussed on Discord (second push; first is a rebase): We go with 1) for now and do 2) for next+1.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5e51a9f71ad079ea21fc0f073fb2ad355de48d98

**Comment by reaperrr** [comment]
> The problem is that actors may run their activity in the time after being killed but before the end-tick disposal cleanup happening (IsDead: true, WillDispose: true, Disposed: false). The carryall (ActorID 900) is killed at the start of the tick, and its death handler disposes Carryable and sets it to null. The activity then runs and crashes due to the null actor.

As far as I can tell, the problem is that player interfaces like `INotifyWinStateChanged.OnPlayerLost` don't adhere to the implicit order that the simulation code is designed around (activities -> traits -> effects), messing up the order in which the simulation code would expect things to happen. For example by triggering `INotifyOwnerLost.OnOwnerLost` in `OwnerLostAction` before any of the activities or regular trait stuff happens.

In my opinion the most robust fix would be to simply not allow killing actors before `Actor.Tick()` at all. `OwnerLostAction` and comparable traits that implement player interfaces probably should not directly affect actors until `ITick.Tick`.

**Pull request merged**
