### PR TITLE
Fixed a crash where AI is searching for target when the squad unit is down

### LINKED ISSUE #21438: Attempted to get trait from destroyed object in SquadManagerBotModule.FindEnemies
commit 8c174551f575097f42bf747f0e78447a19a4027c

```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (scout2 3103 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.FindEnemies(IEnumerable`1 actors, Actor sourceActor)
   at OpenRA.Mods.Common.Traits.BotModules.Squads.Squad.IsTargetValid(Actor squadUnit) in OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs:line 118
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.ProtectOwn(IBot bot, Actor attacker) in OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs:line 484
   at OpenRA.Mods.Common.Traits.ModularBot.<>c__DisplayClass15_0.<OpenRA.Mods.Common.Traits.INotifyDamage.Damaged>b__0() in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 115
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Mods.Common.Traits.INotifyDamage.Damaged(Actor self, AttackInfo e) in OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 118
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in OpenRA.Mods.Common/Traits/Health.cs:line 204
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in OpenRA.Game/GameRules/WeaponInfo.cs:line 246
   at OpenRA.Mods.HV.Projectiles.EnergyBolt..ctor(ProjectileArgs args, EnergyBoltInfo info) in $HOME/Git Projects/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 147
   at OpenRA.Mods.HV.Projectiles.EnergyBoltInfo.Create(ProjectileArgs args) in $HOME/Git Projects/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass36_0.<FireBarrel>b__2(Int32 burst) in OpenRA.Mods.Common/Traits/Armament.cs:line 346
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in OpenRA.Mods.Common/Traits/Armament.cs:line 342
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in OpenRA.Mods.Common/Traits/Armament.cs:line 287
   at OpenRA.Mods.Common.Activities.Attack.DoAttack(Actor self, AttackFrontal attack, IEnumerable`1 armaments) in OpenRA.Mods.Common/Activities/Attack.cs:line 258
   at OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack) in OpenRA.Mods.Common/Activities/Attack.cs:line 251
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) in OpenRA.Mods.Common/Activities/Attack.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenRA.Launcher/Program.cs:line 32
```

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/21438

### CODE REVIEW

**Comment by RoosterDragon** [comment]
This seems supect to me. Every tick the `SquadManagerBotModule` calls into `CleanSquads`:

https://github.com/OpenRA/OpenRA/blob/0aac5885fb88cbd10256c4b9ba14dd81b8f3cc6f/OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs#L302-L307

which should have removed any dead or not in world units from the squad.

https://github.com/OpenRA/OpenRA/blob/0aac5885fb88cbd10256c4b9ba14dd81b8f3cc6f/OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs#L148

So, in theory I would expect the squad unit to always be valid. Did we ever get a replay where this was definitely not the case?

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/issues/1076 contains replays, but they don't crash.

**Comment by Mailaender** [comment]
The crash path is stemming from `IBotRespondToAttack` leading to
https://github.com/OpenRA/OpenRA/blob/0aac5885fb88cbd10256c4b9ba14dd81b8f3cc6f/OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs#L480
where I believe `CenterUnit` to be dead.

**Comment by RoosterDragon** [comment]
That seems plausible - all the other call sties are within a Tick call which should be fine, but this is the only one that comes outside of a Tick call.

Can we fix this instead by adding `protectSq.Units.RemoveWhere(unitCannotBeOrdered);` just above the line you highlighted? Once it has removed the invalid units, the existing `protectSq.IsValid` will only pass if at least one valid unit remains in the squad.

A lot of the bot code relies on the squad having valid units, so in some sense I'd rather have `IsTargetValid` continue to throw if it is ever called with a dead squad unit, so we don't mask over the issue.

**Comment by Mailaender** [comment]
I think you are right. Updated code to be in line with other squad functions.

**Review by RoosterDragon — APPROVED** [review]

**Review by PunkPun — APPROVED** [review]

**Pull request merged**
