### PR TITLE
Added TS map Tiberium Garden Redux

### PR DESCRIPTION
**Pull request by Mailaender**
Another test for https://github.com/OpenRA/OpenRA/pull/10368. This is a map that doesn't highlight the deficiencies of our TS mod (missing bridges) and should be already playable.

Source: http://ra2maps.zzattack.org/Tiberian%20Sun/index.php?dir=Official%20Multiplayer%2FTiberium%20Garden%20Redux

Description inspired by http://cnc.wikia.com/wiki/Tiberium_Garden_Redux.

### CODE REVIEW

**Comment by pchote** [comment]
The bottom border of the map is truncated, and needs to be extended by reducing the south cordon.

**Comment by Mailaender** [comment]
Corrected the bounds. Verified against FinalSun. It also makes sense as the bottom left decorational old war factory and bottom right Tiberium field is now included.

**Comment by pchote** [comment]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me, too. :+1: / :white_check_mark:

**Pull request merged**
