### PR TITLE
Add Allies05c

### PR DESCRIPTION
**Pull request by Smittytron**

### CODE REVIEW

**Comment by darcyrush** [comment]
Were there 6 SAMs in the original? Two to the top right of the prison seems excessive and the main base is on low power from the start. If so, perhaps another power plant could be added.

**Comment by Smittytron** [comment]
There were 6 SAMs in the original. The player can't build them in this mission so I've set their power consumption to 0.

**Comment by pchote** [comment]
Is that true even if the player captures enemy tech?
Should players be able to take them offline by destroying power plants?

**Comment by Smittytron** [comment]
> Is that true even if the player captures enemy tech?
> Should players be able to take them offline by destroying power plants?

Construction of SAMs is disabled in the mission's rules (Allies05a as well). Tanya has to destroy the only SAMs on the map to progress the mission to where the player gets engineers, so it's impossible at any time for the player to capture them. Also Tanya can't get past the flame tower so there's no destroying power plants before destroying the SAMs.

**Review by pchote — DISMISSED** [review]
Script looks reasonable, and I completed a playthrough on Normal without noticing any obvious issues.

**Review by reaperrr — DISMISSED** [review]

**Comment by reaperrr** [comment]
👍 , but needs a rebase now.

**Comment by Smittytron** [comment]
Rebased

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/742fda55b8c8a156ed53abc536237e4ab852f9fa...88d6a7e166c49626b36011ee2a1b9acbde87cd8a

**Pull request merged**
