### PR TITLE
pathability cost changed to ushort.

### PR DESCRIPTION
**Pull request by teinarss**
Updated the pathability cost structures to use ushort instead of int for performance improvements.

### CODE REVIEW

**Comment by Unit158** [comment]
Benchmark?

**Comment by pchote** [comment]
(I think this was the lastest one that @teinarss posted in IRC).

**Comment by teinarss** [comment]
As seen in this image just by reducing the size of GraphConnection struct to >64bits we gain around 15% performance. **PQ Current implementation** is using the GraphConenction which is using the struct which size is larger  than 64bits.
image

**Comment by GraionDilach** [comment]
Wouldn't this have the potential of causing overflows on bigger TS maps with cliffs during pathfinding? 65535/125 is 524 and 65535/177 is 370.

Maps like Final Twist - http://zombapro.ppmsite.com/maps/full/twist.jpg - might pose bigger issues on this PR than pathfindi9ng lag.

**Comment by teinarss** [comment]
I did a test with a map that should produce a path longer than 600, the map is 128x128. I had no overflows.

image

**Comment by teinarss** [comment]
Ouch, the longest path generated a cost of 65513. So we need to do this in a different way.

**Comment by pchote** [comment]
Can we define two different types, and switch to the bigger/worse one only when the cost gets too large?

**Comment by pchote** [comment]
Do we still want to move forward with this one @teinarss?

**Comment by teinarss** [comment]
Closed due to no good ideas to make this work with a good performance.

**Pull request closed without merging**
