### PR TITLE
Refactor Lua code in GDI missions

### PR DESCRIPTION
**Pull request by dtluna**
This is a refactor of Lua code of Tiberian Dawn GDI missions, a lot of the ideas are borrowed from a [similar file with global campaign functions for Dune 2k](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/bits/scripts/campaign-global.lua) 

This changeset will:
1. Add `mods/cnc/bits/scripts/campaign-global.lua` file with functions and variables that are used numerous times in missions.
1. Remove all occurances of `enemy = Player.GetPlayer("Nod")` and `player = Player.GetPlayer("GDI")` and replace all usage of `enemy` with `Nod` and `player` with `GDI` (unless it's a local variable)
1. Replace all occurances of `Map.LobbyOption("difficulty")` with the `Difficulty` variable
1. Replace the boilerplate for objectives with `InitObjectives` function
1. Remove all copies of `ReinforceWithLandingCraft`
1. Remove all copies of `CheckForBase`
1. Remove all copies of `KillCounter`
1. Change the function naming scheme from `FunctionName = function()` to `function FunctionName()`

### CODE REVIEW

**Review by Smittytron — COMMENTED** [review]
- This is tackling quite a lot. For ease of reviewing, these changes should be split into their own commits. Possibly even separate PRs for some.

-  Point 2 would be a good candidate for a separate PR. Would be easy to review. Would also close #9456. (I'd do all CnC missions if you split it though)

- A lot of these would break consistency across official mods unless we refactor all of them. I'd like an agreed upon list of which of these points we want to tackle if not all before pushing this through.

- Not sure about point 8 in particular. IMO FunctionName = function() is good for readability.

**Comment by abcdefg30** [comment]
> Not sure about point 8 in particular. IMO FunctionName = function() is good for readability.

Agree. Please drop this change.

**Comment by pchote** [comment]
@Smittytron do you want to take this over?

**Comment by Smittytron** [comment]
@pchote I can take a stab at it. At the very least I'd like to get #9456 out of this. I assume if I do this I'd just have to push a new PR? Don't think I have access to push changes on another.

**Comment by abcdefg30** [comment]
Imho this should wait for #16277.

**Comment by abcdefg30** [comment]
Superseded by #16568.

**Pull request closed without merging**
