### PR TITLE
Add sequences for the Clustermissile

### PR DESCRIPTION
**Pull request by LipkeGu**
This PR makes the Clustermissile visible, the down sequence is missing projectiles, thats why the UP and Down sequence are the same :)

### CODE REVIEW

**Comment by Mailaender** [comment]
Actually a crate icon. The original is a voxel. This is a much better placeholder though. :+1:

**Comment by LipkeGu** [comment]
mhmm then i should look for the voxel :/

**Comment by LipkeGu** [comment]
i found the Voxel, mislmlti but how can i assign it to the Missile :/

**Comment by LipkeGu** [comment]
O.O" what the f***

**Comment by pchote** [comment]
Voxel artwork isn't yet supported for missiles or other projectiles.

**Pull request closed without merging**
