### PR TITLE
Fixed incorrect D2k song installation

### PR DESCRIPTION
**Pull request by penev92**
Split out from #19143, this fixes what appears to be very old copy-pasta.

### CODE REVIEW

**Comment by pchote** [comment]
If we add this to the `TestFiles` list in mod.yaml the content manager will show the music installation as incomplete and offer to fix it, saving the player from manually deleting all the files.

**Comment by penev92** [comment]
That sounds like a dirty way of fixing it.

**Comment by reaperrr** [comment]
> That sounds like a dirty way of fixing it.

A mere changelog entry is likely to be missed by many players with existing content/music installations, though.

**Comment by penev92** [comment]
Added to the music `TestFiles`.

**Review by reaperrr — APPROVED** [review]

**Review by pchote — APPROVED** [review]
Fix confirmed

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/456375203a89552aff58c74a56d7ee29048a0833

11d84041d993ff43b02c8f9e8216819e6fa210a7

**Pull request merged**
