### PR TITLE
Fix ScreenMap handling of flipped sprites.

### LINKED ISSUE #14093: (bleed) Animations defined with FlipX in their sprite sequence are invisible.
I suspect SpacionallyPartitioned.

Note that this affects C&C and RA due to building_napalm2.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14093.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
Thanks, probably would've taken me hours to figure out the exact issue and fix.

**Comment by reaperrr** [comment]
Note to testers: One way to make this easier to test is to set `FlipX: true` or `FlipY: true` on a bunch of common explosion or building sequences in RA and watch the shellmap to see if these are still visible (just mirrored on the respective axis).

**Comment by penev92** [comment]
👍

**Review by penev92 — APPROVED** [review]
👍

**Pull request merged**
