### PR TITLE
Make `OrderGenerator` flexible on mouse input for modder

### PR DESCRIPTION
**Pull request by dnqbob**
In doing so the modder can use it for dragging mouse action or even more creative ideas.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
Ok.

**Comment by abcdefg30** [comment]
This change is so trivial that I think we can merge it without a second +1.

**Review by pchote — COMMENTED** [review]
Retrospective 👍

**Comment by dnqbob** [comment]
Then I can do my drag repair/powerdown much easier, due to this small fix.

**Pull request merged**
