### PR TITLE
Removed InitialActivity from FreeActor and Buildable

### PR DESCRIPTION
**Pull request by reaperrr**
For `Harvester`s, `FindResources` is now queued from `Created()`, provided `SearchOnCreation` is set to `true`.

### CODE REVIEW

**Comment by reaperrr** [comment]
Note: I intentionally didn't change the caching of `FindResources` here to keep the rebase of #8622 as painless as possible.

**Comment by GraionDilach** [comment]
The code looks good but untested. +0.5 from here.

**Comment by atlimit8** [comment]
I'm fine changing the harvesting activity to not use `InitialActivity`.
However, I would like to use `InitialActivity` to test YAML activity deserialization in the (near) future, after some improvements to the `FieldLoader` code.
I made some fiddly code for that months ago and would like to try again.

**Comment by atlimit8** [comment]
I'll just add it another way anyways.

**Comment by Mailaender** [comment]
:+1: This is a lot safer.

Compared to playtest-20150628 harvesters leaving the factory don't seem to start searching on their own now. Not sure what is going on there.

**Comment by reaperrr** [comment]
> Compared to playtest-20150628 harvesters leaving the factory don't seem to start searching on their own now. Not sure what is going on there.

Hm, that's not how it's supposed to be. I'll take a look tomorrow.

**Comment by reaperrr** [comment]
Updated, should now work with factory-produced harvesters, too.

**Comment by obrakmann** [comment]
It does. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/85855196a6bf988cd6fb0cf45e1c64b17fe6ee45%5E...85855196a6bf988cd6fb0cf45e1c64b17fe6ee45)

**Pull request merged**
