### PR TITLE
Add trait GrantConditionOnLowPower

### PR DESCRIPTION
**Pull request by jrb0001**

### CODE REVIEW

**Comment by pchote** [comment]
This should be integrated with or replace `RequiresPower` to align with #7807.

**Comment by jrb0001** [comment]
I will do changes to the trait itself but I won't investigate the side effects of removing any IDisable related traits. If you insist on that, then @reaperrr should merge it into his work and finish it.

**Comment by pchote** [comment]
Adding the condition granting to `RequiresPower` would be the safest and simplest approach here then.

**Comment by jrb0001** [comment]
No, this wouldn't help in my usecase because the IDisable logic still applies then.

**Comment by pchote** [comment]
Ok, then best to either wait for or help @reaperrr progress his branch to a mergable PR.

**Comment by jrb0001** [comment]
Should be doable with https://github.com/OpenRA/OpenRA/pull/13998.

**Pull request closed without merging**
