### PR TITLE
Isometric selection corners and bars

### PR DESCRIPTION
**Pull request by Mistranger**
Just as the title says:
openra-2017-06-02t093604102z

Will work only on RectangularIsometric grid type.
New fields to SelectionDecorations trait:
bool Isometric - switch between rectangular and isometric styles.
float IsometricHeight - selection height in pixels
The rules should be updated from art.ini to include Height parameter (currently it uses one value for all buildings)

### CODE REVIEW

**Review by pchote — CHANGES_REQUESTED** [review]
Adding this as an option to the existing selection boxes conflicts with our goal of having separate traits and renderables that can be switched between at the mod yaml level.

Please start by separating the isometric parts of the renderables into their own `IsometricSelectionBoxRenderable` and `IsometricSelectionBarRenderable`, and then have the WorldInteractionController ask the trait to draw the rollover so that it doesn't need to know about the implementation details.

**Comment by pchote** [comment]
I'm hoping to rework some of the low level selection plumbing for Next + 1 so that we can support arbitrary mod-defined selection boxes, and also non-rectangular clickable regions.  The idea is that then lets us take this with many less hacks and workarounds.

**Comment by reaperrr** [comment]
> I'm hoping to rework some of the low level selection plumbing for Next + 1 so that we can support arbitrary mod-defined selection boxes, and also non-rectangular clickable regions. The idea is that then lets us take this with many less hacks and workarounds.

Since it's hard to tell when that will happen and how much this PR would then have to be rewritten to work with that plumbing, I'm closing this to tidy up the PR queue for now. Feel free to reopen or re-file once the prerequisites are merged and the PR has been adapted.

**Comment by pchote** [comment]
Note that the rework I mentioned is currently blocked on #13899.

**Pull request closed without merging**
