### PR TITLE
Prevent civilians from spawning alongside crates

### LINKED ISSUE #16790: Red Alert Soviet Campaign mission 1
Blew the church up with my infantry. Civilian came out of the church of which blew up. Civilian picked up the crate himself and healed the pillboxes at the bridge.

I was in tears in laughing from this.

Might need to remove civilians from churches or other buildings which would give crates in case this happens.

### LINKED ISSUE #17802: Civilians pick up health and money crates that are meant for the player
DESCRIPTION
Civilians that spawn after you destroy houses will pick up the health crates spawned from it.
This is most notable in Red Alert Soviet Mission 3.

EXPECTED BEHAVIOR
Only the players units should be able to pick up crates in missions.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #16790.
Closes #17802.

### CODE REVIEW

**Comment by pchote** [comment]
It would be cleaner to disable these for all missions in campaign-rules.yaml.

**Comment by abcdefg30** [comment]
I considered that but disagree since we have a lot of missions that don't use spawning for churches, and the other missions set the spawning manually. Additionally this doesn't look to be limited to churches, which means we'd need to do mission specific overrides again.

**Comment by pchote** [comment]
Why do churches need to spawn infantry in *any* mission?

**Comment by abcdefg30** [comment]
They don't need to. No building needs to in theory. IIrc this feature was added to make destroying villages more vivid, which it imho achieves.

**Comment by Smittytron** [comment]
A thing I've noticed from Remastered is there were multiple instances of civilians fleeing buildings with an `OnDamaged `trigger. A compromise here could be to remove spawning on death, and placing `OnDamaged `triggers on certain buildings in the campaign, such as I do in #18124. This is a good place to use the new `Panic `function.

A somewhat sinister idea: On Soviet 03 you chase the spy into a village where he is picked up and moved by an Allied transport. We could have some civilians leave the houses and follow him to the beach. When he gets in the transport takes off without them they `Panic`. I might just have to write that one up.

**Comment by abcdefg30** [comment]
I'm planning on going a different route.

**Comment by Smittytron** [comment]
Two more reasons I've come across for disabling civilian spawns in campaign-rules:

- There are a couple missions where the player is supposed to evacuate all civilians from a village, and the village is attacked after the civilians leave. If civilians spawn from destroyed buildings that would imply some were left behind.
- The player is supposed to destroy all civilians in the mission Shock Therapy. Here it's easy for a player to destroy a civilian structure on the edge of fog of war, and for them to not catch the spawned civilian. Removing civ spawn here will prevent a situation where the player is canvassing the map at the end of the mission to find what they missed.

From playing Remasters it seems civilians spawned from destroyed buildings in TD but not in RA. If we do need civilians to spawn in RA it could be scripted.

I'll PR this if we have consensus.

**Pull request closed without merging**
