### PR TITLE
Updated year numbers in all files

### PR DESCRIPTION
**Pull request by abcdefg30**
Hope, I didn't miss something.

Should I squash the commits?

### CODE REVIEW

**Comment by Phrohdoh** [comment]
I'd say squash them as they aren't logic changes that could cause regressions.

:+1:

**Comment by abcdefg30** [comment]
Squashed.

**Comment by huwpascoe** [comment]
:+1:

**Comment by Phrohdoh** [comment]
No changelog entry necessary, thanks!

**Pull request merged**
