### PR TITLE
Add support for loading mods from `oramod` packages.

### PR DESCRIPTION
**Pull request by pchote**
After months of preparations, this adds the final few pieces to enable support for parsing packaged mods from the system or support mod directories.

Depends on #10838.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Oops, sorry!
Those comments belong on #10838.

**Comment by pchote** [comment]
Rebased and ready for review.  Suggested test case: compress one of our default mods, which will work without any additional changes.

**Comment by penev92** [comment]
:+1:

**Comment by obrakmann** [comment]
Looks ok to me :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/5f5e6e9b45eab0bdbd68e29cc0d9f6a059a33576)

**Comment by pchote** [comment]
This one is important enough to justify its own changelog entry, IMO.

**Comment by penev92** [comment]
Definitely.

**Comment by obrakmann** [comment]
Well then: [Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/d4778eb461fb9c59eb99a711ad0151b519eec672...c4e1ab43e44df23bc425ace06b3952b3f7b457fc)

**Pull request merged**
