### PR TITLE
Add the ability for all remaining RA infantry to attack when garrisoned

### PR DESCRIPTION
**Pull request by PunkPun**
This is mostly a way overdue consistency change, it shouldn't have a any significant bearing on balance. It adds the ability to fire from a pillbox to Spy, Technician, and for Rocket Soldier to fire at air targets

### CODE REVIEW

**Comment by pchote** [comment]
IMO it feels weird and wrong for medic and mechanic to be able to heal/repair things through the walls of a pillbox.

The spy pistol is a hidden manually targetable extra that rewards explicit micromanagement. Having the spy turn basically into a combat sniper when placed in a pillbox also feels wrong, IMO.

**Comment by PunkPun** [comment]
> The spy pistol is a hidden manually targetable extra that rewards explicit micromanagement. Having the spy turn basically into a combat sniper when placed in a pillbox also feels wrong, IMO.

Spy still keeps his low weapon range. So not really a sniper. Units when garrisoned use the exact same weapons as they use normally, with riflemen being an exception.

> IMO it feels weird and wrong for medic and mechanic to be able to heal/repair things through a concrete wall.

I don't know how widespread the medic/mechanic emersion issue is. To me it just feels lame that medics and mechanics don't work in a pillbox, even though they normally have range. But I'd be willing to compromise if more people feel the same as you

**Comment by PunkPun** [comment]
I'd imagine that if we wanted medics and mechanics to be immersive we would change their design to have 1 / 1.5 cell range instead of the current 4

**Comment by pchote** [comment]
> Units when garrisoned use the exact same weapons as they use normally

My point was that the spy *doesn't* use its pistol normally, only when manually force-fired.

**Comment by PunkPun** [comment]
Or when his stance is changed, and pillbox changes his stance

**Comment by deleted-user-1** [comment]
Don't like the idea of pillbox-repair-bays or pillbox-healing-stations and I'm sure we'd see those. Although medics and mechanics do attack on a technical-level, they do not on "what a player expects and the game tells you"-level, simply because they're not armed with actual weapons and they can not attack enemies. So this is not inconsistent IMO. I can behind the logic that everything what shows by default an attack cursor when hovering over enemies can enter a pillbox and fire from within it. Other infantry may be placed in pillboxes to take cover or alternatively make #13449 a won't-fix (for the RA mod!)  and don't allow them to enter at all. This would also address the complaint about inconsistency in this issue.

**Comment by PunkPun** [comment]
Removed the ability from medic and mechanic to heal / repair within pillboxes

> Don't like the idea of pillbox-repair-bays or pillbox-healing-stations and I'm sure we'd see those

People don't make healing stations currently, so I doubt that they will make more expensive and immobile ones

**Comment by matjaeck** [comment]
Immobile ones are somewhat attractive because it makes micro easier because you don't have to care about (not) selecting them. Like cheap service depots with AOE.

**Comment by matjaeck** [comment]
> Immobile ones are somewhat attractive because it makes micro easier because you don't have to care about (not) selecting them. Like cheap service depots with AOE.

Actually, scratch that and the other comment. I had yet again forgotten about https://github.com/OpenRA/OpenRA/pull/18236#issuecomment-643824576, but it's fixed now.

**Comment by deleted-user-1** [comment]
Since this healing/repairing was again requested in #18845 it could help to get some other opinions on this (not my, hence I removed some of my last comments and don't really want my earlier comments to have any effect on this decision). I could imagine people asking in the future why these units can enter but not do anything.

**Comment by Smittytron** [comment]
I don't think any change is needed here. If 'inconsistency' is too big of a complaint then it makes much more sense to remove the passenger slot from pillboxes.

**Comment by pchote** [comment]
The discussion above seems to have run its course without much visible support for these changes. I think it would be best if this goes back into the pool of community discussion until there's enough support to show that the opposition here was a vocal minority, or wait until a more general rework of Spies makes my specific complaints above moot.

**Comment by PunkPun** [comment]
Well, on that case can the technician and rocket soldier changes get merged? There wasn't any opposition to them. 

PS I currently and in the near future am not able to rebase or create pr's

**Pull request closed without merging**
