### PR TITLE
Those trait should work only when in world as well

### PR DESCRIPTION
**Pull request by dnqbob**

### CODE REVIEW

**Review by RoosterDragon — APPROVED** [review]

**Comment by Mailaender** [comment]
I think this is redundant because `ITick` is invoked in `World` and only for actors in world. I also didn't notice any rendering changes for the Red Alert crate drop plane. It will stop rendering trails here and on bleed when leaving the map.

**Review by PunkPun — APPROVED** [review]
LGTM, though the trails still act incorrectly when a unit is exiting a transport. The first trail is placed where the unit entered the transport rather than its current position where it is exiting

**Comment by PunkPun** [comment]
@Mailaender this fixes a visual glitch where when a carryall would pickup a damaged harvester the smoke would remain on the ground in the position the harvester was picked from

**Comment by dnqbob** [comment]
>  also didn't notice any rendering changes for the Red Alert crate drop plane

@Mailaender The `LeavesTrails` is not `Contrail`, I guess you mean `Contrail` but it is not fixed in this PR.

**Comment by dnqbob** [comment]
> I think this is redundant because ITick is invoked in World and only for actors in world.

ITick still run for those not in world.
bug

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/833263122fb0c39c27e14337370a994df2a5c072...3fc790efc75cf05945479731a613cb1c464bde53)

**Pull request merged**
