### PR TITLE
Hardcode mod logo and preview image file names

### PR DESCRIPTION
**Pull request by penev92**
Fixes a oversight on my part. I had said I'd remove those, but forgot.
See https://github.com/OpenRA/OpenRA/pull/10232#commitcomment-15368566 (some of the discussion is probably on IRC though :/ )

### CODE REVIEW

**Comment by pchote** [comment]
The reasoning behind hardcoding these is that we need to guarantee that they are present (for both the mod chooser and external tools like the resource site or OS shell integration), and not referencing a file from another mod package.  This is the same strategy that we use for mod/map.yaml, map.png, etc.

**Comment by Phrohdoh** [comment]
Code looks good and I agree that some paths absolutely need to be consistent/hardcoded. :+1:

**Comment by pchote** [comment]
Confirmed that the images still work ingame :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/9db100230f2db9b4e5105505748bb4366f1d1b80

**Pull request merged**
