### PR TITLE
D2K - Fix Carryalls can't land on Concrete

### LINKED ISSUE #12479: ReinforceWithTransport doesn't work on Concrete tiles
another Bug with the ReinforceWithTransport LUA function: Transports called in with this function can't land on top of concrete tiles. see picture.
carryallbug
See also [other issues](https://github.com/OpenRA/OpenRA/issues/12464).
Cheers,
     SirCake

### PR DESCRIPTION
**Pull request by MustaphaTR**
Fixes #12479.

https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/tilesets/arrakis.yaml#L19

https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/tilesets/arrakis.yaml#L936

### CODE REVIEW

**Comment by ltem** [comment]
:+1: 
it tested it with the map of @CH4Code [LINK](http://resource.openra.net/maps/17843/) (if you upgrade the outpost you get a carryall reinforcement ability)

Concrete Drop
:----------:
openra-2017-01-22t195904228z

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/359300071cce73138f6dc7f1fc1bda621a8d25b1)

**Comment by CH4Code** [comment]
👍 Thanks, man :) Didn't think it was a fix this easy ^^ One only needs to know which screw to drive...

**Pull request merged**
