### PR TITLE
Unit stance decoration

### PR DESCRIPTION
**Pull request by atlimit8**
This at least lays the ground work for visualizing unit stances of selected actors. Part of the problem is balancing the size of the indicators between easily identified and non-obtrusive. At the very least, a few commits should be removed before merging. The mod I am having the most trouble with is the d2k mod since I am not sure how to add the graphics for that mod.

### CODE REVIEW

**Comment by CH4Code** [comment]
You can include tmptd format files. I use shp(td) (using the d2k palette) all the time for including custom units in d2k. 
Worth noting: In the far future that will be removed again, so if you can manage to include it in .R8 format, that would be even better.
If you dont know how to do it, I'll gladly help (in case of d2k).

**Comment by atlimit8** [comment]
@CH4Code, I used Open Source SHP Builder for the graphics and I found the d2k palette, but I have not found a way of converting to r8.

**Comment by reaperrr** [comment]
@atlimit8 I don't think there are any .r8 encoders in the  community, use ShpTD instead (we already use that for all custom sprites in D2k).

**Comment by CH4Code** [comment]
It might throw an error saving as ShpTD - my version of SHP builder scews the shptd format up, so that openRA throws an error. Save instead as ShpTS and convert with XCC Utilities to .png->ShpTD. Thats what I allways do. 
I don't know a way to convert to .R8 either.. ^^

**Comment by reaperrr** [comment]
Pinging @GraionDilach , iirc the newest version of OS SHP Builder is able to save shp(td) properly with the right setting, but I don't remember what it was.

**Comment by GraionDilach** [comment]
I don't remember if the SHP Builder with the SHPTDfix was released as a stable but certainly the following applies to the last betas: in order to save the SHP properly as SHP(TD) you have to select the SHP type to be TD or RA1 BEFORE you save the file as SHP(TD).

**Comment by MartinCurwen** [comment]
Just throwing an idea out there but if you find that the icons become cluttered especially with infantry, could you not just colour code the selection box around units to inform the player of the stance. Eg: white normal, red holdfire, yellow return fire?

**Comment by pchote** [comment]
I really don't like the idea of using only color to distinguish between different stances - either in a pip, like it is now, or on the selection box.  The indicators should have an intutive connection to the thing they are indicating.

**Comment by pchote** [comment]
> The mod I am having the most trouble with is the d2k mod since I am not sure how to add the graphics for that mod.

You can use XCC mixer to convert png to Shp(TD) sprites that will work in D2K.

**Comment by atlimit8** [comment]
Any ideas for the icons to use for the stances?

**Comment by CH4Code** [comment]
The symbols would have to be cross mod and even cross-genre, so they fit scifi as well as medival age stratgames, so no guns and such.
What about a stylized green shield for defend ([like this without wings](https://image.freepik.com/freie-ikonen/geflugelten-schild_318-63578.jpg)),
a stylized white dove for hold fire ([like this](http://www.ds-dan.de/images/product_images/info_images/307_0.jpg)),
a stylized single yellow saber pointed straight down (blade outward) for return fire,
and a sylized red crossed double saber ([like this](https://image.spreadshirtmedia.net/image-server/v1/compositions/130775528/views/1,width=300,height=300,appearanceId=39,version=1472099537/gekreuzten-degen-saebel-240630-t-shirts-maenner-premium-t-shirt.jpg)) for attack anything?
The art referenced might be copyrighted.
(Assuming the symbol will be displayed in the top right corner of the selection box)

**Comment by pchote** [comment]
I suggest looking at what generals/tiberium wars/RA3 did.  There is no need for us to do anything new here.

**Comment by CH4Code** [comment]
But in general I disagree with pchote and would perfer the minimal UI solution. 
Using symbols on every single unit would clutter up the screen too much, since the units themselves are only a few pixels.
If the symbol for the currently selected group was displayed below the build menu, that would be much better, and allow it to be bigger and have explaining text below it.

**Comment by pchote** [comment]
Which part do you disagree with? That indicators should be related to the thing they are indicating, or that the later C&C games didn't solve this well enough?

**Comment by CH4Code** [comment]
realy, in c&c3 I only used hold position on venoms, when I wanted to make a chain of them to use the laser reflector. Imho ALL the cnc games did a bad job with the stances, the menue in RA3 I think was a roll out menue with tiny buttons. Basicaly you had to learn the hotkey. In openRA I only think of stances with dogs(instant hotkey x 1) and subs (instant hotkey x 3) and forget about it afterwards.

Im not sure if the cycling solution of openRA is better, opposed to setting a fixed stance on a hotkey. No rts I know displays the stance with the actor however. It is not that important. Most the time it is part of the general UI, mixed button/display. So i disagree that there should be symbols on the actors. too much clutter.
If we want to be avant-garde with this it has to be very subtle. 
OR put those symbols into the side menue somehow, current stance highlighted, click-able, like most rts do. I hope this was clear..

**Comment by GraionDilach** [comment]
>The symbols would have to be cross mod and even cross-genre

If they are decorations then they don't, because decorations are replaceable by the modder.

I don't remember RA2 having stances. Area Guarding is the closest thing I can think of and that had no visual feedback from the unit.

I also prefer the colored selection box method because of the less UI clutter, tbh. I am fine with introducing decorations in the main mods though, as long as you promise you wouldn't object another PR introducing the selectioncolorstances.

**Comment by pchote** [comment]
We are already planning to finish implementing the unit stance logic in the immediate future to go along with the building TargetableLocations change, so IMO the most reasonable way forward here is to go all the way and implement the stance selection UI from the later games.  This then naturally wraps up the planned work.

e.g. from C&C3:
screen shot 2017-05-26 at 18 37 56

The four right-most buttons map to HoldFire / ReturnFire / Defend / AttackAnything, and are highlighted based on the stances of the selected units.

This is another very-long planned feature (e.g. #3789 and linked tickets) that has never gone anywhere mainly because people wanted to scope-creep it into a dynamic order palette.  I'm suggesting that we officially give up on that idea, and instead duplicate the fixed C&C3 bar with a fixed layout having buttons for our three primary order generators (move, attack-move, guard) and the four stance buttons.

**Comment by atlimit8** [comment]
Maybe this will be revisited.

**Comment by GraionDilach** [comment]
> This is another very-long planned feature (e.g. #3789 and linked tickets) that has never gone anywhere mainly because people wanted to scope-creep it into a dynamic order palette. I'm suggesting that we officially give up on that idea, and instead duplicate the fixed C&C3 bar with buttons for our three primary order generators (force-move, attack-move, guard) and the four stances.

Stuff like an attack ground option will be needed longterm - see the discussion in #11663. This sounds like another made-up issue like "fragile alliances are wrong".

**Pull request closed without merging**
