### PR TITLE
Added the Tiberium active overlay animation

### PR DESCRIPTION
**Pull request by Mailaender**
blowing spores in the air.

### CODE REVIEW

**Comment by reaperrr** [comment]
In both TD and TS, this animation actually only played when the tib tree actually tried to spawn tiberium, it wasn't just independent cosmetics.
Not a blocker, but something to consider.

**Comment by GraionDilach** [comment]
Why does this need an additional trait? Just asking of the difference.

**Comment by reaperrr** [comment]
Animations replace the body, overlays are added on top.

**Comment by GraionDilach** [comment]
Ah, right.

**Comment by pchote** [comment]
I agree with both @reaperrr and @GraionDilach.  The Interval property could be added to `WithIdleOverlay` to avoid unnecessary duplication.

**Comment by Mailaender** [comment]
They were talking about `WithActiveAnimation` and `WithActiveOverlay` though.

**Comment by reaperrr** [comment]
Yes, but generally speaking, the most logical solution would be to add `Interval` to `Idle` anims/overlays (defaulting to 0, of course) so it's usable by any kind of actor, and introduce `WithResourceSpawnAnimation`/-`Overlay` triggered whenever the actor spawns a resource, with a minimum delay property to avoid anims playing every 55 ticks.

**Comment by Mailaender** [comment]
I don't think this kind of feature creep demand is fair on this pull request.

**Comment by pchote** [comment]
Its not really a feature creep, as far as I can see.  There have been two major points, which are largely separate but both apply to your original implementation instead of asking for new things:

* Adding a generic `WithActiveOverlay` is redundant, as this duplicates the existing `WithIdleOverlay` trait.  The only difference is the `Interval` property, which can be added to `WithActiveAnimation` instead.
* In any case, its not correct to use either `WithActiveOverlay` or `WithIdleOverlay` for tiberium trees, because they should only animate when spawning.  To make this work as it should you would need to introduce a new interface, and then rename your generic `WithActiveOverlay` to a more specific `WithResourceSeedingOverlay` that implements the interface.

**Comment by penev92** [comment]
This hasn't seen any activity in almost a month and a half.
I don't know if `WithActiveOverlay` would be useful or not, but I do agree with the `WithResourceSeedingOverlay` part.
If this is a #wontfix then we should close this.

**Comment by Mailaender** [comment]
This can be consolidated later. The behavioral changes are also out of scope of this pull request.

**Comment by pchote** [comment]
The conservative option may be to close this for now, and then somebody else can revisit either the `WithResourceSeedingOverlay` trait or adding an `Interval` parameter to `WithIdleOverlay` in the future.

**Comment by Mailaender** [comment]
I merged `WithActiveOverlay` into `WithIdleOverlay` although I don't think it is a good idea to have every idle overlay tick for performance reasons.

**Comment by pchote** [comment]
It may be better to go with the `WithResourceSeedingOverlay` approach in that case.

**Comment by abcdefg30** [comment]
Needs a rebase.

**Comment by Mailaender** [comment]
Too many cooks...

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/commit/8ce274ed791f19e81745509afd31d0143dbbe5b1 and https://github.com/OpenRA/OpenRA/pull/11297.

**Pull request closed without merging**
