### PR TITLE
Happy New Year 2017, everyone!

### PR DESCRIPTION
**Pull request by phrohdoh**
Here's to another year of OpenRA! :-)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I'd very much appreciate it if you could touch exactly 200 more lines :P

**Comment by reaperrr** [comment]
Happy new year 👍

**Comment by Phrohdoh** [comment]
I just realized this marks a decade of OpenRA, that is awesome.

**Comment by Micr0Bit** [comment]
@Phrohdoh : according to @pchote,  the more precise mark should be middle of the year

**Comment by pchote** [comment]
Specifically b59ba43934a3a6837410db51cf60157cf854e52d.

**Pull request merged**
