### PR TITLE
Makes only concrete walls block fire

### LINKED ISSUE #9320: Firing over barbed wire and sandbags
In the original games, I believe units could fire over barbed wire and sandbags, but that it would block the paths of light vehicles and infantry.

In oRA, these seem to block projectiles too, making them more like cheap weak walls. I think it would be  more interesting to allow units to shoot through them but still block the paths of light vehicles and infantry.

That is unless it is actually a ray-caster issue that these units can't fire over them?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26618699-firing-over-barbed-wire-and-sandbags?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
And clean up TS `^Wall` default.

Closes #9320.

### CODE REVIEW

**Comment by Mailaender** [comment]
You will also need to adapt the descriptions in
* https://github.com/OpenRA/OpenRA/pull/9339/files#diff-83e2e01e165e3b565b57237ce194b720R1497
* https://github.com/OpenRA/OpenRA/pull/9339/files#diff-83e2e01e165e3b565b57237ce194b720R1522

**Comment by reaperrr** [comment]
Updated.

**Comment by Phrohdoh** [comment]
What is the inspiration behind this?
The community or some discussion over IRC?

**Comment by reaperrr** [comment]
As mentioned above, #9320 and the fact that this matches the behavior in the original games.

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
Looks good, and makes a lot of sense :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/1499304129624af3c97ed3af1ecfbbd484391c81

**Pull request merged**
