### PR TITLE
Make Beacon arrow and circle sequences loop

### LINKED ISSUE #16436: Beacon circle animations don't loop on support powers
The circle animation is only played once.

While this was apparently originally intentional, I feel it looks a bit weird/buggy.

In my opinion the circle anim should loop for support power beacons as well.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes circle anim in RA/TD and allows animated arrows.

Closes #16436.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks nice and I find it with these changes easier to tell to which player(color) a beacon belongs. I think the circle and arrow animation are not perfectly synced, but fixing this is probably not within the scope of this PR.

**Comment by abcdefg30** [comment]
Isn't `circles` now the same as `beacon`?

**Comment by pchote** [comment]
The circles animating only once was originally intentional, and is what makes the distinct from `beacon`.

**Comment by matjaeck** [comment]
Dismissing the review because I can't say anything to the raised questions.

**Comment by reaperrr** [comment]
OK, I thought it was a bug. I'll close this for now, but leave the issue open since it looks a bit weird for the circles to animate once and then stop.

**Pull request closed without merging**
