### PR TITLE
Separated SelectionSize and ScreenMap Bounds

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/11115.

### CODE REVIEW

**Comment by pchote** [comment]
Doesn't this conflict with #13899?

**Comment by Mailaender** [comment]
Yes, it is a bit uncoordinated here as I didn't know about those plans. It seems to address a different issue though. `Selectable` and `SelectionDecorations` conflicting I assume. Something I didn't touch here.

My pull request fixes `AutoSelectionSize` not taking all `RenderSprites` animations (overlays) into account. The most important change is hidden in the diff as I implemented as an addition. See https://gist.github.com/Mailaender/da2a3f04e971aea57fd30ad492abcc92/revisions

We need to agree on calling it `RenderBounds` or `ScreenMapBounds` and one person has to rebase his pull request.

**Comment by pchote** [comment]
@reaperrr will need to clarify, but to me that one sounds like it is supposed to solve the same issue:
> This step was necessary to prevent actors with selectable area smaller than their graphics to be removed too early from ScreenMap even though part of the graphics should still be visible.

I don't had time to take more than a glance at the code of either PR, but on the face of things #13899 looks like it fits with my plans for generalizing the selection regions to support arbitrary polygons, which we need for isometric selection boxes.

**Comment by reaperrr** [comment]
> It seems to address a different issue though. Selectable and SelectionDecorations conflicting I assume. Something I didn't touch here.

No, like @pchote said it's aiming at the same thing, only my PR doesn't fix `AutoSelectionSize not taking all RenderSprites animations (overlays) into account` yet (I was planning that for a follow-up, but haven't coded anything yet), I only separated Selectable bounds and ScreenMap/Render bounds.

Basically your PR takes things one step further than mine, so I guess it makes sense to stick with yours for now and re-purpose mine to just renaming and maybe the fall-backs I added.

About `ScreenMap` vs. `Render`, I guess it doesn't matter much, but those bounds might be used by more than just `ScreenMap` culling (fallback for Visual/SelectionOverlayBounds, for example), and they *do* represent the bounds around the actor that is *rendered* in any case, regardless of the ScreenMap. So both may be essentially correct, but `Render` is more likely to *stay* correct, in my opinion.

**Comment by pchote** [comment]
No, please lets do the opposite.  #13899 lines up perfectly with the selection changes that I have been planning for ages, so it would be better to get that in first and then adapt this PR to add the rest.

**Comment by Mailaender** [comment]
I am okay with that. Let's take #13899 first and let me try to rebase.

**Comment by penev92** [comment]
#13899 was merged, so this needs to be rebased.

**Comment by penev92** [comment]
It has been a while, and while I'd prefer @Mailaender came back to finish this, at some point @reaperrr will have to take over, since this is closely tied to his ongoing refactoring.

**Comment by reaperrr** [comment]
I've locally rebased and updated the part that might be useful and will file a PR after #14398 is finished and merged.

**Comment by penev92** [comment]
#14398 was merged.

**Pull request closed without merging**
