### PR TITLE
Remove global chat integration.

### PR DESCRIPTION
**Pull request by pchote**
A lot has been said and done over the years to try and encourage the global chat as a community service, but the facts are that it remains mostly unused and most of the use it *does* get is counter to our community code of conduct and basic respect.

The [vast majority of messages in the channel](https://ingame.logs.openra.net/) are one of:
* Spamming ]games
* Insulting players and/or developers
* Spamming jibberish to make orabot kick themselves

There are occasional support requests (usually how to handle port forwarding), but these often go unanswered.  There are usually a few "normal" messages each day ("join server x", etc), but this usage really can't justify keeping what has become a hub of antisocial and unwanted (in at least my opinion) behaviour.  There has been little enthusiasm about trying to moderate the channel, and I do not believe that to be worth the effort even if we could find enough volunteers.

This PR removes all global chat integration.  If it is merged then I would like to think that somebody can work on a couple of followups to help address the other usecases of the global chat:
* Exposing the vestigial client list that is included in the master server data in a bin below the map preview in the server browser (the full plan of exposing spawn points and teams is be too much).
* Exposing the server list in some form as a tab from the MP game lobby, like global chat is now.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]
:cry:

**Comment by CH4Code** [comment]
Damn, probably 50% of fresh recruits for d2k Thursday came from that :/

**Comment by Arular101** [comment]
I think it's fine to remove this feature. I've seen some other games that removed this too because of abuse in different ways.

> Damn, probably 50% of fresh recruits for d2k Thursday came from that :/

Maybe you can use the OpenRA Facebook or Reddit to get more people.

**Comment by pchote** [comment]
> Maybe you can use the OpenRA Facebook or Reddit to get more people.

D2K Thursday and similar events are definitely the kind of thing we should be advertising more on social media.

**Review by penev92 — COMMENTED** [review]
There is still a mention of `SmartIrc4Net` in `AUTHORS`

**Comment by Mailaender** [comment]
👍 though I am frustrated as well if we count the man hours @ScottNZ, myself and countless other contributors put into the feature. From a technical standpoint we also have to get rid of the outdated NuGet dependency: https://github.com/meebey/SmartIrc4net/issues/33

**Comment by pchote** [comment]
Updated.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/71f01e471480d4c6f68c4da3dd77ab260c45aa25...ccf9c0016b9da42632ade4a9626cfa34d4a82660)

**Comment by Mailaender** [comment]
> D2K Thursday and similar events are definitely the kind of thing we should be advertising more on social media.

Done.

**Comment by pchote** [comment]
Followup PRs to restore the useful functionality from the chat:
* Display who is playing in each server: #14571, #14591, https://github.com/OpenRA/OpenRAMasterServer/pull/41, https://github.com/OpenRA/OpenRAMasterServer/pull/42, https://github.com/OpenRA/OpenRAMasterServer/pull/43, https://github.com/OpenRA/OpenRAMasterServer/pull/44.
* Display outdated/invalid version warnings: #14581, #14596, https://github.com/OpenRA/OpenRAWeb/pull/369, https://github.com/OpenRA/OpenRAMasterServer/pull/50.
* View server status without leaving the current game: #14599.

**Pull request merged**
