### PR TITLE
Don’t create multiple sound contexts.

### LINKED ISSUE #9271: Crash when switching mods for second time
This happens in bleed build

Full exception:
```
 Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Can't create OpenAL context
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\OpenAlSoundEngine.cs:line 102
   at OpenRA.Platforms.Default.DeviceFactory.CreateSound() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\DefaultPlatform.cs:line 29
   at OpenRA.Sound.CreateDevice(Assembly platformDll) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:line 37
   at OpenRA.Sound.Initialize(String engineName) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:line 72
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 278
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass23.<LoadMod>b__22()
   at System.Action.Invoke()
   at OpenRA.Primitives.ActionQueue.PerformActions() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 43
   at OpenRA.Game.LogicTick() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 487
   at OpenRA.Game.Loop() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 619
   at OpenRA.Game.Run() in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 659
   at OpenRA.Program.Run(String[] args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in c:\Users\Alvar\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 39
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26472943-crash-when-switching-mods-for-second-time?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9271, which was a regression introduced by #8632.

### CODE REVIEW

**Comment by pchote** [comment]
```
18:30 < pchote> gwass: can you please try compiling 
                https://github.com/pchote/OpenRA/archive/fix-sound-engine.zip
8:35 < gwass> pchote: Mod switching works finee, I didn't try music downloading, but 
               I assume it was exact same bug considering exception was identical
18:35 < pchote> yeah
18:35 < gwass> Nice work
18:35 < pchote> great, thanks
```

**Comment by pchote** [comment]
I have a potential followup pr waiting at 7299522bcf26cb08b75109ce1af02c1aa8f4bdbe, which makes the sound engine work more like our renderer.

**Comment by penev92** [comment]
Looks quite reasonable :+1:

**Comment by Mailaender** [comment]
Thanks for the quick fix!

**Pull request merged**
