### PR TITLE
Official Map Pool: Alter 21 maps' player spawns (letter order) and ore mines for minimap exposure.

### PR DESCRIPTION
**Pull request by SoScared**
I went through the map pool and picked up a few maps that currently is unlikely to be affected by any change in the official map pool (e.g. #11143). It's just a reorganizing of the player spawns' letters (and some minor adjustments) that are mostly aesthetic but will make it easier for players to set up teams in the lobby.

Most of the erroneous player spawns are due to a bug (fixed in the next playtest/release - #11125) in the editor that sometimes scrambles the order of the letters when saving/exiting, or possibly old maps that was made before letters were introduced to the spawns. Regardless, here are some fixes:

**Forest Path**: http://resource.openra.net/maps/15209/
forest path compare

**Bad Neighbors**: http://resource.openra.net/maps/15207/
bad neighbors compare

**Mad Science**: http://resource.openra.net/maps/15211/
mad science compare

**Puddles Redux**: http://resource.openra.net/maps/15215/
puddles redux compare

**Poland Raid**: http://resource.openra.net/maps/15212/
poland raid compare

**Haos Ridges**: http://resource.openra.net/maps/15210/
haos ridges compare

**Vegetation**: http://resource.openra.net/maps/15239/
vegetation compare

**A Path Beyond**: http://resource.openra.net/maps/15206/
a path beyond compare

**All Connected**: http://resource.openra.net/maps/15205/
all connected compare

**Caffeinated**: http://resource.openra.net/maps/15208/
caffeinated compare

**Pressure**: http://resource.openra.net/maps/15214/
pressure compare

**Regeneration Basin**: http://resource.openra.net/maps/15216/
regeneration basin compare

**Pool Party**: http://resource.openra.net/maps/15213/
pool party compare

### CODE REVIEW

**Comment by SoScared** [comment]
Part of #11690 

I'll be moving forward with the rest of the maps but it's my first pull request so - starting small :)

**Comment by Mailaender** [comment]
First pull request! :balloon:  Hooray! :raised_hands:

**Comment by SoScared** [comment]
Ah ok so adding commits will add on to any ongoing pull request.

The last commit adds all the remaining maps in #11690

**Comment by SoScared** [comment]
Edited first comment for clarity.

And thanks Mailaender for encouraging this. I've learned a lot the past 24 hours!

**Comment by GraionDilach** [comment]
Please revert the packaging of Poland Raid. Maps with custom rules should be in a loose folder, that makes sure they get upgraded when necessary.

**Comment by pchote** [comment]
i would prefer it if we could throw out the custom rules instead.  Official maps should be designed to work with our official game rules, without having to do weird things like expand the conyard sight range.

**Comment by SoScared** [comment]
View range 8 for the conyard and ca. 50% faster accumulation from oil derrics. Neither looks to be neccessary for any purpose on Poland Raid.

**Comment by SoScared** [comment]
That should be all. The rest of the map alterations will eventually be found through #11143

Apologize for the prolonged pull request. It's been a learning process after all.

These map alterations should help set the bar higher for any future change in the map pool and hopefully have map makers aim higher when they design their maps.

**Comment by GraionDilach** [comment]
Pease do not drop everything into one PR.

These balance changes should be in a PR of their own.

**Comment by SoScared** [comment]
Yeah sorry, that wasn't intentional. I'm still trying to learn how to create seperate PRs.

**Comment by Micr0Bit** [comment]
that said ... i think we have already enough balance-changes in RA for the next playtest/release

**Comment by SoScared** [comment]
Added Operation Goldmine (added to bleed 2 months ago): http://resource.openra.net/maps/15410/
operation goldmine compare

**Comment by obrakmann** [comment]
ok, I guess. :+1: 

Please squash those commits into one.

**Pull request closed without merging**
