### PR TITLE
Support randomized death animations

### PR DESCRIPTION
**Pull request by pchote**
As requested by Nolt in IRC.

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
:+1:

**Comment by pchote** [comment]
Rebased and removed testcase.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b08e3a68023f9f8d395dcff7cc5f18a27e2f110a...6564cc57f9b7bad7adad343bb8f19d26aa87b36c)

**Pull request merged**
