### PR TITLE
Fix TD tower selection boxes and improve TS sequence offsets

### PR DESCRIPTION
**Pull request by reaperrr**
- Fixes that the Obelisk and AGT in TD only have 24x24 visual selection boxes.
- Improves offsets of TS Adv. Nod Power Plant and GDI Comm. Center. This does NOT fix the offset issues on "A River Runs Near It", but makes them more accurate everywhere else.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by Mailaender** [comment]
Regarding https://github.com/OpenRA/OpenRA/pull/9189#issuecomment-136099529 I guess there is still code which isn't really height-map aware.

**Comment by pchote** [comment]
The upgrade center / advanced power plants have nothing to do with heightmaps, and only occur on one theater each.  I suspect that the tileset-specific artwork might have bogus offsets defined in the artwork.

**Comment by GraionDilach** [comment]
Disagree. I've put a day to fix two buildings having that same footprint in my mod, and in both cases I
 - either managed to have the cell position markers synced with the art, with both floating in air like 75 pixels above they should
 - either managed to make the building placed in it's actual position so-so but then the placement position cell art went off

I can't think anything else besides that footprint being bogus for some reason.

**Comment by pchote** [comment]
@GraionDilach: Do you have screenshots of those issues?  I don't see how your description disagrees with my comment (if that's what it was aimed at).

**Comment by GraionDilach** [comment]
Because if it'd be the tileset-specific art, then it would happen with all buildings. It also affects my powerplant and barracks on these pictures which has one common thing next to the affected ones - they are all 2x3 buildings. Which is why I think this specific foundation being bugged.

openra-2015-08-30t224723z
openra-2015-08-30t225235z

**Comment by pchote** [comment]
@GraionDilach: the problem there is that the buildings are rendered fine in the snow tileset.  The only thing that is different between snow and temperate is the specific building sprite file.

**Comment by reaperrr** [comment]
@pchote: No, the offset issues do not appear on both temperate maps, only on "A river runs near it", not on "River Raid".

I just now changed the normal Nod power plant to a 2x3 footprint without any other changes and indeed, offset is fine on "River Raid", wrong on "A river blah".

So it's definitely not an art issue.

**Comment by penev92** [comment]
:+1:

**Pull request merged**
