### PR TITLE
Added a missing SequenceReferenceAttribute

### PR DESCRIPTION
**Pull request by penev92**

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]
Fix confirmed after applying #20112.

**Comment by penev92** [comment]
Rebased on top of #20112.

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ec33cf4e85e04f1a97c9ac024a0257d08dc104fa...2d15188936d330c792780e6b89449aa274d1b70a

**Pull request merged**
