### PR TITLE
Add more varied pre-selected colors to player colors palette

### PR DESCRIPTION
**Pull request by PunkPun**
I've just copypasted hexcodes from #19335's diff.

If someones wants to polish up the color selection, I'll be more than change the hexcodes in this PR.

### CODE REVIEW

**Review by Mailaender — DISMISSED** [review]

**Review by anvilvapre — DISMISSED** [review]
untested.

perhaps document how you came to/generated these colors. also since they are different per mod.

**Comment by PunkPun** [comment]
I meantion in the opening post how I got them

**Comment by Mailaender** [comment]
image

does not look at all like

image

though

**Comment by PunkPun** [comment]
I took some time and mixed the old colors with new colors for more variety (no new hex codes), also shuffled the values around

> does not look at all like

Because as I wrote in the intro, I had just taken the old values.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f96ee5ba074db814745d18c2e3ba3275b04fc4cf...b9ac1fa7ff508e31ce583f54ceefaa1cf19db31f)

**Pull request merged**
