### PR TITLE
Remove OpenRA.TilesetBuilder.

### PR DESCRIPTION
**Pull request by pchote**
This has been unmaintained for years, and I suspect it may have been completely broken until 8844defb44fad9bd51ee644046c9abd9dd9f202a fixed a bunch of bitrot in tileset saving.  The CRLF issue with default.yaml (#7754) highlights that this is doing nothing for us except causing problems.

A general tileset building tool is a good idea in principle, but it would be better maintained as an outside project that outputs openra-compatible yaml without hooking into the engine internals.

### CODE REVIEW

**Comment by Mailaender** [comment]
Okay. :+1:

**Comment by Phrohdoh** [comment]
Rebase then :+1:.

**Comment by Phrohdoh** [comment]
[Changelog entry](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a26857e2a85b2ec0c181f89c7a0935051a97bb05...0872868671128feb98489e90e26a02e4e9bf6045).

**Comment by Mailaender** [comment]
Moved it to https://github.com/OpenRA/TilesetBuilder

**Pull request merged**
