### PR TITLE
Replace pseudo-childactivities in several activities.

### PR DESCRIPTION
**Pull request by tovl**
Continuing the work of #16374 this PR replaces pseudo-childactivites by actual usage of `Childactivity` in `Enter` and related activities as well as in the `WaitForTransport` activity. I also made some slight simplifications in the `Enter` activity. The only pseudo-childactivities remaining now are in `AttackMoveActivity`, which would need to be based on #16369 to work properly on aircraft.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Ingame testing didn't reveal any regressions in RA.

**Review by pchote — APPROVED** [review]
Code changes LGTM and didn't notice any issues ingame.

**Comment by pchote** [comment]
Taking @matjaeck's testing as a second :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9e39b86618fd1fa5c51285350436785cbe0d2ce1

**Pull request merged**
