### PR TITLE
Some necessary functions & fix for AttackOverlay

### PR DESCRIPTION
**Pull request by dnqbob**
showcase-2

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
LGTM, untested

Could a testcase of sorts be added?

**Comment by dnqbob** [comment]
Sure, wait for me

**Comment by dnqbob** [comment]
testcase
I pushed a code simlifying and a test case here.

**Comment by dnqbob** [comment]
The code simplify itself proves 
[WithAttackOverlay: fix ZOffset not related to actor.](https://github.com/OpenRA/OpenRA/pull/21411/commits/5fcef1eae8643fe132d25543c4f4531452880504)
[WithAttackOverlay: now support facing correctly with BodyOrientation](https://github.com/OpenRA/OpenRA/pull/21411/commits/ce0552de6474558e5158509dce6fcfb8ca74df7d)
works as promise.


While test case proves
[WithAttackOverlay: support decoration animation.](https://github.com/OpenRA/OpenRA/pull/21411/commits/7b36f53884a48d1ce519ba107b909196da257aaa)
works as promise.

As for
[WithAttackOverlay: support specifc Armament to play animation.](https://github.com/OpenRA/OpenRA/pull/21411/commits/85deebcc0ad8aa77eec23004b6f6f6a3e9848df9)
You can change the Armament name to see if it can trigger on different names.

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b530d9e7481ce8759568af895625f6c71483c6a1...586a7709d6d6ceb87a116e4e88d5871a1d54ec3e)

**Pull request merged**
