### PR TITLE
Allow BlendMode to be changed for RgbaColorRenderer

### PR DESCRIPTION
**Pull request by CastleJing**
* Some graphic effects seem to use different BlendMode in the original game, such as Beam effect and laser in Ra2, etc.

### CODE REVIEW

**Comment by deleted-user-1** [comment]
Welcome, great to see a PR owned by you! d3123cac1dfcc112af8d882ef3380b2ec08f has been very helpful for OpenRA!

**Comment by CastleJing** [comment]
> 
> 
> Welcome, great to see a PR owned by you! [d3123ca](https://github.com/OpenRA/OpenRA/commit/d3123cac1dfcc112af8d882ef3380b2ec08fe1aa) has been very helpful for OpenRA!

I'm glad that could be helpful 😆

**Comment by pchote** [comment]
Two initial style nits:
* Please rename `blendModeUsed` to `blendMode` to match the naming conventions used in the other renderers.
* Please remove the default value the non-public drawing methods (like `SpriteRenderer.DrawRGBAVertices`,`SpriteRenderer.DrawConnectedLine`, `SpriteRenderer.DrawDisconnectedLine`). These are always called with a blend mode, so it is not necessary.

I have not yet thought about the overall implementation approach.

**Comment by dnqbob** [comment]
I don't know a thing for blending but I have a thing for greeting.
Hello, our OpenRA localization core coder!

**Comment by CastleJing** [comment]
> 
> 
> Two initial style nits:
> 
>     * Please rename `blendModeUsed` to `blendMode` to match the naming conventions used in the other renderers.
> 
>     * Please remove the default value the non-public drawing methods (like `SpriteRenderer.DrawRGBAVertices`,`SpriteRenderer.DrawConnectedLine`, `SpriteRenderer.DrawDisconnectedLine`). These are always called with a blend mode, so it is not necessary.
> 
> 
> I have not yet thought about the overall implementation approach.

I modified it as you suggested.

I found using BlendMode.Additive looked better while improving the ra2 laser

Using BlendMode.Additive:
t1

Using BlendMode.Alpha:
t2

Effects in the original game:
t3

**Review by pchote — DISMISSED** [review]
This isn't exposed in any way that can be tested, but the plumbing changes look reasonable to me. Needs a rebase though.

**Review by teinarss — APPROVED** [review]

**Comment by teinarss** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3652368c11a4f83183df5538a3c38944895bf3f7...899f5f0b09f4cfd6453f60525a9df72a5e1cd969

**Pull request merged**
