### PR TITLE
Rename d2k actors to match original game rules.

### PR DESCRIPTION
**Pull request by pchote**
A small step towards making #9106 reviewer friendly.  Works towards #7558.

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by penev92** [comment]
I'd like to hold on to this until it includes an update for the map importer. I volunteer to do that if nobody else is willing to, but it may be a few days before that happens.

**Comment by penev92** [comment]
Everything works in skirmish, but you forgot to update the Lua scripts for the missions, and the scripted reinforcements crash the game.

**Comment by Mailaender** [comment]
Better write an actor upgrade rule to also cover the community http://resource.openra.net/maps/

**Comment by pchote** [comment]
Integrated additional changes by @penev92.

**Comment by reaperrr** [comment]
With these additional changes my :+1: still stands.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5b92fb8bf6b3edc373a214327258614cff4419a3...725a50a67a5cc698db3e0aa5637edb558c7819e4)

**Pull request merged**
