### PR TITLE
Fixed RallyPoint sprites not being truely optional

### LINKED ISSUE #20844: Unhardcode rally point sequences.
`RallyPoint` trait has two sequences:

- FlagSequence
- CirclesSequence

While setting own name for them is totally doable, you cannot set one sequence and leave the other one empty. The game will just crash. There are two solutions to the problem right now, either have artwork which covers both sequences or create an empty sequence.

Setting at least one sequence should be mandatory but setting the other one should be optional.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/20844

### CODE REVIEW

**Comment by PunkPun** [comment]
I don't agree with the second commit. There needs to be something designating the end of the rally point, otherwise it looks off.

**Comment by Mailaender** [comment]
It is kind of a test commit, kind of proposition to get rid of (C) content from the bits folder related to the discussion you started today.

**Review by Dzierzan — DISMISSED** [review]
I tested that in RA mod. Works nicely when one sequence is left empty. The less hardcoded stuff, the better :-).

**Comment by Dzierzan** [comment]
On the other hand, perhaps this PR should focus on the unhardcoding rally point sequences only, not removing (C) content. That should be reserved by another PR.

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d2e4066dd7caef12f42d03b7656d707c0be6f8b8...f5894dffaabaddc9ecd1983a11975306d7500b30)

**Pull request merged**
