### PR TITLE
Rearrange default observer hotkeys

### LINKED ISSUE #15956: Rearrange observer hotkeys
The "Statistics graph" panel for observers doesn't have a hotkey bound by default. I thinks that's a little awkward. The natural place for it would be `F5` but  currently `F5` through `F8` are mapped to replay game speed controls. In light of #15767 and possible other panels coming in the future I think it makes sense to move the speed hotkeys to `F9 - F12` and free up `F5 - F8` for stat panels.

@SoScared has already done that in Unplugged and I think it works fine. I know that power user can remap their hotkeys however they like but I think it's better to have sane defaults. And this won't be a major change, so players should adapt quickly to the new defaults.

### PR DESCRIPTION
**Pull request by dragunoff**
* Move replay speed hotkeys to `F9 - F12`
* Set `F5` as default for `StatisticsGraph`

Closes #15956

### CODE REVIEW

**Comment by teinarss** [comment]
Could this be done for TD and the other mods as well if it's missing there?

**Comment by dragunoff** [comment]
@teinarss These definitions live in `common|hotkeys/observer.yaml` so they apply to all core mods.

**Comment by MustaphaTR** [comment]
> @teinarss These definitions live in common|hotkeys/observer.yaml so they apply to all core mods.

I don't think this can be said for everything in common, tho in this case it is correct.

**Review by ghost — COMMENTED** [review]
Working as advertised in RA, CNC, D2K. Could we add `F7` as hotkey for the army value graph after #15767 is merged (in this or a follow-up PR)?

**Comment by dragunoff** [comment]
Sure, once that is merged I can rebase and add `F7`.

**Comment by matjaeck** [comment]
@dragunoff Ready for rebase.

**Comment by pchote** [comment]
We're going to want this in the playtest to go along with the army graph.

**Comment by dragunoff** [comment]
Rebased and updated. I've added the hotkey for the army value panel in a separate commit.

**Review by ghost — APPROVED** [review]
Works and `F6` is the correct hotkey, not `F7`. :+1:

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/32cf03bb5b3b0294b7c38b499bcf72c385bff998

**Pull request merged**
