### PR TITLE
Remove GlobalFilesystem.OpenWithExts.

### LINKED ISSUE #5272: Remove magic sprite filename resolution (support TS-style terrain-specific artwork) [$20]
Automatically resolving extensionless filenames to tileset-specific versions made sense back in 2007, but the engine is now a completely different beast and this now causes more problems than it solves.

* It makes it very difficult to statically verify sequence errors. #2283
* It makes it difficult to effectively cache data to reduce load times (see #5234).
* It's not needed for D2K, which doesn't have tileset-specific art.
* It won't work at all in TS or RA2, which use different names (not just extensions) for tileset-specific art.

We should rip out this legacy code, require mods to define tileset-variants in sequences, and then use name mangling (like we do for damage states) to resolve them in mod-level code.

<bountysource-plugin>
---
There is a **[$20 open bounty](https://www.bountysource.com/issues/2076095-remove-magic-sprite-filename-resolution-support-ts-style-terrain-specific-artwork-20?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Closes #5272.

### CODE REVIEW

**Comment by Mailaender** [comment]
I don't want to grant you the bounty until the regressions from https://github.com/OpenRA/OpenRA/pull/7741#issuecomment-87197152 are fixed.

**Comment by Mailaender** [comment]
Also https://github.com/OpenRA/OpenRA/pull/7733#issuecomment-87198162 is very serious as #4496 is not yet shipping.

**Comment by obrakmann** [comment]
This breaks RA the same way d2k is already broken in bleed (in the editor).

**Comment by pchote** [comment]
Fixed the missing sprites in the legacy editor.  @reaperrr will fix the desert wall palette in #7747.

**Comment by Mailaender** [comment]
:+1: This fixes the OpenRA.Editor.exe regressions for D2k and RA.

**Comment by reaperrr** [comment]
Fixes editor regression for resources on ra desert (and interior, btw) as well as d2k, and all mods still start and their shellmaps work, so the GlobalFilesystem.OpenWithExts removal seems to cause no issues, either. :+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0d2bf05e40cf4361c49087703cce086383a7f7c5...1cbf8a6e99303236e1939d6accf0f44533d0646e)

**Pull request merged**
