### PR TITLE
mods/ra/maps: update Winter Storm

### PR DESCRIPTION
**Pull request by kyrylo**
Map link: http://resource.openra.net/maps/20503/

Old | New
--- | ---
openra-2017-04-09t095447104z | openra-2017-04-09t094805748z

Changes:

* Renamed from `Winter Storm 2` to `Winter Storm`
* Decorated the chain links near middle oil derricks
* Resized the map from 89x82 to 89x86 to add more sea tiles to the top
  and to the bottom
* Fixed broken tile near the ridge to the middle right

### CODE REVIEW

**Comment by ltem** [comment]
Were the spawn points moved on purpose?

**Comment by kyrylo** [comment]
Good catch, no. I resized the map and copy/pasted terrain. When you do that, spawn points don't move.

**Comment by kyrylo** [comment]
Updated map spawns (reverted back to original locations), but didn't change the PR screenshot.

PTAL

**Comment by FrameLimiter** [comment]
The map in the commit still has the old spawn points: [16,68] & [74,16].

**Comment by kyrylo** [comment]
That's strange. I deleted the map, committed, pushed it and committed again. I can see these (correct) spawn points `[16,70]` && `[74,18]`.

PTAL

**Review by ghost — APPROVED** [review]
:+1:  Looks good.

**Comment by ltem** [comment]
:+1: yep it's fixed

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7566e7ebd505de5472bfb5ea726273e57d843741...58b75e3af083edf46995f33c9fcf7746cb035d44)

**Pull request merged**
