### PR TITLE
Remove DelayedAction from WeaponInfo 

### PR DESCRIPTION
**Pull request by tohava**
Remove DelayedAction from WeaponInfo and replace it with the more serialization friendly DelayedImpact. This should be part of the fix for #12310.

### CODE REVIEW

**Comment by reaperrr** [comment]
You forgot to add `DelayedImpact` to OpenRA.Game.cs.

Generally speaking, I recommend to locally compile and run `make check` from our scripts once before staging changes or pushing commits, that usually catches things like these early and can save you some later fixups and force-pushes (I learned that the hard way myself).

**Comment by tohava** [comment]
@reaperrr - I did 'make check' and it worked fine, just as it seemed to have working fine on travis-ci. Am I missing something?

**Comment by tohava** [comment]
@reaperrr - I did the fix you requested

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
> Am I missing something?

I meant that it's better to do both (test-compiling and 'make check') before staging/pushing, because that normally catches ~99% of these mistakes.
`make check` alone only checks files listed in a csproj for style issues, it won't catch compile errors.

**Comment by pchote** [comment]
If @tohava is on Linux or OSX then test compiling wouldn't have caught this (the makefile doesn't use the csproj).

**Comment by reaperrr** [comment]
> If @tohava is on Linux or OSX then test compiling wouldn't have caught this (the makefile doesn't use the csproj).

I see. Nevermind then.

**Comment by Phrohdoh** [comment]
Another reason to move away from the makefile and promote the use of xbuild (eventually xplat msbuild).

**Review by pchote — APPROVED** [review]

**Pull request merged**
