### PR TITLE
Allowed aircraft to land on Tiberium and Veins

### PR DESCRIPTION
**Pull request by DaynosaurusRex**
Added TS specific LandableTerrainTypes for aircraft on Veins and Tiberium. As requested in: #11746

### CODE REVIEW

**Comment by pchote** [comment]
[temperate.yaml#L11](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/tilesets/temperate.yaml#L11) has a list of the terrain types used in TS.  Can you please tweak your types to match? (need to remove Ore, add DirtRoad, Rail)

**Comment by GraionDilach** [comment]
Needs to be suqashed now. The result looks good otherwise.

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
:+1:

**Pull request merged**
