### PR TITLE
Grouped the radar traits together

### PR DESCRIPTION
**Pull request by Mailaender**
Just moving code that belongs together.

### CODE REVIEW

**Comment by pchote** [comment]
If you moved these into their own namespace then they would appear grouped on https://github.com/OpenRA/OpenRA/wiki/Traits too.

**Comment by Mailaender** [comment]
Good idea. Done.

**Comment by abcdefg30** [comment]
Well, looks simple enough. :+1: / :white_check_mark:

**Comment by GraionDilach** [comment]
TBH, I thought @pchote already thought about removing `JamsRadar` in favor of an `UpgradesActorsNear`-disable radar upgrade combination so I'm not certain if this worths the effort (especially the separate namespace aspect).

**Comment by Mailaender** [comment]
I doubt anyone is working on that at the moment.

**Pull request merged**
