### PR TITLE
Changed SubCell to byte.

### PR DESCRIPTION
**Pull request by teinarss**
Updated SubCell enum to byte, could be be some small performance improvement, haven't done any benchmark on this.

### CODE REVIEW

**Comment by Unit158** [comment]
:-1: for premature optimization.

**Comment by pchote** [comment]
This plus #15478 reduce the size of the pathfinding struct to improve cachability.

**Comment by teinarss** [comment]
The whole point of this is to reduce the size of value types (structs etc) which will increase the performance by reducing the cost of copy these values to the stack. Ofc this will introduce a risk like all code changes. I would say that this is a low risk low reward change which was easy to do. 

Most of these value types are used in the hot path of the engine, ie the pathfinding.

**Comment by chrisforbes** [comment]
@Unit158 we want to get the core node structure the pathfinder uses to fit in 64 bits. This path is incredibly hot.

**Comment by GraionDilach** [comment]
Even from a practical standpoint - it's a reasonable assumption to assume that even the most extreme subcell amounts will cap between 10 and 50 - on huge cell sizes the cell-based maps becomes more of a burden than something properly playable and no amount of subcells can fix that.

**Review by Mailaender — APPROVED** [review]
Subcells still behave as they should in-game.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ffcb7904f840776e58089685b9c06181a92961d7

**Pull request merged**
