### PR TITLE
[RA] [Map pool] Fix tile errors on various maps.

### PR DESCRIPTION
**Pull request by SoScared**
**Update**: Includes tile fixes to official maps:

- Minor Pressure #13001

- Vihaan Lunta #12998

- Ensio Kaivo #12994

### CODE REVIEW

**Comment by SoScared** [comment]
Waiting out map uploads until the official release is out.

Also plugging awareness towards #295

**Comment by SoScared** [comment]
Added fix #13001 to the commit

**Comment by SoScared** [comment]
Added fix #12998 to the commit

**Comment by SoScared** [comment]
closes #13001, #12998, #12994

**Comment by FrameLimiter** [comment]
Minor Pressure & Vihaan Lunta both have (r):revision tags on their names. This should probably be removed.

Minor Pressure(r)
Vihaan Lunta(r2)
Ensio Kaivo

**Comment by SoScared** [comment]
Revision tags removed.

**Review by ghost — APPROVED** [review]

**Review by GraionDilach — APPROVED** [review]
:+1: and I believe this should be merged to the release version as well.

**Review by ltem — APPROVED** [review]
:+1: Triple approve, all errors are fixed

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9332370d83f34d15eb95c6e5b39e5aab3a3ecca4...6b1688a4fb61f4ad4f7d140076dbc8dd44716893)

**Pull request merged**
