### PR TITLE
Revise the map pool of RA mod

### LINKED ISSUE #14698: Refresh RA mod map pool
Meta issue to self and to support the discussion if required.

I'd like to revise and update the RA official map pool, as there are some popular community 1v1 maps which deserve being available for the greater number of people, also the team/FFA map would benefit from new maps.

**list was moved to [PR 14768](https://github.com/OpenRA/OpenRA/pull/14768), check there**

Feel free to comment, give feedback and provide reasons for/against any of the maps.

**Siberian Pass**: I feel it has outlived its time and is now quite "inefficient" in terms of gameplay - lots of chokes, snaky nature, refinery placement tends to be unoptimal and unbalanced between player positions. Also starting ore mines are away from each other yet in range of ore truck seeking range, so trucks tend to jump from one to another often.

### PR DESCRIPTION
**Pull request by netnazgul**
Closes #14698.

Name | Players | Author | Checked | Fixed revision link | PR
---- | ------- | ------ | ------- | ------------------- | -----
[Bad Neighbors](https://resource.openra.net/maps/15207/) (**remove**) | 4 | Nuke'm Bro. | | | +
[Ghost Town](https://resource.openra.net/maps/15299/) (**remove**) | 4 | hamb | | | +
[Seaside 2](https://resource.openra.net/maps/15228/) (**remove**) | 6 | hamb | | scarce ore count and numerous oil derricks... I'm not sure, not seen in the lobby either | +
High&Low (**remove**) | 8 | Captain Mel | | center chokes that will lead to lags, Shattered Mountain will be a good similar replacement | +
[Agenda](https://resource.openra.net/maps/22718/) (revise) | 2 | SoScared  | + | https://resource.openra.net/maps/24975/ | + 
[A Nuclear Winter](https://resource.openra.net/maps/24834/) | 2 | 3Lucian | + | https://resource.openra.net/maps/25446/ | +
[Borrowed Time](https://resource.openra.net/maps/20222/) | 2 | Omnom | x | sadly I can't fix all the tiling issues and keep the map structure intact, so this is dumped | -
[Pitfight](https://resource.openra.net/maps/20892/) | 2 | kazu | + | https://resource.openra.net/maps/25518/ | +
[Ysmir](https://resource.openra.net/maps/20553/) | 2 | kazu | + | https://resource.openra.net/maps/25460/ | + 
[Decrepit Isles](https://resource.openra.net/maps/23107/) | 4 | mo | + | https://resource.openra.net/maps/25445/ | +
[Doublestep](https://resource.openra.net/maps/23195/) | 4 | FRenzy | + | https://resource.openra.net/maps/25381/ | +
[Maelstrom](https://resource.openra.net/maps/24320/) | 4 | netnazgul | + | https://resource.openra.net/maps/24320 | +
[Outdoor Trails](https://resource.openra.net/maps/21397/) | 4 | CRLF | + | https://resource.openra.net/maps/21397 | +
[Sude's Digest](https://resource.openra.net/maps/21331/) | 4 | Jopani Kansaro | x | concept is interesting, but editing/balancing/testing is required to make this playable | -
[Jungle Law](https://resource.openra.net/maps/22991/) | 6 | FRenzy | + | https://resource.openra.net/maps/25382 | +
[River Borealis](https://resource.openra.net/maps/23375/) | 6 | Blackened | x | some balance/tiling concerns | -
[Union Sacrée](https://resource.openra.net/maps/25449/) | 6 | FRenzy | + | https://resource.openra.net/maps/25449/ | +
[Volcano (Accent)](https://resource.openra.net/maps/24468/) | 6 | American Blunt/Printer | + | https://resource.openra.net/maps/24468 | +
[Rapa Nui](https://resource.openra.net/maps/22158/) | 7 | American Blunt | + | https://resource.openra.net/maps/25519/ | +
[Unconventional Warfare](https://resource.openra.net/maps/20317/) | 7 | PizzaAtomica | + | https://resource.openra.net/maps/25384/ | +
[Shattered Mountain](https://resource.openra.net/maps/24512/) | 8 | james.bong | + | https://resource.openra.net/maps/25447/ | +
[Ore Gardens](https://resource.openra.net/maps/23413/) | 8 | sith_wampa | + | https://resource.openra.net/maps/23413/ | +

### CODE REVIEW

**Comment by Arular101** [comment]
I gave it already a quick look (as the state of this PR now), so far it looks good imho.

Some small things:
- Can you change the spawning points for Pitfight? The B is at the top now.

- I noticed that there is a Chinook husk in Decripit Isles in the top left corner. But the husk disappears after some time. This has to do with the burn damage the husk receives every second. To let the husk stay a rule.yaml file needs to be made with:
```
TRAN.Husk: (or Husk1 or Husk2)
	Burns
		Damage: 0
```

- The maps A Nuclear Winter and Shattered Mountain has weather effect. If I'm correct then the weather rules should also be separated from the binary files. Like how it is in for example Snow Off. Can someone confirm this? Also, I don't know how that was done.

- @3Lucian This is how the barrel damage looks like now:
openra-2018-01-28t122450268z

- @netnazgul If you want to close the open issue when this PR is merged, you need to write "Closes #14698" or "Fixes #14698". Then it automatically closes the issue too when the PR is merged.

**Comment by GraionDilach** [comment]
>The maps A Nuclear Winter and Shattered Mountain has weather effect. If I'm correct then the weather rules should also be separated from the binary files. Like how it is in for example Snow Off. Can someone confirm this?

Yes, that's how it should be done - the mapsave dialog offers the option for such.

**Comment by pchote** [comment]
> To let the husk stay a rule.yaml file needs to be made with:

For default shipped maps it would be better to remove the husk.

**Comment by netnazgul** [comment]
@Arular101 map can be saved unpacked. I suppose I'll unpack those two then. For Nuclear Winter that would mean yet another revision :P
Nice mention on the husk (I had the same issue once on my map as well), but better way would be just to remove it I think.

**Comment by netnazgul** [comment]
- Nuclear Winter and Shattered Mountain are unpacked, custom rules put into rules.yaml.
- Fixed Pitfight spawn points order
- Removed husk from Decrepit Isles

**Comment by netnazgul** [comment]
Added **Union Sacrée**, 6 player map.

Probably the last one to be added on this batch.

**Comment by HappyORA** [comment]
Can you please define the need that is adressed here? Is there data and statistics showing that the current maps in the release are insufficent?

Can you tell us who you have collaborated with to develop this map pool? What is the basis and criteria for the selection.

**Comment by pchote** [comment]
@HappyORA: See the issue linked from the PR description (#14698).

**Comment by HappyORA** [comment]
After reading through it I saw it was based near enough all on opinion. And after witnessing how events have unfolded in this community - opinions are not valid to make changes. I would like to see statistical evidence and data to see why maps should be added and removed. Firstly is there a large enough difference between games played on maps to warrent removal and are there similar games played on maps being added to the pool. And secondly can we have case evidence and pictures and explanations of issues with maps being replaced such as glitches etc etc.

**Comment by HappyORA** [comment]
For some reason github on mobile wont let me edit posts. I meant differences in games played compared to popular maps for example comparing Assymetric Battle (a map I assume isn't very popular) compared to Haos Ridges.

**Comment by netnazgul** [comment]
@HappyORA regarding 1v1 maps - the list is based on RAGL season 1-4 statistics (this actually was the main idea behind this PR). Some top maps are already included, the four listed above are not. I'd love to include Borrowed Time (with capturable civ buildings) as well, but it has lots of tiling glitches (pool beach tiles placed one over another) which are not easily fixable without breaking the map structure, so it was scrapped.

As for the other maps - on team maps I've asked around and mostly based the map selection on the FRenzy's team mapmaking post on Sleipnir's which was gathering mappers on creating these maps; Outdoor Trails and Unconventional Warfare were map contest nominees (afair they were both highly regarded), and Volcano looks a nice sub for Singles/Doubles/Triples with its simplicity.

I don't see why having less nice diverse maps in the distributable package is better than more maps; if you think some map should or should not be present there - just say so. Gathering data you want is impossible, especially that RC statistics got reset several times for some maps (at least it looks like it).

**Comment by netnazgul** [comment]
Now I'm reminded that **Ore Gardens** map is missing from the map pool... 
I'll add it in the evening today if there are no objections, as it is probably one of the best and most popular FFA/team maps around.

**Comment by HappyORA** [comment]
Unfortunatley RAGL map statistics are a bit flawed in the sense RAGL is a map picking system in a competitive enviroment - people will pick maps that tactically disadvantage their oppenant. The official map pool are maps picked by players because they want to play on them than thinking of tactically disadvantaging their oppenant or advantaging themselves - for example if I was against a highly inexperinaced player in RAGL I would pick Keep off the grass 2 because it is a very brutal map to new players rather than I like it. As well I bring Griaons point that we shouldnt look at the competitive players for the all round official map pool. It's all good if we like pitfight but if casual players want singles and the stats back it then what can you do.

I would like to see records of these conversations like on the other pull request however it is still just opinions anyway. Frenzys map making thread is for creating maps not disscussing what maps are great. Yes amazing for development of maps but even then actual game counts are more valuble. The map contest was once again opinions to player votes. I have no qualms with the contest selection because it was NMM's tournament but this is the official pool.

I said nothing about diveristy. If Frenzys map Sacre bleu absoloute bombs it with games played then it should be in the pool. I'm not putting my opinion forward on this because it defeats my whole point and the projects point of using data.

Unfortunatley the RC resets are not my problem. They will need to be fixed to fix processes like this.

**Comment by netnazgul** [comment]
Ok, I think the list looks almost finished now. **American Blunt** said he will look into upgrading Rapa Nui by thursday, otherwise it is a perpetual question of adding/removing maps which can be postponed for later (say, next release).

**Comment by HappyORA** [comment]
Opinions haven't mattered in near enough every previous case I don't see why they matter now unless this is another pick and choose when to apply scenario.

Why not? They're invisible and why would they care? It's not like your giving out the personal history your just counting how many times a map has been played. Do they even know any of this is happening?

In addition if your set on using opinions then even with that, you need good evidence to support your argument.

**Comment by pchote** [comment]
> American Blunt said he will look into upgrading Rapa Nui by thursday

As with the chinook in Decripit Isles, our normal default maps should avoid customizing the standard game rules or adding new actors.

This seems like a good time to remind everybody that GitHub is a professional environment, and we expect everybody to participate in good faith, and abide by our [code of conduct](https://github.com/OpenRA/OpenRA/blob/bleed/CODE_OF_CONDUCT.md).

**Comment by Arular101** [comment]
Maybe a forum post should have been made to get more attention and opinions from players. I hope the time window is big enough to still do that. 

> As with the chinook in Decripit Isles, our normal default maps should avoid customizing the standard game rules or adding new actors.

The 8 player map Center of Attention Redux 2 has the following custom rules:
```
OILB.Strong:
	Inherits: OILB
	Health:
		HP: 600000
	RenderSprites:
		Image: OILB

OILB.Weak:
	Inherits: OILB
	Health:
		HP: 90000
	RenderSprites:
		Image: OILB 
```
Should this map stay?

**Comment by pchote** [comment]
In the past we removed the custom rules but kept the map.  Depends on whether that would break gameplay there or not.

**Comment by netnazgul** [comment]
PR is complete. Open the floodgates

**Comment by abcdefg30** [comment]
Looks good overall. A few remarks:
- Can we drop `Pitfight` for now please? It doesn't really look visually appealing to [me](https://logs.openra.net/?year=2018&month=02&day=01#12:22:15). The dense lines of trees contrast a bit too much with the emptiness of the rest of the map, imho.
- `Maelstrom` has a few odd placed trees imho:
maelstrom
(I.e. standing on top of cliffs.)
- We might want to disable bots on `Rapa Nui`. I don't think they do well on that map.

**Comment by netnazgul** [comment]
- Fixed Maelstrom trees
- Did some visual changes to Pitfight
- Disabled bots on Rapa Nui

**Comment by pchote** [comment]
I'm somewhat concerned about the extreme size of the Rapa Nui map.  It is almost as big as the infamous "Zeus" map, and twice the size of its smaller brother "Apollo".

**Comment by ThisBlunt** [comment]
Rapa Nuis perforformances are better comparable to "Zues" and "Apollo". Gameplay times average ~1 hour based on a player spread of a spread of green and yellow pings. Gameplay speeds are average at best in that its not fast but not too slow a pace. 

There are numerous huge maps the have been added to the map pool currently and in the past and that perform the same or arguably worse then this map.

**Comment by oraservers** [comment]
I have read through these posts and all participants raise great points about the nuances of each of these maps. It looks like an opportunity to have fun and get engagement from a broader set of stakeholders. 

The list is really big and is focused on competitive maps. Maybe we could put the "slot" for maps up for a vote on the OpenRA website, as a special "you be the judge" event, where unique IPs can vote on the maps that they want to include. For example, pick the consensus 1v1, 2v2, 3v3, 4v4 additions (1-2) from this GitHub discussion, and then open one more from each category up for nomination by the public. Target could be for the next +1.  This way, the hard work of the contributors here is part of it, and there is an opportunity for broader community engagement. 

We could retire this PR this and make a new PR for "Add X number of new maps" based on this methodology, and then a separate one for "Remove X outdated maps" or something.

**Comment by pchote** [comment]
@oraservers a pessimist might rephrase that as "you can't please everyone, so shame on you for trying to change what we have now".  @netnazgul has proven himself sensible and knowledgeable enough on the current state of community maps to put forward a concrete proposal.  I am more than happy to let him take the lead here unless someone can give specific arguments against that.

**Comment by netnazgul** [comment]
I like the idea of making these a real popular vote, however I'd like to push this one like it is and only do voting on successive map refreshments as it already looks finished enough to be implemented.

**Review by abcdefg30 — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/e566d1139301475dd218ca82bb4cb09e751b4ee7...5de5b653fb2f33be0b4000fb70a19399dd02243a)

**Pull request merged**
