### PR TITLE
Enforce a line length limit.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Adds Roslynator.Formatting.Analyzers and enforces [RCS0056](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0056).

I have commits with the line length set to 180 and 160 to choose from. Getting to 140 requires another 600 violations resolved which my motivation does not currently extend to. We can always adjust the setting later if we're happy to take something to start with.

We used to enforce a line length limit, but it got lost in the transition from StyleCop to Analyzers. #7649

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
160 is good for me 👍

**Comment by Mailaender** [comment]
:+1: GitHub diff view creates forced line breaks even for 160, so I think 140 might be a good idea.

**Comment by AspectInteractive** [comment]
I vote for 180 characters because we are enforcing expression body'd functions which are hard to read quickly on multiple lines due to the lack of braces. The below method I have in my project is perfectly readable without scrolling on a 27 inch monitor with side navigation pane in Visual Studio, and a fairly large font size of 16 (I can't see small fonts very easily). This method is 162 characters including 2 tabs at the start, so would violate both the 140 and 160 character limits. Since the limit is meant to improve readability, it should only enforce line breaks for lines that cannot be easily viewed on a standard monitor, which by modern standards is at least 27 inches. So 180 gets my vote.

image

EDIT: One other downside to small character limits is the tendency to use shorter variable and method names. Sometimes this is helpful, but in many cases it makes it harder to understand what functions are actually doing. In my above example if I had shortened the name, you would not know at a glance what the method does unless I added a comment, and comments are very seldom seen in the codebase, not something we can rely on.

**Comment by PunkPun** [comment]
the line in your example is definitely too long and hurts readability, for me at least. In a multi-window setup I'd also have to scroll horizontally to read it

**Comment by AspectInteractive** [comment]
> the line in your example is definitely too long and hurts readability, for me at least. In a multi-window setup I'd also have to scroll horizontally to read it

Seriously? It's one method with 2 parameters, returning 1 method with 3 parameters. In what world is that unreadable? Also not sure how common multi-window setups are on the same monitor, usually people use multiple monitors or alt tab between information and code. In any case a method that returns itself with default parameters should not need 2 lines of code.

**Comment by pchote** [comment]
I (speaking as someone with two 27" monitors side-by-side) agree that its too long and hurts readability.

I would expect that line to be written as

```csharp
public static List<WPos> GetPointsSurroundingCircleUnit(WPos centerPos, WDist unitRadius) =>
    GetPointsSurroundingCircleUnit(centerPos, unitRadius, WAngle.Zero);
```

**Comment by RoosterDragon** [comment]
Rebased.

**Review by Mailaender — APPROVED** [review]

**Pull request merged**
