### PR TITLE
Admin List Setting

### PR DESCRIPTION
**Pull request by gru2007**
This new setting allows to restict getting admin by anyone on dedicated servers. That allows to create private games with predefined admin.

### CODE REVIEW

**Comment by PunkPun** [comment]
Hi 👋 

I don't think going by name is a secure option, anyone can have any name. I'd advise to either use forum name or IP

related #17659

I haven't checked, but there may be issues with the rest of the codebase as it was built with the assumption that at least one admin is always present in game lobby. There's also the assumption that no more than one admin is present in the lobby.

You may as well want to disable the ability to grant admin to other players, or change its behaviour at the very least

**Comment by PunkPun** [comment]
There's also the assumption that no more than one admin is present in the lobby

**Comment by PunkPun** [comment]
You may as well want to disable the ability to grant admin to other players, or change its behaviour at the very least

**Comment by gru2007** [comment]
I have added a check for only one admin in the lobby. But if player leaves, there may be troubles, so I need to test it..

This setting will only restrict getting of admin access to people in list. All other things work the same.

### Which problems that solves?
I wanted to create a private server for events, and I needed to give admin only to eventmaker. This field solves my problem.

### Secure
I wanted to create a check with a forum profile, but I don’t know how to get it in this context. So maybe I create 2 fields, one with insecure names and another with IPs.
One more thing: this field is intended to be used on private servers, so maybe it doesn’t need a lot of protection?

**Comment by anvilvapre** [comment]
what happens if no admin joined yet, but normal players did? you have an admin-less lobby where start is not possible?

**Comment by PunkPun** [comment]
Closing as it doesn't seem that this PR will be getting the necessary features to be merged

**Pull request closed without merging**
