### PR TITLE
Fix maximum range estimation for stationary turrets and stance-restricted units.

### LINKED ISSUE #16251: Regression: AA Defenses Slow Turn Rate at Max Range
AA Defenses at max range (both Sam Site and AA Gun) have slow turn rate when auto acquiring targets.

https://cdn.discordapp.com/attachments/279290580201373696/551288554349789195/AA_Defense_Bug.mp4

Hard to tell, but fire rate seems to be affected as well.

The bug goes away when you manually target or you close in beyond max range.

This behavior isn't present in release.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #16251.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by Punsho** [comment]
Does this also fix turret twitching for mobile actors?

**Comment by pchote** [comment]
I would be very surprised if it did.

**Comment by pchote** [comment]
It turns out that this does fix turret twitching for mobile actors, which is probably related to the defend stance not allowing them to move.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/484f127b0dc9285a8aa4b37893d025f24617755d...0bdad8dc8b777081467f6f0312c3f62a2e98e7ef

cdf74cf

**Pull request merged**
