### PR TITLE
Change tree husks from FrozenUnderFog to HiddenUnderShroud

### LINKED ISSUE #15579: Trees vanish when killed under fog
If a tree dies under the fog it visually disappears. The tree husks should be updated under the fog.
FrozenUnderFog: should be replaced with HiddenUnderShroud:

cnc:
https://github.com/OpenRA/OpenRA/blob/5d1c37a4c55e1ec4d8ab7d83501e4ca6eb77c985/mods/cnc/rules/defaults.yaml#L938

ra:
https://github.com/OpenRA/OpenRA/blob/5d1c37a4c55e1ec4d8ab7d83501e4ca6eb77c985/mods/ra/rules/defaults.yaml#L897

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #15579.

### CODE REVIEW

**Comment by pchote** [comment]
I have mixed feelings about this.  On the one hand, this should fix the trees disappearing by making the husk visible, but on the other we shouldn't be leaking that the tree has died through the fog at all.  

The correct behaviour will come from having both the trees and their husks frozen under fog, but there are (possibly no longer relevant) performance concerns here - look for the PR that switched trees away from this in the first place.

**Comment by Smittytron** [comment]
> look for the PR that switched trees away from this in the first place.

Looks like #9250

**Comment by Smittytron** [comment]
Re-opened per comment on #15579.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/69baece453403a16fdc9d3771acae4d62cb5c5ff

4631cbfc2a2c8c0ae00b54524f1bd521eaa8e494

**Pull request merged**
