### PR TITLE
Add support for playing a BridgeRepaired notification

### PR DESCRIPTION
**Pull request by abcdefg30**

### CODE REVIEW

**Comment by obrakmann** [comment]
Works as advertised :+1:  Needs a rebase, though

**Comment by abcdefg30** [comment]
Rebased.

**Comment by Mailaender** [comment]
No negative side effects on the legacy mods. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/911e1a25ea052bc5407622d20be6bfb0f44164ab...6e458842ac27f62eae884c7187c4cb6d4892d1e3)

**Pull request merged**
