### PR TITLE
Fix BGRA channel count.

### LINKED ISSUE #11341: Sprites render from the wrong texture.
Can't reproduce it anymore though.
niced2kloadscreen

### PR DESCRIPTION
**Pull request by pchote**
This fixes the minimap issues from #11341, but probably not the loadscreen issue shown by @abcdefg30 (which doesn't use `SheetBuilder`).  Those other issues are probably driver bugs, so i'm going to say that this closes #11341.

### CODE REVIEW

**Comment by pchote** [comment]
Testcase: Launch the RA mod with `Graphics.SheetSize=1024` and open the map chooser.

**Comment by ltem** [comment]
I agree with closing #11341. My error doesn't change through this PR and I'm 100% certain that it is caused by something on my side (Linux AMD GPU drivers + Chromium Hardware Acceleration)

**Review by Mailaender — APPROVED** [review]

**Comment by reaperrr** [comment]
It doesn't fix #12109 though, so if #11341 is closed, the former should be re-opened.

**Comment by pchote** [comment]
Really? The voxel renderer uses `SheetBuilder` with `SheetType.BGRA` so the bug that this fixes definitely broke voxel rendering in a way that matches #12109.

**Comment by reaperrr** [comment]
Really. I just re-tested and made sure to re-compile.
vxl-turret-preview-bug

**Comment by pchote** [comment]
Huh... looks like you're right.  We have a reliable repro case now (start a game on Hot Springs, built one titan, then build but don't place a laser turret), so i'll look into this ASAP.

**Comment by reaperrr** [comment]
FWIW, if I build a hover tank, the preview changes to HVRTUR, if I destroy it, it reverts to the titan barrel.

**Comment by GraionDilach** [comment]
FWIW I always thought that #12109 was related to #11083 which was happening before depth stuff even got in.

**Comment by pchote** [comment]
I'm suspect that this ishappening because we somehow aren't re-rendering the voxel sheet for renderables that are drawn above the shroud (including PBOG).  They will then end up drawing whatever pixels were last drawn into their reserved region of the FBO sheet.

**Comment by pchote** [comment]
Added a fix for #12109.  The code was too lazy for its own good...

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
Could someone else confirm the voxel fix so we can get this merged?

**Review by abcdefg30 — APPROVED** [review]

**Pull request merged**
