### PR TITLE
Add IsDead check to fix crash in Sarin Gas 1

### LINKED ISSUE #16032: Crash on Saring Gas 1 20190106
"Soft crash", could exit..

Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor '4tnk (dead)' does not define a property 'Patrol'
  at OpenRA.Scripting.ScriptContext.FatalError (System.String message) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Scripting.TriggerGlobal+<AfterDelay>c__AnonStorey0.<>m__0 () [0x0004a] in <filename unknown>:0 
  at OpenRA.Effects.DelayedAction.<Tick>m__0 (OpenRA.World w) [0x00000] in <filename unknown>:0 
  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #16032

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I think we don't need the `else`, and is against the code standards we have been using everywere else.

Code should be:
```lua
	if mammoth.IsDead then
		return
	end

	mammoth.Patrol(MammothPath, true, 20)
```

**Comment by abcdefg30** [comment]
```
if not mammoth.IsDead then
	mammoth.Patrol(MammothPath, true, 20)
end
```
would be even better, imo.

**Comment by Smittytron** [comment]
Updated

**Review by pchote — APPROVED** [review]
Fix confirmed

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/528f0f88052a94821a28c5c030d82a1aa8cc4bb3

c3a8065b996ea60848f049ed188d1abb5d6826ec

**Pull request merged**
