### PR TITLE
Disable EnemyWatcher in all ra missions

### PR DESCRIPTION
**Pull request by abcdefg30**
IMHO it does not make sense in some of then.
(E.g. in allies05a when your spy drives with the truck into the enemy base, you get notifications...)

### CODE REVIEW

**Comment by abcdefg30** [comment]
Removed `EnemyWatcher` from all ra missions as "discussed" on IRC.

**Comment by Mailaender** [comment]
It would make sense to keep it in the survival missions, because you are mostly defending there. However I also noticed some overlapping with other announcements there so :+1: anyway.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/5bc609b346259ddb124254f457616d0d619d529e%5E...5bc609b346259ddb124254f457616d0d619d529e)

**Pull request merged**
