### PR TITLE
Rebalance a number of RA maps

### LINKED ISSUE #10718: [RA] The official map pool. Altering existing maps.
I encourage you to give specific feedback/contribututions to: 
**The Official Map Pool - collaboration thread** 
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=294875#294875

I've gone through the existing RA maps and noted specific changes that IMO needs to be done. The changes are partially aesthetic and some balance related. This may or may not give the map new life but in any case they will look much better in the map chooser and in-game. If we are to hold on to the classic maps, they should at least be up to par with competing maps on aesthetics and balance. I've done my best to preserve as much of the maps' original character with the recommended changes.

Separate issues will eventually be submitted for each map for a final review and chance for additional discussion. All maps have been thoroughly playtested and altered after feedback from players before being submitted individually.

Map and author names should stay unchanged unless the map is altered a lot beyond it's original structure.

**Map list:**

Screenshots and comparisons are found on the altered maps' pages.

[**Forest Path**](http://resource.openra.net/maps/7295/) (2 players)
Move player spawns one cell away horizontally from the ore patches.
Change layout of actors around secondary ore patches to equalize access for both spawns.
Switch out actors (trees) to vary the fauna.
[Altered](http://resource.openra.net/maps/9138)
**Playtested, submitted at #10928**

[**Keep Off The Grass 2**](http://resource.openra.net/maps/7242/) (2 players)
Move the first ore patch for both spawns to balance ore access.
[Altered](http://resource.openra.net/maps/9008/)
also see #10347 
**Playtested, submitted at #10954**

[**Man to Man**](http://resource.openra.net/maps/7196/) (2 players)
Remove oil derricks -or- access them by bridge.
[Altered](http://resource.openra.net/maps/9230/)
also see #10312
**Playtested, submitted at #10953**

[**Sidestep**](http://resource.openra.net/maps/8176/) (2 players)
Add edge ridges for more distinction.
Add more roads, actors and debris to make the map less blank.
[Altered](http://resource.openra.net/maps/9353/)
**Playtested, submitted at #10927**

[**Singles**](http://resource.openra.net/maps/7353/) (2 players)
Map structure overhaul. see #10301
Work on balance and aesthetics.
[Altered](http://resource.openra.net/maps/9487)
**Playtested, submitted at #10987**

[**Snowy Ridge**](http://resource.openra.net/maps/7996/) (3 players)
Move the first ore patch for all spawns to balance ore access.
Move horizontal ridge north to equalize size of north/south fields.
[Altered](http://resource.openra.net/maps/9373/)
also see #10712
**Playtested, submitted at #10952**

[**Doubles**](http://resource.openra.net/maps/7153/) (4 players)
Map structure overhaul. see #10303
Work on balance and aesthetics.
[Altered](http://resource.openra.net/maps/9489/)
**Playtested, submitted at #10988**

[**Chokepoint**](http://resource.openra.net/maps/7285/) (4 players)
Make the corners' cliff and ore more symmetrical.
Narrow the top water a little on it's west side so player A and D symmetrically has equal fields towards the chokes.
[Altered](http://resource.openra.net/maps/8920/)
**Playtested, submitted at #10833**

[**East vs West**](http://resource.openra.net/maps/7583/) (4 players)
Add more detail scenery.
Tweak spawn spots so as making them distinguishable in the lobby.
[Altered](http://resource.openra.net/maps/9367/)
**Playtested, submitted at #10950**

[**Temperal**](http://resource.openra.net/maps/7233/) (4 players)
Add actors and debris to out-of-reach and vacant areas.
Slightly tweak the north players poor economic start position.
[Altered](http://resource.openra.net/maps/9456/)
**Playtested, submitted at #10980**

[**Asymmetric Battle**](http://resource.openra.net/maps/6790/) (6 players)
Add actors (trees) to areas unlikely to be used for base-building and battle.
[Altered](http://resource.openra.net/maps/9157/)
**Playtested, submitted at #10951**

[**Encounter**](http://resource.openra.net/maps/7290/) (6 players) 
Make the corner ridges more symmetrical.
Make all ridges more distinctive.
Balance east/west ore patches for corner player spawns.
[Altered](http://resource.openra.net/maps/9516/)
**Playtested, submitted at #10798**

[**High & Low**](http://resource.openra.net/maps/7999/) - 8 players
East/west are uneven in build areas, distance to deploy site and the map is slightly offset from the middle. Needs an overhaul.
Make ridges around player spawns more distinctive.
Add roads from the edges of player spawns leading out to the middle ground.
[Altered](http://resource.openra.net/maps/9457/)
**Playtested, submitted at #10979**

[**North by Northwest**](http://resource.openra.net/maps/6720/) (8 players)
Add more ore mines.
Remove 4 x middle edge ore patches, replace with debris.
Remove trees outside 4 entrances to the middle ground.
Add decorative trees.
[Altered](http://resource.openra.net/maps/9486/)
**Playtested, submitted at #10985**

[**Mass Confliction**](http://resource.openra.net/maps/7427/) (12 players)
Fix uneven build areas east/west (8 cell difference!)
Make ridges more symmetrical east/west.
Make ridges more distinctive.
[Altered](http://resource.openra.net/maps/9376/)
**Playtested, submitted at #10949**

**Additional altered maps by other users:**

[Artic Triangle Resort](http://resource.openra.net/maps/8081/) (3 players) -Major structural overhaul including balanced ore access.

**Suggested maps to be altered:** - Murto The Ray

[Artic Triangle Affair](http://resource.openra.net/maps/1313/) (3 players)
Make starting ore equidistant from spawns and make room for all player's MCVs in middle.
 
[First Come, First Served](http://resource.openra.net/maps/7249/) (4 players)
Widen center passage to encourage larger armies.

[Puddles Redux](http://resource.openra.net/maps/7961/) (4 players)
Take ore from near middle and place nearer starting positions.

[Tabula Rasa](http://resource.openra.net/maps/6750/) (4 players)
Make oil derrick valley entrance equal in size for both sides.

[Vegetation](http://resource.openra.net/maps/8066/) (6 players)
Widen gap between players and add small gap where walls join with the outer wall.

 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30626271-ra-the-official-map-pool-reworking-existing-maps?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10798: [RA] Official Map Pool: Alter Encounter (6 players) - balance, aesthetics
[**Encounter, current**](http://resource.openra.net/maps/7290/), (6 players)

Changes:
Make the corner ridges more symmetrical.
Make all ridges more distinctive.
Balance east/west ore patches for corner player spawns.

[**Encounter, altered**](http://resource.openra.net/maps/9516/), incl. fixed bottom right player spawn..

encounter compare

encounter compare

### LINKED ISSUE #10833: [RA] Official Map Pool: Alter Chokepoint (4 players) - balance, aesthetics
[**Chokepoint, current**](http://resource.openra.net/maps/7285/) (4 players)

Changes:
Make the corners' cliff and ore more symmetrical.
Narrow the top water a little on it's west side so player A and D symmetrically has equal fields towards the chokes

[**Chokepoint, altered**](http://resource.openra.net/maps/8920/), playtested. No issues encountered.

chokepoint compare

chokepoint compare

### LINKED ISSUE #10927: [RA] Official Map Pool: Alter Sidestep (2 players) - aesthetics
[**Sidestep, current**](http://resource.openra.net/maps/8176/), (2 players)

Changes:
Made the map's edges more distinct.
Thicker fauna.
Variety of field debris.

[**Sidestep, altered**](http://resource.openra.net/maps/9353), altered and playtested. No issues encountered.

sidestep compare

sidestep compare

### LINKED ISSUE #10928: [RA] Official Map Pool: Alter Forest Path (2 players) - balance, aesthetics
[**Forest Path, current**](http://resource.openra.net/maps/7295/), (2 players)

Changes:
Players spawns and initial ore patches moved to equalize access for both spawns.
Altered ridges to balance build and unit access towards middle.
Change layout of actors around secondary ore patches to equalize access for north/south.
Varied the fauna.

[**Forest Path, altered**](http://resource.openra.net/maps/9138/), playtested. No issues encountered.

forest path compare

forest path compare

### LINKED ISSUE #10949: [RA] Official Map Pool: Alter Mass Confliction (12 players) - balance, aesthetics
[**Mass Confliction, current**](http://resource.openra.net/maps/7427/), (12 players)

Changes:
Fixed uneven build areas east/west (8 cell difference!)
Made ridges more symmetrical east/west.
Made ridges more distinctive.

[**Mass Confliction, altered**](http://resource.openra.net/maps/9376/), playtested. No issues encountered.

mass-confliction compare

mass-confliction compare

### LINKED ISSUE #10950: [RA] Official Map Pool: Alter East vs West (4 players) - aesthetics
[**East vs West, current**](http://resource.openra.net/maps/7583/), (4 players)

Changes:
Added more detail scenery.
Tweaked spawn spots so as making them distinguishable in the lobby.

[**East vs West, altered**](http://resource.openra.net/maps/9367/), playtested. No issues encountered.

east vs west compare

east vs west compare

### LINKED ISSUE #10951: [RA] Official Map Pool: Alter Asymmetric Battle (6 players) - aesthetics
[**Asymmetric Battle, current**](http://resource.openra.net/maps/6790/), (6 players)

Changes:
Added actors (trees and debris) to areas unlikely to be used for base-building and battle.
Added fences to edge positioned oil derricks.

[**Asymmetric Battle, altered**](http://resource.openra.net/maps/9157/), playtested. No issues encountered.

asymmetric battle compare

asymmetric battle compare

### LINKED ISSUE #10952: [RA] Official Map Pool: Alter Snowy Ridge (3 players) - balance, aesthetics
[**Snowy Ridge, current**](http://resource.openra.net/maps/7996/), (6 players)

Changes:
Moved the ore patches for all spawns to balance ore access.
Moved horizontal ridge north to equalize size of north/south fields. General tweaking of the ridges.

[**Snowy Ridge, altered**](http://resource.openra.net/maps/9373/), playtested. No issues encountered.

snow ridge compare

snowy ridge compare

### LINKED ISSUE #10953: [RA] Official Map Pool: Alter Man to Man (2 players) - balance, aesthetics
[**Man to Man, current**](http://resource.openra.net/maps/7196/), (2 players)

Changes:
Accessed the oil derricks by bridge to avoid Allied dominance (Transport Helicopter).
Tweaked ore fields to stall immediate run towards middle.
Added detail scenery.

[**Man to Man, altered**](http://resource.openra.net/maps/9230/), playtested. No issues encountered.

man to man compare

man to man compare

### LINKED ISSUE #10954: [RA] Official Map Pool: Alter Keep Off The Grass 2 (2 players) - balance, aesthetics
[**Keep Off The Grass 2, current**](http://resource.openra.net/maps/7242/), (2 players)

Changes:
Moved the first ore patch for both spawns to balance ore access.
Changed ridges and debris to balance fields around the players.  #10347
Tweaked the players spawn's first ore field after discussion below.

[**Keep Off The Grass 2, altered**](http://resource.openra.net/maps/9542/), Playtested (revision 4), altered to revision 5 after discussion below.

keep off the grass 2 compare revision

keep off the grass 2 rew

### LINKED ISSUE #10979: [RA] Official Map Pool: Alter High & Low (8 players) - balance, aesthetics
[**High & Low, current**](http://resource.openra.net/maps/7999/), (8 players)

Changes:
Fixed east/west uneven build areas, distance to deploy site and the slight map offset from the middle. 
Make ridges around player spawns more distinctive.
Add roads from the edges of player spawns leading out to the middle ground.

[**High & Low, altered**](http://resource.openra.net/maps/9457/), playtested. No issues encountered.

high low compare

high low compare

### LINKED ISSUE #10980: [RA] Official Map Pool: Alter Temperal (4 players) - minor balance, aesthetics
[**Temperal, current**](http://resource.openra.net/maps/7233/), (4 players)

Changes:
Add actors and debris to out-of-reach and vacant areas.
Slightly tweak the north players poor economic start position.

[**Temperal, altered**](http://resource.openra.net/maps/9456/), playtested. No issues encountered.

temperal compare

temperal compare

### LINKED ISSUE #10985: [RA] Official Map Pool: Alter North by Northwest (8 players) - balance, aesthetics
[**North by Northwest, current**](http://resource.openra.net/maps/7644/), (2 players)

Changes:
Add more ore mines.
Remove 4 x middle edge ore patches, replace with debris.
Remove trees outside 4 entrances to the middle ground.
Add decorative trees.

[**North by Northwest, altered**](http://resource.openra.net/maps/9486), playtested. No issues encountered.

north by northwest compare

north by northwest compare

### LINKED ISSUE #10987: [RA] Official Map Pool: Alter Singles (2 players) - balance, aesthetics
[**Singles, current**](http://resource.openra.net/maps/7353/), (2 players)

Changes:
Map structure overhaul. see #10301
Including altered ore patches, aesthetics.

[**Singles, altered**](http://resource.openra.net/maps/9487), playtested. No issues encountered.

singles compare

singles compare

### LINKED ISSUE #10988: [RA] Official Map Pool: Alter Doubles (4 players) - balance, aesthetics
[**Doubles, current**](http://resource.openra.net/maps/7153/), (4 players)

Changes:
Map structure overhaul. see #10303
Includes altered ore patches, aesthetics.

[**Doubles, altered**](http://resource.openra.net/maps/9489/), playtested. No issues encountered.

doubles compare

doubles compare

### PR DESCRIPTION
**Pull request by obrakmann**
Courtesy of @SoScared.

Closes #10718 (master ticket).

Closes #10798.
Closes #10833.
Closes #10927.
Closes #10928.
Closes #10949.
Closes #10950.
Closes #10951.
Closes #10952.
Closes #10953.
Closes #10954.
Closes #10979.
Closes #10980.
Closes #10985.
Closes #10987.
Closes #10988.

Closing this will be so amazingly satisfying :stuck_out_tongue:

### CODE REVIEW

**Comment by SoScared** [comment]
Thanks man! I'll miss having my issues dominating the front page :D

There are 2 others maps incoming, doubles and singles, on the master ticket. I'm in the process of playtesting them. I'll just submit them and reference them here when completed.

**Comment by SoScared** [comment]
Added Singles and Doubles:

https://github.com/OpenRA/OpenRA/issues/10987
https://github.com/OpenRA/OpenRA/issues/10988

**Comment by obrakmann** [comment]
Added those two as well.

**Comment by pchote** [comment]
:+1: great work guys.

**Comment by Mailaender** [comment]
In the map Encounter, the MCV can't be deployed on the bottom right spawn, causing AI bots to drive all the way up. Also human players will have an annoying start disadvantage.

**Comment by Mailaender** [comment]
Otherwise looking good. :white_check_mark:

**Comment by SoScared** [comment]
@Mailaender fixed, and updated the map issue and master ticket. had the latest map revision playtested several times on the stream. must have overlooked bottom right player moving the MCV.

**Comment by obrakmann** [comment]
The AI attacks wire fences in Temperal. Guess I'll have to play through all of those after all :/

**Comment by SoScared** [comment]
@obrakmann The wire fences is from the original map: http://resource.openra.net/maps/7233/

Is this fixable or does the bots have a hard on for fences? :)

**Comment by SoScared** [comment]
@obrakmann Heh :) Is that fixable or does the bots have a hard on for fences regardless?

**Comment by Mailaender** [comment]
The fences probably just have the wrong owner: creeps, another multi* etc.

**Comment by SoScared** [comment]
@obrakmann Also Bottom right AI killed off one house v07 (red) but left house v05 (white) alone. That doesn't make sense to me - I don't switch from the neutral actor tab. http://resource.openra.net/maps/9456/

I could remove them for simplicity sake, but I'd rather learn what happened and fix it.

**Comment by pchote** [comment]
The easy fix here would be to write a throwaway lint pass that checks for map actors that aren't owned by Neutral.  The one @SoScared just linked has a bunch of random actors owned by Creeps.

**Comment by GraionDilach** [comment]
That's not that simple though, preplaced visceroids, TS Floater etc. will need to be owned by Creeps.

**Comment by pchote** [comment]
Yes, which is why I suggested a throwaway lint pass that would only be used to identify issues in these RA maps, and then discarded.

**Comment by obrakmann** [comment]
Updated, changed all instances of `Owner: Creeps` to `Owner: Neutral`

**Comment by Mailaender** [comment]
Maybe we shouldn't create the `Creeps` player by default.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1859227b12a757093693056d5012051c1950e8eb...a30e89c733cd22ea9fe6e5e310ba0ea2cf7bf6ac)

**Comment by obrakmann** [comment]
Both d2k and cnc need the Creeps player, though.

**Comment by obrakmann** [comment]
Maps have just been uploaded to the resource center, too.

**Comment by SoScared** [comment]
Added a new revision of Keep of the grass 2 after some reasoning at https://github.com/OpenRA/OpenRA/issues/10954#issuecomment-202657100

Minor tweak of the players spawn's first ore patches. Worth a new revision:
http://resource.openra.net/maps/9542/

keep off the grass 2 compare revision

**Pull request merged**
