### PR TITLE
Expose TeslaZap duration to yaml.

### PR DESCRIPTION
**Pull request by GraionDilach**

### CODE REVIEW

**Comment by reaperrr** [comment]
An idea (not necessarily for this PR, but maybe a follow-up):
Replace the `doneDamage` boolean with a `DamageDuration` property, so modders can make the projectile deal damage over multiple ticks as well.

**Comment by GraionDilach** [comment]
IIRC LaserZap doesn't have that feature either so a followup where both gets it at the same time would make more sense.

**Comment by obrakmann** [comment]
:+1:

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b0a5f1c580e404e157053cf548d7541acef5b41a...5a025816b473eeccf823b0e806343b6cde24930e)

**Pull request merged**
