### PR TITLE
Add StyleCheck.exe.config

### PR DESCRIPTION
**Pull request by reaperrr**
Since #16196, this was automatically created on compile every time (on Windows, at least).

That's quite annoying on bleed. Adding it to the repo directly should fix the original issue without that side-effect from #16196.

### CODE REVIEW

**Comment by pchote** [comment]
The Game and Utility exes have config files committed to the repository, so wouldn't it make more sense for this too?

**Comment by reaperrr** [comment]
I don't know how differently things are treated on Linux/macOS, so I'm not sure. If we do add this config to the main folder, we probably have to revert #16196.

**Comment by reaperrr** [comment]
Updated. @portablestew @GraionDilach can you confirm that this works, too?

**Comment by pchote** [comment]
Confirmed that #14013 stays fixed on this PR, at least for me.

**Review by pchote — APPROVED** [review]

**Comment by portablestew** [comment]
Confirm that I can still "make check" on this branch, after building with MonoDevelop.

**Comment by GraionDilach** [comment]
I can't check this - the original bug was limited to my Travis tests only - https://travis-ci.org/AttacqueSuperior/Engine/builds/254123577 - and I still haven't got there to even reapply #13611 myself.

**Comment by reaperrr** [comment]
I'll take @portablestew's confirmation as +2, lgtm.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/524d4fe0ac71b182290845bcb302331948d0c12c...22b880c61caa6678344674c97f8b4bd77dca932d

**Comment by GraionDilach** [comment]
Can confirm that did managed to fix it. Better late than never.

https://travis-ci.org/AttacqueSuperior/Engine/builds/528098701

**Comment by pchote** [comment]
Just in time for it to be removed completely as part of #14182 :)

**Pull request merged**
