### PR TITLE
Fixed inappropriate usage of SharedRandom

### PR DESCRIPTION
**Pull request by Mailaender**
A broad-spectrum anti-desync against https://github.com/OpenRA/OpenRA/issues/11660.

### CODE REVIEW

**Comment by pchote** [comment]
The desync in #11660 isn't caused by SharedRandom.  SharedRandom is simply the first piece of `[Sync]`ed world state that the diverged game flow touches.  Removing these without understanding the actual desync will just push the bug to an even harder to reproduce corner of the engine.  This would be very unwise.

**Comment by Mailaender** [comment]
These are all safe imho as they have decorational or otherwise game state irrelevant pieces not use the expensive shared and synced random.

**Comment by pchote** [comment]
@obrakmann and @abcdefg30's testing appears to have isolated the desync to the scorch removals.  This is not an irrelevant piece, and there is no perf difference between the shared and synced randoms.  The scorch code was intentionally using synced random and sync-safe code so that we can have cross-client consistency when somebody finally decides to implement multicell craters.

**Comment by Mailaender** [comment]
Is the weapon sound randomization also shared on purpose?

**Pull request closed without merging**
