### PR TITLE
D2K - Add Sihaya Ridge to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
This is the only 3PLAYX map, so i wanted to get it out of the way while i have some time.

http://resource.openra.net/maps/20633/

### CODE REVIEW

**Comment by ltem** [comment]
:+1:

**Review by obrakmann — CHANGES_REQUESTED** [review]
The three worm spawns are all located near the players in the lower right. Can we distribute those a bit more evenly/fairly, please?

In general it seems that this map favours the two top-most players. The spice field in the top right is pretty much uncontested.

**Comment by MustaphaTR** [comment]
@obrakmann This is a vanilla map, i don't think it is time to edit something yet. We can take a look to balance the maps after all are added.

**Review by obrakmann — COMMENTED** [review]
👎 I don't think we should add it then. There's no point to having a map that will just frustrate half of its players.

**Comment by MustaphaTR** [comment]
Actually, locations of Worm Spawners indeed doesn't make much sense, i'll edit that. But not planning to touch the spice fields.

**Comment by ltem** [comment]
From the point of implementing all the vanilla maps, this map should be added and I see the worm spawner repositioning as reasonable and good change (I have overlooked that).

From the point of adding preferably balanced maps, this map has some problems and quite possible wouldn't fulfill this selection criteria.

So as far as I know the goal of the d2k-mod is to recreate the original game and I would lean towards adding the map, even if I fully understand the point of declining imbalanced things.

**Comment by MustaphaTR** [comment]
If we really don't want this map, i can just closr this PR and note that this map won't be added on #12788. I agree that this map is far from being balanced.

**Comment by pchote** [comment]
I support @obrakmann's opinion here.  If everyone knows this is crap and needs to be replaced then we're better off not taking it in the first place.  Community made maps can fill the gap.

**Pull request closed without merging**
