### PR TITLE
Helis return to nearest base like Planes

### LINKED ISSUE #13173: Choice of helipad for reloading
Hinds and Longbows seem to reload at the previous helipad they were. Not the closest one. 
On the opposite, Yaks and Migs seem to choose the closest one. 

Is there any reason for this different behaviour ?

### PR DESCRIPTION
**Pull request by rob-v**
Heli unification of behaviour with Plane

Closes  #13173

### CODE REVIEW

**Comment by pchote** [comment]
The reactions we had to deal with from parts of the player community the last time we fixed issues with the aircraft RTB behaviour really puts me off wanting to deal with this part of the code again.  

Could somebody please check through the discussions linked from the [release-20161015 changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/561383b9ba791a557cde37616f42a8df7d8a3182) and make sure that this fix isn't breaking somebodies pet broken edge case?

**Comment by rob-v** [comment]
An idea - instead of returning to nearest/oldest base, helis and planes return to primary base

**Comment by rob-v** [comment]
Looking briefly at all those requests and issues I understand why you are worried. In this case I think this is wanted and safe feature - you can compare ReturnToBase.ChooseAirfield with HeliReturnToBase.ChooseHelipad - the behaviour is unified and requested.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b0c0ef5c21696bfc32b678243f22bad68c61846e...cdd8ca43f44667beaf4a5620d9223f67f7ecd848

**Pull request merged**
