### PR TITLE
Sync members of base classes

### PR DESCRIPTION
**Pull request by RoosterDragon**
The method that generates sync hashing functions for traits was missing out non-public members in base classes of that trait. This meant the hash function might not be syncing over all the members you had tagged.

Now, if a trait has a base class with syncable members, we ensure these are included when hashing the state of the trait. This is verified by a test.

I also include a test to guard against unintended changes of the output from the sync mechanism in the future.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
Looks sensible, so :+1: after fixing the namespaces (either pulling the sync up, or I guess more likely pushing the other ones down).

**Comment by RoosterDragon** [comment]
Updated to keep namespace consistent with existing tests.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/2fb00570c781e5d07b3ef0892576ca418f3528a9%5E...2fb00570c781e5d07b3ef0892576ca418f3528a9

**Pull request merged**
