### PR TITLE
Show a tooltip for titles and author in map chooser

### LINKED ISSUE #19108: Mouseover whole mapname in map chooser
For long names, you cannot see the end of the name, and then you are not sure what version of the map you have.

My fix is to try to delete maps, then you can see the whole name.
Mouseover displaying whole name of map would be nice.

### PR DESCRIPTION
**Pull request by dragunoff**
An attempt to fix #19108 

But the tooltip won't show up. Either I'm missing something or there's something wonky going on :thinking: Help appreciated.

### CODE REVIEW

**Comment by pchote** [comment]
Try checking whether `TOOLTIP_CONTAINER` is actually visible - it might be attaching the tooltip to the hidden lobby one instead of the one you're defining here. IIRC we have fixed this issue in other places by giving the container a different name.

**Comment by dragunoff** [comment]
> Try checking whether `TOOLTIP_CONTAINER` is actually visible - it might be attaching the tooltip to the hidden lobby one instead of the one you're defining here. IIRC we have fixed this issue in other places by giving the container a different name.

I tried pointing it to a different tooltip container and still nothing :thinking: I don't think it's picking up the mouse event at all.

**Comment by pchote** [comment]
Did you make any more progress on understanding this while working on #19544?

**Comment by dragunoff** [comment]
> Did you make any more progress on understanding this while working on #19544?

No, I didn't. I suspect it may be related to the grid layout because tooltips work for scroll panels the use the list layout.

**Comment by pchote** [comment]
The problem is that the labels below the map preview don't define a height, so they have no event bounds to trigger the tooltip.

**Comment by dragunoff** [comment]
> The problem is that the labels below the map preview don't define a height, so they have no event bounds to trigger the tooltip.

Thanks, that completely eluded me. I added heights to all of the labels and re-positioned them. This is ready for review now.

**Review by Smittytron — DISMISSED** [review]
LGTM

**Review by abcdefg30 — APPROVED** [review]
Also removed the test case.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ba58e246279db0889908f8d447cd9a2ce8a817c7...fc7b5613bf37724706ad2316498494e10c7e0cc2)

**Pull request merged**
