### PR TITLE
Add Moebius, Chan and Delphi to TD

### LINKED ISSUE #11387: TD: Missing scientist unit
There are a few missions with scientist units: Dr. Mobius and Dr. Wong Hu Chan. 
Compared to civilians they...
- Can't attack.
- Feature different animations.
- Have different voice samples.
- Display their full name in the tooltip.

**Following missions use those scientists:**
- GDI 8b (Dr. Mobius)
- GDI 12a (Dr. Mobius)
- GDI 12b (Dr. Mobius)
- Nod 10a (Dr. Wong Hu Chan)

Required for: #4988

### PR DESCRIPTION
**Pull request by reaperrr**
Also used the opportunity to clean up civilian sequences and fix voices.

Closes #11387.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by GraionDilach** [comment]
:+1:

**Comment by Mailaender** [comment]
Thanks!

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e95b192f856205878dec5cded43309c5d08b1527...db3f012595a3a3eee9aa03383ec46c4f8b480165)

**Pull request merged**
