### PR TITLE
Fixed all cheat code

### PR DESCRIPTION
**Pull request by pevers**
Polished #7505 to activate all cheat codes on call and reset all on call.

### CODE REVIEW

**Comment by Unit158** [comment]
:-1: This now limits the /all cheat to Developer Mode cheats.

**Comment by Unit158** [comment]
Actually, that could be fixed in other ways. You need to make sure that all the effects from the cheats that it previously activated are still activated, however.

**Comment by pevers** [comment]
I think I don't fully understand. Are there other modes? Future modes may have total different behaviour for disabling/enabling all cheat codes, right? So is DeveloperMode specific code a problem?

**Comment by pchote** [comment]
This looks like a good idea, but I haven't tested it yet.  #7505 has always annoyed me.

**Comment by Unit158** [comment]
Disregard my first comment; I misunderstood the code. My problem is that /all doesn't currently activate the effect of DevGiveCash or DevLevelUp. I just like having the extra cash after calling /all. In any case, +1

**Comment by pevers** [comment]
I could add DevGiveCash and DevLevelUp too? I wasn't totally sure if I should add this or not.

**Comment by pchote** [comment]
DevLevelUp doesn't make a lot of sense for this, since it requires you to have actors selected.

**Comment by obrakmann** [comment]
:+1: once DevGiveCash has been added

**Comment by penev92** [comment]
I'd say give something like 100k in order to simplify things (just hardcode it) and squash the commits.

**Comment by Phrohdoh** [comment]
Let's not hardcode it.
It already has a default value.

**Comment by pevers** [comment]
The commits are now squashed.

**Comment by obrakmann** [comment]
Thanks!

[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/3915830cf574aef71c0904a517ef93e379520aff%5E...3915830cf574aef71c0904a517ef93e379520aff)

**Comment by Mailaender** [comment]
The shroud is not disabled anymore when I type `/all`.

**Comment by pevers** [comment]
Oops, I missed that. Sorry, I'll open a PR.

**Pull request merged**
