### PR TITLE
Restore two-button prompt for two-button dialogs.

### LINKED ISSUE #10665: ConfirmationDialogs.PromptConfirmAction dialog should size to match buttons
It looks a bit ridiculous to have a wide dialog with only two buttons.
This can be easily fixed by defining the narrow/wide widths on dummy child widget, like we do for the world tooltips.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30386621-confirmationdialogs-promptconfirmaction-dialog-should-size-to-match-buttons?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Closes #10665.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
No changelog, since #10665 is kinda a regression.

**Comment by pchote** [comment]
You can include this PR # in the changelog entry for the original feature.

**Comment by abcdefg30** [comment]
Done: [Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5817de267c1b59d059f971603000b36bdcbd62c4...b7d86f4cf5ca8acc0876677b193d8fb66488d2e1)

**Pull request merged**
