### PR TITLE
Fix Ant sharing cell

### LINKED ISSUE #15235: RA Ants share cells on bleed
Regression from #14893.  The `SharesCell` override was missed when porting over locomotors.  Revealed by #15201.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #15235.

### CODE REVIEW

**Comment by pchote** [comment]
I wonder if we could get away with using the tracked locomotor instead.  This would save on memory and domain calculations, and only changes things by 10%

**Comment by reaperrr** [comment]
I was wondering about that, too. Let's at least use 'lighttracked' though, because iirc, ants didn't crush infantry in the original.

**Comment by reaperrr** [comment]
Updated.

**Review by Smittytron — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/60e14108a191ffcd851e401851112fd44ab40312...f4ba054160f3e1c72f5c5acd2c9f48ee3d545342)

**Pull request merged**
