### PR TITLE
Fix compatibility with macOS's dark mode.

### LINKED ISSUE #15369: Enable macOS 10.14 dark mode support
Info.plist needs to override `NSRequiresAquaSystemAppearance` to false.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #15369.

~~Test build: [removed]~~
Updated test build: https://www.dropbox.com/s/w8utrsgy21hs59h/OpenRA-darkmode-fix-2.dmg?dl=1

### CODE REVIEW

**Comment by Punsho** [comment]
Hello, I use mac os dark mode and the the game worked flawlessly for me in this hot fix and the version before it. This test build loads up the game not with the usual load screen screen but starts with a grey one and then continues to the original load screen. Whenever I start up a game/ replay/ map editor I can not edge scroll, it's like the game isn't fully full screen. The bug fixes permanently (atliest until I restart the program) when I move to another desktop and back (On mac os fullscreen works like a separate desktop and you work with multiple desktops on one monitor). When playing windowed the the dark theme works like it should and makes the top part of the window grey unlike the previous versions

**Comment by pchote** [comment]
I can reproduce the edge-scroll bug, but I don't know what you mean about the grey screen.  Can you please post a screenshot or video showing that?

**Comment by pchote** [comment]
Fixed the edge scroll issue - I was dropping the focus event that is needed for the game to know it is focused.

Updated test build: https://www.dropbox.com/s/w8utrsgy21hs59h/OpenRA-darkmode-fix-2.dmg?dl=0

**Comment by Punsho** [comment]
ezgif com-video-to-gif-2
here's a gif recording the grey screen, it shows it when the game is starting up and when I exiting it

**Comment by pchote** [comment]
That looks like the dark mode equivalent to the light-grey that has always showed up if the startup is delayed due to runtime weirdness.  I can't reproduce that specifically here now, can you try again on the updated version?

**Comment by Punsho** [comment]
It's the same with the updated version also when when using the light theme the screen is white, it used to be black what is a lot more pleasing to the eye when it suddenly switches to the proper loading screen

**Comment by pchote** [comment]
Considering that we don't have any other macOS devs to review this and my call for testers in the Discord channel didn't get any responses, I will set a deadline of Sunday UTC and then merge this to avoid holding up the playtest.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/fd21cbd1c03336e1d481bbded3c8c47b6e64ebfb

**Pull request merged**
