### PR TITLE
Rewrite BlowfishKeyProvider.ProcessPredata using safe code.

### LINKED ISSUE #2441: MixFile.RaHeader, duplicate values found
On map room-warzone with release-20121019, playing as Allies, closed as game began. exception.log contains:

```
Exception of type `System.ArgumentException`: MixFile.RaHeader, duplicate values found for the following keys: 2811818068: [(offs=1376304610, len=1436818881),(offs=1303428578, len=3844756581),(offs=3932274146, len=504285086),(offs=261406178, len=2011127635),(offs=3772169698, len=2458156051),(offs=4124556770, len=1657300316),(offs=394575330, len=2763129078),(offs=3464150498, len=1912530027),(offs=3887775202, len=1535573085),(offs=1667349986, len=1651050265)], 3255518541: [(offs=1099208783, len=3303102605),(offs=3604191311, len=3972225307),(offs=2693699663, len=316463550),(offs=2821888079, len=2932147912)], 2925018180: [(offs=118932477, len=331163447),(offs=2042545149, len=4248835109)], 3575071090: [(offs=2624743082, len=3797053306),(offs=1751213738, len=1182934561)], 1243613079: [(offs=1637127797, len=3841171263),(offs=3865482869, len=2023497237)], 3284888157: [(offs=687789427, len=358779927),(offs=3138704755, len=4230776020),(offs=1887884659, len=3736988869)], 465091051: [(offs=1882287750, len=3730501625),(offs=3090378374, len=4279611615)], 3851858380: [(offs=197200840, len=1913283067),(offs=83561416, len=2673869643)], 3683159305: [(offs=867278684, len=1087770530),(offs=2663358300, len=3130547281),(offs=1722326876, len=1312637092)], 400405198: [(offs=2385359528, len=400405198),(offs=1218818728, len=1142595513)]
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.FileFormats.MixFile..ctor(String filename, Int32 priority)
   at OpenRA.FileFormats.FileSystem.OpenPackage(String filename, Int32 order)
   at OpenRA.FileFormats.FileSystem.OpenPackage(String filename)
   at OpenRA.FileFormats.FileSystem.<Mount>c__AnonStoreyF.<>m__2E()
   at OpenRA.FileFormats.FileSystem.Mount(String name)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, Boolean isShellmap)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Game.<Tick>c__AnonStorey39.<>m__9E()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey30.<>m__69()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.Tick(OrderManager orderManager)
   at OpenRA.Game.Tick(OrderManager orderManager, Viewport viewPort)
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98049-mixfile-raheader-duplicate-values-found?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #2441.  This error would occur when the memory
regions were allocated at particular addresses when
running a mono-compiled binary on a .net runtime.

The data would be copied to the pointer returned
from a fixed() statement, but the managed array
would _not_ be updated with the new data.  This
caused DecryptKey to silently return a bogus key
full of zeros, and the mix file header decryption
would subsequently fail.

### CODE REVIEW

**Comment by pchote** [comment]
There may be other dragons hiding in the blowfish code, but this is sufficient to pass the "load all the mix files 100 times without dying" test.

**Comment by RoosterDragon** [comment]
:+1: YES

**Comment by obrakmann** [comment]
I can still start games in all four mods, the asset browser still works, too. I guess we'll have to wait and see how this turns out when it's released and receives wide-spread testing. :+1:

**Comment by cjshmyr** [comment]
:tada:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/be8b6fa0faf3090265f993e8c6e51d2734dcd6d7)

**Comment by reaperrr** [comment]
> when running a mono-compiled binary on a .net runtime.

That explains why us self-compilers could never reproduce it.

**Pull request merged**
