### PR TITLE
Pause MovePart when Mobile is paused.

### LINKED ISSUE #17043: Regressed Thief behaviour
From https://forum.openra.net/viewtopic.php?p=310692#p310692:
> Thiefs miss their target, they often just run by and bug out. After this they forget their target.

A quick test on bleed confirmed this.

### PR DESCRIPTION
**Pull request by tovl**
This was an oversight from #16262

Fixes #17043

### CODE REVIEW

**Comment by pchote** [comment]
As mentioned in #17043, I'm on the fence about whether this is the best approach.

If we restore pausing stopping movement immediately we will be forced to introduce a third state for `Mobile` (using Subterranean/Jumpjet locomotors) and `Aircraft` that disables player input but allows the unit to continue moving to land or surface.

IMO "reject player input and move to a safe/valid location before stopping" is a completely reasonable default behaviour for pausing, and cases like the Hijacker that really do want to freeze the unit immediately have the option of enabling a speed modifier.

What do we gain by going this route instead?

**Review by ghost — APPROVED** [review]
Fix works.

**Comment by tovl** [comment]
This fixes the regression part and restores the thief to its current (stable) behaviour. The other use cases are not part of stable mods yet, so do not require a quick fix.

I agree that always going to a valid location instead of stopping on the spot is the more sane behaviour, but there are several snags in the current movement logic that prevent that from working properly (especially with regards to turning). I have been busy for a while now with a rigorous rework of the movement logic that will (hopefully) address those issues in a more robust way, but that is way out of scope for next release. In the mean time, I am hesitant to add more workarounds that may make that job more difficult. 

I am also not sure if a proper implementation of the hijacker behaviour would absolutely need freezing on the spot either and would be more happy if there where no exceptions to the rule at all (so speed modifiers would also only apply after the current MovePart has ended).

**Comment by GraionDilach** [comment]
> (so speed modifiers would also only apply after the current MovePart has ended)

Please no. Ares's AttachEffect-based SpeedMultiplier: 0 case freezes units on the spot and that distinction has usecases within the modding scene.

**Comment by tovl** [comment]
So what does that do to units coming up behind?

**Comment by pchote** [comment]
In that case I agree that it makes sense to restore the previous behavior and defer discussion/other changes until your rework is ready.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/d4c50d605deeff723a9540c1f8fd4b96b98b74b2

a93fbc3219

**Pull request merged**
