### PR TITLE
Eliminated superfluous linendings

### PR DESCRIPTION
**Pull request by Phoib**
Eliminated linendings from player files

### CODE REVIEW

**Comment by pchote** [comment]
Looks good to me, thanks. :+1:

**Comment by penev92** [comment]
Fwliw the utility automatically adds those every time you run an upgrade.

**Comment by Mailaender** [comment]
Yeah, thanks. This only adds even more noise when you run it now.

**Comment by Phoib** [comment]
But why does the tool add it, if it is against the styling convention?

**Comment by penev92** [comment]
Because it needs some love, but nobody has been interested in giving it.

**Comment by Mailaender** [comment]
Fixed in https://github.com/OpenRA/OpenRA/pull/10384.

**Pull request merged**
