### PR TITLE
Ignore modifiers when applying initial placement damage.

### LINKED ISSUE #19633: Player's buildings explode with high handicap and without concrete (Dune 2000)
## Issue Summary

Buildings explode if player have high handicap and place buildings not on concrete (Dune 2000)

## Reproduction

1. Set up your handicap to 95%
2. Order wind traps
3. Place it on ground without concrete

## Expected behavior

BOOM

### PR DESCRIPTION
**Pull request by pchote**
Fixes #19633.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]
Works

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
Something still isn't right. When placing a building with 95% handicap it starts at half health as expected, but drops down to the red when starting to repair.

**Comment by pchote** [comment]
Good catch, I should have thought to have tested that...

Updated and added comments.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/059bea0312ba00c6857929ad8365ec68acd53413...07591750c52281a947feac03d38ae56133a3bd58)

**Pull request merged**
