### PR TITLE
Don’t crash when asking for the offset of an invalid subcell.

### LINKED ISSUE #7813: IndexOutOfRangeException: OpenRA.Map.OffsetOfSubCell
Exception log here: https://gist.github.com/deniz1a/6c27c3e704c195f9e737

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10288895-indexoutofrangeexception-openra-map-offsetofsubcell?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7975: Playtest-2015-045-18 crashes with destruction of MCV
https://gist.github.com/GrayHatter/126f9a9ad82a16b0dd7b

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11484469-playtest-2015-045-18-crashes-with-destruction-of-mcv?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #7813.
Fixes #7975.

### CODE REVIEW

**Comment by pchote** [comment]
Confirmed that this fixes the crash in http://www.megafileupload.com/X7i/OpenRA-2015-04-19T012428Z.orarep

**Comment by Mailaender** [comment]
:+1:

**Comment by penev92** [comment]
Replay doesn't crash and fix seems reasonable :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/770276c499efeebe4fac8df2a12734f08fd502a8...6e803ed7240c688f303d5f8f7791a765a18cece3)

**Pull request merged**
