### PR TITLE
Fix RA-uibits dependency in D2k and TS

### PR DESCRIPTION
**Pull request by reaperrr**
Copies ui elements to D2k and TS instead of loading them from RA.

### CODE REVIEW

**Comment by Mailaender** [comment]
:-1: on the duplication. Move it to `mods/common` instead.

**Comment by reaperrr** [comment]
I'll wait with updating until #9744 is merged.

**Comment by reaperrr** [comment]
Updated.

Moved the art to each mods' buttons.png instead and removed the separate files from RA. I know I could have packed them more densely, but I wanted to keep position consistent across mods.

**Comment by Mailaender** [comment]
Hmmkay... I guess saving sprite sheets on runtime is more beneficial than avoiding duplicated artwork. Still works. :white_check_mark:

**Comment by obrakmann** [comment]
Seems ok. Couldn't spot any misalignments in any mods during a quick check. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/9905ff86d3c68fd30a89c07b62fc0e804da71f80)

**Pull request merged**
