### PR TITLE
TraitDictionary use EmptyEnumerable

### PR DESCRIPTION
**Pull request by anvilvapre**
A static Enumerable.Empty<T> is 14% faster over AllEnumerable, 25% faster over MultipleEnumerable - as the cost of having to check if the actors list is empty.

5% of all TraitDict queries seems to return an empty result (during a 1 minute game replay).

--
Extended the trait report with more columns. Should have no performance impact - apart increasing an integer if GetMultiple returns no results.

Example trait report output
```
Actors  Traits  QTotal  QActors QAPred  QAll    QGet    QMult   QMulNA  Trait
20      20      22670   0       0       22590   0       50      30      Production
464     464     15224   0       0       0       0       15203   21      HitShape
167     167     5912    0       0       0       0       3173    2739    IDisableEnemyAutoTarget
172     172     5095    0       0       0       5095    0       0       Mobile  
457     457     3446    0       0       0       3446    0       0       IHealth 

```
Actor column could be improved to show unique actors.

### CODE REVIEW

**Comment by reaperrr** [comment]
Travis is reporting some style errors. You can catch these locally by running make->check.

**Comment by pchote** [comment]
Wouldn't it be better to use comma separators so it can be loaded directly as a csv?

**Comment by pchote** [comment]
A general style nit: Please make sure the first line of the commit message is a short description < 50 characters. This keeps it readable in the github and local client histories.  Extended commit info can be added after two linebreaks.

**Comment by anvilvapre** [comment]
I now realize. The empty enumerations will only work if other objects won't keep references to the enumerations and reuse them.

**Comment by pchote** [comment]
Caching and reusing enumerables is used in several places as an optimization.

**Pull request closed without merging**
