### PR TITLE
Reset Ready status of players in Lobby when options change

### PR DESCRIPTION
**Pull request by praetp**
This is my first contribution. Let me know if I overlooked something.

### CODE REVIEW

**Comment by dragunoff** [comment]
Thanks for your contribution!

Closes #11274

**Review by abcdefg30 — APPROVED** [review]
Works as advertised.

**Review by abcdefg30 — DISMISSED** [review]
Actually scratch that, we're just invalidating the state of a single client, while it should loop over all clients and mark them as not ready.

**Comment by abcdefg30** [comment]
Testcase: You need to have 3 clients in one lobby, mark two as ready and change the settings with the third.

**Comment by praetp** [comment]
Don't all clients receive this message then?
And then publish their updated state?

**Comment by abcdefg30** [comment]
No, you're just updating the local client at the moment. Apparently sending that state change requires something like this: https://github.com/OpenRA/OpenRA/blob/23b3c237b7071fd308c4664b0b6c5d719c0f3c74/OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs#L72
(We might be able to do without `RunAfterTick`, but I don't know for sure.)

**Comment by abcdefg30** [comment]
I don't know enough about this code and can't look it up right now. If you can't find the solution yourself feel free to ping me later.

**Comment by praetp** [comment]
Agree this commit is not ready yet.. will have a look at your suggestion.

**Comment by praetp** [comment]
@abcdefg30 I tried the test case you suggested and it works as expected now (with your suggestion).

**Comment by abcdefg30** [comment]
Did you test what happens when we just use `orderManager.IssueOrder(Order.Command("state {0}".F(Session.ClientState.NotReady)));` without `RunAfterTick` like we do in the rest of `UnitOrders`? I did a quick test and it seems to work as well, so I'd prefer doing it without `RunAfterTick` if we can.

**Comment by praetp** [comment]
No. OK, if you tried it, let's go for that approach then.

**Comment by praetp** [comment]
@abcdefg30 +2 and submit ?

**Comment by abcdefg30** [comment]
Sorry, I hadn't noticed you already updated this.

**Review by abcdefg30 — APPROVED** [review]

**Comment by penev92** [comment]
Looks good.
Thanks for contributing!

P.S.: [Changelog.](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/463417b936cf6caeb39b9ce9940511675f8b8687...4ee8c6a8a48c06007277e435988718ed26b43397)

**Pull request merged**
