### PR TITLE
Renamed non-conforming .yaml to .oraml

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/4856.

I used the following script: https://gist.github.com/Mailaender/0d1b83680f51afcdceb1d24a430a32f2

### CODE REVIEW

**Comment by pchote** [comment]
IMO the ship on #4856 sailed years ago, and the disruption that this will cause massively outweighs the benefits.  This will break all downstream mods and tooling, all third party maps, the resource center itself, all open PRs, and i'm sure many other things.

**Comment by pchote** [comment]
If people are still interested in pushing forward with #4856 then someone will need to take charge of managing the migration.  First a decision on the name needs to be made, and then all our side/supporting projects (resource center, mod sdk, tileset builder, etc) that use yaml will need to be updated to work with both.  This and community notification will need to be done at least a release before the main file changes.  It also shouldn't be mixed in with other controversial changes such as shipping all of our maps unpacked.

**Comment by Mailaender** [comment]
We could also keep supporting `mod.yaml`, `map.yaml` and `settings.yaml` for backwards compatibility.

@ihptru Would you help adding support for the `.oraml` extension for http://resource.openra.net/maps/?

**Comment by reaperrr** [comment]
Tbh, both as maintainer and modder my motivation to deal with this is rather low. The only benefit I see is that people like the creator of #4856 and maybe a few programs/plugins wouldn't get mislead by the extension, but I really wonder whether the number of such cases is high enough to justify such a huge undertaking that just creates inconvenience for every modder that has no real issues with the yaml extension (and I expect those to be the majority by a *huge* margin).

**Comment by Mailaender** [comment]
There are some editors where it is extremely bad https://github.com/OpenRA/OpenRA/issues/2310. For example in @Geany I can't see the cursor nor marked text and everything is red with a dark grey background except the header:

image

Also @GitHub started formatting yaml a while ago also enforcing tabs marked red 
```yaml
^BallisticWeapon:
	ReloadDelay: 40
	Range: 4c768
	Report: tnkfire6.aud
	Projectile: Bullet
		Image: 120MM
		Speed: 682
		Shadow: true
	Warhead@1Dam: SpreadDamage
	Spread: 128
		Damage: 40
		Versus:
			None: 25
			Wood: 100
			Light: 100
			Heavy: 100
		DamageTypes: Prone50Percent, TriggerProne, ExplosionDeath
	Warhead@2Smu: LeaveSmudge
		SmudgeType: Crater
		InvalidTargets: Vehicle, Structure, Wall, Husk, Trees, Creep
	Warhead@3Eff: CreateEffect
		Explosions: small_frag
		ImpactSounds: xplos.aud
		VictimScanRadius: 0
```

The change is easily automated and resolves this issue once and for all. OpenRA modding should be way newbie friendlier this way.

**Comment by GraionDilach** [comment]
>OpenRA modding should be way newbie friendlier this way.

Custom extensions are more than likely throw newbies off at Windows, because they will manually require to associate their preferred text editor with the new extension. Think the same applies to Linux as well, although I guess metadata can be shipped there about the extension. Either way, I heavily disagree with this statement of yours.

Also take note that the OpenRA YAML parser accepts space-indenting by now, there's been revisions with space indentations during CD development.

**Comment by Mailaender** [comment]
> Custom extensions are more than likely throw newbies off at Windows, because they will manually require to associate their preferred text editor with the new extension. Think the same applies to Linux as well, 

That is a valid argument for Windows. On Linux desktop the system detects it as `Text (text/plain)` regardless of the file extension.

Shall we go with space indention instead and adhere to the yaml specification now that the parser supports it?

**Pull request closed without merging**
