### PR TITLE
Report mission briefings in the mp lobby.

### LINKED ISSUE #8901: Allow text-field for maps in lobby
When you start a custom game, we need a text-field or text printet in chat for us to know how to set it up. Etc. ant party: how many do we need of each faction?
And text can also tell what we need to know in the map: oil in the middle, tanks hp:2000 etc..

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25284434-allow-text-field-for-maps-in-lobby?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Closes #8901.

### CODE REVIEW

**Comment by GraionDilach** [comment]
>OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:L857: [SA1507] The code must not contain multiple blank lines in a row.

**Comment by obrakmann** [comment]
This is certainly one way to do it, :+1: 

I wouldn't agree that this closes #8901, though.

**Comment by pchote** [comment]
> I wouldn't agree that this closes #8901, though.

Why not?

> When you start a custom game, we need ... or text printet in chat for us to know how to set it up.

This lets custom maps print text inot the chat.

**Comment by pchote** [comment]
Updated.

**Comment by obrakmann** [comment]
I was imagining something more user-interface-y than abusing the chat once more, but yeah, it'll work. We won't find any free place in the lobby UI anyway.

**Review by RoosterDragon — CHANGES_REQUESTED** [review]
Please extract a common method for grabbing the briefing string.

**Comment by pchote** [comment]
Done.

**Review by RoosterDragon — COMMENTED** [review]
Code looks fine, but I have not tested it.

**Review by RoosterDragon — APPROVED** [review]

**Comment by RoosterDragon** [comment]
(Still needs another +1 - please do not count my 'approved' review as such in this instance)

**Comment by reaperrr** [comment]
Tested and works as advertised :+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6ed72aea81b2a50e3d428e9e7437003b4eb973f1...58b1d17c2db03ada148a6875875e6708a63fd641)

**Pull request merged**
