### PR TITLE
Fix RGB map previews

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by Mailaender** [comment]
I always wondered if we should link all those duplicate images.

**Comment by obrakmann** [comment]
I *think* that they only end up only once in the git repo anyway, since the blobs all get the same SHA.

**Comment by Mailaender** [comment]
Guess this is a followup of https://github.com/OpenRA/OpenRA/pull/7951. RA mission browser previews work fine. :white_check_mark:

**Comment by penev92** [comment]
:+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9eefbddf04503290d1e9d5c71b7c5a42dbe5b79e...87f2607fed35279165a6bdcf663e04632b29f972)

**Pull request merged**
