### PR TITLE
Fix zombie sequence mess

### LINKED ISSUE #15633: The zombie has a bad frame & an incorrect start for its idle1 sequence
The RA zombie.shp contains a black bar on frame 108(ora-107) x,y:[13-27,1]
It also contains four black pixels that should be red blood x,y:[6,3][22,0][37,3][37,6]

The zombie idle1 sequence should start at '95' not '96':
https://github.com/OpenRA/OpenRA/blob/d9946f63e4d62e1dc4d084cc87af069e33296b99/mods/ra/sequences/infantry.yaml#L1308

Revised zombie.shp:
[zombie.zip](https://github.com/OpenRA/OpenRA/files/2407850/zombie.zip)

### PR DESCRIPTION
**Pull request by abc013**
Closes #15633.

- Removed black points and the line as described in #15633
- Adjusted the die sequence lengths, which are apparently a frame longer
- Duplicated frame 72 (duplicate is frame 75); Every attack facing had 4 frames but the one to the left

### CODE REVIEW

**Comment by reaperrr** [comment]
> Duplicated frame 72 (duplicate is frame 75); Every attack facing had 4 frames but the one to the left

Wouldn't that shift the Start frame of later sequences by 1?

**Comment by abc013** [comment]
Attack frames begin at 64. They go till 64 + 8*4 which means 96. That's where idle1 starts, which is correct. So actually, the offset was wrong by one before the fix. You can check this by looking into the asset browser if you want.

**Review by abcdefg30 — DISMISSED** [review]

**Review by reaperrr — APPROVED** [review]
Changes look good to me

**Comment by reaperrr** [comment]
The changes were fine, but I took the liberty to make the following changes:
- Merged 3rd commit into 1st, with a short commit message.
- Added two fixes of my own: `stand2` sequence made the zombie randomly turn around its axis because it had `Length: 8` when it should have been `Facings: 8`, and `run` sequence tick rate adjusted to match other infantry.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/985e4de3155037600e8d269bb39c3e3e85f38c6b...798102c42e6efc2895585e42d56a253698ec2df9)

https://github.com/OpenRA/OpenRA/commit/c6c05802d237089952df2010c9de345883dce60d
https://github.com/OpenRA/OpenRA/commit/082efe1b08d9c1d51881a5f5a6dae0dcafc3d7a7
https://github.com/OpenRA/OpenRA/commit/a23634897aa5d92ae0867cc153797263ed152735

**Pull request merged**
