### PR TITLE
D2K carryall pickup indicator offset fix

### LINKED ISSUE #14487: D2k carryall pickup indicator is missing sequence offset
This can be seen by it jumping position when changing zoom.  The Offset: should be set to center the image so that it remains stationary.

### PR DESCRIPTION
**Pull request by fruestueck**
This Fixes #14487 jumping `pickup-indicator` when zooming in/out.

EDIT: `ReferencePoint: Top, Left`, Offset adjusted as seen on [compare_image](https://www.dropbox.com/s/nwzmjl1p0b27axe/openra_pickup.png?dl=0).
<strike>Also the icons should scale on zoom.</strike>

 [d2k Vanilla video source](https://www.youtube.com/watch?v=4P6lANvfXog)

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by pchote** [comment]
I always interpreted the original as having it inset from the corner rather than offset from the origin, and so to be consistent with our other decorations can we please attach this back to the TopLeft?

**Comment by fruestueck** [comment]
I agree @pchote. Changed it acordingly ( see image in top post).
Maby the offset could use a slight adjustment. What do you think?

**Review by pchote — APPROVED** [review]
LGTM, thanks!

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/56eec7245752d9b9bd1973a424676de399448f14

**Pull request merged**
