### PR TITLE
Fix BaseBuilderBotModule.LocomotorsForProducibles.

### LINKED ISSUE #21663: Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.ProductionInfo`
## System Information
- Operating System:  Linux (X64, Unix 6.8.0.48)
- OpenRA Version: playtest-20241116
- OpenRA Mod: d2k mod version playtest-20241116
- Source: https://github.com/OpenRA/OpenRA/releases/download/playtest-20241116/OpenRA-Dune-2000-playtest-x86_64.AppImage
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version playtest-20241116
d2k mod version playtest-20241116
on map bdcff34983b28f36e047f234d4e7acc923159187 (Venac ditch by CombineCnR).
Date: 2024-12-02 19:22:22Z
Operating System: Linux (X64, Unix 6.8.0.48)
Runtime Version: .NET CLR 6.0.36
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.ProductionInfo`
   at OpenRA.Primitives.TypeDictionary.Get[T](Boolean throwsIfMissing) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Primitives/TypeDictionary.cs:line 67
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.LocomotorsForProducibles(Actor producer)
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.ChooseRallyLocationNear(Actor producer) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 341
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.SetRallyPoint(IBot bot, TraitPair`1 rp) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 310
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.OpenRA.Mods.Common.Traits.IBotTick.BotTick(IBot bot) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 244
   at OpenRA.Mods.Common.Traits.ModularBot.<OpenRA.Traits.ITick.Tick>b__14_0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 97
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Traits.ITick.Tick(Actor self) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 93
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/TraitDictionary.cs:line 312
   at OpenRA.World.Tick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/World.cs:line 458
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenRA/OpenRA/OpenRA.Launcher/Program.cs:line 46
```

### PR DESCRIPTION
**Pull request by RoosterDragon**
Account for per-actor production (e.g. ProductionQueue) and per-player production (e.g. ClassicProductionQueue). This requires resolving the Production and ProductionQueue traits on both the producing actor, and the owning player actor.

When setting rally points, check the actor didn't die first.

Fixes #21663

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
AI managed to put spawnpoint in an unreachable position

Screenshot 2024-12-02 at 22 48 03

On Morbid Aimless Poseidon, bottom left. I didn't quit gracefully so I don't have the replay 😞

**Comment by RoosterDragon** [comment]
Based on other usage, looks like I was missing a `!p.IsTraitDisabled` check, added now.

**Review by PunkPun — COMMENTED** [review]
I ran another AI game and managed to get a crash `Attempted to
get trait from destroyed object (hand 637 (not in world))` in this function. The log doesn't mention which line specifically

at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.LocomotorsForProducibles(Actor producer)
   at OpenRA.Mods.Common.Traits.BaseBuilderBotModule.SetRallyPoint(IBot bot, TraitPair`1 rp) in /OpenRA/OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs:line 310

Screenshot 2024-12-08 at 11 36 40

at about 3:30 the pink ai places rallypoint in innacacible location


[cnc-2024-12-08T093305Z-0.orarep.zip](https://github.com/user-attachments/files/18051556/cnc-2024-12-08T093305Z-0.orarep.zip)

**Comment by RoosterDragon** [comment]
An IsDead check would likely solve the not in world crash.

As to the inaccessible locations, I'm not easily seeing where the production checks are going wrong on that. If anybody who is more familiar with the production aspect of things can see the missing piece please do point it out.

**Review by PunkPun — COMMENTED** [review]
The issue seems to lie in multiqueue, the `ProductionQueue` trait being attached to the structure, while we are looking for it on the player actor. 

The is dead check seems to be consistently crashing in my test games

**Comment by RoosterDragon** [comment]
Ah - there is per-player and per-actor queue setups. Okay I've updated the code to account for that and a test run in RA and TD both seems reasonable at a glance now.

Also adding a missing Disposed check which will cover us for the case when we decide a rally point needs redoing and queue it for later, but it's died a few ticks later when we actually get around to doing it.

I'm feeling better about this version, although not fully confident.

**Comment by penev92** [comment]
I'm probably quite rusty at this point, but what's the use-case for the first `// Player-wide production` case?
`ProductionQueue`s can be either on the production structure OR the player actor, but `Production` and its derivatives are always on the structures 🤔

**Review by PunkPun — COMMENTED** [review]
I suppose service depot doesn't produce anything 😄

Screenshot 2024-12-19 at 19 17 43

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/1f401b977a40ef1e2ff5ca047c882b91a60bfb81...52c8892f164583cec5a1a83a089f4b92a0f443fb)

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/commit/68ad9163ffd2e0c1d6b80b332564bf92b7b5b6cb

**Comment by RoosterDragon** [comment]
> I'm probably quite rusty at this point, but what's the use-case for the first `// Player-wide production` case? `ProductionQueue`s can be either on the production structure OR the player actor, but `Production` and its derivatives are always on the structures 🤔

I am struggling with the usage of these traits. I probably have this wrong and thus it's dead code.

**Pull request merged**
