### PR TITLE
Credit removal due to request.

### PR DESCRIPTION
**Pull request by IceReaper**
Removal due to his request on IRC.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
What a shame.

**Review by reaperrr — APPROVED** [review]

**Comment by Micr0Bit** [comment]
@IceReaper : sry , but such requests should cook a bit more imo ... he should have made this PR himself ... and in this particular case paul should have given a thumb (up or down)

theres no need to pull triggers quickly when theres a overheated discussion, even when the request came from himself

**Comment by reaperrr** [comment]
Same here. In this particular case the chance was high any delay would have just added more fuel to the fire.
And if the circumstances ever change again, reverting this is easily done.

**Comment by IceReaper** [comment]
I know what you mean, but he has the right to have his name removed and he clearly demanded it. Ofcourse he could have made a pr, but he has been asked to do so and didnt do it. That would just have kept the discussion going, cause if i want someone to remove my name, all i need to do is to tell the responsible people to do it, and its their responsibility to do so. If he would made a pr, it it would still have to be accepted, which clearly shows thats not himself who could delete it, but the project owners. So there is no need to keep discussions going like "oh, we have your deletion request, but  hey, get active and do another delete request via pr" as the answer is sadly simple: he made the request to the project owners, now they have to do it.

**Comment by GraionDilach** [comment]
Besides the above, __filing a PR is a contribution, regardless of content__ resulting with a catch-22 case when I explicitly stated that I no longer want to contribute.

The real shame is that I didn't made this choice earlier and let myself ground up by this project.

**Pull request merged**
