### PR TITLE
Change the ingame diplomacy’s close button’s hotkey from esc to p.

### PR DESCRIPTION
**Pull request by phrohdoh**
A bit faster and more logical IMO.

### CODE REVIEW

**Comment by cjshmyr** [comment]
I agree with your sentiment but think it breaks a standard. +/-1

**Comment by chrisforbes** [comment]
I think we should ALWAYS be able to make some UI go away by hitting ESC.
Adding *additional* mechanisms (for a toggle, like this one?) is fine.

**Comment by dan9550** [comment]
No ESC thats just weird :\ You break the logic of my mind.

**Comment by penev92** [comment]
I like the addition of the 'P' button, but not the removal of the 'Esc'. But I suppose we can't have both, can we...

**Comment by Phrohdoh** [comment]
I see no reason to traverse the entire keyboard to close a panel that is opened with a specific hotkey.
But okay.

**Pull request closed without merging**
