### PR TITLE
Fix the misleading wording of the confirm dialogs

### PR DESCRIPTION
**Pull request by abcdefg30**
Noticeable when leaving the map editor. Previously it asked you "Exit and lose all unsaved changes" and gave you `[Cancel]` and `[Abort]` which might be confusing (which one is the correct button?).

### CODE REVIEW

**Comment by Phrohdoh** [comment]
:+1:

**Comment by obrakmann** [comment]
Found that the file deletion confirmation prompts in the map and replay browser didn't have a cancel button anymore, filed https://github.com/abcdefg30/OpenRA/pull/7 to fix.

:+1: when that's been added.

**Comment by abcdefg30** [comment]
Merged the fix and rebased.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/8b972afa0af29e69bafeb910ee25872113572d87)

**Pull request merged**
