### PR TITLE
Add more building explosions to d2k and cnc

### PR DESCRIPTION
**Pull request by abcdefg30**
Same as #9943 for the d2k and cnc mods.

I'm not sure though if all explosions are fitting (in cnc `big_napalm` looked a bit large).

### CODE REVIEW

**Comment by Mailaender** [comment]
Yeah, the big napalm also overlaps the "dead" sequence in cnc. Better send a service regulation to all military engineers not to store napalm barrals everywhere. Otherwise nice subtle polishing. :+1:

**Comment by abcdefg30** [comment]
An order to all engineers was issued.

**Comment by obrakmann** [comment]
Looks fine to me. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/e09cf1cac70f1a680432b3b991c10ed7ed6e9d31)

**Pull request merged**
