### PR TITLE
Game main loop. Consider actual render time. Fix 18491.

### LINKED ISSUE #18491: performance, remove the forced renders
as once discussed in discord developer chat,

release latest. at Game.cs Loop().

the game main loop use a force render. on systems where rendering becomes slow the force render causes the main loop to become slower and slower - ending up loop resulting in 120% cpu usage, locking up multi player games.

the game also forces a minimum of 16 fps at the default game speed.

background: i have the issue that render time drops from 6-9ms to 20+ ms at times. likely gl, driver, cooling related. but i assume the full CPU usage happens on any slow systems.

request:
- let the game detect if rendering is slow, skip frames
- let the game detect that in general it can't keep up in both rendering and logic frames, perhaps drop in game speed or log console message, pause to catch up, exit
- let the game skip render frames - rather than forcing them
- send warnings to the console, indicating 
- bring back the possibility - like in previous releases - to run the game at 10 to 20 fps. works fine.

additional:
- register also a network delay, next to render and logic delay
- differentiate in the network ping/latency stats between network delays and render delays, allowing players to determine if the network is causing the issue or their PC

### PR DESCRIPTION
**Pull request by anvilvapre**
Fix #18491. Consider actual render time in determining next render interval.

Relevant because the game currently does not perform on slow hosts and
recursively becomes slower and end up in full 120% CPU usage.

Lower render interval based on actual render time.                   
                                                                                
`Game.Loop` assumes the maximum configured frames per second                    
is also the minimum frames per second that can be met by the host.
It does not actually consider real actual render time in any way.       
                                                                                
The minimum minimal fps of 60 frames per second is not always                   
achievable on even a reasonable host (an Intel i7 with                           
OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)                   
OpenGL version: 4.5 (Core Profile) Mesa 21.0.0-devel                            
(git-05ad0f8 2020-12-19 focal-oibaf-ppa)).                                      
                                                                                
Proposal fix. The game will dynamically lower the render interval               
to the minimal (replay) frames per second if the render end time                
exceeds the future next (forced) render time. This for only                      
the single next render frame.                                                   
                                                                                
Minimal changes to previous logic.                                              
                                                                                
In the previous situation when a render frame would take longer                 
than render interval - i.e. due to initial render, many                         
renderables or a slow host or gpu - the game would still schedule the           
next render at the render interval which would potentially be                 
in the past. The result is the game lagging behind in fps until at              
some point it is able to catch up - i.e. when a logic tick takes less           
time.                                                                           
                                                                                
This at times actually occurs 40+ times on my host when                
leaving the shell map open for 2 minutes. Typically related                     
to a video player also being active in a browser.                               
                                                                                
This change causes the reported frame rate on my host to go up 
considerably from from 10-60 to 100-120+. `PerfDebugLogic` considers            
the skipped frames to be rendered. 

Very much open to receiving any alternative fix.

### CODE REVIEW

**Comment by pchote** [comment]
Does this mean that the game can tick multiple times between rendered frames? We tried that in the past, and had to revert it because it regressed gameplay behaviour in multiplayer games.

**Comment by anvilvapre** [comment]
You mean multiple `logic` ticks per render frame.

The behaviour of `renderBeforeNextTick` `bool` has not changed. If set `forceRender` will be `true` - in the next loop. And even if the `forcedNextRender` `frame/time` is set to be far in future the `forceRender` `bool` will force the render.

As i understand the code.

**Comment by pchote** [comment]
@adammitchelldev how does this interact with your changes?

**Comment by adammitchelldev** [comment]
> @adammitchelldev how does this interact with your changes?

Not sure how it will interact directly, I'm of the opinion that the whole loop needs to be refactored (I haven't gone all the way but started) because it currently behaves in some ways that are not easy to predict due to interacting mechanisms designed to fix individual problems (that don't appear to work correctly in combination). Adding another mechanism on top of that should be approached with caution.

I think the current loop is designed specifically not to skip frames and to attempt to render "as fast as possible" (1000fps) unless specifically frame limiting or vsync'd, so I think the problem presented here is more of a "by design" feature. It isn't currently set up to do framerates lower than tickrates and will render as fast as it can, which is exactly as intended. It doesn't skip logic frames in order to render though.

We should probably just support optionally capping framerate at the logic tick rate, or lower.

**Comment by anvilvapre** [comment]
Please know that the same performance issues stay in the new release. My gpu not being able to keep up causing the game to end up using 140% cpu due to forced render times. So i also patched the latest release with the fix and reduced fps below the 60. So i can imagine more (Linux) players experience this problem without being aware.

**Comment by anvilvapre** [comment]
Reminder.

The game still goes from 30% to 150% cpu locking up my computer - once rendering performance drops to some GPU issues. The game still hangs itself. This happens on all slow computers where the game falls behind in render or logic ticks.

**Comment by pchote** [comment]
Reminder noted, but it is still not at all clear to me how this integrates with the ongoing netcode rework and therefore how to proceed here.

**Comment by pchote** [comment]
IMO the ideal way forward here would be to find a solution that automatically downgrades first to half the VSync rate (60 to 30 FPS, 144 to 72, ...) which would be smoother and paced more evenly than going straight from VSync to 10 FPS. I'm not sure we have a reliable cross-platform way to query the vsync rate - would it be sufficient to instead just force every other render?

**Comment by pchote** [comment]
We could perhaps try to actually measure `renderInterval` based on the time between successive frames (vsync, if enabled, will force the main thread to block until the previous frame has been handed over) and then manually double it if we detect we can't keep the current frame pace?

This would be difficult if we are in a situation where 1 tick + 1 render takes longer than the vsync rate or have a variable refresh rate display...

**Comment by anvilvapre** [comment]
I later noticed a problem in my proposal. So I should close this. Forgot what it was.

I think my laptop runs into temp issues, causing it to scale down in freq.

Auto adjusting may be hard to implement robustly. 

The main importance would be that the game can no longerhang itself up by becoming recursively slower. Dropping in quality seems like the best option to also not effect other players.

Current pausing the game doesn't cause it to use less CPU, get out of that loop.

If the user could also again choose for frame rates below 60 that could be great. My local fix is to use a patch to reduce FPS to chess level ; )

**Comment by reaperrr** [comment]
> If the user could also again choose for frame rates below 60 that could be great. My local fix is to use a patch to reduce FPS to chess level ; )

I agree that we should lower the minimum to at least something like 30 or 25 (close to default game/simulation speed).

**Pull request closed without merging**
