### PR TITLE
Some carryall fixes

### PR DESCRIPTION
**Pull request by MatthijsBenschop**
Add carryall edge production and other minor improvements.

### CODE REVIEW

**Comment by pchote** [comment]
The problem there is in making it work properly when there are multiple players, each with their own shroud.

**Comment by MatthijsBenschop** [comment]
Left out the actual edge spawn. Now only includes the bug fixes.

The edge spawn will get its own pr later.

**Comment by Mailaender** [comment]
:+1: can't find any behavioral regressions.

**Comment by obrakmann** [comment]
Me neither, looks good. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/76686854197df1b1faca38d5fc926752eab7cd9d%5E...76686854197df1b1faca38d5fc926752eab7cd9d)

**Pull request merged**
