### PR TITLE
(Production)Paradrop fixes

### LINKED ISSUE #17270: ProductionParadrop throws an NRE if all exits are occupied at production.
On https://github.com/OpenRA/OpenRA/blob/ae34410c8077a45d3dae20419aa63659cf0718a6/OpenRA.Mods.Common/Traits/ProductionParadrop.cs#L90

It's a single-line fix, compared with
https://github.com/OpenRA/OpenRA/blob/ae34410c8077a45d3dae20419aa63659cf0718a6/OpenRA.Mods.Common/Traits/Production.cs#L118

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #17270.
(I actually forgot to PR this because of https://github.com/OpenRA/OpenRA/issues/17270#issuecomment-545380181 -.-)

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]
Looks sane.

**Comment by reaperrr** [comment]
Should be in next release, in my opinion.

**Comment by pchote** [comment]
I haven't tested this, but based on the fact that this situation can happen at all: wouldn't it be better if this behaved like `ProductionAirdrop`, where the plane circles until there is a free exit?

**Comment by abcdefg30** [comment]
> wouldn't it be better if this behaved like `ProductionAirdrop`, where the plane circles until there is a free exit?

Yes. As discussed on IRC I'd like to do that in a follow-up PR.

**Review by pchote — COMMENTED** [review]
Crash fix confirmed, and :+1: to the 2nd, 3rd, and 4th commits. I still think that the first commit has some serious problems, but considering that we don't use this trait in the default mods and the discussion about defering a proper fix to a followup PR I don't think it is worth delaying a playtest over.

The other production traits indeed don't support null exits - Production (except for the special case where Production is on the Player actor) blocks if no exits are available and ProductionAirdrop's plane circles until the exit is clear. The fallback to TopLeft also happens at the wrong time - units will be dropped in the wrong place if the exit clears while the plane is flying in.

IMO the followup PR should start by removing the null-exit support and then either fall back to the first blocked exit (and let the new unit die if the nudge to clear it doesn't work), or implement new logic to allow the drop plane to circle until it is clear.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/8793c708fe74b12bbaa78c17c865e43d7e7fefa2

**Pull request merged**
