### PR TITLE
Added the new Tiberian Sun build palette skin

### LINKED ISSUE #7474: TS UI
In order to help developers get rid of the old UI code https://github.com/OpenRA/OpenRA/pull/7461, I have started a draft, a first attempt at making a TS UI. It may or may not be be final UI (I don't know yet), but we'll see.

Current branch:
https://github.com/x-a-n-a-x/OpenRA/commits/new-TS-UI

As you can see, it's far from being finished and there are still bugs with some coordinates in chrome.yaml or ingame-player.yaml files. But little by little, I try to fix problems. 

screen shot 02-14-15 at 08 25 pm

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8580961-ts-ui?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/7474. Also fixes regressions introduced by https://github.com/OpenRA/OpenRA/pull/7461.

### CODE REVIEW

**Comment by pchote** [comment]
The active/hover/hover-active behaviour of the queue buttons are inconsistent with the order buttons, and both are inconsistent with what the other mods do.  The latest version of @x-a-n-a-x's [chrome.png](https://raw.githubusercontent.com/x-a-n-a-x/OpenRA/new-TS-UI/mods/ts/uibits/chrome.png) splits out the background and foreground states so that the yaml can be set up properly to avoid this.

**Comment by Mailaender** [comment]
This is also how he did it for the Dune 2000 mod build palette in https://github.com/OpenRA/OpenRA/pull/7384.

**Comment by pchote** [comment]
The D2K build palette will also need to be fixed.

**Comment by Mailaender** [comment]
https://github.com/x-a-n-a-x:new-TS-build-palette-skin adds far more breakages than fixups so don't expect me to rebase upon that.

**Comment by x-a-n-a-x** [comment]
I am sorry but I am not good at fixing yaml errors.

**Comment by x-a-n-a-x** [comment]
My recent successful progresses on the RA2 UI (https://github.com/Phrohdoh/oramod-ra2/issues/11) made me more confident about the possibility to fix the TS UI errors. I'll retry to fix them as soon as the RA2 UI is done.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/pull/7699.

**Pull request closed without merging**
