### PR TITLE
Added support for XDG user data and cache on Unix

### LINKED ISSUE #10374: Adhere to XDG Base Directory Specification
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/10374.

### CODE REVIEW

**Comment by pchote** [comment]
Does this provide an automatic fallback to continue using the existing content, or is this going to create a hard break where players have to maintain two sets of content and settings files?

**Comment by pchote** [comment]
I'm not convinced that this is going to be worth the disruption: OpenRA still violates both the spirit and the letter of the specification because it is storing large user-independent game files in user-specific directories.

#16587 caused (and continues to cause) significant support problems, but at least that had an arguable benefit of not polluting the players' home directory root. Splitting the support dir components over multiple locations is going to make it even harder to document and help players who need to report logs after a crash, manage maps, etc.

What practical benefits does this provide to justify the additional support burden and player confusion it will cause? Are there any other examples of games that implement the specification?

**Comment by Mailaender** [comment]
@Warzone2100 and https://bitbucket.org/Doomseeker/ have files in `.local/share/`

https://www.eduke32.com/ @OpenDUNE @OpenTTD use `~/.config` only for configuration.

It's been quite some time since this specification was published so naturally all the progressive OS game clones have adopted it. Also #10374 has 6 👍🏻 so there are also users who want this. The disruption is a one-time event and with quick install of the assets available not a huge thing in my eyes.

**Comment by pchote** [comment]
Its not a one-time event: there is an ongoing support burden and confusion for players in having our file layout work differently on Linux to other platforms. Right now we can still say "find the support directory at X, then look for settings/maps/logs/replays/etc at these subfolders", and it already causes problems that linux and windows have two different locations for X.

**Comment by Mailaender** [comment]
I think it is a matter of updating a wiki page and maybe that Discord bot. Linux users are probably more technical anyway.

**Comment by deleted-user-1** [comment]
FWIW the motivation behind my +1 to the comment above was to keep things simple and more important keeping backwards compatibility (now that the music is not available anymore from the free sources). I can't review code so don't know what this does.

**Comment by Mailaender** [comment]
If you are on Windows then this does nothing. Linux users have to `mv ~/.config/openra/Content ~/.local/share/openra/Content` or put in their CD ROMs again.

**Comment by deleted-user-1** [comment]
Ok, but note in case it's merged and you update the docs, some people (on linux systems) like me have it all in ~/.openra and not in ~./config.

**Comment by pchote** [comment]
I don't see any way forward with this PR until we have come to a consensus on what the desired end result is and how to get there. This will require more discussion that would be best handled either in #10374, or on another platform (e.g. IRC or Discord) and then summarised in #10374. Closing this until then to help clean up the PR queue.

**Pull request closed without merging**
