### PR TITLE
Fix rails in TS being invisible

### PR DESCRIPTION
**Pull request by abcdefg30**
Followup to #11904.

### CODE REVIEW

**Comment by Mailaender** [comment]
They are indeed back again except for the turn right segments:

image

Tested on the City Scape map.

**Comment by abcdefg30** [comment]
Yeah, looks like only `tracks10` and `tracks12` are affected.
tstracks
Fixed by increasing their `Offset.Z` by one.

`tracks15` and `tracks16` were also invisible (I don't know what those two tiles are even supposed to do). I had to increase the offset by 3 for them.

**Comment by pchote** [comment]
Fudging z-offsets with arbitrary values to make them look "right" without understanding the significance of those values is a bad idea.  An offset of 1 is understandable because you need to push the sprites unambiguously above the terrin.  *Why* do those specific tiles need values of 2 or 4?

**Comment by reaperrr** [comment]
> Without any other info my best guess is that we have a bug that is giving sprites with different frame sizes different base z-offsets, which (a) would be bogus, and (b) would mean that the changes in this PR are almost certainly wrong.

I suspect that might be the case, the curves show up as expected (with lower half invisible) if `ZRamp: 1` is commented out.

**Comment by pchote** [comment]
I've opened #13246 about investigating this properly, but for now I think we are done here.

**Pull request closed without merging**
