### PR TITLE
BugFix for #7955

### LINKED ISSUE #7955: Game freezes, probably pathfinder-related
The game somtimes freezes at arbitrary times. It's therefore hard to track down, but our user Clemmy has managed to catch a replay of it ([download here](http://www.pipelinestall.org/stuff/OpenRA-2015-04-14T164638Z.rar), cnc@playtest-20150408).

Edit: The freeze happens at around 16:56 in the replay.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11155926-game-freezes-probably-pathfinder-related?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Rydra**
Fixes #7955. Improves pathfinder performance a bit.

### CODE REVIEW

**Comment by penev92** [comment]
Well, I can confirm that this fixes the problem in the replay. That's all I can do for now.

**Comment by reaperrr** [comment]
Spotted no crashes in skirmish and shellmap, and performance seems to be better for the most part. :+0.5: , I guess together with penev's replay test we can count this as :+1:

**Comment by obrakmann** [comment]
According to the discussion in the ticket, this should be the correct fix, it prevents already closed nodes from being added to the open queue and being evaluated more than once. Unfortunately, I've never been able to reproduce the bug, and the replay desyncs quite early. I didn't notice any regressions in movement behaviour in-game, so :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/4bf9374fbddd023e7f641b0c303856533c5412cd%5E...4bf9374fbddd023e7f641b0c303856533c5412cd)

Thanks to everyone involved for debugging and fixing this so quickly! Much appreciated!

**Comment by Rydra** [comment]
'it prevents already closed nodes from being added to the open queue and being evaluated more than once'

Well to be correct and purist, this is not an issue, the issue is the way neighbours are selected to improve performance. Just a small correction.

**Comment by chrisforbes** [comment]
Show me a paper that allows closed -> open transitions.

**Pull request merged**
