### PR TITLE
Complete Upgrades -> Condition transition.

### LINKED ISSUE #12380: Replace upgrade levels with BooleanConditions
## Motivation

When the upgrades system was first introduced (#6110, #6556) it used single string conditions as boolean flags for enabling/disabling a trait, with a fuzzy overrideable definition for "can I accept an upgrade of this type" that was used by the stats modifier trait to allow multiple upgrades to increment the applied bonuses.  #6750 overhauled this by changing the upgrade types from booleans to integer levels, and added a framework for turning traits on and off at arbitrary upgrade levels.  This had the very nice benefit of allowing stacked upgrades to activate higher levels of behavior.

As time has gone on it become clear that the benefit of upgrade levels / stacked upgrades is significantly outweighed by our inability to define conditions that depend on non-trivial combinations of upgrades.

As an example, we would like to have the RA radar dome's `ProvidesRadar` trait to be active when:
* The buildup sequence has completed (i.e. not during the make / sell animations).
* The Player is not low-power.
* The building has not been manually powered down.
* A radar jammer is not in range.

This can't be represented using our current upgrade system, but can easily be defined in terms of a boolean expression: `buildcomplete && !(lowpower || powerdown || jammed)`.  We have a number of projects (e.g. removing `IDisabled`, removing the BuildComplete hacks from traits, removing the hardcoded radar jamming logic, finishing TS carryalls) that are stalled over similar syntax problems.

## Discussion

This is going to be a painful migration to complete because it can only be partly automated.  It's not so bad for our default mods because we only use multi-level upgrades for veterancy.  I have heard that other mods rely on these much more extensively, but as far as I know they aren't publicly available so I can't look at their rules.  Based on earlier discussions I expect this to be a controversial change.

The new system will be able to replicate stacked upgrades in two ways:

* A `ConditionCombiner` trait that can (among other things) convert parallel conditions `a`, `b`, `c` (granted in any order) to ordered conditions `1`, `2`, `3`:
```
ConditionCombiner@1
	EnableCondition: a || b || c
	GrantCondition: 1
ConditionCombiner@1
	EnableCondition: (a && b) || (a && c) || (b && c)
	GrantCondition: 2
ConditionCombiner@1
	EnableCondition: a && b && c
	GrantCondition: 3
```

* Making `UpgradeActorsNear`, `GrantUpgradeWarhead`, etc, grant the first disabled upgrade in their type list.  E.g. for a hypothetical "slow" weapon that stacks to two levels
```
GrantUpgradeWarhead:
	GrantCondition: slow-1, slow-2
	Duration: 50
```

The first warhead impact would grant the `slow-1` condition on the target.  The second warhead impact would see that `slow-1` is already enabled, and grant `slow-2` instead.  The third and subsequent impacts would see that all upgrades are already active, and instead recharge the timeout on the shortest one (first `slow-1` then `slow-2` and so on).  This can be combined with `ConditionCombiner` on the target actor if the modder wants the warhead to trigger multiple conditions on the target actor.

This overhaul is explicitly trading off convenience for the stacked upgrade case for the ability to solve a lot of problems that currently aren't possible.  I have tried to cover all the bases in this PR introduction because I want to avoid a rehash of the ill-informed argument when I first outlined this plan in IRC a few months ago.

### PR DESCRIPTION
**Pull request by pchote**
Closes #12380.

### CODE REVIEW

**Review by obrakmann — APPROVED** [review]
👍 

Rename the `OpenRA.Mods.Common/Traits/Upgrades` diretory as well?

**Comment by pchote** [comment]
Renamed the traits directory, and also the `UpgradableTrait` base class.  Not sure if you want to recheck your review @obrakmann.

**Review by GraionDilach — APPROVED** [review]
:+1: Looks good to me.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ec3720017865cd5ccec720cf6dcf5d6e42d0fabc)

**Pull request merged**
