### PR TITLE
Fix D2K outpost artwork offsets and selection box.

### LINKED ISSUE #8504: D2K - Outpost offset is wrong
Comparison;
radar offset

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22382977-d2k-outpost-offset-is-wrong?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #8504.  Another simple fix to make the overhauled D2K mod extra polished for the nit-picky original game fans.

### CODE REVIEW

**Comment by Mailaender** [comment]
Causes some overlapping issues, but nothing serious:

image

To be honest I didn't compare those offsets to the original when I setup all the rules back in the days.

:+1:

**Comment by GraionDilach** [comment]
Shouldn't this also make the bottom row a bib?

**Comment by penev92** [comment]
Looks good to me :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/f31f2adda87a4e6485aeeecf9d8863cc3effdf6d)

**Pull request merged**
