### PR TITLE
Rewrite Enter and remove ResolveFrozenActorOrder.

### LINKED ISSUE #9362: Sold (captured?) buildings stay frozen under the fog of war
(playtest 20150830)
I captured the enemy's building but later sold it. It remained visible/frozen under the fog of war.
This visual glitch was only present during the game and it is not seen in the replay.

### LINKED ISSUE #14365: Enter activity does not account for moving Targets.
From #13699:

The `Enter` code does not account for the target moving after the movement (e.g. `Drag`) has started.  If the target is moving then the unit will move to the original target position, notice that it is no longer there, and then fail/cancel itself.

What we really want here to fix this properly is to fix the `IMove.MoveIntoTarget` implementations to deal with moving targets.  This means that `Drag` etc can adjust themselves to move always towards the actual position of the target.  For this to work well we would need to introduce a `WDist targetMoveLimit` to the method call that can abort the activity if the target is moving too far/fast from the original location.  This then covers the Hijacker issue plus any visual glitches that could be caused by the target moving too fast.

### LINKED ISSUE #14755: "Engineer can repair enemy building" not fixed
Closed #11505 should be fixed by #12535, however the bug as described is still happening, in release and playtest aswell.

### LINKED ISSUE #16048: Remove ActorExts.ResolveFrozenActorOrder
Once the plumbing from #15866 has converged on stable code we need to follow through and replace `ActorExts.ResolveFrozenActorOrder` everywhere else.

### PR DESCRIPTION
**Pull request by pchote**
This PR implements the third and hopefully final part of the target-visibility changes.

The changes required to recreate the old behaviour for #16139 were going to be ugly, so I instead pushed forward and rewrote `Enter` from scratch.  The new activity should support visibility and all our other modern activity expectations. It should also be *significantly* more readable (not hard, considering the state of the old one).

Fixes #9362.
Fixes #14365.
Fixes #14755.
Fixes #16139.
Closes #16048.
Supersedes #13699.

The `Enter` activity made up 95% of the work left for #16048, so I included the final four commits to close that here too.

### CODE REVIEW

**Comment by pchote** [comment]
Updated.
* Changed `Enter` method signatures as mentioned above
* Added a commit to pause movement in `MovePart` when `Mobile` is disabled (improves reliability of vehicle capturing).

Note that GitHub has messed up the commit ordering in the web interface as usual.

**Review by ghost — COMMENTED** [review]
Can't find any issues with the changes in this PR. #14755 and #16139 are fixed, can't comment on #14365. I tested units that can enter things in RA quite extensively and in-game behavior looks good to me.

**Comment by pchote** [comment]
Added a new commit to fix #9362, which appears to have a bigger impact now that the Enter activities care about frozen actors (or maybe just being noticed more with people actively testing capturing).

Testcase:
* Add `-SpawnActorsOnSell:` to `POWR`
* Start a MP game with two players, cheats enabled
* Player 1 builds a power plant somewhere outside of his normal vision range
* Player 2 builds a barracks outside his normal vision range, near but outside vision range of the power plant
* Player 2 builds an engineer and captures the power plant
* Player 2 sells the power plant

Before the fix: Player 1 sees a power plant frozen actor that has the faction color of Player 2, but a tooltip showing themselves. Player 2 sees a power plant frozen actor that appears to be owned by Player 1.

After the fix: Player 1 sees a power plant frozen actor that appears to be owned by Player 2. Player 2 does not see a frozen actor.

**Review by ghost — COMMENTED** [review]
https://github.com/OpenRA/OpenRA/pull/16150/commits/1dea58465e8de5c03663ee7fb2bbeee3e1fd2847 fixes #9362. :+1: for in-game behavior.

**Review by obrakmann — APPROVED** [review]
looks ok, and seems to work fine ingame. I tried to test as many edge cases as I could

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a65cc1b1db2d1bc775e2247439109382659a19c3)

[Prep commit](https://github.com/OpenRA/OpenRA/commit/2b6ebcd09caa21af84986c42568b8903382a0333)

**Pull request merged**
