### PR TITLE
TD: make cliffs unbuildable

### LINKED ISSUE #9265: TD tileset: buildable on ridges
(playtest 20150830)
It is possible to build on some ridge tiles.
Spotted in "Warthog hunt" mission (TD, NOD)

[12:24] <+penev> it's a tileset issue
[12:24] <+penev> it defines those tiles as buildable

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26469405-td-tileset-buildable-on-ridges?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by clemty**
fixes #9265 

I assume "Rough" means "can walk on, but cannot be built on", at least it seems that way during gameplay

### CODE REVIEW

**Comment by reaperrr** [comment]
As far as I remember the original, these tiles shown in #9265 should not even be Rough, but Rock. Actors shouldn't be able to enter these cells at all.

**Comment by clemty** [comment]
I changed them to "Rock"

**Comment by Mailaender** [comment]
:+1:

**Comment by penev92** [comment]
:+1: Thanks.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/9bdd9ae22e0a5d43cda0d256ebde839441202aa9...4edf445c0d8a39a1d4adb749ba091b78a9e9aaaa)

**Pull request merged**
