### PR TITLE
Use IntegerExpressions for Chrome Layout (again)

### LINKED ISSUE #13526: IntegerExpressions are slooow, causing UI lag
Since cd0898236d934cfe5701b1d90a051bc5004a5348, some UI actions are noticeably sluggish, for example clicking the "Skirmish" button in the main menu, or pressing the menu button in the in-game UI, which after that commit take up to a full second, while on the immediately preceding commit they are instantaneous.

### PR DESCRIPTION
**Pull request by Mailaender**
This reverts https://github.com/OpenRA/OpenRA/pull/13601. Closes https://github.com/OpenRA/OpenRA/issues/13526 as since https://github.com/OpenRA/OpenRA/pull/20765 we now target Mono 6.12.0

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Comment by PunkPun** [comment]
Entering RA game lobby crashes instantly
```
Exception of type `OpenRA.YamlException`: Missing whitespace at index 2, before `*` operator.
   at OpenRA.FieldLoader.ParseIntegerExpression(String fieldName, Type fieldType, String value, MemberInfo field) in /OpenRA.Game/FieldLoader.cs:line 342
   ```

**Comment by Mailaender** [comment]
Fixed and added a lint test.

**Comment by RoosterDragon** [comment]
Noticed one regression:
Multiplayer menu (common)

Bleed
image

PR
image

but otherwise flicking through various UI everything seemed good.

**Comment by Mailaender** [comment]
Fixed.

**Review by RoosterDragon — DISMISSED** [review]

**Review by RoosterDragon — APPROVED** [review]

**Comment by anvilvapre** [comment]
Side remark. Popovers are also widgets. These get loaded each time and often at each mouse move. There might be situations where the integer expresions are evaluated very often? But perhaps in the old situation it was not much more efficent?

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a1770687a2a3c5fa012fcb076e2866dfcded23e3...f96ee5ba074db814745d18c2e3ba3275b04fc4cf)

**Pull request merged**
