### PR TITLE
Added option to disable unit voices in-game

### PR DESCRIPTION
**Pull request by Chaosus**
I think this audio option is not a bad addition, sometimes this a boredom to hear the same replicas over and over again.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Sorry but :-1:.

Sure, it might not seem that way in RA/TD but unit voices are a great help at unit management and I'm not really sure if there is anyone who is disabling them.

**Comment by pchote** [comment]
@GraionDilach that's not a good welcome for somebodies first attempt at contributing! 😞 

While my personal opinion is also probably against this, I do think it is worth at least considering and seeing if there is a use case from other players.

**Comment by GraionDilach** [comment]
I have heard of people disabling/decreasing music volume to hear SFX/responses more clearly during all the mod betatesting runs I've had. Never heard of the opposite.

I can relate that it's not the best welcome either but the feature itself is unnecessary and if anything, we should have a separate unit voice volume bar longterm instead of a checkbox anyway.

**Comment by pchote** [comment]
I could get behind a volume slider.

If we go ahead with that then IMO we will need to reconsider the UI that we expose - having too many absolutely set sliders is a pain to configure, so we would want one master-volume slider, and then the music/video/voice/sounds sliders would then set an additional relative attenuation.  Moving to a logarithmic scale complicates things here of course...

**Comment by GraionDilach** [comment]
Most of the games I know work like that - one master volume and three relative bars for music/voices/sfx.

What I really don't want to ahve is to end up with akin to the situation during the time I joined up with that MapMusic checkbox and all the confusion it led to before MusicPlaylist resolved it.

**Pull request closed without merging**
