### PR TITLE
Polish and improved customization for actor trails

### PR DESCRIPTION
**Pull request by pchote**
Improves the APC and Hover MRLS in TS, and prepares the code for worm trails in D2K.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: This looks so great in combination with https://github.com/OpenRA/OpenRA/pull/10119.

**Comment by pchote** [comment]
We may want to sit on this for a couple of days, as I can extend this to add sandworm trails as soon as we have artwork.

**Comment by pchote** [comment]
The worm trails builds on top of this without conflict, but requires changes to several other traits.  I'm going to leave that to its own PR.

**Comment by pchote** [comment]
Fixed.

**Comment by RoosterDragon** [comment]
:+1:

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/207aeef5923751e753ee2d103d0cbb21b7aa650d)

**Pull request merged**
