### PR TITLE
Fix RenameContrailProperties UpdateRule

### PR DESCRIPTION
**Pull request by PunkPun**
Addresses https://github.com/OpenRA/OpenRA/pull/20220#issuecomment-1264644874

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]
Fixes the existing rules.

**Comment by Mailaender** [comment]
Note that https://github.com/OpenRA/OpenRA/pull/20220/commits/305b24beb07cc872005ad88cf3ba2b99af22c4ba also added `StartColorAlpha` which does not have a rule to automatize.

**Comment by PunkPun** [comment]
> Note that [305b24b](https://github.com/OpenRA/OpenRA/commit/305b24beb07cc872005ad88cf3ba2b99af22c4ba) also added `StartColorAlpha` which does not have a rule to automatize.

The implementation preserves the old behaviour, so there's no need for an update rule

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/658d5e9f1799124f7d59290ed715507063013bb3...e119ad2ccab3cd0e6f0d39efb38825982cbfd407)

**Pull request merged**
