### PR TITLE
Fix contrail using the wrong colors

### PR DESCRIPTION
**Pull request by PunkPun**
Splitting commit from #20350. I'm not sure why I didn't split it to #20420 nor into a separate PR back then

### CODE REVIEW

**Comment by pchote** [comment]
Can you please explain what this is trying to fix? Its not clear to me from reading #20350.

**Comment by PunkPun** [comment]
If end color is not set, we default to start color. But the mistake I did, which I fix here is that when start color is player palette, I don't set the end color to player palette. Rather I set it to the unused start color

**Review by pchote — APPROVED** [review]

**Review by dragunoff — APPROVED** [review]
Fix confirmed :+1:

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c03a67556a94eb524371e61224cf9662dd0e2665...f017b3a426affc37bfdc0e89110986232701f251)

https://github.com/OpenRA/OpenRA/commit/674ca8555b8be4b1d5aed9901e2068778c1d2a52

**Pull request merged**
