### PR TITLE
Support map-defined bot types

### PR DESCRIPTION
**Pull request by pchote**
This removes the `Map` usage from `LobbyLogic`, reworks the lobby and server to use the map ruleset for bots, and introduces a new `DummyAI` that can be used to fill slots in scripted maps.  This doesn't yet expose the bot info to Lua – i'm hoping that @abcdefg30 can suggest the best way to do this.

Depends on #10901.  We're almost at the end of this marathon rewrite, I promise!

### CODE REVIEW

**Comment by obrakmann** [comment]
Looks ok, :+1:

**Comment by pchote** [comment]
Dropped the testcase and DummyAI commits so that we can merge the completed parts of this.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/01b64b0cfe260879284bf8cd1201f5b75b6137b2...aa82fc9102a8bf2d24f62e1a03e06baf5fb256bf)

**Pull request merged**
