### PR TITLE
Revert the search radius decrease in TS and D2k

### LINKED ISSUE #17115: bleed TS shellmap: Nod harvester asleep
The nod harvester is idle next to the refinary.

On Bleed. Looks like a regression

Reported by @tovl in #17086

### PR DESCRIPTION
**Pull request by abcdefg30**
Looks like I was a bit too enthusiastic in #16920. Fixes #17115.

### CODE REVIEW

**Comment by tovl** [comment]
We might want to do the same for D2K. The rock/sand divide makes mining distances naturally longer in that game (which is why carryalls exist).

**Comment by abcdefg30** [comment]
You are probably right. Done. I counted the count of tiles from the most secluded corner to the nearest patch on some maps and it is usually not more than 40, so the values should work unless you place your refinery away from the spice on purpose.

**Comment by reaperrr** [comment]
Since this now affects D2k as well, at least the 2nd commit should be picked to prep.

**Review by reaperrr — APPROVED** [review]

**Review by tovl — APPROVED** [review]
:+1:

**Review by fruestueck — APPROVED** [review]
Fixes ts shellmap. Three random missions in D2K worked as intended

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9e1e18321f170e8540a0604b69a3968b7c780216...f35b84a710b6d79e49684f54d45d4cdab571895d

picked 2nd commit to prep.

**Pull request merged**
