### PR TITLE
Finish D2K worm implementation

### LINKED ISSUE #7289: Create Sandworm art
The sandworm's behavior is being done and redone, but because the original sandworm was drawn by the engine, there is no animation we can use.

>[23:30] penev__> aaaaand we still don't have proper artwork for them, too
[23:34] MicroBit> penev__ : as far as i heard ... its code related ... the "art" for the worm
[23:35] +pchote> in the original game, yeah
[23:35] +pchote> somebody will need to make some sprites for us
[23:35] MicroBit> why is nobody doing it via "code" ?
[23:35] +pchote> because it is a real PITA to do it in code on our engine
[23:35] +pchote> which works completely different graphics-wise to the original games
[23:37] MicroBit> tbh. i have no idea how to do the art to make it look like the original
[23:39] +pchote> that animation you did ages ago looked like it would have worked
[23:39] +pchote> with the spray paint mspaint tool, or whatever you used
[23:40] MicroBit> yeah ... but that is just 1 cell ...
[23:40] +pchote> the code would then need to overlap it a bunch of times
[23:40] +pchote> which is what the original games did
[23:40] MicroBit> i dont think so
[23:40] +pchote> they were drawn with pixel positioning instead of cell positioning
[23:41] MicroBit> looks damn fluid
[23:44] MicroBit> penev__ : why not asking for help in the modding section of "sleipnir stuff" ?
[23:46] MicroBit> pchote : i bet worm-sprites will cause some uglyness when they overlap or cut "rock" tiles
[23:47] +pchote> I bet they do in the original game, too
[23:47] MicroBit> the do indeed
[23:47] MicroBit> but guess what
[23:47] MicroBit> the color even changes
[23:48] MicroBit> like ... it gets more redish ... or darker
[23:48] MicroBit> depends on what tiles the worm is diving under
[23:50] +pchote> that's because of the blending mode they use

Not to mention that lightnings around the worm should be only at random times (that could easily be achieved in the `Sandworm` trait once the current constant lightning animation is replaced with something else).

So someone will have to step up and make ... something. Please!

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7546500-create-sandworm-art?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7290: Add Sandworm sound effects
There should be:
 - [ ] ~~Slight hissing sounds when the worms moves (not sure if we have such)~~
 - [ ] Lightning sound when random lightnings (mentioned in #7289) are implemented
 - [x] Worm attack sound (not the voice notification that says "Worm attack") #8013

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7547342-add-sandworm-sound-effects?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
This implements the sand trail and lightning as in the original game, so we can now finally mark this beast of a feature as finished :tada:

Also adds upgrade support to `WithActiveAnimation` (now renamed to `WithIdleAnimation` for consistency with `WithIdleOverlay`) and `LeavesTrails`, and tidies up the worm attacking code.

Depends on #10380.

Closes #7289.
Closes #7290.

### CODE REVIEW

**Comment by MicroJOo** [comment]
:+1:

**Comment by RoosterDragon** [comment]
#10380 is merged. Needs a rebase.

**Comment by pchote** [comment]
Rebased.

**Comment by Mailaender** [comment]
:zap:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/207aeef5923751e753ee2d103d0cbb21b7aa650d...453a36bfa96816ac224f45a6b3fae2fa3ec1eaae)

**Comment by Mailaender** [comment]
Good work! The movement of the worm is also now better to predict which makes dodging a bit easier.

**Pull request merged**
