### PR TITLE
Soviet05 reveal enemy base after capturing radar dome 

### PR DESCRIPTION
**Pull request by Arular101**
A proposal to polish the Soviet-05 mission.

The first objective in this mission is to capture the enemy radar dome. Unfortunately, like in the original game, nothing happens. Although, the mission briefing says: Capture their radar center so we can track Allied activity in this area.

I think a nice feature would be to reveal the enemy base after the radar dome is captured.

I decided to reveal the base with a big radius on easy difficulty level. On normal and hard, a small radius is used. It only shows the MCVs location.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Good idea! What do you think about placing a beacon with a text message hinting the player to what is going on (e.g. "We are now able to track allied movement in this area and discovered there expansion base.").

**Comment by Arular101** [comment]
Updated.

Yeah, that is a great feature! I added the beacon and message. I hope the message is good.

I also did it in Allies 06a, see PR #14328.

**Comment by Arular101** [comment]
Changed the message as requested at #14328 .

**Review by reaperrr — DISMISSED** [review]

**Comment by Arular101** [comment]
Apparently somehow the review of reaperrr was dismissed by me. I don’t know how that happen, but I didn’t change anything after the review. So, I consider reaperrrs review still valid.

**Comment by Smittytron** [comment]
Not a big deal, but I'd go with something like "Allied MCV detected moving to the island." or "The Allied MCV is fleeing to the island!" Then, "Coordinates of new Allied base discovered."

👍 After squashing.

**Comment by Arular101** [comment]
That the MCV is moving to the island is in a different trigger. I agree that it is a good idea to show a message when the MCV is moving, because this could happen in different moments.

Just to clarify the current state: on easy, the whole expansion base is shown with the message "Movement of an Allied expansion base discovered."

On normal and hard, only the construction yard is shown with the message "Coordinates of an Allied expansion base discovered."

So, I'll add the message "Allied MCV detected moving to the island." for when the MCV is triggered to move. (By the way, this happens at the start at hard difficulty level.)

**Comment by MustaphaTR** [comment]
> Just noticed that on bleed one of the AA Guns is in low power. But I can't find the reason why that is.

May be same reason why Outpost on Har5 is on Low Power.

**Comment by reaperrr** [comment]
> Apparently somehow the review of reaperrr was dismissed by me. I don’t know how that happen, but I didn’t change anything after the review. So, I consider reaperrrs review still valid.

Don't worry, github does that automatically when updating a PR.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8807a9bc6993018fe7029e8862fa2eb8eefdd23d...babcab0fd80d2d73a4f3565ed0caad6fe7cd55ef)

**Pull request merged**
