### PR TITLE
Correct Tiberian Dawn voice lines audio.

### PR DESCRIPTION
**Pull request by VonNah**
This PR brings the TD mod's voices audio in line with the **original/remastered game**.

### CODE REVIEW

**Comment by Smittytron** [comment]
`nuyell6` isn't used anywhere?

**Comment by VonNah** [comment]
It is not being used by the original/remastered game.

**Comment by abcdefg30** [comment]
We could still use them if they're included in the mix files, similar to how we want to add #17210?

**Comment by VonNah** [comment]
Rebased.

**Comment by VonNah** [comment]
Updated.

**Comment by abcdefg30** [comment]
Both @pchote and me agree that we'd like to have extra voicelines, so can you please re-add the lines that are completely dropped now?

**Comment by VonNah** [comment]
The lines missing are `nuyell6` and the Moebius `mthanks1`, `mtiber1`, `mplan3` which I think are good action voice lines.

I will add them asap.

**Comment by VonNah** [comment]
Updated.

**Comment by reaperrr** [comment]
> The lines missing are nuyell6 and the Moebius mthanks1, mtiber1, mplan3 which I think are good action voice lines.

You forgot the vehicle versions (v00/v02) of `report1`.

👍 after that.

**Comment by VonNah** [comment]
> 
> 
> > The lines missing are nuyell6 and the Moebius mthanks1, mtiber1, mplan3 which I think are good action voice lines.
> 
> You forgot the vehicle versions (v00/v02) of `report1`.
> 
> 👍 after that.

Thanks! I somehow missed it.

**Comment by VonNah** [comment]
Updated.

**Review by Smittytron — APPROVED** [review]

**Comment by Smittytron** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/727f5d00fbbb9f88b464f274a597189343dc65fe

**Pull request merged**
