### PR TITLE
Fix bridges crashing RA/TD

### LINKED ISSUE #13453: Maps with bridges crash in TD/RA bleed
They are targetable but don't define a BodyOrientation.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #13453.

### CODE REVIEW

**Comment by rob-v** [comment]
In RenderSprites.RenderPreview if QuantizedFacings == -1 and trait IQuantizeBodyOrientationInfo is null, facings = 1 is used. Couldn't the same default be applied in other cases or it isn't always 1 appropriate?

**Review by obrakmann — APPROVED** [review]
👍

**Comment by reaperrr** [comment]
> In RenderSprites.RenderPreview if QuantizedFacings == -1 and trait IQuantizeBodyOrientationInfo is null, facings = 1 is used. Couldn't the same default be applied in other cases or it isn't always 1 appropriate?

I'm not sure because it was ages ago I last dealt with BodyOrientation itself, but I think there was some reason why we didn't use that approach.
But in any case, it's safer to change this at the yaml level, it's only necessary for some special cases like bridges, not worth risking regressions by changing the code, in my opinion.

**Review by rob-v — APPROVED** [review]
👍

**Pull request merged**
