### PR TITLE
Revise the RA map pool

### PR DESCRIPTION
**Pull request by abcdefg30**
Prompted by https://forum.openra.net/viewtopic.php?p=312265 (and my response https://forum.openra.net/viewtopic.php?p=312265#p312265 ).

Removing:
```
Northwest Passage
Winter Storm
Poland Raid
Snow Off
Barracuda
Icy Ridge
Decrepit Isles
East vs West
Puddles Redux
Tabula Rasa
Vihaan Lunta
Cold Front (we have the dual version)
Encounter
Opposite Force
Six Below Zero
Rapa Nui
Unconventional Warfare
All Connected
Caffeinated
Centre of Attention Redux
Coastal Influence
North by Northwest
Regeneration Basin
Hypothermia
Alaska Anarchy Redux
Engagement
Tainted Peak
Mass Confliction
```

Adding:
```
1v1
Shadowfiend 2
Marigold Town
Forgotten Plains
Blitz
Trapped
Discovery

2v2
Chernobyl
Ridges
Collaboration

3v3
Progress
Fortified

4v4
Altercation
Forward Progress
Archipelago
Ardennes
Ritual Circle

5v5
Dusttown Battle

FFA
Code 19
Europe
```
~~(Tbh, although that were the most wished for maps in the thread, we probably shouldn't ship two versions of Chernobyl and three versions of Marigold Town.)~~

Suggested but not added:
```
1v1
Beyond Destruction
Face Off
River Crossing II
Arid
Mountain Ridge Redux
Pleasant Plains
Stanitsa

2v2
Temptation
Trouble Town
The Swamp
Pitiless

3v3
Europe Universalis 3
Nod Garden
Nod Castle
Frostmourne
Oasis

4v4
Anal Gardens
```

Replacements I didn't find a map for:
```
A replacement for Countercross
A new 5 player ffa map (we only have a single map)
A new 7 player ffa map (remove Unconventional Warfare)
Find another 3v3v3 map (remove Hypothermia)
A new 6v6 map (remove Mass Confliction)
```

### CODE REVIEW

**Comment by abcdefg30** [comment]
Updated with feedback from Discord.

**Comment by deleted-user-1** [comment]
~:-1: to `Anal Gardens`. It's a low-effort derivate of Oregardens and imbalanced because Soviets can't access the plateau in the center. The name is unacceptable for QA, as the identical author name is. It's also an exception to have the author's name in the map name. Someone should make a derivate with an acceptable name and make the plateau inaccessible again and add their map.~

**Comment by deleted-user-1** [comment]
Nvm, i failed to read it correctly as "not added".

**Comment by pchote** [comment]
We know that many casual players like maps like Poland Raid and Bombardment Islands specifically because they can completely cut their base off from the enemy. It would be nice if we could find another one or two maps of this type for the default pool, even though they do murder AI and unit perf.

**Comment by pchote** [comment]
"Beyond Destruction" is listed in both the added and not added lists, and isn't in the PR. Is this intentional?

**Comment by abcdefg30** [comment]
It must have slipped in the `Added` list somehow, fixed.

**Review by pchote — DISMISSED** [review]

**Comment by deleted-user-1** [comment]
Can we maybe get a 2v2v2v2 map? There are some, I know one with islands at the edges where each team spawns and a contested central island and one desert map but cant remember the names.

**Comment by deleted-user-1** [comment]
So I know it's a bit late but this is the 2v2v2v2 map (or at least one variant of it) island map I meant. I think there's also one without the flanking islands but not sure. The version that has them entirely  filled with ore so only ukraine can make room with demos is a bit meh. Fun map though for naval combat. https://resource.openra.net/maps/36088/

Arch Islands could be a replacement for Bombardment Islands (without neutral buildable tech structures in case this is the one with neutral airfields and aa guns):   https://resource.openra.net/maps/33175/

I played both before but haven't looked at these linked maps ingame so it's only a suggestion (in the hope somebody else has time to look over them).

**Comment by OpenOP2Admin** [comment]
I know people dont like the anal gardens map, and neither do i, but the fact remains it is probably the most popular team map right now. I suggest just grabbing the most downloaded version of it, and simply changing the name to "A. Gardens by Painful A"

**Comment by KOYK** [comment]
> We know that many casual players like maps like Poland Raid and Bombardment Islands specifically because they can completely cut their base off from the enemy. It would be nice if we could find another one or two maps of this type for the default pool, even though they do murder AI and unit perf.

@pchote How about this one?
https://resource.openra.net/maps/37990/

**Comment by abcdefg30** [comment]
> Can we maybe get a 2v2v2v2 map?

We could also add https://resource.openra.net/maps/30304/ which is by the same author you suggested, too.

**Review by Smittytron — DISMISSED** [review]

**Comment by pchote** [comment]
@abcdefg30 did you make any progress towards checking with the map authors?

**Comment by abcdefg30** [comment]
Rebased and updated Code 19 with feedback from the map author (WhoCares) since ERCC was removed from it.

> @abcdefg30 did you make any progress towards checking with the map authors?

I still haven't got an answer from all. I'm not sure if I'll get one from the remaining ones, tbh.

**Comment by OpenOP2Admin** [comment]
3 v 3 is a little lacking on the easier maps. Suggest adding Isle of Man https://resource.openra.net/maps/19514/

**Comment by pchote** [comment]
Are we ready to merge this now?

**Comment by abcdefg30** [comment]
Depends on if we want to wait for the latest suggestions to be discussed/approved on the forums/Discord or merge it now and do those in a follow-up.

**Comment by pchote** [comment]
Followup, IMO. I expect this may require further revisions after the first public playtest, so no point spending excessive amounts of time delaying things now.

**Review by pchote — APPROVED** [review]
The Chernobyl map will cause problems for remaster compatibility, but we can cross that bridge when we come to it.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/29f3f32cb2bb4ef51b3ba8eb96d3074ac5d7035f

**Pull request merged**
