### PR TITLE
Make D2k Frigate VTOL

### PR DESCRIPTION
**Pull request by reaperrr**
Finally.

Depends on #16584.

### CODE REVIEW

**Comment by reaperrr** [comment]
Rebased.
I think the upcoming rebase conflict with #16509 is small enough that it's not worth delaying this PR over.

**Comment by pchote** [comment]
If you build a bunch of things at once with the instant build cheat the frigates will land in arbitrary cells away from the starport. We probably should wait for #16509 to fix that first?

**Comment by reaperrr** [comment]
OK, I guess that makes sense.

**Comment by reaperrr** [comment]
Is basically superseded by #16685. Closing.

**Pull request closed without merging**
