### PR TITLE
Prepare TS chrome for fractional DPI/UI scaling

### PR DESCRIPTION
**Pull request by pchote**
This PR completes the set (with #17494, #17495, #17504), implementing the minimum changes required to prevent UI glitches in TS once we enable fractional scaling.

This includes the dialog.png fixes and high resolution UI and production glyphs, but avoids touching chrome.png because, again, the source artwork is not compatible with non-photoshop editors. Fortunately the TS chrome is already layed out in a way that avoids most problems.

I've also skipped a higher resolution load screen because the source artwork uses different colors to the rendered png (or maybe this is another photoshop-ism?), and because I expect we will implement a new loadscreen for TS before release.

Depends on #17495 for the common music chrome changes.

### CODE REVIEW

**Comment by pchote** [comment]
This will need to be updated for #17549, but I will wait until #17495 has been merged.

**Comment by pchote** [comment]
Rebased and added the audio glyph for #17549. This should now hopefully be good to go.

**Comment by pchote** [comment]
Updated with new cash glyph based on https://github.com/OpenRA/ArtSrc/pull/8#issuecomment-573643602.

**Comment by reaperrr** [comment]
- Same minor dropdown arrow misalignment as in D2k (intentional?)
- Dropdowns are missing separator!

👍 once those are adressed.

**Comment by pchote** [comment]
Fixed the separator and filed #17593 to fix the arrow.

**Review by reaperrr — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8a7c18cec108a25577e6c476f123e47b3faf2617...f7842f508f35100fade4a70172270e0ce3e5e51f)

**Pull request merged**
