### PR TITLE
Register the current mod even if LaunchPath is bogus.

### LINKED ISSUE #14186: Mods launched with a bogus Engine.LaunchPath definition won't be registered
This breaks the MP server list, even though the launch path is not used in this case. We should *always* register the current mod, even if it bogus for external switching.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14186.

Testcase: Set the mod version to something with a bunch of online games, then launch the game with a bogus `Engine.Launchpath`.  Before: server list doesn't show any games for the current mod.  After: it does.

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Comment by pchote** [comment]
Ping @OpenRA/engine-hackers.  This is an easy fix to a release blocking bug.

**Comment by reaperrr** [comment]
For the record: I HAVE tested this, not just reviewed the code.

**Comment by pchote** [comment]
Rebased.  Can we please get this merged?

**Review by reaperrr — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/63e0b4ea20146599e1238d294a118f1c135945c0...8308a769035a81b24fa6e49f934ab6e71d49a3ba)

**Pull request merged**
