### PR TITLE
Hide the starport animation from highlights and when not playing.

### PR DESCRIPTION
**Pull request by pchote**
Some more fixes to go along with #12841.

### CODE REVIEW

**Comment by ltem** [comment]
:+1: works for my case

**Comment by Mailaender** [comment]
It still seems to highlight the initial first frame:

image

white dot in the center.

**Comment by ltem** [comment]
hmm in combination with PR #12841 it doesn't appear for me, this was also the way I tested it
- git checkout this pr
- make all 
- switch to fix welding lights pr
- run and compare

**Comment by pchote** [comment]
I also can't reproduce the problem:

screen shot 2017-02-26 at 10 13 04

**Comment by Mailaender** [comment]
I didn't check this in combination with #12841.

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/42920160410fe918340397c97a8d7283cb1dd173...d703ee5d46968382725567db546c4449ecdeab3a)

**Pull request merged**
