### PR TITLE
Added the GDI Juggernaut to Tiberian Sun 

### PR DESCRIPTION
**Pull request by Mailaender**
Depends on / testcase for https://github.com/OpenRA/OpenRA/pull/11787.

### CODE REVIEW

**Comment by pchote** [comment]
Can we please make this use upgrades like the tick tank and mobile sensor array?

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/rules/nod-vehicles.yaml#L192 after which this is modeled. I guess the Nod artillery not using upgrades has a reason.

**Comment by GraionDilach** [comment]
The Nod arty setup predates the Tick Tank/MSA setup. There shouldn't be a reason actually, AttackTurreted can be upgraded to work only in deployed mode.

My question is, will we ship FS as TS or FS will be a techlevel or something akin? (Due to tileset updates and whatnot.)

**Comment by Mailaender** [comment]
> There shouldn't be a reason actually, AttackTurreted can be upgraded to work only in deployed mode.

I am bit more worried about the rendering which needs to change completely.

**Comment by reaperrr** [comment]
> I am bit more worried about the rendering which needs to change completely. Upgrades usually break and are very fiddly to work with in complicated setups.

You just need to replicate the Tick Tank setup. I haven't noticed any breakage or other problems with the tick tank so far.

**Comment by reaperrr** [comment]
Except for the sequences this needs a major rewrite, so I'm taking over and will file an updated PR once #12429 is merged.

**Comment by Mailaender** [comment]
Okay, thanks.

**Pull request closed without merging**
