### PR TITLE
Improved download progress formatting

### PR DESCRIPTION
**Pull request by MorMund**
Now shows the correct magnitude suffix (KB,MB,...)  #6186.

### CODE REVIEW

**Comment by deniz1a** [comment]
So this displays 1024 KB as 1 MB? Wouldn't it be better if that was 1000?

**Comment by Unit158** [comment]
I agree with Deniz. We really shouldn't pervert the metric system. We have KiB for 1024.

**Comment by penev92** [comment]
wut?  o.O

**Comment by deniz1a** [comment]
See #6186 for the discussion.

**Pull request merged**
