### PR TITLE
Fixed some tiling errors in the map 'Winter Storm'

### PR DESCRIPTION
**Pull request by abc013**
## Tiling error 1:

openra-2016-10-23t092514479z
### Changed to:

openra-2016-10-23t092600468z
## Tiling error 2:

openra-2016-10-23t092643479z
### Changed to:

openra-2016-10-23t092733043z

If you find more tiling errors,
tell me, and i will fix them in this PR. :)

### CODE REVIEW

**Comment by abcdefg30** [comment]
👍

**Comment by MustaphaTR** [comment]
:+1:

**Comment by TheRaffy** [comment]
love your sense for graphical aesthetics.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/66976c0cd3f116f3ed068b1581edd12f725e9903...bff695b5b16006333f56d1a3d895a79aa92cfde7)

**Pull request merged**
