### PR TITLE
Add Shuriken Island to the RA official map pool

### PR DESCRIPTION
**Pull request by PunkPun**
I found this map to be an incredibly good naval map, it works well as 3v3 but also should not be bad for 2v2v2 of FFA. Such maps aren't common so I wanted to include it.

map

In exchange I'm removing haos ridges. It's an outdated design and not really played.

### CODE REVIEW

**Comment by Mailaender** [comment]
Can you split into two commits?

**Comment by PunkPun** [comment]
split

**Comment by Mailaender** [comment]
You may need to disable the AI here as it will perform poorly. https://github.com/OpenRA/OpenRA/issues/10483

**Comment by PunkPun** [comment]
Completely forgot about AI. It might be best to avoid merging this until naval AI is improved

**Comment by abcdefg30** [comment]
You can disable bots on that map specifically. I'm also not sure about the Haos Ridges removal.

**Comment by PunkPun** [comment]
disabled bots

**Review by Mailaender — APPROVED** [review]

**Review by RoosterDragon — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0ad549897c3dc9fe36283e8b0ec5c9b9cdd3c91c...72d243da1e434a57441640828c93ed32996c52e2)

**Pull request merged**
