### PR TITLE
Refactor Reservable into Dock trait

### PR DESCRIPTION
**Pull request by reaperrr**
This makes (ab)using `Exit` for landing offsets unnecessary, while also allowing for multiple actors docking to a single dock-providing actor (if it has multiple docks).

Also serves as plumbing to be used by `ResupplyManager`/`Resupply` activity to move ground actors to custom dock locations, instead of hardcoding the center.

Provided a testcase for multiple docks on a single building (RA airfield).

Disclaimer: I'm aware that the resupply anim currently plays for all sprite bodies in the testcase, because the animation trait responds to any resupply tick no matter from which dock it came from. This will be easy to fix once #16464 is implemented in #16446, as those resupply BitSet types would allow us to give each dock its individual type (`dock1-repair` etc.) and then let the animation only run on the corresponding type.
Doesn't affect our official mods though, so I think this can wait until both PRs are merged (though I might address it in this one if #16446 is merged first).

Part of #16403.

### CODE REVIEW

**Comment by matjaeck** [comment]
I gave this a quick test and noticed the following:
- helicopters can not resupply in the testcase - you can not order them to land on a helipad
- planes that have reloaded their ammo won't make room for other planes that need to resupply

The issue with helicopters is a problem for testing docking of multiple actors.

**Comment by reaperrr** [comment]
@matjaeck Could you give more detail how you tested or provide a GIF? Because I just re-tested, and for me both things work just fine.

**Comment by matjaeck** [comment]
@reaperrr see gif below

<details>

dock

The aircraft have been build from the "multi-airfield" and I enabled all debug cheats except visibility.

**Comment by reaperrr** [comment]
I'm really at a loss here. Tried to do things exactly as you did in the gif, but both cases work for me.

@matjaeck Are you on Linux/Mono by any chance?

**Comment by Punsho** [comment]
Also as I see in this gif when the yak reams helipads also run the rearming animation

**Comment by reaperrr** [comment]
> Also as I see in this gif when the yak reams helipads also run the rearming animation

See disclaimer in the original post. That's only because they're a single building here, and will also be fixed in a later PR.

**Comment by Punsho** [comment]
ah yes, sorry about that, overlooked for some reason I though that only helipads are connected

**Comment by matjaeck** [comment]
@reaperrr Yes, I'm on Ubuntu 18.04 / Mono 5.20.1.19.

**Comment by reaperrr** [comment]
> Yes, I'm on Ubuntu 18.04 / Mono 5.20.1.19.

OK. That doesn't *have* to be the reason, but I'm on Windows and this wouldn't be the first time we're running into a Mono bug, which would explain why I can't reproduce it.

**Comment by matjaeck** [comment]
I tested it on windows and have the same issue. Does not seem to be platform-related. Should I upload my settings file?

**Review by PunkPun — COMMENTED** [review]
Did quite a lot of testing and: (I'll call the multi-dock building as mdb)

When a rearmed plane is on the mdb, f key on other planes doesn't make it move away. Only pressing on the mdb with another planes does.

Ports don't work properly, helicopters can be pushed around when landing and still rearm afterwards 

Most of the time only one heli can rearm at a time, sometimes 2 or 3, depends on how you push them around. I also can get 2 planes rearming at the same time, though aircraft never overlap they can rearm at seemingly random locations

**Comment by matjaeck** [comment]
@reaperrr The problem that the testcase only works for Russia's airfield, but not for Ukraine's - and I have only build the one from Ukraine.

**Comment by reaperrr** [comment]
Updated.

> @reaperrr The problem was that the testcase only works for Russia's airfield, but not for Ukraine's - and I have only build the one from Ukraine.

Oops... fixed, ukraine afld will now work, too.

> Ports don't work properly, helicopters can be pushed around when landing and still rearm afterwards

This is the fault of our repulsion logic more than anything else. I disabled repulsion for aircraft that are not at CruiseAltitude (e.g. landing or taking off).

> Most of the time only one heli can rearm at a time, sometimes 2 or 3, depends on how you push them around. I also can get 2 planes rearming at the same time, though aircraft never overlap they can rearm at seemingly random locations

I forgot to mention this: I intentionally set up the left hpad dock to only accept Apaches and the right dock to only accept Hinds. If the repulsion fix above works as intended, it should now only be possible to reload one of each at a time. So multiple Hinds ignoring the left dock is actually the correct behavior in this testcase.

> When a rearmed plane is on the mdb, f key on other planes doesn't make it move away. Only pressing on the mdb with another planes does.

Seems planes sometimes get stuck in the ReturnToBase activity without asking the occupying plane to leave. I still need to figure out what's the exact problem here, but feel free to re-test the rest in the meantime.

**Comment by pchote** [comment]
My initial thought on skimming this is that it is focusing too much on the implementation details of the repair/resupply usecase, which is going to get in the way of our other docking usecases.

The two big usecases that come to mind are
* Harvesters/Refineries
* The custom KKnD docking code - which I haven't looked at in detail, but seems to be mostly implemented in 260b8d5b837eccac031071e62308166a2bb56977 for the engine parts, and in 
https://github.com/IceReaper/KKnD/tree/master/OpenRA.Mods.Kknd for the trait/activity parts.

The two big blockers I can see are determining dock validity based on actor type, and relying on standard move activities for the actual docking behaviour.

If we can change the filtering here to use a `BitSet<DockType>` and implement a new interface/traits that go on the actor doing the docking to return a docking activity (for the current cases this could simply be `Move` / `Land`) we should be much closer to being able to cover these cases.

**Comment by pchote** [comment]
> My main motivation to keep the changes here mostly on the surface was to get the trait renamings and some low-hanging fruits into Next with as-low-as-possible regression risk, by not touching the stuff I moved to ResupplyManager more than necessary for now (within the scope of this PR).
Similar situation for #16470.
>
> I was then hoping to tackle their integration and real internal refactorings during the Next+1/Next+2 cycles, as I see zero chance of making the cut for Next with any deeper refactorings.

(from #16446, responding here where it is more appropriate).

Taking a deep cut like this is a valid approach, but I think it would more manageable (and involve a lot less rewriting/rereviewing of code) if we could do this in several shallow but wider cuts.

Maybe something like:
 * Fix #16462 - this will remove the nastiest code from `Repairable`, and IMO should be a priority for the playtest independently of what we do with docking/resupply.
* Implement a basic `Dock` trait that is conditional, specifies the entrance cell, offset, facing, and a bitset of docking types. Update `Resupply`, `Land`, `Refinery` to use this to manage the docking positions. The `Reservable` trait would remain separate at this point. Activities would query the first valid dock at the start, and cancel themselves if it becomes invalid.
* Implement a `DockingManager` trait modeled after `CaptureManager`. Change activities to use this so that they can switch to a different dock if the one they are targeting becomes invalid while they are moving to it.
* Implement an `IDockable` interface that abstracts cursors and validity checks (based on the dock type bitset). `Repairable` / `Harvester` / etc would implement this interface, and `DockingManager` would then implement the cursor and order management. We'd have a single "Dock" order that sends the dock types in the ExtraData, and the ResolveOrder would ask the `IDockable` traits for a dock activity for the given types.
* Merge anything thats left in `Reservable` into `DockingManager` and make sure it works with all docking types instead of just aircraft reloading.
* Implement the remaining bits of #16446, which should now be very simple (no need for `ResupplyManager`, and the `Repairable`/`Rearmable` traits would be small implementations of `IDockable` with methods to check whether docking is valid and to tick the repair/rearm when docked via the `Resupply` trait)

This discussion might be best moved to a new issue...?

**Comment by reaperrr** [comment]
OK, that roadmap makes sense, copied it to #15023. I guess there's no point in keeping this PR in its current form open then.

**Pull request closed without merging**
