### PR TITLE
Added checks for syntax errors in Lua scripts

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/6879.

### CODE REVIEW

**Comment by Unit158** [comment]
This will require a wiki update stating that Lua 5.1 is now a requirement for make check.

**Comment by abcdefg30** [comment]
Could you also add the check to `make.ps1`?

**Comment by pchote** [comment]
Please either make this optional, or use a separate command for lua vs code checks.  I basically never modify lua files in a way that need syntax checks, so I don't want to be forced to install a system-wide lua package in order to continue using the code style checks.  Likewise, most people working on scripted maps are generally not going to be working on C# code changes at the same time.

**Comment by Mailaender** [comment]
> Could you also add the check to `make.ps1`?

No, I don't have Windows nor do I know how Lua distributions there work and which are common.

**Comment by Mailaender** [comment]
The "I don't want to install Lua (on Mac)" argument is weak. However you are right that mixing those StyleCop checks, which also run a lot longer, with missions together doesn't make much sense so I separated those.

**Comment by Phrohdoh** [comment]
It is not weak at all.
I don't want to install Lua to check C# is perfectly valid.

**Comment by Mailaender** [comment]
> This will require a wiki update stating that Lua 5.1 is now a requirement for make check.

Not anymore. I separated it into `check-scripts` as requested.

**Comment by GraionDilach** [comment]
`make.ps1` still needs to be expanded though.

**Comment by Mailaender** [comment]
Not in this pull request and not by me though.

**Comment by pchote** [comment]
Can you please push a test commit that shows that this fixes

> It should at least go through WorldLoaded or find other obvious problem such as syntax errors and broken actor references.

**Comment by Mailaender** [comment]
Wow, I am astonished that it the `sudo zypper install lua` is such a Linux exclusive luxury. Added a test case for you. It obviously can't check actor references.

**Comment by pchote** [comment]
You're proposing a change to our travis test setup, so it is unreasonable to expect us to merge this without verification that that actually works.  There have been cases in the past where changes where checks were added without testing and only later found to be completely ineffectual because the check did not return 1 on error.

The attitude is unnecessary.

**Comment by Mailaender** [comment]
Don't worry, I locally tested the exit codes. Shall I remove the test commit again?

**Comment by Phrohdoh** [comment]
`luac` being sandboxed is terrible at giving the real error, unfortunately:

```
Checking for Lua syntax errors...
luac: mods/ra/maps/desert-shellmap/desert-shellmap.lua:40: '(' expected near 'if'
make: *** [check-scripts] Error 1
The command "make check-scripts" exited with 2.
```

**Comment by Mailaender** [comment]
Nothing is sandboxed here. This is the real Lua compiler doing it's syntax checks. It spits out the line and position of the error. This is really useful for me and I am annoyed by this simple pull request being delayed and bad-mouthed here. I wanted to work on https://github.com/OpenRA/OpenRA/issues/5490 but made only slow progress due to having to reload the game only to get a crash from a simple syntax error.

**Comment by Phrohdoh** [comment]
The real error is a missing `(a)` not just a `(` preceding the `if` in the function body.

**Comment by Mailaender** [comment]
Static source code analysis isn't trivial for Lua due to the flexibility of the language.

**Comment by Unit158** [comment]
I think it is important to note that Lua is so powerful that you can build an entire other language on it without a huge amount of effort. I'm not talking about a new interpreter either. Just a language that is a script.

**Comment by Phrohdoh** [comment]
@Unit158 I'm not understanding how that is relevant (especially since this can be done with many languages).

**Comment by Unit158** [comment]
It is relevant because Lua can't see the actual "structure" of the program as so much as it sees the words.

**Comment by penev92** [comment]
:+1: from me.
If travis checks all PR-ed/merged scripts and mappers can check them if they want, that's good enough. Kind of sucks that it doesn't include Windows, but `¯\_(ツ)_/¯`
@abcdefg30 can look into it if he feels it can benefit him.

**Comment by Mailaender** [comment]
Removed the test case again. See https://travis-ci.org/OpenRA/OpenRA/builds/75810433 for the recorded run.

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark: with https://github.com/Mailaender/OpenRA/pull/55.

**Comment by Mailaender** [comment]
Thanks!

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4ab2848666ce29abc31b2318937caa2c33a17f09...22fb500391ef9d24a2e168d55e6cc8284c75ac50)

**Pull request merged**
