### PR TITLE
Revert "Lower aircraft altitude"

### PR DESCRIPTION
**Pull request by pchote**
This reverts prs #7842, #7866.

Closes https://github.com/OpenRA/OpenRA/issues/8018.

### CODE REVIEW

**Comment by obrakmann** [comment]
You need to revert #7866, too.

**Comment by pchote** [comment]
Updated.

**Comment by obrakmann** [comment]
The issue that prompted the lowered altitude change is indeed already fixed, it seems. :+1:

**Comment by Mailaender** [comment]
Confirmed. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1adbb780808cc4ad810324bf6ed52a32b58e5141...a2d37ed05509576c3b152efe5da8dfb51a837d7e)

**Pull request merged**
