### PR TITLE
Add a new secondary objective to the soviet06 missions

### PR DESCRIPTION
**Pull request by abcdefg30**
Also fixes an over~~view~~look. `controlCenterTrigger` was probably copied over from `soviet07`, as I didn't find this variable in any of the `soviet06`-scripts in other places.

### CODE REVIEW

**Comment by Mailaender** [comment]
> Also fixes an overview.

You probably mean "overlook and you also need a `player.MarkCompletedObjective(SaveAllTrucks)` so it gets ticked in the end:

image

**Comment by abcdefg30** [comment]
> You probably mean "overlook" here.

I really shouldn't send PRs when I'm tired.

> Needs a  player.MarkCompletedObjective(SaveAllTrucks)  imho so it gets ticked in the end:

Derp (same as above), added. Sorry.

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/af8546907d56a623e1d2aff4c89538b0dca58e87)

**Pull request merged**
