### PR TITLE
Moved Upgrades, SupportPowers and some misc features to Mods.Common

### PR DESCRIPTION
**Pull request by reaperrr**
And moved some loose traits from the Mods.RA root folder into the Traits folder.

### CODE REVIEW

**Comment by penev92** [comment]
:+1:

**Comment by obrakmann** [comment]
needs a rebase

**Comment by reaperrr** [comment]
Rebased.

**Comment by penev92** [comment]
That did not go well...

**Comment by pchote** [comment]
```
OpenRA.Mods.RA/Scripting/Properties/AirstrikeProperties.cs(20,69): error CS0246: The type or namespace name `AirstrikePowerInfo' could not be found. Are you missing an assembly reference?
```

**Comment by reaperrr** [comment]
It puzzles me that a PR that was fine before and showed no conflicts during rebase can break like this.
Could it be that a PR from someone else removed a using that my PR needs?

Anyway, I'll fix it when I get home.

**Comment by penev92** [comment]
I can't say what happened, but you need
`using OpenRA.Mods.Common.Traits;`  in `OpenRA.Mods.RA\Scripting\Properties\AirstrikeProperties.cs` and also to make `AirstrikePower` `public`.

**Comment by reaperrr** [comment]
Updated.

**Comment by abcdefg30** [comment]
(My fault, sorry.) I added ```AirstrikeProperties.cs``` in #7164.

**Comment by reaperrr** [comment]
No need to apologize for adding a featur ;)
I didn't bother checking whether the code still compiles after that rebase, so strictly speaking it was my own fault.

**Comment by obrakmann** [comment]
Compiles with make and md, starts too. :+1:

**Pull request merged**
