### PR TITLE
Make range circles visible to observers

### LINKED ISSUE #8543: Show range diameter in replay for turrets
Add to the turrets the same circle that is on the "Construction yard" that represent the diameter of the range in replay.
openra game_2015_06_22_15_20_27_468
openra game_2015_06_22_15_20_18_226
openra game_2015_06_22_15_20_23_371

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22738005-show-range-diameter-in-replay-for-turrets?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Closes #8543

### CODE REVIEW

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by obrakmann** [comment]
Updated. Changed `Player::IsAlliedWith` to also respect the `Player.Spectating` flag.

**Comment by GraionDilach** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a722a2508f9f871aaab457e26bbf9f70684635ca...414a3b4af734e21659ad56af3e1af35d4208b344)

**Pull request merged**
