### PR TITLE
Fix FallsToEarth not accounting for effective ownership

### LINKED ISSUE #14802: Aircraft husks are Gray after player loses
To test you can just build couple of aircraft and surrender.

aircrafthusk owner

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #14802.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I think {here](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/defaults.yaml#L548) also needs  [this](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/vehicles.yaml#L132-L133) (across all the mods) for it to correctly work, but didn't test so i'm not sure.

**Comment by abcdefg30** [comment]
I thought that as well, for some reason it worked without adding those lines. (Or my local test environment wasn't clean again...)

**Comment by pchote** [comment]
It works because `SpawnActorOnDeath` has a special case logic that changes `OwnerType.Victim` to `OwnerType.InternalName` if (and only if) the player is defeated.

When aircraft are killed on surrender it falls back to Neutral but passes `EffectiveOwnerInit`, and so the fix above produces the correct colour.  When aircraft are killed normally the husks are spawned normally (without `EffectiveOwnerInit`) but as the original owner, so the colours look correct.  The issue hits when an aircraft is killed normally and the player surrenders before it hits the ground.  The husk is owned by the player, so is immediately removed from the world.  Forcing the husk to always spawn as neutral fixes this.

**Comment by abcdefg30** [comment]
Updated.

**Review by MustaphaTR — APPROVED** [review]
Works as described. 👍

**Review by Smittytron — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c9c8e80749a3694d304d72a73a5b1a762fededf4...348f7b2806e0a61f57bf3044f959748bf4bae7ba

Note: Since it was a regression from #13276, I just added this PR to the former's entry since there won't be another playtest.

**Pull request merged**
