### PR TITLE
Reduce InitialSpawnDelay for crates in TD

### LINKED ISSUE #9629: Five minute initial crate spawn delay is probably too long
I forgot about this until watching https://www.youtube.com/watch?v=nKePUk5DBuQ, where fiveaces and @SoScared comment that they think this is a bad change.  I agree, this seems far too long.  A TD game can be half way finished by five minutes.  A 30 - 60 second (max) delay to prevent spawn-time crates would be much more reasonable.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27387944-five-minute-initial-crate-spawn-delay-is-probably-too-long?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #9629.

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by pchote** [comment]
Can we reduce the default to 0, and then set explicit times for all mods?

**Comment by reaperrr** [comment]
Actually, I agree.

**Comment by abcdefg30** [comment]
Updated. (Note the changelog for this should probably go into the one of #9060.)

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/64de10fc1a27ea8380c402108753b8c559c89701...525b2474979096ced5084df4a6abbba0fbbb5b1b)

**Pull request merged**
