### PR TITLE
Prepare D2k chrome for fractional DPI/UI scaling

### PR DESCRIPTION
**Pull request by pchote**
Like #17494 and #17495 but for D2k. See those PRs for more info on the motivation and testing. This one depends on #17495 thanks to the common load screen and music chrome changes.

The scope for D2k is much smaller, mainly because the source psd file isn't compatible with anything but real photoshop, which I don't have. Therefore i've limited changes to the `chrome.png` to just bumping pixels around (and ideally somebody who *does* have photoshop can easily backport these). I have also generated high resolution loadscreen images based on the artsrc renders, and a glyphs.svg ported from RA with some minor d2k-specific additions.

### CODE REVIEW

**Review by dragunoff — DISMISSED** [review]
Looks good in-game. I didn't spot any issues.

**Comment by pchote** [comment]
This will need to be updated for #17549, but I will wait until #17495 has been merged.

**Comment by pchote** [comment]
Rebased and added the audio glyph for #17549. This should now hopefully be good to go.

**Comment by pchote** [comment]
Updated with new cash glyph based on https://github.com/OpenRA/ArtSrc/pull/8#issuecomment-573643602.

**Comment by reaperrr** [comment]
The dropdown down arrow looks slightly misaligned compared to the down arrow on the scroll slider, so unless that's intentional, it should move 1 pixel to the right.

example1

Otherwise LGTM.

**Comment by pchote** [comment]
It turns out that issue has nothing to do with this PR, so I filed the fix in #17593 instead.

**Review by reaperrr — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/05028369a61470e5dc624bddaa3f2e3c25045ea9...8a7c18cec108a25577e6c476f123e47b3faf2617)

**Pull request merged**
