### PR TITLE
Do not shutdown when no one is playing after a long time

### LINKED ISSUE #7451: Server stops after game Timeout has passed
I've had this twice now. My server stops when the set Timeout for a game has passed. Last log entry: `Timeout at 02/08/2015 20:18:37!!!`.

This is what I found in the code: https://github.com/OpenRA/OpenRA/blame/bleed/OpenRA.Game/Server/Server.cs#L692
I believe the `Server.TimeOut` shouldn't cause the program to exit when `Server.DedicatedLoop = True`.

Apart from exiting when the timer times out, it looks like the timer itself is never canceled. Shouldn't the timer be canceled once the game is over?

Full logs:
```
Platform is Linux
Using Null renderer
Using Null sound engine which disables SFX completely
Available mods:
cnc: Tiberian Dawn (release-20141029)
d2k: Dune 2000 (release-20141029)
modchooser: Mod Chooser (release-20141029)
ra: Red Alert (release-20141029)
Loading mod: ra
Game started
No one is playing, shutting down...
Starting a new server instance...
Game started
No one is playing, shutting down...
Starting a new server instance...
Game started
Timeout at 02/08/2015 20:18:37!!!
```

### PR DESCRIPTION
**Pull request by LipkeGu**
closes  #7451

### CODE REVIEW

**Comment by Unit158** [comment]
:-1:

This can be fixed through settings, if I'm reading the code correctly.

**Comment by Unit158** [comment]
My bad. I misunderstood what was trying to be achieved.

**Comment by GeertJohan** [comment]
With this PR there is NO game timeout at all.. This just causes a console log, but doesn't take any action.
I think the Timeout /should/ cause the currently running game to stop, but it shouldn't shut down the complete server.

**Comment by GeertJohan** [comment]
So I don't think this fixes #7451

**Comment by ihptru** [comment]
this does not fix #7451 , issue author asks about  restarting server if Server.DedicatedLoop is True, instead of existing server completely.

**Comment by LipkeGu** [comment]
maybe some other should fixed this :(

**Pull request closed without merging**
