### PR TITLE
Fixing TS EMP issues

### PR DESCRIPTION
**Pull request by PunkPun**
Makes EMP disable Laser Fence 
Makes Mobile Sensor Array lose detection on EMP
Makes subterranean units EMP-able while underground #17090

### CODE REVIEW

**Comment by tovl** [comment]
-Fixes laser fences and mobile sensor array.
-Doesn't fix landed aircraft being EMP-able (it only adds the visual overlay, but doesn't affect the behaviour at all).
-Makes subterranean units EMP-able, but they will not come to the surface.

The last two points cannot be fixed without engine changes, so I'd recommend to drop the third commit and leave that one to fix for later.

**Comment by Punsho** [comment]
There's no reason to delay the third commit. When the engine changes are going to happen they will need to add it either way

**Comment by reaperrr** [comment]
@Punsho I picked your 3rd commit to #17136, so you can remove it (not a requirement, but it would save me a rebase).

**Comment by Punsho** [comment]
> @Punsho I picked your 3rd commit to #17136, so you can remove it (not a requirement, but it would save me a rebase).
👍 removed it

**Review by tovl — APPROVED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]

**Pull request merged**
