### PR TITLE
Updated NuGet dependencies

### PR DESCRIPTION
**Pull request by Mailaender**
- https://www.nuget.org/packages/Mono.Nat/
- https://www.nuget.org/packages/SharpFont/

should both be safe as they don't come with API or Framework changes.

### CODE REVIEW

**Comment by pchote** [comment]
What changes does this bring?

**Comment by Mailaender** [comment]
See the NuGet release notes.

**Comment by penev92** [comment]
Sooo... do the new versions give us anything?

**Comment by Mailaender** [comment]
I need the SharpFont Face.GetKerning() bugfix for https://github.com/OpenRA/OpenRA/issues/5017 and I hope using the latest Mono.Nat version solves some problems with our UPnP based automatic port forwarding.

**Comment by abcdefg30** [comment]
Game still works. :white_check_mark:

**Comment by obrakmann** [comment]
It does indeed. :+1: 

I'd still really prefer if we dropped UPNP support, btw. I hate that we're encouraging users to enable that freaking security nightmare on their routers. That shit belongs to be dead and buried six feet underground.

That's not even mentioning that it only works for a minority of users anyway. It causes way more trouble than it's worth.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/a5f910dab12d63d2c18d0b4d7c91ce055c0bd549)

**Comment by GraionDilach** [comment]
Manual port forwarding is also as user-friendly as the Chinese language for Average Joe, @obrakmann.

**Comment by Mailaender** [comment]
Disabling it by default seems to be a good compromise.

**Comment by GraionDilach** [comment]
It's disabled by default already.

**Comment by pchote** [comment]
It's not just disabled by default: it's disabled by default, with a second checkbox (*also* disabled by default) hidden in the advanced settings menu that you must change before the game will let you enable it.

This is the usability equivalent of putting it on display at the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying _beware of the leopard_.

**Pull request merged**
