### PR TITLE
[RA Map Pool] Replace map Agenda with Bandit.

### PR DESCRIPTION
**Pull request by SoScared**
map uploaded at: http://resource.openra.net/maps/22791/

As mentioned on https://github.com/OpenRA/OpenRA/pull/13972#issuecomment-326791653 and on IRC:

We might want to replace Agenda with a more subtle map for the release. Agenda was initially the only map that reliably showcased all the civilian structures but ideally we might want a map that doesn't throw the player out on a huge and heavily competitive map. Map 'Bandit' is less intimidating in that fashion and plays well too.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Are we sure that we want to replace the map now that we mentioned it explicitly in the news post? We could also just add `Bandit` and keep `Agenda`.

**Comment by reaperrr** [comment]
> Are we sure that we want to replace the map now that we mentioned it explicitly in the news post? We could also just add Bandit and keep Agenda.

I was thinking the same, tbh.

**Comment by pchote** [comment]
We can and should still add Bandit in addition to Agenda if you think it is release-worthy.

**Comment by SoScared** [comment]
Nah given how recent the map is made, better hold out on it. I had an excuse for that with the civilian structures.

**Pull request closed without merging**
