### PR TITLE
Several TD mod fixes

### LINKED ISSUE #8040: TD levelup (+1 Rank) and chevron art use wrong palette
The shps were apparently just copied over from RA, we need to either a) add the RA palette to the TD mod and use that, or convert the shps to TD's own palette.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12193051-td-levelup-1-rank-and-chevron-art-use-wrong-palette?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #8040

Result of my work on TDX.

I have more in the pipeline, but that may take a while. Those were the easiest to port.

Maps:
- Dramatically reduced tile errors on Rogue States and Necessary Illusions, additionally fixed tiberium tree placement
- Replaced tc\* temperate tree groups with desert tree t18 on Rogue States and Chokepoint
- Fixed tiberium tree positions on Break of Day, as well as a minor tile error

Art:
- Converted rank and levelup shps to TD palette
- split Nod airfield's radar dish into separate idle overlay, it looked weird if it's only played when a unit is delivered.

Sound:
- Added two previously unused voice reports to Commando voice set.

### CODE REVIEW

**Comment by pchote** [comment]
Fixes #7973?

**Comment by pchote** [comment]
The dish glitches when transitioning from the end of the make anim to the first idle frame.  Could you reorder the dish animation frames to avoid this?

**Comment by reaperrr** [comment]
It doesn't fix #7973, at least not completely.

> The dish glitches when transitioning from the end of the make anim to the first idle frame. Could you reorder the dish animation frames to avoid this?

The animation starts at the correct frame. The problem is rather that the idle overlay seems to start at the same time as the make animation (right after placement).

**Comment by reaperrr** [comment]
#8109 will fix the alignment issue.

**Comment by pchote** [comment]
Looks good. :+1: now that #8109 is merged.

**Comment by penev92** [comment]
Thanks. Please do share more ;)
:+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/e8421e2d076515e3d3cc0c5653fe0a73088a5df7...b391ab366a726846ea647ea6b799a3f8a5483ca8)
I skipped the airstrip. Feel free to add it if you feel it should be in there.

**Pull request merged**
