### PR TITLE
Prevent non-combatant players from receiving units from crate pickups

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by pchote** [comment]
Looks reasonable to me, but not tested :+0.5:

**Comment by Phrohdoh** [comment]
Is there any reason the same shouldn't be done to `DuplicateUnitCrateAction`?

**Comment by obrakmann** [comment]
A couple:

1. I forgot about it ;)
2. It wouldn't cause civilians to get units that they don't have access to. They just get another civ unit, which is ok by me.

**Comment by GraionDilach** [comment]
I'm not certain if I'd like visceroids getting duplicated.

**Comment by obrakmann** [comment]
Good point, updated.

**Comment by GraionDilach** [comment]
:+1:

**Comment by Mailaender** [comment]
No more random neutral MCVs appearing on the battlefield. ;)

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4c7bee14330cd2530d78d9a57191549779e4e8e2...e5c139a0cc5aaed95c04aa8aa0e59f5fcc11cec8)

**Pull request merged**
