### PR TITLE
Fix TS radar sprite Z offsets and GDI temperate radar sprite

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes cut-off pixels on TS Nod radar at lower sprite borders by shifting depth sprite.

Fixes building->shadow transition of TS GDI radar (was a problem with the sprite, making it look like there was a gap between building and shadow).

Since I was touching the GDI temp radar sprite anyway, slightly polished it by replacing some non-remapable red pixels (some with remap, some with more suitable adjacent colors).

Nod Radar before/after:
naradr
naradr-fix

GDI temperate radar before/after:
gtradr-old
gtradr-new

Note: The GDI radar is slightly cut off at the lower borders of the sprite as well, however it seems shifting the depth sprite Y offset only helps with pixels not 'spilling' onto cells adjacent to the footprint.
Offsetting the entire building up by 2 pixels helps, but that would hide what's potentially an engine issue that should rather be adressed instead.

### CODE REVIEW

**Comment by pchote** [comment]
> potentially an engine issue that should rather be adressed instead.

This sounds like #12229, which I now finally understand the cause of but need to do more research before considering the best fix.

Shifting the depth sprite Y isn't the right fix here: shift the Offset Z instead!

**Comment by reaperrr** [comment]
> Shifting the depth sprite Y isn't the right fix here: shift the Offset Z instead!

That works, updated.

garadr-fixed2

**Review by Smittytron — APPROVED** [review]
Looks good

**Review by pchote — APPROVED** [review]
I expect we'll need to change these again when fixing #12229, but that is already going to be the case for other buildings so i see no harm in taking this for now.

**Pull request merged**
