### PR TITLE
Add more airdrop options

### PR DESCRIPTION
**Pull request by dnqbob**
new-airdrop

### CODE REVIEW

**Comment by PunkPun** [comment]
⚠️ this is violating physics and CnC lore in serious ways

**Comment by dnqbob** [comment]
How?

**Comment by dnqbob** [comment]
Your cargo plane land on the middle of the strip and actor spawn at start of the strip, I don't think that is what the lore suggest.

**Comment by PunkPun** [comment]
1. it looks absurd when Inertia of the aircraft is violated in such an extreme way
2. in Tiberian Dawn lore it's said the aircraft never stops. This is what I quickly found from the wiki

> The large [cargo plane](https://cnc.fandom.com/wiki/Cargo_Plane_(Tiberian_Dawn)) does not land at the field. Instead it slowly flies in at an extremely low altitude and releases the vehicle from the aircrafts cargo bay as it passes over the gently inclined runway.

In openRA we have sped up the plane for balance, although it isn't slow in vanilla as well

**Comment by dnqbob** [comment]
> it looks absurd when Inertia of the aircraft

It is the same for RA actually if you must say that, aircraft should not be stop all in a sudden.

~~And if it is the lore suggested, please just takes the third commit as showcase. Those option is still worthy on other airdrop case.~~

At least airdrop offset needs to be fixed.

**Comment by dnqbob** [comment]
Remove the wait, only fix the landing offset

**Comment by dnqbob** [comment]
d2k-airdrop

Also fix d2k airdrop. I don't see any wiki on D2k starport and I don't think carryall can be release while transport ship is still moving.
@PunkPun

**Review by PunkPun — APPROVED** [review]
LGTM, confirmed that in vanilla d2k they were at the ground for a prolonged period of time

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0dab9be5146892cb8de53acfe211a337a00d2213...cb60940205af4929044c3ba119b9a2f31f3030b5)

**Pull request merged**
