### PR TITLE
Fix compilation with csc/msbuild on non-windows platforms

### PR DESCRIPTION
**Pull request by pchote**
Mono 5 now defaults to `msbuild` and the roslyn `csc` compiler.  Compiling the projects using XS/vs4mac fails because our AfterBuild tasks are expecting to see a mdb symbol file instead of a pdb.

This fixes these errors by checking against the files, not against of the OS.  It also cleans up some stray lines from OpenRA.sln.

Tested with mono 5 on macOS.  We need at least a test with mono 4.x on Linux and VS/.Net on Windows before merging.

### CODE REVIEW

**Comment by atlimit8** [comment]
Well this is what I get after `yaourt -S msbuild-15-bin`, https://gist.github.com/atlimit8/a88b38144955ac8c7e98b95ba07df4d3 and it does run.

**Comment by rob-v** [comment]
This isn't changed, just curious - it is intentional/needed to copy cnc and common to mods/common/, but d2k to mods/d2k.

**Comment by rob-v** [comment]
You could include this change 1acc3b9 in your PR?

**Comment by pchote** [comment]
Included.

**Review by rob-v — APPROVED** [review]
VS/.Net on Windows 👍

**Comment by pchote** [comment]
Rebased.  Can we please get a final :+1: from someone on Linux/macOS?

**Review by obrakmann — APPROVED** [review]
I can confirm that debugging with MD4 works again when compiling with with both Mono 4.4 and 5, so 👍

**Pull request merged**
