### PR TITLE
Remove dead code inside SupportPower.cs

### PR DESCRIPTION
**Pull request by abcdefg30**
Continues https://github.com/OpenRA/OpenRA/pull/19662#issuecomment-1315248228.

### CODE REVIEW

**Review by PunkPun — APPROVED** [review]

**Review by ThomasChr — APPROVED** [review]
My IDE seems to agree, I do too...
image

**Review by dragunoff — APPROVED** [review]

**Review by anvilvapre — APPROVED** [review]
untested.

**Comment by ThomasChr** [comment]
I think even untested is this a sure-fire thing!

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d22769593d108872f1573f04973552065a64aa47...df7e5967dec11d4f6af8708f506c90421e14bcc9)

**Pull request merged**
