### PR TITLE
[RA] Balance - Allied Barracks (Tent) cost increase

### PR DESCRIPTION
**Pull request by SoScared**
Quick fix. Slipped through the code review of balance patch #13790

Allied Barracks, cost $500 up from $400

### CODE REVIEW

**Review by MustaphaTR — APPROVED** [review]

**Comment by SoScared** [comment]
[18:40:17] <SoScared> forgot to add the barracks cost increase to the allied tent, only to soviet barracks
[18:40:39] <SoScared> cringy mistake but it happened

[18:57:53] <@orabot> New pull request #13930 by SoScared: [RA] Balance - Allied Barracks (Tent) cost increase | http://bugs.openra.net/13930

[19:04:13] <SoScared> pchote: ^ will #13930 be a pain to slip that through after the tag and pack?

[19:04:22] <+pchote> SoScared: yes
[19:04:32] <SoScared> ouch
[19:04:38] <SoScared> sorry about that
[19:04:53] <+pchote> the only option is to scrap the current playtest and make an entirely new one
[19:05:04] <+pchote> only option aside from shipping what we already have
[19:05:32] <+pchote> but i'm washing my hands of this - i've done all I need to for the next playtest, so this is between you and reaperrr/abc/whoever
[19:05:47] <SoScared> k k

@reaperrr @abcdefg30 any chance one of you (or any other) would have the time to redo the playtest as stated above? Pretty embarrassing mistake by me but it would be a shame shipping a playtest with such a glaring flaw.

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRAWeb/pull/353 hasn't been merged yet, so there is still time to tag another playtest and update the newspost including download IDs.

**Comment by reaperrr** [comment]
> OpenRA/OpenRAWeb#353 hasn't been merged yet, so there is still time to tag another playtest and update the newspost including download IDs.

I guess that's what we should do then, this also gives us a little more time to hopefully have the organization issues regarding social media adressed by next weekend.

**Comment by SoScared** [comment]
Thanks guys, sorry about the extra work.

Adding the fix ought to help getting more players over to the next playtest.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
b4f0244

https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ed51f80f7b866599a65999aa7d1c0c4204d02da4...6d13863093396f70c3c4a4b4231b68bd86083633

**Pull request merged**
