### PR TITLE
Added a new interface for the Chronosphere

### PR DESCRIPTION
**Pull request by Mailaender**
required for Red Alert 2.

### CODE REVIEW

**Review by sorcerer86pt — DISMISSED** [review]
LGTM

**Comment by abcdefg30** [comment]
We'll need to play the animation before the teleport. Or delay the teleport a bit. I don't know how that is going to work with just this PR.

**Comment by Mailaender** [comment]
I also don't have a plan for that yet. Writing a RA2 Chronosphere trait would be the easiest option, but I don't really want to do that.

**Comment by Mailaender** [comment]
Added the delay as that is probably the best way to go. I didn't intend to do it in this pull request, but it seems you both leave me no choice.

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
Introducing a `DelayedAction` sounds like a bad approach: #12310

**Comment by Mailaender** [comment]
Sorry, didn't know that. Removed the need for `DelayedAction`.

**Comment by pchote** [comment]
Needs a rebase.

IMO if we really do want to go ahead with the `Delay` field then `INotifyChronosphere` needs to be aware of this, otherwise we're going to have to rewrite this all again in the future once people start complaining that weird things happen if the chronosphere or targeted units die while the delay is counting down.

I may be remembering wrong, but I believe that RA2 didn't use a delay at all. It instead played the source animation as soon as you selected the source position, and kept looping it until you select the target. You should implement this by having interface methods to notify the initial source selection, target selection, and cancellation between the two. I expect that you will also need to play that source animation (plus set conditions to freeze the actors?) for all players, which is going to require sending separate orders to set the source and destination (plus a third to cancel without setting a destination)!

**Comment by Mailaender** [comment]
Removed b6fd11a74a833d0bedbbc02cf14149ccc61d3023 again.

**Comment by pchote** [comment]
That still doesn't help my concern, FWIW, which is that the current interface isn't compatible with what RA2 actually needs.

**Comment by pchote** [comment]
Do you want to proceed here? Or should we close this?

**Pull request closed without merging**
