### PR TITLE
D2K - Add Gara Kulon to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
https://resource.openra.net/maps/24432/

### CODE REVIEW

**Comment by ltem** [comment]
I think it would improve the balance to move the worm spawner in front of the bottom player to the south west of the map.

|image|
|:---:|

**Comment by MustaphaTR** [comment]
Updated.

**Review by ltem — APPROVED** [review]

**Review by Smittytron — APPROVED** [review]
👍

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6be1cefa95c74ac21cbfda4c691696d41b8dd56d

**Pull request merged**
