### PR TITLE
Battle for Dune 3v3 map

### PR DESCRIPTION
**Pull request by OmegaBolt**
PR as recommended by penev

### CODE REVIEW

**Comment by penev92** [comment]
I thought we could use another 3v3 map, since we're kind of short on those, and this looks nice.
Here is a [preview](https://www.dropbox.com/s/7l3artsc0yf2n8r/Battle-For-Dune.png), and the [link](http://resource.openra.net/maps/2498/) to the resource site.

**Comment by penev92** [comment]
I decided to test this ingame.
So far I noticed a few broken tiles:



I haven't investigated.

**Comment by penev92** [comment]
OK the map looks good, but I want to play a few test games on it before giving a +1.

**Comment by Mailaender** [comment]
:+1: Looking exceptionally good especially the cliff details! The spice pools inside the rocks near the spawn points are a great idea, too.

**Comment by obrakmann** [comment]
Looks good, :+1: 

Can you please squash those two commits together, please?

**Comment by Mailaender** [comment]
http://resource.openra.net/maps/2499/ is the updated link. Looks like the resource site allows to delete individual revisions.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/03353224e6e935488646a06345f6914a8c0d5bd3...e2a0d936b67c3b334ad4138866b90001577f17d7)

**Pull request merged**
