### PR TITLE
TD mission script fixes

### LINKED ISSUE #8532: "Mao Civil War (a)" initial camera position is incorrect
It is centered in the shroud, with the units entering the world being hidden behind the build palette at 1024 x 850 resolution.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22663626-mao-civil-war-a-initial-camera-position-is-incorrect?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #8534: Some missions are missing "Reinforcements have arrived" notification at the start
Noticed with "Repair the GDI Base (b)", but probably affects others too.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22663948-some-missions-are-missing-reinforcements-have-arrived-notification-at-the-start?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #8537: Repair the GDI Base (b) does not play "Mission Accomplished" audio
May also affect other missions.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22664925-repair-the-gdi-base-b-does-not-play-mission-accomplished-audio?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by clemty**
nod06 (a, b, c): transport helicopter no longer selectable

nod06c would crash if you moved to the extraction point without first picking up the crate
easiest way to reproduce is to edit the map to move to the extraction point immediately

edit: changes added to also fix #8537
edit: changes added to also fix #8534
edit: gdi05b: player's tanks would crush the sandbags in the abandoned GDI base because their owner was set to neutral - set all sbags to either gdi or nod
edit: nod04a: set initial camera position; fixes #8532
edit: fixed sbag owner in gdi04b and nod05 
edit: music now starts playing when a mission starts

is there a way to make the helicopter land in nod06? currently it moves to the flare, then stays there

### CODE REVIEW

**Comment by abcdefg30** [comment]
> nod06 (a, b, c): transport helicopter no longer selectable

Why actually? AFAIK only GDI has helis in those missions?

Otherwise :+1: / :white_check_mark:

**Comment by clemty** [comment]
in nod06, once you go towards the extraction point, a transport is sent to you towards the flare

I've now added the "reinforcements have arrived" notifications to fix #8537 too

**Comment by penev92** [comment]
Is your question
>is there a way to make the helicopter land? currently it moves to the flare, then stays there

still valid?

**Comment by abcdefg30** [comment]
> is there a way to make the helicopter land? currently it moves to the flare, then stays there

The heli should land by itself. If it doesn't, it probably can't because of the flare blocking the required space to land.

**Comment by abcdefg30** [comment]
Also adding the `PR: Rebase me!` label for
> Please get rid of these. Fetch and rebase. Don't pull.

**Comment by penev92** [comment]
OK I haven't played the mission, but I'm pretty sure we want the helicopter to land.

**Comment by clemty** [comment]
the maps use Reinforcements.Reinforce instead of Reinforcements.ReinforceWithTransport - I'll change the missions accordingly and test them

**Comment by Mailaender** [comment]
Can't spot regressions. :white_check_mark: Nice bunch of cleanups.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6d6bb2076c24ecbdf0ab497f9845d7033ca1d1a2...c238339dbd0964dfb8d0f3898c88d7ef4f0346fd)

**Comment by Mailaender** [comment]
Don't forget to add yourself to https://github.com/OpenRA/OpenRA/blob/bleed/AUTHORS!

**Pull request merged**
