### PR TITLE
Fix the --png command trying to use OpenRA's virtual file system

### LINKED ISSUE #10921: Unable to get PNG from SHP in bleed
The same Utility commands which works in release, does not work in bleed anymore and crashes.
Example:
```
$ mono --debug /home/ihptru/Downloads/OpenRA/OpenRA.Utility.exe ra --png /home/ihptru/Downloads/mech.shp /home/ihptru/Downloads/temperat.pal
```

```
Error: Utility application crashed. See utility.log for details

Unhandled Exception:
System.IO.FileNotFoundException: File not found: /home/ihptru/Downloads/mech.shp
File name: '/home/ihptru/Downloads/mech.shp'
  at OpenRA.FileSystem.FileSystem.Open (System.String filename) [0x00031] in /home/ihptru/Downloads/OpenRA/OpenRA.Game/FileSystem/FileSystem.cs:239 
  at OpenRA.Graphics.SpriteLoader.GetFrames (IReadOnlyFileSystem fileSystem, System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders) [0x00003] in /home/ihptru/Downloads/OpenRA/OpenRA.Game/Graphics/SpriteLoader.cs:79 
  at OpenRA.Mods.Common.UtilityCommands.ConvertSpriteToPngCommand.Run (OpenRA.ModData modData, System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015e] in /home/ihptru/Downloads/OpenRA/OpenRA.Utility/Program.cs:84 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: File not found: /home/ihptru/Downloads/mech.shp
File name: '/home/ihptru/Downloads/mech.shp'
  at OpenRA.FileSystem.FileSystem.Open (System.String filename) [0x00031] in /home/ihptru/Downloads/OpenRA/OpenRA.Game/FileSystem/FileSystem.cs:239 
  at OpenRA.Graphics.SpriteLoader.GetFrames (IReadOnlyFileSystem fileSystem, System.String filename, OpenRA.Graphics.ISpriteLoader[] loaders) [0x00003] in /home/ihptru/Downloads/OpenRA/OpenRA.Game/Graphics/SpriteLoader.cs:79 
  at OpenRA.Mods.Common.UtilityCommands.ConvertSpriteToPngCommand.Run (OpenRA.ModData modData, System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015e] in /home/ihptru/Downloads/OpenRA/OpenRA.Utility/Program.cs:84
```

File exists on given path.

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #10921.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: 

For people trying to reproduce, you need to use absolute paths, the crash isn't triggered with relative ones.

**Comment by ihptru** [comment]
will this work for other commands like --import-ra-map ?

**Comment by pchote** [comment]
It won't, those commands will need to be fixed individually.  Ironically I pointed out the issue and fix for the map importers back in #10404, but it was ignored.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6b75e9d7c23f1c61579dabcde2ea2c0adad746c9...5ff240d7145e61bd3fbe8d35bc176cedc56fa8de)

**Pull request merged**
