### PR TITLE
Change remaining Vulcan vs Light values to 50

### LINKED ISSUE #14185: Strange change to "Vulcan" weapon (smallcaliber.yaml)
The weapon features 6 different "Warhead" attributes that deal damage. 

With the last patch a single one of these (Warhead@4Dam_2) had it's damage reduced vs "light" from 60% to 50% while the other 5 remain at 60%

Intentionally or where the other warheads overlooked?

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #14185 
Was intended with #13790

### CODE REVIEW

**Comment by MustaphaTR** [comment]
`Warhead@1Dam: SpreadDamage` is still using default 60 coming from `Inherits: ^HeavyMG`. Please add `Light: 50` under `None: 200` under there too.

**Comment by Smittytron** [comment]
> Warhead@1Dam:` SpreadDamage is still using default 60 coming from Inherits: ^HeavyMG. Please add Light: 50 under None: 200 under there too.

Hmm, talked to SoScared about that. Problem is that'll nerf Yaks and Hinds vs light vehicles as well, which was not intended. Would it be best to take Vulcan off of inheritance?

**Comment by MustaphaTR** [comment]
> Hmm, talked to SoScared about that. Problem is that'll nerf Yaks and Hinds vs light vehicles as well, which was not intended. Would it be best to take Vulcan off of inheritance?

That's incorrect, you need to change it under `Warhead@1Dam:` SpreadDamage` or Vulcan, not ^HeavyMG.

**Comment by Smittytron** [comment]
Ugh, I clearly don't know how to squash correctly

**Comment by reaperrr** [comment]
Do you rebase via commandline or GUI?
For the former, you'd just have to `git rebase -i HEAD~2`, delete the line with the first commit, then execute `:x`. Then force-push your local branch to this PR branch again.

**Comment by Smittytron** [comment]
Thanks! This should look more sane now.

**Review by MustaphaTR — APPROVED** [review]

**Comment by reaperrr** [comment]
Just wondering, do you know if @SoScared actually made that balance change based on test results with correct values (as in this PR), or did he also only change that 1 value on the balance test maps?

I'm asking because if the 60 -> 50 nerf was based on only 1 nerfed warhead, a value of 57 or 58 for all warheads would be the closest match.
I have no idea if the pillbox is still considered too powerful on bleed/current release so maybe this PR is wanted as-is either way, I just want to make sure we don't merge a change based on a misconception.

**Comment by Smittytron** [comment]
I couldn't find a change to vulcan values in SoScared's playtest maps. It looks like he had the change listed as a [potential alternative](http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&t=20017) apart from the playtests. I'll see if I can get ahold of him to clarify. 

What I can confirm is that the strength of pillboxes, including the ability to shred light vehicles, is still a common complaint I hear.

**Comment by SoScared** [comment]
The vulcan change was on the loose end of the playtests. As @Smitty mentioned its strength vs light armor was a common observation however, having a very limited area of effect (and new path for the game meta) fixing the values to all-50/60 is probably fine either way.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3092d6b7e74ddf27e53394c3a9fac7c6850309fa

**Pull request merged**
