### PR TITLE
Fixed the faction insignia being drawn over the radar minimap

### PR DESCRIPTION
**Pull request by Mailaender**
An oversight introduced by https://github.com/OpenRA/OpenRA/pull/7384.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
A bit more time to review the merged PR would have probably allowed this to be caught.

**Comment by pchote** [comment]
Could you please use more descriptive commit messages? "change order" means nothing when viewed in the commit list.

**Comment by Mailaender** [comment]
Updated. I thought the people giving their :+1: were testing my branch. The thumps up = I like this idea or "vote" for someone to please fix this bug or implement this feature seems far more popular. https://www.bountysource.com/extension I think we should use another icon for the review process. Maybe something like :white_check_mark:

**Comment by pchote** [comment]
This is only a problem because people aren't following the rule that :+1:s must be qualified ("code looks good" / "found no regressions" / etc) to count for review.  A lone :+1: says nothing about what the person has actually done with respect to the pull request.

**Comment by penev92** [comment]
:+1: 
Fixes the insignia problem.

**Comment by rappo** [comment]
@Mailaender there's also the shipit frog (:shipit:) which is "looks good to me!"

**Comment by Phrohdoh** [comment]
That is the most rodent-like frog I have ever seen.

**Comment by rappo** [comment]
Haha.... I had a complete brainfart while typing that, since it's actually a squirrel. :P

**Pull request merged**
