### PR TITLE
Add Tiberian Dawn Nod Campaign 10b

### PR DESCRIPTION
**Pull request by dtluna**
Add the 10b mission a.k.a. ["Destroy the Mammoth Tank Facility"](http://cnc.wikia.com/wiki/Destroy_the_Mammoth_Tank_Facility) for the Tiberian Dawn Nod campaign.

[Playthrough of the original mission](https://www.youtube.com/watch?v=M4egg2X78NE)

### CODE REVIEW

**Comment by obrakmann** [comment]
Would it be possible for you to port some of the original triggers over? The original mission was already pretty bland, and without any triggers it feels kinda lifeless.

**Comment by dtluna** [comment]
@obrakmann if only I knew what the triggers were.

**Comment by obrakmann** [comment]
They are in [the .ini file](http://nyerguds.arsaneus-design.com/cncstuff/mappics/campaign-nod/maps/scb10eb.ini).  Documentation for them can be found here: http://cnc.wikia.com/wiki/Tiberian_Dawn_Mission_Manual

**Comment by dtluna** [comment]
@obrakmann I'll try to implement them.

**Comment by dtluna** [comment]
@obrakmann I've implemented these triggers but I also have an idea to make the engineer unit like in the original game (not able to capture husks and captures buildings with full hp)

**Review by obrakmann — CHANGES_REQUESTED** [review]
Thanks, much better already!

A few more suggestions:
* I'm wondering whether we should make it an objective to keep Rambo alive?
* For added polish, set the initial cash to 0, and remember to give Nod enough cash in WorldLoaded so that they can build that infantry squad.
* In the original, the four rifle men in the lower left patrol up and down the Western base entrance. This would be nice to have as well.
* Regarding the engineer husk capture: I think this mission would actually be a nice lesson how to use that feature. Players probably won't use it on the medium tanks, but after killing that Mammoth they'd probably be tempted.
* As for the building capture, I'd do what the other missions do as well. In TD there's not much to be gained by changing it. In RA it was a completely different story before the last release when it still had reusable engineers.

**Review by obrakmann — DISMISSED** [review]
:+1:

**Comment by reaperrr** [comment]
`keepRamboAliveObjective` isn't marked as complete when you win and Commando is still alive.
👍 after that is fixed.

**Comment by dtluna** [comment]
@reaperrr Fixed!

**Review by reaperrr — APPROVED** [review]

**Pull request merged**
