### PR TITLE
Avoid some memory allocations

### PR DESCRIPTION
**Pull request by RoosterDragon**
Very minor, but a couple of small changes to avoid some memory allocations.

### CODE REVIEW

**Comment by pchote** [comment]
Looks fine to me, but I haven't tested anything.

**Comment by obrakmann** [comment]
Looks and plays fine, :+1: But I get the impression that you're really grasping for straws now with these optimizations.

**Comment by penev92** [comment]
Looks good to me :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/75d8d724a5e08b356ef897a3f2a25341eb963833...e925bfc228b9c1e8d776c1e71a9879a7e45a7f98)

**Pull request merged**
