### PR TITLE
RA/TD - Add 1 Tile Cliffs by Nooze

### PR DESCRIPTION
**Pull request by MustaphaTR**
These should really help to avoid situations like [this](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=300471#300471) and give mapmakers more ability. Also D2K and RA2 for sure and possibly TS has such 1 block cliffs, so why not RA and TD.

Here are some images, some of those may not be really fitting in this shape in some tilesets, so does original tiles, there are some places even some of the original tiles don't fit so didn't really get into that. Those issues are visible on winter and for some reason water desert ones.

Temprate:
1clifftemp
1clifftempratwater

Desert:
1cliffdesert
1cliffdesertwater

Snow:
1cliffsnowtd
1cliffsnowwater

Jungle:
1cliffjungle

Winter:
1cliffwinter

Looks like i took some of the SS with pixel doubling some without sorry for that.

### CODE REVIEW

**Comment by reaperrr** [comment]
The desert versions don't look that convincing to me, not only are the edge discontinuities more visible, the coloring of the cliff (and water) is a bit off, too.

**Comment by MustaphaTR** [comment]
We taked about that on IRC with Nooze and Pchote. I'll update later when Nooze redoes them.

**Comment by pchote** [comment]
Note that I support this PR in principle (after the quality issues are fixed) because this solves a real problem for map authors.  I remain quite strongly against adding random decorative tiles that serve no additional purpose.

**Comment by MustaphaTR** [comment]
I'm planning to add decorative stuff either. Just these and bridges.

**Comment by MustaphaTR** [comment]
Updated.

**Comment by pchote** [comment]
The desert cliffs are still paletted incorrectly:

screen shot 2017-03-11 at 11 23 09

Make sure that whatever software you're using doesn't apply color profiles, or, even better, keep it as a paletted image while editing it.

If you can fix this issue then I think we could get away with pulling this into the next playtest/release, but I wouldn't want to hold up a release just for this.

**Comment by SoScared** [comment]
I'm the nitpicky type but there's some glitches that sticks out that concern me a bit. Many of these are lines of pixels along the connecting edge:
issue1
issue2
issue3
issue4

**Comment by MustaphaTR** [comment]
> If you can fix this issue then I think we could get away with pulling this into the next playtest/release, but I wouldn't want to hold up a release just for this.

Not really want to hold another playtest if one will happen soon, but i would love to see this in the proper release. I2ll try to fix the palette issue.

**Comment by pchote** [comment]
@SoScared: those demonstration screenshots weren't a good choice, because the cliff corners themselves have those kind of issues.  It is more important that they look correct when blended with regular flat/angled cliffs.

**Comment by SoScared** [comment]
Yeah true. I'd still want to point to the first and last image as sticking out a bit too much tho.

**Comment by reaperrr** [comment]
In my opinion once the desert palette issue is fixed, these are "good enough" for a merger, we can then fine-tune them for Next+1.
These discontinuities are barely noticable with pixel doubling disabled.

**Comment by reaperrr** [comment]
Looks like this was silently updated yesterday.

I think for Next+1 or Next+2 they need some fine-tuning (water pixels of the desert versions are still a little off), but the palette issues are fixed (see updated OP screenshots) and they look good enough to merge them for now. 👍

**Review by reaperrr — APPROVED** [review]

**Review by GraionDilach — APPROVED** [review]
LGTM :+1:

**Comment by MustaphaTR** [comment]
Actually Nooze have me another edited verison of the desert tiles that i think weill work this time. He said on IRC that previous files were based on his other tiles instead of original, which didn't fit, so these new ones should fit better, i'm currently turning them to shp. Should be ready in at most a half hour.

**Comment by MustaphaTR** [comment]
Updated the PR/Image above.

@GraionDilach , @reaperrr : need your confirmations again.

**Review by GraionDilach — APPROVED** [review]
LGTM. :+1:

**Comment by reaperrr** [comment]
👍

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/acbc7488ed3784af708a83d388b34b4b46fbaf93...4cd6f6001247e317e71c0cf6ad1fc9cee0ef99ae)

**Pull request merged**
