### PR TITLE
Compress all pngs.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Reduces size used for png files from 19,034,446 bytes to 13,305,798 bytes in total. Reduces size used for oramap files from 2,774,405 bytes to 2,614,332 bytes in total.  The smaller files also improve loading times as the zlib decoder has less bytes to schlep through.

The PNG decoder shipped with OpenRA only supports a bit depth of 8 for images with a palette, so must must ensure that other depths (1,2 or 4) are not used.

zopfilpng is used for compression with the following command line: 'zopflipng.exe --keepcolortype -y -m image.png image.png'

The keepcolortype flag ensures the bit depth is not changed.

The oramap files were updated by:
- Saving as a folder, unpacking the data in loose files.
- Compressing the png files using the command above.
- Saving back as an oramap, except instead of regenerating the map preview on save we save the existing version on disk.

----

Amount of time spent on PNG decoding during loading of each mod

| Mod | Before | 1st commit | 2nd commit |
| -- | --: | --: | --: |
| TD | 3.0% | 2.6% | 2.3% |
| RA | 2.5% | 2.2% | 2.1% |
| D2K | 8.8% | 5.6% | 5.1% |
| TS | 1.2% | 1.2% | 1.2% |

A black background on gdi05c/map.png is also fixed.

### CODE REVIEW

**Comment by PunkPun** [comment]
Shouldn't we also automatically compress map previews generated by OpenRA?

**Comment by RoosterDragon** [comment]
Yes that could be sensible to tackle in a follow-up. It could also be something for the resource centre to manage.

**Comment by pchote** [comment]
Compressing previews will change the map UID, so it would need to be done on map save.

Compressing all the previews inside the oramap files should grant even more of a win?

**Comment by RoosterDragon** [comment]
Pushed a second commit which compresses the pngs within the oramap files. This nests another modest performance improvement. Have updated the first post with extra details + stats.

**Comment by PunkPun** [comment]
Both Red Alert and Tiberian Sun crash on launch with

```
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.FileFormats.Png..ctor(Stream s) in /OpenRA/OpenRA.Game/FileFormats/Png.cs:line 34
   at OpenRA.Graphics.Sheet..ctor(SheetType type, Stream stream) in /OpenRA/OpenRA.Game/Graphics/Sheet.cs:line 52
```

Mod content crashes with

```
Exception of type `System.InvalidOperationException`: Cursor sequence `default` attempted to load an indexed sprite but does not define Palette
   at OpenRA.Graphics.CursorManager.ConvertIndexedToBgra(String name, ISpriteFrame frame, ImmutablePalette palette) in /OpenRA/OpenRA.Game/Graphics/CursorManager.cs:line 228
   at OpenRA.Graphics.CursorManager..ctor(CursorProvider cursorProvider) in /GitHub/OpenRA/OpenRA.Game/Graphics/CursorManager.cs:line 75
```

IMO it's a must to include automatic compression into openra. The need to regenerate all non-custom map previews comes from time to time.

**Comment by RoosterDragon** [comment]
Issues fixed, thanks.

Filed #20918 to follow-up on teaching OpenRA better compression.

**Review by PunkPun — APPROVED** [review]
LGTM

**Pull request merged**
