### PR TITLE
Replace BLOXMAS.R8 with R16 eqivalent

### PR DESCRIPTION
**Pull request by Porenutak**
BLOXMAS.R8 doesn't have R16 equivalent, but luckily we use just some tiles from bridge and Rotten-base category. Most visible difference is on sand and rock terrain. I replace these in BLOXMAS.R8 with R16 equivalentfrom other tilesets. 
Before:
d2k-2024-03-15T103853238Z

After:
d2k-2024-03-15T103955522Z

### CODE REVIEW

**Comment by Porenutak** [comment]
update: removed file BLOXXMAS.R8 from content as its no longer needed.

**Comment by pchote** [comment]
>  I replace these in BLOXMAS.R8 with R16 equivalentfrom other tilesets.

Can we reference these directly in arrakis.yaml instead of shipping duplicated artwork?

**Comment by Porenutak** [comment]
I meant I replace R8 sand artwork with R16 artwork by blending multiple tiles pixel by pixel in gimp. There is nothing to refer.

**Comment by Porenutak** [comment]
Technically its new artwork.

**Comment by pchote** [comment]
Ok, would it make sense to include only these tiles as part of the customtiles.r16?

**Comment by Porenutak** [comment]
sure. I will convert it into PNG. All R16 tileset editors require 640x1280 resolution. That is only reason why file is so big.

**Comment by Porenutak** [comment]
I moved all BLOXMAX.R16 tiles to the customtiles.r16

**Review by PunkPun — COMMENTED** [review]
I dunno if this is problematic, but a few of the tiles still don't match the sand texture

1099 and 1100
Screenshot 2024-06-03 at 12 55 27

1092
Screenshot 2024-06-03 at 12 55 53

515
Screenshot 2024-06-03 at 12 56 23

514
Screenshot 2024-06-03 at 12 57 24

**Comment by Porenutak** [comment]
fixed
d2k-2024-06-04T081825355Z
d2k-2024-06-04T081837221Z
d2k-2024-06-04T081852754Z
d2k-2024-06-04T081921688Z

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/41f53ef5326c77ca3b74372f44115073caaa0599...014e333e7296da2ee299fb3c4ea2b4168ba0f262)

**Pull request merged**
