### PR TITLE
Revise the TD Map Pool 2020

### PR DESCRIPTION
**Pull request by Orb370**
After some discussion with the TD community, we came to agreement on these changes.

The maps being removed are outdated. Some outdated maps were left in since they were deemed "Classic" or "Unique".

The new maps are some of the many new maps made in the last few months. Some are classics that weren't part of the map pool yet (like Badland Ridges).

Removing (13 maps):

```
Avocado
Contra
Dead in Motion
Letters from Lexington
Plan B
The New Mandarins
Understanding Power
Desert Lakes
Winter's End
Frostways
Thawed Front
Tiberium Canopy
Twisted peak
```

Adding (15 Maps):

African Gambit by MASTER, Jay https://resource.openra.net/maps/36153/ 1vs1 map
Badland Ridges by The Echo of Damnation https://resource.openra.net/maps/21004/  1vs1 map
Desert Mandarins by MASTER https://resource.openra.net/maps/38721/ 1vs1 map
Reaching Out by BLACK https://resource.openra.net/maps/38726/ 1vs1 map
Tiberium Rift by ZxGanon https://resource.openra.net/maps/38456/ 1vs1 map
Deserted Outpost by MASTER https://resource.openra.net/maps/38768/ 2vs2 map
Master Alert by MASTER https://resource.openra.net/maps/38467/ 2vs2 map
Fight Win Prevail by J MegaTank https://resource.openra.net/maps/38224/  2vs2 map
Master Of The Jungle Book by MASTER https://resource.openra.net/maps/32341/ 2vs2 map
Desert Invasion by BLACK https://resource.openra.net/maps/38769/ 3vs3 map
Tiberium Forest by J MegaTank https://resource.openra.net/maps/35702/ 3vs3 map
Valley of Gold (6P) by Irnub/CombinE https://resource.openra.net/maps/38457/ 3vs3 map
Anvil of War by The Echo of Damnation https://resource.openra.net/maps/32753/  4vs4 map
Elysian Expanse by The Echo of Damnation https://resource.openra.net/maps/29014/  4vs4 map
Armageddon by J MegaTank https://resource.openra.net/maps/33912/ 5vs5 map

### CODE REVIEW

**Review by abcdefg30 — COMMENTED** [review]
Looks like some really nice maps. I only spotted two minor things while skimming over them:
- Desert Mandarins:
grafik
I guess that is intentional, but looks a bit odd to me. I don't know how to fix it so I guess it can stay.
- Deserted Outpost:
grafik
The tree on the ridge is a bit odd, but hiding what appears to be a tiling error which should be fixed if possible.

**Comment by Orb370** [comment]
Megatank fixed the tiling errors. PR updated

**Comment by Orb370** [comment]
A few more tile errors fixed.

**Review by abcdefg30 — APPROVED** [review]

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2061dacdb4d58f0977fc563ab5a303eea1c0fd13

**Pull request merged**
