### PR TITLE
Changed the chat notification sounds for RA mod

### PR DESCRIPTION
**Pull request by huwpascoe**
The current sound "BEDOOP" is kind've obnoxious right? The other mods get nice chat sounds now so how about these?

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: for ra, :-1: for cnc

**Comment by huwpascoe** [comment]
Okay this is the last available sound effect that could work for cnc chat sound.

Failing that would we be able to just use the same one as RA?

**Comment by Mailaender** [comment]
:+1: for RA.

This is now identical to the blocked button click in TD which is kinda confusing.

Also D2k needs some kind of change very badly.

**Comment by huwpascoe** [comment]
Any suggestions for replacement sounds are welcome!

**Comment by Mailaender** [comment]
Let's go for the on RA bleep change only now which seems uncontroversial.

**Comment by huwpascoe** [comment]
Okay just the RA one then

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9b603ceeae5f66b61c07d3d3742e9c0450d67cfa...930ab26f7311681baf9ea139903c9c83aeed8bba)

**Comment by MicroJOo** [comment]
:+1: 
thx @huwpascoe , this makes even the chat-spam agreeable (for my ears)

**Pull request merged**
