### PR TITLE
Fixed BuildingCommonNames magic

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/9326.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Why is this `For stable`?

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/9326 was reported in the last playtest.

**Comment by abcdefg30** [comment]
:+1:

**Comment by Mailaender** [comment]
Updated.

**Comment by reaperrr** [comment]
Code makes sense and no crashes in two all-AI games (1 RA with naval, 1 TD on Haos Ridges).
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/88fc56d53f4e03f1e0dbadb5d2e6dd26a8a8c5f2...a3eca9b144e5aae42a4db74501e1d78a8fd013d5)

**Pull request merged**
