### PR TITLE
Add new enemy detection voice notifications to RA and D2k

### PR DESCRIPTION
**Pull request by penev92**
As yet another attempt to address people's issues with the "Enemy units approaching" notifications that both RA and D2k provide us with, deniz1a created some new notifications, which should be better suited for the task:
"Enemy units detected" in D2k and
"Enemy detected" in RA.
Now, we may or may not want to go with "Enemy units detected" in RA as well, I'll leave that up for discussion.
I converted the to .wav and uploaded here for easier testing:
[Atreides](https://www.dropbox.com/s/ao4us7b20o6myf0/AI_ENEMY_DETECTED.wav)
[Harkonnen](https://www.dropbox.com/s/yyb21agsfyoa8s5/HI_ENEMY_DETECTED.wav)
[Ordos](https://www.dropbox.com/s/a5i8a3ddzmz7u0g/OI_ENEMY_DETECTED.wav)
[RA](https://www.dropbox.com/s/r2357sht2902otc/enmydet.wav)

Also if anyone wants an easy way to hear the original files but doesn't have an appropriate tool, [this one](http://d2kplus.com/audioconverter.php) works pretty well.

I will probably add a commit that actually makes use of these tomorrow.

### CODE REVIEW

**Comment by Mailaender** [comment]
They all seem to have a certain noise fading out in the end that should be cut out, but otherwise well done.

**Comment by obrakmann** [comment]
Both the Atreides and Ordos sounds have a hissing distortion after the 's' in 'units'. Would be nice if that could be avoided. Don't know if the source audio allows that, though.

The RA sound is good. Not sure if "enemy units detected" would be better, but I doubt it would make such a difference in the end.

**Comment by penev92** [comment]
OK you can now hear the new notifications ingame. The revert is so that I can actually make use of them, I'm not saying "bring it back now". People might still have problems with frequency/quantity `¯\_(ツ)_/¯` .

**Comment by obrakmann** [comment]
The 's' sound indeed doesn't sound so bad in-game.  But the filename extensions of the three .aud files need to be upper-case as well, otherwise the game can't find them on operating systems with case-sensitive filesystems.

**Comment by obrakmann** [comment]
Ok, I'm fine with those. :+1: when the filenames for the d2k .auds are all upper-case.

**Comment by Mailaender** [comment]
I tested this and the "Enemy detected" seemed a bit random. When I discovered their base and attacked the enemy units I got no notification. As I then surrendered and the map got revealed it said "Enemy detected" which was a bit weird.

**Comment by penev92** [comment]
File names have been fixed.

**Comment by Mailaender** [comment]
It works nicely with the new sounds. :+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/68287a88679111c9a8f8fc4b5d29bec718f2b0ea...0652f76a7f36ce8050d1f54636e173095ab886d0)

**Pull request merged**
