### PR TITLE
Remove EjectOnDeath from RA Vehicles

### LINKED ISSUE #14020: Decide whether to keep EjectOnDeath on RA vehicles
#13892 had an unintentional side-effect of fixing an old, long broken and forgotten feature in the RA mod to spawn infantry from destroyed vehicles. 

If we want to keep this "new" feature then it should be listed in the Changelog.  If not, then `EjectOnDeath` should be removed from the `^Vehicle` default.

Related IRC discussion / initial report: https://logs.openra.net/?year=2017&month=09&day=11#23:10:07

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #14020

### CODE REVIEW

**Comment by AoAGeneral** [comment]
Shouldn't the QTNK keep the Eject code? Since its a vehicle that is self destructing with an escaping pilot?

**Comment by Smittytron** [comment]
The pilot actually ejects before the self destruct using different logic. The -Eject line was there to prevent an additional rifleman from spawning after detonation.

**Comment by AoAGeneral** [comment]
Ah I see so the Eject counts for the actual dead vehicle. That makes sense. ^^ nevermind

**Review by pchote — APPROVED** [review]

**Review by SoScared — APPROVED** [review]
Works as promised, seem to have caught all rule exceptions as well. Nicely done.

**Comment by GraionDilach** [comment]
This might resolve #4693 from the POV of the RA mod but doesn't implement the actual feature requested there so i disagree with this PR closing that ticket.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/d5555cd7ac855866271c0e99f4e329f5255977b4

 0b78f93

**Pull request merged**
