### PR TITLE
Fix crates not spawning immediately on the dropzone maps

### LINKED ISSUE #10227: Initial crate spawn delay breaks dropzone maps
We'll need to override it back to 0 for these.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29122318-initial-crate-spawn-delay-breaks-dropzone-maps?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #10227.

### CODE REVIEW

**Comment by pchote** [comment]
Don't forget the TD dropzone map(s)!

**Comment by abcdefg30** [comment]
Updated.

**Comment by obrakmann** [comment]
:+1:

**Comment by pchote** [comment]
:+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e07a01de6b8e6748a479add9a63fd2e4295fd1dd

**Pull request merged**
