### PR TITLE
Fix northern boundary on new maps.

### LINKED ISSUE #10944: MapSize/Bounds calculation when creating new map is broken
If I tell the editor to create a 64x80 map, it creates a 64x96 map. 64x78 resulted in 64x94. So it always adds 16 to the height. Pretty annoying.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #10944, which is on the release milestone.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by obrakmann** [comment]
This creates a 128x112 map for me, instead of 128x128:

Bleed:
```
MapSize: 130,146
Bounds: 1,1,128,144
```

This branch:
```
MapSize: 130,146
Bounds: 1,17,128,128
```

I don't quite understand why yet, `Map.SetBounds` is called with the expected arguments.

**Comment by obrakmann** [comment]
Turns out it's `System.Drawing.Rectangle` fucking things up:

screenshot from 2016-04-01 16 54 42

**Comment by obrakmann** [comment]
:+1: then

**Pull request merged**
