### PR TITLE
Update SDL to 2.0.20

### PR DESCRIPTION
**Pull request by teinarss**

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Comment by pchote** [comment]
This is giving the same assertion failed error on macOS as 2.0.17 was. Something must need to be changed in the build config, which will require another nuget update.

**Comment by pchote** [comment]
We should update to 2.0.20 while we're at it.

**Comment by Mailaender** [comment]
```
Platform is Linux
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.2
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 347
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 290
   at OpenRA.Launcher.Program.Main(String[] args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Launcher/Program.cs:line 32
```

```
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 159
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 368
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 159
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 368
```

**Comment by teinarss** [comment]
@Mailaender can you try to downgrade the sdl2.so to 2.0.16 and also test update to 2,020?

**Comment by Mailaender** [comment]
Both 2.0.8 and 2.0.20 crash.

**Comment by teinarss** [comment]
> Both 2.0.8 and 2.0.20 crash.

What about 2,0,16?  The one we are using on bleed. Also does it work on bleed for you (without using the environment var?)

Otherwise the only thing I can suggest is to link directly to https://github.com/teinarss/SDL2-CS/tree/nugetified and see which commit starts to crash.

**Comment by Mailaender** [comment]
If `2.0.16` is the one I am using all the time, by default, then that works without problems.

**Comment by Mailaender** [comment]
Comparing https://nuget.info/packages/OpenRA-SDL2-CS/1.0.28 to https://nuget.info/packages/OpenRA-SDL2-CS/1.0.30 I see a new `SDL2-CS-legacy.dll.config`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<dllmap os="!windows" dll="SDL2.dll" target="libSDL2-2.0.so.0" />
	<dllmap os="openbsd" dll="SDL2.dll" target="libSDL2.so" />
	<dllmap os="osx" dll="SDL2.dll" target="libSDL2.dylib"/>
</configuration>
```

However the package does not ship those.

**Comment by Mailaender** [comment]
https://nuget.info/packages/OpenRA-SDL2-CS/1.0.29 also fails on Linux.

**Comment by teinarss** [comment]
Updated.

**Review by pchote — APPROVED** [review]
Working on macOS

**Review by Mailaender — APPROVED** [review]
Works fine on Linux

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5603a6fe5e5207b53ccae5cb2dd93c651c2fe3c8...6dba4500ac30c941a18d1e64b556a665062dbf51)

**Pull request merged**
