### PR TITLE
Fixed a crash on empty mission options

### LINKED ISSUE #21464: Crash on Mission Browser - Infiltration - Game Options
```
Loading mod: ra
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Widgets.Logic.MissionBrowserLogic.<>c__DisplayClass36_2.<RebuildOptions>b__12() in OpenRA/OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs:line 382
   at OpenRA.Mods.Common.Widgets.ButtonWidget.Draw() in OpenRA/OpenRA.Mods.Common/Widgets/ButtonWidget.cs:line 258
   at OpenRA.Mods.Common.Widgets.DropDownButtonWidget.Draw() in OpenRA/OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs:line 68
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 505
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 507
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter() in OpenRA/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs:line 231
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 507
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 507
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 507
   at OpenRA.Widgets.Widget.DrawOuter() in OpenRA/OpenRA.Game/Widgets/Widget.cs:line 507
   at OpenRA.Game.RenderTick() in OpenRA/OpenRA.Game/Game.cs:line 748
   at OpenRA.Game.Loop() in OpenRA/OpenRA.Game/Game.cs:line 856
   at OpenRA.Game.Run() in OpenRA/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenRA/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenRA/OpenRA.Launcher/Program.cs:line 32
```

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/21464.

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
I think this is more an error on the map side. Maybe a better fix would be to improve linting?

**Comment by Mailaender** [comment]
I just imitate behavior from lobby logic, so I am very confident that I am on the right track.

**Review by RoosterDragon — APPROVED** [review]
I think having this match the lobby logic when there are no option values makes sense.

**Review by PunkPun — APPROVED** [review]
Alright

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/91765ad8646a0feb0ba2225e1ca2f6bf94cfbe4e...e726b4c513690e022aad99c68aa7bc23a5bc4c43)

**Pull request merged**
