### PR TITLE
Add 'Reload aircraft' hotkey (ammo not full) #4950

### PR DESCRIPTION
**Pull request by rob-v**
F (Deploy-Return to base) no change - returns all aircraft to base
new 'Reload aircraft' hotkey (G default, can be changed) - returns to base only aircraft which needs reload (not full ammo)

obrazok

### CODE REVIEW

**Comment by pchote** [comment]
I consider this to be a bad idea.  If the "return to base" feature is not fit for purpose, then that should be changed.  Adding an entirely new hotkey that works *almost* the same adds UI complexity that runs against the goal of having a streamlined control scheme.

This also ties in to the long running argument about having the game play itself vs providing a skill ramp by requiring players to manage their own units.

**Comment by pchote** [comment]
@rob-v I would appreciate it if you could restart discussion on tickets before starting work on them.

Anybody can file issues, and many tickets are based on opinion or frustration rather than planned game design.  It would save all of us a lot of time if these tickets could be evaluated and a proper plan of attack determined (which may be closing the ticket) *before* the PR stage.

**Comment by rob-v** [comment]
@pchote Ok, sorry.

**Comment by pchote** [comment]
Closing as discussed in IRC.

**Pull request closed without merging**
