### PR TITLE
Add support for using launch-game.cmd with parameters

### PR DESCRIPTION
**Pull request by abcdefg30**
Follow-up of #13033.
You can now specify the mod when calling `launch-game.cmd` from the command line.

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Review by pchote — DISMISSED** [review]
I'd prefer it if we could make this work the same way as `launch-game.sh`: pass all the arguments to OpenRA.Game.exe, and show the chooser if one of them doesn't start with `Game.Mod=`.

This link might be helpful: http://stackoverflow.com/questions/29655065/check-if-batch-variable-starts-with

**Comment by abcdefg30** [comment]
Updated.

**Review by pchote — APPROVED** [review]

**Comment by reaperrr** [comment]
The console window still closes for me when closing the game.
First commit works, though.

**Comment by abcdefg30** [comment]
If you open it by double clicking, it should still close. The window just remains open now, if you used the command line to execute the script.

**Comment by reaperrr** [comment]
Right, my bad. 👍 then.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/210ca7802efda00c007f8bcd6bb8214897054582...1c3b36d4916eb90cbb62f27d5fb76df953036ed6

**Pull request merged**
