### PR TITLE
Fix attack move lines not showing up for undeploy on force move units

### LINKED ISSUE #19793: GrantConditionOnDeploy prevents AttackMove TargetLine being rendered
## Issue Summary

As title, Present on live & bleed TS mod.

## Reproduction

Load TS, build Tick Tanks or Juggernauts, issue queued move orders and you will see it displays properly with shift held.
Now repeat with attack move and the Target lines are not rendered but the orders are still followed.
 
## Expected behavior

Target Lines should render.

attackmove

### PR DESCRIPTION
**Pull request by PunkPun**
Closes #19793

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Comment by dragunoff** [comment]
Works as promised. However I wish there was an explanation (in the commit message or at least in the PR) why this is the fix.

**Comment by PunkPun** [comment]
it is explained in the issue

**Comment by PunkPun** [comment]
Added the explanation to the commit as requested

**Review by dragunoff — APPROVED** [review]
@PunkPun thanks for adding the explanation to the commit - that is a great place for it as it is closer to the code.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d878969fcb6246782a6a0b9557d37840174df684...9fa07222ab81d982f1f3aba946ee307795d18b12)

**Pull request merged**
