### PR TITLE
PreviewActor offset behavior toggle-able.

### PR DESCRIPTION
**Pull request by IceReaper**
PreviewActor has the default behavior of overwriting the offset with the actual rendered sprite center. This behavior is not toggle-able. When turned off, the sprite is positioned with its defined offset again.

### CODE REVIEW

**Comment by pchote** [comment]
Can you elaborate on your use case for this?

The code calculates the size based on the rendered sprite size, and the offset corresponds to this.  Disabling the offset without adjusting the bounds will mean that any actor where the sprite is not centered on the actor's CenterPosition will extend outside the selection bounds.

See this example with the TS billboards:

screenshot 2018-10-25 at 22 49 45

**Comment by IceReaper** [comment]
thats exactly how i want it. For kknd2 i have an ui where i render the actor previews in and animate them on mouse over. i want to center them, scale them so the smallest side fits, and then crop it with the scissors to its button region.

**Comment by pchote** [comment]
Can you show some images to demonstrate this?

**Comment by IceReaper** [comment]
Just refactored my code, dont need the pr anymore. Is there interest in merging this? otherwise it can be safely closed.

**Pull request closed without merging**
