### PR TITLE
Rebalanced stat gains from rank-up

### PR DESCRIPTION
**Pull request by reaperrr**
It was mentioned on IRC that the first, relatively powerful rank-up allows jeeps, for example, to safely bring infantry like spies and engineers to enemy buildings.

This is mainly because the firepower, armor and speed bonuses are about 10% each on first rank-up, whereas the next two, harder to reach rank-ups only add 4-5%.

This lowers the initial buffs, generally flattens the 'armor' curve for level-ups, and lowers the maximum bonus for armor and speed.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: I can follow the reasoning. Leveled up yaks can also out-run SAM missiles etc.

**Comment by pchote** [comment]
Fixes #8603.

**Comment by penev92** [comment]
Seems legit :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/c811593fe0400ab73c96f5546a2603c1543b6829...a8017c81acbfd688120d6de89209773fc9f2f7f0)

**Pull request merged**
