### PR TITLE
Fix McvManagerBotModule spamming deploy orders

### PR DESCRIPTION
**Pull request by abcdefg30**
Removes the 'activeMCVs' list since it was not useful.
The real bugfix is not iterating over 'activeMCVs' when issueing new orders (this was previously needed for already discovered mcvs that stopped) but over 'newMCVs' instead.
See this line: https://github.com/OpenRA/OpenRA/blob/d20182f158bdf2baa91945b437e628a610c71cc3/OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs#L154
On bleed the mcv manager will do something like this for new mcvs:
grafik

I suggest testing this by observing a bot with a new mcv that is stopped a few times so you can see the fixed version does actually still issue orders to it. You can use a script like this:
```
WorldLoaded = function()
	local player = Player.GetPlayer("Multi0")
	Trigger.AfterDelay(DateTime.Seconds(5), function()
		local mcv = Actor.Create("mcv", true, { Owner = player, Location = CPos.New(40,80) })
		Trigger.AfterDelay(DateTime.Seconds(5), function()
			mcv.Stop()
		end)
		Trigger.AfterDelay(DateTime.Seconds(10), function()
			mcv.Stop()
		end)
	end)
end
```

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]
Looks sane.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/631ea4259af2f3b26585fcdc9dbc3d5b6f75ac4c...76167a0e523729492a0d5cec70585d1dc5a66aa8

**Comment by pchote** [comment]
@Inq8 suggested in Discord that this may have introduced a significant performance regression.

**Comment by abcdefg30** [comment]
I really can't believe this is causing anything significant (we actually only reduced enumerations). Are you sure this isn't more likely to be caused - if at all [1] - by the second PR he linked (#16347)? ([1]: Actually I'm not even sure if I trust this method of performance measuring.)

I just ran a 10-minute AI game (6 AIs, maximum speed) and `newMCVs` is empty except for the start (since they didn't build new MCVs).

**Comment by pchote** [comment]
The Firestorm PR shouldn't be making any logic-related changes to anything in the default mods - just adding a new extension point in the base support power code which should have a negligible overhead.

**Comment by abcdefg30** [comment]
Yes, should not, but does. It changes much of the support power related code and even take cover and the changes in general are much less clear than in this PR - if one of those is really responsible it is more likely we overlooked something in #16347 than here.

**Comment by pchote** [comment]
We eventually discovered that the performance issues were caused by aircraft, nothing to do with this PR.

This was picked to prep as 609dadc51bba3e4f8b16266703e8f4b61aeccc0d, changelog https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2c76f8e60815891c77e2aedbbfa1a111d40a8dd6

**Pull request merged**
