### PR TITLE
D2K - Fix tile 443

### PR DESCRIPTION
**Pull request by MustaphaTR**
That cliff tile supposed to allow infantry to pass. You may want to check the original game first, but i'm sure about that.

Image:
cliff

### CODE REVIEW

**Comment by pchote** [comment]
This is reverting part of #10037.  It would be nice if we could get some agreement on what these tiles are supposed to allow.

**Comment by MustaphaTR** [comment]
There is this tile on Harkonnen Mission 7 at right to the base we capture,  if you wanna look to original game. Uou can open directly this mission using MissionLauncher of Gruntmods Edition.

**Comment by MustaphaTR** [comment]
Here is a SS from original game.

**Review by pchote — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/cf0b2c23985b518b8a38bb6a62d68eb33acd0075...4e3f1c22f87ed63d8f5e7b68031cbcf1570f3529)

**Pull request merged**
