### PR TITLE
Create only one scratch vertex buffer for rendering

### PR DESCRIPTION
**Pull request by RoosterDragon**
Previously several buffers were created but only one was ever used.

### CODE REVIEW

**Comment by Mailaender** [comment]
Can't spot any regressions. Tested unit rendering, the grid overlay and A* debug layer. :white_check_mark:

**Comment by pchote** [comment]
Looks good to me :+1:

**Comment by chrisforbes** [comment]
ARGH, NAK NAK NAK.

This looks unused, but it's a performance workaround for lousy drivers that fail to `rename` our BO memory and instead decide to stall.

**Comment by chrisforbes** [comment]
[It looks like someone broke the actual behavior of this some time ago. I don't have time to do the archaeology to untangle it now]

**Comment by Mailaender** [comment]
Next time, better leave a comment in the source code explaining those.

**Pull request merged**
