### PR TITLE
Fix missing click sounds on observer stat hotkeys.

### LINKED ISSUE #14726: Click sound for StatisticsBasic, but no sound for other hotkeyed tabs
Self-explanatory.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14726.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]

**Comment by ltem** [comment]
I thought I already had approved this PR but turns out I only clicked the `Review changes` button. 
Nevertheless 👍 from me, I couldn't spot anything missing.

**Comment by GraionDilach** [comment]
This requires a changelog entry I presume and being pushed to prep.

**Comment by ltem** [comment]
Yep, I'm already on it

**Comment by ltem** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/0e5ededa3211c4e040641e0ca61fa70c670361f5...6d19b05acb5c7dfe42e2c44605f3a0f8d0f589bf)

[60749b25](https://github.com/OpenRA/OpenRA/commit/60749b250fa859259314e681e68080daebed7273)

**Pull request merged**
