### PR TITLE
Expose RallyPoint.AddIndicator to public API

### PR DESCRIPTION
**Pull request by Mailaender**
Fix for https://github.com/Dzierzan/OpenSA/issues/110.

### CODE REVIEW

**Comment by pchote** [comment]
This implies that the first `RallyPointIndicator` is somehow being removed from the world. How is this happening, and can we fix that instead? The `RallyPointIndicator` already knows how to handle owner change, there should be no reason to have to add new ones.

**Comment by Mailaender** [comment]
[The colony is using `health.resurect`.](https://github.com/Dzierzan/OpenSA/blob/master/OpenRA.Mods.OpenSA/Traits/Colony/Colony.cs#L191)

**Comment by pchote** [comment]
`Health.Resurrect` causes all sorts of problems (like this one!), and should not be used for player owned actors. I don't think we should be trying to work around its problems in upstream code. What is stopping SA from using husk actors instead?

**Comment by Mailaender** [comment]
Victory conditions are pretty much tied to capturing dead colonies.

**Comment by pchote** [comment]
Better than breaking the rally point in all other mods! (this currently duplicates the flag)

**Comment by Mailaender** [comment]
Fixed the flag duplication.

**Review by abcdefg30 — APPROVED** [review]
Ok.

**Comment by reaperrr** [comment]
I'm a bit confused by the title vs. what this PR actually does now.

If I'm reading the code right, this now only puts the stuff from Created into a public method, so 3rd-party mod code can call that method if it needs to refresh the rally point?

**Comment by Mailaender** [comment]
Yes, that is correct. I am actually fine with not integrating this (although it doesn't hurt) and rewriting [Colony.cs](https://github.com/Dzierzan/OpenSA/blob/master/OpenRA.Mods.OpenSA/Traits/Colony/Colony.cs) which @IceReaper wrote in a hurry back then.

**Comment by pchote** [comment]
> (although it doesn't hurt)

IMO it does midly hurt by adding confusion about why that code has been split out into its own method, and risks breaking in the future if someone decides to move it back inline.

**Comment by abcdefg30** [comment]
Making it `virtual` like at https://github.com/OpenRA/OpenRA/blob/86f61298e61c49b90935366d8beb071b2d1524d7/OpenRA.Mods.Common/Traits/Conditions/ConditionalTrait.cs#L64-L70 could avoid some confusion.

**Pull request closed without merging**
