### PR TITLE
Use UTF8 instead of system locale code page

### LINKED ISSUE #10308: Exception during assets extracting 20151224
Hit by an exception while trying to extracting the downloaded assets.

Platform: Linux 64bit(Fedora 23 64bit)
Official build from OBS: http://download.opensuse.org/repositories/games:/openra/Fedora_22/noarch/openra-20151224-5.1.noarch.rpm

exception.log attached.

PS: Exception type looks a bit similar with https://github.com/OpenRA/OpenRA/issues/7668.

[exception.log.zip](https://github.com/OpenRA/OpenRA/files/72920/exception.log.zip)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29428731-exception-during-assets-extracting-20151224?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10332: Add `LC_ALL=en_EN openra` to linux launchers
This works around mono choking on non-english locales.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29470864-add-lc_all-en_en-openra-to-linux-launchers?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
as recommended by https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756

Closes https://github.com/OpenRA/OpenRA/issues/10332 in a cleaner way.
Probably fixes https://github.com/OpenRA/OpenRA/issues/10308.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by RoosterDragon** [comment]
:+1:

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/048fac368fdb63b65615fd0dae2de772398e5a61)

**Comment by pchote** [comment]
It turns out that this wasn't enough to fix the problem for everyone.  Installing the `libmono-i18n4.0-all` package (debian/ubuntu) helped in at least one of these cases.

**Pull request merged**
