### PR TITLE
FixHeader: Add support for "/LargeAddressAware"

### LINKED ISSUE #304: Buildsystem doesnt set Flag "/LargeAddressAware"
See https://github.com/OpenRA/OpenRA/issues/12125#issuecomment-250557430

### LINKED ISSUE #12125: OpenRA.Game.exe is not "/LARGEADDRESSAWARE"
first log:

```
Red Alert 2 Mod at Version {DEV_VERSION}
on map 844106135f7993f089abf392d5371af5b0f002d7 (Blank by Matthias Mailänder).
Date: 2016-09-28 20:39:46Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
GC Memory (post-collect)=695.334.048
GC Memory (pre-collect)=696.076.948
Working Set=923.467.776
Private Memory=925.814.784
Virtual Memory=1.745.629.184
   bei OpenRA.Graphics.Sheet.CreateBuffer() in d:\ssss\OpenRA\OpenRA.Game\Graphics\Sheet.cs:Zeile 133.
   bei OpenRA.Graphics.Sheet.GetData() in d:\ssss\OpenRA\OpenRA.Game\Graphics\Sheet.cs:Zeile 32.
   bei OpenRA.Graphics.Util.FastCopyIntoChannel(Sprite dest, Byte[] src) in d:\ssss\OpenRA\OpenRA.Game\Graphics\Util.cs:Zeile 60.
   bei OpenRA.Graphics.Theater.<>c__DisplayClassc.<.ctor>b__1(Int32 j) in d:\ssss\OpenRA\OpenRA.Game\Graphics\Theater.cs:Zeile 79.
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei OpenRA.Graphics.Theater..ctor(TileSet tileset) in d:\ssss\OpenRA\OpenRA.Game\Graphics\Theater.cs:Zeile 69.
   bei OpenRA.Graphics.WorldRenderer..ctor(ModData modData, World world) in d:\ssss\OpenRA\OpenRA.Game\Graphics\WorldRenderer.cs:Zeile 59.
   bei OpenRA.Game.StartGame(String mapUID, WorldType type) in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 168.
   bei OpenRA.Game.LoadShellMap() in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 446.
   bei OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   bei OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 433.
   bei OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass2f.<LoadMod>b__2d()
   bei OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in d:\ssss\OpenRA\OpenRA.Game\Primitives\ActionQueue.cs:Zeile 53.
   bei OpenRA.Game.LogicTick() in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 577.
   bei OpenRA.Game.Loop() in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 712.
   bei OpenRA.Game.Run() in d:\ssss\OpenRA\OpenRA.Game\Game.cs:Zeile 752.
   bei OpenRA.Program.Run(String[] args) in d:\ssss\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 134.
   bei OpenRA.Program.Main(String[] args) in d:\ssss\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 41.
```

Reproduce case (maybe 3 attempts needed but do not cclose the game):
1. load the mod and open dustbowl in the map editor and load 2 other maps afterwards in the editor (everytime without saving)
2. Goto Mod chooser and reload the mod

### PR DESCRIPTION
**Pull request by LipkeGu**
closes #12125 Thanks to @chrisforbes who explained me the PE Header Layout =)
closes https://github.com/OpenRA/ra2/issues/304

To test:
- use VS `dumpbin.exe` in:

```
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin> .\dumpbin.exe /HEADERS <OpenRA.Game.exe-path>
```

the output should be:

```
FILE HEADER VALUES
             14C machine (x86)
               3 number of sections
        57EEF3CA time date stamp Sat Oct  1 01:22:50 2016
               0 file pointer to symbol table
               0 number of symbols
              E0 size of optional header
             122 characteristics
                   Executable
                   Application can handle large (>2GB) addresses <---- here
                   32 bit word machine
```
- or use PE Explorer (look for the checkbox) next to the red square under characteristics

pe_explorer

### CODE REVIEW

**Review by chrisforbes — APPROVED** [review]
Yeah! 👍

**Comment by LipkeGu** [comment]
would be nice to see this in the next Playtest

**Comment by GraionDilach** [comment]
Is fixheader used during Windows compilation?

**Comment by LipkeGu** [comment]
Mit wiil be merged when this fix ist merged

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ef6c11d382c85b2edbe6f7a91fa228e6deb0a012)

**Comment by GraionDilach** [comment]
This doesn't affect Windows.

**Comment by LipkeGu** [comment]
@GraionDilach Yes it is not linked in make.ps1 so it will only patch the binary in linux.

**Pull request merged**
