### PR TITLE
Fix RepairableBuilding never stopping repair

### LINKED ISSUE #20240: Buildings keep repairing after reaching full health
Buildings continue to repair after reaching full health (which keeps draining funds). Then you're not able to stop the repairing until the building becomes damaged again.

Most likely caused by: https://github.com/OpenRA/OpenRA/pull/20208

### PR DESCRIPTION
**Pull request by PunkPun**
Closes #20240

### CODE REVIEW

**Comment by darkademic** [comment]
Have confirmed that this fixes the problem.

**Review by abcdefg30 — APPROVED** [review]
The `return` should have become a `continue`. 🤦 Untested but code changes LGTM.

**Review by dragunoff — APPROVED** [review]
Fix confirmed and code changes LGTM :+1:

**Comment by PunkPun** [comment]
#20208 didn't have a changelog

**Pull request merged**
