### PR TITLE
Add Soviet13b

### PR DESCRIPTION
**Pull request by Smittytron**

### CODE REVIEW

**Comment by pchote** [comment]
Here's the output from my script decoder (still missing TeamType actions, I will try to come back to finishing this soon):

<details>
<summary>Click to expand</summary>

```
Trigger@LOS1:
	On:
		 House "Greece" owns building of type "DOME"
		 AND
		 Attached cell entered or attached building captured by house "USSR"
	Actions:
		 Set global scenario variable 1
		 Run trigger "los5"
	Disable: After running once
	AttachedTo:
		Cells: 24,99, 25,99, 26,99, 27,99, 28,99, 29,99, 30,99, 31,99, 24,100, 25,100, 26,100, 27,100, 28,100, 29,100, 30,100, 31,100, 24,101, 25,101, 26,101, 29,101, 30,101, 31,101, 24,102, 25,102, 26,102, 29,102, 30,102, 31,102, 24,103, 25,103, 26,103, 27,103, 28,103, 29,103, 30,103, 31,103, 24,104, 25,104, 26,104, 27,104, 28,104, 29,104, 30,104, 31,104, 24,105, 25,105, 26,105, 27,105, 28,105, 29,105, 30,105, 31,105
Trigger@hnt1:
	On:
		 0.0 minutes have elapsed
	Actions:
		 Create team "hunt1"
		 Reinforce with team "mcv1"
	Disable: After running once
Trigger@sea1:
	On:
		 35.0 minutes have elapsed
	Actions:
		 Create team "sea1"
	Disable: After running once
Trigger@prod:
	On:
		 0.0 minutes have elapsed
	Actions:
		 Enable production for house "Greece"
		 Enable production for house "Good"
	Disable: After running once
Trigger@ent2:
	On:
		 Attached cell entered or attached building captured by house "USSR"
	Actions:
		 Create team "hunt2"
		 Create team "hunt1"
	Disable: After running once
	AttachedTo:
		Cells: 58,14, 59,14, 58,15, 59,15, 58,16, 59,16, 58,17, 59,17, 58,18, 59,18, 58,19, 59,19, 58,20, 59,20, 58,21, 59,21
Trigger@los2:
	On:
		 All buildings (excluding civilian) and units owned by house "USSR" are destroyed
	Actions:
		 House "USSR" is defeated
	Disable: After running once
Trigger@win1:
	On:
		 All buildings (excluding civilian) and units owned by house "Greece" are destroyed
		 AND
		 All buildings (excluding civilian) and units owned by house "Good" are destroyed
	Actions:
		 House "USSR" is victorious
	Disable: After running once
Trigger@chro:
	On:
		 Attached unit or building is destroyed
		 LINKED
		 Attached cell entered or attached building captured by house "USSR"
	Actions:
		 House "USSR" is defeated
		 House "USSR" is victorious
	Disable: After running once
Trigger@los3:
	On:
		 All buildings (excluding civilian) owned by house "Germany" are destroyed
	Actions:
		 House "USSR" is defeated
	Disable: After running once
Trigger@los4:
	On:
		 Global scenario variable 1 is set
		 LINKED
		 Attached cell entered or attached building captured by house "USSR"
	Actions:
		 Destroy attached buildings
		 Run trigger "win2"
	Disable: After running once
	AttachedTo:
		 Actor1 (pdox owned by house "Germany" at cell 27,101)
Trigger@win2:
	On:
		 Manual Trigger
	Actions:
		 Play speech message "OBJRCH1"
		 House "USSR" is victorious
	Disable: After running once
Trigger@win3:
	On:
		 Attached unit or building is destroyed
	Actions:
		 Disable trigger "los3"
	Disable: After running on all attached objects
	AttachedTo:
		 Actor10 (dome owned by house "Greece" at cell 49,104)
		 Actor38 (dome owned by house "Greece" at cell 29,90)
		 Actor39 (dome owned by house "Greece" at cell 48,88)
		 Actor40 (dome owned by house "Greece" at cell 69,89)
Trigger@reac:
	On:
		 Attached unit or building is destroyed
	Actions:
		 Destroy attached buildings
	Disable: After running once
	AttachedTo:
		 Actor62 (v19 owned by house "Greece" at cell 26,78)
		 Actor63 (brl3 owned by house "Greece" at cell 26,77)
		 Actor66 (v19 owned by house "Greece" at cell 54,96)
		 Actor67 (brl3 owned by house "Greece" at cell 53,96)
Trigger@air1:
	On:
		 4.2 minutes have elapsed
		 AND
		 Global scenario variable 2 is set
	Actions:
		 Reinforce with team "air1"
	Disable: After running once
Trigger@air2:
	On:
		 6.0 minutes have elapsed
	Actions:
		 Set global scenario variable 2
	Disable: After running once
Trigger@air3:
	On:
		 Attached unit or building is destroyed
	Actions:
		 Clear global scenario variable 2
	Disable: After running on all attached objects
	AttachedTo:
		 Actor26 (hpad owned by house "Greece" at cell 32,73)
		 Actor27 (hpad owned by house "Greece" at cell 55,96)
		 Actor41 (hpad owned by house "Greece" at cell 56,76)
		 Actor48 (hpad owned by house "Greece" at cell 61,80)
Trigger@mly1:
	On:
		 0.1 minutes have elapsed
	Actions:
		 Create team "mlay1"
	Disable: After running once
Trigger@mly2:
	On:
		 3.0 minutes have elapsed
	Actions:
		 Create team "mlay1"
	Disable: After running once
Trigger@para:
	On:
		 House "USSR" has built building of type "AFLD"
	Actions:
		 Enable repeating superweapon "PARA_BOMB" for house "USSR"
		 Enable repeating superweapon "PARA_INFANTRY" for house "USSR"
	Disable: After running once
Trigger@auto:
	On:
		 16.2 minutes have elapsed
	Actions:
		 Enable AI autocreate for house "Greece"
		 Enable AI autocreate for house "Good"
	Disable: After running once
Trigger@los5:
	On:
		 Manual Trigger
	Actions:
		 Reveal area around "waypoint75" (27,101)
		 Display text message 55 from tutorial.ini
	Disable: After running once
Trigger@setg:
	On:
		 0.0 minutes have elapsed
	Actions:
		 Set global scenario variable 5
		 Run trigger "set7"
	Disable: After running once
Trigger@set7:
	On:
		 Manual Trigger
	Actions:
		 Set global scenario variable 6
		 Set global scenario variable 7
	Disable: After running once
Trigger@des1:
	On:
		 Attached unit or building is destroyed
	Actions:
		 Clear global scenario variable 5
	Disable: After running once
	AttachedTo:
		 Actor42 (syrd owned by house "Greece" at cell 73,84)
Trigger@des2:
	On:
		 Attached unit or building is destroyed
	Actions:
		 Clear global scenario variable 6
	Disable: After running once
	AttachedTo:
		 Actor43 (syrd owned by house "GoodGuy" at cell 32,43)
Trigger@des3:
	On:
		 Global scenario variable 5 is not set
		 AND
		 Global scenario variable 6 is not set
	Actions:
		 Clear global scenario variable 7
	Disable: After running once
Trigger@lst1:
	On:
		 6.0 minutes have elapsed
		 AND
		 Global scenario variable 6 is set
	Actions:
		 Reinforce with team "lst6"
	Disable: After running once
Trigger@lst2:
	On:
		 13.0 minutes have elapsed
		 AND
		 Global scenario variable 5 is set
	Actions:
		 Reinforce with team "lst1"
	Disable: After running once
Trigger@lst3:
	On:
		 23.0 minutes have elapsed
		 AND
		 Global scenario variable 7 is set
	Actions:
		 Reinforce with team "lst2"
		 Reinforce with team "hel2"
	Disable: After running once
Trigger@lst4:
	On:
		 34.0 minutes have elapsed
		 AND
		 Global scenario variable 5 is set
	Actions:
		 Reinforce with team "lst5"
	Disable: After running once
Trigger@lst5:
	On:
		 50.0 minutes have elapsed
		 AND
		 Global scenario variable 6 is set
	Actions:
		 Reinforce with team "lst4"
	Disable: After running once
Trigger@lst6:
	On:
		 63.5 minutes have elapsed
		 AND
		 Global scenario variable 7 is set
	Actions:
		 Reinforce with team "lst7"
		 Reinforce with team "lst3"
	Disable: After running once
Trigger@lst7:
	On:
		 72.0 minutes have elapsed
		 AND
		 Global scenario variable 6 is set
	Actions:
		 Reinforce with team "hel1"
		 Reinforce with team "lst4"
	Disable: After running once
Trigger@lst8:
	On:
		 84.0 minutes have elapsed
		 AND
		 Global scenario variable 7 is set
	Actions:
		 Reinforce with team "lst6"
		 Reinforce with team "lst2"
	Disable: After running once
Trigger@hel1:
	On:
		 69.2 minutes have elapsed
	Actions:
		 Reinforce with team "hel2"
	Disable: After running once
Trigger@sea2:
	On:
		 60.0 minutes have elapsed
		 AND
		 Global scenario variable 6 is set
	Actions:
		 Reinforce with team "sea3"
	Disable: After running once
Trigger@sea3:
	On:
		 95.0 minutes have elapsed
		 AND
		 Global scenario variable 5 is set
	Actions:
		 Reinforce with team "sea2"
	Disable: After running once
TeamType@hunt1:
	Units: 2TNK, 2TNK, 2TNK, ARTY, ARTY, MGG
TeamType@sea1:
	Units: CA
TeamType@mcv1:
	Units: MCV
TeamType@sea2:
	Units: DD, DD, CA
TeamType@hunt2:
	Units: 2TNK, 2TNK, 2TNK, 2TNK, ARTY, ARTY
TeamType@air1:
	Units: HELI, HELI, HELI, HELI
TeamType@auto1:
	Units: 2TNK, 2TNK, 1TNK
TeamType@auto2:
	Units: E3, E3, E3, ARTY, ARTY
TeamType@auto3:
	Units: 1TNK, JEEP, JEEP
TeamType@auto4:
	Units: E1, E1, E6, E6, E6, APC
TeamType@mlay1:
	Units: MNLY
TeamType@lst1:
	Units: 2TNK, ARTY, ARTY, LST
TeamType@lst2:
	Units: 1TNK, 1TNK, 1TNK, LST
TeamType@lst3:
	Units: ARTY, ARTY, ARTY, LST
TeamType@lst4:
	Units: 2TNK, ARTY, ARTY, LST
TeamType@lst5:
	Units: JEEP, JEEP, JEEP, LST
TeamType@lst6:
	Units: 2TNK, 1TNK, 1TNK, LST
TeamType@hel1:
	Units: E3, E3, E3, E3, E3, TRAN
TeamType@hel2:
	Units: HELI, HELI, HELI, HELI
TeamType@lst7:
	Units: E3, E3, E3, E3, E3, LST
TeamType@auto5:
	Units: 2TNK, 2TNK, ARTY
TeamType@auto6:
	Units: 2TNK, 2TNK, 2TNK
TeamType@auto7:
	Units: 2TNK, 2TNK, 1TNK, 1TNK, 1TNK, ARTY, ARTY
TeamType@sea3:
	Units: CA
ScriptedBuildingProduction: house "Greece"
	GUN at cell 63,78
	GUN at cell 59,74
	GUN at cell 46,69
	GUN at cell 50,69
```
</summary>

**Comment by abcdefg30** [comment]
This probably also wants the adjustment of delaying the "Mission Accomplished" speech.

**Comment by Smittytron** [comment]
Extended Mission Accomplished delay.

**Comment by Smittytron** [comment]
Updated for #19738

**Comment by Orb370** [comment]
[13b Lua bug.zip](https://github.com/OpenRA/OpenRA/files/9099195/13b.Lua.bug.zip)

2022-07-13 01_33_38-OpenRA - Red Alert

Happened at the end when I captured the Chronosphere, hard difficulty.

Still found it easy on hard compared to other missions (like in 13a https://github.com/OpenRA/OpenRA/pull/19363#issuecomment-956508445). I think the start could be harder (rest of mission difficulty is probably fine, considering there's no mines and all).

**Comment by Smittytron** [comment]
Fixed the typo responsible for the crash.

The only other comment about difficulty said it was "impossible", so I'm hoping to wait until post-release feedback to see if there's much clamor for a change.

**Comment by PunkPun** [comment]
Needs to be rebased and translations added #20387

**Comment by PunkPun** [comment]
needs a rebase

**Comment by Smittytron** [comment]
Rebased and updated.

**Review by PunkPun — COMMENTED** [review]
Crash [lua.log](https://github.com/OpenRA/OpenRA/files/12195465/lua.log)

> 128: attempt to index global 'CruiserStop' (a nil value)

**Comment by Smittytron** [comment]
Updated

**Review by PunkPun — DISMISSED** [review]
Played through Easy, Normal and Hard and additionally observed the AI on fastest / vision hacks

LGTM

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/49e6f9a80f54203129758313e8c93110fd945f62...159e14c7c8e68a33448fe57903fdfad9c6db25e2)

**Comment by PunkPun** [comment]
Moved to prep https://github.com/OpenRA/OpenRA/commit/0ac9d96ab822acdc747340a668d20f12e461bd1e

[New changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ab652211b40c4a890a63c0f04952d7cb183c30ba...cf5b17f75fe11447d3b3784b38a1c89b03c8cff9)

**Pull request merged**
