### PR TITLE
Add DeathTypes to OwnerLostAction.

### LINKED ISSUE #12802: Infantry disappear when a player is defeated/surrenders/leaves game.
This is a bug for TS, where it played Die1 instead. These cases should have an option to apply the killing via using damagetypes.

### PR DESCRIPTION
**Pull request by GraionDilach**
Something I overlooked back at reviewing #14982. Would be cool if it would hit the playtest, because it is a good polish. I've enabled the first deathtype in all mods because that was the case in RA and TS (notsure what D2K used originally.)

Fixes #12802.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Buildings don't lack OLA, they just don't need a deathtype on their OLA - in all the default mods, the building explosions aren't linked to such, but appear unconditionally.

**Comment by pchote** [comment]
Moving to the Future milestone so we don't lose this.

@MustaphaTR do you want to take this one over so we can prioritize it for the playtest?

**Comment by pchote** [comment]
Actually this already has a :+1: so i'll add it to my review list, then we can merge it as-is if there aren't any issues.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e1e201dee3e04f9412027b724d59d663a928ba51

**Pull request merged**
