### PR TITLE
Enables Explored Map by default in lobby settings.

### PR DESCRIPTION
**Pull request by deniz1a**
This can be done now since #6123 is fixed.

### CODE REVIEW

**Comment by penev92** [comment]
Why exactly would we want this?

**Comment by deniz1a** [comment]
Because explored map is better.

**Comment by MicroJOo** [comment]
nope :-1:

**Comment by jaZzKCS** [comment]
Why would we want to change defaults?
This is just your personal preference.
In almost every RTS, shroud is an essential game element and always present.

Shroud should always be enabled by default to guarantee a certain game experience, and should only be disabled if there is a significant portion of players on the server that does NOT know the map, to make it more fair.

But in general, having shroud enabled is and will always be the standard.

**Comment by obrakmann** [comment]
:-1: I agree with all the previous comments. This is already configurable, no need to change the default.

**Comment by abcdefg30** [comment]
I don't think we're getting anywhere here.

**Pull request closed without merging**
