### PR TITLE
Add casing throwing for Armament

### PR DESCRIPTION
**Pull request by dnqbob**
Add a casing throwing for Armament. Use a weapon for the casing.
casing-showcase

### CODE REVIEW

**Comment by dnqbob** [comment]
Test case is just used as showcase, we need to ask @ABrandau if we want to use the casing art.

**Comment by PunkPun** [comment]
Couldn't this be better implemented as a new class? Something like ArmamentWithCasings : Armament

**Comment by dnqbob** [comment]
> Couldn't this be better implemented as a new class? Something like ArmamentWithCasings : Armament

Due to the change to `barrel`, I don't think make it a new class is a better idea.

**Comment by PunkPun** [comment]
Hmm, in that case it's almost possible to move it outside.
I still think we should try to explore that solution, it seems like a waste to have such a feature on every armament when most wouldn't take advantage of it

**Comment by PunkPun** [comment]
Better to make armament more modular and less monolithic

**Comment by dnqbob** [comment]
I do have another solution, though.

https://gitee.com/CastleJing/TiberianAurora/blob/bleed/OpenRA.Mods.TA/Traits/Combat/FireWeaponToOffsetWhenAttack.cs

To put it simple: Add `OffsetIndex` to `barrel` as an reference value, use another trait to throw casing according to the `OffsetIndex`.

I suppose `OffsetIndex` is a little hardcoded and less perf if the casing throwing not in `Armament`, while Milk think the way in my PR makes `Armament` bloat.

**Comment by dnqbob** [comment]
> Better to make armament more modular and less monolithic

Then we need a not small refactoring. It is better to move all after-fire effect (including muzzle) into other trait.

**Pull request closed without merging**
