### PR TITLE
 Add "Spawn Child Actor" and "Deployed" checkboxes to the map editor.

### PR DESCRIPTION
**Pull request by pchote**
This makes it easy for map authors to disable the free harvester spawning from refineries.

### CODE REVIEW

**Comment by pchote** [comment]
Updated to add a "Deployed" checkbox for `GrantConditionOnDeployed`.

**Comment by pchote** [comment]
Marking as Next + 1 so this can go together with #16772 and #16900 as an editor improvements theme.

**Comment by pchote** [comment]
Sorry for the spam - accidentally deleted the branch while cleaning up my repository... twice.

**Comment by teinarss** [comment]
Just a thought it would be nice if Deployed actors would shown their deployed state in the viewport.

**Comment by pchote** [comment]
That is #15494, which is going to be a huge task.

**Review by teinarss — DISMISSED** [review]

**Comment by reaperrr** [comment]
Two issues I noticed:
- The 'Deployed' checkbox doesn't seem to work on the TS Tick Tank.
- Changing the value of the checkboxes does not enable the OK button.

**Comment by pchote** [comment]
Updated.

> Changing the value of the checkboxes does not enable the OK button.

This was caused by a conflict / rebase issue against #16772. Rebased and fixed.

> The 'Deployed' checkbox doesn't seem to work on the TS Tick Tank.

This is #17184, which isn't related to this PR.

**Comment by pchote** [comment]
Rebased.

**Review by abcdefg30 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/719bed8c0ca7bc150da6bd2b364d8f380499107c...6821da23aeb74e9c7fc2c5dc60bc6656eb9c59c1)

**Pull request merged**
