### PR TITLE
Split TD weapons.yaml into multiple categorised yamls

### PR DESCRIPTION
**Pull request by reaperrr**
Only CnC mod for now.
This is far from finished, I'd like to get some feedback and ideas before I continue working on this (and especially before I apply this yaml/folder structure to other mods).

### CODE REVIEW

**Comment by penev92** [comment]
Note1: `mod.yaml` files should be purged of unnecessary `Assemblies` when the migration to Mods.Common is done.
Note2: For some mods `voices.yaml` and `notifications.yaml` might need refactoring.

Now, for this PR:
Commit 1 gets a +1. Verified that nothing is added, nothing is missing and nothing is changed during the separation.
Commit 2 gets a +1.
Commit 3 should have been split to at least two commits :|
I also didn't see anything break in-game, so :+1:

**Comment by pchote** [comment]
:+1: to the first commit, although you'll need to be careful when rebasing.  I think we should aim to get that non-controversial change in asap, but the other changes will need a bit more discussion and iteration.

**Comment by reaperrr** [comment]
Updated & rebased. I've removed commits 2 + 3 from this PR, they'll return in follow-up PR(s).

**Comment by penev92** [comment]
So how many +1s are we counting now for this?
Mine still stands.

**Comment by obrakmann** [comment]
:+1: from me for good measure :)

**Pull request merged**
