### PR TITLE
Rename the Experience coloumn to Score in observer stats.

### PR DESCRIPTION
**Pull request by GraionDilach**
Semi-followup of #11627 for consistency.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
`EXPERIENCE_HEADER` should be changed, too.

**Comment by GraionDilach** [comment]
Internally it's called as Experience, so I don't see why.

**Comment by obrakmann** [comment]
probably better, consistency-wise. :+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a2dddac96b9992ccf7ea27289f127bfaa9c433d4...1b3810241aaadde7ba7480477b3aa6b767f13411)

**Pull request merged**
