### PR TITLE
Add Aftermath mission Shock Therapy

### PR DESCRIPTION
**Pull request by Smittytron**
Another Aftermath mission that was made for the sole purpose of showing off new units. This mission is pretty much a civilian massacre in the style of Soviet01. The original was absurdly easy even on 'hard', so I have gone with one difficulty mode here.

### CODE REVIEW

**Comment by Mailaender** [comment]
Looks like this needs some kind of AI money spend routine to avoid:

image

**Comment by Mailaender** [comment]
Capturing the 🏥 seems to have no effect? At least I saw no icons on the infantry.

**Review by Mailaender — DISMISSED** [review]
Mission script works as promised.

**Comment by Smittytron** [comment]
Updated.
The hospital works, it's just hard to see the cross without zooming in. The infantry production does spend money but it was no where near fast enough to keep up with two ore trucks. I went ahead and removed one.

**Comment by pchote** [comment]
Should we pick this to prep too?

**Comment by Smittytron** [comment]
Updated date

**Comment by KautionORA** [comment]
Looks good, Tested it out and you cant just brainless A move and win the mission, reducing the harvester to 1 did help, at min 10 the silos were like half full.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
> Should we pick this to prep too?

In my opinion yes.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/60404902bc81081073ca3bb144936260818fb701...d7724edff4ecdf6fbe9802f77d99217c34dcb41c

prep: 53fe004

**Pull request merged**
