### PR TITLE
Polish ProximityCapturable.

### PR DESCRIPTION
**Pull request by GraionDilach**
Added descriptions and an Influenced field for gamemodes where the capturing actors only would initiate the capturing process.

Practically everything which was agreed on the IRC yesterday. I didn't removed the inline comments though - should that also happen?

### CODE REVIEW

**Comment by pchote** [comment]
It's out of scope for this PR, but the capture range checks should also be rewritten using proximity triggers (`ActorMap.AddProximityTrigger`, `ActorMap.RemoveProximityTrigger`) instead of DIYing its own queries each tick.

**Comment by GraionDilach** [comment]
Asking for the Has Dependencies label. I'll do that.

The trait has instant capture right now. >_>

**Comment by obrakmann** [comment]
This hasn't seen any activity in a while so I took a shot at it, since I'll need this for my mod: https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:koth-refactor

@GraionDilach: let me know how we want to go from here.

**Comment by GraionDilach** [comment]
I have a complete rewrire in mind tbh, but I couldn't find time to implement it before Wednesday... I have no idea what to do now.

**Comment by obrakmann** [comment]
OK. I suggest you check out my branch then and see how closely it matches what you were going to do, and we'll either go with it if you don't need any more changes, or you can use it as a base.

**Comment by RoosterDragon** [comment]
Do we maybe want to drop the addition of `Influenced` and just take the extra descriptions? Seems silly to delay this for a rewrite that may or may not happen any time soon.

**Comment by GraionDilach** [comment]
Then please take @obrakmann 's polish.

**Pull request closed without merging**
