### PR TITLE
 Add more variations to building explosions in ra

### PR DESCRIPTION
**Pull request by abcdefg30**
Followup of #8911.

### CODE REVIEW

**Comment by obrakmann** [comment]
I like the more varied explosions, but it needs some tweaking. For example, the kennel blowing up with the large napalm explosion looks a bit simpson-esque ;) I'd add that only to larger three-cell-footprint buildings.

**Comment by GraionDilach** [comment]
I think napalm2 should have a flipped variant for this to make less subtle of being a downsized napalm3.

**Comment by abcdefg30** [comment]
> I like the more varied explosions, but it needs some tweaking. For example, the kennel blowing up with the large napalm explosion looks a bit simpson-esque ;) I'd add that only to larger three-cell-footprint buildings.

Ops, forgot about that.
Removed `large_napalm` from 1x1 buildings.

**Comment by abcdefg30** [comment]
> I think napalm2 should have a flipped variant for this to make less subtle of being a downsized napalm3.

Flipped `napalm2` in an extra commit.

**Comment by GraionDilach** [comment]
I meant flip it exclusively for building explosions, say `napalm_building_explosion: napalm2`. >_>

**Comment by abcdefg30** [comment]
Updated. I hope I got it this time. ^^

**Comment by Mailaender** [comment]
:+1: Good idea. Looking fine.

**Comment by UberWaffe** [comment]
:+1: Did a playtest between AIs in RedAlert.
Looks good to me.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4bd64db81c04649e74fbaf78415937c10fed346b...333551fe4037c33874ddc253a0d5c4bd64d4e387)

**Pull request merged**
