### PR TITLE
Revert "Remove FrameData and update OrderManager"

### LINKED ISSUE #19415: Attempted to process orders from client X for frame 1 on frame X
```
OpenRA engine version 98caae106faa6f3ea73c448324ae450c54a7f1fe
OpenHV mod version 20210516
on map 7e57b2ac7bd6332a058bfbcf6b5129da2bf3541f (Beyond Destruction by Dzierzan).
Date: 2021-05-16 18:54:51Z
Operating System: Linux (Unix 5.3.18.152)
Runtime Version: .NET CLR 5.0.6
Exception of type `System.IO.InvalidDataException`: Attempted to process orders from client 2 for frame 1 on frame 4
   at OpenRA.Network.OrderManager.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 215
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 640
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 655
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 822
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 875
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 276
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

```
OpenRA engine version 98caae106faa6f3ea73c448324ae450c54a7f1fe
OpenHV mod version 20210516
on map bc4432b69c5eaad95069b94b11d24c2fdc6fc7aa (Doubles by Dzierzan).
Date: 2021-05-16 19:12:04Z
Operating System: Windows (Microsoft Windows NT 10.0.19042.0)
Runtime Version: .NET CLR 5.0.6
Exception of type `System.IO.InvalidDataException`: Attempted to process orders from client 9 for frame 1 on frame 4
   at OpenRA.Network.OrderManager.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 215
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 640
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 655
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 822
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 875
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 276
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.WindowsLauncher/Program.cs:line 71
```

### PR DESCRIPTION
**Pull request by Mailaender**
Reverts https://github.com/OpenRA/OpenRA/pull/19402 
Fixes https://github.com/OpenRA/OpenRA/issues/19415

### CODE REVIEW

**Comment by pchote** [comment]
I can't reproduce #19415 in RA or TS, so more research is needed to understand the actual problem before we think about reverting this.

**Comment by teinarss** [comment]
> 
> 
> I can't reproduce #19415 in RA or TS, so more research is needed to understand the actual problem before we think about reverting this.

I did some testing with RA and D2K, started 7 MP games in each without this happening. Without any repro case this will be hard to fix, and just reverting the changes is a bad approach IMO.

**Comment by Mailaender** [comment]
Yes, this was just damage control. https://github.com/OpenHV/OpenHV/releases/tag/20210517 is based on this commit.

**Comment by pchote** [comment]
Superseded by #19422.

**Pull request closed without merging**
