### PR TITLE
Change nukes to be able to damage submerged submarines

### LINKED ISSUE #10812: subs "underwater" do not take damage from nukes
on a direct hit 

thats is just wrong , for the nuke there should be a exception on this sub-rule imo

### PR DESCRIPTION
**Pull request by obrakmann**
Closes #10812.

### CODE REVIEW

**Comment by pchote** [comment]
Looks fine to me :+1:

**Comment by abcdefg30** [comment]
Works as advertised. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/51fb5a54d41f062f1d92a1f6f880a791a00e7a30...f1d35b66c8e994fd5642bd9577d8a034f594d4fc)

**Comment by Micr0Bit** [comment]
thank you , @obrakmann

**Pull request merged**
