### PR TITLE
Adjust difficulty, add speeches to allies-06a

### LINKED ISSUE #20045: Allied mission 06a: cripple Iron Curtain impossible on hard level
On hard level, speed normal, this mission is practically impossible to finish. Or, better... you can't even start it!

Have someone tested it? You cannot estabilish a base, you cannot survive enough to do nothing! Let me know if you have had the same experience...

### PR DESCRIPTION
**Pull request by JovialFeline**
These are some tweaks intended to smooth out this mission's Hard difficulty (without committing to bigger changes), fix some oddities, and add some polish.

If and when this is considered golden, it _should_ be simple to give B a similar treatment.

Fixes https://github.com/OpenRA/OpenRA/issues/20045

----

### LSTs

On bleed, the mission starts with a repeating timer for Soviet LSTs that unload one of two random teams. These are the teams on Hard:
  - x3 Heavy Tank, x2 V2 Rocket Launcher
  - X1 Heavy Tank, x2 V2 Rocket Launcher, x2 Flamethrower

One of these every minute seems harsh. The interval for LST teams on Hard is now 140s (from 60s; Normal is 180s).
  - Besides the obvious effect, this lets the smaller Soviet base use their tanks in attacks beforehand. On bleed, one of those attacks can coincide with the first LST team for extra pain.

<details><summary>The original timeline for LSTs is less straightforward if you are REALLY interested.</summary>

**Greece approaches the western Soviet base (`OP1-`/`OP1X` trigger):**

Reinforce the `lst1` team.
  - 4 Rifle Infantry are carried from Waypoint 22 to 43 (at the beach southeast of this base). They simply hunt.

----

**Greece touches the `LST3` zone at the northeastern gem island:**

Reinforce the `lst2` team:
  - 3 Heavy Tanks are carried from Waypoint 22 to 43.
  - They attack defenses, vehicles, and any other targets.

----

**Greece kills/captures the Barracks or nearby Radar Dome:**

`LST4`: After ~03:06, reinforce the `lst4` team.
  - 1 Heavy Tank, 3 Grenadiers are carried from Waypoint 22 to 43.
  - They attack vehicles, defenses, and power plants before hunting.

`LST5`: After ~07:33, reinforce the `lst5` team.
  - 1 V2 Rocket Launcher, 4 Flamethrowers are carried from Waypoint22 to 68 (by the beach in the southwest corner).
  - They will attack harvesters, defenses, & factories before a hunt.

----

**Greece kills one of USSR's starting Submarines:**

A Submarine will investigate when Greece builds a Naval Yard, and the teams below will be scheduled after its death. (`SEA7`, `SEA3`) If USSR later loses their Sub Pen, the teams can be skipped. (`SEA6`)

`SEA4`: After ~01:36, reinforce the `sea1` team.
  - 2 Heavy Tanks and 1 V2 Rocket Launcher are carried from Waypoint 34 to 43.
  - They attack vehicles, defenses, and structures.

`LST2`: After ~05:24, reinforce the `lst3` team.
  - 1 Heavy Tank, 2 V2 Rocket Launchers, and 2 Flamethrowers are carried from Waypoint 22 to 68.
  - They attack defenses or structures before hunting.

`LST1`: After ~09:12, reinforce the `lst2` team.
 - 3 Heavy Tanks are carried from Waypoint 22 to 43.
 - They attack defenses, vehicles, and any other targets.

`LST7`: After ~18:36, reinforce the `lst4` and `lst5` teams.
 - `lst4`: 1 Heavy Tank, 3 Grenadiers are carried from Waypoint 22 to 43.
   - They attack vehicles, defenses, and power plants before hunting.

 - `lst5`: 1 V2 Rocket Launcher and 4 Flamethrowers are carried from Waypoint 22 to 68.
   - They attack harvesters, defenses, and factories before hunting.

`LST8`: After ~25:00, reinforce the `lst5` team again.
</details>

----

### Yaks

Limited USSR production to one Yak for their one Airfield. (That part of the script seemed to be from `allies-04` where two are expected.)

Changed Yak production so the first has different delays for each difficulty. On Hard, this is 90s (from 70s). On Normal, this is 120s (from 70s) so production roughly matches the RA '96 timer (reinforcement at ~150s).

<details><summary>Like the LST one, the original aircraft timeline is a rabbit hole.</summary>

**Greece acquires a Construction Yard:**

Trigger `AIR9`: Every 50 moments, reinforce team `air2`.
  - 1 Yak targets power plants, structures, vehicles, and infantry.

`AIR4`: The `air2` team has died.
  - Set global {8} and prompt `AIR7`.

`AIR7`: Every 40 moments while global {8} is set, reinforce team `air3`.
  - 2 Yaks target power plants, structures, vehicles, and infantry.
  - Remove the previous `AIR9` trigger.
  - These planes start near the northwest corner at waypoint 52. This is the only team with a particular spawn point, and the last air team reinforced until the eastern base is attacked.

`AIR5`: The `air3` team has died.
  - Clear global {8} and call `DES1` ( -> `DES2` -> `DES3`).
    - Remove the previous `AIR9`, `AIR4`, and `AIR7` triggers.

----

**Greece kills a USSR starting submarine:**

`LST6`: After 265 moments, reinforce team `air5`.
  - A Badger drops 3 Rifle Infantry and 2 Flamethrowers at Waypoint 73.

`LST8`: After 500 moments, reinforce team `air6`.
  - A Badger drops 2 Rifle Infantry and 3 Grenadiers at Waypoint 72.

----

**Greece attacks certain units/structures at the eastern base:**

`REAC`: Set global {4}. The rest of the events below can be skipped if the Airfield is destroyed (`AIR2`).

`AIR1`: Every 40 moments while global {4} is set, reinforce team `air1`.
  - 3 Yak planes target factories, structures, vehicles, and infantry.

`AIR8`: The `air1` team has died.
  - Set global {11} and prompt `AIR0`.
  - Clear the previous `AIR1` trigger.

`AIR0`: Every 52 moments while global {11} is set, reinforce team `air4`.
  - 2 Yak planes target vehicles and infantry.

`AI10`: The `air4` team has died.
  - Clear global {11} and call `DES4`.

`AIR2`/`AI10`/`DES4`: Clear globals {4} and {11}, along with the `AIR1` trigger.
</details>

----

### Navy Stuff

Changed the Soviet navy production so a Submarine cluster is less likely to force Greece out of the water and maintain that with more production.
  - Per the original, Submarines won't start production until a starting Submarine is killed. One of the starters will scout the coast near the Soviet Barracks after a Naval Yard is built.
  - Production is delayed whenever Greece is later found to lack any Naval Yard.

Added an objective for building a Naval Yard, with text that mentions redeployable MCVs. That knowledge has unusual importance for this map, where the build area in common start locations may not reach the water.
  - I'm [partly going off remarks](https://forum.openra.net/viewtopic.php?f=82&t=21566) from **rossboylan** and **Carrillo**.
  - The infiltration objective's appearance is normally delayed until this one is completed.

----

Added a 30s grace period before Soviet infantry production, reinforcement timers, and so on are started. This grace period ends when Greece deploys (or loses) their MCV, but it should help with early pressure.
  - There is a 10s delay to these events on bleed, though this is about the time it takes for the MCV to reinforce and move to its rally point (8.2s).
  - This is closer to original behavior anyway, where USSR starts creating infantry teams at ~30s or once Greece has "built" a Construction Yard (which itself triggers more things).

Changed Greece's starting cash to its original 8500 (from 5000).

Changed Greece's death check so they can be defeated if they're somehow wiped out after the spy objective is done.

Added an alert bleep to the tech capture message.

Added "objective met" notifications, with some delays so speech should not overlap.

Added back the Soviet bases' wire fencing. (See https://github.com/OpenRA/OpenRA/pull/21373)

Added another Soviet infantry team based on `inf2`: 2 Grenadiers, 1 Rifle Infantry.

Changed dog patrols to stop waiting on dead team members.

Changed Soviet paratrooopers to hunt when idle.

Fixed some infantry subcells. (See https://github.com/OpenRA/OpenRA/pull/21397)

### CODE REVIEW

**Review by RoosterDragon — APPROVED** [review]
Played through on Normal - the early pressure required constant attention but was mangeable. Based on your description, the changes for Hard now seem like a step up, rather than overwhelming. A 3x step up in the enemy reinforcements would've been very rough.

The Yak and naval pressure seems good - allowed pressure to apply without becoming too much spam.

Fences all look good.

One odditiy I noticed, after capturing the shore radar dome and getting an objective success, it was later destroyed and then marked as a fail. Since you've got what you need out of it, maybe it shouldn't matter at that point.

**Comment by JovialFeline** [comment]
> One odditiy I noticed, after capturing the shore radar dome and getting an objective success, it was later destroyed and then marked as a fail. Since you've got what you need out of it, maybe it shouldn't matter at that point.

That change seems fine to me, and there are other missions that do a similar thing like Production Disruption or `soviet-05`. I've added a check and rebased.

**Review by PunkPun — APPROVED** [review]
Merging in trust that any regressions will be quickly fixed

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3f84b659819614548cfa3e6cb999f01e183bab20...6084f31d2bb8c8b75208d984f318366b4656bab2)

**Pull request merged**
