### PR TITLE
Enable the restart button for missions with script errors

### LINKED ISSUE #14104: Restart button for multiplayer replays
Right now (playtest-20170930) the restart button during a replay is only available for single player replays. I dug in the code a bit and found that there is a condition:
https://github.com/OpenRA/OpenRA/blob/78bedb0513d0444963f9bf9a59f849b1b0c81974/OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs#L100

That makes sense for live games but not in the context of replays.

Often times I find myself wanting to restart a replay (cause I missed something or just to see the match from a different perspective). And with the current setup I'd have to go through all the motions of the menu and finding the replay.

I can see a couple of tickets about desyncs when restarting replays (#12523 and #13312). Is there a reason for not enabling it for multiplayer replays?

### LINKED ISSUE #17540: Wish: restart button on mission lua.error
When testing lua scripts ingame, the "Restart" button comes in handy but it got disabled during the latest UI changes.

I would prefer to have it available after an lua error, again.

Often the error is due to a minor typo in the script (alt+tabbing and changing it). The restart button is missed

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #17540.
~~Edit: #14104 is still open.~~

~~I didn't encounter a desync when restarting a multiplayer replay, but I also don't know the reproduction case of https://github.com/OpenRA/OpenRA/issues/15423#issuecomment-412343652.~~

### CODE REVIEW

**Comment by pchote** [comment]
The script error commit LGTM.

> I didn't encounter a desync when restarting a multiplayer replay,

Rebase this onto playtest-20201213 and download the replay from #18923 or #18925. These reliably desync on restart for me.

**Comment by abcdefg30** [comment]
This might be the same problem with no client id 0 existing.

**Comment by pchote** [comment]
#18902 was included in playtest-20201213, and should have fixed that.

Since we don't have an obvious way forward here i'll close this to help clean up the PR queue. We can reopen this if anyone has any ideas on how to reproduce or debug the desyncs.

**Comment by abcdefg30** [comment]
Dropped the offending commit.

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f84403329470a62c05dfac2cfcd90836827d7f6e...80b1b18aafabfa31879f0d3e53772b21f5f50963)

**Pull request merged**
