### PR TITLE
Fix filename case on weapon reports.

### PR DESCRIPTION
**Pull request by pchote**
Fixes the RA and TD mods in preparation for #10535.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Could we get an upgrade rule for maps?

**Comment by pchote** [comment]
I don't think we can, unless you want to risk the rule breaking other things.  For example, D2K's sounds are legitimately upper case.

**Comment by GraionDilach** [comment]
TS isn't fixed though, on the other hand, even unit voices are capitalized in TS.

**Comment by pchote** [comment]
@GraionDilach: could you list all the case inconsistencies you know of in #10535?  This one is reasonably self-contained, so I'll do another pr for the remaining cleanups.

**Comment by GraionDilach** [comment]
Oh, I overlooked for some reason I haven't seen the TS fixes in this.

**Comment by pchote** [comment]
Added a commit for TS voices, since that is easy enough to test while testing the weapon reports in TS.

**Comment by Mailaender** [comment]
I can still hear the sounds. :white_check_mark: It would be nice to get a pull request for https://github.com/OpenRA/ra2/ or at least get the command you used for this conversion.

**Comment by pchote** [comment]
I used the global find and replace in textmate with a search string of `Report: (\w+)` and a replacement string of `Report: \L$1.aud`.

**Comment by abcdefg30** [comment]
Sounds still work ingame. :white_check_mark:

**Pull request merged**
