### PR TITLE
Fix CanBeViewedByPlayer query in HackyAI.GetVisibleActorsBelongingToPlayer

### PR DESCRIPTION
**Pull request by phrohdoh**
I was checking the wrong player's visibility status.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Well, ingame it wasn't that noticable. :+1:

**Comment by Phrohdoh** [comment]
Err, this needs to be fixed more, sorry for the cruddy code.
`CapturableActorTypes` lies about the way it behaves.
If it is empty no orders are given (which is not what the second line of the desc says).

**Comment by Phrohdoh** [comment]
It turns out I lied.
I must have changed that code on another branch and not realized it.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ee00b74067991f061bf891b09d797d02a5c0923e)

**Pull request merged**
