### PR TITLE
Fixed empty pixels on flak truck art

### PR DESCRIPTION
**Pull request by reaperrr**
old:
ftrk-old

new:
ftrk-new

### CODE REVIEW

**Comment by obrakmann** [comment]
Fixes #7892

**Comment by obrakmann** [comment]
Looks good to me :+1:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2099adadbef413d64af8044fbaffee66d3727e1d%5E...2099adadbef413d64af8044fbaffee66d3727e1d)

**Pull request merged**
