### PR TITLE
Remove ESC hotkey from lobby 'Back' button

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Why?

**Comment by obrakmann** [comment]
https://github.com/OpenRA/OpenRA/pull/8680#discussion-diff-35460324

**Comment by penev92** [comment]
Well as far as I know the Esc key has never actually worked in the lobby until today, so I guess no harm done.
:+1:

**Comment by pchote** [comment]
Works as advertised :+1:.  Skipping the changelog entry because this is effectively fixing a regression from #8680.

**Pull request merged**
