### PR TITLE
Some D2k polishing

### LINKED ISSUE #9516: D2k grenadier idle animation looks wrong
The white line above his head is the weapon offset, shown by the combat debug overlay (the offset is wrong, but ignore that for the moment).
The issue is that he is facing one way, while the animation seems to be facing the other.

  

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27137461-d2k-grenadier-idle-animation-looks-wrong?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10137: D2k missile visual polish
Release 20150919 and earlier had the Missile Tank's and Rocket Turret's missiles do a nice arc, which looked pretty nice.
The big D2k overhaul changed the projectile type from `Bullet` to `Missile`, making them fly in a straight line. While they also fly in a straight (kinda) line in the original, the actor artwork suggests they would be fired upwards, and I personally think it looks better with the arc.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28676622-d2k-missile-visual-polish?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
Fixed d2k grenadier stand sequence facings (other sequences are not affected), gave larger missiles a ballistic flight curve and changed `yes` to `true` on all boolean properties for consistency.

Fixes #9516.
Closes #10137.

### CODE REVIEW

**Comment by reaperrr** [comment]
As for the grenadier, #9516 shows how it looked before, this is how it looks now:
gren-fixed

**Comment by Mailaender** [comment]
Thanks! :white_check_mark:

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/4eab3dd1146fc92735b763f11813c5b1223ded79...e81aac6a30f68b17360e907117b9556da63c1950)

**Pull request merged**
