### PR TITLE
Fix RA civilian artwork

### LINKED ISSUE #13187: Technicians looking all the same
I dont know if this is wanted but is looking a bit curious now.
This is a result of https://github.com/OpenRA/OpenRA/pull/12174

### PR DESCRIPTION
**Pull request by pchote**
Fixes #13187 referencing [RA Classic](https://github.com/OpenRA/raclassic/blob/master/mods/raclassic/rules/civilian.yaml) and [Chronoshift](https://github.com/TheAssemblyArmada/Chronoshift/blob/5ddaf47792266141fa2cfc293bce6e81336cdc20/src/game/engine/infantrydata.cpp#L394-L544) for the correct definitions.

A new `c11` civilian has been added to use the custom c3 sprite.

### CODE REVIEW

**Review by MustaphaTR — DISMISSED** [review]
C7 should be able to come out of sold buildings. Looks good to me otherwise.

**Comment by pchote** [comment]
Added the yellow shirted technician, now defined as a new `tecn2` actor type to match the `c1` vs `tecn` split that happened years ago.

I'm wondering whether we should split these properly, removing the weapons (which afaik only exist for the player-controlled spawning case?) from `c1` and `c7`, and removing the panicking from `tecn` and `techn2`.

**Comment by Smittytron** [comment]
Civs besides c11 all have c1 or c3 death animations. Also missing female deathrattle.

**Comment by pchote** [comment]
Fixed the death animations. There aren't any specific female death sounds, so we can either stick with male (matching original game) or switch to tanya (confusing/misleading ingame?)

**Review by Smittytron — DISMISSED** [review]
^ I'd stick with the original. Tanya voice would be too jarring.

**Comment by pchote** [comment]
Rebased.

**Comment by pchote** [comment]
Rebased again.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b09344e104c18695e927e589e24fe63f60ae8557...625ffcf56d031a89fd7124dfa6a5ca692563cbaa

**Pull request merged**
