### PR TITLE
Ensure that TLS 1.2 is enabled for web downloads.

### LINKED ISSUE #15518: GitHub links give SSL error on ingame Content Manager on Windows
I was trying to add Music installer to Generals Alpha and noticed GitHub links don't work. Seems like similar problem with #14855.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #15518 (hopefully) and prerequisite for fixing https://github.com/OpenRA/OpenRAWeb/issues/372.

### CODE REVIEW

**Comment by reaperrr** [comment]
@MustaphaTR does this fix it for you?

**Review by MustaphaTR — APPROVED** [review]
I applied the changes on my engine locally and it downloaded the music properly. 👍

**Review by reaperrr — APPROVED** [review]
Code looks good to me and no regression downloading the cnc quickinstall package

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0c0a83c20c8bd9547024ff81b55abbc226b7291f...331854fdf9625409970c9b3e813ed547a7e5fb69

fbb3172

**Pull request merged**
