### PR TITLE
Normalize RA/TD track volumes

### LINKED ISSUE #14231: Music tracks have different volumes
Hello,

the music of the tiberian dawn variant of this game has large differences in volume of the background music. Especially the ones that weren't included in the original C&C game.

For example, the track "Act of Instinct" is there in two variants. One of them is much louder that the other.

One or two in the list are extremely loud and bassy so the music tends to be louder than the sound FX.

This is a bit annoying because I need to adjust the music volume in the game settings every few tracks^^.

Please normalize them or use ReplayGain or something like this so the volume is equal for each track. :-)

The original C&C game hasn't this issue.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #14231 for TD and RA, roughly based on @dan9550's ReplayGain values.

I also went through the D2k and TS tracks by ear, but in my opinion there aren't any outliers in them that justify touching these.

Also manually tested the tracks mentioned in #16140.
The 3 sfx tracks have nearly identical volume to their non-sfx counterparts.
Outtakes has a similar volume, too.

Furthermore, some TD tracks from the original were falsely listed under CovOps.
Only tracks with 226m in their filename are cov ops tracks.

### CODE REVIEW

**Review by pchote — APPROVED** [review]
SGTM

**Review by obrakmann — APPROVED** [review]

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ee32e3efd9b6147c9f502d8b6851db20337c25bc)

[Prep commit](https://github.com/OpenRA/OpenRA/commit/b18110012b6d9cf56e44e8a5bafbdfa6e95e52fd)

**Comment by reaperrr** [comment]
> Ahh beat me to the rest 😮

Sorry, I wasn't sure if you were working on a PR.
Feel free to file a follow-up if you have some suggestions for polish/fine-tuning the values.

**Comment by dan9550** [comment]
No worries this is the kind of change that's going to be subjective really. As long as everyone happy with the values we shouldn't have to get too serious with it.

I might take a look at doing the TS, and D2K music at some point if I have the time, as you said we can always fine tune.

**Pull request merged**
