### PR TITLE
Changes faction name from England to Britain so that it matches the flag

### PR DESCRIPTION
**Pull request by deniz1a**
Second attempt at fixing #8024. Changing flag to match name was rejected so I changed name to match flag. I changed all occurances of "england" I could find except for the one here: https://github.com/OpenRA/OpenRA/blob/89a1bdd4f15d7a960a9ece1e89181b440a839705/OpenRA.Mods.Common/UtilityCommands/LegacyMapImporter.cs#L460

I didn't know if that would need to be changed.

### CODE REVIEW

**Comment by deniz1a** [comment]
Also github search doesn't show all the results... There are many more instances than were shown in github search results.

**Comment by pchote** [comment]
Please keep the internal names as england.  Changing this to britain breaks our legacy map importer, and unless you want to write an upgrade rule it will also break any custom maps that people have created for this release.

The only thing that should change is the `Country@1:` name/description in world.yaml.

**Comment by deniz1a** [comment]
But wouldn't it then be confusing to have two different names for the same faction? I can write an upgrade rule if that would be accepted. I can also try to make the map importer compatible with this...

**Comment by pchote** [comment]
I take back my comment about the upgrader - map lua scripts depend on the naming, and they cannot be automatically upgraded.

**Comment by deniz1a** [comment]
OK then I think I should close this PR until I find a solution to automatically upgrade maps and scripts...

**Comment by Unit158** [comment]
Scripts should NOT! be touched! Ever!

They are much more complex than the simple YAML rules, and the map authors should have to update them manually. An upgrader can not and should not reason about the identifiers used in Lua.

**Comment by deniz1a** [comment]
OK but it was also not wanted to update them manually.

**Comment by SoScared** [comment]
Any new movements on this? Would still love to see the faction name changed to Britain.

**Pull request closed without merging**
