### PR TITLE
Hide selection decorations when spectators zoom too far out.

### PR DESCRIPTION
**Pull request by pchote**
Before:

After:

### CODE REVIEW

**Review by abcdefg30 — COMMENTED** [review]
Comment from IRC: The path debug overlay will also be disabled which is unintentional.

**Comment by pchote** [comment]
Fixed. I also removed the limitation that the path debug overlay would not display for enemy units.

**Review by abcdefg30 — APPROVED** [review]
Ok.

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/38e1fd85458c21c729ec09278ae541937f929ca1)

**Pull request merged**
