### PR TITLE
Remove legacy sidebar code

### PR DESCRIPTION
**Pull request by pchote**

### CODE REVIEW

**Comment by Mailaender** [comment]
I suggest you link or reference instead of duplicating the RA build palette.

**Comment by Bynnar18** [comment]
If it's a placeholder then we can assume it'll be replaced eventually with something unique so I don't think referencing RA is all that important given that this will be replaced with something anyhow.

**Comment by Mailaender** [comment]
The PSD file is 6 MB large and binaries are bad for source code management so I would like to keep those at a minimum.

**Comment by pchote** [comment]
Removed the psd file.  You're right that people shouldn't be basing any future TS work off that file, so there's little point in keeping the source file around.

**Comment by Mailaender** [comment]
@x-a-n-a-x prepared some early drafts at http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=288650#288650

**Comment by pchote** [comment]
The goal here is to remove the old ingame UI code to complete the goal of having shared UI logic that people don't actively avoid dealing with.  TS currently uses a placeholder UI copied directly from an old version of the cnc mod, and so replacing it with a newer placeholder based on the new ra UI should not be controversial.  Building a proper sidebar for TS is well out of scope of this ticket.

**Comment by Mailaender** [comment]
@x-a-n-a-x is working on something right now so let's wait for that.

**Comment by pchote** [comment]
Rebased.  I think it is unfair to pressure @x-a-n-a-x to rush out a new UI for TS (which is going to take twice as much work as D2K, since there are both GDI and Nod sidebars to build) on short order.

**Comment by Mailaender** [comment]
We are going with one sidebar and different faction logos in the radar for now. https://github.com/OpenRA/OpenRA/issues/7474

**Comment by pchote** [comment]
I take that as evidence of rushing, vs taking the time to do it properly.

**Comment by Mailaender** [comment]
I take the duplication with the Red Alert sidebar as evidence of rushing. Try to add the core value "gradual improvement over initial perfection" to your collection of development philosophies.

**Comment by pchote** [comment]
Rebased.

**Comment by Mailaender** [comment]
You need to remove the files from the projects, too.

**Comment by pchote** [comment]
Odd, I guess that got lost during the rebase.

**Comment by reaperrr** [comment]
It's also weird that it passed travis.

Anyway, :+1: once the csproj is fixed.

**Comment by pchote** [comment]
Fixed.

**Comment by Mailaender** [comment]
This works nicely. It also adds the scrollbars when adding all vehicles in debug mode. No regressions/leftovers in the other mods. :white_check_mark:

**Comment by obrakmann** [comment]
looks good, the other mods are fine, yay for code removal! :+1:

**Comment by Mailaender** [comment]
This will probably break a lot of third-party mods.

**Comment by obrakmann** [comment]
Well, we don't really have "a lot of" third-party mods, so I doubt it'll be that bad.

[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e8c982d17ac138677cbbf20d35d7abb00d5d71d1%5E...e8c982d17ac138677cbbf20d35d7abb00d5d71d1)

**Pull request merged**
