### PR TITLE
Set ideal aircraft separation to half of the default value

### PR DESCRIPTION
**Pull request by teees**
before: https://streamable.com/8byl
after: https://streamable.com/z41e

### CODE REVIEW

**Comment by RoosterDragon** [comment]
This makes the other, larger, aircraft uncomfortably close. Maybe you should refine this to just affect the smaller ones?

**Comment by Mailaender** [comment]
Also needs a rebase.

**Comment by teees** [comment]
rebased and changed

**Comment by Mailaender** [comment]
This matches their visual sizes way better. :+1:

**Comment by RoosterDragon** [comment]
:+1:

**Pull request merged**
