### PR TITLE
Fix server filter width

### PR DESCRIPTION
**Pull request by penev92**
Fixes this:

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/1f6d68dd372dbaa2a1b61d79f989a5b09a29e97d)

**Comment by GraionDilach** [comment]
This also affects RA though.

**Pull request merged**
