### PR TITLE
Improve discoverability of dummy sound device

### PR DESCRIPTION
**Pull request by pchote**
This PR expands on #17245 to make it more obvious to players why their sound isn't working when the dummy sound device is active.

The first commit renames the sound device exposed in the settings.
The second commit disables the options when the sound is disabled or muted. It also fixes a silly bug where the sliders won't work at all if the sound is muted when the settings menu is first opened.

If the second commit is considered weird, I could instead display a label warning that the sound is disabled so changing them won't do anything, and find a different fix to whatever the mute code was trying to do.

### CODE REVIEW

**Review by Mailaender — DISMISSED** [review]

**Comment by reaperrr** [comment]
Probably out of scope for this PR, but: The 'disabled' feedback of the volume sliders sucks. Rather, other than being immovable, there's no visible indicator that they're disabled at all, not even greyed out text.

**Comment by pchote** [comment]
Indeed - this is what I was referring to in the final paragraph. Would you prefer to keep them active with a warning label somewhere (less obvious), or to hide the controls and show the warning instead (possibly less flexible)?

**Comment by reaperrr** [comment]
If it doesn't require too many changes, personally I'd prefer the text and slider box to grey out (in addition to becoming immovable), like what we do with the cash ticks box.

**Comment by pchote** [comment]
That would work too, but i'm not touching `chrome.yaml` again until #17489 has been merged.

**Comment by reaperrr** [comment]
> That would work too, but i'm not touching chrome.yaml again until #17489 has been merged.

I guess that disqualifies the approach for prep, then...
Could we compromise on just greying out the slider text in this PR and then a follow-up after #17489 greying out the slider boxes as well?

**Review by abmyii — DISMISSED** [review]

**Comment by pchote** [comment]
The main reason is that I have a tree of 4 levels of branches based on #17489, and I really don't want to deal with resolving the rebase conflict this would cause several times over.

If we wait for #17489 I can make the change in the new syntax for bleed, then file a separate PR with the legacy format for prep.

**Comment by pchote** [comment]
I'm now hiding the controls instead:

Screenshot 2019-12-28 at 10 37 36

and keep the slider bindings regardless of the mute setting.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/cb906c00b553f9b7b74d85a1783d9fba64b1b999...fcabba7d761d6e89e03a8c83d68793e9e1d9f5f7

846df4f
373bfdb

**Pull request merged**
