### PR TITLE
Refactor SupplyTruck/AcceptsSupplies to *Cash traits

### PR DESCRIPTION
**Pull request by reaperrr**
~It's only used by our RA mod and no more likely to be used by any 3rd-party mod than any other RA-specific logic (less likely, in my opinion), so I think it can be moved to Mods.Cnc.~

Renamed to more generic `DeliversCash`/`AcceptsDeliveredCash` and added Type/Stance tags instead.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Actually, i'm using Supply Truck logic on the D2K map i was working on which is currently on bleed, but will keep it on release when it happens.

I wouldn't mind much if this won't effect the Next but Next + 1. I don't think i would update the map anyway when that happens.

**Comment by reaperrr** [comment]
@MustaphaTR D2k currently needs the Mods.Cnc.dll anyway due to ProductionAirdrop, and I don't see that changing soon (not before Next+1 in any case).

**Comment by reaperrr** [comment]
Alternatively, we could keep it in Common and rename the trait to `SupplyActor` or `SupplyDeliverer` or `DeliversSupplies`.

**Comment by GraionDilach** [comment]
Coönsidering that these could be used for the YR Grinder even, I'd say it just needs a tag property.

**Comment by MustaphaTR** [comment]
Yea, i keep forgetting that D2k read CnC dll.

But Graion is right, this is the closet thing we have to grinder. So keeping it on common, renaming it and adding a Type: support for AcceptsSupplies and SupplyTruck so multipile types can be used (both actual Supply Trucks and Grinder for example).

**Comment by reaperrr** [comment]
Updated as suggested.

**Comment by GraionDilach** [comment]
Ah, I forgot this doesn't have a stance check. May you add that as well? :+1: after it.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by Iamgoofball** [comment]
#13000

**Review by pchote — DISMISSED** [review]
"Supplies" is still a mod-specific name (what's a supply?).  Can you please change these to `DeliversCash` and `AcceptsDeliveredCash` or something similar?

**Comment by pchote** [comment]
This PR supersedes #5925, so that one can be dropped from the Future milestone after this is merged.

**Comment by reaperrr** [comment]
Updated.

Note: Removing `AcceptsSupplies` from TS instead of renaming is intentional, that looks like copy-pasta from the early days of the mod.

**Comment by GraionDilach** [comment]
Probably you should also rename the DonateSupplies activity as well.

**Comment by reaperrr** [comment]
> Probably you should also rename the DonateSupplies activity as well.

Done.

**Review by GraionDilach — APPROVED** [review]
:+1: still stands.

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b20148a7bf083920401a104a562504ccfe040179)

**Pull request merged**
