### PR TITLE
Restricted effect rendering to the viewport

### PR DESCRIPTION
**Pull request by Mailaender**
Another take on https://github.com/OpenRA/OpenRA/issues/9443 after https://github.com/OpenRA/OpenRA/issues/9699 grew way too complex and error prone.

### CODE REVIEW

**Comment by pchote** [comment]
Unfortunately, like I mentioned in IRC earlier, I do not think this a good approach:

* It ignores the existing conventions that we use for actor rendering, and instead invents its own.
* We still pay the cost of generating the renderables, and then pay an additional cost of a duplicate `PrepareRender` on each.

I suspect that these tradeoffs may completely negate the benefits that we want from #9443.

**Comment by reaperrr** [comment]
> We still pay the cost of generating all the renderables (which is a significant chunk of the rendering!), and then pay an additional cost of a duplicate PrepareRender on each.

Just a thought, would it be possible/feasible to simply create some "is WPos in player's viewport" boolean (similar to the `FogObscures` check, just hopefully much cheaper in terms of performance), and then only generate the renderable if that is `true`?

**Comment by pchote** [comment]
Yes (except in screen space instead of world).  This is essentially what actors and #9699 do.

**Comment by Mailaender** [comment]
I tried it in https://github.com/OpenRA/OpenRA/issues/9443 and it doesn't work for text and line renderables, because they don't define a position and don't have a valid bound ready in the constructor, because that is calculated just before getting rendered.

**Comment by reaperrr** [comment]
@Mailaender isn't the 2nd commit possibly the fix for the issue you had in #9699?

**Comment by Mailaender** [comment]
Sadly screen bounds for actors are offset + bounds and effects are location + bounds. Plus all effects will crash the game as they have empty screen bounds in constructor and the first iterations of Tick.

**Comment by pchote** [comment]
Thosw are implementation details/issues with those specific effects (which can be fixed).  Adding engine level workarounds for bad code just cements the technical debt and makes it harder for the next person.

**Pull request closed without merging**
