### PR TITLE
Fix waypoint, spawnpoint and camera editor art

### LINKED ISSUE #9989: Remap errors for MPSPAWN, CAMERA and WAYPOINT
They were supposed to be semi-transparent and remapped to player colors. https://github.com/OpenRA/OpenRA/issues/3377#issuecomment-76590891

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28246386-remap-errors-for-mpspawn-camera-and-waypoint?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
- added camera editor art to cnc, d2k and ts
- fixed shadow and remap colors where necessary
- fixed d2k effect palette shadow index

I think this should go into release as it's a nice bit of polish.

Closes #9989.

### CODE REVIEW

**Comment by pchote** [comment]
Don't forget about the worm spawner in d2k!

**Comment by pchote** [comment]
:+1: after that fix

**Comment by reaperrr** [comment]
Done.

**Comment by obrakmann** [comment]
Thanks. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ea4321495e49722f0fbc8e40e98807958cb170a2)

**Comment by Mailaender** [comment]
Thanks!

**Pull request merged**
