### PR TITLE
Show only missing required "mod (version)"s

### PR DESCRIPTION
**Pull request by atlimit8**
As requested in @Phrohdoh's [comment](https://github.com/OpenRA/OpenRA/pull/9463#issuecomment-152861123) to #9463 for the mod installer.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
While I did originally request this I believe it would be better if we took this visual approach.
Excuse my terrible graphic.

sketch

**Comment by penev92** [comment]
Sorry, I'm not convinced about this. We will probably (eventually) want to go with a grid like the above one.

**Comment by pchote** [comment]
I'm quite happy with this as a short term fix that bridges the (probably many months) time until somebody can lay this out as a table.  @Phrohdoh, @penev92: if you are committed to the commit that this must go straight to a table, then please close this as it is past our stale-pr-close cutoff.

**Comment by Phrohdoh** [comment]
I'm fine with taking this as-is because our "short term" fixes are typically long lasting but I'd rather accept that than having people get upset over UI.

I'll test this again tonight (hopefully) and give a +1.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by Phrohdoh** [comment]
screen shot 2015-12-30 at 7 38 19 am

:+1:

**Pull request merged**
