### PR TITLE
stop "Unit Ready" sound spaming when Instant Buildtime is enabled

### PR DESCRIPTION
**Pull request by LipkeGu**
By adding the missing condition... Normal mode works as expected...

### CODE REVIEW

**Comment by abcdefg30** [comment]
Now I don't get any `unit ready` notifications when building with the dev cheats.

**Comment by LipkeGu** [comment]
thats because every unit is done under 1 second :)

**Comment by Unit158** [comment]
I'm really not convinced this is the correct way to fix this issue. I have an idea that might work a little bit better.

**Comment by LipkeGu** [comment]
lets hear

**Pull request closed without merging**
