### PR TITLE
Fix wrap text on credit widget

### LINKED ISSUE #20971: Credits window doesn't render wordwrapped text correctly
## Issue Summary

When `LabelWidget` is configured to wrap text using `WordWrap: True`, the text inside the label is wrapped in terms of maximum width, but long lines overlap with other lines. The reason is that `CreditsLogic.ShowCredits` renders each line from credits file as separate `LabelWidget`

## Reproduction

Remove manual wraps in `AUTHORS` file in the part with credits to libraries/services at the end of the file.

## Expected behavior

The text should be properly wrapped and lines should not overlap with each other.

## Screenshots

credits_wordwrapping

### PR DESCRIPTION
**Pull request by sa3047**
Fixes #20971

Fix wrap text on credit widget #20983

### CODE REVIEW

**Comment by PunkPun** [comment]
Hello,

It seems this has regressed the current credits. Also now text can be wrapped twice, as in content is wrapped in CreditsLabelWidget and in LabelWidget when using `WordWrap: True` #20971

**Comment by sa3047** [comment]
@PunkPun I double checked by default wordwrap is false, when we create LabelWidget. I tried to debug it and I am not able to understand below line is causing extra spaces in credits labels.

[Line 91](https://github.com/OpenRA/OpenRA/pull/20983/files#diff-4f64ff94cb27b9ca4c62e869408c82dcb678867d376e06ca75f63f1ec3744b1eR91)

I am following below steps. Let me know what I can do to fix this issue.

1. replace new line chars
2. wordwrap using widgetutils functions
3. add that to label text property
4. Increase the label height by context text
5. Add Label into scrollPanel widget

Appreciate any input. Thanks in advance.

**Comment by PunkPun** [comment]
When adding `WordWrap: True` to the `Label@CREDITS_TEMPLATE` inside the `credits.yaml` file and editing AUTHORS file to not include whitespaces I found an additional issue. The label length does not account for the scrollbar

As for the cause of your regression? Label template already has its height set to `Height: 16`, so when you add the text height it adds onto it doubling the gaps

**Comment by PunkPun** [comment]
Closing as it seems the PR is dead

**Pull request closed without merging**
