### PR TITLE
Create abstract class AffectsShroud[Info] with RevealsShroud core logic also used by CreatesShroud

### LINKED ISSUE #9297: CreatesShroud inherits from RevealsShroud, but are functionally disjoint.
`CreatesShroud` inherits from `RevealsShroud`, but every actor with `CreatesShroud` also has  `RevealsShroud` in the MiniYaml (`GAP` in `mods/ra/rules/structures.yaml:78-83`, `MGG` in `mods/ra/rules/vehicles.yaml:504-507`).

Separating the two would be the most flexible option.

`CreatesShroud` *currently* derives from `RevealsShroud`:
```c#
	public class CreatesShroud : RevealsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```

I'm proposing that that be change to:
```c#
	public class CreatesShroud : AffectsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```
where `AffectsShroud` is an absract base class for `RevealsShroud` & `CreatesShroud`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26493508-createsshroud-inherits-from-revealsshroud-but-are-functionally-disjoint?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by atlimit8**
Closes  #9297.

### CODE REVIEW

**Comment by penev92** [comment]
Please either put all 3 classes in 1 file or put each in its own file. The current separation doesn't make sense any more.

**Comment by atlimit8** [comment]
Split into 3 files now.

**Comment by atlimit8** [comment]
`git diff` seems to have trouble seeing that I renamed `OpenRA.Mods.Common/Traits/RevealsShroud.cs` => ` OpenRA.Mods.Common/Traits/AffectsShroud.cs` and created a new `OpenRA.Mods.Common/Traits/RevealsShroud.cs`.

**Comment by RoosterDragon** [comment]
It isn't obvious that ```addCellsToPlayerShroud```, ```removeCellsFromPlayerShroud``` and ```isDisabled``` need to be assigned.

Try adding a constructor argument in ```AffectsShroud``` for them, or maybe change them into abstract methods instead.

**Comment by atlimit8** [comment]
Changed.

**Comment by RoosterDragon** [comment]
:+1: Looks reasonable to me and revealing and gap gens still work.

**Comment by pchote** [comment]
Looks good, and confirmed that gap gens and sight still work :+1:.

**Pull request merged**
