### PR TITLE
Resize TD mission browser

### LINKED ISSUE #11388: TD: Missions screen is too small for mission names
See screenshot:

missions_screen

I dunno if I should shorten the names or if the missions screen should receive a redesign. The names are as follows:

- Destroy the Mammoth Tank Facility
- Recapture The Ezekiel's Wheel (a)
- Recapture The Ezekiel's Wheel (b)

And probably some other missions that haven't been ported yet.

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #11388.

I checked that the title "Restore GDI Presence Near Salzburg" fits.

I also finally added the map numbers to the mission titles.

### CODE REVIEW

**Comment by pchote** [comment]
GDI 01,02,03, and Nod 01 use `.` as a separator, while all the others use `:`.  Can you please make them all the same?

**Comment by pchote** [comment]
Looks good and seems to work well ingame otherwise, thanks.  :+1:

**Comment by obrakmann** [comment]
Woops, indeed. Fixed.

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/45174300564572f8782008ef4c83b6cc452e53fb...66374ffb17a099762f6d87866da59aeba7a487df)

**Pull request merged**
