### PR TITLE
Improve performance of path-debug command.

### LINKED ISSUE #20215: Path-debug is incredibly performance heavy
https://user-images.githubusercontent.com/37534529/185956324-e8f43ab5-52f6-4ac7-9493-32665229fe84.mov

When I click behind these sub pens my FPS more than halfs, (This map is called Ensio Kaivo)

### PR DESCRIPTION
**Pull request by RoosterDragon**
If a long path was being visualized with the path-debug command it would generate renderables for everything on the path, even for parts of the path that would be offscreen. Add some simplistic culling so the performance impact is reduced.

### CODE REVIEW

**Review by anvilvapre — APPROVED** [review]
Untested.

Many similar function arguments. Consider creating arguments `new WVec(HorizontalOffset, VerticalOffset, 0)` once. Also to perhaps add a function that takes less arguments i.e. with the same font and color.

**Comment by RoosterDragon** [comment]
There's some minus signs being tweaked in each one, so it's not the same argument used across all the calls.

**Review by PunkPun — APPROVED** [review]
LGTM, this improves the perf but doesn't close the issue as it's still very performance intensive

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e726b4c513690e022aad99c68aa7bc23a5bc4c43...2ff00f2c659e6313439a50da9974140abb9e76fc)

**Pull request merged**
