### PR TITLE
Fixed transparency breakage on quad and line rendering

### PR DESCRIPTION
**Pull request by Mailaender**
A regression from https://github.com/OpenRA/OpenRA/pull/8176.

### CODE REVIEW

**Comment by MutterOberin** [comment]
I fixed the debug overlay rendering for A* path cost now. 

This is not needed anymore, right?

**Comment by Mailaender** [comment]
More like the other way round. This already fixes a broader range of breakage than the workaround at https://github.com/OpenRA/OpenRA/pull/8249 and https://github.com/OpenRA/OpenRA/pull/8258.

**Comment by abcdefg30** [comment]
This fixes the A* path debug overlay.

**Comment by obrakmann** [comment]
Fixes the over-saturated range circles, too. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9859d7e02db58e2c64a5ffb094585f242c117200%5E...9859d7e02db58e2c64a5ffb094585f242c117200)

**Pull request merged**
