### PR TITLE
Remove redundant frames from TS repair bay Nod icon shp

### PR DESCRIPTION
**Pull request by reaperrr**
The original Nod version of the repair bay icon has two completely redundant frames inside the SHP (damage frames of the original building, actually).
While that doesn't affect ingame appearance, it's still bad in terms of which impact it has on the size and efficiency of the sprite sheet, so using a fixed shp is better for memory efficiency or should at least help reducing the number of texture sheets in the future.

### CODE REVIEW

**Comment by reaperrr** [comment]
This PR:
sheet5-fixed

Bleed:
sheet5-bleed

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by pchote** [comment]
`Length: 1` in the sequence should fix this without requiring new artwork

**Comment by GraionDilach** [comment]
It doesn't. Unused frames of an artwork still pop up on the sprite sheets.

**Comment by pchote** [comment]
Ok.  Give me a couple of days and I will fix that.

**Comment by pchote** [comment]
Superseded by #15098.

**Pull request closed without merging**
