### PR TITLE
 Remove out of bounds actors from missions

### PR DESCRIPTION
**Pull request by Smittytron**
There were several actors left outside the map boundaries when these missions were ported. This removes them, and pulls a few stray waypoints back inside the bounds. There are no trees in d2k, and I did not find any actors outside the bounds there.

### CODE REVIEW

**Comment by Mailaender** [comment]
Why do you want them removed?

**Comment by Smittytron** [comment]
The player can't see or interact with these actors. It's effectively junk data.
The waypoints needed to be pulled in bounds to work properly. (#14593)

**Comment by MunWolf** [comment]
Are you sure scripts don't make use of them?

**Comment by Smittytron** [comment]
Yes, I checked the scripts on every waypoint I removed and on the the units that were outside in Sov03. The used waypoints are the ones I brought back in the boundary.

**Review by Mailaender — APPROVED** [review]
Okay then.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/875171c0057ff30bf3b43fc8819fd7bdb247203b...a105969b3159ae7a797048c89160ac7fd1770fe6)

**Pull request merged**
