### PR TITLE
Fix margins of refund tooltips

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by Phrohdoh** [comment]
:+1:

**Comment by pchote** [comment]
The margins look good to me, but can you add the missing $ too?

**Comment by obrakmann** [comment]
Added dollar sign to tooltip

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/742582a91e635c8b2982c7d92f9dbacd70ba8051%5E...742582a91e635c8b2982c7d92f9dbacd70ba8051

**Pull request merged**
