### PR TITLE
Next

### PR DESCRIPTION
**Pull request by justinr776**
Oktoberfest

### CODE REVIEW

**Comment by GraionDilach** [comment]
This PR looks broken to me. What was your actual aim?

**Comment by pchote** [comment]
Looks like he is trying to game the system for a free tshirt.  Somebody should report him to the github staff.

**Comment by GraionDilach** [comment]
Well, honestly, his profile seems like a teacher to me so it's really odd seeing such in this scenario. On the other hand he doesn't even have a fork so I guess this is indeed just for the abuse. I'm writing the report as we speak.

**Comment by MicroJOo** [comment]
what a weirdo

**Pull request closed without merging**
