### PR TITLE
Fixed GitHub syntax highlight complaining about tabs

### PR DESCRIPTION
**Pull request by Mailaender**
Same as https://github.com/OpenRA/OpenRA/pull/18002 but project wide.
Preview: https://github.com/OpenHV/OpenHV/tree/master/mods/hv/rules

### CODE REVIEW

**Comment by pchote** [comment]
As discussed (mainly in IRC) around the time of #18002, I really don't like the idea of declaring our miniyaml as some random niche syntax that has nothing to do with our actual usage - Linguist is open source, so we should do this properly by adding *our* random niche syntax (i.e. MiniYaml) to its list.

SaltStack is defined as a programming-type syntax instead of data, which means that it will be displayed in the languages list in the repo sidebar (and is very likely to dominate the percentages). If others want to go ahead with the current approach, then we need to be at least declaring `-linguist-detectable` to avoid contaminating that list.

**Comment by dragunoff** [comment]
Not a fan of this workaround. I think [adding our MiniYaml niche syntax to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) is the way to go.

**Comment by Mailaender** [comment]
https://github.com/github/linguist/blob/dc577fe72a28ab069f02cc002b4f2e3851a72f93/lib/linguist/heuristics.yml#L74-L75 They allow stuff like @AdventureGameStudio script so that seems like a possibility. We can then re-use the @TextMate grammar for VS Code.

**Comment by pchote** [comment]
I also noticed that the SaltStack grammar behaves badly with MiniYaml arrays and values that start with `^`. An OpenRA-specific grammar would allow these (and others) to be treated correctly.

**Comment by Mailaender** [comment]
https://github.com/pchote/OpenRA/tree/linguist/ also seems to be a good workaround.

**Pull request closed without merging**
