### PR TITLE
Selectable option for HackyAI

### PR DESCRIPTION
**Pull request by TheBlueLeader**
My request would be making mapping more user and beginner friendly and this would be "Selectable" trait for HackyAI. :) Because for now you just can allow or disable certain AI for the map to be selectable but disabling will remove functionality for that AI even if it have been set via yaml file.
Accepting my request would make it a lot of simpler to make quite a good AI because yaml's are not that difficult to understand than LUA and allows actually also much better things for AI than LUA itself also. In addition this AI could be hidden then for lobby to allow old and regular settings for human players only. :)

For example I made Blue Group that would be able to build both units and structures by Allies and Soviet and that's behaviour would be different from other AI's. With HackyAI I would be able to make the most part of it but I want this AI to be available only for ingame custom AI not visible at lobby and I want to provide old regular skirmish AI's for humans that must be not changed that's why. Making Blue Group is real pain to create in LUA only because it is difficult or nearly impossible even to make simple AI in LUA.
If I would have HackyAI that can be hidden from lobby then I think I would use LUA only for few fixes that HackyAI nor another yaml's still doesn't allow. :) This would be enough also to make custom hidden AI even by the beginners soon enough.

### CODE REVIEW

**Comment by LipkeGu** [comment]
please rebase your changes against bleed by using befor pushing it to your PR branch

```
git fetch upstream
git rebase upstream/bleed
```

**Comment by GraionDilach** [comment]
This isn't even a PR, just a feature request posted totally wrong.

**Comment by reaperrr** [comment]
@TheBlueLeader 
Although  it contains the word "requests", the Pull requests tab is for submitting code or other changes.
To file a feature request, you actually have to use the Issues tab.

**Comment by TheBlueLeader** [comment]
I saw that people are talking about OpenRA and are doing even request so I joined and started to post but soon I realized that this site is very different from regular forums. So I admit that I may have done this very improperly.

**reaperrr:** I think your comment helps me much because you show understading the reason why my post was made like it was. What's the most important you explained me where do I need to post and mentioned also that although it contains the word "requests"... So you understood the reason by me doing this very wrong. :D

Sorry for this! Should I delete this?

**Comment by GraionDilach** [comment]
>I saw that people are talking about OpenRA and are doing even request so I joined and started to post but soon I realized that this site is very different from regular forums. 

Well, because this is not a forum but a development platform + bugtracker.

**Pull request closed without merging**
