### PR TITLE
Fix DeliverUnit-related crash

### LINKED ISSUE #17208: DeliverUnit related crash
This happened while testing #17055 but seems unrelated to this PR. 

<details>

```
OpenRA engine version {DEV_VERSION}
Dune 2000 mod version {DEV_VERSION}
on map 0b2a79b86ddd04965cf9d40ed31d76d623cc3ae9 (Eyes of The Desert by Blueblood).
Date: 2019-10-09 17:52:54Z
Operating System: Linux (Unix 4.15.0.65)
Runtime Version: Mono 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Activities.DeliverUnit+ReleaseUnit+<>c__DisplayClass4_0.<OnFirstRun>b__0 (OpenRA.World w) [0x00021] in <6381e02f12b4441c953e88b4184fe726>:0 
  at OpenRA.World.Tick () [0x001a9] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001bc] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Game.LogicTick () [0x0003e] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Game.Loop () [0x000e3] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Game.Run () [0x0003c] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00044] in <a0fcc7c9cdf440dc9188b6796928c8d9>:0

### PR DESCRIPTION
**Pull request by reaperrr**
(Probably) fixes #17208.

### CODE REVIEW

**Review by tovl — DISMISSED** [review]
Code changes look good.

**Comment by pchote** [comment]
Does this relate to #17353 at all?

**Comment by tovl** [comment]
The crash report in #17208 indicates that `DeliverUnit` was the root activity and not related to `FerryUnit`.

**Comment by matjaeck** [comment]
> (Probably) fixes 

See https://github.com/OpenRA/OpenRA/issues/17208#issuecomment-544264835 for reproduction information.

**Comment by pchote** [comment]
@tovl I’m wondering whether there may be some more fundamental issue that then triggers the crashes here or in FerryUnit depending on which runs first.

**Comment by tovl** [comment]
Hmm, there is certainly something weird going on. The only time `DeliverUnit` runs as root activity and not as a child of `FerryUnit` within D2K is when a new refinery is build and a new harvester gets delivered. It shouldn't be possible for anything to happen to the harvester between it being created and the `DeliverUnit` activity ticking that could make it `null`.

**Comment by pchote** [comment]
My testing in #17208 shows that we need to be checking `self.IsDead` (and `carryall.Carryable` if we want to be extra safe) inside the FrameEndTask instead.

**Comment by reaperrr** [comment]
Updated.

**Review by pchote — APPROVED** [review]
LGTM

**Review by abcdefg30 — APPROVED** [review]
Code changes look reasonable.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/80caa8745efae014ab04d7691eb7d0c87fec714e...987f7c5106360f309fab0080ace86e58c6ccd636)

https://github.com/OpenRA/OpenRA/commit/d71b116969217b4d55c83058d6a408ea6a000b99

**Pull request merged**
