### PR TITLE
Spy veterancy leftovers

### PR DESCRIPTION
**Pull request by matija-hustic**
Fixes regression from #8210 (RANK+1 displayed for every experience increase instead of only on level increments).

Disables levelup thru war factory spy infiltration in Allies05 (https://github.com/OpenRA/OpenRA/pull/8210#issuecomment-117320639)

Sorry bout missing these in #8210

### CODE REVIEW

**Comment by GraionDilach** [comment]
Oh, so this is why I see all those levelups! Thought it's just me. :+1:

**Comment by abcdefg30** [comment]
Needs a rebase.

**Comment by matija-hustic** [comment]
Rebased.

**Comment by obrakmann** [comment]
Confirmed fix. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/ded6924e3f9041f5483ffc0fb1e96d617393ef22%5E...ded6924e3f9041f5483ffc0fb1e96d617393ef22)

**Pull request merged**
