### PR TITLE
Split server translations int their own file

### PR DESCRIPTION
**Pull request by PunkPun**
This just adds an additional en.ftl file.

Server also needs lobby option translations to function so we'll want to split those eventually as well. They don't split as cleanly atm.

### CODE REVIEW

**Comment by Mailaender** [comment]
I think you should show how you want to use that file before we split this.

**Comment by PunkPun** [comment]
Does it matter? I thought the consensus was that we should split up the en.ftl files into smaller yet still decently sized chunks. We don't want to force third parties to choose wether to take all translations or none

**Comment by Mailaender** [comment]
Yes, it does matter as this adds change for thirdparty mods and another one when it is reverted.

**Comment by PunkPun** [comment]
I'm not sure how it should look like. My first attempt is here https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:translation-split. I doubt that we'll need a revert though. It makes sense to have these translations separate even without the custom server loading

**Comment by pchote** [comment]
> I thought the consensus was that we should split up the en.ftl files into smaller yet still decently sized chunks.

The comments in discord seem to indicate that the consensus is actually to *not* do this.

**Comment by PunkPun** [comment]
Closing as cleanup

**Pull request closed without merging**
