### PR TITLE
Fix explosion effects on trees

### LINKED ISSUE #13686: Shooting on tree shows no explosion effect (Playtest-20170722)
Verified on the fresh installation of the new Playtest.

Force firing cannon shells onto a live tree (not burnt ones) shows no weapon FX and feels very odd.

### PR DESCRIPTION
**Pull request by reaperrr**
I forgot that trees don't have the Ground TargetType (to make them invulnerable to everything but flame weapons) when refactoring the effect warhead.

Fixes #13686.

### CODE REVIEW

**Comment by pchote** [comment]
On the topic of renaming things, we should rename the new `TDTRUK` to something more appropriate.

**Comment by reaperrr** [comment]
> On the topic of renaming things, we should rename the new TDTRUK to something more appropriate.

I'd just remove the 'TD' and maybe add the missing letter (make it TRUCK), any other suggestions?

**Comment by reaperrr** [comment]
> I'd just remove the 'TD' and maybe add the missing letter (make it TRUCK)

Done.

**Comment by ltem** [comment]
- Rename TD TowerMissle to TowerMissile ✔️  
- Rename tdtruk to truck ✔️ 
- Fix RA effect waheads ✔️
- Fix TD effect warheads to account for trees ✔️

The changes seem fine to me (I couldn't spot anything missing) and the issue is fixed but I have two questions.

1. I couldn't reproduce the issue (missing explosions on trees) in `cnc` in the playtest, still there are changes for it. Why?
2. Trees and water are not `ValidTargets` for `Missiles` in `cnc` , still the explosion gets enabled for it. Why? (Similiar situation for e.g. `^AACannon` or `^Explosion` in `ra`)

So 👍 from me (which is maybe devalued by my questions 😄 )

**Comment by reaperrr** [comment]
> I couldn't reproduce the issue (missing explosions on trees) in cnc in the playtest, still there are changes for it. Why?

I forgot about it while making the changes, but since effect warheads in TD all have victim scans completely disabled, they won't 'find' trees and 'think' they just hit normal ground, which is a valid target.
Same goes for some AA weapons in RA.

> Trees and water are not ValidTargets for Missiles in cnc , still the explosion gets enabled for it. Why?

Water tiles in TD mod contain both Water and Ground TargetTypes, and Ground is valid while Water is not listed as invalid.

**Comment by reaperrr** [comment]
Updated.

**Comment by ltem** [comment]
👍 

(Thanks for the explanation.)

**Review by ltem — APPROVED** [review]

**Review by SoScared — APPROVED** [review]
Appears to generates explosions effects from all ballistic/missile types.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2754f116fab7de8224da17776748c013af7e22e7...ec4d1ac5c5dd87f4e21ced816e33d094c03f9528)

https://github.com/OpenRA/OpenRA/commit/818fc9d1731be44241dcdb7a5f2b20ea2953bd7a
https://github.com/OpenRA/OpenRA/commit/09d9cf7da6836a1d9e48399705af814d313277f3
https://github.com/OpenRA/OpenRA/commit/63ee481f01cfa8f9804bb7cf1a2549e0c7b2530a

**Pull request merged**
