### PR TITLE
Add nod08b

### PR DESCRIPTION
**Pull request by ghost**
Add nod08b - "Battle for Zaire (b)"
http://cnc.wikia.com/wiki/Battle_for_Zaire

**Known issue:**
Boats turn into idle actors and stop their patrol, each time they attack an unit.
Is there a way to avoid turning them into idle actors?

### CODE REVIEW

**Comment by Mailaender** [comment]
I believe the gunboat stopping during attacks is related to https://github.com/OpenRA/OpenRA/issues/3288.

**Comment by obrakmann** [comment]
The patrol thing is actually related to https://github.com/OpenRA/OpenRA/issues/7454#issuecomment-107056625. The way `AttackMove` works right now is absolutely moronic, and needs a complete re-write of `Activity` to be fixed properly.

**Comment by Mailaender** [comment]
Actually for me the boat turned around when it was attacked, but I don't think you should try to fix it during this pull request. The only nit I have with the boats is that you can destroy them in this mission, but they don't define an explosion on death.

**Comment by Biofreak1987** [comment]
it's turning around as it's wrapped inside a Trigger.OnIdle, which tells it to patrol (The first waypoint is located on the left). It would stop moving without that one.

**Comment by HenrytheSlav** [comment]
Idk why GDI ships have no naming, I see "Enemy " (the blank space is intentional.
campaign-tooltips.yaml defines ships and Boat inherits ^ship. Is there something more to this?

I assume the camera/visibility of boats is intentional and taken from original. But maybe it would be cool to turn it on when you build Communications centre? It coould in theory be secondary tasks (Build commcentre to track enemy naval support). Nod player has almost no reason to build commcentre since he gets no airstrikes.

Another thing to consider is that you get flame troops to build at hand of nod, which allows you kinda sneakattack at start using chinnok (also in (a) ).

Otherwise seems verya well made.

**Comment by Mailaender** [comment]
> Should I make them invincible or do you plan on adding an explosion for this actor type?

They are already quite sturdy. Making them invincible would be overkill. Just add an explosion type.

**Comment by HenrytheSlav** [comment]
> Just add an explosion type.

Maybe even define that generally? In separate commit in this PR. I guess it doesn't hurt to have.

**Comment by Biofreak1987** [comment]
Added an explosion to the boat.
Revealing GDI ships when you have a communications center sounds interesting... feel free to create a separate commit for that.

**Comment by HenrytheSlav** [comment]
I actually meant to make the gunboat explosion general. (in original yaml)

**Comment by Biofreak1987** [comment]
Reverted the last change seeing as boats get used in nod09, nod11a/b and nod13a/b/c as well. I rather change it with a different merge request by updating the ship.yaml and giving it a explosion similar to red alert ships.

**Comment by HenrytheSlav** [comment]
Could you please also solve that they have wrong name? At least I saw tooltip with "Enemy ". That should be done together.

**Comment by Mailaender** [comment]
We can do it in a separate pull request. That is true. The mission itself works fine. :white_check_mark:

**Comment by HenrytheSlav** [comment]
Could you fix this? Preferably globally like the explosion? Otherwise :+1:
openra-2016-05-16t164742z

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/caf0f75a7345de7c7cf88fa12210aac7eb46bd36...4ca1c0b136ac7451632c67df95cbda4f43a85de5)

**Pull request merged**
