### PR TITLE
Drop attack targets when switching to a more restrictive stance.

### LINKED ISSUE #8373: Changing the units stance should also stop its current action
https://www.youtube.com/watch?v=RUrlddwGN1M&t=7m
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/20213211-changing-the-units-stance-should-also-stop-its-current-action?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
This PR changes the attack activities to drop the current target when the unit's stance is changed if:
* The new stance is more restrictive than the previous one
* The target is not auto-targeted in the new stance
* The attack was not force-targeted

Fixes #8373.

### CODE REVIEW

**Comment by matjaeck** [comment]
Something is not right - changing an attacking apc/tank to hold fire stance does not stop the attack.

**Comment by matjaeck** [comment]
The issue only occurs when you target something else than a structure.

**Comment by abcdefg30** [comment]
Needs a rebase.

**Review by abcdefg30 — DISMISSED** [review]
Can confirm, this does not work when targeting non-structures.

**Comment by pchote** [comment]
Right. I'd forgotten that ReturnFire and HoldFire restrictions were hardcoded instead of relying on conditional `AutoTargetPriority`s. Fixed by adding an extra check to `HasValidTargetPriority` and rebased.

**Review by ghost — COMMENTED** [review]
Tested in RA and looks good from the ingame perspective :+1:

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9cac12e9f02d1ca79b118bda8368d321ded65d61...f0418d6bdd2c80ba40e921fa8ace9e0dcc1c7831)

**Pull request merged**
