### PR TITLE
Revert "Deploy with just OpenRA-Setup.exe"

### PR DESCRIPTION
**Pull request by Mailaender**
Reverts OpenRA/OpenRA#7761

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
Looks like we need to add a `make version` somewhere, too:

```
(00:15:56) abcdefg30: it installed without errors
(00:16:05) abcdefg30: but shows {Dev_Version}
````

**Comment by Mailaender** [comment]
Looks like this does not work as expected:

> Uploading artifact OpenRA-.exe (9.5 MB)...OK

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/issues/7766 and https://github.com/OpenRA/OpenRA/issues/7767.

**Pull request closed without merging**
