### PR TITLE
Fixed missile shadow on elevated terrain

### PR DESCRIPTION
**Pull request by reaperrr**
Looks like neither me nor the reviewers tested missiles in TS properly in #8923.

### CODE REVIEW

**Comment by Unit158** [comment]
:+1:

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
Is this `For stable`?

**Comment by penev92** [comment]
Nah, it only affects TS.

**Comment by abcdefg30** [comment]
Or custom mods.

**Comment by GraionDilach** [comment]
Still not enough justification imo. At the moment diamond-tiled custom mods shouldn't affect the release cycle.

**Pull request merged**
