### PR TITLE
Fix the spectator UI being too wide

### LINKED ISSUE #17059: Specatator UI a few px too wide in TD/D2k/TS
Some of the panels overlap the sidebar by a few px at our minimum resolution (1024x720). We should make sure that all panels stay within a horizontal width of ~760 px (including the scrollbar if needed).

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #17059. (Together with #17055.)

### CODE REVIEW

**Comment by pchote** [comment]
The TD Economy and Combat panels and the two graphs still overlap with the scrollbar enabled.

**Comment by abcdefg30** [comment]
Updated. This is no completely based on #17055.

**Comment by pchote** [comment]
RA AI names run off the side of the graph background:

Screenshot 2019-10-09 at 20 45 36

Otherwise LGTM, good work slogging through all the changes here :+1:

**Review by ghost — COMMENTED** [review]
LGTM, the text overflow issue does not occur on my screen (`<pchote> could be related to hidpi`).

**Comment by reaperrr** [comment]
Needs rebase now.

**Comment by abcdefg30** [comment]
Rebased and updated.

**Review by pchote — APPROVED** [review]
LGTM in all four mods at min res.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/3706b7b1e9ece6089882f41910c433093be962dd...b699ac37844eff80714f5423cce48169e5ea455a

508f748
1353ad3
f15bb98
ac1d95c

**Pull request merged**
