### PR TITLE
add troubleshooting info for SDK path error

### PR DESCRIPTION
**Pull request by tmsbrg**
Tell me if this is stupid and should be fixed another way. But this would have helped me find out what this error meant and fix it for myself faster(Google wasn't too helpful this time).

### CODE REVIEW

**Comment by pchote** [comment]
Related to #10661.

**Comment by obrakmann** [comment]
We could also add that to the `Compiling` wiki page (why don't we auto-generate `INSTALL.md` from that?).

At least we point people to the `Compiling` page more often than we tell them to read `INSTALL.md`.

**Comment by Mailaender** [comment]
This is worded like a https://github.com/OpenRA/OpenRA/wiki/FAQ entry so it might be placed there. https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md has very bad discover-ability. We should probably consolidate our documentation a bit.

**Comment by Mailaender** [comment]
> (why don't we auto-generate `INSTALL.md` from that?).

The tarball published at https://github.com/OpenRA/OpenRA/releases won't contain it.

**Comment by pchote** [comment]
Why don't we remove the compiling page and point people to INSTALL.md instead?

**Comment by Mailaender** [comment]
The wiki has the benefit that it is quicker to update by anyone.

**Comment by tmsbrg** [comment]
I didn't even know about the wiki page, so maybe the line in INSTALL.md should instead link to the wiki, and the wiki should contain this troubleshooting info. I'm used to just cloning the repository and checking INSTALL.md and README.md for instructions.

**Comment by tmsbrg** [comment]
I've updated the [Compiling](https://github.com/OpenRA/OpenRA/wiki/Compiling) page on the wiki. So this is no longer needed to be in INSTALL.md. Probably still need a link to the wiki in INSTALL.md. But I'll close this pull request as it's no longer relevant. If you see any errors I made updating the wiki page, feel free to fix them.

**Pull request closed without merging**
