### PR TITLE
Give D2k its own mission browser

### PR DESCRIPTION
**Pull request by penev92**
Since D2k has different requirements about the size and shape of some components than RA, it gets its own mission browser.
Feel free to compare with bleed and decide which looks better ;)

### CODE REVIEW

**Comment by abcdefg30** [comment]
Well, this is just a bigger version, isn't it? :D
Anyway looks good to me except this overlap, but I'm not sure if this is a issue:
d2kmissionoverlap

**Comment by abcdefg30** [comment]
> Anyway looks good to me except this overlap, [...]

Doesn't seem like an issue to anyone. So :+1: / :white_check_mark:

**Comment by Mailaender** [comment]
It adjusts it to the bigger map size. :+1: 

> Anyway looks good to me except this overlap

Should be easy to fix. Just move the performance graph further to the left.

image

**Comment by penev92** [comment]
This overlap depends on the windows size you have OpenRA.
While the mission browser is static, the performance graph is relative to the bottom right corner.
So for people with big screens there will be no overlap. And for people with small screens the performance graph may be completely hidden.
With small enough window size this would happen with every single windows across every mod - lobby, settings menu, asset browser.

**Comment by abcdefg30** [comment]
I count :+2:, therefore merging now.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/139a5760a535bab13f32c1d40e6b634289b6d84a...a5f880bbed1b593414764ef47ef0802d56dc6960)

**Pull request merged**
