### PR TITLE
Support skipping stacked condition levels.

### PR DESCRIPTION
**Pull request by pchote**
Testcase is to replace the RA `^IronCurtainable` default and use the iron curtain multiple times on an actor.  The second level will lighten the actor, and the fourth level will darken it.

```yaml
^IronCurtainable:
	UpgradeOverlay@IRONCURTAIN:
		RequiresCondition: invulnerability && !invulnerability2
	UpgradeOverlay@IRONCURTAIN2:
		Palette: highlight
		RequiresCondition: invulnerability2 && !invulnerability4
	UpgradeOverlay@IRONCURTAIN4:
		Palette: shadow
		RequiresCondition: invulnerability4
	DamageMultiplier@IRONCURTAIN:
		RequiresCondition: invulnerability
		Modifier: 0
	TimedConditionBar:
		Condition: invulnerability
	ExternalConditions@INVULNERABILITY:
		Conditions: invulnerability
	StackedCondition@INVULNERABILITY:
		Condition: invulnerability
		StackedConditions: invulnerability2, , invulnerability4
```

### CODE REVIEW

**Review by Micr0Bit — COMMENTED** [review]
Testcase worked for me without any problems :+1:

**Review by GraionDilach — APPROVED** [review]
The commit order seems that the attribute commit is preceded by the actual usage case, but the result works so :+1:.

**Comment by pchote** [comment]
> The commit order seems that the attribute commit is preceded by the actual usage case

This is just github's long running PR commit-display-ordering bug.  They'll be the right way around when merged.

**Review by phrohdoh — APPROVED** [review]
LGTM and the provided test-case worked on 47a013e6c2c29715eabcb31d3d1fce70386a008b so :+1:

@pchote, upon merge would you add an entry to the conditions (maybe still "upgrades") wiki page mentioning this?

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d1be22afa490eabce446ece09ef81139e807e970...6c455ff83fe7d81be0d1bde53cc75a5ae22ea93e)

**Pull request merged**
