### PR TITLE
Fixed deployed vehicles being treated as buildings

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/8521.

### CODE REVIEW

**Comment by GraionDilach** [comment]
You should do this same with GAARTY.

**Comment by Mailaender** [comment]
Indeed. Updated.

**Comment by GraionDilach** [comment]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me, too. :+1: / :white_check_mark:

**Pull request merged**
