### PR TITLE
Render UI and multiple sheets without breaking the batch.

### PR DESCRIPTION
**Pull request by pchote**
This PR follows on from #15149 by merging RGBA sprite rendering into the same shader as normal sprites and colors, and then takes a much more dramatic step for reducing batch breakage by managing 8 parallel texture bindings (limited by our minspec gfx target).

This gives a significant performance win for the UI, especially in the lobby where we are constantly switching between rendering images and text.  This also helps a lot in TS, where the ingame sprites don't fit within a single sheet.

This also disables the requirement that depth sprites must live on the same sheet as the sprite it is attached to, which simplifies our sequence and sprite building code. 

Some numbers from my laptop, with #15177 disabled in order to disambiguate the render times from tick:

| **Testcase**                           |  **Bleed**                       | **This PR**                |
| ----------------------------- | ------------------------ | -------------------- |
| TS Shellmap                           | ~18-20ms, 220 batches | ~5-6ms, 35 batches |
| TS lobby (Drawbridges map) | ~29-30ms, 315 batches | ~6-7ms, 38 batches |
| RA map selector                    | ~14-15ms, 210 batches   | ~4-5ms, 11 batches  |

### CODE REVIEW

**Comment by GraionDilach** [comment]
>This also disables the requirement that depth sprites must live on the same sheet as the sprite it is attached to, which simplifies our sequence and sprite building code.

Pinging @ABrandau for interest.

**Comment by GraionDilach** [comment]
Care to elaborate on that minspec gfx target limit - asin where that limit comes from? Is it from the OpenGL specification?

**Comment by pchote** [comment]
8 comes from the Raspberry Pi, which is my main motivation for working on these optimizations right now.  Pretty much all proper hardware that we care about support between 16 and 192 units [[ref](http://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB)].

**Comment by Sininini** [comment]
Looks like a major improvement, thanks a lot! Also thanks to RoosterDragon for the separate render thread as well.

**Comment by MunWolf** [comment]
@pchote You could try and query OpenGL how many it supports so you can try to lift the number of sheets higher then 8.
Not sure how important it is for performance, depends mostly on how many textures we have, are we sorting them before rendering etc.

**Comment by GraionDilach** [comment]
I was asking out of interest alone, even 8 textures are more than 1 and any improvement is better over no improvement afterall. Thanks for the list, it was really interesting to look at.

**Comment by chrisforbes** [comment]
Nak to dynamic array size tricks. Working my way through the actual change now.

**Review by chrisforbes — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]
Don't know if you changed something major since the earlier revision I tested, but batch reduction and and worst-case render ticks improved by another order of magnitude since then 👍 Didn't come across any issues, either 👍

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6185b02a47c13c256b51befda73ddac3653637cf...078b6d8feeaa06a128908b9a59b36c13ef1973c7

**Comment by ABrandau** [comment]
I updated my mods yesterday, and I want to share the results.

On Shattered Paradise the amount of batches reduced from 300 when zooming out a map to 30, on the earlier version the amount of batches would increase with less zoom, but this is not the case anymore, so it remains around 30 all the time. I will hand the build to an user who didnt had a high end PC to see if there are any improvements when playing.

On Nomad Galaxy the perf improvement isnt that noticeable because there isnt much content, but one thing that calls my attention is that my laptop ventilator isnt running at full speed when testing anymore, thats a nice change, thanks.

**Pull request merged**
