### PR TITLE
UpgradeManager after IUpgradables

### LINKED ISSUE #8444: Elite weapon(s) in TS broken
I don't know yet whether this is a yaml or code issue, but in any case elite weapons don't work.

The Nod bike should get the HoverMissile @ elite, but it doesn't.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21036885-elite-weapon-s-in-ts-broken?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by atlimit8**
Fixes #8444 as a consequence.

### CODE REVIEW

**Comment by atlimit8** [comment]
Someone should check to see if @matija-hustic is correct in #8444 by checking it against this.

**Comment by GraionDilach** [comment]
My elite Armaments work wonderfully with this.

**Comment by penev92** [comment]
Will this wait for *all* traits that implement `IUpgradableInfo` to be initialized before it initializes `UpgradeManager`, or would one of those suffice?

**Comment by atlimit8** [comment]
`ActorInfo.TraitsInConstructOrder` sorts required traits before, so it should unless their is a bug.

**Pull request merged**
