### PR TITLE
Remove ruleset cache

### PR DESCRIPTION
**Pull request by pchote**
This removes the RulesetCache in favour of a simpler and more perf/memory predictable loading setup:
- The default rules are initialized during the initial load, and stay in memory until mod-exit.
- Custom map rules will always be parsed when loading the map.  Any default sections will use the defaults.
- (after #10901) MapPreviews will cache their custom rules themselves.

The parsing is now done on a background thread, which lets us animate the load screen smoothly during the parsing (currently only ~1/3 – ~1/2 of the load screen duration for me).  I plan on pushing more loading tasks to background threads later.

Depends on #10902.

### CODE REVIEW

**Comment by abcdefg30** [comment]
```
OpenRA.Game/GameRules/Ruleset.cs:L87: [SA1001] Invalid spacing around the comma.
OpenRA.Game/GameRules/Ruleset.cs:L87: [SP2100] Code line must be no longer than 180 characters (now 196).

**Comment by pchote** [comment]
Fixed and rebased.

**Comment by obrakmann** [comment]
looks ok, :+1:

**Comment by abcdefg30** [comment]
:+1: Looks good to me, too.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/785755cd6a9d2820911ef09bac7e1e061c315a00...1ed0badf1b9b3c14b731e9252fea0248d3fb5ea9)

**Pull request merged**
