### PR TITLE
Fix the demo truck explosion not killing the initiator

### LINKED ISSUE #7327: dtrk - tsla bug
release-20141029
demo-truck is doing no damage on a enemy tesla-coil 
demo tesla

cant reproduce 

map is called "The Earth 2064" http://resource.openra.net/maps/1119
replay : https://www.dropbox.com/s/gxo3rpuh6q0k6lb/demo%20tesla%20bug.rep?dl=0
here is a screenshot for the exact time , and position ... on the map 

openra 2015-01-13 01-17-21-16

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7689981-dtrk-tsla-bug?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #7327.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5ecb15fe4dd725a92325b2f3e47c4e9a5354402d%5E...5ecb15fe4dd725a92325b2f3e47c4e9a5354402d)

**Comment by deniz1a** [comment]
This is still persistant in current bleed. The initiator gets damage but it's much less than what a normal unit gets.

**Pull request merged**
