### PR TITLE
Removes Spy's ability to disguise as Attack Dog or Giant Ant.

### LINKED ISSUE #7478: Remove spy's ability to disguise as a dog
Does he wear a dog costume?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8592049-remove-spy-s-ability-to-disguise-as-a-dog?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by deniz1a**
Fixes #7478. Also currently when spy disguises as giant ant, it has glitchy idle animation.

### CODE REVIEW

**Comment by Unit158** [comment]
:-1:
There's no balance issue related to this that is fixed, and it provides an unnecessary step away from the original. Also, I like dog spies.

**Comment by deniz1a** [comment]
What do you like about them?

**Comment by Mailaender** [comment]
:+1: works as promised and I see it as nice polish. It is also a usability improvement as you now don't need to force fire on guard dogs.

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark: 
I actually also like spy disguised as dog. But got conviced by
> 15:58 (deniz1a) spy also moves like a dog when he disguises.. so it's like he becomes a dog

which is really a bit ridiculous.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ffc56c8d1183632060de5b6fd96eb09c3c8dcb49...213aefdd503ed8606930f1f5065aa12f80f0aa83)

**Pull request merged**
