### PR TITLE
Upgrades overhaul part 4a: Lua API

### PR DESCRIPTION
**Pull request by pchote**
Depends on #12406.

### CODE REVIEW

**Comment by pchote** [comment]
Rebased and ready to review.

**Comment by reaperrr** [comment]
Something seems to be broken, allied actors on RA shellmap are killable. Also needs rebase.

**Comment by pchote** [comment]
Rebased and fixed the shellmap external condition lists.

**Review by obrakmann — APPROVED** [review]
Looks fine to me, 👍

**Comment by pchote** [comment]
Fixed and rebased.

**Comment by Phrohdoh** [comment]
Did I miss `UpgradeManager` being renamed or is that coming in a later PR?

**Comment by pchote** [comment]
That will come in part 5.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by abcdefg30** [comment]
Why do we throw `InvalidDataException`s instead of `LuaException`s?

**Comment by pchote** [comment]
Dunno, I didn't change that (github hasn't tracked the file rename, show it shows up as a deletion and separate addition).

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f2bc3962fcf89a42e0989239f847006b46accafa)

**Pull request merged**
