### PR TITLE
Skip non-existing player references

### LINKED ISSUE #9364: OpenRA.Mods.Common.Traits.EditorActorLayer.Add KeyNotFoundException
(playtest 20150830)
I just experienced a crash while I was playing around in the (RA) editor:
exception.log  - http://pastebin.com/xEzGHNxr
At the time I was trying to place a spawn point for a player labeled in the dropdown menu as "Multi0". It was a new, blank, 64x64 temperat map. I previously placed and erased some "Creeps" buildings.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26773781-openra-mods-common-traits-editoractorlayer-add-keynotfoundexception?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LipkeGu**
fixes #9364

### CODE REVIEW

**Comment by pchote** [comment]
The proper fix for #9364 is to update the selected player reference when the underlying players change.  This just bandaids the crash.

**Comment by LipkeGu** [comment]
You mean i should Add the Reference back? in this case on this position?

**Comment by penev92** [comment]
No, you should remove it from the dropdown.

**Comment by LipkeGu** [comment]
where can i find the connection to the Drop down?

**Comment by Mailaender** [comment]
It is not so easy anymore with the way @pchote refactored my map editor code. `EditorActorLayer.SyncMultiplayerCount()` does the player adding and removal, but `ActorSelectorLogic.ownersDropDown` is the one which needs an update now.

**Comment by pchote** [comment]
Sure it is. Add a <X>Changed event for the player ref collection, and then have the sidebar code adjust itself.

**Comment by pchote** [comment]
Closing stale pr, since this needs a total rewrite rather than just a small modification.

**Pull request closed without merging**
