### PR TITLE
Fix Defend stance auto-targeting naval structures.

### LINKED ISSUE #14118: Units in Defend stance auto-target SPEN/SYRD

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14118.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Review by Smittytron — APPROVED** [review]
Subs will auto-fire naval structures in defense stance but that looks like a different matter.

**Comment by pchote** [comment]
Fixed submarine autotargeting and rebased.

**Comment by reaperrr** [comment]
@Smittytron can you confirm the updated version fixes that auto-fire issue?

**Review by abcdefg30 — APPROVED** [review]
Looks still good to me.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/41b84e862825de63a10f334ce8838b002a28968c...d0f9e819fd1ce7130f8a7e0cb4c90e01389133f7

**Pull request merged**
