### PR TITLE
Allow Chinook to land/deploy on gems

### PR DESCRIPTION
**Pull request by HenrytheSlav**
As reported in #10291.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/57f68cb5a410b1f2ae0d95f8c342c5d03350f70d)

**Comment by Micr0Bit** [comment]
thanks a lot @HenrytheSlav

**Pull request merged**
