### PR TITLE
Fix self-healing percentage in yaml rules for all mods

### PR DESCRIPTION
**Pull request by obrakmann**
From https://redd.it/4hgzd3

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by HenrytheSlav** [comment]
:+1:

**Comment by abcdefg30** [comment]
:+1:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/57f68cb5a410b1f2ae0d95f8c342c5d03350f70d...d65776ef73d94dbd0b31ba69b670bd3284c9d931)

**Pull request merged**
