### PR TITLE
Add IsDead check to FerryUnit OnFirstRun

### PR DESCRIPTION
**Pull request by teinarss**
Fixes the crash reported in https://github.com/OpenRA/OpenRA/pull/17076#issuecomment-554790649

### CODE REVIEW

**Comment by abcdefg30** [comment]
Do you have a reproduction case?

**Comment by teinarss** [comment]
Check the replay in the linked comment :)

**Review by tovl — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7c5948e5bcc4ca1b18a0097843203824ea2d2f5a...3b43f321538d95351cd0c86e15289bb9a5af0a6c

**Comment by pchote** [comment]
This hasn't been picked to prep yet. Should we, considering #17500?

**Comment by reaperrr** [comment]
Yeah, I think so.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fcabba7d761d6e89e03a8c83d68793e9e1d9f5f7...50b8c88a27c1fecb5512fe8b54564f8141da73ac

844da26

**Pull request merged**
