### PR TITLE
Fixed Tiberian Sun radar dishes

### PR DESCRIPTION
**Pull request by Mailaender**
as exhibited in https://github.com/OpenRA/OpenRA/issues/5272#issuecomment-77744521.

### CODE REVIEW

**Comment by pchote** [comment]
Why were these commented out originally?

**Comment by pchote** [comment]
This shows both the normal dish and the destroyed one, which surely isn't right?

screen shot 2015-03-08 at 21 11 17

**Comment by Mailaender** [comment]
I probably did not understand the concept of hiding the dish. It does not work in your branch (so I guess you sequence replacement is not working correctly). Try building a radar and damaging it.

**Comment by reaperrr** [comment]
I believe it was me who commented them out.
The reason is that the 3rd frame (critical) of the main shp shows a destroyed dish, unlike the damaged and undamaged one. This cannot be fixed without modifying the art. The radars aren't meant to have an animated dish at the 3rd (critical) damage stage, only at the first two (undamaged and damaged).

**Comment by LipkeGu** [comment]
It seems these are animations which was taken over from the Beta version of the GDI Radar... which was mainly the "Radar+Upgrade centre" :/

**Comment by Mailaender** [comment]
You will notice that that this branch corrects this if you test it properly. The critical damage state will show a destroyed dished and hide the animation as it points to transparent frames.

**Comment by pchote** [comment]
This is also a problem for map-placed radars in temperate maps.  Something else is going on here...

screen shot 2015-03-10 at 17 50 45

**Comment by pchote** [comment]
`WithIdleOverlay` does not account for the initial damage state.  Apply the following to fix this:
```diff
diff --git a/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs b/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs
index 0b67e17..c8f0e5c 100644
--- a/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs
+++ b/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs
@@ -74,6 +74,9 @@ public WithIdleOverlay(Actor self, WithIdleOverlayInfo info)
 		public void BuildingComplete(Actor self)
 		{
 			buildComplete = true;
+
+			// Account for initial health
+			overlay.ReplaceAnim(RenderSprites.NormalizeSequence(overlay, self.GetDamageState(), overlay.CurrentSequence.Name));
 		}
 
 		public void Sold(Actor self) { }
```

**Comment by pchote** [comment]
Actually, a better alternative would be to use `NormalizeSequence` in the constructor.  The damage event will still fire during the make animation etc.

**Comment by Mailaender** [comment]
Fixed.

**Comment by reaperrr** [comment]
This works as intended now, so in that regard it gets my :+1: 

However, after testing it ingame, I'd say we should use the 3rd damage state graphics only as death animation like in RA/TD, in critical condition the radars look pretty destroyed to me.
This is actually true for nearly all buildings, though, so I guess that should be dealt with in a separate PR.

**Comment by obrakmann** [comment]
Well, I can confirm that the third damage state is now seen in-game, so :+1: 

I agree with everything reaperrr said, though. That thing should not be operational anymore in that state.

**Comment by Mailaender** [comment]
We could also use the critical state for building husks.

**Pull request merged**
