### PR TITLE
D2K - Add Habbanya Ridge to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
A map from the original game. 2 Player.

Edit: http://resource.openra.net/maps/18357/

### CODE REVIEW

**Comment by reaperrr** [comment]
Could you move the top-right spawnpoint down by 2 or 3 cells? It's a bit close to the map border compared to the bottom-left spawn.

Looks good to me otherwise 👍

**Comment by MustaphaTR** [comment]
Updated.

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/05e6023815a34b91acd62ebbd97e707810925371...1185177778b4541f6871dc3294b55a493f336201)

**Pull request merged**
