### PR TITLE
Fixed a null reference exception in Reservable.UnReserve

### LINKED ISSUE #18801: A crash in Reservable, line 89
```
OpenRA engine version f41aa12
Shattered Paradise mod version SP-Playtest-20201021
on map 9e1cb657d4a7082f063c097d34c1b0f20b570e6a (Way to Uganda by Morton).
Date: 2020-11-01 08:46:46Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Traits.Reservable.<>c__DisplayClass8_0.<UnReserve>b__0() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Buildings\Reservable.cs: 89
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\AttackMoveActivity.cs: 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs: 120
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs: 35
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs: 267
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs: 466
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs: 606
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs: 632
   在 OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs: 797
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs: 838
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs: 274
   at OpenRA.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Support\Program.cs: 33
```

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/18801.

### CODE REVIEW

**Comment by dnqbob** [comment]
Hi, dude.

I think this problem may be somewhere else, crash still happens in replay when I test this fix.

The test modsdk branch is:
https://github.com/dnqbob/Shattered-Paradise-SDK/tree/eff-fix

The test engine for it 
(Note: it is not the rv-engine, it is the engine based on rv-engine including my AI fixes for new SP. You need to change the content in file VERSION for test):
https://github.com/dnqbob/OpenRA/tree/Fix-AI-airforce-scanning-RV

Deeply sorry for the inconvenient.

**Comment by dnqbob** [comment]
I think because I enable the AI resupply on repair pad so this bug happens more frequently.

**Comment by dnqbob** [comment]
[sp-2020-11-01T095049Z.zip](https://github.com/OpenRA/OpenRA/files/5475023/sp-2020-11-01T095049Z.zip)
If the fix can fix the bug then the crash won't happen at the end of replay (I don't know if use this method to test is sufficient and correct but I use it to debug some of the crash bug in OpenRA like the water check crash)

**Comment by Mailaender** [comment]
The replay was recorded with a version that crashes the game so the network stream is interrupted. You can't use it to get a game that carries on. If you know how to trigger the crash you can try that instead. I checked the stack trace. This is the only variable without a null check that can be null, so I am pretty confident of the proposed fix.

**Comment by dnqbob** [comment]
> The replay was recorded with a version that crashes the game so the network stream is interrupted. You can't use it to get a game that carries on. If you know how to trigger the crash you can try that instead. I checked the stack trace. This is the only variable without a null check that can be null, so I am pretty confident of the proposed fix.

going to have some proper tests tomorrow if you say so. 

Some of my crash debug used to be like:
1.  found the crash replay
2.  if it was still crash after fix, the fix failed
3.  if it stop at crash time,  but game is not crash, then the fix is successful

This method is crude but working on especially null check lacking (which will not change the main procedures), I use it on #18692 and works as my expectation. I don't know if it is sufficient or necessary condition or unrelated with the null-check crash fixing.

**Comment by dnqbob** [comment]
Maybe an useful idea.

**Comment by abcdefg30** [comment]
> I checked the stack trace. This is the only variable without a null check that can be null

The odd thing about the stack trace in #18801 is that line 89 seems to be called from `AttackMoveActivity` which leads me to believe the inner activity (`() => reservedForAircraft.MoveTo(cell, 1, targetLineColor: Color.OrangeRed))`) is somehow causing the crash. But I don't know what would be null there either.

**Comment by dnqbob** [comment]
Don't have time test it until 12 hours later. 
 
> The odd thing about the stack trace in #18801 is that line 89 seems to be called from `AttackMoveActivity` which leads me to believe the inner activity (`() => reservedForAircraft.MoveTo(cell, 1, targetLineColor: Color.OrangeRed))`) is somehow causing the crash. But I don't know what would be null there either.

I also think the problem is this inner activity but it is too strange. Can Cell be null? otherwise nothing can be null here.

**Comment by dnqbob** [comment]
This bug happens again when use the null check on `reservedFor`, this time is not the replay but game play:

Crash bug:
("未将对象引用设置到对象的实例" = "Object reference not set to an instance of an object")
bug

The fix I use (compiled by make.cmd):
engine

**Comment by dnqbob** [comment]
I am afraid this bug is beyond my understanding.

But we should also keep the null check for `reservedFor` here because it is better to have one here.

**Comment by dnqbob** [comment]
I will also do some check on my own AI related repair code.

upgrade:
```
						if (repairBuilding != null)
						{
							squad.Bot.QueueOrder(new Order(orderId, a, Target.FromActor(repairBuilding), orderQueued));
```

is this line can cause bug like that?

**Comment by abcdefg30** [comment]
Is there some way to reproduce this crash in our default TS mod?

**Comment by dnqbob** [comment]
> Is there some way to reproduce this crash in our default TS mod?

I will try #18039 after 3 hours (it needs a rebase to current bleed for test)

**Comment by Mailaender** [comment]
Okay, my fix is then invalidated.

**Comment by dnqbob** [comment]
> Okay, my fix is then invalidated.

I will try find a way to reproduce this bug in upstream, which may help you to confirm here.

**Comment by Mailaender** [comment]
Saw nothing suspicous in https://github.com/Inq8/CAmod/blob/9c90ab4ff6a68fbd310e93047d055b01d25cd501/OpenRA.Mods.CA/Traits/BotModules/Squads/States/StateBaseCA.cs.

**Comment by dnqbob** [comment]
@Mailaender 
@abcdefg30 

I get a successful reproduction by using #18039. 
Already push the AI YAML change I used for test this bug to #18039, so you can use it directly reproduce this crash.
(You can keep the AI.yaml change if you want)

If you can debug this bug from replay, the file is here.
[ts-2020-11-03T130013Z.zip](https://github.com/OpenRA/OpenRA/files/5481389/ts-2020-11-03T130013Z.zip)

Other information, I skip the stack trace because it is the same as #18801:

```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map 28a09cab7f1ee45c4ea5b339c85ce41b3d5fb9c3 (Way to Uganda by Morton).
Date: 2020-11-03 13:06:34Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.4200
...
```

I use 2v2 AI on it so combat will last long enough for this bug.

**Comment by dnqbob** [comment]
[Logs.zip](https://github.com/OpenRA/OpenRA/files/5481432/Logs.zip)
First hand logs.

**Pull request closed without merging**
