### PR TITLE
Suppress error messages from make.ps1 clean.

### PR DESCRIPTION
**Pull request by pchote**
Fixes the issue noted in https://github.com/OpenRA/OpenRAModSDK/pull/170#discussion_r563296283.

### CODE REVIEW

**Comment by teinarss** [comment]
image

**Comment by teinarss** [comment]
From https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.1

**Comment by pchote** [comment]
> When it is used with the Include parameter, the Recurse parameter might not delete all subfolders or all child items. This is a known issue. As a workaround, try piping results of the Get-ChildItem -Recurse command to Remove-Item, as described in "Example 4" in this topic.

We're not using `-Include`, so should be fine?

**Review by abcdefg30 — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/51a5530974e5d6ef146d1eee54bcf309362837dd...4aea1da49d1c7491519121d9863876f34af2d760

d3482c0

**Pull request merged**
