### PR TITLE
Add a Demolish function to lua

### PR DESCRIPTION
**Pull request by abcdefg30**
Split from #8418 as wished by @Mailaender (https://github.com/OpenRA/OpenRA/pull/8418#discussion_r33413516).

This functionality has already one :+1: from @obrakmann (https://github.com/OpenRA/OpenRA/pull/8418#issuecomment-114541500).

### CODE REVIEW

**Comment by Mailaender** [comment]
You could add a test case in Allies05a so that Tanya blows up her prison when leaving.

**Comment by abcdefg30** [comment]
Added the testcase.

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/964442505583b4e0e94d8f47e17690960c45b787...da62830b04488d0e2e62abc2d1a0f48814128ffb)

**Pull request merged**
