### PR TITLE
Remove custom TD & D2k engineer selection priority

### LINKED ISSUE #11067: Remove lower selection priority for engineers in TD
I said on one of the original post that making a lower selection priority for engineers in TD would be counter-productive since they are used differently to everything in RA except the spy.
Could you please remove this from TD

### PR DESCRIPTION
**Pull request by reaperrr**
Closes #11067.

### CODE REVIEW

**Comment by obrakmann** [comment]
TBH, I'd do it for all the mods. It would suck if it worked one way in cnc and another way in the other mods. But that's just my opinion, maybe the players prefer it in RA.

**Comment by pchote** [comment]
I wasn't a fan of the original change, so I'd also support reverting the remaining parts of #10519.

**Comment by pchote** [comment]
I guess the RA engineers could be argued either way (since they work differently to other units), but could we revert the d2k engineers here for consistency?

**Comment by reaperrr** [comment]
Updated, reverted d2k engineers as well.

**Comment by Mailaender** [comment]
The back and forth is a bit ridiculous, but anyway this should  be safe.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/04d270cec2f5df7524a83654568b801b0153596f...b67f0e84ec192194534fa9a746446a70f2d4ddbf)

**Pull request merged**
