### PR TITLE
Cold front fix

### PR DESCRIPTION
**Pull request by ghost**
http://resource.openra.net/maps/14034/

Fixed erroneous sporadic ore cell placement and a tiling error. Once the main ore patch at north spawn has been mined, the two largest red circled areas will each idle ore trucks if left unnoticed. Removed some other erroneous ore placement.

Also renamed the map from `cold-front-1v1` to `dual-cold-front` to match the in-game name for consistency.

cf

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
@SoScared you might want to see this since it is 1) GL map and 2) since you are working on refreshing the map pool anyway.

**Comment by SoScared** [comment]
oh yeah. I had quite a bit of ore to remove from the original 3v3 map. sorry I missed that.

rouge ore trucks would be a problem for balance. I'll have to distribute http://resource.openra.net/maps/14034/ for the league in the meantime.

**Comment by Mailaender** [comment]
:+1:

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/2eb0276da0bf1c49f3f1c9fd78c424787b9f9c2d...43f89057d894231ed30e09f45d071e6587882879)

**Pull request merged**
