### PR TITLE
Actor.TraitsImplementing<T>() LINQ specialization & exceptions

### PR DESCRIPTION
**Pull request by atlimit8**
This leaves the LINQ queries as is, but provides `ITraitEnumberable<T>` which allows for specialization of `Where`, `ToList`, `ToArray`, `First[OrDefault]`, `Any`, `All`, and `Single[OrDefault]`. These specializations usually use one less `IEnumerator` and at most one array allocation for `ToList` & `ToArray` except for `.Where(...).ToArray()` which usually uses two array allocations. The `First` & `Single` specializations provide clearer exception messages as well.

### CODE REVIEW

**Comment by atlimit8** [comment]
I added actor trait helpers.

**Comment by RoosterDragon** [comment]
Aside from the exception messages, is this intended purely as allocation reduction? The amount of bytes allocated from these methods is negligible in terms of our overall allocations. From that perspective it would seem like a lot of code that's not winning us much back in terms of value.

**Comment by pchote** [comment]
@atlimit8: Can you please clarify this PR with regards to @RoosterDragon's question?

**Comment by RoosterDragon** [comment]
@atlimit8: Going to close this for now. If you have some numbers that back this up, feel free to reopen it.

**Pull request closed without merging**
