### PR TITLE
Refresh new/updated maps in lobby #3483

### PR DESCRIPTION
**Pull request by rob-v**
Added 'Refresh' button to lobby map browser to refresh new/updated maps.

### CODE REVIEW

**Comment by pchote** [comment]
Pressing the refresh button causes the game to stall while the enumeration is done on the main thread – this is bad.

Personally, I don't like the idea of devoting UI to such a niche feature.  Players shouldn't expect modifications that they make to the map pool to be applied in real time - what games support this?

**Comment by rob-v** [comment]
The issue could be partially resolved (another thread, progress indication like when refreshing servers), but as you prefer. I don't remember a game with such support.

**Comment by kyrreso** [comment]
If this is cancelled with UI in mind, then at least we can have a secret key-combo. Restarting Openra takes time, and many times the auto-download does not work. Then this would be helpful.

**Comment by pchote** [comment]
@ScottNZ's suggestion of having a file system watcher automatically add new maps without requring a manual reenumeration would fix that.

**Comment by rob-v** [comment]
If it works properly on all systems.. It is more work, would run in background, though rarely needed to have new maps loaded outside Map browser. I don't think it is worth the effort at this moment, but as you prefer. In such case let's close this PR.

**Pull request closed without merging**
