### PR TITLE
Added map Grassy Knoll

### PR DESCRIPTION
**Pull request by Mailaender**
Another map that should be not too fancy #12518 and playable already. First map to add `CAHOSP` and `CAARMR`. http://resource.openra.net/maps/22847/

### CODE REVIEW

**Comment by pchote** [comment]
This one has destroyable cliffs too.

**Comment by Mailaender** [comment]
Many maps we already have imported have it. On this map, it doesn't seem to be that important.

**Comment by pchote** [comment]
The point is that it's not fair for us to have to re-review all of these map additions again in the future for the sake of not wanting to spend 20 minutes fixing the importer now.

**Comment by reaperrr** [comment]
I have to agree with @pchote here.
Fixing the importer before (re-)importing those maps would save us some future work both on the reviewer side and on the side of whoever will update the maps with proper destroyable cliffs.

Ideally, we should also properly implement destroyable cliffs first before importing any more maps that have them, because the best-case scenario would be if we only need to import them once and then never have to touch them again (unless for balancing reasons once the mod is public).

I think our current TS map pool is sufficient at this stage, maybe one more FS 2-player map (provided it has no destructible cliffs) and we have a solid mix of small, medium and large maps that shouldn't need additions for quite a while.

**Comment by pchote** [comment]
#14046

**Comment by reaperrr** [comment]
Out of the 3 maps, this is the only one where merging it would be ok in my eyes, *if* it is reimported with current state #14046 first (i.e. replace destroyable cliffs with normal ramps).

The 2 destroyable cliffs seem relatively redundant on this map (considering how easy they were to destroy in the original), so taking it with normal ramps and leaving a possible re-import to a late stage of polishing would be fine with me.

@Mailaender I leave it up to you whether you want to reimport the map now, or would rather close the PR and wait for a proper solution to the cliff issue.

**Comment by Mailaender** [comment]
Sorry, I probably added way too many at once. Also with linter performance #13533 in mind, I better not add more stuff.

**Pull request closed without merging**
