### PR TITLE
Fix cloak sounds playing on build for initially cloaked actors.

### LINKED ISSUE #13169: Submarines play their Uncloak sound at the start of a map

### PR DESCRIPTION
**Pull request by pchote**
Fixes #13169.

### CODE REVIEW

**Comment by rob-v** [comment]
👍

**Comment by pchote** [comment]
I'll just note that I don't consider this to be the final long-term fix, because we still have a 1 tick delay between creation and the `CloakedCondition` being granted.  The proper fix will be to rework the granting/revoking logic to support being called during actor creation, but that is too big of a change to risk for the bugfix release.

**Review by GraionDilach — APPROVED** [review]
LGTM then.

**Comment by GraionDilach** [comment]
Although I wouldn't close the original ticket with this to make sure it won't get overlooked.

**Comment by pchote** [comment]
The original ticket is specifically about the cloak sound, so I'd prefer to close that with this pr then make a new one about the condition granting.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a633fe85bdd7060ac1f4f1ebcfb9510060f00eb7...b582448a1a0a085d55b2390b6e84b01dc10ff468

**Pull request merged**
