### PR TITLE
Add missing target lines.

### LINKED ISSUE #16884: RTB orders are missing target lines
On bleed, the target lines are

- not displayed (also not when pressing shift) when giving an RTB order while the aircraft has full ammo
- are updated while target lines from a preceding order are still displayed or displayed when pressing shift, provided the aircraft can rearm.

It would be nice to know where the units are heading after the RTB order.

### LINKED ISSUE #16898: Target lines are not shown for units coming out of production buildings
a green line is shown one cell away from a production building but then the following attack move line is missing

### PR DESCRIPTION
**Pull request by tovl**
Fixes #16884 
Fixes #16898

### CODE REVIEW

**Comment by pchote** [comment]
There are several other places where `AttackMove` is queued without defining a target line: `ProductionParadrop`, `TakeOff`, `Hunt`, and the Lua APIs for queueing attack move / hunt.

**Comment by tovl** [comment]
Added the lines for `TakeOff` and `ProductionParadrop`. I'm not sure it makes much sense to show target lines for scripted actions or `Hunt` since these are never directly controlled by the player. Showing the randomly appearing one-cell lines for hunting creeps just looks weird.

**Review by ghost — COMMENTED** [review]
The target lines are fixed for RTB orders and for ground and naval units that leave their production facility (including `ProductionAirdrop`). I noticed that unarmed units also show a red a-move target line although you can't order them to a-move, just as a side note.

For planes and helicopters, no target lines are displayed when they take off and approach the rally point.

I don't know how to test `ProductionParadrop`.

**Comment by tovl** [comment]
> For planes and helicopters, no target lines are displayed when they take off and approach the rally point.

That seems like a logical consequence of #16912 rather than a problem with the target lines themselves.

> I noticed that unarmed units also show a red a-move target line although you can't order them to a-move, just as a side note.

That is indeed a bit odd, but I don't know what would be correct in this case. They are given AttackMove orders like all other units, but without a valid attack this is functionally equivalent to a normal Move. Does this need to be addressed here?

**Comment by matjaeck** [comment]
> That seems like a logical consequence of #16912 rather than a problem with the target lines themselves.

Note that this issue only applies to airfields, not to helipads (but helicopters also miss target lines when approaching the rally point).

**Comment by tovl** [comment]
Updated with fix for helicopters.

**Review by ghost — APPROVED** [review]
LGTM.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0adc1eff59274bc68181aa57f1c2c98d64321698...9abb49db75857df0427e46a4408db691f33c63c3)

**Pull request merged**
