### PR TITLE
Fix #17229: Refactor ReturnToBase.cs

### LINKED ISSUE #17229: Returning planes have a hardcoded facing of 192 for landing.
https://github.com/OpenRA/OpenRA/blob/801f5ba525f184299c3215bbab4b119055bb7de8/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs#L116-L119

There's no need for that latter if check - `InitialFacing` could be used for both.

### PR DESCRIPTION
**Pull request by abmyii**
Fixes #17229.

### CODE REVIEW

**Comment by reaperrr** [comment]
Thanks for filing a PR, @abmyii !
However, since the internal default for `InitialFacing` is 0, this will at least need an update rule that lists and warns the modder about any non-VTOL that doesn't explicitly define an `InitialFacing`, and the MiG and Yak in our RA mod likely need an explicit `InitialFacing: 192` to work correctly with this change.

**Comment by abmyii** [comment]
@reaperrr I'm quite new to the internal workings of OpenRA so I've a few questions:
I expect the modder warning would go in a log. If so which? As for the `InitialFacing: 192` setting, that would go into the yaml file(s) under the MiG and Yak section, correct?
Thank you!

**Comment by abmyii** [comment]
I hope that's correct!

**Comment by matjaeck** [comment]
Unfortunately not. Are you sure you can handle this on your own? Fwiw, I decided a while ago that I can support the project more effectively by helping people who have the skills and knowledge I'm lacking, by testing their changes (pick one of the other 72 PRs) for example. That's not as satisfying as getting your own code merged (and also won't get you a t-shirt) but these things shouldn't matter anyway if you truly want to contribute. Just my personal opinion ofc.

**Comment by abmyii** [comment]
I understand what you meant, and of course it isn't black-and-white. I'm not familiar with the engine yet and I'm not too proud to ask for help where I am going wrong. I'd appreciate it very much if you could give me a few pointers as to how to correctly implement this PR. About the shirt then that is news to me - I submitted the PR primarily because I enjoy playing around with code. Thank you very much!

**Comment by abmyii** [comment]
Ah I see - @reaperrr I noticed that `InitialFacing: 192` is already set in both under the `Aircraft` section. Does that need to be changed as per your instructions above of setting them explicitly or is that what you were suggesting to be done?

**Comment by abcdefg30** [comment]
`OpenRA.Utility.exe <mod> --update-mod RemoveInitialFacingHardcoding --apply` should do the trick (run without `--apply` to just see the description).

**Comment by abmyii** [comment]
Thanks @abcdefg30, that worked! I ran the command and it seems to work as intended.
@reaperrr Which other changes would you like me to make?

**Comment by abcdefg30** [comment]
It would be good if you could squash the first 3 commits together, to keep the history clean.

**Comment by abmyii** [comment]
All right, done! Anything else?

**Comment by abcdefg30** [comment]
Ah yes, I just noticed we forgot to add the rule to the update path. Can you please add `new RemoveInitialFacingHardcoding(),` below https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/UpdateRules/UpdatePath.cs#L144 ?

**Comment by abmyii** [comment]
Should I do that as part of the same commit?

**Comment by abcdefg30** [comment]
Yes, please.

**Comment by abmyii** [comment]
Done.

**Review by abcdefg30 — APPROVED** [review]
Thanks. Code changes look good to me, Yaks and MiGs still behave properly on a quick test and the update rule works.

**Comment by abmyii** [comment]
Great! I expect the label means that the PR requires two more reviews to be merged?

**Comment by abcdefg30** [comment]
It means one more review is required, yes. We have the policy of having at least 4 eyes review the code and behaviour (making it 6 eyes in total, assuming no pirates) to reduce the regression risk.

**Comment by abmyii** [comment]
Haha - pirates! No problem, just wondering. I guess I'm done from my side for now. Thanks for all your help!

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/38190cfd1f7d9de62ee5c0845363748ce73e05a0...9638c127b43451277b42ae5d7254a7ceec71fa4c

**Pull request merged**
