### PR TITLE
Fix the IonCannonPower not playing all launch sounds

### PR DESCRIPTION
**Pull request by abcdefg30**
Depends on #11989, but doesn't necessarily need to go into stable, I think.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Rebased.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
Looks good to me, but it would be nice if you used `OnFireSound` (or weapon `Report`, doesn't really matter) to play the sound for TS' ion cannon as well (filename is `ion1.aud`, too).

**Comment by reaperrr** [comment]
Ignore my previous comment, the reason the sound isn't playing in TS is a simple typo on the relevant effect warhead, I'll fix that myself in an upcoming PR.

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ae9b997a613ec0fff31d657a559e4c5c2efc0552)

**Pull request merged**
