### PR TITLE
Work around a hang on shutdown caused by IRC

### LINKED ISSUE #9869: Connecting to Global IRC chat causes closing OpenRA to hang
So I discovered that if at any point I connect to the global IRC chat, quitting OpenRA will hang and It'll either take 10s+ to close or I'll need to ctrl+alt+del and force close the game. If I just watch a replay though I don't have this issue and the game closes normally.

This is on the Halloween playtest, while using Windows 7.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27901724-connecting-to-global-irc-chat-causes-closing-openra-to-hang?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by RoosterDragon**
Our IRC client doesn't shut down properly - but we only need to shut it down when we're about to close the game anyway, so we just don't bother since it won't hurt anybody.

Fixes #9869.

### CODE REVIEW

**Comment by GraionDilach** [comment]
```
OpenRA.Game/GlobalChat.cs:L371: [SP2000] Invalid spacing at the end of the line.
OpenRA.Game/GlobalChat.cs:L374: [SP2000] Invalid spacing at the end of the line.
```

**Comment by pchote** [comment]
Looks fine to me, but it sucks that we have to do this.  Thanks for including the detailed comment. :+1:

**Comment by obrakmann** [comment]
I'll take the comment for face-value and believe that it works, and penev says it fixes it, too. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/40a99591930c75f87f0041f4cf85e5eda9a7035e)

**Pull request merged**
