### PR TITLE
Fix bad behaver on InterpretServerOrders

### LINKED ISSUE #7515: Dedicated server NullReferenceException
Got this exception in my logs, server crashed.

```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Network.Session+<PingFromClient>c__AnonStorey2.<>m__0 (OpenRA.Network.ClientPing p) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Single[ClientPing] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.SingleOrDefault[ClientPing] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.Session.PingFromClient (OpenRA.Network.Client client) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.<Server>m__0 (System.Object _) [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.Session+<PingFromClient>c__AnonStorey2.<>m__0 (OpenRA.Network.ClientPing p) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Single[ClientPing] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.SingleOrDefault[ClientPing] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.Session.PingFromClient (OpenRA.Network.Client client) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server.<Server>m__0 (System.Object _) [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8785468-dedicated-server-nullreferenceexception?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LipkeGu**
fixes #7515

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: This is very likely to fix the NRE suspected in line

```csharp
var pingFromClient = LobbyInfo.PingFromClient(GetClient(conn));
```

**Comment by RoosterDragon** [comment]
It doesn't look like ```conn``` can ever become null to me - the caller verifies it as not-null before calling the method.

**Comment by Mailaender** [comment]
We have those `conn == null` checks on multiple occasions in the source code so I thought it may also be necessary here. Any idea what else causes https://github.com/OpenRA/OpenRA/issues/7515?

**Comment by RoosterDragon** [comment]
I'm not going to claim to know enough to answer that. My assumption is that the null check on the socket is what actually fixes it - but LipkeGu would have to explain it.

**Comment by LipkeGu** [comment]
My Idea was to check both so we doesnt take the null socket down to other functions, so i choosed that existing if function to check if conn and conn.socket is not null...

**Comment by huwpascoe** [comment]
As far as I understand from involvement with the protocol, there are 3 places where sockets are used: 

```Network.Connection.Connection()``` connection thread body is inline here
```Server.Connection.ReadDataInner(Server)``` which is referenced in ReadData(Server) then called from the server thread.
```Server.SendData(Socket, byte[])``` for some reason declared as a static member.

**Comment by RoosterDragon** [comment]
Ok I don't think this PR will affect anything:
- ```conn``` cannot be null here, it is verified as not-null by the only caller of this method.
- ```conn.Socket``` is only assigned in one place, ```Server.AcceptConnection```, where it is set to the value of ```TcpListener.AcceptSocket()```. This is a framework method that does not appear to have any reason to return null. The ```Connection``` class is only ever instantiated here too, so ```Socket``` will never be left in its default null state.

Unless I'm missing something here, this extra null checks here are pointless.

**Comment by penev92** [comment]
Why not just put a `try/catch` over the whole iffy area and be done with it?
Won't be bad for performance and will have a better chance of preventing the crashes.

**Comment by RoosterDragon** [comment]
That doesn't fix the issue, that's just ignoring it and hoping something else won't react badly instead.

**Comment by penev92** [comment]
Still, a seemingly highly volatile class like that should have a few catches, instead of crashing the game.

**Comment by RoosterDragon** [comment]
That only works if we know we can safely ignore the error.

If we don't what's causing the error then we can't trust our process to be in a reasonable state if some random exception occurs. Our process may very well be beyond any hope of running correctly again so there's no point trying to keep it alive - much better to crash early and hopefully get a stack trace close to the source of the real problem.

**Comment by huwpascoe** [comment]
The entire network set is made of many try-catch bandaids over a confused attempt at multithreaded networking, which hasn't been changed since the beginning of the project. Adding more bandaids to the pile isn't going to hurt much at this point so go ahead.

I'll keep trying to cram the new udp/protobuf code in the meantime, but it's a lot of work going through all that. Will be a while longer.

**Comment by pchote** [comment]
Thanks for the attempt @LipkeGu, but it sounds like the consensus here is to not take this.

**Pull request closed without merging**
