### PR TITLE
Added high quality Tiberian Dawn community maps

### PR DESCRIPTION
**Pull request by Mailaender**
I am a bit unhappy about the Tiberian Dawn map selection. There are a lot of maps lacking detail or innovation as they are just remakes of existing ones which add more spawns or a bit more surrounding terrain mostly from the same author. They also tend to be very symmetric to ease balancing which makes them look less interesting. We probably need to do a https://github.com/OpenRA/OpenRA/pull/4817 there as well when the time is right.

This adds some awesome community maps I found and test played with @abcdefg30, @obrakmann, @pchote and @penev92 or against random opponents. They seemed to also work out in terms of gameplay. Some also make use of the new JUNGLE tileset which adds some diversity. They are not too easy to find, because the resource site does not let you filter by mod yet https://github.com/OpenRA/OpenRA-Resources/issues/23 and there are a lot of RA maps in the repository.

Source:
- http://resource.openra.net/maps/2702/
- ~~http://resource.openra.net/maps/1652/~~
- ~~http://resource.openra.net/maps/2861/~~
- http://resource.openra.net/maps/1382/
- ~~http://resource.openra.net/maps/1449/~~
- http://resource.openra.net/maps/2647/
- http://resource.openra.net/maps/1403/
- http://resource.openra.net/maps/1375/

### CODE REVIEW

**Comment by abcdefg30** [comment]
:+1:

**Comment by pchote** [comment]
I don't like Braided River or Fumble in the Jungle (and to a lesser extent Morel Soup) because they are very visually cluttered, and full of choke points that will expose the worst behavior from our pathfinder.

I like all the others.

**Comment by Mailaender** [comment]
Removed the ones with too many obstacles.

**Comment by penev92** [comment]
How about version 2 ofhttp://resource.openra.net/maps/1382/ -  http://resource.openra.net/maps/1388/ ?

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/07df7436b23566883f369e4e542a34ba184c1879...464a3f9b89fc8b4cdc4c7213cb682ddb716d182e)

FWIW I liked http://resource.openra.net/maps/1449/   :/

**Pull request merged**
