### PR TITLE
Update BeaconLib to 1.0.1.

### LINKED ISSUE #13674: Crash when network is lost during game launch
I suspect there will be a timing aspect to this, because it doesn't crash when the game is launched with the network completely disabled.

```
OpenRA engine version playtest-20170722
Red Alert mod version playtest-20170722
on map 1a0958d85ff68f3964dc80664ab99e1d715d92be (Desert Shellmap by Scott_NZ).
Date: 2017-07-21 18:42:30Z
Operating System: OSX (Unix 16.6.0.0)
Runtime Version: Mono 5.0.1.1 (2017-02/5077205) CLR 4.0.30319.42000
Exception of type `System.Net.Sockets.SocketException`: Network is unreachable
  at System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEP) [0x00060] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Net.Sockets/Socket.cs:2046 
  at System.Net.Sockets.UdpClient.Send (System.Byte[] dgram, System.Int32 bytes, System.Net.IPEndPoint endPoint) [0x00061] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System/net/System/Net/Sockets/UDPClient.cs:531 
  at BeaconLib.Probe.BroadcastProbe () [0x0002a] in <b796f1ff1cd14a64968a1547282469c4>:0 
  at BeaconLib.Probe.BackgroundLoop () [0x00002] in <b796f1ff1cd14a64968a1547282469c4>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/thread.cs:68 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/thread.cs:105 
```

### PR DESCRIPTION
**Pull request by pchote**
Closes #13674.

### CODE REVIEW

**Review by rob-v — APPROVED** [review]
👍 

no practical reason? but it could be updated also here:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj#L44

**Comment by reaperrr** [comment]
from IRC: > [16:34] <+pchote> the specific version stuff should be removed

Best to do that with this PR so we don't have to file another one, in my opinion.

**Comment by pchote** [comment]
Done.

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a5ccf880cf4fb1a35e250c4e024dfbfcf54fa7c0)

**Pull request merged**
