### PR TITLE
Enabled debug mode by default on Linux launch scripts

### PR DESCRIPTION
**Pull request by Mailaender**
The performance overhead is minor and getting line numbers in stack traces is really valuable for development.

### CODE REVIEW

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by deleted-user-1** [comment]
> The performance overhead is minor 

Did you make any benchmarks or how do you know? Official mono docs say `running with –debug will slow down the execution.` I don't get why you needlessly risk regressing perf - which just got better this release - for all linux users, just to make your workflow easier. 99,9% of the users do not need the debug flag! Why did you introduce a vscode debugger extension in the sourcecode if this is not telling you line numbers?

**Comment by abcdefg30** [comment]
I suppose most people running the source code will be interested in running the debug mode. Users of releases (i.e. the people using the AppImages etc.) won't be affected by this as far as I know.

**Comment by deleted-user-1** [comment]
> the people using the AppImages etc.) won't be affected by this as far as I know.

I assumed that it affects packaging too or at least somehow mixed that up in my mind that I'd be using the script when playing.  It also says you'd need to compile using the debug flag btw.

**Comment by pchote** [comment]
For what its worth, the AppImages have *always* run with `--debug` enabled.

**Comment by deleted-user-1** [comment]
> For what its worth, the AppImages have _always_ run with `--debug` enabled.

And why is that a good thing?

**Pull request merged**
