### PR TITLE
Don't spawn aircraft husks when not airborne

### PR DESCRIPTION
**Pull request by abcdefg30**
As suggested by @GraionDilach in https://github.com/OpenRA/OpenRA/issues/13889#issuecomment-324155789.

### CODE REVIEW

**Comment by SoScared** [comment]
So if I understand this correctly, this also solves the trade-off (death vision on grounded units) with #13878.

**Review by SoScared — APPROVED** [review]
Tested this in combination with #13878

Grounded air units now explodes as-is instead of spawning a husk exploding in its place.

**Comment by ltem** [comment]
The `EjectOnGround: false` setting of `EjectOnDeath` trait won't prevent that a "landed" aircraft will randomly spawn an (instantly crushed) actor (it prevents that an actor gets spawned if a destroyed aircraft hits the ground). 

Is it possible to add a condition to prevent that?

|Crushed pilot|
|:---:|
|image|

**Comment by reaperrr** [comment]
@ltem Actually this was already fixed, but the fix was merged into bleed after this PR was created and it hasn't been rebased.
If you rebase your local copy of this branch onto bleed, you'll see no infantry is spawned anymore.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/98bc002f1b3c85396e15279e4d134151864ab1d6...2a261df49580c71b09886d666a80f87b5f7988ad

**Comment by ltem** [comment]
@reaperrr yep, you are right

**Pull request merged**
