### PR TITLE
Fix welding lights of Dune 2000 structures

### LINKED ISSUE #9641: Light factory production lights
[This video](https://www.youtube.com/watch?v=AEHRiRxCR9Q) shows the Light factory (at least the Atreides one, I haven't really investigated this) having production lights at the back. Seen between 2:16 and 2:20.
Our current factory has production lights only at the front.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27436066-light-factory-production-lights?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ltem**
This PR should fix #9641 

The only structure which is a bit off is the heavy factory of the mercenaries. All the other factions have 10 frames, mercenaries use 8. This is also the odd part of the heavy factory lights. In total they have 47 frames, but effective I only use 38 of them. Still it doesn't seem that there is anything missing.

For reviewing I would suggest either to check if there is something "off" during the animation or to compare it to the original game, what is quite time consuming but easier if you record your screen and replay it afterwards.

### CODE REVIEW

**Review by pchote — COMMENTED** [review]
Looks great overall, but I suspect that these animations should be split with the first 5 frames as `damaged-production-welding` and the second 5 as `production-welding`.  This is best seen with the atreides high tech factory, which has a set of windows fall down the side when damaged.  Would you mind verifying and if necessary fixing that?

**Comment by ltem** [comment]
I checked gruntmods and it seems that damaged building don't have any welding light sequences...just flames and smoke overlay for some ticks.

##### Two possibilities:
1. Remove the welding sequence from the damages part
2. Remove the parts of the welding sequence which look "off" if the building is damaged, this could be ugly

darp

**Comment by ltem** [comment]
I added special welding sequences for the damaged Atreides light factory and the Atreides high tech factory. The other factions don't seem to need that.

I also noted that a damaged outpost won't have a turning dish. I will try to implement that

**Comment by ltem** [comment]
Added dish animation fix, so it won't be played if the structure is too damaged. 

The reason for it was that 
1. If the outpost is damaged the animation will interfere with the picture of the structure
2. It was like that in the original D2K

If there are any urges to change the condition name, feel free to do so.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/addb9d22ef83c99b90a0d17c6edb3b01a67c1800

**Pull request merged**
