### PR TITLE
Remove GivesBounty>LevelMod

### LINKED ISSUE #14381: GivesBounty>LevelMod is calculated wrong
Currently it is increasing too quick. For ra mod (and default values), it goes from 10% on normal to 50% on 1 star. It is adding 125% (default value of LevelMod) on each level after first one, as can be seen at http://openra-red-alert.wikia.com/wiki/Veterancy

I think what should happen is either getting 125% of previous level's value (10-12,5-15,625-19,53125-24,414065) or 125% of original value (10-12,5-15,17,5-20). First makes more sense to me, but latter is more straightforward.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Closes #14381. Its effect can be recreated using conditions, as first commit fixes the issue with passengers having multipile GivesBounty traits.

I didn't do that to RA mod tho. I know we wanted to remove this for a while now. This will effect balancing so i would like to hear some words from people looking for these stuff too.

This probably needs a update rule, not sure if i can write a proper one or i should just add a notice but first seems less likely as it is a bit complicated.

### CODE REVIEW

**Review by Smittytron — APPROVED** [review]
Works as advertised. I agree with this method most as I stated in #14381.

**Comment by WhoCaresora** [comment]
I agree to remove extra bounty on vet units.

**Review by GraionDilach — APPROVED** [review]
:+1: but needs a followup/ticket to mention that passengers are killed without transferring damagetypes (and fixing that will require to update GetDisplayedBountyValue as well).

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0f0a43c52b359c2cd14cd34efe142861914dcf1f

**Pull request merged**
