### PR TITLE
Fix husks not updating targetable positions on teleport

### LINKED ISSUE #15329: Mechanics can remote repair chronoshifted husks

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #15329.

### CODE REVIEW

**Comment by pchote** [comment]
`HuskInfo` is missing `IPositionableInfo`, so this isn't quite enough as-is.  Easy fix though thankfully.

**Comment by reaperrr** [comment]
Updated (and tested, seems to work).

**Review by pchote — APPROVED** [review]
Code changes look good, but not tested ingame.

**Review by Smittytron — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/73960c4f0f03488669f100ce470211af6a10e5c3

115567f67fcf2a981542158997e8ce31e79ddfd2

**Pull request merged**
