### PR TITLE
Speed up TraitContainer.RemoveActor.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Find the actor to remove faster by using the binary search.

Remove the actor and traits faster by removing from the lists in a bulk operation.

### CODE REVIEW

**Comment by chrisforbes** [comment]
Random acts of optimization :)

**Comment by chrisforbes** [comment]
:+1:

**Comment by pchote** [comment]
Changes look sensible, and I added some logging before/after to confirm that the same traits appear to be removed in the same order. :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/247203609d5d1e58a1f5401113f99554f6df0e2c%5E...247203609d5d1e58a1f5401113f99554f6df0e2c

**Pull request merged**
