### PR TITLE
Add "(Ally)" behind the name of allies in all-chat

### LINKED ISSUE #7518: Distinguish ally and enemy chat messages
It would be better if the in-game chat showed teammate and enemy messages differently. For example when a teammate says something it could be green underlined and when enemy player posts a message red underline? Or some other way to make them different.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8803369-distinguish-ally-and-enemy-chat-messages?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jabbink**
Fixes #7518

### CODE REVIEW

**Comment by pevers** [comment]
Nice! But I think it would be better to show enemy text in a red color and ally text in green instead of the 'Ally' suffix.

**Comment by Phrohdoh** [comment]
We should not modify the actual string as the user may want to send `hi guys (Ally)` whether or not they are actually allied with the receiving clients.

**Comment by jabbink** [comment]
I thought, as the string was already manipulated at the same place ("(Dead)" and "(Spectator)") I could add it there.

of course the "(Ally)" is not appended to the chat message itself.

But then again: one could change their name to be "my_name (Ally)", so you are correct, this is actually bad.
Also as @pevers suggested: I actually don't think it's good to replace the player colors in the chat by red/green (or anything that color blind people can distinguish), so maybe it's a better idea to split this part up in the chat lines, so have a colored username, a differently colored indicator for the state of the player (dead/spectator/ally/enemy), followed by the chat message (current color is fine).

What do you think?

**Comment by deniz1a** [comment]
Yeah Phrohdoh has a point, that would be funny. I also think in addition to being able to distinguish between ally and enemy public messages, player colors should also somehow be added to those. Either the player name is in player color or an underline with player color? So would know just by looking at the chat message the allied green colored player said something for example.

**Comment by Phrohdoh** [comment]
Sorry @jabbink I misread this as modifying the message string, not the sender's identifier.
This is OK as-is.

**Comment by jabbink** [comment]
Yes, but your point is still valid as someone can name him/herself "username (Ally)". Of course the chat messages of this person will then be shown as "username (Ally) (Ally)".

**Comment by penev92** [comment]
I don't think we should worry about "username (Ally)".

**Comment by Mailaender** [comment]
I tested this with two local OpenRA instances teamed together and this does not seem to work. Not sure why, but I guess none of the commentators and developers here actually tested it or am I missing something?

**Comment by Phrohdoh** [comment]
@Mailaender I don't think anyone here claims to have tested it, so you are most likely the first to report this instead of just commenting on the approach.

**Comment by jabbink** [comment]
Tested here: 
image

**Comment by Mailaender** [comment]
Let's be more precise: this will only work for connected clients. Not the host.

image

**Comment by Mailaender** [comment]
Never mind, wrong window. This works as promised. :+1:

**Comment by obrakmann** [comment]
Works well enough, :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6d2c42b576a474cd07da7d50cfbd9fc7be8edd9c%5E...6d2c42b576a474cd07da7d50cfbd9fc7be8edd9c)

**Pull request merged**
