### PR TITLE
Fix TD SAM Site facings being reset when damaged while closed.

### LINKED ISSUE #18901: TD, Bleed: Taking damage prevents Sam Site from Turning
[Sam Site Turning Bug.zip](https://github.com/OpenRA/OpenRA/files/5649518/Sam.Site.Turning.Bug.zip)

### PR DESCRIPTION
**Pull request by pchote**
Fixes #18901.

### CODE REVIEW

**Review by Smittytron — APPROVED** [review]

**Comment by reaperrr** [comment]
Ah, so that was the root cause for all other RA/TD defenses with facings as well. If they received damage while the make anim was running, it would derive the quantized facings from the make anim.

Do we want to revert #18738 in favor of applying this on all of them?

**Comment by pchote** [comment]
> Do we want to revert #18738 in favor of applying this on all of them?

Is there a simple way to do the recoil animation with `WithEmbeddedTurretSpriteBody`?

**Comment by reaperrr** [comment]
> Is there a simple way to do the recoil animation with WithEmbeddedTurretSpriteBody?

Hm, good point. None that I'm aware of.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b6ebe6860441a4eec30e1817548b3764764c5395...95ac5ba8110edbdb38b7686b218f92211e8c12bb

**Comment by pchote** [comment]
IMO in the long term we are better off solving that division by changing SAM Sites to use a similar approach to #18738 and removing `WithEmbeddedTurretSpriteBody` completely.

**Pull request merged**
