### PR TITLE
Increase the speed of HIJACKER

### PR DESCRIPTION
**Pull request by abcdefg30**
Adds the speed buff missed in #9668.

### CODE REVIEW

**Comment by MicroJOo** [comment]
:+1:

**Comment by obrakmann** [comment]
Even with the speed change, hijackers still can't catch up to moving/harvesting harvesters. they get too them in the refinery, though.

**Comment by MicroJOo** [comment]
should be possible to get them while they are "harvesting" ... too

**Comment by reaperrr** [comment]
I'd increase it to 96, tbh, then it would be a little faster than harvs (assuming same terrain modifier).

**Comment by reaperrr** [comment]
After discussing this on irc, 85 should be good enough for the playtest, we can still tweak it later if necessary. :+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ad735cd3eec6d138d9c09086c1fb99fc0c53355c...1ca40f4b03768ae85440bcba4e5758097f82fd15)

**Pull request merged**
