### PR TITLE
Remove shellmap script from d2k

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by pchote** [comment]
:+1: Looks good to me.

**Comment by deniz1a** [comment]
What was that code in shellmap.lua even doing?

**Comment by Phrohdoh** [comment]
`Effect.ChangeLighting(red, green, blue, ambient)` is the bit that actually changed something.

**Comment by deniz1a** [comment]
So it changed lighting? I looked at the d2k shellmap and couldn't notice anything.

**Comment by Mailaender** [comment]
> No description provided.

What is the reason behind this and why is this a release blocker?

**Comment by obrakmann** [comment]
The reason is that the effect doesn't do a good job of conveying a sunrise to me. It looks more like a fade-in that takes ages to complete, and as a user I'm constantly wondering, "is it still changing, or is something wrong with my eyes"?

I'm not opposed to having the effect at all, but it needs some more work. It would probably be better to start off with regular lighting, then segue into night and back again.

**Comment by pchote** [comment]
I was under the impression that this effect was a testcase and wasn't supposed to be merged in the first place.  There are several places where this effect fits naturally and improves the experience ([e.g. IRC logs](http://logs.openra.net/?year=2015&month=07&day=08#12:36:56)), but it doesn't benefit anything on the d2k shellmap.

**Comment by reaperrr** [comment]
Needs rebase.

**Comment by Mailaender** [comment]
I didn't know it was perceived that bad.

**Comment by obrakmann** [comment]
Rebased

**Comment by reaperrr** [comment]
:+1:

**Pull request merged**
