### PR TITLE
Friendly name for HashSet in docs

### PR DESCRIPTION
**Pull request by RoosterDragon**
Requested in https://github.com/OpenRA/OpenRA/pull/9181#issuecomment-135579391.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by Phrohdoh** [comment]
Why do we need separate names for a set vs array, etc?

**Comment by penev92** [comment]
I guess it's a compromise between giving technical information like `HashSet` vs `string[]` and not being technical enough (people might like to know why their YAML isn't working when it is due to `HashSet` swallowing the duplicate values).

**Comment by Phrohdoh** [comment]
Do we have any situations where duplicate values *do* work?

**Pull request merged**
