### PR TITLE
Downgrade SDL to 2.0.22.

### LINKED ISSUE #20709: After screenshotting selected area, openra stops accepting keyboard inputs
The only way I found to fix it is to change to another desktop, and back again. This issue also happens when recording

### LINKED ISSUE #20715: MacOS m1 pro, m2 pro, left click not working properly anymore
## Issue Summary

DESCRIPTION
[in the lastest release](https://github.com/OpenRA/OpenRA/releases/tag/release-20230225), On MacOS m1 Pro monterey, the single left click doesnt work anymore in the menu and in the game. Now a double click or CMD+click is required to do the left click action.
 It is working in [the previous prerelease](https://github.com/OpenRA/OpenRA/releases/tag/playtest-20230218).
Same behaviour with the trackpad or a mouse. 
 

## Reproduction

STEPS TO REPRODUCE THE ISSUE

[Install release](https://github.com/OpenRA/OpenRA/releases/tag/release-20230225) on a macos m1 pro monterey and launch the game. The single left click does not do allow to click on buttons in the menu.

## Expected behavior

EXPECTED BEHAVIOR

The single left click should be mapped to the same action as previous prerelease.

### PR DESCRIPTION
**Pull request by pchote**
Closes #20709.
Closes #20715.

https://github.com/pchote/native-dependencies/commit/f3abfe20d3b2149b01c3388a37a1f31897ab3efe

### CODE REVIEW

**Comment by PunkPun** [comment]
[Testbuild](https://github.com/PunkPun/OpenRA/releases/tag/devtest-20230412)

**Comment by penev92** [comment]
Works on my machine™️

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7998e76926ee0ddf76d17e34632516ac9d9fe349...5d9632f2ebd0078d0999306fea2f1d13549320bd)

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/commit/08a7735dedf41a0cddd0fee9e92c2cad4911f1ef

**Pull request merged**
