### PR TITLE
 TD APC Turret artwork rework

### LINKED ISSUE #2125: Add separate "aims" for different elevations
One aim for when the unit is engaging air units and another for when it is engaging ground units.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98267-add-separate-aims-for-different-elevations?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Inq8**
This PR replaces the current 3rd party AA gun turret artwork with my own.
The aim being to more faithfully recreate the turret from the source material & allow for turret switching between ground & air targets.

apc

AAgun

 Closes #2125

**Note:**
The reload condition juggling is required to maintain a smooth transition between turrets otherwise it can visually glitch out.

### CODE REVIEW

**Comment by pchote** [comment]
Why did you close this?!?

**Comment by Inq8** [comment]
Because I'm an idiot that can't work GitKraken. 

aatur2

Cleaned the sprite a bit, doubled the fire rate & halved the damaged as discussed on Discord @ Tiberian-Dawn

**Comment by pchote** [comment]
LGTM, although i think it may look better if it defaulted to the ground-facing turret?

**Comment by Inq8** [comment]
apctur3

Done.

**Review by Mailaender — APPROVED** [review]

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/908442391205a0c2ca4d539d30b2417d854f64fb)

**Comment by KOYK** [comment]
@Inq8 would it be easy to make an HD version of the turret for the remastered version? also same thing about the black hawk

**Pull request merged**
