### PR TITLE
Partially revert BuildingInfluence removal

### LINKED ISSUE #18816: Bot places buildings on bibs and exits blocking itself
image

image

### LINKED ISSUE #18852: Bibs no longer count towards building adjacency
bleed:
grafik
release-20200503
grafik

Possibly another regression from #18689.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #18816.
Fixes #18852.

This PR reverts the problematic ~half of commits from #18689.
I did not revert:
* f1a949f6380f3c762438dfa52999f4c995bf78bf: Plugs can't be placed on bibs, so BuildingInfluence isn't useful here.
* c4045bdd7eb92f1a65d6bf0a6d9b581461499e81: No change in behaviour thanks to the `aircraft.CanLand` check that already filtered out bibs.
* 83b61ab76208bfc074c629d1f69912c17e4fd6f7: LaysTerrain was removed, replaced by 8344eaa.
* 1800ea91ab56d9fe56d7d50c0d2d671887fe3cfe: It seems reasonable to allow crates and aircraft to spawn/land on bibs.

This also tweaks #18688 to restore the bib check in a different form instead of reverting the other cleanups in that PR.
 
Disclaimer: I have run out of time to properly test this, but did not want to hold up filing the PR. I will test the changes in more depth over the weekend.

### CODE REVIEW

**Comment by pchote** [comment]
This isn't showing the red blocked preview when trying to place concrete on top of existing buildings.

**Comment by pchote** [comment]
Fixed.

**Review by reaperrr — APPROVED** [review]
Can confirm the fixes, didn't notice any other issues.
As long as it's minor, feel free to count this as +1 even after potential further fixups.

**Comment by pchote** [comment]
This should be a reasonably safe change (mostly reverting back to the code we have had for years), and no further bib-related issues have been reported on the recent test builds that have contained this PR. It seems reasonable to take this without a second approval for the sake of making progress towards a playtest.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ebfd8b7bd8e6061cedb9f3510968669afac64d48

**Pull request merged**
