### PR TITLE
Overhaul Input settings panel

### PR DESCRIPTION
**Pull request by pchote**
This PR overhauls the Input tab in the settings menu with three goals in mind:

* Make left vs right click control schemes discoverable and understandable. This is IMO a key prerequisite for #17345, and was the main motivation of this work. This is also why I've added the dependency label and milestone assignment.

* Fix the right click orders + right click scrolling problem to unblock #17099. The two mouse scrolling types have been merged into one (which now defaults to the Joystick mode), which is mapped to middle mouse in the "Modern" scheme and right (or optionally middle) mouse in the "Classic" scheme. I have also clarified the terminology for scroll vs pan vs zoom because it didn't make sense to have N instances where we used "scroll" to mean "pan" but then talk about using the scroll wheel to zoom.

* Prepare for trackpad gestures. This is really an extension of the second point - the previous mess regarding mouse scrolling meant that there was no intuitive way to introduce the gesture support without adding even more scroll configuration options.

The tab is arranged with the settings that impact the control scheme description are above/to the right. The settings that don't are placed below.

I have reserved space to the right to add a "Touch Pad/Screen Gestures" checkbox - enabling this would disable MMB/RMB panning, change the zoom description to "Zoom the battlefield using a {Pinch} gesture", and change the pan description to "Pan the battlefield using a {Scroll} gesture".

I noticed after implementing the new layout that the Display/Audio/Input/Advanced tabs were all coincidentally the same height, with an awkward amount of empty space along the bottom due to the Hotkeys tab. These have now been straightened out.

### CODE REVIEW

**Comment by dragunoff** [comment]
This is a great improvement. It helps explain the differences between the control schemes and simplifies the setup immensely. It even alleviates a bit the problem described in #16669 by being clear about which button does what. The changes are even more welcome in light of #17345. So 👍 👍 from me.

>
> I noticed after implementing the new layout that the Display/Audio/Input/Advanced tabs were all coincidentally the same height, with an awkward amount of empty space along the bottom due to the Hotkeys tab. These have now been straightened out.
>
The settings panel is clearly near its limits in terms of layout and is screaming for a redesign but that's the topic of a larger conversation. Until then I think it needs to keep whatever breathing room there is - it's already very tight and trimming those few pixels at the bottom IMO doesn't do any good. It looks more crowded and doesn't leave space for new settings - any PR that wants to add a checkbox would have to increase the size of the panel (see https://github.com/OpenRA/OpenRA/issues/6354#issuecomment-573264969 for example). I think we should drop the last commit here.

**Comment by pchote** [comment]
Hmm... the Audio and Advanced tabs still have room, and my next PR (which I was hoping to defer until some of my current ones have been merged...) is going to remove the two cursor settings and win back a full row on the Display tab. Isn't this enough?

**Comment by pchote** [comment]
I'd like to do another pass over the menu to fix some other spacing/margin inconsistencies I have noticed, and will post a mockup of what I expect the final version (after all the parallel and the couple of future PRs have been merged) should look like.

**Comment by pchote** [comment]
Updated to align the settings layout to the standard 30px row height.

My end goal for the Display tab is something like:
Screenshot 2020-01-17 at 18 46 56

The cursor size option will be moved to the Input tab, and the hardware/software cursor toggle to a hidden option.

**Comment by Punsho** [comment]
It might be clearer if you renamed `radar` to `minimap`

**Comment by dragunoff** [comment]
> 
> 
> Hmm... the Audio and Advanced tabs still have room, and my next PR (which I was hoping to defer until some of my current ones have been merged...) is going to free up ~two rows worth of space on the Display tab by removing the two cursor settings and restart description text. Is this enough?

The Advanced tab doesn't have any room when the extra debugging settings are enabled. The new layout for the display tab looks good but I still don't see a problem with having some extra space. I can let my objections slide though if we restore the input dialog to its previous state. Or at least the padding within the remap dialog, it just looks so crammed together with this PR:

**With this PR** 
after

**Before this PR**
before

**Comment by pchote** [comment]
It would be good to get some additional opinions on the Hotkeys pane - I had intended the changes there as a polish/usability improvement, as the buttons are now vertically centered within the panel, and reducing the height of this bottom section allows a full extra row to be visible in the top section.

**Comment by dragunoff** [comment]
Without reducing the height of the settings panel a full seven rows are visible in the Hotkeys scroll pane :stuck_out_tongue: 

Perhaps we should leave these rearrangements for a separate PR - when the Display tab is ready and things have stopped shifting around? I don't want to be blocking this PR over disagreements with the spacing. 

And as I said, the settings panel is in need of a redesign - I have some ideas, I will try to put them in a mockup and file an issue.

**Comment by pchote** [comment]
The spacing is important - our UI conventions we apply everywhere else is to aim for a 30px row height and try to make the most use of the full dialog space, but this was let slide in the settings panel mainly because this was impossible with the old combined Input tab.

I'd rather take the delay now while we sort out the short-medium direction forward, versus making this PR and game objectively worse by throwing away the fixes (which are now more than just reducing the height of the panel) for Next + 1.

**Comment by pchote** [comment]
Updated to restore the original vertical margins within the bottom hotkey panel:
Screenshot 2020-01-18 at 20 37 09
Screenshot 2020-01-18 at 20 48 07

**Review by dragunoff — APPROVED** [review]
LGTM :+1:

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/985a913a34655f0d0dae22d4c3734cd55d3c1611...8bf14ef1d31f7a7952aa7819ba4b4df4b4397bf2)

**Pull request merged**
