### PR TITLE
Add restart button to in-game menu for single player (skirmish, misison, replays)

### LINKED ISSUE #11318: Odd "Restart Mission" Menu button placement
This is a little thing, and I seem to recall it was kind like this originally, but the "Restart Mission" button should be front and center of a mission failure screen.  It was jarring enough where I spent a minute or two clicking things at random, looking...

Right now, it's like this:
I just _eat it_, Tanya walks in front of a Tesla coil, and dies.  Dang.  I want to restart, but the screen looks like this.
where

After looking and looking, I just say screw it, and quit.  Lo and Behold.
oh

Personally, I think it could be better.

### PR DESCRIPTION
**Pull request by dragunoff**
This PR:
- Adds a "Restart" button to the ingame menu for single player (skirmish, misison, replays)
- Removes the "Restart" button from the prompt for "Abort Mission" / "Leave" as it is redundant
- Removes the "Surrender" button for single player games (the screenshots are outdated in this regard)

game-in-progress
Game in progress (skirmish, mission, replay)

game-over
Game over (skirmish, mission, replay)

restart-prompt
Prompt on "Restart" button

The second commit of this PR changes the behavior of "Leave" button when a game is over. The behavior was inconsistent because it did not prompt players that won the game but sent them straight out. I know this is a bit out of scope here and may be controversial but I was tempted to change it to make the behavior of all buttons ("Restart", "Surrender", "Leave") consistent (i.e. always prompt).

Closes #11318

### CODE REVIEW

**Comment by dragunoff** [comment]
Related issues for multiplayer games and replays: #15181, #14104

**Comment by pchote** [comment]
Scope creeping onto the milestone - this goes well (both code and feature wise) with the savegame changes.

**Review by abcdefg30 — DISMISSED** [review]

**Comment by pchote** [comment]
Unfortunately this overflows the window width (1024px) in the TD ingame menu in skirmish mode.

I suspect that the best fix here (which has been on my low priority TODO list for a long time now) will be to remove the Music button, and have the music options as a tab on the central panel instead.

This is too much for the playtest, so we'll have to defer this to Next + 1.

**Comment by dragunoff** [comment]
> 
> Unfortunately this overflows our minimum supported window width (1024px) in the TD ingame menu in skirmish mode.
> 
Ah, that's a bummer... But I thought the minimum supported resolution is 1280x720 and this is what I tested on. 

> I suspect that the best fix here (which has been on my low priority TODO list for a long time now) will be to remove the Music button, and have the music options as a tab on the central panel instead.
> 
You mean as a tab on the score/chat panel?

**Comment by tovl** [comment]
I think we should just remove the surrender button for single player skirmish.

**Comment by dragunoff** [comment]
> 
> 
> I think we should just remove the surrender button for single player skirmish.

I can get behind that. I can't think of a use case for the surrender button for single player other than for testing purposes but that can be achieved with a chat command.

**Comment by pchote** [comment]
I use the surrender button a lot while testing, but I guess I can live with the chat command for that use case.

**Comment by dragunoff** [comment]
> 
> 
> I use the surrender button a lot while testing, but I guess I can live with the chat command for that use case.

Yeah, I use it a lot too. But if there is no other value in keeping it I think we should sacrifice it. 

And with regards improving the usability of chat commands - an auto-complete sounds like a good addition (if it's not already there, haven't tried).

**Comment by abmyii** [comment]
> And with regards improving the usability of chat commands - an auto-complete sounds like a good addition (if it's not already there, haven't tried).

There is already one for player names, though it is a bit annoying when you want to toggle team/all chat. Perhaps we should change either toggle or autocomplete (Ctrl+Tab/Space?) to another key. I'll make a separate issue if it is worth it.

**Comment by abcdefg30** [comment]
Chat commands do support auto-completion.

**Comment by dragunoff** [comment]
Update:
- Remove "Surrender" button for single player games
- Add a fixup commit making `isSinglePlayer` readonly (will squash when ready to merge)

**Review by abcdefg30 — DISMISSED** [review]

**Comment by abcdefg30** [comment]
Adding `Fixup requested` so we don't forget to squash the extra commit.

**Comment by dragunoff** [comment]
Squashed.

**Review by pchote — APPROVED** [review]
LGTM, and since this is a relatively simple polish PR I'm going to take the liberty of picking this onto prep for the upcoming hotfix.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/20bc0da934b16e10d1e766d2dced899fa5a11cee

db7297171778d6e20bb8382829242194b8d46202
4e9cf96d6dfe454446d444ee853a952ca60a6b84
26c3ea50fa2137f65a3b903d708f8f0c0abb6ded

**Pull request merged**
