### PR TITLE
[RA] [Map Pool] Fix tiles on Countercross, Siberian Pass & Six Below Zero.

### LINKED ISSUE #13098: Tiling error on "Sudden Death" map
screen shot 2017-04-10 at 21 38 07

### LINKED ISSUE #13112: Tiling errors on maps "Countercross","Siberian Pass","Six below zero"
**Countercross**
Bad tile locations:
47,25 - tile
142,125 - tile
172,79 - tile
187,16 - road
177,12 - inaccessible ore
35,141 - misplaced ore
34,143 - misplaced ore
Link to revision:
http://resource.openra.net/maps/20541/

**Siberian Pass**
Bad tile locations:
9,33 - road
10,30 - road
17,33 - road
19,33 - road
5,51 - road
3,53 - road
72,57 - road
50,41 - misplaced ore
Link to revision:
http://resource.openra.net/maps/20542/

**Six Below Zero**
Bad tile locations:
24,42 - road
43,17 - road
30,48 - road
36,49 - road
76,65 - road
77,107 - road
86,112 - road
74,88 - road
44,110 - road
109,81 - road
109,56 - road
109,18 - debris
106,19 - road
87,28 - road
Link to revision:
http://resource.openra.net/maps/20543/

### PR DESCRIPTION
**Pull request by SoScared**
Adressing #13112 

Will also unpack map Six Below Zero with its rules.yaml (snow).

revisions used:

Countercross: http://resource.openra.net/maps/20541/
Siberian Pass: http://resource.openra.net/maps/20542/
Six Below Zero: http://resource.openra.net/maps/20543/

closes #13112 
closes #13098

### CODE REVIEW

**Comment by ltem** [comment]
The maps from #13112 are fixed

But could you fix the issue from #13098 (Sudden Death) as well?

**Comment by SoScared** [comment]
@ltem: Added!

closes #13098

**Comment by SoScared** [comment]
Renamed commit.

**Comment by SoScared** [comment]
Added extra tile-fixes mentioned on https://github.com/OpenRA/OpenRA/issues/13112#issuecomment-294295528

**Comment by ltem** [comment]
:+1: 
'Sudden Death' and 'Six Below Zero' are fixed

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e4f899466e09f0a8c7aff54e88050ea3ba66f0bc)

**Pull request merged**
