### PR TITLE
Don’t draw WorldTooltip if the game is paused.

### LINKED ISSUE #6936: Tooltip drawn over pause menu.
Hover over an actor then pause the game.
If you move the cursor the tooltip is not drawn again (as is expected).

image

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5959664-tooltip-drawn-over-pause-menu?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by phrohdoh**
Closes #6936.

### CODE REVIEW

**Comment by obrakmann** [comment]
This approach won't help in multiplayer games, where the game isn't paused when you bring up the menu. It would be better to move the `TooltipContainer` below `WorldRoot` in `ingame.yaml`.  I do not know whether there was any specific reason that the tooltip container is where it is now, though, so moving it might break something else.

**Comment by pchote** [comment]
The menus have tooltips, too.

**Comment by Phrohdoh** [comment]
So any tips for this or should we close it for later?

**Comment by obrakmann** [comment]
you could try if adding separate TooltipContainers to both `MenuRoot` and `PlayerRoot` works. Will probably need some changes in the code to avoid finding multiple widgets with the same name.

**Comment by pchote** [comment]
A simpler fix would be to add some mechanism to explicitly clear the tooltip when opening/closing the menu.

**Comment by Phrohdoh** [comment]
@pchote I went for that approach yesterday but couldn't quite find the right spot for it.

I can come back to this later (today or tomorrow hopefully).

**Pull request closed without merging**
