### PR TITLE
Add Allies05b

### PR DESCRIPTION
**Pull request by Smittytron**
Code here is mostly based on Allies05a. That one has an interesting Real Tough Guy difficulty that vastly changes the way the mission plays out. I couldn't think of an innovative way to achieve that here so just the three difficulties. If I find the right amount of inspiration/motivation I may come back and add the extra difficulty level.

### CODE REVIEW

**Comment by Smittytron** [comment]
From Discord FWIW
> 3:43 PM] tttppp: Allies05b on Easy worked great

**Comment by darcyrush** [comment]
```
Fatal Lua Error: [string "allies05b.lua"]:79: attempt to index global 'Hero' (a nil value)
   at OpenRA.Scripting.ScriptContext.FatalError(String message)
   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Launcher.Program.Main(String[] args)
```
[ra-2021-02-20T051306Z.zip](https://github.com/OpenRA/OpenRA/files/6014184/ra-2021-02-20T051306Z.zip)

**Comment by darcyrush** [comment]
C4ing the large bridge has a high chance of killing tanya. I didn't check the other bridges. Hard plays ok apart from the crash and bridge explosions.

For a real tough guy variant, perhaps instead of a chinook and reinforcement LSTs in the bottom left, an LST could drop off two mechanics and an arty on the prison island?

**Comment by Smittytron** [comment]
Fixed the crash when the player skips the civilian help. The C4 issue is #4660; a long standing issue that won't be fixed here.

**Comment by pchote** [comment]
Screenshot 2021-02-21 at 00 31 12

There seems to be a whitespace issue with the title.

**Comment by pchote** [comment]
Is it intentional that you can interrupt the scripted chain where the spy gets out of the truck and infiltrates the prison by issuing it an order? The script does continue if you manually order it into the prison, so I'm not sure.

Otherwise, I played the starting sequence through a couple of times (both with and without the civilian by the church), and played through the rest of the mission on the standard difficulty without finding any bugs.

The Lua script looks reasonable as far as I can tell (but tbh you're now a bigger expert on them than I am), so :+1: once the title spacing is fixed and my question here is resolved.

**Comment by Smittytron** [comment]
Whitespace fixed.

> Is it intentional that you can interrupt the scripted chain

Yep, we've got that in Allies05a as well.

**Comment by Smittytron** [comment]
Noticed more mission browser whitespace issues so I added a fixup commit to #19169

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/12f39251eb9d335f5a9f934d12e461a7061c649d...742fda55b8c8a156ed53abc536237e4ab852f9fa

**Pull request merged**
