### PR TITLE
Resharper codestyle settings

### PR DESCRIPTION
**Pull request by hartmark**
I'm using resharper with Visual Studio. It really improves my code quality. I have added some naming rules so it won't complain on some.

Is this something we want to have in the repository or should I just have my own settings file locally?

### CODE REVIEW

**Comment by Mistranger** [comment]
I use it too, so your settings would be helpful.

**Review by Mailaender — APPROVED** [review]
I am okay with adding this file here.

**Comment by pchote** [comment]
Can you please outline what these do?  I don't run a system compatible with resharper.

**Comment by hartmark** [comment]
There's three rules defined in this PR,
1. Makes resharper not complain that private modifier is missing on fields and methods, and if they have private it suggests to remove it
2. private fields should have camel casing with starting lower letter, with no prefix
3. public fields should have camel casing with starting uppercase, no prefix

**Comment by pchote** [comment]
Ok, thanks.  They sound good to me.

**Review by pchote — APPROVED** [review]

**Pull request merged**
