### PR TITLE
Fix spicebloom spawns on all older D2k maps

### PR DESCRIPTION
**Pull request by reaperrr**
Follow-up to #12584.

Spice blooms are not supposed to show and grow on cells occupied by spice, which is the case for pretty much all pre-placed spice blooms.

### CODE REVIEW

**Review by ltem — APPROVED** [review]

**Review by ltem — APPROVED** [review]

**Comment by ltem** [comment]
:+1: 
---------------------
2 questions regarding this topic(if it is offtopic I would fill a issue):
1. Would it possible to add for the map editor some kind of overlay, like for the worm spawnpoint? Right now there is none.

Sandworm overlay
:--------------------:
wormspawner

2. Would it further be possible to use some kind of graphic for these overlays? For example the grunt mod map render tool uses something like this for the spicebloom/sandworm-spawn:

Sandworm | Spicebloom          
:-------------------------:|:-------------------------:
sandworm | spicebloom


(This "approve one file, approve the whole PR"-behavior is bit strange)

**Comment by reaperrr** [comment]
@Item That will be done as part of #12350 (using transparent spicebloom image), I just split off this PR to make #12350 smaller.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by ltem** [comment]
Nice :)

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/64d2b2119d3f7201894d5ad508c7d835c7dc37d3...dfb6e93bb80990fa3844d9ad3f05915ac7dc265e)

**Pull request merged**
