### PR TITLE
Remove "Enemy Unit Detected" announcements

### PR DESCRIPTION
**Pull request by pchote**
By popular demand.  The `EnemyWatcher` removal is deferred to the next playtest.

### CODE REVIEW

**Comment by reaperrr** [comment]
#8515 includes a fix for that Travis complaint.

**Comment by reaperrr** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/15ecee28b38abc1ca0e5a43fb943e4ea20d0fe1b%5E...15ecee28b38abc1ca0e5a43fb943e4ea20d0fe1b)

**Pull request merged**
