### PR TITLE
Remove version information from NuGet folder names

### PR DESCRIPTION
**Pull request by rneatherway**
This makes the names consistent and prevents changes in versions of
dependencies from breaking the build.

If you like this I can update the .ps1 and -windows scripts as well.

### CODE REVIEW

**Comment by Mailaender** [comment]
I don't think there will be any conflicts as we delete the folder right away. :+1:

> If you like this I can update the .ps1 and -windows scripts as well.

Yes, that makes sense.

**Comment by rneatherway** [comment]
OK, all done

**Comment by pchote** [comment]
This is a nice cleanup, and doesn't seem to break anything. :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/8fee89ba1f01d67f2ebc9ba4c1aa81fab2451e24%5E...8fee89ba1f01d67f2ebc9ba4c1aa81fab2451e24

**Pull request merged**
