### PR TITLE
Enforce StyleCop rules

### PR DESCRIPTION
**Pull request by RoosterDragon**
Review StyleCop rules.

- Enforce SA1604 ElementDocumentationShouldHaveSummary.
- Enforce SA1629 DocumentationTextShouldEndWithAPeriod.
- Turn off some rules covered by IDExxxx rules.
- Remaining rules are treated as part of OpenRA style.

~~Disable IDExxxx rules by default. This prevents new rules from triggering until we are ready to enable them.~~

### CODE REVIEW

**Comment by PunkPun** [comment]
Do we actually want to `Disable IDExxxx rules by default.`? Afaik new rule severity is set to suggestion, so they shouldn't break our workflow

**Comment by RoosterDragon** [comment]
The won't break our workflow, but do we want to be pinged by suggestions in the error list until we've had a chance to decide on them? I had a soft preference to disable them but I'm not hard set on it, so happy to go with the majority opinion.

**Review by abcdefg30 — DISMISSED** [review]

**Comment by PunkPun** [comment]
> do we want to be pinged by suggestions in the error list until we've had a chance to decide on them?

I think being "pinned" is a good reminder to do something about them / notification that something needs to be done

**Comment by RoosterDragon** [comment]
Ok, removed the disabling of IDExxxx rules.

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/992517b973bed482e53e70db18ed4f1e6c43fa4f...ba0b0bb5d44dfedab1546ed7836fd57b94822fe9)

**Pull request merged**
