### PR TITLE
Fix effect warhead triggering on invalid actors

### LINKED ISSUE #16727: Destroyer missiles show splash when hitting target
Probably affects other missiles, too.

Regression from recent `CreateEffectWarhead` simplification.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #16727 by reverting #16312.

### CODE REVIEW

**Comment by GraionDilach** [comment]
>if a CreateEffectWarhead has ImpactActors: true we only want it to trigger if there are no actors at impact position and the terrain is valid

This case doesn't sound intuitive to me. Infact. I'd say only the latter case should be allowed.

**Comment by reaperrr** [comment]
Yeah, I agree that would be the technically correct solution.
The reason I don't want to go there right now is that it would definitely require a larger rework of the warhead yaml setup in at least RA, and I don't want to go there this close to a playtest.
This was the simplest way of fixing the regression while avoiding yaml changes.

Can we settle with adding HACK: in front of the comment, + adding
```
TODO: Always returning 'false' if there are no valid actors would be more correct, but would require a larger rework of the mod rules of at least our RA mod.
```

and adressing this properly for Next+1?

**Comment by pchote** [comment]
Would it make more sense to revert the PR that introduced the regression and then do it properly all in one go for next + 1?

**Comment by reaperrr** [comment]
> Would it make more sense to revert the PR that introduced the regression and then do it properly all in one go for next + 1?

I guess so. Updated.

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
Original PR didn't have a changelog, so this has neither.

**Pull request merged**
