### PR TITLE
Fixed a crash after changing the display scale

### PR DESCRIPTION
**Pull request by Mailaender**
This is a followup to https://github.com/OpenRA/OpenRA/pull/20877 and an attempted fix for https://github.com/OpenRA/OpenRA/issues/20951 which I can't reproduce as the option is not available to me.

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
Crashes with the same error

**Comment by PunkPun** [comment]
`w.X` and `w.Y` are null as well

**Comment by PunkPun** [comment]
This seems to fix the issue.

Though I'm not sure why we need to use a readonly dictionary here? Also maybe fixing the bug here is not addressing the issue at the core? Sorry I don't have time to investigate

**Comment by Mailaender** [comment]
If you have a look at https://github.com/OpenRA/OpenRA/pull/20877 you can see that I am using the exact same pattern for safe evaluations.

**Review by PunkPun — APPROVED** [review]
Ah I see now

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/de7696e48551c086d2e2dcfc04282cd9bb007864...f3a13a995430e493a129b5fcde2f522c53f90977)

https://github.com/OpenRA/OpenRA/commit/db3145ed5e2c96bfc456d556021966b36d674db0

**Pull request merged**
