### PR TITLE
Added more possible decoration positions

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenRA/OpenRA/pull/17808.

### CODE REVIEW

**Comment by dragunoff** [comment]
@Mailaender Could you provide a testcase?

**Comment by Mailaender** [comment]
Sure. https://github.com/OpenHV/OpenHV/pull/124

**Comment by pchote** [comment]
Please demonstrate that these won't break in TS - this was the reason why I specifically didn't add them in the first place.

The selection / decoration APIs were designed around the idea that selection boxels would be rendered using a specific renderable, and not assembled using decorations (which are super heavy weight for this task).

**Comment by Mailaender** [comment]
In TS it will default to the center position. You said it is impossible to solve in an isometric environment.

**Comment by Mailaender** [comment]
See also https://github.com/OpenHV/OpenHV/pull/124/files#diff-18a19db84e393546981bdfbd1d49eb6aR850-R854 as other valid sprite decorations profit from removing this constraint as well.

**Comment by pchote** [comment]
I filed #18521 to remove the hardcoded constants, which allows you to implement what you need in HV without impacting TS.

**Comment by Mailaender** [comment]
That seems like a good compromise.

**Pull request closed without merging**
