### PR TITLE
Fix a crash in allies03a

### LINKED ISSUE #17062: RA1 Allied 03a Dead End, selling or undeploying captured MCV causes crash.
### Issue Summary
I was playing 03a Dead End mission on RA1 Allied campaign. In the mission, you can rescue an engineer, and with him, a MCV. But if you sell or undeploy it, game will crash.

Expected behavior was it wouldn't crash.

#### System Information
- **Operating System:** Ubuntu 18.04
- **.NET / Mono Version:** 5.20.1.19
- **OpenRA Version:** playtest-20190825
- **Mod:** RA1
- **UUID:** 207895a4-7a65-439c-b2c9-d8f24f44d961

#### Additional Information:
- Steps to reproduce
	1. Run 03a Dead End mission from RA1 Allied Camp.
	2. Rescue the first medic
	3. Rescue the second medic and Engineer
 	4. Capture the nearby MCV
	5. Sell or undeploy the MCV

- Logs
```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'camera (dead)' does not define a property 'Destroy'
  at OpenRA.Scripting.ScriptContext.FatalError (System.String message) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Mods.Common.Scripting.TriggerGlobal+<>c__DisplayClass19_0.<OnAllRemovedFromWorld>b__0 (OpenRA.Actor m) [0x0004f] in <a1710de8320c4e3fb3b955ebbefc3cd3>:0 
  at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Traits.INotifyRemovedFromWorld.RemovedFromWorld (OpenRA.Actor self) [0x00074] in <a1710de8320c4e3fb3b955ebbefc3cd3>:0 
  at OpenRA.World.Remove (OpenRA.Actor a) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Actor.<Dispose>b__81_0 (OpenRA.World w) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.World.Tick () [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Game.Loop () [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Game.Run () [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <cd5e9c0bbda84d79a5889e81da9eed16>:0 
```

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #17062 which is a regression from #15680.

Testcase: Destroy the entire base except the construction yard. Then capture it. That triggers the camera removal. Then sell or undeploy it (triggering it a second time).

### CODE REVIEW

**Comment by pchote** [comment]
> [22:07:57] | <abcdefg30> hm, I might have successfully broken half of our RA missions with #15680
> [22:07:58] | <orabot> Pull request #15680 (closed) by abcdefg30: Fix OnAllRemovedFromWorld only triggering once \| http://bugs.openra.net/15680
> [22:08:11] | <abcdefg30> now it makes sense why infiltration was weirding out

Do we need to worry about other missions here too?

**Review by pchote — DISMISSED** [review]
In any case, confirmed the allies03a fix.

**Comment by abcdefg30** [comment]
Updated to include other missions as well.

**Review by ghost — APPROVED** [review]
LGTM and no other `OnAllRemovedFromWorld` involves a conyard as far as I can see.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/3fb334802373d1633ba88f8162d8d275676e8395...6f97f1843228f59effd4c0ecb78f103ca50a8b95

ef9b8fd
e5eca67

**Pull request merged**
