### PR TITLE
Fixed HarvesterInsurance assuming all refineries get free harvesters

### LINKED ISSUE #14544: HarvesterInsurance crash
The D2k `HarvesterInsurance ` assumes all `Refinery` actors have `FreeActorWithDelivery ` which crashes the game if the last actor with `Refienry ` in the game is one without `FreeActorWithDelivery ` and `HarvesterInsurance ` gets triggered.

In missions one might want to have refineries without free harvesters beeing delivered at the mission start.

### PR DESCRIPTION
**Pull request by penev92**
Fixes #14544.

Simple fix for a stupid crash, so putting on the milestone.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
(We still do one lookup twice though... :/)

**Comment by penev92** [comment]
I can change it to manually iterate over all the refineries and check for the trait if requested...

**Comment by pchote** [comment]
You could do something like `self.World.ActorsHavingTrait<Refinery>().Where(a => a.Owner == self.Owner).Select(a => a.Info.TraitInfoOrDefault<FreeActorWithDeliveryInfo>()).FirstOrDefault(x => x != null)`

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ee35214eaa975ed50f2c3a05badfe569f8c22761

**Pull request merged**
