### PR TITLE
Overhaul macOS packaging

### PR DESCRIPTION
**Pull request by pchote**
This PR overhauls the macOS package creation with two main goals
- Sign and notarize the app bundles to solve the macOS gatekeeper from blocking launch - this requires building on Travis-CI's macOS VMs
- Create macOS-specific files from generic sources during packaging - solving the main prerequisite for https://github.com/OpenRA/OpenRAModSDK/issues/22

and two minor goals:
- Add a volume icon for display on the desktop/window title
- Rename osx directory to macos to fit more recent platform conventions

This uses travis's conditional builds feature to keep normal PR/bleed merges as they have always been, but spawn parallel Linux and macOS jobs when a tag is pushed. The macOS VM skips the tests to provide more time for the future notarization process, which can apparently take a few tens of minutes to complete.

Testcase ("bleed"): https://travis-ci.org/pchote/OpenRA/builds/647090875
Testcase (tagged build): https://travis-ci.org/pchote/OpenRA/jobs/648308808
Testcase (tagged build with code signing failure): https://travis-ci.org/pchote/OpenRA/jobs/648294331

### CODE REVIEW

**Comment by pchote** [comment]
I am (hopefully) close to implementing automated code signing and notarization. To avoid wasting time, reviews should wait until this has been finished.

**Comment by pchote** [comment]
Updated to sign and notarize the macOS builds using my personal developer account.

I've already added the credentials to the travis web config, so this should just work once merged.

Please be aware when reviewing any future PRs that somebody doesn't try to slip in changes to the makefile or packaging scripts to leak the credentials to the log.

Before:
Screenshot 2020-02-10 at 19 42 39

After:
Screenshot 2020-02-10 at 19 42 49

**Comment by pchote** [comment]
We don't have anybody else to review this, and we have confirmed that the end results work (tested by myself and @Punsho). Is there any objection if I merge this tomorrow?

**Review by abcdefg30 — APPROVED** [review]
Ok.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f69a65ce9e3727f4d8fba3735ad457480d94ef62...931776caf142270d738c06ef56d40711b4c5f9c0)

**Pull request merged**
