### PR TITLE
Updated the ZeroBraneStudio API converter

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of #11686

### CODE REVIEW

**Comment by Mailaender** [comment]
I also wrote https://en.opensuse.org/ZeroBrane_Studio including a step by step tutorial for beginners.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/28e4fc9568a3e100a951897ea2ba51a655a4397e...03eba0858d1d742aa441a504c8f60c541194aea0

**Comment by pchote** [comment]
argh, this was merged to master!

**Comment by Mailaender** [comment]
Sorry.

**Comment by reaperrr** [comment]
Sorry for not noticing,

**Comment by pchote** [comment]
I didn't notice either, until I `git fetch`ed down an unexpected changeset to master.  Mistakes happen, and it was easy to fix.

**Pull request merged**
