### PR TITLE
Fix some TS building overlays

### LINKED ISSUE #13046: TS building light animations need to glow in the dark
All building light overlays in the original were unaffected by map lighting, so we need to define a separate palette for them that won't get modified by global lighting and such.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixed some overlay errors (compared to original game) I came across.

### CODE REVIEW

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by ltem** [comment]
This PR has some issues with the custom rules of the map "Sunstroke" but I don't know why.
image

**Comment by pchote** [comment]
That looks to be a fatal issue for this solution.  I assume the original game did this by masking palette indices?  It would be straightforward to add that to the `GlobalLightingPaletteEffect`.

**Comment by reaperrr** [comment]
The original game used both approaches, a `Normalized=yes/no` for the whole art.ini entry (yes = affected by map lighting), and hardcoded for the indices 240-255 of the player palette.
My attempt to implement the latter has failed though, so for now I've removed the palette stuff and changes this PR to just fix the overlay anims.

**Comment by ltem** [comment]
:+1: 
- Code is fine
- My issue is fixed 
image

**Review by pchote — APPROVED** [review]
Confirmed that these are indeed supposed to be idle lights, and that they look correct ingame.  :+1:

**Pull request merged**
