### PR TITLE
Allies-02: Fix mission timer on medium difficulty

### PR DESCRIPTION
**Pull request by simon-v**

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
:+1: Good catch.

**Comment by penev92** [comment]
Looks correct to me :+1: 
I'd like for @abcdefg30 to take a look, as he wrote that originally.

**Comment by abcdefg30** [comment]
Ops, seems like a copy-paste error. Thanks!

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/fc04f185052181dbe82f062970606394d718e4c0...dbe2066114345fdb66cd8e31c2578e6d06542cab)

**Pull request merged**
