### PR TITLE
Added a German translation for the Linux desktop entry

### PR DESCRIPTION
**Pull request by Mailaender**
This is exposed in KDE.

### CODE REVIEW

**Comment by obrakmann** [comment]
:/ I'd expect it to fall back to the generic name. Not a fan of adding translations for umpteen languages.

:+1:

**Comment by Phrohdoh** [comment]
This was created on upstream.

**Comment by deniz1a** [comment]
Translation is correct: http://de.wikipedia.org/wiki/Echtzeit-Strategiespiel

**Comment by abcdefg30** [comment]
Although I can't test it: This looks simple and reasonable enough, so :+1: / :white_check_mark:.

**Comment by Mailaender** [comment]
It adheres to the http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s04.html standard.

**Pull request merged**
