### PR TITLE
RA - Fix Veterancy removal on shellmap rules.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Since we moved GainsExperience inheritance from defaults to units, the current implementation on RA shellmap causes crashes if a unit without GainsExperience kills something somehow (i.e Crushing).

D2k Shellmap seems to be already set up this way.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
I tryed to use wall change as a workaround for the yaml merging issue but it didn't work for travis even tho worked for me locally. But i'm gonna keep it, i still think walls on the shellmap should be indestructible.

**Review by obrakmann — DISMISSED** [review]
Works as advertised.  Could I ask you to fix the TS shellmap as well?

**Comment by MustaphaTR** [comment]
TS Shrllmap doesn't seem to have Veterancy removal at all do you want me to add it?

**Comment by reaperrr** [comment]
@MustaphaTR Yes, please do.

**Comment by reaperrr** [comment]
I think we want the invulnerable walls on the TS shellmap, too.
👍 after that.

**Comment by MustaphaTR** [comment]
Looking at the TS Shellmap, i feel like it needs way more work. Can we merge this as currently is and i do some further work on TS Shellmap in seperate PR?

**Comment by reaperrr** [comment]
Alright, in that case lgtm.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f15a4f9f85212afe6442656b0e74e73494cd92cd...4bf17e1f6b42082930f203a3083ea4f46143dece

**Pull request merged**
