### PR TITLE
Add a global script for campaign missions in d2k

### PR DESCRIPTION
**Pull request by abcdefg30**
Especially the AI methods were duplicated a lot. Fixes also some other bugs/oversights (+ general polish).

### CODE REVIEW

**Comment by MustaphaTR** [comment]
That last commit is only applied for Atr1 and Atr3. Har1 and Ord1 are also spice collecting missions.

It looks like AI is using starting units (given with lua as in [here](https://github.com/OpenRA/OpenRA/pull/13592/files#diff-47f393b674dafc25bbc86a322cb7ce64R34), not preplaced ones), that are meant to guard their base, to attack. It is pretty earlygame so it makes stuff a bit hard. They were previously added to IdlingUnits too, i'm not sure why it is happening now but didn't used to. Maybe we shouldn't add them to.

**Comment by abcdefg30** [comment]
> They were previously added to IdlingUnits too, i'm not sure why it is happening now but didn't used to. Maybe we shouldn't add them to.

Hm, that is weird. The should attack on latest bleed as well.

**Comment by MustaphaTR** [comment]
Oh, wait starting units is not the issue. On bleed AI doesn't attack with everthing they built/have in IdlingUnits, in this PR it does, causing attack force to bigger and harder to counter compared to bleed.

**Comment by abcdefg30** [comment]
> That last commit is only applied for Atr1 and Atr3. Har1 and Ord1 are also spice collecting missions.

Fixed.

> On bleed AI doesn't attack with everthing they built/have in IdlingUnits, in this PR it does, causing attack force to bigger and harder to counter compared to bleed.

Ah, I see. Fixed, thanks.

I also made the Fremen less aggressive on Atreides04 as discussed on IRC (a while back) and fixed some other bugs.

**Comment by ltem** [comment]
👍 
- Add a global script for campaign missions in d2k ✔️ 
- Add a warning when attacking the Outpost to ordos04 ✔️
- Fix the harvest protection logic ✔️
- Fix a bogus condition ✔️
- Add more fail conditions to the spice harvesting missions
- Let the fremen fallback in atreides04 instead of attacking the base ✔️
- Fix sietches being repairable and remove the Power trait (unused) ✔️
- Fix actors being able to walk on cliffs after the sietch was destroyed ✔️

**Review by ltem — APPROVED** [review]

**Review by MustaphaTR — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/34c94012aa600b559e85baf522f7609852021890...ec441379a36db8eb4b701af532006db241e669cf

**Pull request merged**
