### PR TITLE
Let spawned soviet vehicles attack move on Survival02

### LINKED ISSUE #10204: Survival 02
The first few heavy tanks just drive through the base without attacking.

On bleed.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29070942-survival-02?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #10204.

### CODE REVIEW

**Comment by obrakmann** [comment]
The mission is broken (on bleed, presumably) in other ways as well:
```
Exception of type `System.InvalidOperationException`: Unit `bomblet` does not have a sequence named `open`
```

**Comment by obrakmann** [comment]
Seems to work as intended on prep, :+1:

**Comment by penev92** [comment]
:+1:

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/pull/10206#issuecomment-164179944 is the same as on Fort Lonestar. See https://github.com/abcdefg30/OpenRA/commit/d9099b282fa8436596e98c5541f51d8687e3f55f.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/aa0f1c64f9e9ff49b38911ae9b0cb30861a52853...ec288016fa69a2a671c2fae6cf2869c306f57634)

**Pull request merged**
