### PR TITLE
Fix tree owner to Neutral for all trees on RA/TD maps

### PR DESCRIPTION
**Pull request by reaperrr**
Otherwise AI squads will try to attack them and get stuck (because only flame units can damage them).

### CODE REVIEW

**Comment by pchote** [comment]
Do we want some kind of lint rule to enforce this?

**Comment by GraionDilach** [comment]
What property would you base such a rule on? I can only imagine such a lintrule working if we add a trait specifically to these kind of actors and the lintrule would then check for the ownership of the actors with that trait.

**Comment by pchote** [comment]
> add a trait specifically to these kind of actors and the lintrule would then check for the ownership of the actors with that trait.

Yes, exactly.

**Comment by GraionDilach** [comment]
In that case, I can get behind that idea.

**Comment by reaperrr** [comment]
It would be even better if we could enforce this (Neutral owner) in the editor as well if the actor has that trait, because forgetting to change the player before placing trees can happen easily and fixing it manually is only really feasible via text editor, which requires unzipping/saving unpackaged, making the whole process a pain.

**Comment by reaperrr** [comment]
Updated, fixed all other maps as well.

The trait + lint check I used to identify them will come in a separate PR.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5fd608f6cb1470ef5b51d335bbb4e8a08f14b2cd

Picked to prep: ced9ff26b509c1c2dab1c0924a75d1b2ee47d713, 9d0d25eca6b576943dcd0daede894cdf1756b4f1

**Pull request merged**
