### PR TITLE
Fix the positioning of the mute label in the TD music player

### LINKED ISSUE #11894: Bogus mute notification position in TD music player.
screen shot 2016-08-27 at 11 12 50

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #11894.

tdmute2

For reference, the outdated look:
tdmute

### CODE REVIEW

**Comment by pchote** [comment]
This breaks our TD theme conventions... the label should move up, instead.

**Comment by abcdefg30** [comment]
Updated:
tdmute2

**Comment by obrakmann** [comment]
works for me, :+1:

**Comment by pchote** [comment]
That looks better, thanks.

Can you please fix the label positioning in the lobby too? (for all mods)

screen shot 2016-08-28 at 12 26 43

**Comment by abcdefg30** [comment]
Done:

tdmute3

**Comment by pchote** [comment]
:+1: and https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0e57fa3c94544544218933a809fb6ec1a3fc29c4

**Pull request merged**
