### PR TITLE
Fix incorrect "In progress" time shown in server browser

### PR DESCRIPTION
**Pull request by cjshmyr**
This fixes a couple problems. The in progress time should be using `TotalMinutes`, and we should be treating the local machine's current time as UTC to match the master server.

### CODE REVIEW

**Comment by obrakmann** [comment]
Looks ok and works for me. :+1:

**Comment by RoosterDragon** [comment]
You might want to consider using `DateTime.TryParse` instead of `string.IsNullOrEmpty` to guard against invalid stuff sent by the server (since you've removed the try-catch).

**Comment by atlimit8** [comment]
I agree.

**Comment by cjshmyr** [comment]
I think that try/catch was spurious to begin with (it was there to catch the NRE I replaced it with), shouldn't we fix bad dates if there are on the master server instead?

The master server sets dates like using php's `date('Y-m-d H:i:s')` which seems okay, though I won't argue if I'm the minority here

**Comment by atlimit8** [comment]
It is both better form to use `TryParse*` where parsing may fail and more efficient since parsing has to check for those cases anyways.

**Comment by cjshmyr** [comment]
Updated.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/37b16d2ead6a0eca235cedb48ab9408cae2b072b...9c1e73d685038896a4ed72ced7b5d23b6c6c6110)

**Pull request merged**
