### PR TITLE
Fixes D2K not finding paratrooper shadow sequence

### PR DESCRIPTION
**Pull request by matija-hustic**
Fixes regression from #8339

https://github.com/OpenRA/OpenRA/pull/8339/files#r34637358

The engine wasn't able to locate the sequence. I haven't gone deeply into it, but it seems all sequences in d2k/sequences/misc.yaml specify the exact file where the sequence resides...

### CODE REVIEW

**Comment by penev92** [comment]
Works :+1:

**Comment by reaperrr** [comment]
I think the d2k mod defaults to `.r8` extension, that's why it didn't find the `.shp`.

**Comment by pchote** [comment]
>  it seems all sequences in d2k/sequences/misc.yaml specify the exact file where the sequence resides...

This has been the case ever since #7733.

**Comment by matija-hustic** [comment]
Changed the name

**Comment by abcdefg30** [comment]
Looks good to me two. :+1: / :white_check_mark: 
I get another crash when paradroping though.
I filed another followup PR: #8720

**Pull request merged**
