### PR TITLE
Server main loop performance optimization.

### PR DESCRIPTION
**Pull request by anvilvapre**
Create checkRead list once.
Search Socket in with checkReadServer only if server sockets in checkRead list.
Avoid LINQ in matching socket with connection.
Search Socket in Conns before PreConns, more chance to find it earlier.
Cache ITIck traits.

See 18804.

### CODE REVIEW

**Comment by deleted-user-1** [comment]
If this PR fixes the points you listed in #18804, the issue can be closed automatically when this PR is merged by editing your first comment and adding 

`Fixes #18804` or `Closes #18804`.

**Comment by adammitchelldev** [comment]
I'd expect the performance improvement here to be extremely negligible, this loop is not "hot", it will only loop either once per second or every time a packet is received, which should at maximum be 8 players * 32 packets per second (16 order packets and 16 sync hashes on fastest speed) = 256 times per second (plus a few extra for chat messages). The other stuff that happens in the loop in response to reading a client packet will be significantly heavier than anything that happens here.

**Comment by pchote** [comment]
@adammitchelldev is this going to conflict with your net code rework if we were to merge it?

**Comment by adammitchelldev** [comment]
> @adammitchelldev is this going to conflict with your net code rework if we were to merge it?

I believe so.

**Comment by anvilvapre** [comment]
Perhaps this could now be merged first. Now that the net code will be surpassed by another pull request.

**Comment by pchote** [comment]
In any case this would need to be rebased and updated to account for the server connection changes that are already merged.

**Comment by anvilvapre** [comment]
Code changed so much that these changes no longer make sense.

**Pull request closed without merging**
