### PR TITLE
Try to fix the AppVeyor build

### PR DESCRIPTION
**Pull request by Mailaender**
Hopefully the last CI regression from https://github.com/OpenRA/OpenRA/pull/7510#issuecomment-80014679.

### CODE REVIEW

**Comment by DeadlySurprise** [comment]
Sadly I don't think this will fix the problem, as the issue seems to be the include file not the dll. Could you add a `dir %NSIS_ROOT%` and  `dir %NSIS_ROOT%\include` (if something like that even works)?

**Comment by Mailaender** [comment]
I think it will as `Processing plugin dlls: "C:\nsis\Plugins\*.dll"` is printed before it fails. https://ci.appveyor.com/project/OpenRA/openra/build/1.0.1536#L193

**Comment by Mailaender** [comment]
Added the `%NSIS_ROOT%` prefix as suggested.

**Comment by DeadlySurprise** [comment]
> Added the %NSIS_ROOT% prefix as suggested.

I meant using the `dir` command to see what files/folders are created inside the NSIS directory, if that’s possible in AppVeyor. It is possible that 7zip doesn’t directly extract the files but instead creates a folder NsProcess first or something like that.

**Comment by Mailaender** [comment]
https://ci.appveyor.com/project/OpenRA/openra/build/1.0.1536#L153 shows quite clear that the problem is Plugin vs Plugins. If that also fails, I will need to investigate deeper or simply revert https://github.com/OpenRA/OpenRA/issues/7510.

**Comment by obrakmann** [comment]
[This line](https://ci.appveyor.com/project/OpenRA/openra/build/1.0.1536#L193) (Processing plugin dlls: "C:\nsis\Plugins\*.dll") makes me believe Mailaender is right, although the error message misleadingly points to the .nsh file and not the .dll.

:+1:

**Comment by penev92** [comment]
OK, let's give it a shot :+1:

**Comment by Mailaender** [comment]
```
move %NSIS_ROOT%\Plugin\nsProcess.dll %NSIS_ROOT%\Plugins\nsProcess.dll -force
The syntax of the command is incorrect.
```

WTF Windows.

**Comment by ScottNZ** [comment]
Where did you get `-force` from?

**Comment by Mailaender** [comment]
Filed a fixup of the fixup at https://github.com/OpenRA/OpenRA/pull/7667.

**Pull request merged**
