### PR TITLE
Prevent crash when unloading Cargo structures

### LINKED ISSUE #16914: Crash when undeploying pileboxes
```
Exception of type `System.InvalidOperationException`: Actor hbox does not have trait of type `OpenRA.Mods.Common.Traits.Mobile`
   at OpenRA.TraitDictionary.TraitContainer`1.Get(Actor actor)
   at OpenRA.Mods.Common.Activities.Move..ctor(Actor self, CPos destination, WDist nearEnough, Actor ignoreActor, Boolean evaluateNearestMovableCell, Nullable`1 targetLineColor)
   at OpenRA.Mods.Common.Activities.UnloadCargo.OnFirstRun(Actor self)
   at OpenRA.Activities.Activity.TickOuter(Actor self)
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

### PR DESCRIPTION
**Pull request by teinarss**
Fixes #16914

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Bug and fix confirmed. Approving after somebody confirms that this an expected change.

**Comment by pchote** [comment]
Minor nit: Can you please fix "pileboxes" &rarr; "pillboxes", or even better &rarr; "Cargo structures" in the commit message?

**Comment by teinarss** [comment]
Updated

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
Seems like #16509 doesn't have a changelog, so skipping here as well.

**Comment by pchote** [comment]
Added both in https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/74585499656164be42c01006f450250f16d442e2

**Pull request merged**
