### PR TITLE
Remove ingame assets installation from the remaster

### PR DESCRIPTION
**Pull request by abcdefg30**
Nobody addressed https://github.com/OpenRA/OpenRA/pull/18254#issuecomment-644947899 yet, which means using these will lead to new cases of #18882 and #18828.

### CODE REVIEW

**Comment by PunkPun** [comment]
The modular installer is not part of stable so I'm not sure wether this works for prep @Mailaender ?

**Comment by IceReaper** [comment]
Got it fixed, pr will be incomming soon ;)

**Comment by IceReaper** [comment]
Tbh, i think this pr can be closed now :-P

**Comment by abcdefg30** [comment]
I guess we could still take the first commit, otherwise yes.

**Comment by IceReaper** [comment]
Oh! A leftover, sorry for that! I agree

**Comment by pchote** [comment]
#20602 was merged, needs rebase.

**Comment by abcdefg30** [comment]
Rebased.

**Review by penev92 — APPROVED** [review]

**Pull request merged**
