### PR TITLE
Added an error message when setting up upgrades without UpgradeManager

### PR DESCRIPTION
**Pull request by Mailaender**
A major downside from actor upgrades is that they can be setup in ways where nothing happens and you don't get any feedback why. This should help reduce the annoyance. Split from https://github.com/OpenRA/OpenRA/pull/11405.

### CODE REVIEW

**Comment by pchote** [comment]
Can you please fix the `CheckUpgrades` lint test instead of adding runtime-only code for this?

**Comment by Mailaender** [comment]
Good idea. That also gives more specific error messages.

**Comment by obrakmann** [comment]
:+1:

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/338916fa730db81da97a43de422d5781a20d08d9...f009259e41a5b4d97314fcea9dcc8981160c6fc6)

**Pull request merged**
