### PR TITLE
Fixed WithBarrel and made it upgradable

### LINKED ISSUE #8439: WithBarrel appears to be broken
...Since at least 5 months.

I guess this can happen if a trait is rarely ever used.

As testcase, add
```yaml
WithBarrel:
		  Barrel: leftarm
		  Sequence: turret
		  LocalOffset: 0,-768,0
```

to RA's cruiser (CA). 
With release 20141029 it will show a 3rd turret via `WithBarrel`, with anything from this year it crashes:

```
Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Die Sequenz enthält kein übereinstimmendes Element.
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   bei OpenRA.Mods.Common.Traits.WithBarrel..ctor(Actor self, WithBarrelInfo info)
   bei OpenRA.Mods.Common.Traits.WithBarrelInfo.Create(ActorInitializer init)
   bei OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in e:\OpenRA_work2\OpenRA.Game\Actor.cs:Zeile 110.
   bei OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) in e:\OpenRA_work2\OpenRA.Game\World.cs:Zeile 234.
   bei OpenRA.World.CreateActor(String name, TypeDictionary initDict) in e:\OpenRA_work2\OpenRA.Game\World.cs:Zeile 229.
   bei OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   bei OpenRA.World.LoadComplete(WorldRenderer wr) in e:\OpenRA_work2\OpenRA.Game\World.cs:Zeile 215.
   bei OpenRA.Game.StartGame(String mapUID, WorldType type) in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 159.
   bei OpenRA.Game.LoadShellMap() in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 380.
   bei OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   bei OpenRA.Game.InitializeMod(String mod, Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 372.
   bei OpenRA.Game.Initialize(Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 264.
   bei OpenRA.Program.Run(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:Zeile 109.
   bei OpenRA.Program.Main(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:Zeile 39.
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/20895298-withbarrel-appears-to-be-broken?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #8439.

Additionally makes trait upgradable and damage-normalized.

### CODE REVIEW

**Comment by reaperrr** [comment]
Test case needs to be removed before merge, obviously.

**Comment by Mailaender** [comment]
Needs a rebase.

**Comment by reaperrr** [comment]
Rebased.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark: Test case https://github.com/reaperrr/OpenRA/commit/1216168983f6dabc19d0dd25cdbe9b982d83d00e needs to be removed.

**Comment by reaperrr** [comment]
Updated, test case removed.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0b0d1d7265574ea71beb608c90d02d7a43194348...79d4d6f8b142ae32cbf30bb93756e6e0841afea2)

**Pull request merged**
