### PR TITLE
Replace WithReloadingSpriteTurret with conditions

### PR DESCRIPTION
**Pull request by reaperrr**
`WithReloadingSpriteTurret` would be bound to run into conflicts with any `WithTurret*Animation` traits sooner or later due to overriding the turret sequence constantly via `Tick`.
Using (stacked) conditions instead avoids that.

Split from #14036.

### CODE REVIEW

**Comment by reaperrr** [comment]
Rebased to fix AppVeyor build failure.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by reaperrr** [comment]
This has a +1 from a known reviewer and I tested this extensively myself, so I'll go ahead an merge it now. If any issues were overlooked, I'll fix them in a follow-up.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ad98895675fe2bee9a7000cd607b74bffe669928...29d4d2961f33be061eafde10e518ad4f57789a80

@GraionDilach I fixed the ActorSpawnManager upgrade rule date with this PR.

**Pull request merged**
