### PR TITLE
Move package loaders to mod code.

### PR DESCRIPTION
**Pull request by pchote**
This is the final followup item from #13223.

This also marks a notable milestone: our core engine is now, except for the voxel loader, completely clean of format loaders or other algorithms used by the original games.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Review by rob-v — APPROVED** [review]
👍 
I am not sure how important it is to run some (and which) utility commands for test.

**Comment by abcdefg30** [comment]
Needs a rebase.

**Comment by pchote** [comment]
Rebased.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ed367776a6a27f1803b48a212966c782ca68f89e...acd7454f571d1e0fbfe97c9f6742eba79a35e9f3)

**Pull request merged**
