### PR TITLE
[RA] Add/remove official maps.

### PR DESCRIPTION
**Pull request by SoScared**
There's quite a few great maps out there that warrants a new map pool overhaul. Before I eventually take steps towards that I just want to quickly add/remove these for our team playing enthusiasts.

**Adding:**

- Countercross (8 players): http://resource.openra.net/maps/17651/

**Removing:**

- Blitzkrieg (8 players): http://resource.openra.net/maps/12996/
- Hopes Anchor (8 players): http://resource.openra.net/maps/12672/

Hopes Anchor being one-of-a-kind "capture the flag"map in the map pool too often creates confusion as players both new and old often don't know how to approach the game properly, resulting in one-sided matches and general disbelief. Blitzkrieg doesn't seem to go anywhere. Was also suggested for removal last time around.

Countercross is spacious, asymmetric yet fairly balanced and well designed. Seems to produce enjoyable games consistently . 
countercross

- - - - - - -

**Disallow bots:**

- Countercross
- Bombardment Island

### CODE REVIEW

**Comment by SoScared** [comment]
Added commit disallowing bots on official island maps.

**Review by pchote — APPROVED** [review]

**Comment by abcdefg30** [comment]
👎 to removing bots from `Bombardment Islands`. They always did behave well for me on that map.

**Comment by SoScared** [comment]
Regarding bots I have no opinion on the matter. But I see the point of having a standard to follow to make things more clear and easy for future map reviews.

Do we go by "either/or" or evaluate bots per map review?

**Comment by pchote** [comment]
@SoScared For the sake of getting this merged, lets just reenable bots on both maps.

**Comment by SoScared** [comment]
Done.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bc0a36df86554a801e753b19e54739ed070f4224...1ee82c2bfbade1c0ae099c8e1d136769a27dcd65)

**Pull request merged**
