### PR TITLE
Remove the copyright year numbers

### PR DESCRIPTION
**Pull request by abcdefg30**

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]

**Comment by PunkPun** [comment]
Will we need a separate PR for prep?

**Comment by abcdefg30** [comment]
Unless prep has new files that don't exist on bleed, we should be able to cherry pick the commit cleanly.

**Comment by PunkPun** [comment]
It most definitely does

**Comment by pchote** [comment]
Not a fan of updating the copyright headers every year - its bogus from a legal/license perspective (making a false claim extending the copyrighted life of the file) and makes it harder to see when files were really last edited.

IMO we should either remove the dates completely by changing the header to something like:
```
/* 
 * Copyright (c) The OpenRA Developers and Contributors
 * (see Git metadata for a list of authors and dates)
 * 
 * This file is part of OpenRA, which is free software. It is made
 * ...
```

or write proper scripts to detect and lint-fail files that are updated with a mismatched header date, and update files only when they change.

**Comment by Mailaender** [comment]
https://hynek.me/til/copyright-years/

**Comment by abcdefg30** [comment]
Changed to
```
  * Copyright (c) The OpenRA Developers and Contributors
  * This file is part of OpenRA, which is free software. It is made
  * available to you under the terms of the GNU General Public License
  * as published by the Free Software Foundation, either version 3 of
  * the License, or (at your option) any later version. For more
  * information, see COPYING.
```
None of the examples I saw referenced from https://hynek.me/til/copyright-years/ mentioned the git history directly, so I didn't include it either.

**Review by Mailaender — APPROVED** [review]

**Review by PunkPun — APPROVED** [review]

**Comment by Mailaender** [comment]
> None of the examples I saw mentioned the git history directly, so I didn't include it either.

As we also provide source tarballs, this was a good choice.

**Pull request merged**
