### PR TITLE
Added original TS maps Tactical and Terraces

### PR DESCRIPTION
**Pull request by Mailaender**
Both maps are very open which is good for gameplay. They also don't have bridges.
- http://resource.openra.net/maps/8526/
- http://resource.openra.net/maps/8525/

### CODE REVIEW

**Comment by reaperrr** [comment]
> Both maps are very open which is good for gameplay. They also don't have bridges.

Should be good for performance too, wrt path-finding and AI.

**Comment by Mailaender** [comment]
Indeed. https://github.com/OpenRA/OpenRA/pull/10458 for example is very choked by cliffs and trees.

**Comment by obrakmann** [comment]
I'm not sure if the tiberium distribution on either map is balanced fairly, but I guess Westwood knew what they were doing. :+1:

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
