### PR TITLE
Change TD water crossings to Rough terrain

### PR DESCRIPTION
**Pull request by Smittytron**
After #14844 was merged it was pointed out to me that it is also possible to build on shallow river crossings.

### CODE REVIEW

**Comment by fruestueck** [comment]
Personally i am in favor of this but i shlould mention:
This was possible in the original. Also it would change gameplay of one or two maps.

**Comment by Smittytron** [comment]
> This was possible in the original. Also it would change gameplay of one or two maps.

Yeah, I polled the TD players via discord to make sure there weren't objections before doing this. Blocking narrow crossings and bridges is viewed as something that inhibits fluid gameplay.

**Review by abcdefg30 — COMMENTED** [review]
One can still place buildings on some parts of the crossing, which looks a bit odd to me:
tdcrossing
Intentional?

**Comment by Smittytron** [comment]
Guess I thought those were one cell. Updated.

**Review by abcdefg30 — DISMISSED** [review]
Looks good to me now.

**Comment by reaperrr** [comment]
IMO these still need some work.
The desert crossings are particularly bad:
riv-cross2

'Red' means the cell is buildable on even though it doesn't look like it should be, green are cells that are *not* buildable on even though they look like they should be. Keep in mind desert aren't visually aligned with their counterparts from other tilesets.

The rest looks better, but at least the top-left corner of vertical crossings should also become Rough on all non-desert tilesets:
riv-cross1-1

Finally, on the jungle tileset, the two top corners of the horizontal crossing visually look like they shouldn't be buildable on, either.
riv-cross3

**Comment by Smittytron** [comment]
Updated. Went with Rock over Rough for the cells that looked bad with a tank on it.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
@abcdefg30 are you fine with the latest changes?

**Comment by pchote** [comment]
Are we sure this won't regress anything in the campaign?

**Comment by reaperrr** [comment]
> Are we sure this won't regress anything in the campaign?

Pretty sure, there weren't any missions that encouraged - let alone required - you to build past a crossing.
The only mission I remember that has a crossing close enough to base to be relevant was one of the 5th GDI missions, which doesn't have a cyard anyway (same for the gdi8-austria mission).
It might indirectly make some other missions a bit more difficult, but we're not matching the original in that regard anyway.

**Comment by Smittytron** [comment]
I did a once-over of current campaign maps. Didn't see any actors on the affected tiles and buildings should be fine as well.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0c80b8a6e84a4d09b70fe0fbab6d2b0e22d72929...7ba7c128d002544e13540e7140540170df4c7430)

**Pull request merged**
