### PR TITLE
Added a lighthouse to the Red Alert civilian buildings

### PR DESCRIPTION
**Pull request by Mailaender**
Screenshot

### CODE REVIEW

**Comment by Phrohdoh** [comment]
You use `windmill` for Nooze's windmill, so can we use `lighthouse` here, instead of `lhus`?

**Comment by pchote** [comment]
```
paul@MacBook-Air:OpenRA+pr/7923$ mono OpenRA.Utility.exe ra --check-sequence-sprites
Tileset: Snow
	File not found: lhus.shp
	File not found: lhus.shp
Tileset: Interior
	File not found: lhus.shp
	File not found: lhus.shp
Tileset: Temperate
	File not found: lhus.shp
	File not found: lhus.shp
Tileset: Desert
	File not found: lhus.shp
	File not found: lhus.shp
```

**Comment by Mailaender** [comment]
Fixed.

**Comment by MicroJOo** [comment]
:+1: 

some

**Comment by pchote** [comment]
Could you please trim down those selection bounds on both? They look far too large atm.

**Comment by Mailaender** [comment]
Updated both.

**Comment by abcdefg30** [comment]
Looks good to me and works ingame. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/36eb5e4fb5ebc7c0ad96357c72594118c54c1f76...4863d3d4e70b9130ac096f92054c890d3f279819)

**Pull request merged**
