### PR TITLE
Rebalance doubles.oramap in RA mod

### PR DESCRIPTION
**Pull request by ghost**
Since it was a simple update after redoing singles, here is doubles.

map on resource centre http://resource.openra.net/maps/8276/ (parsed on bleed...)

For those that wondered, apart from more spawns, the original (and this re-imagined) version of doubles has slightly more ore than singles.

### CODE REVIEW

**Comment by r34ch** [comment]
Updated with fixed map size, decorations and improved spawn placements.

**Comment by Mailaender** [comment]
Map borders are sane now, no tiling errors spotted and the additional details adds polishing. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/7165d4bd0d23938c52a1315d86cf5d514827a154)

**Comment by SoScared** [comment]
Following the same argument as shared on #10301, I made a version reverting some of the aesthetic add-on to allow for more build space. Also, altered the ore patches a bit:

http://resource.openra.net/maps/9487

doubles compare piz

doubles compare piz

**Pull request merged**
