### PR TITLE
Don't do trait lookups for Health on each processed order

### PR DESCRIPTION
**Pull request by penev92**
A small random fix that will save _a ton_ of unnecessary trait lookups.

### CODE REVIEW

**Comment by cjshmyr** [comment]
Out of curiosity does anyone know why there's two separate IsDead checks in the engine? [Actor](https://github.com/OpenRA/OpenRA/blob/34cd7173499ac7c6c8f0d85ecb299102caf92d70/OpenRA.Game/Actor.cs#L54) vs [Health](https://github.com/OpenRA/OpenRA/blob/89a1bdd4f15d7a960a9ece1e89181b440a839705/OpenRA.Game/Traits/Health.cs#L56)

**Comment by penev92** [comment]
The one in `Actor` just caches the `Health` trait and then uses its check.

**Comment by cjshmyr** [comment]
I guess what I'm wondering is if there's other wins to be made by referencing the cached actor check, in some cases we do explicitly use `Health.IsDead` but I can't see why anymore. Doesn't need to be addressed in this pull :)

**Comment by penev92** [comment]
I assume all (or at least most) of those are leftovers from simpler times:
>[19:16] <+pchote> we never used to cache traits, so there used to be hundreds of thousands of unnecessary lookups done per tick

I can see if I can address some of the other use-cases of `Health.IsDead` later if this is still open.

**Comment by obrakmann** [comment]
Makes sense :+1:

**Comment by pchote** [comment]
:+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/48e20468cc1aa25c572da4a69eec03131c49db12%5E...48e20468cc1aa25c572da4a69eec03131c49db12

**Pull request merged**
