### PR TITLE
ra: Remove caffeinated, snowy-ridge

### PR DESCRIPTION
**Pull request by chrisforbes**
These are both terrible.

Caffeinated is my old RA95 study of how much
detailing you could get away with; it has horribly unbalanced resources
and spawn locations.

Snowy-ridge is a 1v1v1 so small that you can shoot from one base to
another, and the bottom player has a serious disadvantage.

Signed-off-by: Chris Forbes chrisf@ijw.co.nz

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: They are archived at:

* http://resource.openra.net/maps/7369/
* http://resource.openra.net/maps/7996/

**Comment by abcdefg30** [comment]
:+1:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a878fa0d0536b43c64cfb87aac4dafa900d96a79...c0c58d717734c7880e865ca38bfc4d6aeb74ad3d)

**Comment by MustaphaTR** [comment]
I'm not conviced about removal of Snowy Ridge. I like and play on that map but as can grab it from resource center not that much problem.

**Comment by Micr0Bit** [comment]
@MustaphaTR : neither am i ... but @Mailaender and @abcdefg30 just bypassed the discussion that is going on here https://github.com/OpenRA/OpenRA/issues/10708

here is a nice example of their so called "open source thinking" ... and making decisions

while other PR's stay forever , this particular one gets forced in within 4 hours , while at the same time a discussion is going on about it

**Comment by Mailaender** [comment]
I simply wasn't aware of the discussion. It wasn't referenced in this pull request.

**Comment by SoScared** [comment]
Reworked Snowy Island  #10718 to make it balanced and shuffled the ore around.

As mentioned there's a lack of 1v1v1 maps. I think this map should stay put for now.

**Comment by chrisforbes** [comment]
Make snowy-ridge better through the resource center process. Don't ship it in a bad state.

**Comment by SoScared** [comment]
[Bloody Delta](http://resource.openra.net/maps/7286/)
[Temperal](http://resource.openra.net/maps/7233/)
[Caffeinated](http://resource.openra.net/maps/7369/)
[Raraku](http://resource.openra.net/maps/7179/)
[Coastal Influence](http://resource.openra.net/maps/7618/)

These are maps that contrast the perfect symmetry ones. I think it's a good Idea having some of these around to offer casuals natural looking - non competitive maps.

I also prefer Caffeinated over Raraku. They're similar but it's easier to pull off a 4v4 on the former.

**Pull request merged**
