### PR TITLE
Added the new modular build palette to Dune 2000

### LINKED ISSUE #3699: The build palette isn't big enough to display all buildings of all factions
The Build Palette isn't big enough to display all possible builidngs (after enabling "Build Everything" in the Cheats menu).

What about adding extra tabs, one for each faction : 

build_evertything_tabs

This way, it would be possible to filter the buildings.

Here are the logos (PNG):
build_evertything_tabs2

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/820639-the-build-palette-isn-t-big-enough-to-display-all-buildings-of-all-factions?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6043: New D2K UI
In order to harmonize interfaces accross mods (see #5972 and #5108), here are some proposals about a possible new Dune2000 UI. For the moment, they are just WIP, mockups, ideas.

test1:
dune2000_test1b

test2 (the one I like least):
dune2000_test2

test3:
dune2000_test3

As you can see, the color of the small planet in the middle could change, depending on the faction (blue: atreides, green: ordos, red: harkonnen). Or maybe we want the whole UI to change its color, something like that: http://forum.dune2k.com/topic/25963-release-dune-2000-resource-editor/  ?

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/3285282-new-d2k-ui?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes #3699
Closes #6043

### CODE REVIEW

**Comment by huwpascoe** [comment]
This is a great change! :+1:

**Comment by huwpascoe** [comment]
Hm, after a bit more testing, I think it needs the feature where it changes to the appropriate queue when you click on the structure? (assuming this is in the scope of ui)

**Comment by Mailaender** [comment]
This is fixed now.

**Comment by huwpascoe** [comment]
:+1: All good!

**Comment by penev92** [comment]
Note: With the new UI, we can now add hotkeys to the production tabs (right?).
Not necessarily in this PR, but if you can... (while @x-a-n-a-x is fixing the buttons).

**Comment by penev92** [comment]
With all the discussion and @x-a-n-a-x's latest changes to his checklist at https://github.com/OpenRA/OpenRA/issues/6043#issuecomment-71561491, I'd like to see this updated with his latest work before we proceed.

**Comment by Mailaender** [comment]
The problem is that @x-a-n-a-x repository is very experimental and not quite stable. I will try to cherry-pick and finish this, probably at the weekend. Especially the new order buttons. I am not so sure if the woodgrain may work when repeated. This is already a problem for the leather buttons and the reason I decided to go with the simple border and stripes.

**Comment by Mailaender** [comment]
Updated. I reverted back to @x-a-n-a-x's repetitive wood grain and the recent order button additions from https://github.com/Mailaender/OpenRA/pull/53/ including the common queue button background. I fixed all the order button that were pointing at the wrong coordinates in that branch and removed the now needless `AddRaceSuffixLogic` everywhere.

**Comment by Mailaender** [comment]
Second :+1: from https://github.com/OpenRA/OpenRA/issues/6043#issuecomment-73519560.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e379847e086c9724e17260d1de593d29e306ef73...a4a32710abc572c8a0bf9a4889d6f5d7f516ca0b)

**Comment by Mailaender** [comment]
Another slight regression that slipped through is the hotkeys not working. This is fixed by https://github.com/OpenRA/OpenRA/issues/7541.

**Pull request merged**
