### PR TITLE
[RA] Add/remove official maps 2.

### PR DESCRIPTION
**Pull request by SoScared**
Just to note in the interest of the ongoing map contest (ending Feb. 28th) I'm leaving out these maps as candidates for map swap PR's. These can easily be brought forth later after an official playtest has been released.

**Adding:**

- Green Belt (2 players): http://resource.openra.net/maps/19254/
- Snow Off (2 players): http://resource.openra.net/maps/14675
- Ensio Kaivo (3 players): http://resource.openra.net/maps/19255/
- Minor Pressure (4 players): http://resource.openra.net/maps/19257
- Vihaan Lunta (4 players): http://resource.openra.net/maps/19256/

**Removing:**

- Forest Path (2 players): http://resource.openra.net/maps/13032/
- Man to Man (2 players): http://resource.openra.net/maps/12875/

**Alter:**

- Desert Rats (2 players): http://resource.openra.net/maps/17961/
- Dual Cold Front (2 players): http://resource.openra.net/maps/19086/

- - - - - - - -

Forest Path will forever ingrain itself as the map showcasing OpenRA on TotalBiscuit's first impression review in 2014. But in all seriousness this map has IMO played out its role even after being heavily revised and balanced in before release2016.0508. Casual or competitive, afaik nobody plays it anymore.

### CODE REVIEW

**Comment by ChristianDK** [comment]
I think we should keep in mind that we need to have a diverse map pool. A lot of the new maps which have been added recently are all big, open and high eco. We need smaller and low eco maps as well.

If Forest Path is taken out then I think it could be replaced by Snow Off by Aaron Lloyd: http://resource.openra.net/maps/14675

This map is rather similar to Forest Path but way better. Of 1v1 maps I would remove man to man from the map pool.

**Comment by SoScared** [comment]
@ChristianDK yeah can't argue with that. The map pool certainly is moving fast towards big, open map styles.

I'll add Snow Off to the commit first thing tomorrow.

**Review by pchote — APPROVED** [review]
These look reasonable, so i'll trust your judgement as our resident RA map expert :+1:

**Review by abcdefg30 — APPROVED** [review]
Bye Forest Path 😢

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c33ae2b6c1823075a7099ff8782b20d016064ad8...c135bc3099ff7ca5b00dae6414d952ee6dbc2a46)

**Pull request merged**
