### PR TITLE
D2K - 3 Ornithopter

### PR DESCRIPTION
**Pull request by MustaphaTR**
I added this before but possibelly @pchote broke it when adding Race Specific Art.

### CODE REVIEW

**Comment by penev92** [comment]
Actually I don't recall them being 3 in OpenRA, so I'd say it's older than that.

**Comment by MustaphaTR** [comment]
The older pull request is #6315

**Comment by penev92** [comment]
:+1:

**Comment by pchote** [comment]
Confirmed that this fixes a regression from #7477.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/3278c9ff65d3d3aa127ec735462d132d45c4643e%5E...3278c9ff65d3d3aa127ec735462d132d45c4643e

**Pull request merged**
