### PR TITLE
Adding starting cache 0$ selection

### PR DESCRIPTION
**Pull request by Nacht-Reiter**
Issue #14937
Added 0$ selection for all modes, should I do it only for "crates"?

### CODE REVIEW

**Comment by abcdefg30** [comment]
Looks good to me codewise. I'm just not sure if this makes sense from a gameplay point of view. Normal maps can't really be started with zero starting cash. So it would indeed sounds logical to only add this setting to our dropzone ("crates only") maps.

**Review by chrisforbes — CHANGES_REQUESTED** [review]
I agree with @abcdefg30  -- this doesn't make sense for the bulk of maps.

We should only expose this for maps that want it -- they already require custom rules IIRC?

There might be a third way, though: if "crates" is a consistent set of rules and is popular enough, should we have a shared set of rules that define the game mode, easily includable?

**Comment by pchote** [comment]
@chrisforbes: I guess this is covered by #10367?  @obrakmann was close to having something ready to PR, but it looks like this wasn't pushed to his fork.

**Comment by pchote** [comment]
Sorry @Nacht-Reiter, I see that #14937 had the "Easy" label attached, which isn't really appropriate for potentially controversial features.  Please drop in the IRC channel if you are looking for ways to get involved and we can try and find something else!

**Comment by obrakmann** [comment]
@pchote: sorry, I only noticed your comment now. What I did for #10367 isn't quite the same. Or, it would be if those rules could be written as a *VictoryConditions trait, but the issue sounds a bit different to me. Anyway, I've pushed the branch now: https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:new-game-modes

**Pull request closed without merging**
