### PR TITLE
add /lib and /lib64 to the locations lookup for Lua

### LINKED ISSUE #7637: add /lib to lua search path in configure script
the title says it all - if Lua is installed with prefix that is "/" instead of "/usr" the search will fail.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9405495-add-lib-to-lua-search-path-in-configure-script?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fluxer**
Fixes #7637

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: No regressions for me on openSUSE. :white_check_mark:

**Comment by obrakmann** [comment]
I'd have preferred if those two paths were tacked onto the end of the list, but I guess it doesn't make a difference in the end. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0d708e8d5ac187ffe0bfe8279df7da237ce7a644%5E...0d708e8d5ac187ffe0bfe8279df7da237ce7a644)

**Comment by fluxer** [comment]
Thanks for merging this.

**Pull request merged**
