### PR TITLE
Add competitive maps to the pool

### PR DESCRIPTION
**Pull request by ghost**
Adds the following maps into the map pool. Some of these maps are in the latest release but not on bleed.

Tabula rasa
http://resource.openra.net/maps/8174/

Tabula rasa has had a slight balance adjustment; The ridge and oil derricks on the top left have been moved right a few cells to allow base building similar to the bottom right. Various tiles fixed and some more decoration added to some bare areas.

Sidestep
http://resource.openra.net/maps/8176/

Behind The Veil (which I missed last time)
http://resource.openra.net/maps/8178/

All maps parsed on bleed

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by pchote** [comment]
Have you uploaded the tweaked version to the resource center?  We need all official maps to be available for the http://www.openra.net/games/ page.

**Comment by r34ch** [comment]
@pchote Yes all the maps are uploaded and linked above.

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f4bdce904a7b6908e56b939c6bdae4e4ca57abcb...77b31333cda8e11858e27f23e9713f1e72b07ef1)

**Pull request merged**
