### PR TITLE
AI AirAttackState fix

### PR DESCRIPTION
**Pull request by dnqbob**
1. consider the air-air threat in anti-air count

2. withdraw the units who are unattackable

3. scan anti-air around the team leader and escape when across the threshold

### CODE REVIEW

**Comment by dnqbob** [comment]
This function can be much better work with #17855. 
I mean it does not depend on it,  but random target scan can let AI air consider different target when attempt to attack,  without this commit AI air will always find the same target during attacks,  and perform advance&flee for a long time if anti-air block the way.

**Comment by dnqbob** [comment]
Rebase to newest commits to checkout conflicts

**Comment by reaperrr** [comment]
@dnqbob While testing this, I saw a bunch of AI MiG and Yak circling over an enemy refinery without shooting, because they were probably all out of ammo. However, they didn't try to reload, either.

**Comment by dnqbob** [comment]
> @dnqbob While testing this, I saw a bunch of AI MiG and Yak circling over an enemy refinery without shooting, because they were probably all out of ammo. However, they didn't try to reload, either.

@reaperrr  I think it is due to Protection Squad logic (at this moment the Aircraft is in fact controlled by Protection States, maybe during a counter attack from AI). The protection squad will pack up a big bunch of all kinds of units with ignorance on their ammo and AttackMove on target until target dies, which will lead to ammo based aircraft just circle upon enemy  if they run out of ammo. I [fixed that one](https://github.com/OpenRA/OpenRA/pull/17999) by introducing ammo load logic from Air Squad.

And in Protection Squad, there is a line:
```
			if (!owner.IsTargetValid)
			{
				owner.TargetActor = owner.SquadManager.FindClosestEnemy(owner.CenterPosition, WDist.FromCells(owner.SquadManager.Info.ProtectionScanRadius));
```
If Protection Squad killed the target and something happen to be in ProtectionScanRadius, protection squad will switch target. which may lead to they target refinery.

**Comment by dnqbob** [comment]
And another problem maybe those aircraft has auto-reload related trait. which will also cause AI aircrafts don't reload at airport.

**Comment by pchote** [comment]
I've noted this PR in #19247 to track this for the future, but for now are closing this to help address the unsustainable state of the PR queue.

**Pull request closed without merging**
