### PR TITLE
Add team chat for spectators

### LINKED ISSUE #2062: Spectator Team for Chat [$15]
Logically, spectators should be a different team so Team Chat in spectator mode would represent it.

<bountysource-plugin>
---
There is a **[$15 open bounty](https://www.bountysource.com/issues/98303-spectator-team-for-chat?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #2062.

### CODE REVIEW

**Comment by deniz1a** [comment]
When a player loses and becomes spectator, will he have the same team chat indicator as he did during game? Because that could be confusing, team chat would no longer mean the same thing.

**Comment by abcdefg30** [comment]
Unfortunately it doesn't do that, but it's also another issue, I think: #4772.

**Comment by pchote** [comment]
We should distinguish between spectator and team chat, in that case.

**Comment by abcdefg30** [comment]
Updated. Using `(Spectators)` instead of `(Team)` now.

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by MicroJOo** [comment]
does that mean , we want "defeated players" (therefor having fog and shroud turned off for him) ,  to still help their team by telling them in the teamchat what the enemy is doing ? 

so nobody else can read that ?

**Comment by pchote** [comment]
If the existing (before this pr) behaviour does that, then I don't think we need hold this PR up over it.  We should definitely switch players from team chat to observer chat at some point, though.

**Comment by MicroJOo** [comment]
true

**Comment by pchote** [comment]
The defeated team-mate case is best solved by #3210:
* If a player is on a team with at least one active player, then use the team-spec mode (no vis controls, regular team chat)
* If a player is not on a team, or everyone in their team is defeated then they all drop to the full spec mode (vis controls, spec chat).

**Comment by obrakmann** [comment]
:+1: works as advertised. As team-chat already doesn't work for dead players and cheating is thus not possible, I won't hold this up to require that dead players get switched to spec chat as well. #3210 indeed sounds like a better solution to that problem.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/478230707498f9c5de15e9da04514d86442816d1)

**Pull request merged**
