### PR TITLE
Fix the spacing at the end of the AUTHORS file

### PR DESCRIPTION
**Pull request by abcdefg30**
Polishes the ingame look.
Before:
endcredits
After:
endcreditsfixed

### CODE REVIEW

**Comment by pchote** [comment]
People keep on breaking this by helpfully "fixing" the AUTHORS file, and I'm sure it will happen again.  How about we fix this in the game instead?  I believe we have a specific ScrollPanel property for the end of list margin.

**Comment by obrakmann** [comment]
This will do it:
```diff
diff --git a/mods/cnc/chrome/credits.yaml b/mods/cnc/chrome/credits.yaml
index 3a806c8..1d90905 100644
--- a/mods/cnc/chrome/credits.yaml
+++ b/mods/cnc/chrome/credits.yaml
@@ -22,6 +22,7 @@ Container@CREDITS_PANEL:
                                        Y: 15
                                        Width: PARENT_RIGHT - 30
                                        Height: PARENT_BOTTOM - 30
+                                       TopBottomSpacing: 4
                                        Children:
                                                Label@CREDITS_TEMPLATE:
                                                        X: 8
```

**Comment by abcdefg30** [comment]
Thanks @obrakmann. Updated. I went for a spacing of `18` though to make it look like in the opening post:
endcreditsfixedtd
(The only downside here might be that we also get additional spacing at the top,
but I think that still looks ok.)

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
I am leaving this without a changelog as I can't reproduce the problem on the christmas release.

**Pull request merged**
