### PR TITLE
Port game speed selection to new lobby backend.

### PR DESCRIPTION
**Pull request by pchote**
This finishes the work started with #11364 and #11451 to port the lobby options to the new backend.

### CODE REVIEW

**Comment by Mailaender** [comment]
This does not work together with the Dune 2000 missions.

**Comment by reaperrr** [comment]
Not just D2k, it doesn't work for missions in general. I works fine for skirmish and multiplayer, though.

**Comment by pchote** [comment]
I forgot to change `Order.Command("gamespeed {0}".F(gameSpeed))` to `Order.Command("option gamespeed {0}".F(gameSpeed))`.  Fixed.

**Comment by reaperrr** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/36162753843e86ccd04d9faebe93e46b05c9ef2d...c25136f29eeb64c26226c0edc1d9248f07446d37)

**Pull request merged**
