### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by declan1171**
I helped tell u bugs

### CODE REVIEW

**Comment by aydjay** [comment]
Is Clifford spelt with CL or Cl?

**Comment by declan1171** [comment]
clifford

**Comment by declan1171** [comment]
L

**Review by anjew175 — CHANGES_REQUESTED** [review]
You forgot Anjew

**Comment by declan1171** [comment]
Huh?

**Comment by GraionDilach** [comment]
The Authors file is for people who have actively contributed. With pull requests. Not for random people reporting bugs - especially people whom I never seen opening an issue even.

**Comment by Micr0Bit** [comment]
> The Authors file is for people who have actively contributed. With pull requests. Not for random people reporting bugs - especially people whom I never seen opening an issue even.

i second that , partly because of Graions consistency and partly because of an empty Github account that was created 7 hours ago

**Comment by reaperrr** [comment]
@GraionDilach He might have reported bugs on IRC or forums.

But @GraionDilach is right, "Authors" is referring to people who have 'authored' at least one commit that adds, fixes or improves something, regardless of code or yaml.
Anything is fine no matter how small, but that's the minimum condition for an entry, otherwise the list would grow too long too quickly.

**Comment by pchote** [comment]
> Anything is fine no matter how small

Trivial changes aren't really enough to justify inclusion, but we have no hard and fast rule over what the threshold is.  Most of our contributors usually wait until they have a few changes merged before they feel happy adding themselves to the Authors list.

**Comment by jaZzKCS** [comment]
..or they don't add themselves or think about this list at all and someday a nice developer approaches them or spreads the word that "this person" should definitely be on the list. Also, the threshold line is not only drawn by github contributions. Contributions to this product can come in vast varieties and forms.

**Comment by declan1171** [comment]
ok

**Pull request closed without merging**
