### PR TITLE
PlayerStatistics should stop ticking after lost/win

### LINKED ISSUE #3451: "Earned/min" in Statistics keeps ticking(decreasing) for lost user
is it correct behavior??
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/422921-earned-min-in-statistics-keeps-ticking-decreasing-for-lost-user?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by teinarss**

### CODE REVIEW

**Comment by pchote** [comment]
The two `Queue`s don't store time info, so the times will get out of sync after 100 minutes when some players start dequeuing elements and others don't.

The simplest fix here is to remove the dequeuing - doing this after 100 samples is really arbitrary, and will never be reached in the majority of games. Those that do pass 100 probably won't last *much* longer, so we may as well preserve the entire history.

**Comment by teinarss** [comment]
Updated

**Review by abcdefg30 — DISMISSED** [review]
This works how it is supposed to be (stopping the graphs, which I like), but does *not* fix #3451. Since the `$/min` stat (not graph) still decreases for dead players.

**Comment by teinarss** [comment]
> 
> 
> This works how it is supposed to be (stopping the graphs, which I like), but does _not_ fix #3451. Since the `$/min` stat (not graph) still decreases for dead players.

Hah, i should learn to read!

**Comment by abcdefg30** [comment]
Needs a rebase.

**Comment by teinarss** [comment]
Rebased

**Comment by RoosterDragon** [comment]
I think it would be nice if it fixed the $/min stat and maybe also zeroed the "Earned this min" for the minutes after those in which a player has lost.

If not, edit the desc as this doesn't close the linked issue.

**Comment by teinarss** [comment]
Done, updated the desc. Been some talk about changing the $/min stat so no point in chaining it here.

**Comment by RoosterDragon** [comment]
Let's take this as-is then.

**Review by RoosterDragon — APPROVED** [review]

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bf2c5a776b9386fe71a0484bdcf9bcbb14b80af6)

**Comment by pchote** [comment]
Picked to prep to avoid rebase conflicts with @abcdefg30's more recent spectator PRs.

088288fee1 and updated both changelogs.

**Pull request merged**
