### PR TITLE
Use correct effects for TD anti-air explosions

### LINKED ISSUE #15248: Incorrect CreateEffect Explosions for AA weapons
TD: Rockets, BikeRockets, OrcaAAMissiles, 227mm.stnk, BoatMissile, and APCGun.AA are all using Ground type CreateEffects vs Air targets. They should be using a small_building or small_poof.

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #15248

### CODE REVIEW

**Comment by ABrandau** [comment]
You could consider setting up an inheritance system for the explosions, that way you dont need to repeat the same on every weapon (makes updating easier)

**Comment by Smittytron** [comment]
Updated. Removed unnecessary lines from effect overrides.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by pchote — APPROVED** [review]
Seems reasonable to me :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d2ff230324f7801d6f1267e25d51fc355c7c3cc3

**Pull request merged**
