### PR TITLE
Change the plane altitude in ra

### LINKED ISSUE #7020: Planes bump helicopters out of their way
repulsion

related to #6087 , #6967 

it might be not a bug ... but its definitly a "unwanted unit behaviour" and balance problem        introduced through repulsion ... which is "imo" a regression (not the repulsion , but the side-effects ) 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6576090-planes-bump-helicopters-out-of-their-way?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #7020.

### CODE REVIEW

**Comment by MicroJOo** [comment]
sry , but i didnt notice any fix here ... you should atleast test it once by yourself

**Comment by abcdefg30** [comment]
> you should atleast test it once by yourself 

Yep, sorry, forgot about that here.

> sry , but i didnt notice any fix here

That's weird, I though different ```CruiseAltitude```s would fix everything.
But that obviously wasn't the case, so I "fixed" that as well: https://github.com/abcdefg30/OpenRA/commit/adffd33f4d9a3d480cce203b0d8e2e8999200c82.

**Comment by obrakmann** [comment]
This works, :+1:

**Comment by abcdefg30** [comment]
> not to mention the slightly more time-consuming lift off and landing compared to allies choppers

I doubled ```MaximumPitch```, so they should ascend faster and don't take (much) longer then before.

**Comment by pchote** [comment]
Code and ingame feel look good to me, so :+1: once the remaining balance issues have been discussed (and resolved if necessary).

**Comment by deniz1a** [comment]
Wouldn't it be more interesting to give different types of planes different altitudes? For example Yaks would fly lower than Migs. And Spy plane flies higher than Migs etc.

**Comment by penev92** [comment]
That is a nice idea, but it probably needs more than a little testing and tweaking, so I wouldn't ask for it in this PR.
But I suppose if you're willing to help with that, it could be done.  :)

**Comment by obrakmann** [comment]
I just compared this against the playtest, ie. built a yak and mig each and flew them directly over a sam site. I did not notice a difference in effectiveness.

This there hasn't been any more constructive input to the discussion, I'll merge this now.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/850e21e8efe41a74f01a3df0c3aaa65a57854c86%5E...850e21e8efe41a74f01a3df0c3aaa65a57854c86)

**Pull request merged**
