### PR TITLE
map.yaml cleanup

### PR DESCRIPTION
**Pull request by abcdefg30**
Split from #7164 as requested (https://github.com/OpenRA/OpenRA/pull/7164#issuecomment-68462738).

This PR...
- Removes unused waypoints
- Renames actors that still have standart names ("waypoint1") to something more reasonable
- Reorderes all named actors; now they're at the end of the "Actors" list

### CODE REVIEW

**Comment by Mailaender** [comment]
> Removes "Facing: 0" on actors that don't use facings and "Health: 1" as it's default in all map.yaml files

I believe that is the only non-controversial change from this cleanup operation.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
nod03a has a problem. the first infantry attack (from the north) doesn't happen. the one from the south shortly after does

**Comment by obrakmann** [comment]
Forget it, I must have missed them the first time. It's working now like it should.

**Comment by Mailaender** [comment]
Sadly this needs a rebase. I suggest splitting this further. This can be merged much faster:

> Removes "Facing: 0" on actors that don't use facings and "Health: 1" as it's default in all map.yaml files

then the rest which has a high chance of breaking things.

**Comment by abcdefg30** [comment]
Rebased and created a new PR: #7319.

**Comment by abcdefg30** [comment]
Updated.

**Comment by obrakmann** [comment]
Needs a rebase now. Sorry about that, you'll have to start completely from the beginning :/

**Comment by abcdefg30** [comment]
Rebased.

**Comment by Phrohdoh** [comment]
:+1: once the tests pass.

**Comment by Mailaender** [comment]
We currently don't have any automated tests that the map.yaml and Lua interaction. This only breaks at runtime.

**Comment by obrakmann** [comment]
Played through all missions again, noticed no misbehaviour :+1:

**Pull request merged**
