### PR TITLE
Replace modcontent

### LINKED ISSUE #21628: cannot stat 'OpenRA/mods/modcontent': No such file or directory
## Issue Summary
When packaging on Arch Linux, commit c6af758 fails to package with the error:

```bash
Installing engine to /path/to/openra-wts-git/pkg/openra-wts-git/usr/lib/openra
Installing engine files to /path/to/openra-wts-git/pkg/openra-wts-git/usr/lib/openra
Installing common mod files to /path/to/openra-wts-git/pkg/openra-wts-git/usr/lib/openra
Installing mod cnc to /path/to/openra-wts-git/pkg/openra-wts-git/usr/lib/openra
cp: cannot stat '/path/to/openra-wts-git/src/OpenRA/mods/modcontent': No such file or directory
```

This error comes from the command `make prefix=/usr DESTDIR="$pkgdir" install DEBUG=false RUNTIME=mono`.

## Reproduction
On an up-to-date Arch Linux install, or Arch Linux WSL, download the AUR package openra-wts-git and build it with the `makepkg -s` command. You should experience this error.

## Expected behaviour
I expected `make prefix=/usr DESTDIR="$pkgdir" install DEBUG=false RUNTIME=mono` to run without error and move the appropriate files to $pkgdir.

### PR DESCRIPTION
**Pull request by PunkPun**
Possibly fixes #21628

### CODE REVIEW

**Comment by pchote** [comment]
Windows packaging script fails with:
```
../functions.sh: line 212: /home/runner/work/OpenRA/OpenRA/packaging/windows/build/mods/-content/mod.yaml.tmp: No such file or directory
```

macOS apps fail to run with:
```
Exception of type `System.IO.FileNotFoundException`: File not found: ^EngineDir|mods/common-content
```

**Comment by pchote** [comment]
Confirmed that Windows works with the new push.

**Comment by pchote** [comment]
Confirmed that macOS works with the latest push.

I don't have an intel based linux machine to hand for testing the appimages.

**Comment by PunkPun** [comment]
https://github.com/PunkPun/OpenRA/releases/tag/devtest-20241021

I tested on intel

**Comment by ottelo9** [comment]
Thx for the fix.

**Comment by fusion809** [comment]
Fixes #21628, I can confirm. I tried adding this as a patch to the package and it causes it to build successfully now.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f610f20a712251ed637f935643809286b3d9d43c

**Pull request merged**
