### PR TITLE
Updated MaxMind.GeoIP to version 2.7.1

### PR DESCRIPTION
**Pull request by Mailaender**
as requsted by @rapgro in https://bugzilla.redhat.com/show_bug.cgi?id=1270525#c7

See https://github.com/maxmind/GeoIP2-dotnet/releases and https://github.com/maxmind/MaxMind-DB-Reader-dotnet/releases for a changelog, which seems to indicate this only standardizes and updates build dependencies.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Seems like we need to update our nuget install (download)?
```
The 'System.Net.Http 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60717.93'.
```
See also AppVeyor failing: https://ci.appveyor.com/project/OpenRA/openra/build/1.0.13061#L23

**Comment by abcdefg30** [comment]
It seems to work using http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe.

**Comment by abcdefg30** [comment]
Seems to work fine aside from that. 👍 / ✅

**Comment by rapgro** [comment]
Mysterically, the tarballs for 2.1.x disappeared from upstream GitHub. Notes about upcoming 2.2.0 got removed from releasenotes.md file.

**Comment by Mailaender** [comment]
Updated.

**Comment by rapgro** [comment]
FYI MaxMind-DB in latest version (2.1.2) needs .NET Core for compilation and NUnit 3 (latter for the tests). I wonder how it can work with Mono 4, also the linkage to OpenRA assemblies built with Mono. AFAIK Mono does not support .NET Core.

**Comment by Mailaender** [comment]
I tested this pull request fine with Mono 4.6.0 on openSUSE, so I can't really help you there. Sorry.

**Comment by pchote** [comment]
We should just remove this dependency completely.

* Their massive bloated database file by itself now makes up *nearly half* of our installer size.
* The last couple of version changes have introduced major architecture and dependency changes while bringing no benefits that I'm aware of.
* This is only needed for one feature ingame (the client tooltips – the master server sends us the server country so it isn't needed for the game listings), and that feature is mainly used by asshole admins to kick the dirty foreigners from their games.   I have been asked by players to remove this (along with the IP) for registered players as part of #2265.

So, looking forward, I do not think that having a country lookup for unregistered players in the lobby by itself justifies the amount of trouble that is required to maintain the feature.

**Comment by rapgro** [comment]
@Mailaender I assume you get the MaxMind assemblies from Nuget, that could work. But please keep in mind that in case of Fedora, we need properly built packages all from sources.

**Comment by Mailaender** [comment]
I wouldn't mind if we move the player client GeoIP lookup server side or remove it entirely. It seems you are making very good progress with https://github.com/OpenRA/OpenRA/issues/2265. We were a bit afraid to do it on the master server to avoid abuse or accidental overload. Back then the GeoIP country database wasn't so big, but I assume that was before IPv6 became popular.

**Comment by pchote** [comment]
@rapgro it looks like the .NET Core stuff came in with 2.7.0, so are you asking that we stay on 2.6.0?

**Comment by rapgro** [comment]
@pchote Not really. It's more an issue in Fedora (or other downstreams currently without support for .NET Core) than for you as upstream. Mono is completely separate for legacy, especially GUI, as far as I understand the situation.

**Review by pchote — COMMENTED** [review]
This makes us download most of .NET core from Nuget:

```
paul@Mjolnir-61:OpenRA+pr/12132$ ls thirdparty/download/
Eluant.dll                                    System.Diagnostics.Tools                      System.Security.Cryptography.Cng
FuzzyLogicLibrary.dll                         System.Diagnostics.Tracing                    System.Security.Cryptography.Csp
GeoLite2-Country.mmdb.gz                      System.Dynamic.Runtime                        System.Security.Cryptography.Encoding
ICSharpCode.SharpZipLib.dll                   System.Globalization                          System.Security.Cryptography.OpenSsl
MaxMind.Db.dll                                System.Globalization.Calendars                System.Security.Cryptography.Primitives
MaxMind.Db.xml                                System.Globalization.Extensions               System.Security.Cryptography.X509Certificates
MaxMind.GeoIP2.dll                            System.IO                                     System.Text.Encoding
MaxMind.GeoIP2.xml                            System.IO.Compression                         System.Text.Encoding.Extensions
Microsoft.CSharp                              System.IO.FileSystem                          System.Text.RegularExpressions
Microsoft.NETCore.Platforms                   System.IO.FileSystem.Primitives               System.Threading
Microsoft.NETCore.Targets                     System.IO.MemoryMappedFiles                   System.Threading.Tasks
Microsoft.Win32.Primitives                    System.IO.UnmanagedMemoryStream               System.Threading.Tasks.Extensions
Mono.Cecil.dll                                System.Linq                                   System.Xml.ReaderWriter
Newtonsoft.Json.dll                           System.Linq.Expressions                       System.Xml.XDocument
Newtonsoft.Json.xml                           System.Net.Http                               addins
Open.Nat.dll                                  System.Net.Primitives                         nunit-agent-x86.exe
OpenAL-CS.dll                                 System.Net.Requests                           nunit-agent-x86.exe.config
OpenAL-CS.dll.config                          System.Net.WebHeaderCollection                nunit-agent.exe
SDL2-CS.dll                                   System.ObjectModel                            nunit-agent.exe.config
SDL2-CS.dll.config                            System.Reflection                             nunit.engine.addin.xml
SharpFont.dll                                 System.Reflection.Emit                        nunit.engine.addins
SharpFont.dll.config                          System.Reflection.Emit.ILGeneration           nunit.engine.api.dll
SharpFont.xml                                 System.Reflection.Emit.Lightweight            nunit.engine.api.xml
SmarIrc4net.XML                               System.Reflection.Extensions                  nunit.engine.dll
SmarIrc4net.dll                               System.Reflection.Primitives                  nunit.framework.dll
SmarIrc4net.pdb                               System.Reflection.TypeExtensions              nunit.framework.xml
StyleCop.CSharp.Rules.dll                     System.Resources.ResourceManager              nunit3-console.exe
StyleCop.CSharp.dll                           System.Runtime                                nunit3-console.exe.config
StyleCop.dll                                  System.Runtime.Extensions                     osx
StyleCopPlus.dll                              System.Runtime.Handles                        runtime.native.System
System.Collections                            System.Runtime.InteropServices                runtime.native.System.IO.Compression
System.Collections.Concurrent                 System.Runtime.Numerics                       runtime.native.System.Net.Http
System.Diagnostics.Contracts                  System.Runtime.Serialization.Primitives       runtime.native.System.Security.Cryptography
System.Diagnostics.Debug                      System.Runtime.WindowsRuntime
System.Diagnostics.DiagnosticSource           System.Security.Cryptography.Algorithms
```

I'm far from convinced that this is a good idea...

**Review by pchote — CHANGES_REQUESTED** [review]
This also, unsurprisingly, breaks compatibility with older mono runtimes (tested with 3.2):

```
DatabaseReader failed: MaxMind.Db.DeserializationException: No constructors found for System.Collections.Generic.IDictionary`2[System.String,System.String] found with MaxMind.Db.Constructor attribute
  at MaxMind.Db.TypeAcivatorCreator.ClassActivator (System.Type expectedType) [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Func`2<System.Type, MaxMind.Db.TypeActivator>:invoke_TResult__this___T (System.Type)
  at System.Collections.Concurrent.ConcurrentDictionary`2+<GetOrAdd>c__AnonStorey46[System.Type,MaxMind.Db.TypeActivator].<>m__3C () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Func`1<System.Collections.Generic.KeyValuePair`2<System.Type, MaxMind.Db.TypeActivator>>:invoke_TResult__this__ ()
  at System.Collections.Concurrent.SplitOrderedList`2[System.Type,System.Collections.Generic.KeyValuePair`2[System.Type,MaxMind.Db.TypeActivator]].ListInsert (System.Collections.Concurrent.Node newNode, System.Collections.Concurrent.Node startPoint, System.Collections.Concurrent.Node& current, System.Func`1 dataCreator) [0x00000] in <filename unknown>:0 
  at System.Collections.Concurrent.SplitOrderedList`2[System.Type,System.Collections.Generic.KeyValuePair`2[System.Type,MaxMind.Db.TypeActivator]].InsertInternal (UInt32 key, System.Type subKey, KeyValuePair`2 data, System.Func`1 dataCreator, System.Collections.Concurrent.Node& current) [0x00000] in <filename unknown>:0 
  at System.Collections.Concurrent.SplitOrderedList`2[System.Type,System.Collections.Generic.KeyValuePair`2[System.Type,MaxMind.Db.TypeActivator]].InsertOrGet (UInt32 key, System.Type subKey, KeyValuePair`2 data, System.Func`1 dataCreator) [0x00000] in <filename unknown>:0 
  at System.Collections.Concurrent.ConcurrentDictionary`2[System.Type,MaxMind.Db.TypeActivator].GetOrAdd (System.Type key, System.Func`2 valueFactory) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.TypeAcivatorCreator.GetActivator (System.Type expectedType) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeMapToType (System.Type expectedType, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeMap (System.Type expectedType, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeByType (System.Type expectedType, ObjectType type, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.Decode (System.Type expectedType, Int64 offset, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeMapToType (System.Type expectedType, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeMap (System.Type expectedType, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.DecodeByType (System.Type expectedType, ObjectType type, Int64 offset, Int32 size, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.Decode (System.Type expectedType, Int64 offset, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Decoder.Decode[Metadata] (Int64 offset, System.Int64& outOffset, MaxMind.Db.InjectableValues injectables) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Reader..ctor (MaxMind.Db.Buffer buffer) [0x00000] in <filename unknown>:0 
  at MaxMind.Db.Reader..ctor (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
  at MaxMind.GeoIP2.DatabaseReader..ctor (System.IO.Stream stream, IEnumerable`1 locales) [0x00000] in <filename unknown>:0 
  at MaxMind.GeoIP2.DatabaseReader..ctor (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.GeoIP.Initialize () [0x00017] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:29 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
LookupCountry failed: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.GeoIP.LookupCountry (System.String ip) [0x00002] in /Users/paul/src/OpenRA/OpenRA.Game//Network/GeoIP.cs:43 
```

**Comment by pchote** [comment]
> which seems to indicate this only standardizes and updates build dependencies.

Considering that this doesn't bring any bugfixes or new features, closing this is our only realistic option.  I don't think anybody is prepared to completely rework our toolchain and minspec *again* for this dependency.

**Comment by Mailaender** [comment]
Yeah, I had a bad feeling seeing all those dependencies https://www.nuget.org/packages/MaxMind.GeoIP2/ and https://www.nuget.org/packages/MaxMind.Db but I assumed it just clearly states the .NET framework version in a more detailed manner.

**Comment by oschwald** [comment]
Only `MaxMind.Db`, `Newtonsoft.Json`, and `System.Net.Http` should be required on .NET 4.5. It sounds like your `nuget install` is downloading the .NET Standard dependencies for some reason.

Here is my output for an install:

```
$ nuget install MaxMind.GeoIP2 
Feeds used:
  https://www.nuget.org/api/v2/

  GET https://www.nuget.org/api/v2/FindPackagesById()?id='MaxMind.GeoIP2'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='MaxMind.GeoIP2' 505ms
Attempting to gather dependency information for package 'MaxMind.GeoIP2.2.7.1' with respect to project '/tmp/nuget-test', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'MaxMind.GeoIP2.2.7.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'MaxMind.GeoIP2.2.7.1'
Resolved actions to install package 'MaxMind.GeoIP2.2.7.1'
Adding package 'MaxMind.Db.2.1.2' to folder '/tmp/nuget-test'
Added package 'MaxMind.Db.2.1.2' to folder '/tmp/nuget-test'
Successfully installed 'MaxMind.Db 2.1.2' to /tmp/nuget-test
Adding package 'Newtonsoft.Json.9.0.1' to folder '/tmp/nuget-test'
Added package 'Newtonsoft.Json.9.0.1' to folder '/tmp/nuget-test'
Successfully installed 'Newtonsoft.Json 9.0.1' to /tmp/nuget-test
Adding package 'System.Net.Http.4.0.0' to folder '/tmp/nuget-test'
Added package 'System.Net.Http.4.0.0' to folder '/tmp/nuget-test'
Successfully installed 'System.Net.Http 4.0.0' to /tmp/nuget-test
Adding package 'MaxMind.GeoIP2.2.7.1' to folder '/tmp/nuget-test'
Added package 'MaxMind.GeoIP2.2.7.1' to folder '/tmp/nuget-test'
Successfully installed 'MaxMind.GeoIP2 2.7.1' to /tmp/nuget-test

$ ls
MaxMind.Db.2.1.2  MaxMind.GeoIP2.2.7.1  Newtonsoft.Json.9.0.1  System.Net.Http.4.0.0

```

I've made a [branch](https://github.com/maxmind/GeoIP2-dotnet/tree/greg/no-net45-nuget-dep) to use the framework version of `System.Net.Http` in the next release, which should remove that NuGet dependency on .NET 4.5.

That said, you may be happier just using `MaxMind.Db` directly rather than `MaxMind.GeoIP2`. Looking at your code, you only appear to use the country name. Something like this should work (untested):

```
public class GeoIP2Record
{
    [MaxMind.Db.Constructor]
    public GeoIP2Record(
        GeoIP2Country country
     )
    {
        GeoIP2Country = country;
    }

    public GeoIP2Country Country { get; set; }
}

public class GeoIP2Country
{
    [Constructor]
    public GeoIP2Country(
        GeoIP2CountryNames names
     )
    {
        Names = names;
    }

    public GeoIP2CountryNames Names { get; set; }
}

public class GeoIP2CountryNames
{
    [Constructor]
    public GeoIP2Country(
        string en
     )
    {
        English = en;
    }

    public string English { get; set; }
}
```

and then in your existing code:

```
var record = reader.Find<GeoIP2Record>(IPAddress.Parse(ip))
```

This also has the advantage of being much, much faster as it will only decode the above data from the database rather than all of the data for the IP address.

Also, `MaxMind.Db` [now includes](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/tree/master/mono) `csproj` build files for Mono, which should help out with the Fedora packaging issue. I suspect we will also add similar files for `MaxMind.GeoIP2` in the next release, if you continue to use that.

**Comment by pchote** [comment]
Great, thanks for the info @oschwald!  Using `MaxMind.Db` sounds like a good option.
We'll just need to sort out what is going on with our dependency fetching.

**Comment by Mailaender** [comment]
The code worked with just some typos removed. See https://github.com/OpenRA/OpenRA/pull/12702 and thanks!

**Comment by rapgro** [comment]
BTW Mono Core is (currently) no option for Fedora.
https://github.com/OpenRA/OpenRA/pull/12132#issuecomment-255403957

**Comment by Mailaender** [comment]
> Also, `MaxMind.Db` [now includes](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/tree/master/mono) `csproj` build files for Mono, which should help out with the Fedora packaging issue. I suspect we will also add similar files for `MaxMind.GeoIP2` in the next release, if you continue to use that.

**Pull request closed without merging**
