### PR TITLE
Speed up frozen actor visibility updates.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Cache the isVisibleTest function in the ctor for FrozenActor. The footprint never changes so the test will always be valid.

### CODE REVIEW

**Comment by pchote** [comment]
Seems like a reasonable change, although I guess there won't be a huge improvement here. :+1:

**Comment by Mailaender** [comment]
Needs a rebase now.

**Comment by RoosterDragon** [comment]
Rebased.

**Comment by Mailaender** [comment]
Tested it with my standard Ice Woods RA test case and found no regressions. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6de2c11e4f661b6444247e267e55775c111c9ffb...5794649b3633624b20964dc7ffe3027b9ffe7660)

**Pull request merged**
