### PR TITLE
Fixed not dropping targets that are out of range if the attacker cannot move

### LINKED ISSUE #6185: AA and Sam site should face their targets only when they're within range
They seem to follow enemy aircraft far beyond their range. But not always, I haven't tested it but in the early game they seem to face aircraft anywhere on the map.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3567417-aa-and-sam-site-should-face-their-targets-only-when-they-re-within-range?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9837: AI defenses don't stop tracking units even if InitialStanceAI is set to Defend
They do switch once a new target comes into range, but as long as that doesn't happen, AI turrets continue to track a target even if it's out of range.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27861950-ai-defenses-don-t-stop-tracking-units-even-if-initialstanceai-is-set-to-defend?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9849: Camo Pillboxes dont cloak.
Found out in a 1V1 game, other player said he could totally see them so it wasn't just me. Tested in a solo game, same results. Doubt this is intentional.
In playtest 20151031

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27871822-camo-pillboxes-dont-cloak?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
From the [original PR](https://github.com/OpenRA/OpenRA/pull/9874):

> I noticed that my mammy in guard stance was trying to shoot a far away harvester while letting himself kill by infantry.
> 
> Closes #9837.
> Closes #6185.
> Closes #9849.

### CODE REVIEW

**Comment by Mailaender** [comment]
Works as promised :white_check_mark: and code looks sensible. :+1:

**Comment by GraionDilach** [comment]
Drop __oor__ targets though... fixup requested?

**Comment by obrakmann** [comment]
@GraionDilach: You're right, the commit titles could be better. I updated them.

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/8ad6d3d3778e2e8617a332a3b7a599164a1fa4db...39cc9331489da01e2b613a1c3f53b6f7da2c4b8b)

**Pull request merged**
