### PR TITLE
Disable hovering for landed aircraft

### PR DESCRIPTION
**Pull request by teees**

### CODE REVIEW

**Comment by penev92** [comment]
Looks good :+1: 

Note that aircraft still hovers while landing/taking off, but that can be handled through the Aircraft trait once it gets its long-needed overhaul. I'll open an issue about that.

**Comment by atlimit8** [comment]
@penev92 perhaps setting `MinAirborneAltitude` > 1 would suffice. I didn't change any behavior when I added that property, figuring that it would be tuned later.

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
Thanks!

**Pull request merged**
