### PR TITLE
Make GPS traits conditional

### LINKED ISSUE #16000: Make GPS traits conditional.
Asin both GpsDot and GpsWatcher. Would open a lot of room to modders atleast.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Closes #16000.

Didn't really test, please test properly.

### CODE REVIEW

**Comment by matjaeck** [comment]
Crashes on launching RA.

<details>
  <summary>Log</summary>

```
OpenRA engine version git-bae322db4
Red Alert mod version git-bae322db4
Date: 2019-02-03 12:38:49Z
Operating System: Linux (Unix 4.15.0.45)
Runtime Version: Mono 5.18.0.240 (tarball Wed Jan 16 09:10:16 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key 'Neutral (0)' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at OpenRA.Player.IsAlliedWith (OpenRA.Player p) [0x00007] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Mods.Cnc.Traits.GpsWatcher.<RefreshGranted>m__0 (OpenRA.TraitPair`1[T] kv) [0x0000c] in <4018c75f79744637b21a45aec3df401b>:0 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x00037] in <0a52baf64a2a4f9b96857c7b358eb12d>:0 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00039] in <0a52baf64a2a4f9b96857c7b358eb12d>:0 
  at OpenRA.Mods.Cnc.Traits.GpsWatcher.RefreshGranted () [0x0005f] in <4018c75f79744637b21a45aec3df401b>:0 
  at OpenRA.Mods.Cnc.Traits.GpsWatcher.RefreshGps (OpenRA.Player launcher) [0x00001] in <4018c75f79744637b21a45aec3df401b>:0 
  at OpenRA.Mods.Cnc.Traits.GpsWatcher.TraitEnabled (OpenRA.Actor self) [0x00008] in <4018c75f79744637b21a45aec3df401b>:0 
  at OpenRA.Mods.Common.Traits.ConditionalTrait`1[InfoType].Created (OpenRA.Actor self) [0x00016] in <66f19adb5efb48b3b31b1aa924398d15>:0 
  at OpenRA.Mods.Common.Traits.ConditionalTrait`1[InfoType].OpenRA.Traits.INotifyCreated.Created (OpenRA.Actor self) [0x00001] in <66f19adb5efb48b3b31b1aa924398d15>:0 
  at OpenRA.World.CreateActor (System.Boolean addToWorld, System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00023] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.World.CreateActor (System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00001] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Player..ctor (OpenRA.World world, OpenRA.Network.Session+Client client, OpenRA.PlayerReference pr) [0x00267] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Mods.Common.Traits.CreateMPPlayers.OpenRA.Traits.ICreatePlayers.CreatePlayers (OpenRA.World w) [0x00061] in <66f19adb5efb48b3b31b1aa924398d15>:0 
  at OpenRA.World..ctor (OpenRA.ModData modData, OpenRA.Map map, OpenRA.Network.OrderManager orderManager, OpenRA.WorldType type) [0x001b5] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Game.StartGame (System.String mapUID, OpenRA.WorldType type) [0x00068] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Game.LoadShellMap () [0x00018] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame (OpenRA.Arguments args) [0x001ac] in <66f19adb5efb48b3b31b1aa924398d15>:0 
  at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x003b3] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x004c8] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00007] in <7b88c258784b4264910c8faaec4367c7>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <7b88c258784b4264910c8faaec4367c7>:0 
```

</details>

**Comment by matjaeck** [comment]
Could you add a testcase? I'm afraid to set it up wrong but would like to test.

**Comment by MustaphaTR** [comment]
This is afaik a bit broken, i had to furter test but i was incapable of downloading an updated dependency (i have been copy-pasting thirdparty folder from older installations) after rebase because of the shitty internet here. Tho i got some mobile data so i guess i should go test now.

**Comment by MustaphaTR** [comment]
Actually, rebase seem to be fixed the issues i noticed while doing older tests. I'll try to think of a testcase for the conditions and add it.

**Comment by pchote** [comment]
Any progress here @MustaphaTR?

If this change isn't useful (which is what I interpret from the comments about not testing / not having a testcase) then its probably best to close this.  Reviewing bandwidth is extremely rare, so this is going to sit around forever if it isn't likely to be used and we have to go out of our to test it.

**Comment by MustaphaTR** [comment]
I don't need this. I did this because @GraionDilach asked in said issue and thought should be easy to do.

**Comment by MustaphaTR** [comment]
I have added a testcase (Radar Jammer should make nearby units of their owner not appear on enemy GPS) but it doesn't seem like actually working fine. I'm not sure what is actually wrong, so maybe someone can figure it out during a review.

**Comment by pchote** [comment]
Theres no clear path forward here, so moving to the Future milestone to help clean up the PR queue.

**Comment by GraionDilach** [comment]
GPSWatcher should never been conditional to begin with.

It's the providers which should have been changed to be conditional, not the watcher itself - the providers list within GpsWatcher should only contain the active traits which provide the gps instead of actual actors. That + unhardcoding the shroud-reveal assumption could then cover the Mobile Sensor Array-to-use-GPS-logic request, with MSA providing GPS enablement and a proxcondition to trigger the GPSDots on subterranean transports when deployed.

**Comment by Mailaender** [comment]
Got it to work: #17885.

**Pull request closed without merging**
