### PR TITLE
Fix Paradop moving off map when it shouldn't

### LINKED ISSUE #20145: The `Paradrop()` function forces the aircraft dropping its cargo to leave the map
Reported by DarkSignal on Discord

> Interesting worth noting: The Paradrop() function forces the aircraft dropping its cargo to leave the map afterwards, even if it's IdleBehavior is not set to LeaveMap

### PR DESCRIPTION
**Pull request by PurityLake**
Fixes #20145

This patch simply makes the `FlyOffMap` activity check for the `IdleBehaviour` to see if it should leave the map after Making a drop.

### CODE REVIEW

**Comment by abcdefg30** [comment]
I don't think modifying `FlyOffMap` is the right approach. If we want `IdleBehaviour` to control this at all then https://github.com/OpenRA/OpenRA/blob/93998dc4a7e944e28083fb383c26a5006bfa3af1/OpenRA.Mods.Common/Scripting/Properties/ParadropProperties.cs#L36-L37 should be removed and `IdleBehaviour.LeaveMap` used. I think the best solution would be changing `public void Paradrop(CPos cell)` to `public void Paradrop(CPos cell, bool flyOffMap = true)` and wrap those two lines into an `if` checking the new parameter. (That way we keep previous behaviour while at the same time allowing the user to control everything if they want to.)

**Comment by AspectInteractive** [comment]
Unless I'm missing something the added lines seem wholly redundant? The `OnBecomingIdle()` method in Aircraft.cs that I've linked below seems to do the exact same thing as what's being added to the properties [here](https://github.com/OpenRA/OpenRA/pull/20163/files#diff-3b4d7ad6074c92e3e4350f6d771edaf9c7afa0770fc4d3e2eed7e0c7dfa8a1cbR37-R41).

https://github.com/OpenRA/OpenRA/blob/92478a219e7401002d00dca9688c51febe3c60f2/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L744-L756

Therefore to fix the bug you would only need to remove these two lines as you've done [here](https://github.com/OpenRA/OpenRA/pull/20163/commits/028c452a3fb1ac7b6a265619a39a146a9bdf9264#diff-3b4d7ad6074c92e3e4350f6d771edaf9c7afa0770fc4d3e2eed7e0c7dfa8a1cbL36-L37) - no extra code needs to be added.

**Comment by PurityLake** [comment]
@AspectInteractive you seem to be correct, thank you for the advice

**Comment by PunkPun** [comment]
Please squash the commits.

**Comment by PunkPun** [comment]
Also are you sure this does not break any missions that use paradrop?

**Comment by PurityLake** [comment]
Will do a quick check on that when I'm back from holiday

**Comment by AspectInteractive2** [comment]
@PurityLake any update on this? Otherwise someone else should be able to check (note: I am not familiar enough with which missions use paradrops to test this).

**Comment by PurityLake** [comment]
@AspectInteractive apologies, had forgetten completely but I am in the same boat. I would appreciate if someone could test this

**Comment by AspectInteractive2** [comment]
@PurityLake thinking about this more, is this functionality necessary for anything? It seems like the only use case for the plane not leaving the map is if you wanted to customise Paradrop to do something that it isn't meant to do (i.e. have the plane stay instead of leaving), in which case I would advocate more for creating your own Paradrop rather than modifying the existing one.

**Comment by penev92** [comment]
Hello there and sorry for the long wait. I hope you're still around @PurityLake. Taking a quick look now @abcdefg30 seems to be thinking what I'm thinking. That said, @AspectInteractive2's comment about letting the default idle behaviour from `Aircraft` seems even better (assuming that works), so conceptually this seems fine. 👍  Still needs to be tested though.

**Comment by PunkPun** [comment]
I searched for where this function is even called and only soviet-soldier-volkov-n-chitzkoi.lua came up. Do note that I don't do lua so I'm not sure If I searched correctly

On that map the paradrop now misbehaves

https://user-images.githubusercontent.com/37534529/208252487-41a3ef4f-7168-4365-a294-b94d956df22d.mov

**Comment by PurityLake** [comment]
Hmmm, thinking of it I would agree. I guess this PR can be closed. Thanks for taking the time to review it

**Comment by PurityLake** [comment]
Closing due to functionality not being necessary as subclassing would be a better alternative.

**Pull request closed without merging**
