### PR TITLE
Fix FMV rendering

### LINKED ISSUE #18103: FMV scan line overlay show banding artefacts at non-integer scales
We should explicitly check the zoom and offsets and fudge the widget fill to keep a consistent line width when repeating the stripes.

### PR DESCRIPTION
**Pull request by pchote**
* Fixes #18103
* Fixed incorrect aspect ratio correction (incorrection?)

I have also reduced the opacity of the scan lines to IMO improve how it looks.

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]
This removes the scan lines for me, but the image quality seems improved. I saw a different color in the upper 10% which is gone now, but I am not sure if that is what you mean with #18103.

**Comment by pchote** [comment]
> This removes the scan lines for me, but the image quality seems improved.

This doesn't sound correct. Can you post a screenshot of your before and after?

**Comment by Mailaender** [comment]
Before:

image

After:

image

When I zoom into the screenshots I can actually see the scan lines.

**Comment by pchote** [comment]
This is indeed the expected behaviour for the PR. I reduced the opacity of the scan lines to make them more subtle while still having the effect of breaking up the large pixels.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/83896ef2631c529ce7ad1aa7ec43b06a9f1abb56...2ef77a081c3347b1b4d575543a00ee950b14e96c

**Pull request merged**
