### PR TITLE
Restore missing versioned source code package.

### LINKED ISSUE #18958: -source.tar.bz2 packages are no longer generated
This was an oversight from the GH Actions migration.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #18958.

Test build: https://github.com/pchote/OpenRA/releases/tag/devtest-20210103

Is a dependency on the final net5 pr, as that changes the way we handle the nuget cache.

### CODE REVIEW

**Comment by Mailaender** [comment]
First impression: you created tar bombs. Convention for source packages is name-version e.g. `OpenRA-20210103` in this case. For the nuget package cache I kept the original file structure as it has to be recreated anyway on the target system:
```
cd ~
mkdir -p .nuget/packages/
cd .nuget/packages/
tar -xjf OpenRA-devtest-%{version}-nugetcache-mono.tar.bz2
```

**Comment by Mailaender** [comment]
It does not build in offline mode:

```
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj" (3) on node 1 (default targets).
[    7s] PrepareForBuild:
[    7s]   Creating directory "obj/Debug/".
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Utility/OpenRA.Utility.csproj" (4) on node 1 (default targets).
[    7s] /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Utility/OpenRA.Utility.csproj]
[    7s] _CleanRecordFileWrites:
[    7s]   Creating directory "obj/Debug/".
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Utility/OpenRA.Utility.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Server/OpenRA.Server.csproj" (5) on node 1 (default targets).
[    7s] /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Server/OpenRA.Server.csproj]
[    7s] _CleanRecordFileWrites:
[    7s]   Creating directory "obj/Debug/".
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Server/OpenRA.Server.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj" (6) on node 1 (default targets).
[    7s] PrepareForBuild:
[    7s]   Creating directory "obj/Debug/".
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj" (7) on node 1 (default targets).
[    7s] PrepareForBuild:
[    7s]   Creating directory "obj/Debug/".
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj" (8) on node 1 (default targets).
[    7s] PrepareForBuild:
[    7s]   Creating directory "obj/Debug/".
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj" (default targets) -- FAILED.
[    7s] Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (1) is building "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Launcher/OpenRA.Launcher.csproj" (9) on node 1 (default targets).
[    7s] /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Launcher/OpenRA.Launcher.csproj]
[    7s] _CleanRecordFileWrites:
[    7s]   Creating directory "obj/Debug/".
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Launcher/OpenRA.Launcher.csproj" (default targets) -- FAILED.
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target(s)) -- FAILED.
[    7s] 
[    7s] Build FAILED.
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj" (default target) (2) ->
[    7s] (ResolvePackageAssets target) -> 
[    7s]   /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj" (default target) (3) ->
[    7s]   /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Utility/OpenRA.Utility.csproj" (default target) (4) ->
[    7s] (GetReferenceAssemblyPaths target) -> 
[    7s]   /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Utility/OpenRA.Utility.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Server/OpenRA.Server.csproj" (default target) (5) ->
[    7s]   /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Server/OpenRA.Server.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj" (default target) (6) ->
[    7s] (ResolvePackageAssets target) -> 
[    7s]   /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj" (default target) (7) ->
[    7s]   /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj" (default target) (8) ->
[    7s]   /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj]
[    7s] 
[    7s] 
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.sln" (Build target) (1) ->
[    7s] "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Launcher/OpenRA.Launcher.csproj" (default target) (9) ->
[    7s] (GetReferenceAssemblyPaths target) -> 
[    7s]   /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Launcher/OpenRA.Launcher.csproj]
[    7s] 
[    7s]     0 Warning(s)
[    7s]     8 Error(s)
[    7s] 
[    7s] Time Elapsed 00:00:00.88
[    7s] error: Bad exit status from /var/tmp/rpm-tmp.4H6Xnm (%build)
```

You only packaged the nuget packages, not the cache: https://build.opensuse.org/source/games:openra/release/nuget-cache.tar.gz

**Comment by Mailaender** [comment]
I'd say this has potential to fix https://github.com/OpenRA/OpenRA/issues/17508.

**Comment by pchote** [comment]
Updated to drop the nuget cache packaging. This fix is a blocker for the next playtest, so I don't want it to get bogged down in .NET5 compilation support issues. We can revisit nuget caching after we have finished migrating the makefile toolchain to .NET5.

> .NETFramework,Version=v5.0

This happens when your system attempts to compile OpenRA as .NET5 using mono. It has nothing to do with the nuget cache.

**Comment by Mailaender** [comment]
How do I not compile with .NET 5? All I did was `msbuild -t:Build -p:Configuration=Debug -p:TargetPlatform=unix-generic` due to https://github.com/OpenRA/OpenRA/issues/19001 and making it look like it wants to access the internet again:

https://github.com/OpenRA/OpenRA/blob/71b13c7b5de1ff9682124f92d5345d8a0c67231e/Makefile#L85-L91

**Comment by pchote** [comment]
You are missing the `-p:Mono=true -p:DefineConstants="MONO"` that tell it to compile using mono, but again this is a bleed packaging issue that has nothing to do with the source code packaging or compiling the prep branch.

**Comment by Mailaender** [comment]
It still fails.

```
[    7s] /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj]
[    7s] Done Building Project "/home/abuild/rpmbuild/BUILD/openra-20210103/OpenRA.Game/OpenRA.Game.csproj" (default targets) -- FAILED.
```

 I think there is really no point in repackaging the source code as `bz2` if it doesn't build offline.

**Comment by pchote** [comment]
Rebased on an older bleed from before #17989 and created a new test tag: https://github.com/pchote/OpenRA/releases/tag/devtest-20210103-2

Again, your problems are because of the incomplete .NET 5 migration, and have nothing to do with fixing the packaging on the prep branch.

**Comment by Mailaender** [comment]
> project.assets.json' not found. Run a NuGet package restore to generate this file.

was a problem of the current release already. It happened during the nuget migration.

**Review by abcdefg30 — APPROVED** [review]
Extracting and compiling the downloaded archive works on Windows.

**Comment by Mailaender** [comment]
It is identical to the GitHub generated tarball except it already contains what `make version` does. Not really interesting for Linux distributions that try to build this offline because it is missing all the dependencies.

**Comment by Mailaender** [comment]
This could be solved with less redundancy by just updating the version string in the prep branch / release tag.

**Comment by pchote** [comment]
I'll repeat again: this is a regression fix, not a new feature!

This was first added in #14226, which was a rewrite of your own #13908. It has proved its worth at solving the support burden from people who download the source code from the website and then complain that they can't play online. The script to build this [is still in the repo](https://github.com/OpenRA/OpenRA/blob/bleed/packaging/source/buildpackage.sh), i just forgot to call it when migrating to GitHub Actions.

Your suggestion isn't compatible with our prep branching model: we merge code changes on top of the prep branch / release tag, which means that sync-incompatible code would be incorrectly specifying the same version. This would lead to desyncs and confusion. Commiting frozen tags into the repo remains a really bad idea.

**Review by phrohdoh — APPROVED** [review]
LGTM

**Comment by Mailaender** [comment]
No need to repeat my previous mistakes. This does not solve the problem that people build the automatically generated source from GitHub (which is easier to find) and then won't be able to play online. You could change the version on prep, then tag a release and revert it back to {DEV_VERSION} if that is not the final tag.

**Comment by abcdefg30** [comment]
> This does not solve the problem that people build the automatically generated source from GitHub (which is easier to find) and then won't be able to play online. You could change the version on prep, then tag a release and revert it back to {DEV_VERSION} if that is not the final tag.

Imo that is more effort than it is worth it, sorry. We need the versioned packages for the links at https://www.openra.net/download/ anyway, so we can merge this and think of a solution for the other problem in a different PR. (Although again, I personally don't think it is worth the hassle.)

**Comment by pchote** [comment]
> think of a solution for the other problem in a different PR

:+1: (but please lets have it in an issue until a solution is decided)

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0d1d399a7a18acbd59e9681ed7bba124ddb7d1ec...f04436bde0ef2c1aa92e68911feec77f23206922)

https://github.com/OpenRA/OpenRA/commit/a8f6256c042a6aa379cb00cbd7080b73b5db138f

**Pull request merged**
