### PR TITLE
Fix PlayMovieInRadar crashing for spectators

### LINKED ISSUE #15051: Playing a video in radar will crush the game in replay mode
Red Alert mod version release-20180307

The error log:

Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Widget  has no child PLAYER of type VqaPlayerWidget
   at OpenRA.Widgets.Widget.Get[T](String id)
   at OpenRA.Mods.Common.Scripting.Media.StopFMVInRadar()
   at OpenRA.Mods.Common.Scripting.MediaGlobal.<PlayMovieInRadar>c__AnonStorey3.<>m__0()
   at OpenRA.Effects.AsyncAction.<Tick>m__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

The map you can test this:
https://resource.openra.net/maps/26690/

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #15051.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Yes, I wrote the PR. :p

**Comment by reaperrr** [comment]
> Yes, I wrote the PR. :p

In theory you might have done so without testing :p

**Comment by KOYK** [comment]
@reaperrr
Well I tested @abcdefg30 code it by copy&paste method in openra (released version) and worked as intended, but I haven't playtested it by using the pr ( I am not even sure if that's even possible since I have no clue how pr's work)

**Comment by abcdefg30** [comment]
I tested it in all mods by copying `aagun.vqa` into the respective bit folders and then using lua.

**Review by reaperrr — APPROVED** [review]
👍 then

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/94944f42234ece6086e68c8ae6112c95cc799177...bf11481badf7ecb2160b9d77eae29c549005601f)

**Pull request merged**
