### PR TITLE
Update AttackGarrisoned.cs

### PR DESCRIPTION
**Pull request by MartinCurwen**
#13107 AttackGarrisoned trait

Small fix and first time edit so hopefully I've done this right.

### CODE REVIEW

**Review by phrohdoh — APPROVED** [review]
Thanks for this!

**Comment by GraionDilach** [comment]
This substitutes a bug with another one: now AttackGarrisoned fires disabled-via-conditions armaments as well.

**Comment by MartinCurwen** [comment]
Did it even respect conditions before?

**Comment by pchote** [comment]
That bug already existed, but wasn't visible only because they weren't defined earlier in the yaml.

**Comment by MartinCurwen** [comment]
@GraionDilach can you explain how to reproduce this bug? I've tested and I have it working perfectly using conditions on the armaments.

	Armament@PRIMARY:
		Weapon: PortaTesla
		LocalOffset: 0,0,555
		RequiresCondition: rank-veteran == 1

	Armament@SECONDARY:
		Name: secondary
		Weapon: Dragon
		LocalOffset: 0,0,555
		RequiresCondition: rank-veteran == 0

	Armament@GARRISONED:
		Name: garrisoned
		Weapon: PortaTesla
		RequiresCondition: rank-veteran == 1

set pillbox attackgarrisoned to use garrison and secondary.
started a skirmish game,
built rocket soldier and pillbox(able to shoot dragon), blow up an enemy ore truck and got promoted
now only shoots tesla and in a pill box also shoots only garrison weapon tesla, no longer dragon rockets and never primary either. seems to be working fine?

**Comment by MartinCurwen** [comment]
I am so sorry I just added a file that was meant to be for a separate pull request, can someone explain how to remove GainsExperience only and submit it under a new pull request?

**Comment by Phrohdoh** [comment]
You have two options here:
 - Easy (but dangerous!): `git reset`
 - Difficult (super powerful): `git rebase`

## `reset`

This will reset your history to be exactly the same as `f82d8bb11c145c375ae1d553a29917db198234de` (which is the commit for this PR).

```
$ git reset --hard f82d8bb11c145c375ae1d553a29917db198234de
```

## `rebase`

With an interactive rebase you can remove commits from a branch entirely (you can also reorder commits, change commit messages, squash commits [which we will surely ask you to do at some point]).

Be sure you have this commit on another branch (you can either manually remake these changes or use `git cherry-pick` to copy the commit to the other branch).

```
$ git rebase -i f82d8bb11c145c375ae1d553a29917db198234de^
```

The text you are presented with will contain some basic instructions / how-tos you should read.

You will want to completely remove the line containing the GainsExperience commit then save and quit your editor.

---

After you do either a reset or a rebase you will need to force push to your remote.

```
# assuming 'origin' is your fork (check with `git remote -v`)
# `bleed` here is the name of the branch you are force pushing
$ git push origin +bleed
```

---

Hopefully this is helpful.
These issues are much easier to work through over IRC in my experience.

**Comment by pchote** [comment]
> This substitutes a bug with another one: now AttackGarrisoned fires disabled-via-conditions armaments as well.

@GraionDilach can you please provide a testcase illustrating this problem?

**Review by GraionDilach — APPROVED** [review]
Apparently I had a typo on the unit I've tested this with, which caused my confusion, so sorry. :+1: and LGTM.

**Review by atlimit8 — DISMISSED** [review]
Please change commit summery to something like:
Multiple armament check fix in AttackGarrisoned

**Comment by atlimit8** [comment]
The current commit message is too generic IMO.

**Comment by MartinCurwen** [comment]
@atlimit8 I agree sorry about that, I think I've done it using --amend and your suggestion so hopefully its alright now

**Comment by atlimit8** [comment]
[Chengelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b20148a7bf083920401a104a562504ccfe040179...4f30664e841a70e55f9db57a7d2cbfa154a626cf)

**Pull request merged**
