### PR TITLE
Print GLSL info log if shader compilation fails

### PR DESCRIPTION
**Pull request by sinf**
The GL info log is written to graphics.log when shaders fail to compile or link. This info log contains compiler errors along with line numbers that explain why the shader failed to compile. Refactoring vertex & fragment shader compilation into a new function  also fixed fragment shader not being checked for errors (obvious copy-paste bug in the original Shader.cs, line 56). Someone with more knowledge can tell how to output the error message more nicely.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
:+1:

**Comment by pchote** [comment]
Nice!  This will make my life a lot easier during the next set of TS-focused renderer changes. :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/a6ae5cf4b27d32eb8eff6d3c47ca3f92c4de113d%5E...a6ae5cf4b27d32eb8eff6d3c47ca3f92c4de113d

**Comment by chrisforbes** [comment]
Please send us a patch to update AUTHORS as well - you've got a couple of changes in now.

**Pull request merged**
