### PR TITLE
Making fake structure prices consistent

### PR DESCRIPTION
**Pull request by PunkPun**
#16187

### CODE REVIEW

**Comment by MustaphaTR** [comment]
ConYard seem to have `Valued: 2500`. I guess 2k is the MCV's cost. I think changing ConYard's cost to 2k too makes sense. I see no reason ConYard should give more sell cash/bounty than it should according to cost of MCV.

**Comment by Punsho** [comment]
Oh, should I also update it's price in this pr? It seems more of a balancing thing though

**Comment by Punsho** [comment]
The reason might be to make it less punishing for selling a conyard and for it to give more soldiers on sell

**Comment by GraionDilach** [comment]
The lack of consistency throws off the value graph as well though.

**Comment by MustaphaTR** [comment]
The Army value graph doesn't count MCV/ConYard.

**Review by Smittytron — APPROVED** [review]

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/80c5c2c5deb16d84f7049402ff67d7604db5415c

Prep: e6a799b

**Pull request merged**
