### PR TITLE
Adjust the stroke of the muted indicator glyph

### PR DESCRIPTION
**Pull request by dragunoff**
I think that the stroke of the muted indicator looks better on the outside. 

изображение

Also sneaked in a change to TD chrome image - the cross mark was missing (probably got lost during the UI scale rework). I can separate that into it's own commit if needed.

### CODE REVIEW

**Comment by pchote** [comment]
The TD chrome-3x sheet needs to be exported at 3072 x 1536 and then have the canvas expanded (on the right and bottom edges) to 4096 x 2048 (similar rules but different dimensions for glyphs-3x). Exporting at 4x breaks the mapped regions!

After fixing the export and testing, I agree that the stroke feels much better at 1x scaling.
IMO the stroke feels too thin wrt the text at 2x and 3x scaling, though:





Are we able to bump the stroke width by a fraction of a px so that the 2x and 3x version look better without impacting the 1x version?

**Comment by dragunoff** [comment]
> 
> 
> The TD chrome-3x sheet needs to be exported at 3072 x 1536 and then have the canvas expanded (on the right and bottom edges) to 4096 x 2048 (similar rules but different dimensions for glyphs-3x). Exporting at 4x breaks the mapped regions!
> 

I completely overlooked that. Will fix.

> 
> Are we able to bump the stroke width by a fraction of a px so that the 2x and 3x version look better without impacting the 1x version?

Yes, I will try. I think it will work.

**Comment by dragunoff** [comment]
Update: fixed the size of the 3x sprites.

I tried playing with the stroke however on my machine it looks alright at 1px on all UI scales:
audio-muted-stroke

I don't have a hi-dpi display, I'm testing by changing the UI scale in the settings. Is there a difference in rendering between different OS?

**Comment by pchote** [comment]
There shouldn't be a difference between OSes, but it looks like you are only testing the 1-1.5x scale range. The stroke differences only become really obvious at 2x and above.

**Comment by dragunoff** [comment]
> There shouldn't be a difference between OSes, but it looks like you are only testing the 1-1.5x scale range. The stroke differences only become really obvious at 2x and above.

Got it. I still hadn't wrapped my head around the UI scaling entirely. I bumped the stroke by 0.5px and tested by changing `OPENRA_DISPLAY_SCALE` on linux. here's how it looks:
image

I think it's fairly balanced except for the 1.5 and 2.5 scales but I guess there ain't much we can do about that with the sprites.

Branch is updated with the new sprites.

**Review by pchote — APPROVED** [review]

**Review by sorcerer86pt — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/372f35aa4874be706254e0395de8b27f80f89333...821afa839d648a34a1b42ebfdc476d328813529c)

https://github.com/OpenRA/OpenRA/commit/3c92c2d789dc2d3a4d908e032ebe43daa612a471

**Pull request merged**
