### PR TITLE
Editor: Increase size of editor tile/actor list widget

### LINKED ISSUE #8451: ingame editor: use full screen height for tile window
currently the ingame editor window only uses a small area of the available screen estate, and requires the user to scroll through the list to find a tile

editing would be easier if the tile window stretched all the way down to the bottom of the screen, or if the window auto-resized for tabs where there are only few options (e.g. 'overlays')

editor

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21258018-ingame-editor-use-full-screen-height-for-tile-window?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by clemty**
fixes #8451

editorwindow

### CODE REVIEW

**Comment by chrisforbes** [comment]
:+1:

**Comment by Mailaender** [comment]
Okay, but you will need to move the performance text which is now hidden.

**Comment by pchote** [comment]
Moving the perf text is a bad idea.  Just make the list finish above it.

**Comment by clemty** [comment]
updated:
updated

**Comment by Mailaender** [comment]
Well done. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/66d57ba9508a87ca512b32c45135b3aea9e1b83f...6251589b74d1d23d7977a0c04a0e62e01cdc0f69)

**Pull request merged**
