### PR TITLE
Some renaming from "folder" to "package"

### PR DESCRIPTION
**Pull request by penev92**
Do some renaming in preparation for an `IPackageLoader`, which will bring packages on par with sprites and sound files, and let us move all those out of the engine.

### CODE REVIEW

**Comment by abcdefg30** [comment]
> OpenRA.Game/FileSystem/FileSystem.cs:L194: [SA1026] There should be no space between the new keyword and the opening square bracket in an implicitly typed array allocation.
OpenRA.Game/FileSystem/FileSystem.cs:L194: [SA1010] Invalid spacing around the opening square bracket.

**Comment by penev92** [comment]
Fixed Travis's complaints.

**Comment by RoosterDragon** [comment]
:+1: Seems reasonable enough.

**Comment by pchote** [comment]
:+1:

**Pull request merged**
