### PR TITLE
Remove the prefixes of all red alert missions

### PR DESCRIPTION
**Pull request by abcdefg30**
noprefixes

### CODE REVIEW

**Comment by r34ch** [comment]
Perhaps it's the OCD in me, but is it possible to add an extra space after (or before) the colon of missions without a letter after the mission number?

That would line up the mission names nicely.

**Comment by Mailaender** [comment]
:+1:

**Comment by abcdefg30** [comment]
Also added alignment now. Hope it's okay so:
noprefixesaligned

**Comment by Phrohdoh** [comment]
That looks much better. :+1:

**Comment by MustaphaTR** [comment]
:+1:

**Pull request merged**
