### PR TITLE
Add TRUCK.Husk to Tiberian Dawn

### LINKED ISSUE #13779: TD supply truck doesn't leave a husk on death
In TD all vehicles should leave husks.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #13779. I wondered if we wanted to spawn a money crate instead though (as we do in RA).

### CODE REVIEW

**Comment by MustaphaTR** [comment]
We can make Husk drop crate on death.

**Comment by abcdefg30** [comment]
> We can make Husk drop crate on death.

Good idea. Added.

**Comment by AoAGeneral** [comment]
This could be a potential issue though if the truck drops a crate this means you can take an engineer and capture the truck husk while gathering its crate. Ultimately you could recycle the unit to get free 500$ each time this unit dies.

**Comment by abcdefg30** [comment]
> his means you can take an engineer and capture the truck husk while gathering its crate.

It only drops a crate when the husk is destroyed. That means no crate when an engineer salvages it.

**Comment by AoAGeneral** [comment]
Ah when the husk is destroyed. Got it. ^^

**Comment by anjew175** [comment]
> I wondered if we wanted to spawn a money crate instead though (as we do in RA).

I really don't think the Supply Truck should do this is TD. I have discussed my position to AoA.
http://logs.openra.net/?year=2017&month=08&day=06#10:41:22
Not dropping a crate was intentional however creating a husk went over my head (sorry).

**Comment by abcdefg30** [comment]
Guess I'm outvoted. Removed the crate dropping again.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fb63007c02aaaa24794bdec0bd4342cdfcacee5d...33b20792727eb642334099b55a86766f75dff949

**Pull request merged**
