### PR TITLE
A few minor portability fixes

### PR DESCRIPTION
**Pull request by jbeich**
An attempt to eliminate some local changes in FreeBSD port. Unix desktop includes the following systems. Adding ifdefs for them all is kinda overkill, so let's simplify instead.
- Linux except Android
- Bitrig, DragonFly, FreeBSD, MirBSD, NetBSD, OpenBSD
- Solaris-based systems
- GNU/kFreeBSD
- GNU/Hurd (not sure if it can do OpenGL 2.0)

Tested with `gmake dependencies` and

``` diff
Index: games/openra/Makefile
===================================================================
--- games/openra/Makefile   (revision 387370)
+++ games/openra/Makefile   (working copy)
@@ -82,10 +82,8 @@ post-patch:
        ${MV} -v ${WRKDIR}/$${f#*/} ${WRKSRC}/thirdparty; \
    done

-   ${REINPLACE_CMD} -e 's/Linux/${OPSYS}/' \
-       -e '/CP_R/s,hicolor/,hicolor,' \
+   ${REINPLACE_CMD} \
        -e '/fetch-thirdparty-deps/d' \
-       -e 's/crashdialog/gamemonitor/' \
        -e '/echo/!s/   @/  /' \
        -e '/^mods:/s/$$/ version/' \
        -e '/^docs:/s/$$/ all/' \
@@ -96,9 +94,6 @@ post-patch:
    ${SED} 's/@LIBLUA51@/liblua-${LUA_VER}.so/' \
        ${WRKSRC}/thirdparty/Eluant.dll.config.in \
        >${WRKSRC}/Eluant.dll.config
-# DragonFly lacks BSD suffix
-   ${REINPLACE_CMD} -e 's/"BSD"/"${OPSYS}"/' \
-       ${WRKSRC}/OpenRA.Game/Platform.cs

 post-build:
 .if ${PORT_OPTIONS:MDOCS}
```

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: Thanks. I nominate https://github.com/jbeich/OpenRA/commit/01dbbb72fa81334b54df125ca22b3890268cca83 for the stable branch.

**Comment by obrakmann** [comment]
:+1: changes look good

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/bd8735fdb6914e84d78f733685503b56ef58e673%5E...bd8735fdb6914e84d78f733685503b56ef58e673)

**Comment by obrakmann** [comment]
jbeich@01dbbb7 isn't needed for stable.

**Comment by Phrohdoh** [comment]
Would have been nice to get an OS X :+1: for this IMO.

**Pull request merged**
