### PR TITLE
Adjust faction label width in lobby to fit better when truncated

### PR DESCRIPTION
**Pull request by dragunoff**
Follow up to #20196 to address https://github.com/OpenRA/OpenRA/pull/20196#issuecomment-1226376890
Screenshot from 2022-08-25 09-55-30
Screenshot from 2022-08-25 09-55-13
Screenshot from 2022-08-25 09-54-55
Screenshot from 2022-08-25 09-54-36

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
LGTM

**Review by Mailaender — DISMISSED** [review]

**Comment by PunkPun** [comment]
The testcase can be dropped

**Comment by dragunoff** [comment]
Update: dropped testcase.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/487f37c0fb5536899cee2633530c31d8589dab93...41150bd40ed2a54cecd38a2bad0a86bb733aff41)

**Pull request merged**
