### PR TITLE
Fix trike muzzle sequence

### PR DESCRIPTION
**Pull request by Porenutak**
While digging in #21266 I realize that trike use wrong muzzle sequence compared to OG.

https://github.com/OpenRA/OpenRA/assets/100044015/49c39d32-ff26-41f7-8b86-155872a89f74

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
LGTM

**Comment by PunkPun** [comment]
Needs a rebase. 

Trike

I'm also not sure if this looks correct. Muzzle feels too far from the gun

**Comment by Porenutak** [comment]
Rebased. Muzzle offset fixed

**Comment by PunkPun** [comment]
They look identical

Trikes

**Comment by Porenutak** [comment]
that was the point. Wasnt it?

https://github.com/OpenRA/OpenRA/assets/100044015/ecb9ba38-66ae-4cdc-bd3c-89e8e22b0712

**Review by PunkPun — APPROVED** [review]
ok

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/40e1c53588950d97b1d3df53cfa43cde54f1c004...26cea205a75ea44816878fc3ee376d3e94234530)

**Pull request merged**
