### PR TITLE
Added destructible trees to the C&C: TD/RA campaigns

### PR DESCRIPTION
**Pull request by Mailaender**
Brings back https://github.com/OpenRA/OpenRA/pull/2612, but for the single-player missions only as I don't want to disturb balancing.

### CODE REVIEW

**Comment by reaperrr** [comment]
From IRC:
> [21:53] <reaperrr> Mailaender: even ignoring any past discussions, there are still some problems to consider, if this is supposed to match the originals:
[21:53] <reaperrr> 1) tree groups were always invulnerable, only single trees could be killed
[21:53] <reaperrr> 2) iirc, burnt trees were also invulnerable, only 'living' trees could be killed
[21:54] <reaperrr> 3) all trees were invulnerable to machine guns and had *lots* of HP (definitely more than 500), it took ages to kill just one
[21:55] <reaperrr> no less than 1000, and concrete(RA)/heavy(TD) armor

**Comment by Mailaender** [comment]
Updated to make them more durable.

**Comment by pchote** [comment]
> [21:53] < reaperrr> 1) tree groups were always invulnerable, only single trees could be killed
> [21:53] < reaperrr> 2) iirc, burnt trees were also invulnerable, only 'living' trees could be killed
> [21:54] < reaperrr> 3) all trees were invulnerable to machine guns and had lots of HP (definitely more than 500), it took ages to kill just one

This reads like a list of steps to reproduce a bug rather than a deliberately designed game feature 😟 
IMO what we have now is a good compromise for the default mods, and so I don't like the idea of changing things unless this actually breaks something in the campaigns.

**Comment by reaperrr** [comment]
> IMO what we have on bleed is a good compromise for the default mods, and so I don't like the idea of changing things unless this actually breaks something in the campaigns.

I'm 100% sure there were no missions designed around trees being destructible, and since they were so robust (or indestructible in the case of tree group actors) that trying to kill them was so tedious people normally wouldn't bother, while making them more fragile could have unwanted side-effects.

As it is now, it would still need more changes to match the original games (only tree *husks* are really destructible right now, which means you need flame weapons to turn them into husks first).
However, I'm rather indifferent towards this feature with a slight tendency towards 'not worth the potential hassle' and since @pchote is rather against it as well, I suspect this wouldn't get enough approvals anyway and sit unmerged for ages until it goes stale, so I'll close it now to avoid that.

Sorry @Mailaender, I know you meant this well and if our RA/TD mods were aiming at true-to-original like D2k, it would be an entirely different matter, but they don't, so I think this isn't worth investing more time on this PR.

**Comment by MustaphaTR** [comment]
I know in some original missions, AI specifically try to kill some trees to open paths for themselves. I'm not sure about places where destroying trees help us tho.

**Comment by Mailaender** [comment]
No problem, we even have https://github.com/OpenRA/OpenRA/wiki/How-to-add-destructible-trees-to-your-map if someone wants to do it in their custom maps.

**Pull request closed without merging**
