### PR TITLE
Improved GPS icons

### LINKED ISSUE #10504: Difficulty to see enemy with GPS Satellite under FoW, if enemy's color is close to terrain's [$10]
When some players choose colors close to terrain's (on temperal maps, dark green, dark blue, ... or even manage to get black with some color trick), it is very hard to see their GPS symbols under the FoW. 

So it can become much easier to sneak attack, which is almost impossible for players who use colors with contrast to terrain.

Not sure what the solution could be. 
- Maybe an equivalent of #9801, but changing the whole color of the enemy team (GPS symbols + maybe units themselves). Not happy with this solution though.
- And further limiting colors might not be an option (#10217)
- Or maybe a white outline on the symbols ? Not liking this too ... 

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/29853092-difficulty-to-see-enemy-with-gps-satellite-under-fow-if-enemy-s-color-is-close-to-terrain-s?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by riiga**
Improved GPS icons by enlarging them, adding an outline and changing the pictogram for some of the icons, so it matches the icon tabs in the production panel better. Closes #10504.

### CODE REVIEW

**Comment by Mailaender** [comment]
Works well on both TEMPERAT and SNOW terrain. :+1:

**Comment by obrakmann** [comment]
I'm liking this so much!

I have one niggle, though: on snow maps, you can see quite clearly that some icons have a shadow (building and infantry), which looks quite good IMO, while others do not (tanks, vehicles, don't know about ships and planes).

openra-2016-01-28t195426z


Can we make all icons consistent in that regard?

**Comment by riiga** [comment]
Added shadows to all now.

**Comment by GraionDilach** [comment]
The commits should be squashed though.

**Comment by obrakmann** [comment]
Thanks, looks fine now. :+1: 

Please squash that second commit so that we can merge this.

**Comment by riiga** [comment]
Hopefully I did this right, appears to be only one commit now.

**Comment by obrakmann** [comment]
Yep, looks good, thanks.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/226bbc721dae3a31e49b17b1105609f330b7b855)

**Pull request merged**
