### PR TITLE
Fix PortableChrono not teleporting on force move

### LINKED ISSUE #20870: Teleport is dysfunctional in current bleed branch!
Reported by @EoralMilk 

This bug should be related to https://github.com/OpenRA/OpenRA/commit/ad683d922691aff013ac84d2c023a61d6594fc41, this commit makes the Teleport (and similar traits in third-party mod) dysfunctional. Neither deploy order nor force move order can trigger the Teleport now.

### PR DESCRIPTION
**Pull request by PunkPun**
Fixes #20870

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]

**Comment by dnqbob** [comment]
Are you sure this fix doesn't have any side effect?

**Comment by dnqbob** [comment]
And it is basically the same as https://github.com/OpenRA/OpenRA/pull/20873, maybe add a tag for both

**Comment by PunkPun** [comment]
> Are you sure this fix doesn't have any side effect?

It should not. This was only meant to cancel itself & child activities.

> And it is basically the same as #20873, maybe add a tag for both

Yeah sorry about that. I didn't see the PR when I made this

**Comment by PunkPun** [comment]
It looks like it regresses the fix to #19163. Which is fine, I had liinked that issue just because it happened to get fixed, I had not investigated it deeper on why it was fixed

**Comment by dnqbob** [comment]
No worry about that PR, already closed and we can focus in this PR.

**Comment by Mailaender** [comment]
As you basically came up with exactly the same thing, I count that as approval.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/263a4b14fade7ca41fef1f00f880977557a0777a...f3a98c39174e1be977db3c47bf49cd4a94bd0494)

**Pull request merged**
