### PR TITLE
launch-dedicated.sh: Support passing args from CLI

### PR DESCRIPTION
**Pull request by moviuro**
The documentation will need an update

### CODE REVIEW

**Comment by Mailaender** [comment]
It wasn't really meant to be used that way, but only serve as an example on how to create your own script.

**Comment by moviuro** [comment]
Still, it makes it easier to test different setups. Also, it isn't a lot of changes to a lot of files and bound to disappear whenever the "Dedicated" form gets a bit more attention :wink:

**Comment by Mailaender** [comment]
I can't really test it at the moment as it keeps crashing for me. Can you add https://github.com/Mailaender/OpenRA/commit/b5895cdcfd987b5705b93f60223e897ad616d514 which I hoped would have been merged sooner and explain the syntax?

**Comment by obrakmann** [comment]
Works for me :+1:

**Comment by Mailaender** [comment]
Thanks!

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/92164ae9edd13e71dbed6dffd950b530b3c03932...553866e8b687e7db98858dda5cc991767d9f4053)

**Pull request merged**
