### PR TITLE
Disable crates by default

### PR DESCRIPTION
**Pull request by MustaphaTR**
Just opening a PR after the discussions on discord.

### CODE REVIEW

**Comment by FRenzy-OpenRA** [comment]
Crates / speed are probably variable options between 1v1 and team games. (no crates, normal VS crates, fast/er, usually)
Setting a default on this would be less evident.

**Comment by pchote** [comment]
I'm really not a fan of this.  Crates are a core part of the C&C gameplay, and generally enjoyed as adding fun to the game by people who don't play competitively (the vast majority of OpenRA players).

Considering that these defaults can be set at the server level IMO it would be more appropriate to leave them enabled in the mod rules and to have e.g. the RAGL servers disable them there.

**Comment by fruestueck** [comment]
As annoying as it is to disable that (and other game options) on every pvp game, i've to agree with pchote.

The mistery of a crate was something special when i was a kid. Same would maby apply to new players. And it's fun :)

**Comment by reaperrr** [comment]
Considering the number of people against changing the default, I see no chance of this getting merged, so we might as well close it now.

**Pull request closed without merging**
