### PR TITLE
Fix AA-only missiles not damaging landed aircraft

### LINKED ISSUE #9911: SAM missiles do not damage landed chinooks
Noticed this on gdi07 in the cnc mod

http://expirebox.com/download/828a6e39674ed88c2a44e4cd8e26af6b.html

On bleed (git-e609abf)

### PR DESCRIPTION
**Pull request by reaperrr**
This adresses the edge case where an AA-only missile is fired while the aircraft is in the air, but hits after the aircraft landed and then deals no damage, because the target type is no longer `Air`.

Fixes #9911.

### CODE REVIEW

**Comment by pchote** [comment]
This may open up a new edge case where splash damage leaks to aircraft on the ground below an explosion.

**Comment by GraionDilach** [comment]
@reaperrr Why you didn't went with the way I said in the issue?

**Comment by reaperrr** [comment]
@GraionDilach Because then AA missiles hitting a landed helicopter would deal splash damage vs. nearby actors. AA warheads aren't balanced for that, they often have 100% efficiency vs. none or wood, for example.

**Comment by GraionDilach** [comment]
Then duplicate the warhead to damage Ground with say 1/5 damage as a start. I'd expect that splash, although I can see why you say it'd be imbalanced with the previous values.

**Comment by reaperrr** [comment]
I don't have the time and "head-bandwidth" for this at the moment, so I'm concentrating on other PRs I consider more important.

**Pull request closed without merging**
