### PR TITLE
Fix TS harvester and MammothMk2 not rendering

### LINKED ISSUE #14395: Bug TS: Harvesters dont display their voxels
Tested on the current bleed the day 21 of november.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #14395.

### CODE REVIEW

**Comment by penev92** [comment]
This needs to go into the first playtest since it fixes a major regression that would otherwise be present in that playtest.

**Comment by reaperrr** [comment]
it doesn't affect the shipping mods so strictly speaking it's not a hard requirement, but I agree we shouldn't ship a release with this bug.

**Comment by Smittytron** [comment]
First time I've loaded up TS. Jumpjet Inf, Wolverine, Titan, and Juggernaut all don't render.

**Comment by reaperrr** [comment]
These are yaml issues, I'll add a Ruleset loading check to avoid these in the future.

With one exception: I don't see why the Jumpjet doesn't render, only using CustomRenderSize instead of AutoRenderSize worked for me. The shp bounds themselves can't be the problem (it worked before when AutoSelectionSize was used for render bounds, afterall), so the bug is likely related to handling multiple sprite/infantry bodies on one actor.

**Comment by pchote** [comment]
Note that I don't get the ping when that is edited in after the first submission :wink:

**Comment by reaperrr** [comment]
The problems with sprite bounds are more complicated, I'll file a separate PR for that so we can get this PR out of the way more quickly.

**Review by abcdefg30 — APPROVED** [review]

**Review by Smittytron — APPROVED** [review]

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4e981fadef86be9f58fa4eb4595550ac8f833c3b...6a45803340e992a4706f7eea553a8914066363a0)

**Pull request merged**
