### PR TITLE
Download and install the required dependencies for freetype6

### PR DESCRIPTION
**Pull request by LipkeGu**
Add Visual C 2010 SP1 ...

### CODE REVIEW

**Comment by LipkeGu** [comment]
Browser session was out of Sync X.x

**Comment by penev92** [comment]
As a user I really hate when programs decide they can download and install random stuff whenever they feel like it.
I am OK with the current fetch script, because that only downloads a few DLLs, and doesn't affect your system in any way.

The fact that you download and install this no matter what in your current implementation (the check has *nothing* to do with the download as you've wrote it, it tries to download an .exe from a link that nobody can guarantee won't change. This isn't a really good thing by itself.
Also there is a ton of stuff that can go wrong with the installation - the user might not have permissions, the installation process can fail due to whatever reason, the script can throw when trying to delete the file that you just started...

:-1: for automatic installation (of anything)

**Comment by LipkeGu** [comment]
@penev92 #8382 <- we could use this PR

**Comment by penev92** [comment]
Yes, that one I agree with.

**Pull request closed without merging**
