### PR TITLE
D2K - Add Harkonnen 5

### PR DESCRIPTION
**Pull request by MustaphaTR**
Something is off with Ordos' Outpost/Power level and i'm not sure what. Outpost looks disabled. I spammed Wind Traps on editor to test but it didn't change anything. Power level also should be OK according to my calculations.

This also adds Modified Outpost tooltip to Ordos 4, which that Outpost were in original game. It doesn't really matter for that mission infact, as you weren't able to see it (it would show Enemy Structure) in original. It is in OpenRA right now tho.

### CODE REVIEW

**Comment by reaperrr** [comment]
> Something is off with Ordos' Outpost/Power level and i'm not sure what. Outpost looks disabled. I spammed Wind Traps on editor to test but it didn't change anything. Power level also should be OK according to my calculations.

Might be a regression from my power traits refactor, I'll check when I get around to reviewing this.

**Comment by MustaphaTR** [comment]
I made the player Ordos Main Base to test, Outpost looks disabled. it doesn't provide radar either. Power level is OK.

**Comment by ltem** [comment]
Plays like the original, even better, Corrino is attacking what didn't happen for some reason in the original. Also didn't find any issues in the code.

Two things I noticed:

1. It wasn't possible to build `Siege Tanks` for the Harkonnen-player.

|image|
|:---:|

2. If you wall of the `Modified Outpost`, the enemy units won't attack it anymore. I'm quite sure this happens due to the pathfinding but I don't see it as a problem.

So as soon as a solution is found for the Power level and the `Siege Tank`, I will approve this PR.

**Comment by MustaphaTR** [comment]
Updated. Disabled the Siege Tank. #14416 is gonna fix the power. It is not related to this PR.

**Review by ltem — APPROVED** [review]
I rebased #14416 onto this pr and it fixed the power level issue, so 👍.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c86e221a526ade01693e5f0e9c4d59f1369ee837...8807a9bc6993018fe7029e8862fa2eb8eefdd23d)

**Pull request merged**
