### PR TITLE
Move MiniYaml into its own OpenRA.Markup project

### PR DESCRIPTION
**Pull request by phrohdoh**
This will allow other projects/tools to depend on miniyaml structures and parsing without needing the entirety of the engine.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Rebased but now I need to remove `OpenRA.Mods.Common/UtilityCommands/LegacyMapImporter.cs` because the original removal must have been lost in the rebase.

**Comment by Phrohdoh** [comment]
Removed and ready for review.

**Comment by obrakmann** [comment]
Similar to [this comment](https://github.com/OpenRA/OpenRA/pull/10654#issuecomment-177563890), I think it would be better to let this be part of a PR that actually has code that uses it. Otherwise it's just needless churn in preparation for code that may or may not ever turn up.

**Comment by penev92** [comment]
My two cents (so this doesn't get merged because "it works" without at least this):
>[17:16:26]	< penev> I guess my question is "why should this change be made upstream" 
...
[17:34:47]	< penev> `¯\_(ツ)_/¯` if you ask me it's best where it is 
[17:35:24]	< penev> having a DLL with 1 class that is used by 1 other project just for the sake of a downstream experiment...
[17:35:31]	< penev> doesn't justify the upstream wtf IMO 

And just to be thorough - regarding the "to move it out of the engine":
>[17:18:23]	< penev> if this really needs to move (which I don't see), the (possibly not-yet-existing) FileFormats project would probably be the place for it 
[17:32:14]	< pchote> penev: there is a difference between a mod-level fileformats dll and an engine-level fileformats dll 
[17:32:27]	< pchote> mod-level is good, because its all implicit
[17:32:32]	< pchote> nothing actually cares about the things in it
[17:32:37]	< pchote> because its all via interfaces 

This one here doesn't actually abstract away from the MiniYaml code specifics.

**Comment by Phrohdoh** [comment]
```
[01:53:06]	<Phrohdoh> Points against both of my PRs were fair and valid so I've closed them.
[01:53:18]	<Phrohdoh> I'll try to get a prototype I feel I am able to show soonish to validate my approach. 
```

**Comment by chrisforbes** [comment]
Nak for calling something 'markup' that isn't.

**Pull request closed without merging**
