### PR TITLE
reset RallyPoint Location after building was captured. resolves #9163.

### LINKED ISSUE #9163: Rally points of captured buildings are not reset
The rally points of captured buildings are not reset to the default rally point.
Tested with release-20150614 and playtest-20150808.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26161990-rally-points-of-captured-buildings-are-not-reset?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Arcitectus**
resolves #9163.

### CODE REVIEW

**Comment by penev92** [comment]
Looks good :+1: 
Thanks.

**Comment by huwpascoe** [comment]
:+1:

**Comment by obrakmann** [comment]
Thanks!

[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/f5645c3350d1f62fb6ba27c4f377c96bc0a55056)

**Comment by reaperrr** [comment]
@Arcitectus: Feel free to file a PR adding yourself to [AUTHORS](https://github.com/OpenRA/OpenRA/blob/bleed/AUTHORS#L25) :)

**Pull request merged**
