### PR TITLE
'Fix' RA wood crate colors and add shadow to TD wood crate

### PR DESCRIPTION
**Pull request by reaperrr**
TD:
Adds frame with shadow to TD wood crate (and uses it by default), drops `crate.shp` (scrate with shadow) in favor of custom scrate.shp with additional frame with shadow, fixes `WCRATE` actor to actually use `wcrate` shp.

RA:
Restores original wcrate colors while keeping shadow fix.

Note on the RA wood crate: Going back to the original colors has one potential downside that probably doesn't matter now, but may in the future:
The water version (wwcrate.shp) actually uses the correct wooden color scheme, so if we ever drop wood crates over water, we may need to rethink this, or add a TD-style palette scheme and use that for the parachute frame when dropping wood crates over water.

Supersedes #19175.

### CODE REVIEW

**Comment by pchote** [comment]
> The water version (wwcrate.shp) actually uses the correct wooden color scheme

What if we keep the original incorrect crate colours for the campaign, and use the fixed palette version for skirmish/mp?

**Comment by reaperrr** [comment]
> What if we keep the original incorrect crate colours for the campaign, and use the fixed palette version for skirmish/mp?

That's one possibility.

Though in that case we should first be clear on some things:
- Do we actually plan to enable crates spawning/dropping on water during skirmish/MP?
- Do we actually plan to use wcrate for the skirmish/MP crates (iirc we use scrate now because players preferred that since it's easier to spot on ore, desert terrain and such)?

**Comment by Smittytron** [comment]
> - Do we actually plan to enable crates spawning/dropping on water during skirmish/MP?
> - Do we actually plan to use wcrate for the skirmish/MP crates (iirc we use scrate now because players preferred that since it's easier to spot on ore, desert terrain and such)?

I'd personally like to see water crates. I'm a fan of adding in as many og assets as we can and I think it would benefit water maps. Competitive games don't use crates in the first place so there shouldn't be balancing concerns.

I'm thinking we should stick to `scrate` for MP/skirmish. Tan crates on ore or green crates on grass will be harder to spot than blue.

**Comment by reaperrr** [comment]
> I'd personally like to see water crates. I'm a fan of adding in as many og assets as we can and I think it would benefit water maps. Competitive games don't use crates in the first place so there shouldn't be balancing concerns.

Apparently the possibility was already there in the RA mod, I've just never seen one (probably because the effective chance is quite low).

I've still decided to add support for spawning a different crate actor on water, because that gives us (and 3rd-party mods) the option to tailor things like the GiveUnitAction to the respective terrain type.

**Comment by pchote** [comment]
Water crates were broken for many years, and only recentlyish fixed!

**Review by Smittytron — DISMISSED** [review]
LGTM

I was wondering if we'd need a splash or something for water crates dropping out of planes but it looks seamless enough for me.

**Comment by pchote** [comment]
I believe that the final two commits can be removed or simplified: we already support water crates! I believe we should just be able to move the new crate actions onto the standard crate type, avoiding any new actors.

The `^Crate` definition includes `Water` in the allowed terrain types for all crates, and `WithCrateBody.WaterSequence` is used for the water-specific art.

**Comment by reaperrr** [comment]
Updated. I originally thought supporting separate water crate actors would be a good idea, but you're right that it's not really needed here, so I only kept the additional GiveUnitCrateActions for ships.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bd1ec6e60013a2a974be74870dfeaf09796b5473

**Pull request merged**
