### PR TITLE
Add an explicit YamlException to ParatroopersPower.SendParatroopers

### PR DESCRIPTION
**Pull request by phrohdoh**
Instead of a `KeyNotFoundException`.

### CODE REVIEW

**Comment by obrakmann** [comment]
Can you show the yaml with which you get the `KeyNotFoundException`? I get "Exception of type `System.NotImplementedException`: No rules definition for unit e17" on both this branch and bleed when I add a typo to the unit list:
```
	ParatroopersPower@paratroopers:
		DropItems: E1,E1,E1,E3,E17
```

**Comment by obrakmann** [comment]
:+1:

**Comment by RoosterDragon** [comment]
:+1:

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/b88e5ede49c03bac34a7b2e2ca6a956dbd94a8c8)

**Pull request merged**
