### PR TITLE
Fix map editor sliders stealing focus

### LINKED ISSUE #20482: Changing facing/turret/health of an actor in map editor disables hotkeys.
If you edit any of these by typing in numbers rather than using the slider your hotkeys will be disabled, including escape, until you select another actor.

Steps to reproduce are easy:
select actor
type in a different facing/health/turret
try and use escape/c/v/f1/etc.

### PR DESCRIPTION
**Pull request by PunkPun**
Fixes #20482

### CODE REVIEW

**Review by dragunoff — CHANGES_REQUESTED** [review]
The value fields should also yield focus inside the `Close` handler. Otherwise the focus remains in the field if we click any of the "OK", "Cancel" or "Delete" buttons.

**Comment by dragunoff** [comment]
And this is another case of #19761

**Comment by PunkPun** [comment]
Added yielding to Close

**Review by dragunoff — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8db99ce7690ecca213eb3c59fda1113dddb1f945...5242af107c2bc3f98fa618e03bdd4ea3dc514ea1)

**Comment by abcdefg30** [comment]
Picked to prep as discussed: https://github.com/OpenRA/OpenRA/commit/f551b542f34c546ae3aeb58cc6f9cffc4d8c5e52

[Changelog (bleed)](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5242af107c2bc3f98fa618e03bdd4ea3dc514ea1...07847d625ef296a39832b4e8488c45830f90f5b1) -> [Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/d5f8b2b348c90d11962515ecfd4bccb666c25457...a6c54212d4a9f5be8f4f174dd8214e95b5253528)

**Pull request merged**
