### PR TITLE
Fixed .shp icons not being displayed in the asset browser

### PR DESCRIPTION
**Pull request by Mailaender**
This is a followup of https://github.com/OpenRA/OpenRA/pull/17984.

### CODE REVIEW

**Comment by pchote** [comment]
What if we have a real WSA with one frame that we want to load?

**Comment by Mailaender** [comment]
WSA stands for Westwood Studios Animation and 1 frame by definition is not an animation to me. I also don't know how else to fix it. Those files don't have proper magic bytes.

**Comment by pchote** [comment]
I scanned through the RA and TD files and couldn't see any single frame wsa, so this is *probably* ok even though I'm not a fan of it.

**Review by pchote — DISMISSED** [review]

**Comment by reaperrr** [comment]
Maybe at least add a comment explaining the purpose of this check (also as reminder to remove it if we ever find a more elegant solution)?

**Comment by Mailaender** [comment]
Left a `TODO`.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/43ff1397d6a2efbe65c462525615260a37b18dad...419b033e8cfe948af5ef58c438c37f62f8b4bf80

**Pull request merged**
