### PR TITLE
Remove flawed RateLimit implementation.

### LINKED ISSUE #16195: "Unit Ready" voice notification is silent sometimes
Second part of #16117 that feels like a regression.

It is not consistent, but generally you can have "Unit Ready" not voiced when for example producing 100 rifle infantry in a row - it is produced for 4-5 rifles, then is silent for the next 4-5, then sounds again for consequent ones.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #16195.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by chrisforbes** [comment]
Actually fixing this would be better than ripping it out?

**Comment by chrisforbes** [comment]
For stable: +1.

**Review by chrisforbes — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/f32a5c1f143c657be89b01e2cdd89b991d0f65f2

3a94c74c4423ec132af303a976ca23d94ae2a399

**Comment by KOYK** [comment]
I removed RateLimit from my TDO mod and I want to know if there is any need for further changes on my end.

**Pull request merged**
