### PR TITLE
Fix shader type conversion.

### PR DESCRIPTION
**Pull request by pchote**
Regression from #21146.

### CODE REVIEW

**Comment by dnqbob** [comment]
I apply the fix in this PR to fix the Angle crash, but the graphic glitches at the start of the game.

test

On https://github.com/ABrandau/Shattered-Paradise-SDK/commit/657a9883ecf74008d9a6869dcbb42539b2b9f7bc
Engine rebased to https://github.com/OpenRA/OpenRA/commit/3bb42522b87d54c585e655cfb7d72668164a154a

**You need to apply the change in this PR manually**

Runtime: .NET CLR 6.0.11
Using SDL 2 with OpenGL (ANGLE) renderer
Desktop resolution: 1600x900
Using resolution: 1572x806
Using window scale 1.00
OpenGL renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.101.1122)
OpenGL version: OpenGL ES 3.0.0 (ANGLE 2.1.20989 git hash: 5c0b4251bd2c)
Using default sound device

Use "WIndowed" instead of "Full Screen".

Plus: OpenGL-Mordern doesn't have the glitches.

**Comment by pchote** [comment]
That is a different, unrelated, issue.

**Comment by dnqbob** [comment]
I will make a separated issue, then.

**Review by PunkPun — APPROVED** [review]
This has been reported to have fixed the issue and I haven't noticed any regressions

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2b88a05accf60c9b7574788e1f5a1793ad064257...4d05cfb2eca5311cd0d2c2c8a2c74fa3f7434add)

**Pull request merged**
