### PR TITLE
Add a missing description to the difficulty dropdown in allies-10a

### PR DESCRIPTION
**Pull request by abcdefg30**
Reported by @Smittytron and @JovialFeline on Discord. Without a description we crash on bleed:
```
Unhandled exception. System.ArgumentException: A translation key must not be null or empty. (Parameter 'key')
   at OpenRA.Translation.TryGetString(String key, String& value, IDictionary`2 arguments) in \OpenRA\OpenRA.Game\Translation.cs:line 92
   at OpenRA.Translation.GetString(String key, IDictionary`2 arguments) in \OpenRA\OpenRA.Game\Translation.cs:line 86
   at OpenRA.Traits.LobbyOption..ctor(String id, String name, String description, Boolean visible, Int32 displayorder, IReadOnlyDictionary`2 values, String defaultValue, Boolean locked) in \OpenRA\OpenRA.Game\Traits\TraitsInterfaces.cs:line 550
   at OpenRA.Mods.Common.Traits.ScriptLobbyDropdownInfo.OpenRA.Traits.ILobbyOptions.LobbyOptions(MapPreview map)+MoveNext() in \OpenRA\OpenRA.Mods.Common\Traits\World\ScriptLobbyDropdown.cs:line 51
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at OpenRA.Mods.Common.Server.LobbyCommands.LoadMapSettings(Server server, Global gs, MapPreview map) in \OpenRA\OpenRA.Mods.Common\ServerTraits\LobbyCommands.cs:line 1210
   at OpenRA.Mods.Common.Server.LobbyCommands.ServerStarted(Server server) in \OpenRA\OpenRA.Mods.Common\ServerTraits\LobbyCommands.cs:line 1179
   at OpenRA.Server.Server.<>c__DisplayClass54_0.<.ctor>b__2(Object _) in \OpenRA\OpenRA.Game\Server\Server.cs:line 351
   at System.Threading.Thread.StartCallback()
```

Added the same description all other missions have.

### CODE REVIEW

**Comment by PunkPun** [comment]
This would have already been fixed by #20585

**Comment by Mailaender** [comment]
Please submit to prep instead.

**Comment by PunkPun** [comment]
prep doesn't have mission translations

**Comment by PunkPun** [comment]
Ah, I see what you mean. Yeah prep would benefit from the addition of missing descriptions

**Comment by abcdefg30** [comment]
Closing as superseded by #20585.

**Pull request closed without merging**
