### PR TITLE
Add D2k Attack outside range cursor

### LINKED ISSUE #20548: D2k needs "Attack outside range" cursor
Dune 2000 is missing a unique cursor animation for ordering units to attack outside their range, and I don't like that.
So here's my take: 
cursor 0000
The attack cursor animation with the ring colored green.
[attackoutsiderange.zip](https://github.com/OpenRA/OpenRA/files/10229507/attackoutsiderange.zip)

### PR DESCRIPTION
**Pull request by Porenutak**
Closes #20548

### CODE REVIEW

**Comment by ThomasChr** [comment]
Tested it - seems to work just fine!
I'm not quite sure if I'm happy with the "in range"-Cursor beeing white and the "out range"-Cursor beeing green - but it does what it says on the tin.

**Comment by Porenutak** [comment]
Maybe it wold be better to have white cursor for Out side range and green in range. But it's up to taste.

**Comment by penev92** [comment]
FWIW what I (and I would assume most of the C&C veterans) are used to is a mid of red/green for "out of range"/"need to move before firing".

**Comment by PunkPun** [comment]
gif

**Comment by Porenutak** [comment]
After some playtest I must admit its not good idea. The green color on any attack cursor is more confusing that helpfull. 
Closing for now.

**Pull request closed without merging**
