### PR TITLE
Add MinelayerBotModule

### LINKED ISSUE #18266: Mine Layer Bot Module
I imagine this to be a mixture of the defense building placement and the MCV deployment routines.

### PR DESCRIPTION
**Pull request by dnqbob**
Add an AI module for control minelayer. It does not work very well in RA because the mine can friendly-fire so I put it here only as some kind of idea showcase if someone wants to explore this further.

Closes https://github.com/OpenRA/OpenRA/issues/18266

### CODE REVIEW

**Comment by PunkPun** [comment]
Closes #18266

**Comment by dnqbob** [comment]
This module cannot solve the concern of AI step on their own minefield in #18266, but I don't think we have idea on AI to avoid the friendly mine at present (also consider if mine is layed by allies, not this bot module).

If we stick to friendly fire mine, we need a mechanic to let AI consider mines when pathfinding while human player doesn't, which needs some refactoring on pathfinding and looks hacky between codes.

 I would like another way which is block allies walk on friendly mine, which only cost a line of MiniYaml. We need to persuade player to accept it, though.

**Comment by dnqbob** [comment]
Except friendly fire mine problem, the module works as promise on AI game. I am curious about how it behaves in human against AI.

**Comment by PunkPun** [comment]
In RA units need to be able to step on friendly mines, otherwise in multiplayer this leads to very unhealthy strategies and gameplay

**Comment by dnqbob** [comment]
> In RA units need to be able to step on friendly mines, otherwise in multiplayer this leads to very unhealthy strategies and gameplay

Then we need a setting on Mine and Crushable, which allows bot player consider those when pathing.

Maybe not very hard, consider we already have Crushable conditional.

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ee1e8c17e1c4f0e62ce98a5a270d2875108dd139...67c1f925027c583fb8b6cabb74f2e11f5a1aab5f)

**Pull request merged**
