### PR TITLE
Added large blue tib crystals to Hot Springs

### PR DESCRIPTION
**Pull request by reaperrr**
I just tested the map in the original and noticed it had these blue tib spawning large crystals of the 'remapable' variant (`BIGBLUE`), so I added them.

I also noticed our custom, fixed sprite (with shadow) doesn't need the Y axis shift, so I fixed that, too.

### CODE REVIEW

**Comment by reaperrr** [comment]
Depends on #13942.

**Comment by Mailaender** [comment]
Any idea why they weren't automatically imported?

**Comment by reaperrr** [comment]
I just had a hunch and checked the original .map file, BIGBLUE is not listed under [Terrain], so the only logical explanation is that it's in fact actually [Cruentus] tiberium type (overlay), despite the rules.ini comment that claims it's unused. Looks like the WW mapper forgot/wasn't aware of it or the comment was outdated by the time FS shipped.

That overlay still served as de-facto blue tib spawner, so using BIGBLUE instead isn't wrong.
Maybe we should investigate adding an import rule that converts any Cruentus cells to BIGBLUE instead of blue tib, though the question is if there are any other maps with Cruentus at all, because if not, it would be a waste of effort, now that this one is fixed.

**Comment by Mailaender** [comment]
Is Cruentus the overlay 178 compare https://github.com/OpenRA/OpenRA/issues/12518#issuecomment-323755206?

**Review by pchote — APPROVED** [review]

**Pull request merged**
