### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by Micr0Bit**
Combine is one of OpenRA's long-time modders and used to create graphic-content and upload it on the old ressource-center ... he also made our tutorial  "Converting a 3D infantry model to sprites" in the PixelArt-section which got translated by @Mailaender 

recently published his latest mod with custom graphics on our ressource-center

http://www.sleipnirstuff.com/forum/viewtopic.php?t=15943&highlight=
https://github.com/OpenRA/OpenRA/wiki/Converting-a-3D-infantry-model-to-sprites
https://www.youtube.com/watch?v=t_g_xPGD0P4
http://resource.openra.net/maps/18950/

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Should get their OK on this.

**Comment by GraionDilach** [comment]
He made no contribution used in the project so I don't see why the justification would stand.

**Comment by Micr0Bit** [comment]
for me a "contribution" to openra is more then just about creating a PR on Github 
and he did write something valuable to help modders 

i did also add credits for soscared and fiveaces at a time when none of them did anything on github directly ... and fiveaces still didnt got interested

**Comment by GraionDilach** [comment]
FiveAces was involved in creating some news assets by then if I remember correctly.

CombinE did a mod. it is cool, but it's not a mod included in OpenRA. Again, no direct contribution. People who add a "comma or a period" still end up with a direct contribution. While I agree that there should be a minimum amount of PRs/patches sent before expanding the AUTHORS, but if I follow your logic, Umair Azfar Khan aka umairazfar aka Crossfire mod owner would've been listed for years now due to the fact he  added dozens of tutorials in 2013-2014 (with a lot of them had to be hidden due to being too outdated for nowadays use). But his name is missing.

**Comment by Micr0Bit** [comment]
>FiveAces was involved in creating some news assets

you might confuse that with my contributions (i did add some assets which got PR'd by other people) ... but if he did , he didnt earn his credit-entry with "any" of your mentioned contributions 

https://github.com/OpenRA/OpenRA/pull/10840

i always try to backup my request by showing links with a bit of work from the authors ... so i dont see a reason why "not" to add Umair Azfar Khan aka umairazfar

if you feel like he deserves a entry or he got neglected/not considered ... feel free to to pr a entry with 1-2 links that are still relevant

**Comment by umairazfar** [comment]
gee, thanks guys! I honestly do not think that I should be added as an author unless I have added something to the project that has become a part of the default package. I was planning on writing the single player missions for Ordos in Dune mod but could not find time to write more than one mission. Anyway, if you guys thin that I should add myself, then I will. 👍

**Comment by Micr0Bit** [comment]
since theres nobody else with the guts or an idea to add weight on a opinion , ill close it 

@umairazfar : i guess we have to wait for your ordos-mission then :simple_smile:

**Pull request closed without merging**
