### PR TITLE
Moved configure native dependencies

### PR DESCRIPTION
**Pull request by Mailaender**
Fixup of https://github.com/OpenRA/OpenRA/pull/8076.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Ok, :+1:. Could have just merged and `chmod`'d if necessary.

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f968d0332ffcfd7a3c3a33727ad38eb3cb5813c0...9c9127e398cf1a1a104ad2203bb0c9fed3a015c7) (it's important for Linux packagers).

**Comment by Mailaender** [comment]
[Updated documentation.](https://github.com/OpenRA/OpenRA/wiki/Compiling/_compare/cebeabdee2ba58761e9081836b2fe0e197633418...d5cdf3db5e062a1e45f533b97632cb2fd122f3a4)

**Pull request merged**
