### PR TITLE
Explicitly specify line-endings of source files in gitattributes.

### PR DESCRIPTION
**Pull request by GraionDilach**
Related to #15273.

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Review by Smittytron — DISMISSED** [review]

**Comment by pchote** [comment]
Are you sure that this doesn't conflict with the `autocrlf` repository setting?

**Comment by GraionDilach** [comment]
I never heard about that setting so I don't know if it does. I am already using the csproj line in AS/Engine for a year now though and noone had any issues out of it from what I heard so I don't think it would.

There are a good amount of these issues cropping up lately though and I thought it's about time to prevent them happenning again.

**Comment by pchote** [comment]
`core.autocrlf` is (was?) the default configuration when installing Git on windows.  It would automatically convert all files to crlf line endings on checkout, then automatically convert them back to lf when committing.  I would expect this to make all the `eol=`s redundant, but this is clearly not the case since we already have lines for lua and yaml.

**Comment by pchote** [comment]
How odd.  It looks like a couple of *my* recent PRs have introduced new uses of crlf.  Must be some change in vs:mac, and shows why this PR is useful.

**Review by pchote — APPROVED** [review]
Added a commit to fix the recent line ending regressions, and rebased. :+1: once travis passes.

**Comment by pchote** [comment]
No changelog necessary.

**Pull request merged**
