### PR TITLE
Fix issues in Allies01 and Monster Tank Madness

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by Phrohdoh** [comment]
Yes.

**Comment by penev92** [comment]
Wouldn't have, had you pressed the merge button before asking :D
Anyway, :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/1deda894ae529c657f702ff48da4cf38363e0130...098c4c701bc8c6ea024845b022e9d7ebc8141757)

**Pull request merged**
