### PR TITLE
Add PlayLaunchSounds() to SupportPowers which are missing it

### LINKED ISSUE #17635: Incoming/LaunchSpeechNotification/Sound only work for some *Power:s.
`PlayLaunchSounds()` function gets called from Nuke, IonCannon, Airstrike, Paradrop, SpawnActor and PrerequisiteChargeDrain powers, and GPSPowers separately play LaunchSpeechNotification/Sound but not Incoming. The rest of the *Power:s do not play those notifications.

Altho this is an easy fix, not sure if there is a reason why `PlayLaunchSounds()` isn't called from `SuperWeapon.Activate()`, so i don't know if it all should be moved there, or it should be added to missing powers.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Fixes #17635.

### CODE REVIEW

**Comment by reaperrr** [comment]
Are there any powers other than GpsPower that don't trigger it from Activate? Could we just move this to base.Activate instead?

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA/issues/17635#issuecomment-580726683

**Review by Mailaender — APPROVED** [review]
Looks sane and I can't spot side effects in-game.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/96f9421a857ef180d19f1657e9fb2efceaeb63e2...2b8cd119d675101b9e4f7b80a08843e792d5597d

**Pull request merged**
