### PR TITLE
Fix Windows Uninstall is incomplete

### PR DESCRIPTION
**Pull request by Shkarlatov**
Fix issue #2790.  Uninstaller not remove %appdata%\OpenRA

### CODE REVIEW

**Comment by MustaphaTR** [comment]
This doesn't sound right. 3rd party OpenRA mods write data there too, uninstalling base OpenRA should not just delete the whole user folder.

**Comment by Shkarlatov** [comment]
Third party mods have to take care of their files themselves. There should be no files left when deleting.

**Comment by MustaphaTR** [comment]
3rd party OpenRA mods made with the OpenRA Mod SDK are standalone and do not require OpenRA. This PR makes it so you are deleting files written by 3rd party mods by uninstalling OpenRA. There is also the fact you can have parallel installations of different OpenRA versions, you wouldn't want to lose the user content because you uninstalled an old version. User folder should only be deleted if there are no other instances of OpenRA, basegame or 3rd party, installed on the device.

**Comment by Shkarlatov** [comment]
It is wrong to leave files. But I agree with you that deleting mod and map files is not good. It might be worth adding a dialog "Save settings, mods and maps?"

**Comment by penev92** [comment]
- Removing the folder when third-party mods might be using them is bad.
- A dialog to keep/remove is best.
- Since OpenRA is an engine, not a game, so this might still screw over any sufficiently custom game based on it that the player doesn't know is OpenRA and so doesn't know to preserve that folder ... ***in theory***. In practice since ora is an engine it shouldn't have its own folder there anyway and also any sufficiently customized game should use a different folder.

**Comment by pchote** [comment]
It is not just a problem for third party mods, but also for side-by-side installs of the default mods (e.g. playtest vs release, historical builds for watching replays etc), and the shared metadata for cross-mod switching.

It is not appropriate to delete everything without warning, or even by default. If we added a dialog to prompt the user on uninstall the default option must be to keep it.

**Comment by Shkarlatov** [comment]
I added a checkbox "Keep user data (settings, mods, maps,...)". Checked by default.

**Comment by pchote** [comment]
I don't have an immediate suggestion for what wording to use, but I think it needs to be a lot stronger. I don't think its clear at all that uninstalling e.g. Shattered Parasise with this option enabled would wipe all of your Red Alert maps and replays.

**Comment by Shkarlatov** [comment]
If it is impossible to separate the engine files from other files, then it's time to refactor :) 

I think we should unambiguously determine which files belong to mods and possibly allow overriding the paths to settings and content files by mod.

**Comment by pchote** [comment]
> If it is impossible to separate the engine files from other files, then it's time to refactor :)

The thing is that the current behaviour was explicitly intentional.

The support directory is defined as a shared location across all OpenRA based projects, solving two main problems:
* The data file for each game can end up being more than 1GB once players have installed the videos and music. A lot of people don't want to (or aren't able to) duplicate these multiple times for different mods.
* The in-game switcher needs to know which other OpenRA based projects are available on the system to run. The only reliable cross-platform way to do this is by having them all write metadata files into a known location (the ModMetadata subdirectory).

While its not unreasonable to want to separate things, alternative solutions need to be found for these first.

**Comment by Shkarlatov** [comment]
How about indexing mod files and building a dependency system? Mods must explicitly specify the files to use. User-generated content will also need to be tagged.

**Comment by penev92** [comment]
We could probably merge this with a sufficiently stern warning about removing all user data as well as settings and content for all OpenRA-based things ever installed.
Otherwise we either go with "each uninstall removes its own stuff" or we close this.
Either way it's no good keeping it open indefinitely.

**Comment by abcdefg30** [comment]
No activity for a while, so closing. Feel free to revisit this.

Making this optional with the "stern warning" as described by @penev92 would Imho be fine for now.
(Although going with "each uninstall removes its own stuff" is preferable.)

**Pull request closed without merging**
