### PR TITLE
Make the circle and arrow sequences of Beacon optional

### PR DESCRIPTION
**Pull request by abcdefg30**
You might only want to use one of them, especially for support powers, where you can't use `AnimatedBeacon` or just want a `beaconposter` without any other animations.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
The lint passes should probably guarantee that at least one is used.

**Comment by abcdefg30** [comment]
Are we sure about that? As I said, you might only want a `beaconposter`.

**Comment by Phrohdoh** [comment]
Oh, sorry I had forgotten that was a part of the beacon setup.
That's what I get for making quick comments.

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3094568fe01ea99609fbc035fa81501cc6a0051f...8143e51c8e3187beb18e5d9815ce081d1383061e)

**Pull request merged**
