### PR TITLE
ReinforceWithTransport: no hardcoded land facing

### PR DESCRIPTION
**Pull request by dnqbob**

### CODE REVIEW

**Comment by PunkPun** [comment]
Why does it need to be changed? Wouldn't be inconsistent if initial facing field was ignored?

**Comment by dnqbob** [comment]
No, initial facing should be used in creation of the actor while in this function use it as facing on landing! This makes aircraft turns to its initial facing and land, looks very weird from normal landing behavior.

**Review by PunkPun — COMMENTED** [review]
In the Land activity it's also used as a default. I suppose defining it here is pointless then

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
I tested it and it seemed to work correctly. Though I missed a comment...

I tracked it down to https://github.com/OpenRA/OpenRA/pull/16509#discussion_r298810962. It doesn't feel critical but probably something we should address

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8f538a545b8b713fe8b0420e608d3823a685b73f...d6961db770969f39048745c3f688320f0308d4b4)

**Pull request merged**
