### PR TITLE
Add support for queued AttackMove and Guard orders.

### LINKED ISSUE #13708: Queuing Amoves
I have been playing since februrary this years and i never been able to queue amove orders.

I mean i would love to use the shift key (or now the hud) to queue some amove allowing my units to follow a multiple waypoint trajectory and staying in attackmove and engaging enemy at any moment.

That would allows to do manual effective/offensive patrols as well, right know i can just make in patrol a unit that will just look enemy units pass by minding its own bizness.

I wanted to know if it's intended that way or a feature to come or a bug. (ultimate case, maybe i did thing wrong and just could't do it)

### PR DESCRIPTION
**Pull request by pchote**
Fixes #13708.

### CODE REVIEW

**Comment by obrakmann** [comment]
This will only work until the unit encounters its first target, then the whole queue will be cleared [here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L366-L367), after which `AttackMove` will restart due to `TickIdle`, but it'll not go to the intended destination, but to whatever location was queued last (`AttackMove.TargetLocation`).

See also #7454, and the last commit of https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:activities-pt3

**Comment by pchote** [comment]
Yup, but that happens regardless of whether the `AttackMove` itself is queued or not by the player so IMO isn't really relevant here.

**Review by abcdefg30 — APPROVED** [review]

**Review by rob-v — COMMENTED** [review]
It doesn't work. There could be some property that hotkeys would always work regardless of modifier, e.g. Shift+A would be always Attack move or in GenericSelectTarget it shouldn't cancel when queued or ...
The issue is while holding A key and you press Shift, Attack move is deactivated afterwards as Shift+A isn't recognized as AM hotkey.

**Comment by pchote** [comment]
> There could be some property that hotkeys would always work regardless of modifier

Yes.  This is waiting on #13706, #13711, and a ready-but-not-PRed part 3.
For now it only works when using the command bar button with the mouse.

**Comment by rob-v** [comment]
So Has dependencies and better to wait with approval/merge (i think yes) or you prefer to merge it sooner?

**Comment by pchote** [comment]
I consider that to be a distinct bug from what this PR is aiming to fix, but i'm not the one reviewing this :smile:.  If you think that limitation hurts the goal of this PR then I won't objecting to waiting until we can fix that first.

**Review by Micr0Bit — APPROVED** [review]

**Review by Mailaender — APPROVED** [review]
Code looks fine. :+1: Indeed this doesn't work well as the command bar doesn't accept stacking of shift waypoint mode with anything other then move. However you can now attackmove and then chain a now shift move afterwards so it works. :white_check_mark:

**Pull request merged**
