### PR TITLE
Fix asset installation on 32 bit windows and with original RA CDs.

### LINKED ISSUE #12316: Installer metadata origin registry keys only work for 64 bit installs
Installs on 32 bit windows / wine use a different prefix: `HKEY_LOCAL_MACHINE\Software\EA Games\`.

### LINKED ISSUE #12473: RA content installer test files don't exist on original CDs.
`eahelp.GID` and `automenu.apm` were added in the later freeware isos.  To fix this properly we need to add support for defining a data range to sha1, and then test the first kB or so of main.mix.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #12316.
Fixes #12473.

### CODE REVIEW

**Comment by reaperrr** [comment]
> OpenRA.Mods.Common/ModContent.cs:L51: [SP2000] Invalid spacing at the end of the line.

> OpenRA.Mods.Common/Widgets/Logic/Installation/InstallFromDiscLogic.cs:L492: [SP2000] Invalid spacing at the end of the line.

**Comment by pchote** [comment]
Fixed.

**Review by obrakmann — APPROVED** [review]
Looks good to me, 👍 . Again, couldn't test myself unfortunately.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ec3720017865cd5ccec720cf6dcf5d6e42d0fabc...48067ac78863278fd504c66965ac887cf383231c)

**Pull request merged**
