### PR TITLE
D2K - Add Baron's Court to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Resource center started to give Server Error (500) to me, i converted 11 more maps, but only could upload 2 of them, so there is one.

https://resource.openra.net/maps/24430/

### CODE REVIEW

**Review by ltem — APPROVED** [review]

**Comment by FrameLimiter** [comment]
My vehicles were unable to access the center of the map. So I couldn't harvest the spice in the middle. I'm not that familiar with d2k; is there a game mechanic that allows access to the middle?

**Comment by MustaphaTR** [comment]
Carryalls.

**Comment by pchote** [comment]
Carryalls won't automatically ferry harvesters back and forward from the central area, probably because the DomainIndex is killing the move before it can check.

I would prefer that we held off merging this or similar maps until that issue has been fixed.

**Comment by pchote** [comment]
This isn't likely to be fixable until the harvester-return logic is rewritten (probably as part of the long delayed docking rework). Moving to the future milestone.

**Pull request closed without merging**
