### PR TITLE
D2K - Allow all upgradable structures to build upgrades

### LINKED ISSUE #12665: D2K - Upgrades require Construction Yard
They shouldn't. It actually is easy to fix by moving upgrade production to `Player:` actor. But there is a small problem with it. If i do that After deploying the MCV at start, Upgrade Menu is shown rather than Structure. This is because `ProvidesPrerequisite:` trait takes effect before the `Production:` trait. `Production`, afaik, waits for the buildup to finish before taking effect, while `ProvidesPrerequisite:` doesn't.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Fixes #12665. This doesn't cause upgrade tab to appear first when you deploy an MCV at the beginning of the game. (unlike moving it to Player: actor) But MCVless missions like Atr5 and Har9b show upgrades first, which i don't think much of a problem

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Hmm, i just noticed this still doesn't look correct. Selecting anything except Constrction Yard causes `ProductionQueueFromSelection` to select Upgrade tab. I guess it selects the first one according to order under `Player:` actor. We can fix that by 2 way:

1-) Move Upgrade tab to last under `Player:` actor. But this may effect other things, one that comes to my mind is order under Production spectator menu.
2-) Make it so `ProductionQueueFromSelection` uses the order at `Production: > Produces:` rather than `Player:` actor.

**Comment by MustaphaTR** [comment]
Updated. Done 1.

**Review by ltem — DISMISSED** [review]
I couldn't spot any issues and it works as advertised.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f50341b09dd94e255ba8d5043db76afa9dfbd72a

**Pull request merged**
