### PR TITLE
Optionally discard resources when silo capacity has been reached

### PR DESCRIPTION
**Pull request by teees**

### CODE REVIEW

**Comment by Mailaender** [comment]
Both cases work as promised. :white_check_mark:

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark: 

(Although think this behaviour is not fitting, but we want to stick to the original...)

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4a8bbe5d5730b62d3f7adfb1d758988bf87de5aa...f2e8763a2318c476c0a3eccd0591afabe2f4cbd5)

**Comment by pchote** [comment]
Balancing can come later.

**Comment by Mailaender** [comment]
It serves as a good reference/test case for now.

**Pull request merged**
