### PR TITLE
Fixed documentation deployment

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/actions/runs/3613778083

### CODE REVIEW

**Review by PunkPun — APPROVED** [review]

**Comment by abcdefg30** [comment]
> Fixes https://github.com/OpenRA/OpenRA/actions/runs/3613778083

fails with `error: pathspec 'playtest' did not match any file(s) known to git` during `Update docs.openra.net (Playtest)`?

**Comment by Mailaender** [comment]
It needs to be merged, so you can run the playtest tag with the script on bleed. You just ran the previous version without a tag.

**Review by pchote — APPROVED** [review]
Based on reading the workflow this does indeed look like a necessary fix; we'll see whether or not it is sufficient.

**Comment by pchote** [comment]
028467f1508b1dbf209e7703013e1da471723de6

**Pull request merged**
