### PR TITLE
Fix RA effect warhead submarine interaction

### LINKED ISSUE #14054: Submerged submarines are damaged by surface fire.
This is caused by the addition of "Water" to the SS & MSUB underwater TargetTypes.
I think simply removing "Water" from the SS & MSUB Underwater TargetTypes should fix this.
SS & MSUB:
->Targetable@UNDERWATER:
-->TargetTypes: **Water**, Underwater, Repair

[playtest-20170902 & bleed]

### LINKED ISSUE #14056: DepthCharge has no CreateEffect animation when hitting a surfaced submarine.
The DepthCharge projectile just disappears when it hits a surfaced submarine. The large_splash effect should still trigger when missing a target.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #14054.
Fixes #14056.

### CODE REVIEW

**Review by pchote — DISMISSED** [review]
LGTM :+1:

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
Depth charges still don't damage surfaced subs.

**Comment by abcdefg30** [comment]
Ah wait. I just saw the issue is only about the animation. That seems to be fixed.
Imho it is buggy to not do any damage but show an animation, though.

**Comment by reaperrr** [comment]
> Imho it is buggy to not do any damage but show an animation, though.

Good point. Not sure how much this might affect balance, though. 

Maybe we should instead display the water splash unconditionally and the explosion only on submerged subs, and continue to only deal damage to submerged subs.
Pinging @SoScared and @FrameLimiter for opinions on this matter.

**Comment by abcdefg30** [comment]
At the moment you can dodge depth charges by firing your sub torpedoes, which makes subs harder to kill (while they still deal damage).

**Comment by reaperrr** [comment]
Ok, already pushed a commit that fixes that.

**Comment by FrameLimiter** [comment]
I agree depth charges doing no damage to the surfaced vessels has always looked wrong / seemed bugged. However the side effect of enabling damage to ships is friendly fire when chasing submarines. Build 10 gunboats and chase 1 submarine and all your gunboats will kill themselves. 

IMO the depth charges will need to do significantly less damage against the surfaced units.

**Comment by abcdefg30** [comment]
> However the side effect of enabling damage to ships is friendly fire when chasing submarines. Build 10 gunboats and chase 1 submarine and all your gunboats will kill themselves.

We could disable depth charges against ships (they're not aimed at ships anyway) and make them only work for subs.

**Comment by reaperrr** [comment]
> We could disable depth charges against ships (they're not aimed at ships anyway) and make them only work for subs.

*sigh* That will require another new target type... well, ok.

**Comment by FrameLimiter** [comment]
Since submarines are light armor & all other vessels are Heavy, perhaps adjusting damage vs this armor type would work best. That huge splash doing "some" damage vs ships seems appropriate.

**Comment by reaperrr** [comment]
Updated.
Damage vs. Heavy armor reduced from 100% to 20% to reduce splash damage vs. other ships.

**Comment by reaperrr** [comment]
All this back and forth made me forget to actually include the fix... will update in a minute.

**Comment by pchote** [comment]
Depth charges are... well, depth charges.  Not triggering against surface objects is correct.

**Comment by reaperrr** [comment]
Updated.

Added `Submarine` target type to subs, made damage warhead & explosion effect wh only trigger on them.

> Unless we want to give them melee damage for a direct hit?

Let's leave that decision for Next+1, I don't feel like touching this PR any more (unless there's another bug/regression).

**Review by abcdefg30 — APPROVED** [review]

**Comment by pchote** [comment]
I wasn't serious :s  That was a joke about how the most likely way for them to damage surface craft would be to leave a dent when they bounce off without detonating.

**Comment by pchote** [comment]
Seems to work as advertised, so my :+1: still holds.

**Pull request merged**
