### PR TITLE
Change D2k power draw and various other aspects to match original

### PR DESCRIPTION
**Pull request by reaperrr**
After #9453, #9458 and this there should be only some minor loose ends remaining (Palace infantry, tweaking debris etc.).

### CODE REVIEW

**Comment by penev92** [comment]
Making infantry not attract worms will make them a whole lot more difficult to deal with, so I'm hesitant on that one.
Otherwise looks good :+1: 
Adding `Changes requested` for the engineers' `CaptureTypes`.

**Comment by reaperrr** [comment]
> Making infantry not attract worms will make them a whole lot more difficult to deal with, so I'm hesitant on that one.

That's what Thumpers should be for once they're implemented (which should be easy now with DeployToUpgrade and then enabling AttractWorms via upgrade on them).

**Comment by reaperrr** [comment]
Updated.

**Comment by pchote** [comment]
Needs a rebase.

**Comment by reaperrr** [comment]
Rebased.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d328e377beb374b133bd97ab98acfc5a0bbe28b0...d78cef09b26889be39fb63508d15e85e691426bc)

**Pull request merged**
