### PR TITLE
Add a dynamically generated bordercolor for supportpower timers

### LINKED ISSUE #11590: Add white border to countdown timers
It is very hard to read the timers of players who have selected a dark color. Perhaps a white border would help them stand out against the fog of war.

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #11590.

Once you got used to it, it looks quite ok/good, imho.
timerbordera
timerborderb

### CODE REVIEW

**Comment by pchote** [comment]
We have a much older ticket somewhere about automatically picking white or black based on the brightness of the player color.  That would be better than defaulting to white.

**Comment by abcdefg30** [comment]
Current WIP version looks like:
timerborder2atimerborder2b
timerborder2ctimerborder2d

**Comment by abcdefg30** [comment]
Updated. Looks like this now:
timerborderatimerborderb

**Comment by Mailaender** [comment]
:+1:

**Comment by GraionDilach** [comment]
#7592 is the old ticket.

**Comment by GraionDilach** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/21c58070b3bc243e8491afe544e2a293ef1e0e72...bb26ca1c938b09fe798abe430904863e4bbbd1db)

**Pull request merged**
