### PR TITLE
Truncate SoundDevice label at the UI level.

### LINKED ISSUE #5723: Audio Device info to short
Look at my options in the picture do you know what they are?
openra game_2014_06_23_10_09_29_346

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2776881-audio-device-info-to-short?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
For consistency with the rest of our UI code. Closes #5723.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: Although my sound device isn't large enough to test this properly.

**Comment by pchote** [comment]
Closes #5723.

**Comment by RoosterDragon** [comment]
:+1:

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/b120191e6a0ae56871ac90bdad6c27117cb3bf3e)

**Pull request merged**
