### PR TITLE
Always use noget in fetch-thirdparty-deps-windows.sh

### PR DESCRIPTION
**Pull request by phrohdoh**
This is #13912 but for Windows builds.

### CODE REVIEW

**Comment by pchote** [comment]
This is wanted for the mod sdk, so adding to the milestone.

**Review by Mailaender — APPROVED** [review]
Not sure what the problem with nuget is exactly, but we don't really need the dependency management plus can't use it for noget.sh compatibility anyway. The certificate checks are also more hassle and I assume problems outweigh the potential security win.

**Review by reaperrr — APPROVED** [review]
Dependency fetching still works under Windows (7).

**Comment by reaperrr** [comment]
ffed6c0

https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/04b8887b703daf31a2512edfe308cf61ee2a4169...3c394278f76373448487b8db7665f6071fe63b85

**Pull request merged**
