### PR TITLE
Modify preset colors to not get flagged by color validator

### LINKED ISSUE #17874: The color validator prevents picking some preset colors
image
Top-left (pink) and bottom-right (black) colors are on the palette, but can't be picked. Both "could not be adjusted enough".

image
The color highlighted above can be picked, but is *slightly* adjusted into allowed range. Black can't be picked.

For the sake of testing, D2K situation is the same as RA.

Another observation is that if a color was automatically readjusted, it gets randomized next time the map is changed.

### PR DESCRIPTION
**Pull request by netnazgul**
Fixes #17874 

Cheap solution to tweak color values into allowed range.

### CODE REVIEW

**Comment by pchote** [comment]
There are unfortunately still colour conflicts in TD:
* Updated black on Temperate, Winter tilesets

and RA:
* Updated black on Temperate tileset

and TS:
* Updated black on Snow tileset

All other preset/tileset combinations work fine.

**Comment by netnazgul** [comment]
Updated

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]
Lgtm.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/435481db91474390e2a485d15a57fc0e93dfb679...d5ae830bf09f91cd161a9ee0ef867a60c5fca5cd)

https://github.com/OpenRA/OpenRA/commit/5cacce3c939a4dd08139024c1c0b0fea1351c6ab

**Pull request merged**
