### PR TITLE
Filter the lua PlayerProperties on Requires

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes https://github.com/OpenRA/OpenRA/pull/11474#discussion_r70184465.

All missions should work again~~, except allies01 (the testcase)~~.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by GraionDilach** [comment]
:+1:

**Comment by abcdefg30** [comment]
Removed the testcase.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0fe93a0a662889f12858009b1aa9a69328808207)

**Pull request merged**
