### PR TITLE
Polish the windows make and launcher scripts

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes issues discovered during the writing/review of https://github.com/OpenRA/OpenRAModTemplate/pull/3.

### CODE REVIEW

**Comment by reaperrr** [comment]
Seems to need a rebase.

**Comment by abcdefg30** [comment]
Weird, this was already based on latest bleed. I recommited my changes, hopefully that resolves the issue.

**Review by pchote — APPROVED** [review]
Works as advertised.  Just one nit: you have a typo in the second commit message ("commad").

I want this before the playtest for consistency with the mod template, so adding to the milestone.

**Comment by abcdefg30** [comment]
Fixed.

**Review by reaperrr — APPROVED** [review]
Can't judge the script changes of 3rd and 5th commit, but they all seem to do what the commit titles suggests.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/09ac6d2fc8c84f7bd7c1a2304fd3e390a04784a3...21b117513d70bb6eca2cb5919a7104b12143f7b5

**Pull request merged**
