### PR TITLE
Fix potentially removing actors twice from world in Actor::ChangeOwner

### LINKED ISSUE #8262: Dune2k crash [playtest-20150524]: KeyNotFoundException
Dune2k mod playtest-20150524 just crashed after an hour of playing in single player on Ubuntu 15.04. I am new here so I do not know what debug data I should provide. Exception.log reads:

> Dune 2000 Mod at Version playtest-20150524
> Operating System: Linux (Unix 4.1.0.40100)
> Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4) CLR 4.0.30319.17020
> Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
>  at System.Collections.Generic.Dictionary`2[OpenRA.Actor,System.Drawing.Rectangle].get_Item (OpenRA.Actor key) [0x00000] in <filename unknown>:0
>  at OpenRA.Primitives.SpatiallyPartitioned`1[OpenRA.Actor].Remove (OpenRA.Actor item) [0x00000] in <filename unknown>:0
>  at OpenRA.Traits.ScreenMap.Remove (OpenRA.Actor a) [0x00000] in <filename unknown>:0
>  at OpenRA.Mods.Common.Traits.Mobile.RemovedFromWorld (OpenRA.Actor self) [0x00000] in <filename unknown>:0
>  at OpenRA.World.Remove (OpenRA.Actor a) [0x00000] in <filename unknown>:0
>  at OpenRA.Actor+<ChangeOwner>c__AnonStorey1.<>m__0 (OpenRA.World w) [0x00000] in <filename unknown>:0
>  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0
>  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0
>  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0
>  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17669570-dune2k-crash-playtest-20150524-keynotfoundexception?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #8262

### CODE REVIEW

**Comment by pchote** [comment]
This looks like the best way to solve that problem, but I haven't confirmed whether it fixes the problem so :+0.5:.

**Comment by abcdefg30** [comment]
Fixes the crash. :+1: / :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/462ae678208350ba85aca2b77a417e0cf4d19510...de47f3662bfacdf7a9a0c108ec42a22649508351)

**Comment by Mailaender** [comment]
Thanks!

**Comment by Mailaender** [comment]
Also successfully updated https://github.com/OpenRA/OpenRA/tree/prep-1505

**Pull request merged**
