### PR TITLE
Fixed D2k trails and deviator explosion color

### PR DESCRIPTION
**Pull request by reaperrr**
Uses the correct trail animations for D2k missiles.
Removes contrails.
Makes explosion and trail of Deviator weapon player-colored.

Fixes points 1-3 of #7689.

Requires #7639.

### CODE REVIEW

**Comment by reaperrr** [comment]
Only the last 3 commits count, the rest is from #7639.

**Comment by Mailaender** [comment]
:+1: Works as promised in Dune 2000. The bazooka and missile quad trails could need a bit more transparency, but I think you already know about that.

**Comment by penev92** [comment]
No more dependencies, but needs a rebase now.

**Comment by reaperrr** [comment]
Adressed the issue @Mailaender pointed out and rebased.

**Comment by obrakmann** [comment]
These do look nice. Bonus points for removing the hard-coded palette. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/26853511df1356fc454f7039de651b0fca6ff808%5E...26853511df1356fc454f7039de651b0fca6ff808)

**Comment by Mailaender** [comment]
Wow, this looks great with the proper blend mode.

**Pull request merged**
