### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by bryanwilbur**

### CODE REVIEW

**Comment by penev92** [comment]
Hello? This is an unusual PR.
Do we know each other? The name doesn't look familiar, but you'll have to give some nickname that one of the devs is familiar with before we can take this PR. We can't let anyone be in AUTHORS.

**Comment by bryanwilbur** [comment]
Hi,

I apologize, I am a fan of Red Alert and was interested in contributing to OpenRA.  I was using Code Triage and was working on one of the open issues.  On the OpenRA github page, one of the steps listed for contributing is "Don't forget to add youself to AUTHORS".  I'm sorry if I was mistaken on that.


I submitted a solution to issue #3318.


Thank You,


Bryan Wilbur

---- On Mon, 29 Jun 2015 12:56:49 -0600 Pavel Penev &lt;notifications@github.com&gt; wrote ---- 

Hello? This is an unusual PR.
 Do we know each other? The name doesn't look familiar, but you'll have to give some nickname that one of the devs is familiar with before we can take this PR. We can't let anyone be in AUTHORS.
 —
Reply to this email directly or view it on GitHub.
    
 
 





​

**Comment by GraionDilach** [comment]
No problem, if you really intend to give the project a helping hand, you're more than welcome in the OpenRA IRC at #openra on irc.freenode.net where you can discuss any issues/codenits/whatever you'd come up with/like to know, either OpenRa or git or related.

It's just the order of your PRs were unlucky to say. But it's all okay now.

**Comment by pchote** [comment]
Superseded by #8777.

**Pull request closed without merging**
