### PR TITLE
Fixed a crash in color picker logic when using the in-game editor

### LINKED ISSUE #8341: Trying to change player color in editor causes CTD
Crash to desktop via fatal error if the player color is clicked in settings, while in the ingame editor.

Steps to reproduce:
-Open the ingame map editor
-Navigate to settings
-Try to change player color

Contents of exception.log: 

```
Red Alert Mod at Version playtest-20150531
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Reflection.TargetInvocationException`: Het doel van een aanroep heeft een uitzondering veroorzaakt.
Inner Exception of type `System.NullReferenceException`: De objectverwijzing is niet op een exemplaar van een object ingesteld.
     bij OpenRA.OwnerInit..ctor(Player player)
   bij OpenRA.Mods.Common.Widgets.Logic.ColorPickerLogic..ctor(Widget widget, World world, HSLColor initialColor, Action`1 onChange, WorldRenderer worldRenderer)
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args)
   bij OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   bij OpenRA.Widgets.Widget.<PostInit>c__AnonStorey0.<>m__0(String l)
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij OpenRA.Widgets.Widget.PostInit(WidgetArgs args)
   bij OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node)
   bij OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w)
   bij OpenRA.Game.LoadWidget(World world, String id, Widget parent, WidgetArgs args)
   bij OpenRA.Mods.Common.Widgets.Logic.ColorPickerLogic.ShowColorDropDown(DropDownButtonWidget color, ColorPreviewManagerWidget preview, World world)
   bij OpenRA.Mods.Common.Widgets.Logic.SettingsLogic.<InitDisplayPanel>c__AnonStorey5.<>m__D(MouseInput _)
   bij OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   bij OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bij OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bij OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bij OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bij OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   bij OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
   bij OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bij OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   bij OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler)
   bij OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
   bij OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler)
   bij OpenRA.Game.RenderTick()
   bij OpenRA.Game.Loop()
   bij OpenRA.Game.Run()
   bij OpenRA.Program.Run(String[] args)
   bij OpenRA.Program.Main(String[] args)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/19282286-trying-to-change-player-color-in-editor-causes-ctd?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes #8341

### CODE REVIEW

**Comment by LipkeGu** [comment]
these are the underlaying fixes of #8342

**Comment by obrakmann** [comment]
Tested after reverting #8342, this fixes the original problem.

This isn't strictly needed anymore after #8342, but it's probably more correct to take it. :+1:

**Comment by penev92** [comment]
Yup, this fixes it. :+1: Thanks!
I would rather see the `for/if` as
```
var worldOwner = Players.Players.Select(kvp => kvp.Value).First(p => !p.Playable && p.OwnsWorld);
w.WorldActor.Owner = new Player(w, null, null, worldOwner);
```
though (unless there are objections to that). I personally find it simpler.

**Comment by Mailaender** [comment]
That probably needs a FirstOrDefault and null check again.

**Comment by penev92** [comment]
Not having such a player (non-playable and owning the world) means your map is broken. Running the linter will tell you that (I believe it was you who added such a lint rule not too long ago?).

**Comment by Mailaender** [comment]
The line I added is mostly copy pasta from https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/World/CreateMPPlayers.cs btw.

**Comment by penev92** [comment]
I believe this is where I say that one can be simplified to the same 2 lines I posted above. (It is 4-year-old code, so no wonder it doesn't really measure up to our current standards.)
But then again, I see no point in arguing over something so simple.
On the other hand, on the off chance that someone does indeed screw up their YAML sufficiently, your fix won't kick in and we're back to the same crash.
Although the way to crash (color picker) is now disabled, so...
But in the end, this violates the braces style rule, and fixes the problem, but leaves a tiny whole through which it can resurface.
My suggestion is to let it crash, but here, so it is very easy to determine what went wrong by only using the stack trace, or using the utility with `--check-yaml` to tell you.

Wow, I really wanted to merge it and be done with it without more arguing. Guess I couldn't.

**Comment by Mailaender** [comment]
Updated to use LINQ only. I also thought about closing and deleting this, but https://github.com/OpenRA/OpenRA/issues/8342 only hides the problem. There may be other occasions where other code queries the world actor.

**Comment by penev92** [comment]
Thanks. The fact that something else might want to use the world owner and then crash in any number of unexpected ways on incorrectly set up maps is why I couldn't bring myself to merge it.

**Pull request merged**
