### PR TITLE
Fix mod updater and clear out legacy rules.

### LINKED ISSUE #10793: Upgrade mod is broken
Probably a regression from all those https://github.com/OpenRA/OpenRA/issues/10717 related refactors.

```
Processing Rules:
	ra2|rules/proxy-actors.yaml
Error: Utility application crashed. See utility.log for details

Unhandled Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/matthias/Entwicklung/OpenRA/ra2|rules/proxy-actors.yaml".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x001c6] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/FileStream.cs:233 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, System.String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/FileStream.cs:152 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost) [0x00065] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:255 
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:236 
  at System.IO.StreamReader..ctor (System.String path, Boolean detectEncodingFromByteOrderMarks) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:207 
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:184 
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
  at System.IO.File.OpenText (System.String path) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/File.cs:346 
  at System.IO.File.ReadAllLines (System.String path) <0x7ff4aeba2d10 + 0x00020> in <filename unknown>:0 
  at OpenRA.MiniYaml.FromFile (System.String path) [0x00002] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/MiniYaml.cs:244 
  at OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.Run (OpenRA.ModData modData, System.String[] args) <0x412a3880 + 0x00193> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Utility/Program.cs:83 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/matthias/Entwicklung/OpenRA/ra2|rules/proxy-actors.yaml".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x001c6] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/FileStream.cs:233 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, System.String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/FileStream.cs:152 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost) [0x00065] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:255 
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:236 
  at System.IO.StreamReader..ctor (System.String path, Boolean detectEncodingFromByteOrderMarks) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:207 
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/external/referencesource/mscorlib/system/io/streamreader.cs:184 
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
  at System.IO.File.OpenText (System.String path) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.2.2/mcs/class/corlib/System.IO/File.cs:346 
  at System.IO.File.ReadAllLines (System.String path) <0x7ff4aeba2d10 + 0x00020> in <filename unknown>:0 
  at OpenRA.MiniYaml.FromFile (System.String path) [0x00002] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/MiniYaml.cs:244 
  at OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.Run (OpenRA.ModData modData, System.String[] args) <0x412a3880 + 0x00193> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Utility/Program.cs:83
```

### PR DESCRIPTION
**Pull request by pchote**
Fixes #10793 and applies some desperately needed dejunking by removing all upgrade rules earlier than the last release.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: 

BTW, I just noticed during testing that updating old maps isn't working as it should, the map version update doesn't seem to stick:

```
Converted bombardment-islands-2.oramap to MapFormat 8.
Error: Utility application crashed. See utility.log for details

Unhandled Exception:
System.IO.InvalidDataException: Map format 7 is not supported.
 File: bombardment-islands-2.oramap
  at OpenRA.Map..ctor (System.String path) <0x40983a30 + 0x0126b> in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.Run (OpenRA.ModData modData, System.String[] args) <0x40977dc0 + 0x000df> in <filename unknown>:0 
```

**Comment by obrakmann** [comment]
Submitted https://github.com/pchote/OpenRA/pull/13 for the broken map format upgrader.

**Comment by pchote** [comment]
Updated.

**Comment by obrakmann** [comment]
Needs a rebase now

**Comment by pchote** [comment]
Rebased.

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/146d848ce8310f57a9b4ddc28304dcc8ac8bfe0c...60b2dc6710d66fe4cfba6233b85b9ce03511f0bb)

**Pull request merged**
