### PR TITLE
Fix Creeps not considering players as enemies on some TD maps

### LINKED ISSUE #11056: TD Visceroids
In TD playtest version 20160403 Visceroids don't attack anything when spawned from Chem Troopers. (Currently untested if it is spawned via map.)

Shown in replay example at 9:20 and onward.

https://www.dropbox.com/s/n46hvd1ag7a5hkx/OpenRA-2016-04-05T194601Z.orarep?dl=0

### PR DESCRIPTION
**Pull request by reaperrr**
Set Multi\* players as enemies for Creeps where this wasn't the case.

Closes #11056.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: 

I think this might be some fallout from #10127, if those maps were created using the buggy version.

**Comment by pchote** [comment]
Llamas 2 also needs a fix.

**Comment by pchote** [comment]
Also the following RA maps:

Alaska Anarchy Redux
Barracuda
Behind The Veil
Bloody Delta
Cold Front
Engagement
Mad Science
Sunstroke
Tabula Rasa
Warwind
Bomber John (maybe just remove Creeps here)
Drop Zone (ditto)
Drop Zone - Battle of Tikiaki (ditto)
02b: The thin red line (ditto)
03:   Covert cleanup (ditto)
04a: Behind the lines (ditto)
04b: Behind the lines (ditto)
05:   Distant Thunder (ditto)
06a: Bridge over the River Grotzny (ditto)
06b: Bridge over the River VizchGoi (ditto)
07:   Core of the matter (ditto)
Training camp (ditto)

**Comment by pchote** [comment]
You can verify for yourself by adding the following code to one of the `ILintMapPass` implementations:
```csharp
var players = new MapPlayers(map.PlayerDefinitions);
if (players.Players.ContainsKey("Creeps"))
{
	var creeps = players.Players["Creeps"];
	if (players.Players.Any(p => p.Value.Playable && (!creeps.Enemies.Contains(p.Key) || !p.Value.Enemies.Contains("Creeps"))))
		emitError("Map has bogus creeps definition");
}
```

**Comment by reaperrr** [comment]
I'm not sure about Bomber John, that setup might be intentional?

**Comment by abcdefg30** [comment]
Bomber John has actually some flame towers owned by `Creeps` (-> no removal please).
However, `Enemies: Creeps` on the `Creeps` player is totally bogus and I think that should be fixed.
IIRC some releases ago those flame towers shot at you, which they aren't now anymore (obviously).

**Comment by reaperrr** [comment]
Updated.

**Comment by pchote** [comment]
All mods now pass my lint tests, so my :+1: still stands.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fd42b7a19b400944b25e49235772770d11818528

**Pull request merged**
