### PR TITLE
 Fix conditional traits that incorrectly override INotifyCreated.

### PR DESCRIPTION
**Pull request by pchote**
This also adds a check command to make sure these errors can't happen again.

### CODE REVIEW

**Comment by reaperrr** [comment]
I locally reverted only the `DetectCloaked` check to test the lint rule, but it returns 214(!) violations for me...

**Comment by pchote** [comment]
Can you paste some of the output it gives? It works correctly for me and travis, so this may be a windows-specific issue.

**Comment by reaperrr** [comment]
error1

I guess it just says that for every trait implementing ConditionalTrait.

**Comment by pchote** [comment]
It seems that the default behaviour wrt `BindingFlags.DeclaredOnly` is different between mono and .NET. Fixed.

**Review by reaperrr — APPROVED** [review]

**Review by teinarss — APPROVED** [review]
Looks good tested the check command.

**Comment by teinarss** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/fcecc67602ad93157b9138d71552258d67600cd9...bc33f3bcf94fcdc8ced7dfac37d37d9aaa00b144

**Pull request merged**
