### PR TITLE
Fix sprite turret recoil.

### LINKED ISSUE #9587: Recoil:  isnt working anymore
i really miss moving turrets while firing with tanks..

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27315557-recoil-isnt-working-anymore?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9587.

### CODE REVIEW

**Comment by obrakmann** [comment]
This fixes it for tanks and ships. But didn't the gun turret also have recoil?

**Comment by Mailaender** [comment]
The RA and TD can't have recoil, because the artwork is just one SHP and the D2k gun turret does not have it set up in the Armament so I think the issue is resolved in general here.

**Comment by Mailaender** [comment]
Thanks for investigating this. Another reason for something like https://github.com/OpenRA/OpenRA/issues/8584.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d78cef09b26889be39fb63508d15e85e691426bc...38d529f50cacc39fc61eec21797ad7f5e8d1fccc)

**Pull request merged**
