### PR TITLE
Sync only once per tick

### PR DESCRIPTION
**Pull request by RoosterDragon**
This greatly improves performance by not syncing the world state for every single order processed as this becomes very expensive, at the cost of being unable to directly pinpoint the order that causes a desync. Instead the granularity of detecting desyncs is reduced to the tick level.

As noted in https://github.com/OpenRA/OpenRA/issues/9008#issuecomment-129202470, in the worst case scenario of running a max speed replay with high orders rates (due to many players, particularly AI in this case), this could represent upto 50% of CPU!

Only syncing once per tick will benefit tick times when:
- Overall orders rates are high (e.g. due to many players or players with high APM (such as AI))
- An order is given to large groups of units (this should reduce the lag spike significantly)

The disadvantage is that in the event of a desync we won't know what specific order caused it, instead we will only know the frame the desync occurred in. This is hopefully a worthwhile tradeoff.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Please dump a list of orders given in the desync frame so we have some sort of information to go off of.

**Comment by Mailaender** [comment]
This still desyncs properly when watching old replays. :white_check_mark: I am also okay with the trait off. Regarding desync hunting the blame tick was never important to me. I am not sure how this will look like with a real desync.log as a more diverged world state with lot's of diffs might make root-cause analysis more difficult, but this is just speculation. I still favor this trade-off towards performance. We should give it a try. :+1:

**Comment by pchote** [comment]
This will definitely need some test games  (preferrably with some intentionally introduced desyncs) to explore the effect it has on real games.

**Comment by RoosterDragon** [comment]
Orders issued in the out of sync frame will now also be added to the sync report.

**Comment by chrisforbes** [comment]
99% of the desyncs I've looked at have been in Tick, so this seems OK to me.

**Comment by reaperrr** [comment]
Even ordering ~400 infantry around repeatedly is now still playable (unlike before), with this change we're now almost purely pathfinder-bottlenecked when issuing move/attack orders to large numbers of actors.
Singleplayer ingame gets my :+1: , but let's wait for additional feedback on multiplayer/desync behavior before merging this.

**Comment by Mailaender** [comment]
I changed HoverMissile inaccuracy and it still pretty much instantly desynced properly: https://gist.github.com/Mailaender/a1d3e9e6abb2ecf53f8e/revisions

**Comment by Mailaender** [comment]
I changed Transforms.cs to provoke an order related desync:

```patch
@@ -73,7 +73,7 @@ public string VoicePhraseForOrder(Actor self, Order order)
 		bool CanDeploy()
 		{
 			var building = self.TraitOrDefault<Building>();
-			if (building != null && building.Locked)
+			if (building == null)
 				return false;
 
 			return buildingInfo == null || self.World.CanPlaceBuilding(info.IntoActor, buildingInfo, self.Location + info.Offset, self);
```

Result looks okay: https://gist.github.com/Mailaender/7451de1c6d4187f4d49d/revisions

**Comment by Mailaender** [comment]
For comparison: https://gist.github.com/Mailaender/c9ea8ec6ef85197defdc/revisions without those changes on current bleed.

**Comment by Mailaender** [comment]
```patch
@@ -137,7 +137,10 @@ public void DeployTransform(bool queued)
 		public void ResolveOrder(Actor self, Order order)
 		{
 			if (order.OrderString == "DeployTransform")
+			{
+				System.Console.WriteLine(self.World.SharedRandom.Next());
 				DeployTransform(order.Queued);
+			}
 		}
 	}
 }
```

created:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Out of sync in frame 4.
 OrderString: "DeployTransform" 
	 Subject: "mcv 45". 
	 TargetActor: "" 
	 TargetLocation: 0,0.
	 TargetString: "".
	 IsImmediate: False.
	 Player(PlayerName): abcdefg30
```

https://gist.github.com/Mailaender/e440c3485ebbf5789a6e/revisions on bleed.

**Comment by Mailaender** [comment]
Which becomes https://gist.github.com/Mailaender/0956817999c1c5d622f7/revisions on this branch, but only due to https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/WorldCommandWidget.cs#L134

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6094c3120b9dc7e1664c7aeb0aebcecf2bcc01be...5dd08158d19c77ccb0703e4677aa593240b05cfa)

**Comment by GraionDilach** [comment]
Note to changelog: this affects single player as well, not just network from what I noticed.

**Comment by penev92** [comment]
Yeah, I did test @reaperrr's comment myself, with ~350 infantry:
>Even ordering ~400 infantry around repeatedly is now still playable (unlike before)

Just issuing the orders in single player, there is still a huge difference.

**Comment by Mailaender** [comment]
[Revised changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/263729c227af442822b2b08286f91369d5ec60d7...82edd49b510786fedfbc7c7c4ccc01bbd41caa4e).

**Pull request merged**
