### PR TITLE
Made RA tent art tileset-specific again

### PR DESCRIPTION
**Pull request by reaperrr**
Additionally fixed the desert wall palette in the editor by removing now-redundant `.des` versions of all walls (no visual difference to generic .shp versions, so we're not losing anything).

Minor follow-up of #7741.

### CODE REVIEW

**Comment by Mailaender** [comment]
Wait a moment. `tent.tem` and `tentmake.tem` are actually duplicates of `tent.shp` and `tentmake.shp`. I suggest to define

```yaml
TilesetExtensions:
	GENERIC: .shp
```

in `mod.yaml` and use

```yaml
 tent:
	Defaults:
		UseTilesetExtension: true
		TilesetOverrides:
			TEMPERAT: GENERIC
			INTERIOR: GENERIC
```

to resolve this.

**Comment by reaperrr** [comment]
@pchote said on irc yesterday that such an approach would be a little too hacky for his taste, and considering we're talking about a single structure, I'm inclined to agree.

**Comment by reaperrr** [comment]
Updated, removed now-redundant *.des shps of the walls.

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1: Checked out the tent in desert, temperate and snow terrain, as well as in the editor. All show the tileset-specific variants, and the walls aren't blue anymore either.

**Pull request merged**
