### PR TITLE
[RA] Add map Agenda and alter Great Sahara 2

### PR DESCRIPTION
**Pull request by SoScared**
The overall playerbase could use a demonstration with the new active civilian structures.

**Agenda** spearheading the last two playtest series would be an excellent map to demonstrate the use and effectiveness of the new civilian structures.

**Great Sahara 2** would be a team map equivalent (8 players). Reason for this pick is the unexpected popularity this map got among the team playtest maps and direct feedback from players regarding the civilian structures on this particular map.

Origins:
Agenda v1.6b: http://resource.openra.net/maps/21582/
Great Sahara 2 v1.6b: http://resource.openra.net/maps/21433/

Both maps with this PR uploaded to the resource center:
Agenda: http://resource.openra.net/maps/22471/
Great Sahara 2: http://resource.openra.net/maps/22470/

### CODE REVIEW

**Review by ltem — APPROVED** [review]
maps are fine and good reasoning to add them :)

**Comment by SoScared** [comment]
Also for future reference, making civilian structure more visible in the map preview would be a great advantage for general map awareness: https://github.com/OpenRA/OpenRA/issues/13823

**Comment by reaperrr** [comment]
Those 'active' civilian structures are already merged into stable, so I think this PR should go into next playtest to give them a bit more exposure.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
4496cff

https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a61ad019150f0481a403c5b95c6c0abc78d86158...211799edb99449dee5ddb0b8d4c47605ded2594a

**Pull request merged**
