### PR TITLE
Fix global-bounty warnings

### LINKED ISSUE #14587: global-bonty warnings on two RA missions.
I must have missed these in the original PR.  These are still using `-GivesBounty` instead of disabling the map option.

```
Testing map: 03:   Covert cleanup
OpenRA.Utility(1,1): Warning: Actor type `dog` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e1r1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e2` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e3` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e3r1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e4` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e6` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `spy` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `spy.england` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e7` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `medi` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `mech` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `einstein` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `delphi` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `chan` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `gnrl` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `thf` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `hijacker` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `shok` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `sniper` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `zombie` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `ant` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c2` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c3` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c4` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c5` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c6` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c7` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c8` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c9` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c10` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `tecn` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `tran` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `heli` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `hind` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `ss` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `msub` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `dd` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `ca` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `lst` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `pt` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e7.noautotarget` grants conditions that are not consumed: global-bounty
```
```
Testing map: 07:   Core of the matter
OpenRA.Utility(1,1): Warning: Actor type `dog` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e1r1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e2` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e3` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e3r1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e4` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e6` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `spy` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `spy.england` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e7` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `medi` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `mech` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `einstein` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `delphi` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `chan` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `gnrl` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `thf` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `hijacker` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `shok` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `sniper` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `zombie` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `ant` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c1` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c2` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c3` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c4` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c5` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c6` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c7` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c8` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c9` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `c10` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `tecn` grants conditions that are not consumed: global-bounty
OpenRA.Utility(1,1): Warning: Actor type `e7.noautotarget` grants conditions that are not consumed: global-bounty
```

### PR DESCRIPTION
**Pull request by Arular101**
Fixes #14587.

### CODE REVIEW

**Review by pchote — CHANGES_REQUESTED** [review]
Can you please instead change and lock the lobby option and remove the overrides? (see d24d80f483ea10261c0588b3f6be1e6a417c3f8a)

**Comment by Arular101** [comment]
Updated.

Should this also be changed for the [desert-shellmap](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/desert-shellmap/rules.yaml#L24), or not needed?

**Comment by pchote** [comment]
Yes, please.

**Comment by Arular101** [comment]
Done

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/605533e64ae9a4fa0e663e7a819051572a2d3207

**Pull request merged**
