### PR TITLE
Prompt FMV installation when trying to play a missing video.

### PR DESCRIPTION
**Pull request by pchote**
This adds multi-line support and reduces duplication in our dialog prompts, and then uses this to display an information dialog when trying to play a video that isn't installed.

### CODE REVIEW

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by abcdefg30** [comment]
Looks good to me as well. 👍

**Comment by abcdefg30** [comment]
Can't add a changelog at the moment as github doesn't allow me to edit the page for some reason.
Will have another try later (if noone else has done it until then).

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/04aa7b4bd4cbb4d7225635fa389d82752cb25278)

**Comment by abcdefg30** [comment]
Ah thanks.

**Pull request merged**
