### PR TITLE
Fix the length of the idle2 sequence of tanya

### PR DESCRIPTION
**Pull request by abcdefg30**
Had a wrong frame in the end (tanya held her hands up 🙌 ):
tanyaidle

### CODE REVIEW

**Comment by jaZzKCS** [comment]
"...and wave 'em like you just don't care!"

**Comment by Mailaender** [comment]
Well spotted. :+1: It runs so fast that no one really noticed the glitch all those years.

**Comment by HenrytheSlav** [comment]
:+1: Nice catch.

**Comment by abcdefg30** [comment]
Btw, the credits for spotting this go to my brother. ;)

**Pull request merged**
