### PR TITLE
Work around incorrect mono drive detection under OSX.

### LINKED ISSUE #12002: First Decade DVD not detected (On OSX at least)
I assume it works on Windows.  
I am using a bleed build I put together from src 20 min ago as of typing.

Maybe this would help:
The path to reach the DVD on OSX is:
"/Volumes/CNCTFD"

I wish I could try other CDs  but the only other copy of C+C I own is the Classic MacOS (7-9) version which I'm not surprised you do not support.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #12002.

### CODE REVIEW

**Comment by reaperrr** [comment]
I can't test it, but the code looks fine to me :+1:

**Comment by Phrohdoh** [comment]
We'll have to take @pchote at his word on this one, unless another macOS user comes along, because I don't have the data to test this.

**Comment by obrakmann** [comment]
@JoshuaPettus: would you be able to confirm this fix, please? The number of people we have that both use OS X and have a TFD disk is a bit on the low side.

**Comment by JoshuaPettus** [comment]
Hey, I just found out about this, I'll be sure to give it a try tomorrow!

**Comment by JoshuaPettus** [comment]
Excellent! It works!  Thanks!

**Review by obrakmann — APPROVED** [review]
Thanks @JoshuaPettus! :+1: then.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a280256a77f0520614f941a11314b74e40884d4f)

**Pull request merged**
