### PR TITLE
Fixed map tile error on "Desert Twister" map

### PR DESCRIPTION
**Pull request by DaynosaurusRex**
Weird cliff tile referenced here: #11747 has now been removed:
image

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Still doesn't look right tho. There are other tiling errors.

**Comment by daynemarais** [comment]
Right, any tips on what needs to change?

**Comment by obrakmann** [comment]
I looked over the map and found a few tiling errors. A lot of places look weird in the d2k tileset, but I think that's just how it is. I find it extremely hard to work with for that reason.

screenshot from 2016-08-10 17 54 51
screenshot from 2016-08-10 17 55 40
screenshot from 2016-08-10 17 56 06
screenshot from 2016-08-10 17 56 22

**Comment by daynemarais** [comment]
Okay, fixed the above:
image
image
image
image
image

**Comment by obrakmann** [comment]
Sorry, I noticed one more, but then it's good. Thanks for doing this!

screenshot from 2016-08-19 19 51 07

**Comment by daynemarais** [comment]
No worries!
Here's my fix:
image

**Comment by obrakmann** [comment]
Thanks, :+1:

**Comment by abcdefg30** [comment]
Looks good to me as well. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/68609d247c2d9d9d8bb40cecd31251fcb63e4ec7...a6bb03e3806d3c7b56c1fbbd1e480c2f52b713ad)

**Pull request merged**
