### PR TITLE
Automatized Coverity Scan with AppVeyor

### PR DESCRIPTION
**Pull request by Mailaender**
Note: this is not final. I just have no other way to test it than file a pull request.

### CODE REVIEW

**Comment by csMACnz** [comment]
@Mailaender just looking this over and I see two issues.

First, you are only compressing the files from the current implementation, not publishing them as well.

publish example are https://github.com/GitTools/GitReleaseManager/blob/develop/BuildScripts/default.ps1#L553 and https://github.com/csMACnz/BCLExtensions/blob/master/build.tasks.ps1#L107.

Second, the AppVeyor secure environment variables are not accessible from a PR build. This means your PR cannot actually run the publish from the secure tokens. You have to add conditional code to only run this either on schedules builds (as the two examples above do) or exclude pull requests. Since there is a daily limit to how many reports are submitted to Coverity Scan, I prefer the schedule build version.  This does make setup of Coverity tricky but I recommend using a branch to get it right.

Also, you can set up appveyor against your fork for testing. Just be aware the secure tokens will probably differ.

**Comment by Mailaender** [comment]
> Second, the AppVeyor secure environment variables are not accessible from a PR build.

That explains a lot. Thanks!

**Comment by csMACnz** [comment]
Also FYI I've been working on a fix for the 401 issues I've noticed everyone having. looks like something might have changed on their end but I think i've fixed it now. 
Latest release (0.10.0) should be publishing again.

**Comment by pchote** [comment]
What's the plan here @Mailaender?

**Comment by Mailaender** [comment]
I need to figure out AppVeyor scheduled builds work.

**Comment by csMACnz** [comment]
@Mailaender checkout: http://www.appveyor.com/docs/build-configuration#scheduled-builds

Note that it builds whatever your default branch is.
image

You use crontab timing to set the schedule. I use daily on the 0th minute on the 18th hour (UTC) every day, 
image

**Comment by Mailaender** [comment]
Automatized it as suggested. This will now build, store and published every day on 4 am once merged.

**Comment by penev92** [comment]
That sounds good.
:+1: with my quite limited understanding of the changes.

**Comment by GraionDilach** [comment]
i never really could access the logs of these Coverity scans but any change leading to a more stable code gets a :+1: from me.

**Comment by Mailaender** [comment]
Invited you to https://scan.coverity.com/projects/3650. I actually want this to be publicly available, but that doesn't seem to work.

**Comment by GraionDilach** [comment]
Thank you.

**Comment by obrakmann** [comment]
Looks good to me :+1: 

Note that the scheduled build is at 4am UTC.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/c326a9ce388f74de5d20f973708e02443d7945e3%5E...c326a9ce388f74de5d20f973708e02443d7945e3)

**Pull request merged**
