### PR TITLE
Signify next item in production queue

### PR DESCRIPTION
**Pull request by dragunoff**
This is an alternative implementation of the feature proposed in #15841

What's in the **first commit** of this PR:
* Add `NextSymbol` property to `ProductionPalleteWidget`;
* Add `NextProductionSymbolOffset` to metrics.yaml;
* Add `InfiniteProductionSymbolOffset` to metrics.yaml;
* Add `InfiniteProductionSymbolSize` to metrics.yaml;
* Add "Symbols" font definition;
* Add `IsNextInQueue` method to `ProductionQueue` trait (it returns
`false` in parallel production context);

The **second commit** is a refactor of `ProductionPaletteWidget.cs` that moves offset calculation logic from `Draw` to `Initialize`.

**Remarks**:
* The game would crash if "Symbols" font is not defined. Perhaps a fallback font should be set?
* The text flickers when priority queueing items (`Ctrl + Left Click`) and I have no idea how fix/work-around that;
* The glyph is very much up for discussion but this seemed like the most suitable one available in FreeSans font;

**Screenshots** from all default mods (including a test with `InfiniteBuildLimit` in CNC):
openra-signify-next-production-item

### CODE REVIEW

**Comment by pchote** [comment]
Did you try experimenting with underlining the queue number?

**Comment by dragunoff** [comment]
@pchote No, that didn't come to my mind. That may work but I don't know how to underline text. 

Here are some more glyph variants available in the font:
openra-hilite-next-production-item--symbols

**Comment by abcdefg30** [comment]
Would changing the colour be an option, too?

**Comment by dragunoff** [comment]
@abcdefg30 Here is a render with the yellow color used for the ready text:
openra-signify-next-production-item--color

**Comment by pchote** [comment]
> That may work but I don't know how to underline text.

Not possible directly using the text renderer, but you already know the glyph bounds so can draw it yourself using `Game.Renderer.RgbaColorRenderer`

**Comment by abcdefg30** [comment]
> @abcdefg30 Here is a render with the yellow color used for the ready text:

Imho not really readable. Do we have other colours than yellow? (Unless you want to go the underlined route now.)

**Comment by dragunoff** [comment]
Here is a mock-up of the underline variant:
openra-signify-next-production-item--underline

**Comment by pchote** [comment]
> Here is a mock-up of the underline variant

IMO this looks like a good way forward

**Comment by SoScared** [comment]
The underline looks simple and elegant 👍

**Comment by dragunoff** [comment]
I personally like the glyph and color variants better, I think the meaning of the underline is not immediately clear. Well, this all better be tested in game, so I will try to make the underline work, but that will be in a separate PR.

**Comment by abcdefg30** [comment]
I think the underline doesn't look good. FWIW, if we want to aim for "immediate clarity", a `<-` glyph would be best, although I expect players will quickly figure out the meaning of any glyph.

**Comment by pchote** [comment]
IMO the glyphs shown so far aren't any clearer than the underline or colouring.

**Comment by SoScared** [comment]
Making the <- glyph thick with the thickness of the underline mock-up could do the trick.

**Comment by dragunoff** [comment]
> Making the <- glyph thick with the *brightness of the underline mock-up could do the trick.

The bolder variant of the font has limited glyph support. I'll see what I can find there.

> I think the underline doesn't look good. FWIW, if we want to aim for "immediate clarity", a <- glyph would be best, although I expect players will quickly figure out the meaning of any glyph.

I agree here.

And some good points from Templarfreak on discord:

> Here are my thoughts on a lot of the ideas presented there. Obviously, no matter what this will end up being at least somewhat ambiguous. I think what feels least ambiguous is the best bet, and I think that is arrows / some kind of indicator to the side like the arrows and here are a few points for my reasoning: 
> 
> 1. The meaning on its own may not be super clear immediately, but people should figure it out pretty quickly as they queue things up. 
> 2. Underlining will still have that advantage, but underlining has well-established and concrete meaning and cultural significance outside ORA that doesn't really align with the usage there at all and I think this should be avoided. An arrow to the side pointing at the next in queue aligns pretty well already with what an arrow means, so it's a better subconcious indicator. 
> 3. A similar problem arises from just changing the next in queue's text's color to yellow; it already has significant meaning throughout ORA.

Another argument in favor of a glyph is that it would be easy for mods to change it and even remove it.

**Comment by pchote** [comment]
It would probably be better to use a mod-defined sprite for this and the infinite production symbol. This will bypass the limited options in the default fontset.

**Comment by dragunoff** [comment]
@pchote  I thought about using a sprite too. But I'd need to learn how to use sprites. Let's close this PR for now and I may revisit the feature.

**Pull request closed without merging**
