### PR TITLE
Make WithRangeCircle conditional

### PR DESCRIPTION
**Pull request by MustaphaTR**
Something long overdue, has been done in generals-alpha-engine long time ago.

### CODE REVIEW

**Comment by matjaeck** [comment]
This is probably better than what I did, please do the same for RenderShroudCircle so I can kill #16147.

**Comment by MustaphaTR** [comment]
Does WSC really need to be conditional? Disabling the Creates/RevealsShroud should disable the circle too already.

**Comment by matjaeck** [comment]
Not sure, I think I've tested it and it didn't but very possible that I'm wrong.

**Comment by pchote** [comment]
This doesn't seem to work. Testcase: Add `RequiresCondition: !disabled` to `NASTLH` in TS.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bee12d2971760e1eb15b2f79b67485f216e444df...9e6d7a51b37bc296f71a37fa0e1757c6abcc1944

**Pull request merged**
