### PR TITLE
Replace Travis-CI and Appveyor CI and packaging with GitHub Actions

### PR DESCRIPTION
**Pull request by pchote**
New functionality:
* Takes advantage of the improved GH UI
* CI tests (compile/code style/yaml and lua checks) are performed on Windows as well as Linux
* Faster build times

Removed functionality:
* IRC notifications (could be added, but now superseded by the improved UI?)
* Appveyor windows installer artifacts (this should wait until the net 5 update to avoid wasting effort)

The CI logs can be seen in the checks panel below or tab above.
The packaging logs can be seen at https://github.com/pchote/OpenRA/actions/runs/404196106

### CODE REVIEW

**Comment by Mailaender** [comment]
I asked @Travis-CI for extra credits regarding @OpenHV and got this response:
> At the moment, credit allocation for OSS projects is on hold as per directives from management. Sincere apologies please.

Time to move on.

**Comment by pchote** [comment]
It looks like you aren't the only one: https://twitter.com/hashtag/travisci?f=live

Oh well, all good things come to an end and it was a good run while it lasted.

**Comment by pchote** [comment]
Updated workers from ubuntu 16.04 to 20.04 to work around the missing external nsis package issue.

**Comment by pchote** [comment]
It would be better if the itch and docs deployment were changed to [manually dispatched](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) actions, so they can be decoupled and run separately from the main release packaging and if set up correction should let us deploy specific tags from bleed.

**Comment by pchote** [comment]
Updated to enable manual docs and itch deployment, and moved to the playtest milestone as rambled in #18917.

**Comment by pchote** [comment]
I'm hoping that this should be an easy review. I've now packaged several devtest releases using this, so i'm confident that the CI and Release workflows are working well. I have tested parts of the docs and itch workflows, and we can fix any issues and rerun those without needing a new tag.

The UI for trigging the docs/itch workflows looks like this:

Screenshot 2020-12-12 at 19 18 28

**Review by abcdefg30 — APPROVED** [review]

**Comment by pchote** [comment]
🤞

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/372f26a3ebb13b9a5486e92fc9a7c41f69f0ce0c

**Pull request merged**
