### PR TITLE
Add a low power overlay to fake structures

### LINKED ISSUE #8143: Fake "dome/atek/mslo/pdox" not being disabled on power down/low
makes them easy to reveal for spies

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14266827-fake-dome-atek-mslo-pdox-not-being-disabled-on-power-down-low?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #8143.
lowfakepower

### CODE REVIEW

**Comment by obrakmann** [comment]
Personally, I'm against this. These are fakes, they aren't meant to act like the real thing.

On the other hand, I see the point of it being too easy to reveal the fakes using spies. It'll also buff the french faction a bit. :+1:

**Comment by penev92** [comment]
Doesn't work over here  :?

**Comment by penev92** [comment]
Never mind, works :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/73378215a3938eb74b63c87bbd7f289681e9b5ac...6163be2506d2c3ade0fe61373dffdf2f0dc9dd45)

**Pull request merged**
