### PR TITLE
Fix enabled trait checks

### PR DESCRIPTION
**Pull request by RoosterDragon**
Fixes some bad uses of Exts.IsTraitEnabled.

Fixes some of #14445.

### CODE REVIEW

**Comment by pchote** [comment]
This doesn't seem to work, am I missing something obvious?

My testcase is:
```diff
diff --git a/mods/d2k/rules/infantry.yaml b/mods/d2k/rules/infantry.yaml
index b83312be0b..36622c31a1 100644
--- a/mods/d2k/rules/infantry.yaml
+++ b/mods/d2k/rules/infantry.yaml
@@ -98,7 +98,11 @@ thumper:
        Mobile:
                Speed: 43
                RequiresCondition: undeployed
+       GrantConditionOnTerrain:
+               Condition: enable-deploy
+               TerrainTypes: Sand, Spice, Dune, SpiceSand
        GrantConditionOnDeploy:
+               RequiresCondition: enable-deploy
                DeployedCondition: deployed
                UndeployedCondition: undeployed
                Facing: 128
```
which should disable the thumper deploy when it is not on sand.  Note that this depends on #14482 to fix the invisible thumper regression.  I plan on PRing this testcase as a polish fix once this and #14482 are merged.

**Comment by MustaphaTR** [comment]
Last time i checked GrantConditionOnDeploy wasn't conditionable.

**Comment by pchote** [comment]
Ah, Derp.  On closer inspection we don't have *any* conditional `IIssueDeployOrder` traits.

This works as expected when I make one Conditional, so :+1:

**Review by pchote — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9c4e5938c54e55f363e1710317f7ad96e04610d0...9f74c1a4b45270f22e43aa896ce9415033cf4871)

**Pull request merged**
