### PR TITLE
Move code style checking to its own executable.

### PR DESCRIPTION
**Pull request by pchote**
Depends on and followup to #13602.  This moves the code-style checks from the utility to its own dedicated executable so that we can remove the Stylecop dependency from Mods.Common.

OpenRA.StyleCheck.exe is licensed under MS-PL to resolve the issues with GPL vs MS-PL compatibility.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Could you adjust `Check-Command` in`make.ps1` similarly?

**Comment by pchote** [comment]
Good catch.  Fixed.

**Comment by pchote** [comment]
Rebased.

**Review by reaperrr — APPROVED** [review]

**Review by rob-v — APPROVED** [review]
👍, makefile not tested, but lgtm

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7f9f20aa642437a65a605f769062004bb8b3ace0...d677e7714298fdbb10ef7302d286786734ce3d5b

**Pull request merged**
