### PR TITLE
Convert Attack*.FacingTolerance to WAngle.

### LINKED ISSUE #18848: FacingTolerance still uses old calculations
Instances of FacingTolerance still use the old metric which is now inconsistent with every other facing-related value, that uses 1024 as the cap instead of 128.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #18848.

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]
Looks good to me

**Comment by pchote** [comment]
Fixed AttackPopupTurreted being listed twice in the list.

**Comment by dnqbob** [comment]
But maybe we should inform all modder on this change?

**Comment by pchote** [comment]
This is a bugfix for the already existing change, so is covered under the existing changelog and update rule entries. Modders who are updating from the last release will not need to know that these changes happened over multiple PRs.

**Review by reaperrr — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/62d57a5c066f964c38a2ae5f616b569a452d4168...ca206a36711fed3bf7abe8d3bc8a5e3606a5c291)

**Pull request merged**
