### PR TITLE
Fix cloned widgets not having default cursor set

### LINKED ISSUE #20413: Misclick through sidebar
## Issue Summary
The sidebar has holes between the category buttons where you click on the game instead of the sidebar. This means you can select a unit and when you click on the sidebar holes, you end up ordering your unit to move. This is why I misclick in OpenRA more often than in the original C&C games.

## Reproduction
Select a unit and click just between the category buttons in the sidebar.

## Expected behavior
Nothing happens

## Screenshots / Screen recordings / Replays
(Red dot is where my cursor is.)
ra-2022-10-30T182119112Z

### PR DESCRIPTION
**Pull request by PunkPun**
Fixes #20413

#18458 forgot to support cloning for the newly added variable

### CODE REVIEW

**Review by ThomasChr — APPROVED** [review]
Move cursor on the left tabs and between the images is fixed, great!

But not this one:
image
This one is no regression - but maybe we can fix it in this PR too?

**Comment by PunkPun** [comment]
> This one is no regression - but maybe we can fix it in this PR too?

This is not a related issue. The Widget.GetCursor method isn't called when you hover over that so the issue isn't with cursors

**Comment by ThomasChr** [comment]
> This is not a related issue. The Widget.GetCursor method isn't called when you hover over that so the issue isn't with cursors

Fine by me - shall we open another issue then?

**Review by Smittytron — APPROVED** [review]

**Comment by Smittytron** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/591311be8f525d1c757a36589e307485a0edc2fb)

**Pull request merged**
