### PR TITLE
MultiTapDetection, use array over dictionary.

### PR DESCRIPTION
**Pull request by anvilvapre**
MultiTapDetection used a Cache which uses a Dictionary.

The game only supports 3 mouse button presses - so only three presses at once. 

The game on Xorg does not support pressing over 3 to 4 different keyboard keys simultenously. Events seems to no longer come through. In general players will or even can't press over 6 buttons at once.

Note: 
- Hitting a modifier key like i.e. shift or ctrl will also result in a key press event. 
- Call to info happen from key up. It suggest key entries should always exist if events arrive in the correct order - we still validate to be sure.
- Is multi tap detection for keys used?

Changes:
- Store button taps in an array over dictionary.
- Store key taps in an array over dictionary. 
- Maintain only timestamp of last click - or rather when it will expire in future. 
- Main last tap event - as a quick way to know that any entry in the array is free to be used.

Benefit:
- Main: less lookup overhead, i.e. of calling Cache that will call Dictionary that will do a bounds checking, hash calculation and dictionary lookups of a byte or int - for key/botton down and up events.
- No maintenance of a dictionary of all keys once ever pressed.
- No maintenance of last three tap events - only the last is relevant. Less time and click distance comparisons.

Downside:
- Code duplication for mouse and key.

Only tested on Linux/xorg.

### CODE REVIEW

**Comment by PunkPun** [comment]
I found this PR borderline unreviewable, I've generated diffs so I or someone else could possibly review so in the future

<details>
<summary>Button diff</summary>
<br>

```diff
using System;
-using OpenRA.Primitives;
+using System.Linq;
 
 namespace OpenRA.Platforms.Default
 {
-       static class MultiTapDetection
+       readonly struct KeyTapHistory
        {
-               static readonly Cache<(Keycode Key, Modifiers Mods), TapHistory> KeyHistoryCache =
-                       new Cache<(Keycode, Modifiers), TapHistory>(_ => new TapHistory(DateTime.Now - TimeSpan.FromSeconds(1)));
-               static readonly Cache<byte, TapHistory> ClickHistoryCache =
-                       new Cache<byte, TapHistory>(_ => new TapHistory(DateTime.Now - TimeSpan.FromSeconds(1)));
+               public readonly Keycode Key;
+               public readonly byte TapCount;
+               public readonly Modifiers Modifiers;
+               public readonly DateTime LastReleaseExpireTime;
 
-               public static int DetectFromMouse(byte button, int2 xy)
+               public KeyTapHistory(Keycode key, Modifiers modifiers, DateTime expireTime, int count)
                {
-                       return ClickHistoryCache[button].GetTapCount(xy);
+                       Key = key;
+                       Modifiers = modifiers;
+                       LastReleaseExpireTime = expireTime;
+                       TapCount = (byte)count;
                }
+       }
 
-               public static int InfoFromMouse(byte button)
-               {
-                       return ClickHistoryCache[button].LastTapCount();
-               }
+       static class MultiKeyTapDetection
+       {
+               const int MaxConcurrentKeysTapped = 6;
+               const int MaxTapsPerKey = 3;
+               const int FindResultAllExpired = -1;
+               const int FindResultNotFound = -2;
 
-               public static int DetectFromKeyboard(Keycode key, Modifiers mods)
-               {
-                       return KeyHistoryCache[(key, mods)].GetTapCount(int2.Zero);
-               }
+               static readonly TimeSpan MaxDurationBetweenTaps = TimeSpan.FromMilliseconds(250);
+               static readonly KeyTapHistory[] History = Enumerable.Repeat(
+                       new KeyTapHistory(Keycode.UNKNOWN, Modifiers.None, DateTime.Now - (MaxDurationBetweenTaps * 2), 0), MaxConcurrentKeysTapped).ToArray();
+
+               static DateTime lastTapExpireTime = DateTime.Now - (MaxDurationBetweenTaps * 2);
 
-               public static int InfoFromKeyboard(Keycode key, Modifiers mods)
+               static int Find(Keycode key, DateTime now)
                {
-                       return KeyHistoryCache[(key, mods)].LastTapCount();
-               }
-       }
+                       // No recent taps.
+                       if (now > lastTapExpireTime)
+                               return FindResultAllExpired;
 
-       class TapHistory
-       {
-               public (DateTime Time, int2 Location) FirstRelease, SecondRelease, ThirdRelease;
+                       for (var i = 0; i < MaxConcurrentKeysTapped; i++)
+                               if (History[i].Key == key)
+                                       return i;
 
-               public TapHistory(DateTime now)
-               {
-                       FirstRelease = SecondRelease = ThirdRelease = (now, int2.Zero);
+                       return FindResultNotFound;
                }
 
-               static bool CloseEnough((DateTime Time, int2 Location) a, (DateTime Time, int2 Location) b)
+               static int FindUpdateIndex(DateTime now)
                {
-                       return a.Time - b.Time < TimeSpan.FromMilliseconds(250)
-                               && (a.Location - b.Location).Length < 4;
+                       // First expired or otherwise oldest.
+                       var minTime = History[0].LastReleaseExpireTime;
+                       var index = 0;
+                       for (var i = 1; i < MaxConcurrentKeysTapped && minTime >= now; i++)
+                       {
+                               ref var el = ref History[i];
+                               if (el.LastReleaseExpireTime < minTime)
+                               {
+                                       minTime = el.LastReleaseExpireTime;
+                                       index = i;
+                               }
+                       }
+
+                       return index;
                }
 
-               public int GetTapCount(int2 xy)
+               public static int Detect(Keycode key, Modifiers mods)
                {
-                       FirstRelease = SecondRelease;
-                       SecondRelease = ThirdRelease;
-                       ThirdRelease = (DateTime.Now, xy);
-
-                       if (!CloseEnough(ThirdRelease, SecondRelease))
-                               return 1;
-                       if (!CloseEnough(SecondRelease, FirstRelease))
-                               return 2;
+                       var now = DateTime.Now;
+                       var count = 0;
+                       var index = Find(key, now);
+                       if (index >= 0)
+                       {
+                               // Detects multi taps when both key and modifiers are equal across taps.
+                               ref var el = ref History[index];
+                               if (el.Modifiers == mods && now <= el.LastReleaseExpireTime)
+                                       count = (int)el.TapCount;
+                       }
+                       else if (index == FindResultAllExpired)
+                               index = 0;
+                       else
+                               index = FindUpdateIndex(now);
 
-                       return 3;
+                       lastTapExpireTime = now + MaxDurationBetweenTaps;
+                       History[index] = new KeyTapHistory(key, mods, lastTapExpireTime, count < MaxTapsPerKey ? ++count : count);
+                       return count;
                }
 
-               public int LastTapCount()
+               public static int Info(Keycode key, Modifiers mods)
                {
-                       if (!CloseEnough(ThirdRelease, SecondRelease))
-                               return 1;
-                       if (!CloseEnough(SecondRelease, FirstRelease))
-                               return 2;
+                       var now = DateTime.Now;
+                       var index = Find(key, now);
+                       if (index < 0)
+                               return 0;
 
-                       return 3;
+                       ref var el = ref History[index];
+                       return (el.Modifiers == mods && now <= el.LastReleaseExpireTime) ? el.TapCount : 0;
                }
        }
 }
```

</details>
<details>
<summary>Mouse diff</summary>
<br>

```diff
 using System;
-using OpenRA.Primitives;
+using System.Linq;
 
 namespace OpenRA.Platforms.Default
 {
-       static class MultiTapDetection
+       readonly struct MouseTapHistory
        {
-               static readonly Cache<(Keycode Key, Modifiers Mods), TapHistory> KeyHistoryCache =
-                       new Cache<(Keycode, Modifiers), TapHistory>(_ => new TapHistory(DateTime.Now - TimeSpan.FromSeconds(1)));
-               static readonly Cache<byte, TapHistory> ClickHistoryCache =
-                       new Cache<byte, TapHistory>(_ => new TapHistory(DateTime.Now - TimeSpan.FromSeconds(1)));
+               public readonly byte Button;
+               public readonly byte TapCount;
+               public readonly int2 LastLocation;
+               public readonly DateTime LastReleaseExpireTime;
 
-               public static int DetectFromMouse(byte button, int2 xy)
+               public MouseTapHistory(byte button, int2 lastLocation, DateTime expireTime, int count)
                {
-                       return ClickHistoryCache[button].GetTapCount(xy);
+                       Button = button;
+                       LastLocation = lastLocation;
+                       LastReleaseExpireTime = expireTime;
+                       TapCount = (byte)count;
                }
+       }
 
-               public static int InfoFromMouse(byte button)
-               {
-                       return ClickHistoryCache[button].LastTapCount();
-               }
+       static class MultiMouseTapDetection
+       {
+               const int MaxConcurrentButtonsTapped = 3;
+               const int MaxTapsPerButton = 3;
+               const int MaxLocationDistance = 4;
+               const int FindResultAllExpired = -1;
+               const int FindResultNotFound = -2;
 
-               public static int DetectFromKeyboard(Keycode key, Modifiers mods)
-               {
-                       return KeyHistoryCache[(key, mods)].GetTapCount(int2.Zero);
-               }
+               static readonly TimeSpan MaxDurationBetweenTaps = TimeSpan.FromMilliseconds(250);
+               static readonly MouseTapHistory[] History = Enumerable.Repeat(
+                       new MouseTapHistory((byte)MouseButton.None, new int2(0, 0), DateTime.Now - (MaxDurationBetweenTaps * 2), 0), MaxConcurrentButtonsTapped).ToArray();
+
+               static DateTime lastTapExpireTime = DateTime.Now - (MaxDurationBetweenTaps * 2);
 
-               public static int InfoFromKeyboard(Keycode key, Modifiers mods)
+               static int Find(byte button, DateTime now)
                {
-                       return KeyHistoryCache[(key, mods)].LastTapCount();
-               }
-       }
+                       // No recent taps.
+                       if (now > lastTapExpireTime)
+                               return FindResultAllExpired;
 
-       class TapHistory
-       {
-               public (DateTime Time, int2 Location) FirstRelease, SecondRelease, ThirdRelease;
+                       for (var i = 0; i < MaxConcurrentButtonsTapped; i++)
+                               if (History[i].Button == button)
+                                       return i;
 
-               public TapHistory(DateTime now)
-               {
-                       FirstRelease = SecondRelease = ThirdRelease = (now, int2.Zero);
+                       return FindResultNotFound;
                }
 
-               static bool CloseEnough((DateTime Time, int2 Location) a, (DateTime Time, int2 Location) b)
+               static int FindUpdateIndex(DateTime now)
                {
-                       return a.Time - b.Time < TimeSpan.FromMilliseconds(250)
-                               && (a.Location - b.Location).Length < 4;
+                       // First expired or otherwise oldest.
+                       var minTime = History[0].LastReleaseExpireTime;
+                       var index = 0;
+                       for (var i = 1; i < MaxConcurrentButtonsTapped && minTime >= now; i++)
+                       {
+                               ref var el = ref History[i];
+                               if (el.LastReleaseExpireTime < minTime)
+                               {
+                                       minTime = el.LastReleaseExpireTime;
+                                       index = i;
+                               }
+                       }
+
+                       return index;
                }
 
-               public int GetTapCount(int2 xy)
+               public static int Detect(byte button, int2 xy)
                {
-                       FirstRelease = SecondRelease;
-                       SecondRelease = ThirdRelease;
-                       ThirdRelease = (DateTime.Now, xy);
-
-                       if (!CloseEnough(ThirdRelease, SecondRelease))
-                               return 1;
-                       if (!CloseEnough(SecondRelease, FirstRelease))
-                               return 2;
+                       var now = DateTime.Now;
+                       var count = 0;
+                       var index = Find(button, now);
+                       if (index >= 0)
+                       {
+                               ref var el = ref History[index];
+                               if (now <= el.LastReleaseExpireTime && (xy - el.LastLocation).LengthSquared < MaxLocationDistance * MaxLocationDistance)
+                                       count = (int)el.TapCount;
+                       }
+                       else if (index == FindResultAllExpired)
+                               index = 0;
+                       else
+                               index = FindUpdateIndex(now);
 
-                       return 3;
+                       lastTapExpireTime = now + MaxDurationBetweenTaps;
+                       History[index] = new MouseTapHistory(button, xy, lastTapExpireTime, count < MaxTapsPerButton ? ++count : count);
+                       return count;
                }
 
-               public int LastTapCount()
+               public static int Info(byte button)
                {
-                       if (!CloseEnough(ThirdRelease, SecondRelease))
-                               return 1;
-                       if (!CloseEnough(SecondRelease, FirstRelease))
-                               return 2;
+                       var now = DateTime.Now;
+                       var index = Find(button, now);
+                       if (index < 0)
+                               return 0;
 
-                       return 3;
+                       ref var el = ref History[index];
+                       return now <= el.LastReleaseExpireTime ? el.TapCount : 0;
                }
        }
 }
```

</summary>

**Comment by anvilvapre** [comment]
> I found this PR borderline unreviewable, I've generated diffs so I or someone else could possibly review so in the future

It's a replacement implementation. Code wise comparison of changes is difficult. Best to look at what the old implementation would do. See if the new does at least the same.

**Comment by AspectInteractive2** [comment]
This needs documentation. The original was sufficiently simple that you could understand it eventually by looking at the code. This version is quite a bit more complicated, so it will be difficult to debug without some documentation. Here are some suggestions:

```C#
// Find whether the recently pressed button has already been pressed and stored in MouseTapHistory
static int Find(byte button, DateTime now)
```

`static int FindUpdateIndex(DateTime now)`
rename to 
`static int FindOldestIndex(DateTime now)`

```C#
// If button has already been pressed and stored
if (index >= 0)
```

Also the below code within `Detect()` should be its own function called `FindUpdateIndex()`, since this is where you are actually finding the index to update (the current `FindUpdateIndex()` method is only getting the oldest/expired index).
```C#
			var index = Find(button, now);
			if (index >= 0)
			{
				ref var el = ref History[index];
				if (now <= el.LastReleaseExpireTime && (xy - el.LastLocation).LengthSquared < MaxLocationDistance * MaxLocationDistance)
					count = (int)el.TapCount;
			}
			else if (index == FindResultAllExpired)
				index = 0;
			else
				index = FindUpdateIndex(now);
```

Lastly, I see a lot of overlap between the `MultiKeyTapDetection` and `MultiMouseTapDetection` classes, and previously these were one class. I think we should aim to use a single class here as well, since there isn't a great deal of difference between the way they function (both use a MouseTapHistory, and find and update indexes the same way).

**Comment by Mailaender** [comment]
> The game only supports 3 mouse button presses - so only three presses at once.

Not sure if this assumptions holds up with https://github.com/OpenRA/OpenRA/pull/20811.

**Comment by anvilvapre** [comment]
That would only require the size of an array to be updated to i.e. 8.

**Comment by anvilvapre** [comment]
Rebase requires me to check each line of the other pull request. As often with old open pull requests. 

Feel free to take this over. 



Just didn't make sense to me the very over complex way you maintain state to see if buttons were pressed.

**Pull request closed without merging**
