### PR TITLE
Calc font size correctly and use it for valign

### PR DESCRIPTION
**Pull request by teinarss**
Calculate the font height with the ascender and descender values from the font and use that for valign top and middle.

Included a testcase

image

### CODE REVIEW

**Comment by pchote** [comment]
Something isn't accounting for screen scale properly...

Standard DPI:
Screenshot 2019-05-03 at 23 58 41
HiDPI:
Screenshot 2019-05-03 at 23 58 47

**Comment by teinarss** [comment]
Updated

**Comment by pchote** [comment]
```
Checking for code style violations in OpenRA.Platforms.Default...
OpenRA.Platforms.Default/FreeTypeFont.cs:L102: [SA1009] Invalid spacing around the closing parenthesis.
OpenRA.Platforms.Default/FreeTypeFont.cs:L102: [SA1008] Invalid spacing around the opening parenthesis.
Makefile:178: recipe for target 'check' failed
```

**Comment by teinarss** [comment]
Updated...

**Review by pchote — DISMISSED** [review]

**Comment by reaperrr** [comment]
Looks good to me, 👍 after testcase is removed.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6f8a4902bb80989677b1b8aeaeb44757e931aaee...f8d5b43ce3d8510d67cef164464a581661bff555

**Pull request merged**
