### PR TITLE
Remove healing ability from d2k barracks

### PR DESCRIPTION
**Pull request by obrakmann**
since it doesn't match the original game.

### CODE REVIEW

**Comment by penev92** [comment]
A lot of things don't match the original. General balancing being the biggest.
Since there is nobody willing to do the balancing, I'll give this a :-1: 
It's a cute little feature that doesn't hurt gameplay in any way.

**Comment by pchote** [comment]
I think I agree with @penev92 on this, but could be convinced otherwise.  We will certainly want to remove this as part of the retro-balance rework (if that ever gets completed), but in the meantime I don't see the harm in it.

**Comment by obrakmann** [comment]
Alright. I'll tag this as `future` and close it. I don't really see the harm atm either, except for not matching the original. Probably nobody knows about this is possible anyway :p

**Comment by penev92** [comment]
I've seen it in the YAMLs, but never had the chance to see it ingame.

**Comment by Mailaender** [comment]
I am okay with this removal. Especially since no player knows about this feature of the barracks. The tooltips don't mention it and there are not graphical indicators.

**Comment by Mailaender** [comment]
:+1:

**Comment by penev92** [comment]
I suppose this is going to get merged sooner or later, so ... no point in delaying, I guess...
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/d6ed3e1dfaf18f94b187a8bbec61af76d85cc66a...a8b32757de956021a59029c66fc7638a38514981)

**Pull request merged**
