### PR TITLE
fix hijacker build limit

### PR DESCRIPTION
**Pull request by vgaming**

### CODE REVIEW

**Comment by MunWolf** [comment]
I am pretty sure this is never going to get merged, and is probably a troll PR.

**Comment by pchote** [comment]
err what?

**Comment by pchote** [comment]
@MunWolf This PR is for TS, and looks correct to me!

**Comment by pchote** [comment]
@vgaming it looks like someone accidentally defined `BuildLimit: 1` under the `Tooltip` trait instead of `Buildable`, 6 lines below the one you've added.  Would you be able to delete that stray entry as part of this PR?

**Comment by MunWolf** [comment]
Ohh damn sorry, miss read that horribly.

**Comment by vgaming** [comment]
@pchote right, didn't notice it. Should I squash?

**Comment by GraionDilach** [comment]
@vgaming Yes, please squash. :+1: after that though.

**Comment by vgaming** [comment]
@GraionDilach @pchote all done.

**Review by abcdefg30 — APPROVED** [review]
Looks good to me. 👍 / ✅ Thanks.

**Pull request merged**
