### PR TITLE
D2K - Add Harkonnen Mission 6a

### PR DESCRIPTION
**Pull request by MustaphaTR**

### CODE REVIEW

**Comment by reaperrr** [comment]
> OpenRA.Utility(1,1): Error: Allies contains player Ordos Main Base Main Base that is not in list.

**Review by ltem — APPROVED** [review]
Couldn't spot any difference to the gruntmod version of the mission (which took me way too long to finish due to windows 10 + gruntsmod issues :S ). Also the map and the lua code is fine, so I approve this PR 👍. 

Funfact and not relevant for the review: It seems, at least I think so, that the small Ordos base was original planed as a Atreides base and these factions would be allies during this mission. If you render (gruntmods tools) the map it still has Atreides structures and the victory voice line back at the main screen (something like "The alliance was broken") makes more sense, if there was an actual alliance during the mission.

**Comment by MustaphaTR** [comment]
It is actually Fremen Base in the editor, not Atreides.

**Comment by ltem** [comment]
Ups, well, I only looked at the structures ^^

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/deafefaba8a46531bee4d052d4a9c58e935a4d00...c5e529724563a1a4bf73789a10221851ae3ecc0e)

**Pull request merged**
