### PR TITLE
Polish allies03a and allies03b

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes:
- A leftover `TODO` and removes outdated comments
- The "Free all prisoners and keep them alive" objective being completed at mission end without freeing a single prisoner
- The insertion transport helicopter not being removed

### CODE REVIEW

**Review by Arular101 — APPROVED** [review]
👍

Tested and all looks good.

Just a question. I noticed the tanks spawn already before the last bridge is destroyed. Is this intended? Because I always thought they only spawn when the last bridge is destroyed, giving me an intense relief to see the tank can't kill Tanya because of the destroyed bridge.

**Comment by ScottNZ** [comment]
I recall the tank spawning before the last bridge was destroyed in the original

**Comment by Arular101** [comment]
You are right, it seems that I always shoot at the barrels before crossing the second to last bridge.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7ea96ba6847bddfe7bc74fc09abac45d8233f069...a9b11e2281bbfbd003fc4f88c2b74c070445dfd3)

**Pull request merged**
