### PR TITLE
Add SHA1 verification to package downloads

### PR DESCRIPTION
**Pull request by pchote**
This PR makes sure that the downloaded files contain the data that we expect before extracting them to disk.

I have verified that all the existing mirrors host valid files.

### CODE REVIEW

**Comment by teinarss** [comment]
Looks good except that the error text doesn't fit.
image

**Comment by pchote** [comment]
Updated:

Screenshot 2019-05-18 at 14 31 31

**Comment by pchote** [comment]
@teinarss can you confirm a :+1: with the new wording?

**Comment by teinarss** [comment]
What technical level do we want to have this message on? The previous
message was less technical.

**Comment by pchote** [comment]
Updated wording as discussed in IRC.

**Review by teinarss — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2de24e1d70bef13b4ff997fdf963a6cbd0ec4dbe...840baa2e912882257b8af502d43ad8adf048e2d9)

**Pull request merged**
