### PR TITLE
Fixed civilians picking up player crates by accident

### LINKED ISSUE #16790: Red Alert Soviet Campaign mission 1
Blew the church up with my infantry. Civilian came out of the church of which blew up. Civilian picked up the crate himself and healed the pillboxes at the bridge.

I was in tears in laughing from this.

Might need to remove civilians from churches or other buildings which would give crates in case this happens.

### LINKED ISSUE #17802: Civilians pick up health and money crates that are meant for the player
DESCRIPTION
Civilians that spawn after you destroy houses will pick up the health crates spawned from it.
This is most notable in Red Alert Soviet Mission 3.

EXPECTED BEHAVIOR
Only the players units should be able to pick up crates in missions.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/17802.
Closes #16790.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]
Works. This will also close #16790

**Comment by reaperrr** [comment]
Don't forget about TD (and possibly TS).

**Comment by Mailaender** [comment]
Added rules for Tiberian Dawn as well. Tiberian Sun has no campaign (rules) yet.

**Comment by atlimit8** [comment]
My one concern with this is that it breaks the corner cases of players having civilians, such as from selling, and using them to fetch crates. This is  basically a hack; however, a proper fix would probably require either making crushes types conditional or making it possible to have different `Mobile` traits with only one active at a time.

**Comment by pchote** [comment]
Both the referenced issues specifically mentioned units spawned from destroyed civilian buildings. I don't remember whether this actually happened for these structures in the original game - if not, removing the spawning would be the simpler fix.

**Comment by pchote** [comment]
Confirmed that civilians do not spawn from destroyed civilian structures in the original RA, so the simpler and more correct fix here is for us to do the same - either in the default rules, or in `campaign-rules.yaml` if the current behaviour is for some reason wanted in MP.

**Comment by pchote** [comment]
TD doesn't spawn civilians from destroyed civ buildings, so this is indeed only a problem in RA.

**Comment by Mailaender** [comment]
That wouldn't account for pre-placed civilians on the map wandering around.

**Comment by pchote** [comment]
The two issues that this closes are both specifically about building-spawned actors, not pre-placed ones.

**Comment by Mailaender** [comment]
Your proposal is a map specific workaround. Mine solves it forever.

**Comment by pchote** [comment]
Solves what, though? The problem here is that scripted campaign events (providing a heal or money crate to the player) are broken by civilians being spawned when they are not supposed to. 

It should be obvious that the correct fix here is to stop them from spawning to match the original behaviour. Keeping the incorrect spawning but then giving them a custom locomotor so they don't break the script is the workaround.

**Comment by abcdefg30** [comment]
> The problem here is that scripted campaign events (providing a heal or money crate to the player) are broken by civilians being spawned when they are not supposed to. It should be obvious that the correct fix here is to stop them from spawning to match the original behaviour.

I disagree. Spawning civilians was intentional. The only problem I could see is spawning crates and civilians from the same building at the same time (but I'm not sure if that actually happens).

**Comment by pchote** [comment]
What benefit do we gain by deviating from the original behaviour here, and can you justify why the benefits outweigh the unwanted sideeffects and workarounds like this required to fix them?

**Comment by abcdefg30** [comment]
That is just my personal opinion, since I think this is a great polish addition to make the game feel more vivid. I also don't think this is an issue that needs fixing anyway, so don't need to justify workarounds. (Actually I thought the justification for changes worked the other way around, but don't care too much about it here.)
I suppose we can justify removing this since we also don't have the usual actor spawning when buildable buildings are destroyed.

**Comment by abcdefg30** [comment]
Fwiw, https://youtu.be/WKeBTdHZWK0?t=411 shows that (at least some) civilian buildings in the original did spawn civilians.

**Comment by Mailaender** [comment]
I'd say the unwanted side effects of having a civilian locomotor is none. It is code duplication, but unavoidable since #14893 and minor in this case.

**Comment by pchote** [comment]
Unwanted sideeffects include:
* Unnecessary overheads to load time and memory usage, and eventually (once group pathing is implemented) pathfinding performace.
* https://github.com/OpenRA/OpenRA/pull/18042#issuecomment-626192324
* General confusion for anybody reading the code and wondering what on earth the logic behind this decision was.

**Comment by Mailaender** [comment]
That is a bit far fetched. 

* Please benchmark the performance overhead before making such claims.
* Buildings don't spawn civilians, but technicians. Also, there is no MCV crate you can long for with your last pistol swinging guy in single-player for obvious reasons.
* General confusion... haha, okay you needed a third point, but my point is the general confusion of the player is higher when a civilian picks up his heal crate than someone stumbling over an additional locomotor. I can name it `civilian-no-crate-pickup` if you need it verbose.

**Comment by teinarss** [comment]
> 
> 
> That is a bit far fetched.
> 
>     * Please benchmark the performance overhead before making such claims.
> 

This will add another locomotor cache that will add to load and memory usage. By my calculations it would be around 0,3 mb, if we say that the map is 128x128 and the number of bytes needed for each cell in the cache is 17.

**Comment by Mailaender** [comment]
Thanks. I measure ~800 MB of RAM usage on soviet01. That means an increase of 0,0375% in memory resource usage...

**Comment by Smittytron** [comment]
> Fwiw, https://youtu.be/WKeBTdHZWK0?t=411 shows that (at least some) civilian buildings in the original did spawn civilians.

That's a on-damaged trigger before the building is destroyed. Played a couple high civilian casualty missions on remastered; looks like no civ spawn is the way to go here.

**Comment by Mailaender** [comment]
This has to be worked around on a per-map basis then.

**Comment by abcdefg30** [comment]
I can have a look at that. We should at least not spawn civilians and crates from one building at the same time, and also decide if we make infantry spawning map-specific or keep it as is.

**Pull request closed without merging**
