### PR TITLE
Remove bounties from d2k

### PR DESCRIPTION
**Pull request by abcdefg30**
As requested by @pchote and @penev92 on IRC.

Btw, this has actually :-1: from me, but it's needed for #8117.

### CODE REVIEW

**Comment by penev92** [comment]
:+1:

**Comment by Phrohdoh** [comment]
So just remove it from the missions?

**Comment by pchote** [comment]
@Phrohdoh: as part of our plan to make D2K more like the original game and less like "RA with sand" the emphasis of any argument should be on justifying why bounties should remain at all (and whether that justification is sufficient to override the complications for the campaign and elsewhere).  I personally find it counter-intuitive that factions fighting over a magical harvestable commodity can fund a significant amount of their costs through bounties.

**Comment by Phrohdoh** [comment]
@pchote The stance has always been "prove why it should be merged", not "prove why it shouldn't be" and you have stated this many times yourself.

> I personally find it counter-intuitive that factions fighting over a magical harvestable commodity can fund a significant amount of their costs through bounties.
Shouldn't we remove bounties from all mods then?

**Comment by pchote** [comment]
Sure thing:
* It takes a step closer to our goal of making our D2K a recreation of the original game.  Given this goal, removing bounties everywhere is a no-brainer unless somebody can argue why it is important enough to keep.
* It avoids the confusion (discussed extensively in IRC recently) that occurs in the "harvest X resources" singleplayer missions: either the combined spice+cash counters gets out of sync with the mission goal, or we count both spice+cash and allow people to win these missions using bounties instead of harvesting.

**Comment by Phrohdoh** [comment]
@penev92 brought up a good point [here](https://github.com/OpenRA/OpenRA/pull/8117#issuecomment-101998181), and while it is actually about the order of methods it here also exposes the fact that the refund the player gets from selling structures will also count toward your target amount.

Should the refund mechanic be removed from missions or just safeguarded in Lua as @abcdefg30 has attempted to do?

Your points are valid, the second more so than the first IMO.
It is clear that my opinion will be out-voted here but I just wanted to make my position known and spark discussion about it on GitHub.

**Comment by penev92** [comment]
> [14:20] < penev> true, but selling the conyard affects things only because we check player.Cash, which was done because bounties

**Comment by abcdefg30** [comment]
> [...] which was done because bounties [...]

No.
The actual reason behinde the `player.Cash + player.Resources` check was, that the UI shows you exactly this sum. So atm selling buildings won't have any effect, but we got back to this "the UI lies to you" point.

**Comment by LipkeGu** [comment]
bounties in skirmish is fine but not for campaign :/

**Comment by Mailaender** [comment]
I count equally +1 and -1. No consensus yet.

**Comment by pchote** [comment]
:+1:

**Comment by Mailaender** [comment]
> It takes a step closer to our goal of making our D2K a recreation of the original game.

:-1: See https://github.com/OpenRA/OpenRA/wiki/FAQ#this-is-not-true-to-the-original

> It avoids the confusion that occurs in the "harvest X resources" singleplayer missions.

Can be easily fixed with some narrative. The emperor/admiral suddenly (tutorial missions ended) decides to put bounties on killed enemy units to motivate commands.

So. :-1:

**Comment by abcdefg30** [comment]
I think this can wait for the balance overhaul. Also there are a lot of :-1:'s.
Sorry for wasting everyone's time.

**Pull request closed without merging**
