### PR TITLE
Rename the Country trait to Faction

### PR DESCRIPTION
**Pull request by penev92**
This is another split off from #7873.
It's not as scary as it looks at first glance - it only renames 3 things.

P.S.: A long time ago, when this was planned, it was proposed that Race be renamed to ID. I am open to suggestions on that point, in case anyone doesn't like InternalName too much. I can go with ID (or something else) if requested.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: Looking good. I like the generic naming. ID is too unprecise imho.

**Comment by penev92** [comment]
Rebased.

**Comment by abcdefg30** [comment]
Needs a rebase again.

**Comment by penev92** [comment]
Rebased and updated as per @abcdefg30's request.

**Comment by abcdefg30** [comment]
Needs a rebase again.

**Comment by penev92** [comment]
Rebased again.

**Comment by obrakmann** [comment]
Looks fine to me. Game still works. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/870a898429fa64f101d9e3279889499dba9577b5%5E...870a898429fa64f101d9e3279889499dba9577b5)

**Pull request merged**
