### PR TITLE
Polished monster-tank-madness

### PR DESCRIPTION
**Pull request by abcdefg30**
What I did:
- The mission shows the "test" of the super tanks at the beginning
- The walls of the outpost belong to the player now
- Improved the super tanks (heal if below 100% and don't eject drivers as you're machines)
- Fixed the tooltips of husks and crates

### CODE REVIEW

**Comment by Mailaender** [comment]
Okay, but we forgot the tooltip of the wired fences:

image

**Comment by abcdefg30** [comment]
Rebased. https://github.com/OpenRA/OpenRA/pull/7329#issuecomment-70359680 should be fixed now.

**Comment by Mailaender** [comment]
:+1: The intro looks much nicer now.

**Comment by obrakmann** [comment]
I suggest to delay running `InitObjectives` as well until the "real" mission starts

**Comment by abcdefg30** [comment]
Updated.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/f7839ca8d803ab70a01a028f6f7dced81e9ebb8b...56737c4fd1550411ba43a3475f40bac29f0b8325)

**Pull request merged**
