### PR TITLE
RA balance fixed up

### PR DESCRIPTION
**Pull request by obrakmann**
Supersedes #9959, fixes the ttnk issue. I'm adding the :+1: from the original PR.

### CODE REVIEW

**Comment by obrakmann** [comment]
Added https://github.com/obrakmann/OpenRA/commit/0fab4669fce43862633ee9f6389dec2e3c54389d on Microbit's request. Removing the :+1:,

**Comment by penev92** [comment]
Hey that was my :+1: !

I'm going to keep it regardless.
:+1:

**Comment by cjshmyr** [comment]
Tested with @obrakmann applying this patch ontop of prep-1512 :+1:

**Comment by cjshmyr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/90e934267834076dd2c96e3e025997164f0d824a

**Pull request merged**
