### PR TITLE
Add HPF overlay controls to observer chrome

### PR DESCRIPTION
**Pull request by dragunoff**
The controls associated with the "hpf" debug command were only visible in player context.

### CODE REVIEW

**Comment by PunkPun** [comment]
Common UI is used for the SDK, it's would be better to follow the convention and use common for RA and delete RA specific file rather than the opposite

**Comment by dragunoff** [comment]
> Common UI is used for the SDK, it's would be better to follow the convention and use common for RA and delete RA specific file rather than the opposite

How is it used in the SDK? If you mean other mods referencing it then it's a downstream problem. There's no point in keeping an unused file around as it cannot be tested.

**Comment by PunkPun** [comment]
I'm not suggesting keeping unused files, I'm suggesting using common for red alert, as it's already how we handle most of red alert and tiberian sun UI

**Comment by dragunoff** [comment]
> I'm not suggesting keeping unused files, I'm suggesting using common for red alert, as it's already how we handle most of red alert and tiberian sun UI

Yes, sure but then this doesn't help downstream mods at all as they will get a file that is tailored to RA but named "common". And we mess up the git history for no good reason.

**Comment by dragunoff** [comment]
Anyhow, I don't care that much which file remains as long as we get rid of unused ones.

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/pull/20079#issuecomment-1250221419

**Comment by dragunoff** [comment]
> [#20079 (comment)](https://github.com/OpenRA/OpenRA/pull/20079#issuecomment-1250221419)

@PunkPun I'm against using a "common" file here because it's not common at all - the ingame UI is slightly different for each mod. So downstream mods linking to a file tailored for another mod probably won't get good results. And in the end it's a downstream problem - chrome yaml files change all the time and it's downstream mods responsibility to make sure they keep up with updates. If you insist on having a common file for ingame-observer then I'd suggest using the one from TS or D2k as the diff there is smaller (the one for RA just differs too much to the current common one).

**Comment by PunkPun** [comment]
Let's go with TS then. We should investigate how many other UI pieces don't have a common variant

**Comment by abcdefg30** [comment]
I disagree that we should have a common file just for the sake of it. (While in reality it is not common but just used by one mod.) Nothing is stopping downstream mods from copying the TS or RA file if they need it.

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
Tested all 4 mods, as a player and a spectator

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b2aea7d84724de9a4524499c4e92f63f43814c6e...8db99ce7690ecca213eb3c59fda1113dddb1f945)

**Pull request merged**
