### PR TITLE
Remove AI capturing from TD and RA, and AIs using mechanics and medics in RA

### PR DESCRIPTION
**Pull request by obrakmann**
Note: this PR is directly against prep.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Might worth to add the medic/mechanic removal into this PR as well.

**Comment by obrakmann** [comment]
Yeah, might as well. Updated.

**Review by cjshmyr — APPROVED** [review]
Tested :+1:

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/bf3bdcb43c0b509b0084fe589497941fd6369b4e...899af6f8005638c9cdd2abac3645d798f23498d0)

**Pull request merged**
