### PR TITLE
Fixed yaml code highlighting on GitHub

### PR DESCRIPTION
**Pull request by Mailaender**
https://github.com/OpenRA/OpenRA/wiki/Settings/_compare/5d68953591284c141a5dbb3ebb14076b26f8acd4...2161bd929da766d1eb763aabc9e3686f43171af9?short_path=99249bf#diff-99249bf5bc3cb1762c803a4bacf25478

https://github.com/OpenRA/OpenRA/wiki/Lua-API/_compare/887dd5fc5f965f6562caf117eb4f7033ddea3dd1...35a5728736dcdb4f54a563a753f586d456fa673c

### CODE REVIEW

**Comment by abcdefg30** [comment]
Fwiw, discussion from the day before yesterday:
> 13:49:10	(pchote) i found a workaround for the broken yaml syntax highlighting on github
13:49:25	(pchote) use \```saltstack instead of \```yaml
13:49:42	(pchote) workaround/hack
13:49:58	(abcdefg30) saltstack, interesting ^^
13:50:09	(abcdefg30) but I can't change that for viewing diffs, can I?
13:50:09	(pchote) that display formatter is forked from yaml before they "fixed" it to show invalid indentation as red
13:50:18	(pchote) no just for the wiki stuff like the settings page
13:50:27	(pchote) my ping was going to be about whether we wanted to do this in your PR
13:50:36	(abcdefg30) ah
13:50:48	(pchote) but then on second thought its probably not a good future-proof idea

**Comment by pchote** [comment]
I raised this a few days ago on IRC:

> [13:49:10] | &lt;pchote&gt; i found a workaround for the broken yaml syntax highlighting on github
> [13:49:25] | &lt;pchote&gt; use \```saltstack instead of \```yaml
> [13:49:42] | &lt;pchote&gt; workaround/hack
> [13:49:58] | &lt;abcdefg30&gt; saltstack, interesting ^^
> [13:50:09] | &lt;abcdefg30&gt; but I can't change that for viewing diffs, can I?
> [13:50:09] | &lt;pchote&gt; that display formatter is forked from yaml before they "fixed" it to show invalid indentation as red
> [13:50:18] | &lt;pchote&gt; no just for the wiki stuff like the settings page
> [13:50:27] | &lt;pchote&gt; my ping was going to be about whether we wanted to do this in your PR
> [13:50:36] | &lt;abcdefg30&gt; ah
> [13:50:48] | &lt;pchote&gt; but then on second thought its probably not a good future-proof idea

My concern is that this only works because the saltstack formatter was forked from the standard yaml formatter before it tightened its syntax rules. It is just a matter of time before they update to the newer version, which leaves us with the same problems plus the additional confusion of referencing the wrong language for no benefit.

**Comment by Mailaender** [comment]
It isn't a clean solution, but half of https://github.com/OpenRA/OpenRA/wiki was already using it. I updated the rest.

**Comment by pchote** [comment]
> but half of https://github.com/OpenRA/OpenRA/wiki was already using it.

I cloned the wiki repo and searched for uses of ```salt`, but could only find two uses before this PR and the changes done by hand alongside it.

**Comment by abcdefg30** [comment]
Sorry, but I don't think we should take this from what I can see.

**Pull request closed without merging**
