### PR TITLE
Evaluate smooth scrolling per-frame instead of per-tick.

### PR DESCRIPTION
**Pull request by pchote**
This PR changes `ScrollPanelWidget` to update the smooth scrolling position every frame instead of every tick. This increases the animation smoothness by 2.4x (assuming 60FPS rendering), which dramatically improves the perceived performance.

Testcase: Open the map chooser and scroll using the mousewheel / trackpad gesture.

This is a big polish win, so I'd like to get this into the playtest.

### CODE REVIEW

**Review by Smittytron — APPROVED** [review]
Yep, certainly looks better.

**Review by TheChosenEvilOne — APPROVED** [review]
smooth as butter :+1:

**Review by ghost — APPROVED** [review]
Feels good.

**Comment by Sininini** [comment]
This is excellent!

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f9f411142392b9f3eca14652a9b746e0f7aa1d8a...fe8d5807a39ae3674e1c62093c0b0f081b675a73

**Pull request merged**
