### PR TITLE
Switched to the new the Docker-based Travis CI infrastructure

### PR DESCRIPTION
**Pull request by Mailaender**
This has been suggested in https://github.com/travis-ci/travis-ci/issues/3077#issuecomment-69458787 to get timeouts under control.

### CODE REVIEW

**Comment by obrakmann** [comment]
Certainly seems to work. Let's see if it helps with the timeouts. :+1:

**Comment by Mailaender** [comment]
I don't know for sure if the non-sudo package installation works.

**Comment by obrakmann** [comment]
It somehow didn't register with me that this only happens during deployment.

Three things then:

1. you need to alter the `PATH` after unpacking the packages, otherwise the makefiles and scripts won't find the executables.
2. if `dpkg --force-not-root` doesn't work, you can use `dpkg -x` instead. Shouldn't make much of a difference with these packages (I hope).
3. Why install `dpkg`? I assume that it must already be installed, since its an essential package.

**Comment by Mailaender** [comment]
Yes, `dpkg` should be installed in the new Docker images. Can you send me a pull request for the other Ubuntu related changes. I can't test those.

**Comment by obrakmann** [comment]
This should work:
```
- apt-get download nsis markdown
- dpkg -x nsis*deb $HOME
- dpkg -x markdown*deb $HOME
- export PATH=$PATH:$HOME/usr/bin
```

**Comment by Mailaender** [comment]
Thanks. Updated.

**Comment by pchote** [comment]
I don't see any obvious issues with this, so lets try it and see.  If we still see issues with nuget, then we could try caching the thirdparty dir: http://docs.travis-ci.com/user/caching/#Arbitrary-directories

**Pull request merged**
