### PR TITLE
Add a note in the tooltip of build-limited TS structures

### LINKED ISSUE #7349: EMP Cannon should act as SupportPower (EMPSpecial)
We introduced the EMP logic for TS to get this work but we should transform them to an EMPSpecial as like in vanilla TS.

In the Moment the EMP is a game killer because:
- When i build of a Wall of EMP Cannons the Game will lag
- The EMP Cannon is firering every second
- Buildlimit should be limited to 1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7844571-emp-cannon-should-act-as-superweapon-empspecial?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
~~Also updates the tooltip(s) to reflect that.~~

~~Closes #7349.~~

EDIT:

> Now I only adjust the tooltip of buildings with a buildlimit.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
:-1: This is not how Vanilla E.M.Pulse cannon works. I was always against the build limit and still is. More than one Cannon should be buildable but only give range support not extra SW to launch.

**Comment by Mailaender** [comment]
This seems to be a misunderstanding. https://github.com/OpenRA/OpenRA/issues/7349 probably only suggested the build limit to workaround the fact that it wasn't a support power back then.

**Comment by abcdefg30** [comment]
Updated. Now I only adjust the tooltip of buildings with a buildlimit.

**Comment by Mailaender** [comment]
Okay. :+1:

**Comment by GraionDilach** [comment]
:+1:

**Pull request merged**
