### PR TITLE
Added a Tiberian Sun loadscreen and shellmap logo

### PR DESCRIPTION
**Pull request by Mailaender**
Just like https://github.com/OpenRA/OpenRA/pull/9130 this isn't meant to be final in any way although they look quite nice together. This replaces the last bit of Tiberian Dawn artwork from the mod. Editable image source: https://github.com/OpenRA/ArtSrc/pull/2.

### CODE REVIEW

**Comment by LipkeGu** [comment]
We should keep the preview image to show that this Mod is in still in development stage :)

**Comment by penev92** [comment]
Sorry, I'm not convinced that it looks better.

**Comment by Mailaender** [comment]
It adds consistency and uses a more subtle placeholder like https://github.com/OpenRA/OpenRA/pull/7186. From what I read in IRC there are more ambitious plans for crafting and coding the in-game UI, but those have a tendencies to take very long and be abandoned quickly so this is better than nothing when only ideas and mock-ups exist I guess.

**Comment by GraionDilach** [comment]
It looks much more fitting than that GDI logo for sure. :+1:

**Pull request merged**
