### PR TITLE
Added lights to the Nod Montauk and Pyramid

### PR DESCRIPTION
**Pull request by Mailaender**
- http://cnc.wikia.com/wiki/Montauk
- http://cnc.wikia.com/wiki/Nod_Pyramid

### CODE REVIEW

**Comment by GraionDilach** [comment]
`ntpyra`'s `damaged-idle-lights` missing a `Start: 16` https://github.com/LipkeGu/TSIniFiles/blob/master/art.ini#L4390

**Comment by Mailaender** [comment]
Thanks. Fixed.

**Comment by GraionDilach** [comment]
:+1:

**Comment by penev92** [comment]
Nice :+1:

**Pull request merged**
