### PR TITLE
Fixed WithCargo

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes the breakages spotted at https://github.com/OpenRA/OpenRA/pull/7229#issuecomment-68625429 introduced in https://github.com/OpenRA/OpenRA/pull/7178. I took the time to make this far more robust and easy to use. Before, `WithCargo` would crash the game when relying only on the default values which is something we avoided for almost any other trait.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
I apologize for sounding like a broken record and probably seeming pushy but could we get more informant commit messages? Something like "this now does foo" would be better as "TraitWow now does foo", etc.

Looks good otherwise.

**Comment by Mailaender** [comment]
> Something like "this now does foo" would be better as "TraitWow now does foo", etc.

Try giving concrete suggestions instead of these vague and confused instructions.

> An uglier, but more reliable approach would be to get the smallest offset and use that.

That will give you less control though.

**Comment by penev92** [comment]
> That will give you less control though.

True, but we're now completely dependent on people ordering the offsets in a particular way in the YAML, and we don't even have this documented. I *can* agree to this, but only if `LocalOffset`'s description includes it. (that the default offset should be in the middle of the list)

**Comment by Mailaender** [comment]
Documented it now as suggested.

**Comment by penev92** [comment]
Well at least the code doesn't look as magical now. I'll give it a try ingame shortly.

**Comment by penev92** [comment]
OK, so TD is back to normal.
The D2k shellmap needs a tweak, though.
The current `LocalOffset: 0,0,-512` is too much. I would suggest something like `LocalOffset: 0,0,-256`, or around that. Once that is done I think we're ready ;)

**Comment by Mailaender** [comment]
I filed https://github.com/OpenRA/OpenRA/pull/7308 to polish that further as it is actually unrelated to this regression fix pull request.

**Comment by obrakmann** [comment]
Looks fine to me. :+1: The carryall offset issue is addressed in 7308.

**Comment by penev92** [comment]
:+1:

**Pull request merged**
