### PR TITLE
Remove legacy A* visualisation.

### PR DESCRIPTION
**Pull request by pchote**
This visualization looks fun, but hasn't been useful for as long as I can remember.  It needs a complete rewrite before it will properly with isometric or heightmap-enabled mods.

This PR puts the feature out of its misery so that it doesn't cause any more maintenance burden until it is next needed.  If that time ever comes it can then be re-implemented in a way that works for all mods (e.g. using color-tinted sprite overlays or whatever technique we end up using for #3605).

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by obrakmann** [comment]
Please add an upgrade rule. :+1: after that.

**Comment by pchote** [comment]
Done.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1e9153a44ac9e2e9bfb2effd9341cac428b587e7...44e35626787ae660e54b77f1b3dcb8090d71d4d9)

**Pull request merged**
