### PR TITLE
D2k super weapon timers

### PR DESCRIPTION
**Pull request by OmegaBolt**
Adjusted the SW timers that makes them correctly relative to one another.

I simply timed them with a stopwatch, then multiplied them to hopefully match our game speed. They shouldn't be wildly off, and are at least more accurate than what is currently in place.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
IIRC, Saboteur builds quicker than fremen but i'm not sure.

**Comment by OmegaBolt** [comment]
If they do Mustapha, it's within seconds because they came up as the same time, give or take the speed of my finger to stop the clock. It seemed to me that Fremen & Saboteur are the same and Ornithopters & Death Hand are the same.

**Comment by obrakmann** [comment]
OK, I guess. :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5fc595725c9e55dca00401f4e0f03d3fd784416b)

**Pull request merged**
