### PR TITLE
Improve Hind visibility

### PR DESCRIPTION
**Pull request by Inq8**
Recoloured the hind a few shades lighter, to alleviate #15401

Should help unit visibility when multiple teams are playing with dark colours.

### CODE REVIEW

**Comment by Inq8** [comment]
hindcolor

**Comment by matjaeck** [comment]
Could it be that the "weapon stations" are lighter too and that this is the reason the helicopter looks "thinner"?

**Comment by Inq8** [comment]
> 
> 
> Could it be that the "weapon stations" are lighter too and that this is the reason the helicopter looks "thinner"?

I only reshaded the remap colours, The greys/browns of the weapon pylons & the blues of the cockpit glass were left untouched.

**Comment by pchote** [comment]
It definitely looks like some pixels have been lost here. The leftmost hind in your animation above has the top of the tail completely disconnected from the body - this shows up in both the body and the shadow, so isn't just a compression issue.

**Comment by Inq8** [comment]
> 
> 
> It definitely looks like some pixels have been lost here. The leftmost hind in your animation above has the top of the tail completely disconnected from the body - this shows up in both the body and the shadow, so isn't just a compression issue.

It's a good observation... but thats not my error - that's Westwood's
hinderror

On the right is the original Westwood sprite untouched by me. I literally just changed the remap colour to increase the Hind's visibility. **No pixels were added or removed**.

I can go back through it and add the missing pixels from the tail etc to "fix" the artwork if thats what the general concensus is?

**Review by MustaphaTR — APPROVED** [review]
Didn't test myself, but looks good to me from the images.

**Review by pchote — APPROVED** [review]
LGTM. This is a significant improvement ingame.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bf7d4f7aac318ee64555c756b90c83e56c57592e

**Pull request merged**
