### PR TITLE
Reduce duplication of "Battlefield Control" chat line label

### PR DESCRIPTION
**Pull request by dragunoff**
Split from #17563 because this change is not blocked by the conversation going on there.

### CODE REVIEW

**Comment by Mailaender** [comment]
It looks like you just shifting hardcoded variables around. Why not make this configurable on a per trait level? That way we get trait documentation and it can be changed in custom mods.

**Comment by pchote** [comment]
The idea is that this label *shouldn't* be customized on a per trait level. The proper place to define this string will be in the language/translation data, but we still don't have a system for this.

**Comment by pchote** [comment]
Is there a specific reason why you didn't include the Lua API changes here too @dragunoff?

**Comment by dragunoff** [comment]
> 
> 
> Is there a specific reason why you didn't include the Lua API changes here too @dragunoff?

I didn't include them because Lua API is hard-coded to use the label "Mission". The changes in #17563 stemmed from making that label configurable. In this PR I'm just placing the string "Battlefield Control" in one location instead of having it scattered and duplicated across traits and widgets. I'm still allowing other labels to use the system chat color through the overload. 

While working on a prototype for #6354 I got some more ideas for the chat lines (split the chat into pools, where each pool can have a different color and label if necessary). I'm hoping to file a PR soon. Perhaps we should wait for that PR as it changes quite a few things related to chat lines.

**Comment by dragunoff** [comment]
Updated to remove the label from `DisplaySystemMessage` in the Lua API - this method is not used anywhere so nothing is affected.

**Comment by abcdefg30** [comment]
That we don't use this in the default repository doesn't mean it is unused by custom maps. Luckily I don't think this would cause any crashes since I think the superfluous value would just be dropped. It would only cause unexpected behaviour since the custom prefix would be ignored.

Tbh, I don't know why we have this method at all. You can already freely define the color of chat messages, so this method does not seem to make much sense? (Not even if you argued that the prefix would be exposed to translations, since the message would not be translated!)

**Comment by pchote** [comment]
It is still a compatibility breaking change. Can we instead change the default prefix to `null` and call the two-arg `AddSystemLine` if the script has set it?

**Comment by dragunoff** [comment]
Rebased and updated to handle the Lua API method with and without a prefix.

**Review by teinarss — APPROVED** [review]

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2befe0a05531f728e47b1afd6236bfce7151b5f9

**Pull request merged**
