### PR TITLE
Ignore buildlimits with AllTech cheat

### LINKED ISSUE #7352: "Build everything" dev cheat should override the build limit for actors
As I understand, it currently doesn't, which seems weird to me. Also might prevent you from properly/easily testing an actor that has a build limit. (Or just prevent you from having some fun with 
10 * Mammoth Mk 2 in the enemy base :D )

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #7352.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
The code makes sense, but I am a bit rusty with the production logic.

**Comment by abcdefg30** [comment]
Updated.

**Comment by Phrohdoh** [comment]
Could you flip that test order around to check the cheat first?

After that :+1:.

**Comment by abcdefg30** [comment]
Updated.

**Comment by penev92** [comment]
:+1:

**Pull request merged**
