### PR TITLE
Fixed suicides counting as kill in the game score

### LINKED ISSUE #19613: ChangesHealth and killself count the actor killed scores to owner Player
IMO, It makes no sense here to pass an attacker in `self.InflictDamage();`.

and this is one of the bug.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/19613

### CODE REVIEW

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
We still need to update the Army and Assets values when the unit dies.

**Comment by Mailaender** [comment]
Ah, yes correct. Updated.

**Review by abcdefg30 — DISMISSED** [review]

**Comment by dnqbob** [comment]
with this fix we can let poison that lethal finally achieve without bug

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d78a43ffd7ec82cfe949ea90b3e35c8a876a53c5...a6efcfa1e2986afcf0d4fcbc65525efd8bf30303

**Pull request merged**
