### PR TITLE
Small code cleanup.

### PR DESCRIPTION
**Pull request by phrohdoh**
Simplify return statements.
Remove redundant ‘this’.
Remove unused using directives.
Simplify LINQ chains.
Add some trait property descriptions.
Add readonly where viable.
Add fullstops to some yaml descriptions.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Looks good, but you'll need to move some of the readonly fields above the non-readonly ones to placate stylecop.

**Comment by Phrohdoh** [comment]
Updated.

**Comment by Mailaender** [comment]
:+1: Did you do this with some kind of automated tool?

**Comment by Phrohdoh** [comment]
No sir, just spent time looking over the classes.
I skipped Mods.Common and the other projects so I can do other things today.

**Comment by RoosterDragon** [comment]
:+1:

**Pull request merged**
