### PR TITLE
Allow ReturnToBase to exit if actor does not land at building.

### PR DESCRIPTION
**Pull request by tovl**
Fixes a small oversight in #16481.

### CODE REVIEW

**Comment by pchote** [comment]
Does this fix #16784?

**Comment by tovl** [comment]
Not quite. It partially fixes the first part of that issue. Helis will only hover above the repair bay but will not in anyway occupy it or repair when fired upon.

**Comment by fruestueck** [comment]
> 
> 
> Not quite. It partially fixes the first part of that issue. Helis will only hover above the repair bay but will not in anyway occupy it or repair when fired upon.

Should i split the issue? Thought they are alsmost the same

**Comment by tovl** [comment]
No need. This is a fix for a minor unreported issue that is only tangentially related to that issue.

**Review by pchote — APPROVED** [review]
This fixes helicopters that are ordered to RTB with full ammo from flying to the helipad and then continuously queuing `Fly` children to their current position. They will now fly to the helipad and go idle.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1839e9b566a3acefce27805b6db9ae4c10704458...8368130d3f4148e204301e6a2ea6b5e4379cc0e0)

**Pull request merged**
