### PR TITLE
Allow integer range notation in yaml

### PR DESCRIPTION
**Pull request by phrohdoh**
@teees this should make gate sequences a bit cleaner.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Added `[PR: Has dependencies]` because the test commit needs to be removed before this is merged.

**Comment by pchote** [comment]
I think it would be good to use this to replace the Start and Length sequence properties, which makes the sequence definitions more descriptive and consise.  As a side effect it will kill the Length: * which gets in the way of static analysis.  The downside is that it forces people to count frames instead of throwing a Length: * at it, but I can live with that.

**Comment by GraionDilach** [comment]
I'm not a fan of killing of `Length: *` because it was the default behaviour in TS/RA2 `art.ini` and those games (especially RA2 or a mod of any of the two) have a lot of animations.

I do like this PR though.

**Comment by penev92** [comment]
Why does the test commit need to be removed? I think it makes sense to leave it, and maybe even add a few more. That's the point of this feature, after all.

**Comment by Phrohdoh** [comment]
Fair point.
Either way it needs to be redone, I didn't stage the file properly.

**Comment by RoosterDragon** [comment]
Are we going to want a matching `FieldSaver` that users ranges when it can?

**Comment by Phrohdoh** [comment]
If people can agree on rules for writing out a range, sure.
I can not think of a delta value we should support that is not just as arbitrary as the next.

**Comment by atlimit8** [comment]
A number plus a comma is at least 2 characters and 2 numbers plus `[..]` is at least 6 characters, so 3 or more consecutive values should be merged into a range since that would take at most the same number of characters.

**Comment by Phrohdoh** [comment]
Ok.
Is that required for this PR?

**Comment by atlimit8** [comment]
No, I would not oppose merging this without changes to the `FieldSaver`. It is not that important.

**Comment by Mailaender** [comment]
Starting a skirmish game will crash:

```
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1366x768
Using resolution: 1366x720
Detected OpenGL version: 3.0
Using OpenAL sound engine
Using default device
Available mods:
        all: All mods ({DEV_VERSION})
        cnc: Tiberian Dawn ({DEV_VERSION})
        d2k: Dune 2000 ({DEV_VERSION})
        modchooser: Mod Chooser ({DEV_VERSION})
        ra: Red Alert ({DEV_VERSION})
        ts: Tiberian Sun ({DEV_VERSION})
Loading mod: ra
Exception of type `OpenRA.YamlException`: Session deserialized invalid MiniYaml:
Client@0:
        Index: 0
        PreferredColor: 8CFF69
        Color: 8CFF69
        Faction: Random
        SpawnPoint: 0
        Name: Matt
        IpAddress: 127.0.0.1
        State: Invalid
        Team: 0
        Slot: Multi0
        Bot:
        BotControllerClientIndex: 0
        IsAdmin: True

ClientPing@0:
        Index: 0
        Latency: -1
        LatencyJitter: -1
        LatencyHistory:

Slot@Multi0:
        PlayerReference: Multi0
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

Slot@Multi1:
        PlayerReference: Multi1
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

Slot@Multi2:
        PlayerReference: Multi2
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

Slot@Multi3:
        PlayerReference: Multi3
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

Slot@Multi4:
        PlayerReference: Multi4
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

Slot@Multi5:
        PlayerReference: Multi5
        Closed: False
        AllowBots: True
        LockFaction: False
        LockColor: False
        LockTeam: False
        LockSpawn: False
        Required: False

GlobalSettings:
        ServerName: Skirmish Game
        Map: 895ad2666bb53933906556e19556dacf48c45b1a
        Timestep: 40
        OrderLatency: 3
        RandomSeed: 846099880
        FragileAlliances: False
        AllowCheats: False
        AllowSpectators: True
        Dedicated: False
        Difficulty:
        Crates: True
        Creeps: True
        Shroud: True
        Fog: True
        AllyBuildRadius: True
        StartingCash: 5000
        TechLevel: Unrestricted
        StartingUnitsClass: none
        GameSpeedType: default
        ShortGame: True
        AllowVersionMismatch: False
        GameUid:

  at OpenRA.Network.Session.Deserialize (System.String data) [0x00148] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Network/Session.cs:64 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x0088b] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Network/UnitOrders.cs:197 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00119] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Network/OrderManager.cs:124 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00007] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:170 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1 fn) [0x00008] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:178 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x0001b] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:170 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00121] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:482 
  at OpenRA.Game.LogicTick () [0x00055] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:527 
  at OpenRA.Game.Loop () [0x000d4] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:651 
  at OpenRA.Game.Run () [0x00042] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:691 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Support/Program.cs:117 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Support/Program.cs:39
```

Not sure why though.

**Comment by Phrohdoh** [comment]
I don't know either and I haven't touched this in 20 days at least, so I'm going to close this.
Perhaps a `FieldSaver` is needed before this can be merged.

**Pull request closed without merging**
