### PR TITLE
Revert "Reduce order latency locally"

### PR DESCRIPTION
**Pull request by Mailaender**
Reverts OpenRA/OpenRA#17903

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
Ok. Sad that we have to go this way, but at least we have time to fix it properly now in a new PR. CC @adammitchelldev

**Comment by deleted-user-1** [comment]
This is potentially a consequence of what turned out to be a not exclusively positive change to the CI pipeline (e.g. codacy) which I think (although can't know for certain) might have put pressure on reviewers to merge pull requests with remaining elements of confusion caused by it to prevent further distraction. 

Unfortunately the discussions surrounding the changes that are reverted here and which would have been valuable information for the person who ended up merging them were not visible on github so there is the possibility that a lack of information contributed to decisions with in hindsight potential to learn from, which itself may be a win at the end.

It's not desireable at a first glance that this ends being reverted and it should be noted here that the original PR author is not to blame for this. Hopefully he takes another approach because from my perspective there is so much potential in their involvement.

**Comment by Mailaender** [comment]
In Discord @adammitchelldev noted that he does not have time to address the outstanding comments in #17903 which is another reason to revert this. It is a bit sad. I was blinded by the very obvious input lag removal, but indeed didn't test all potential breakage. Sorry for that.

**Comment by deleted-user-1** [comment]
Comment edited to be in line with CoC, sorry for being disruptive. As a player I had high hopes in these changes and have been equally disappointed when seeing them being reverted.

**Comment by penev92** [comment]
Comment unhidden after the edit. Bonus points for the fancy wording this time around 😄

**Comment by Mailaender** [comment]
Note: the @codacy accident had nothing to do with this. It was quickly communicated in IRC and Discord that those rules don't apply and can't be adapted for the OpenRA project. I had high hopes to help streamline the currently stuck review process. However, the support just answered me that we should keep our `{ }` as the thirdparty product they re-sell comes with that rule... It was also unpolite that the registering via GitHub meant that they automatically add their CI integration to the repositories I have access to without asking first. I can only recommend everyone to stay away from Codacy at this point.

Sorry that mess also coincided with the wrong decision to merge #17903 just yet. Thought it was an easy target to cleanup the pull request queue. Formally we had +2 and no reply from @pchote to the answered comments for 3 months so it looked good at first glimpse. I hope we can just revert this quickly now and come back to it later.

**Review by obrakmann — APPROVED** [review]

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2b160e64d92c03ef3c999c0fd9831ef7905cc526)

**Comment by adammitchelldev** [comment]
@matjaeck don't worry, I'm not put off contributing, I think there's a lot to improve on this part of the code and I can at least help.

The contents of the PR were meant to be a "cheap win", but as has been sadly discovered, this part of the code is a bit too fragile for hasty changes. There is a lot of "hack this feature in" technical debt, the architecture has been incorrectly refactored multiple times with little to no documentation and there is basically no encapsulation left. It is nigh impossible to make assumptions about whether or not a change will be valid because other parts of the system do not behave in well-defined/documented and isolated ways (e.g. the behaviour of orders, replays, various aspects of the game loop). I can only guess or infer the thought processes behind each part, for example: there should be no reason for the replaying replays to care about order latency since orders are recorded *post* latency, but they do and it works and when order latency is zero it doesn't (because they don't bootstrap the orders correctly).

@Mailaender I'm pretty sure we found out that you can just fix the replays by setting what it thinks is order latency to 1, so this should still be a cheap win in theory, but I don't have time to confirm. I appreciate that you took time to try and merge this and I'm sorry that it wasn't fully QA'd.

What I'd like to see happen is for the OpenRA team to commit to prioritising some improvements here for some release cycle so that any serious amount of work doesn't end up just sitting around gathering rust because it breaks something else or isn't completely stable and nobody wants to delete or fix that something else or playtest and iterate on it until it is. If I had time, I'd try and push on this harder.

**Comment by teinarss** [comment]
> 
> 
> @matjaeck don't worry, I'm not put off contributing, I think there's a lot to improve on this part of the code and I can at least help.
> 
> The contents of the PR were meant to be a "cheap win", but as has been sadly discovered, this part of the code is a bit too fragile for hasty changes. There is a lot of "hack this feature in" technical debt, the architecture has been incorrectly refactored multiple times with little to no documentation and there is basically no encapsulation left. It is nigh impossible to make assumptions about whether or not a change will be valid because other parts of the system do not behave in well-defined/documented and isolated ways (e.g. the behaviour of orders, replays, various aspects of the game loop). I can only guess or infer the thought processes behind each part, for example: there should be no reason for the replaying replays to care about order latency since orders are recorded _post_ latency, but they do and it works and when order latency is zero it doesn't (because they don't bootstrap the orders correctly).
> 
> @Mailaender I'm pretty sure we found out that you can just fix the replays by setting what it thinks is order latency to 1, so this should still be a cheap win in theory, but I don't have time to confirm. I appreciate that you took time to try and merge this and I'm sorry that it wasn't fully QA'd.
> 
> What I'd like to see happen is for the OpenRA team to commit to prioritising some improvements here for some release cycle so that any serious amount of work doesn't end up just sitting around gathering rust because it breaks something else or isn't completely stable and nobody wants to delete or fix that something else or playtest and iterate on it until it is. If I had time, I'd try and push on this harder.

No worries!  I agree with you on that we should commit on the improvements in these parts of the code. I did also failed to test the code, so its not only you and @Mailaender that missed these issues.

**Pull request merged**
