### PR TITLE
Replace nod07 music and fix codestyle

### PR DESCRIPTION
**Pull request by ghost**
- Change a variable from global to local
- Remove double white spaces
- Change the music from "In The Line of Fire" to "Just do it up", the right nod07 track

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by HenrytheSlav** [comment]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark: Thanks!

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c84a35981245013dd50c6cc9124ded4bd93b457f...7c659c07478ec3d39bdc631c29f3390e45a488b0)

**Pull request merged**
