### PR TITLE
Fix crash in SpreadDamageWarhead if range is >= 32c0

### PR DESCRIPTION
**Pull request by jrb0001**

### CODE REVIEW

**Comment by GraionDilach** [comment]
This doesn't really sit well with me considering that IIRC LengthSquared was calculated as long internally for a good while.

**Comment by pchote** [comment]
What are you using `int2` for that hits this limitation?

**Comment by jrb0001** [comment]
`SpreadDamageWarhead` crashes if the range is >=32c0 if I have calculated that correctly.

**Comment by GraionDilach** [comment]
@pchote For the record, he's using a SpreadDamageWarhead to affect the entire map and I find the idea horrible. We're already in a heated argument regarding this.

**Comment by pchote** [comment]
@jrb0001: `SpreadDamageWarhead` doesn't appear to use `int2`...?

**Comment by jrb0001** [comment]
@pchote `SpreadDamageWarhead` uses `RectangleHitshape` which uses `int2` iirc.

**Comment by pchote** [comment]
The real issue in that case is that `RectangleHitshape.DistanceFromEdge` is using `int2` to do calculations on`WVec`s.  A better fix would be to make it use `WVec` and `.HorizontalLength`.

`int2` is used for screen-space pixel coordinates where overflow is not an issue.

**Comment by jrb0001** [comment]
@pchote is this what you meant? It works although I don't understand why you want to keep broken code which doesn't even have any comment that you should only use it in specific cases..

**Comment by reaperrr** [comment]
I all likelyness this will fix #11502.

**Comment by pchote** [comment]
> @pchote is this what you meant?

Yes, thanks.

> I all likelyness this will fix #11502.

I concur.

**Review by GraionDilach — APPROVED** [review]
Looks good to me as well.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/00352b793d2f72a97e6460451ae377133bb7261b...1286ca863df7fd160d12439db4d0523b4292a075)

**Pull request merged**
