### PR TITLE
Add multi-resolution badge and icon support

### LINKED ISSUE #17675: External mod metadata should define 2x and 3x icons
This is another overlooked UI element for full HiDPI / scaling support.

### PR DESCRIPTION
**Pull request by pchote**
This PR adds the last missing piece in the UI scaling support: loading and rendering higher resolution badges. This ended up taking more work than I expected because #17581 didn't hit the right abstraction, so I had to rework some things in the first commit before the second commit could actually work.

Before:
Screenshot 2020-02-10 at 23 02 11

After:
Screenshot 2020-02-10 at 23 00 17

### CODE REVIEW

**Comment by pchote** [comment]
Updated (first push) and rebased (second).

This now also fixes #17675.

Before:


After:

**Comment by Mailaender** [comment]
Works fine:
image

I also like that the feature is optional.

**Review by Mailaender — DISMISSED** [review]

**Comment by pchote** [comment]
Rebased to pull in #17715 on bleed.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/897f423863a2eb64c4e6bf4076b8a515c464e44d...25a5cd7ed99b93485999c4007e1e8106c36ba3fe)

**Pull request merged**
