### PR TITLE
Add a lint pass for map format/author/title.

### PR DESCRIPTION
**Pull request by pchote**
Inspired by #9420 and others.  It doesn't make any sense for a map to not define a title or author, so this will flag the maps when they are uploaded to the resource center.

### CODE REVIEW

**Comment by obrakmann** [comment]
I think it would be worth checking Map.Type, too, just to see if it's set. If it's unset, it would never appear in the map chooser, possibly leading to confusion on the part of the mapper (not to mention players if it was uploaded to the resource site).

**Comment by pchote** [comment]
Good idea.  Updated.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/75a6c5dd902b19b0ecebfd03aa38bdcd03d43f3d)

**Pull request merged**
