### PR TITLE
Added random sprite sequence tick times

### PR DESCRIPTION
**Pull request by Mailaender**
as an example I made the Ornithopters not flap all at the same time.

### CODE REVIEW

**Comment by pchote** [comment]
This will complicate fixing #16557. Can you please elaborate on your motivations for this feature (I guess this is for OpenHV) so we can better consider the tradeoffs for/against it?

**Comment by Mailaender** [comment]
To avoid https://github.com/OpenHV/OpenHV/pull/399 flapping all at the same time.

**Comment by pchote** [comment]
Would keeping a constant tick rate but setting a randomized start frame solve the problem?

**Comment by Mailaender** [comment]
It would improve the look, but a random tick rate would be even more realistic. I think this does not even conflict with https://github.com/OpenRA/OpenRA/issues/16557. Dividing all ticks by 40 and rounding the result on a range or a single value shouldn't change the essence.

**Comment by PunkPun** [comment]
Needs a rebase

**Comment by Mailaender** [comment]
Rebased

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by pchote** [comment]
I expect this will introduce desyncs if used with sequences that impact gameplay timing (like harvester docking)!

**Pull request closed without merging**
