### PR TITLE
Remove helicopter RTB from command bar deploy description.

### LINKED ISSUE #14641: Orca and Apache aren't returning when you press F.
In the release version of OpenRA, if you select an Apache or Orca and press F, they return to a helipad to heal, although that isn't working in the current playtest version.

### PR DESCRIPTION
**Pull request by pchote**
This no longer functions, and does not make sense as a feature.  We do not have a dedicated "return and repair" hotkey for any units in any other mods, and it only worked in TD before now because of a hack that we have removed and do not want to restore.

If we really do want a "retreat to base" command then that would be best implemented as its own button/hotkey that works with all unit types.

Closes #14641.

### CODE REVIEW

**Comment by pchote** [comment]
We could possibly add #13975 to the milestone to compensate for this.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
@GraionDilach @abcdefg30 @penev92 would be nice to see this striked off the list this week-end so we can prepare for the next playtest.

**Comment by abcdefg30** [comment]
👍 the other issue noted on IRC will get an own ticket.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/f80644e2b70a28f804d4c2f4cec08f9c12cafca2...6fb8e985b8fdd6a112436d461f6023f2a266894a)

https://github.com/OpenRA/OpenRA/commit/adacbb1b9db15216d550b091fb3d7ffdb46bb629
https://github.com/OpenRA/OpenRA/commit/2b18c57b41eb9bbe89c3e546b042de83c7ab21ea

**Pull request merged**
