### PR TITLE
thirdparty/fetch-thirdparty-deps.sh: silence the nuget check

### PR DESCRIPTION
**Pull request by moviuro**
The check was printing lots of errors on archlinux: I silenced it.

### CODE REVIEW

**Comment by Mailaender** [comment]
Both cases still work. :white_check_mark:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/80d59f4777fcc2e291f4b2fe61875b62c6e719c9%5E...80d59f4777fcc2e291f4b2fe61875b62c6e719c9)

**Pull request merged**
