### PR TITLE
Fixed airdrop production crash

### PR DESCRIPTION
**Pull request by Unit158**

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Promises to fix #7312.

**Comment by penev92** [comment]
What happens if the building is destroyed/sold while the plane/space frigate is in-flight?

**Comment by Unit158** [comment]
It flies along like normal.

**Comment by Mailaender** [comment]
:+1: This is very likely to fix #7312 which crashed in line

```csharp
a.QueueActivity(new Land(Target.FromActor(self)));
```

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/87e25a4063f3b5d2ed7b2eccc5231ad317f032ec%5E...87e25a4063f3b5d2ed7b2eccc5231ad317f032ec)

**Comment by Phrohdoh** [comment]
[Updated changelog entry for verbosity.](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/87e25a4063f3b5d2ed7b2eccc5231ad317f032ec...15bed39120cf99ef4e1b42465a108b6352a980bb)

**Pull request merged**
