### PR TITLE
Added missile launch overlays for Dune 2000, Tiberian Sun and Tiberian Dawn

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/12537.

### CODE REVIEW

**Comment by ltem** [comment]
In the original game, if the palace is damaged the animation is skipped, so the rocket appears after the delay in the middle of the air. This isn't the case in this PR right now and the overlay looks quite off if the structure is damged. I would prefer the original solution (maybe the rocket could start further below, so that it won't pop in the middle of nowhere) but I don't know how complex it is to have two launch animations depending on the health.

**Comment by Mailaender** [comment]
> I don't know how complex it is to have two launch animations depending on the health.

Should be doable with `GrantConditionOnDamageState`.

**Comment by ltem** [comment]
@Mailaender yep, it works. 

The code is below and I changed the `MissileDelay:` to `19` because I think it fits better.

```yaml
	NukePower:
		Cursor: nuke
		Icon: deathhand
		PauseOnCondition: disabled
		Prerequisites: ~techlevel.superweapons, ~palace.nuke
		ChargeTime: 300
		Description: Death Hand
		LongDesc: Launches an atomic missile at a target location
		BeginChargeSpeechNotification: DeathHandMissilePrepping
		EndChargeSpeechNotification: DeathHandMissileReady
		MissileLaunchDetected: MissileLaunchDetected
		MissileWeapon: atomic
		MissileDelay: 19
		SpawnOffset: -512,1c171,0
		DisplayBeacon: True
		DisplayRadarPing: True
		CameraRange: 10c0
		ActivationSequence:
		ArrowSequence: arrow
		CircleSequence: circles
	WithNukeLaunchOverlay:
		RequiresCondition: !launchpad-damaged
	GrantConditionOnDamageState@LAUNCHPADDAMAGED:
		Condition: launchpad-damaged
		ValidDamageState: Medium, Heavy, Critical
```

Proof that the animation is skipped in D2K:

|launchanimationskipped|
|---|

**Comment by Mailaender** [comment]
Rebased and updated with your suggested changes.

**Comment by ltem** [comment]
With this [Video](https://youtu.be/gCJbIzh0E4E?t=1m32s) as reference I optimized the smoke offset of the Nod Temple to these values.

```yaml
	smoke: atomdoor
		Length: *
		Offset: -1,-47
```

After this change I would approve this PR for the yaml-side.

--------

Out of scope: The missiles in the `ra` and `cnc` mod are "in front" of the launch structures.  
It seems that they solved it in `ra` by adding a delay and poping the missile right above the silo ([Video](https://youtu.be/c3kJFQG5-z8?t=2m59s)). 
In `cnc` the missile has a spot in the launch smoke cloud and should be synced somehow (delay for the smoke animation). Manipulating the `ZOffset:` to `-2048` so that it travels behind the smoke only looks good for the start and makes the impact weird.

**Comment by pchote** [comment]
> Manipulating the `ZOffset:` to `-2048` so that it travels behind the smoke only looks good for the start and makes the impact weird.

This can be fixed by changing the `SpawnOffset`, giving it a negative Y and positive Z so that it launches further back but higher on the building (giving the same screen position as now).

**Comment by Mailaender** [comment]
Updated with your optimized smoke offsets.

**Comment by ltem** [comment]
So, after some struggles with the coordinates, I think I got the launch animation of the `Temple of Nod` and the `Missile Silo` into the right direction. Would be happy if you could add it as well.

|Temple of Nod|Missile Silo|
|:---:|:---:|
|launchtmpl|ra_launch|

```diff
diff --git a/mods/cnc/rules/structures.yaml b/mods/cnc/rules/structures.yaml
index 9009d41..10d8e24 100644
--- a/mods/cnc/rules/structures.yaml
+++ b/mods/cnc/rules/structures.yaml
@@ -716,8 +716,9 @@ TMPL:
                LaunchSpeechNotification: NuclearWeaponLaunched
                IncomingSpeechNotification: NuclearWarheadApproaching
                MissileWeapon: atomic
-               MissileDelay: 20
+               MissileDelay: 11
                DisplayBeacon: True
+               SpawnOffset: 3c0,0,-1c512
                BeaconPoster: atomic
                BeaconPosterPalette: beaconposter
                DisplayRadarPing: True
diff --git a/mods/ra/rules/structures.yaml b/mods/ra/rules/structures.yaml
index 63fa875..8a2fb8a 100644
--- a/mods/ra/rules/structures.yaml
+++ b/mods/ra/rules/structures.yaml
@@ -42,8 +42,8 @@ MSLO:
                InsufficientPowerSpeechNotification: InsufficientPower
                IncomingSpeechNotification: AbombLaunchDetected
                MissileWeapon: atomic
-               MissileDelay: 3
-               SpawnOffset: 0,427,0
+               MissileDelay: 5
+               SpawnOffset: 1c0,427,0
                DisplayTimerStances: Ally, Neutral, Enemy
                DisplayBeacon: True
                DisplayRadarPing: True
```

**Comment by Mailaender** [comment]
Added your latest patch for the missile spawn offsets.

**Review by ltem — APPROVED** [review]

**Comment by SoScared** [comment]
Harkonnen launch animation looks really good and the RA nuke missile spawns more naturally. Nod's Temple chimney spews its smoke from a slightly more naturally looking position.

**Review by SoScared — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3c1b6c014e15c46faa9444763d7ca5793f9f9fa3...554083db77cf94727b178f5821ceff745beeae09)

**Pull request merged**
