### PR TITLE
Fix palette effects on RA desert buildings/rocks

### LINKED ISSUE #15759: Desert rocks and buildings are blinking
Palette 'desert' should be added to RPE@desertwater and excluded from the LPR.
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/palettes.yaml#L107
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/palettes.yaml#L111
v21, v24 - water doesn't animate without RotationPaletteEffect.
v20, v29, rock3, rock5, rock6, rock7 = blinking from LightPaletteRotator.
blinking_desert

### LINKED ISSUE #16311: Water palette effect on desert civ buildings broken
It still (or again?) doesn't show the palette effect on civ buildings with a water source.

Should be an easy fix, so I'll put it on the milestone for next release.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #15759.
Fixes #16311.

### CODE REVIEW

**Review by pchote — APPROVED** [review]

**Comment by reaperrr** [comment]
@matjaeck Could you take a quick look at this?

**Comment by matjaeck** [comment]
Sorry, I don't know anything about palettes so can't help.

**Comment by reaperrr** [comment]
I meant can you test & confirm that it fixes the two issues I listed (without introducing new visible regressions)?

**Comment by matjaeck** [comment]
Ok, I take a look at it now.

**Review by ghost — APPROVED** [review]
Issues are fixed and I didn't spot anything strange.

**Comment by reaperrr** [comment]
Thanks!

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7016bbe67558b7c64a023f92f77701e103ac9559...8e2925e3f5248d7a27ec7a19d68ad71c5efd06d2

**Pull request merged**
