### PR TITLE
Reverse target line draw order.

### PR DESCRIPTION
**Pull request by pchote**
This implements a minor polish fix for the target lines.

Before:

After:

My implementation doesn't feel very elegant, but a cleaner solution wasn't obvious to my flight-addled brain. Suggestions welcome!

### CODE REVIEW

**Comment by teinarss** [comment]
> 
> 
> This implements a minor polish fix for the target lines.
> 
> Before:
> 
> 
> 
> After:
> 
> 
> 
> My implementation doesn't feel very elegant, but a cleaner solution wasn't obvious to my flight-addled brain. Suggestions welcome!

Dont think its worth to try finding a cleaner solution! :P

**Review by teinarss — DISMISSED** [review]

**Comment by abcdefg30** [comment]
Needs a rebase, though.

**Comment by pchote** [comment]
Rebased.

**Review by ghost — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e6862d0d39c0651d50770c2b0d9ce55ffb80a09f...ea275f3bfdf95da776e0c78fb1343be55bf80f3f)

**Pull request merged**
