### PR TITLE
Added a unit test for MPos conversions

### PR DESCRIPTION
**Pull request by Mailaender**
I was inspired by https://github.com/OpenRA/OpenRA/pull/7743#issuecomment-87038763 and astonished to hit a problem that quickly.

### CODE REVIEW

**Comment by abcdefg30** [comment]
This already needs a rebase?

**Comment by Mailaender** [comment]
Rebased and added an exception as there is currently no interest/need in fixing the problem.

**Comment by abcdefg30** [comment]
Needs a rebase again.

**Comment by Mailaender** [comment]
Placed it in the middle of the .csproj file so this annoying back and forth rebasing comes to an end.

**Comment by abcdefg30** [comment]
Looks good to me. :+1:

**Comment by Unit158** [comment]
:+1: test looks reasonable.

**Pull request merged**
