### PR TITLE
Prevent locked spawns from being selected by other players.

### LINKED ISSUE #10230: Lobby crash due to yaml-hardcoded teams / spawns
Game crashes in lobby under specific conditions. Attached picture explains how to reproduce the crash.

openra_crash_report

Note: should say "select another SLOT" under step 2.

Some clarifications: map has 4 slots, it defines the 1st slot to be team 1, spawn A and other slots to be team 2 with a chooseable spawn. I believe the bug happens because the game allows spawn A to be selected when slot 1 is unoccupied. When a player enters slot 1 and spawn A is already occupied, the game crashes.

I fixed the issue for now by hardcoding spawns so it doesn't keep crashing but should someone investigate this issue they can use this version of the map: http://resource.openra.net/maps/6611

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29139771-lobby-crash-due-to-yaml-hardcoded-teams-spawns?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #10230.

A future PR (which depends on the ongoing map format cleanups) will be able to hide these invalid spawns from the lobby GUI.  For now, the error message will have to do.

### CODE REVIEW

**Comment by pchote** [comment]
Here's a copy of the test map upgraded to format 8: https://www.dropbox.com/s/ym5cwvk0lh5179g/kanesinvasion_dev.oramap?dl=0

**Comment by obrakmann** [comment]
looks good to me, :+1:

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2fcc6b9bf04a29e34ff3ae654c8d1dede37105f6...82e7bfddc51d99ae33e0753d379b5058179b54db)

**Pull request merged**
