### PR TITLE
Add Buildings and Trees to Tiberian Sun

### PR DESCRIPTION
**Pull request by LipkeGu**
Converted with my rudimentary TS-Asset Converter... 

things are missing:
- Rocks (comes also later)
- Veins (hole is in trees.yaml and will be together with Rocks in misc.yaml later)

### CODE REVIEW

**Comment by LipkeGu** [comment]
Updated also my WIP VB converter to pay attention at ```Buildable:```

**Comment by Mailaender** [comment]
You could port it to C# and move the converter into OpenRA.Utility as I guess it will be helpful for a lot of other people (in a new pull request). That OpenRA uses different file formats is an often voiced complain from the modding community.

**Comment by Phrohdoh** [comment]
Following what Matt said you could try https://github.com/wbennett/DotNetTranslator or do a port by hand (which is often better and allows a more refined approach).

**Comment by LipkeGu** [comment]
I have the also Idea when anyone give me a function (where i can find the INI parsing function)

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/blob/master/OpenRA.Game/FileFormats/IniFile.cs

**Comment by LipkeGu** [comment]
i have begun but i dont know how to implement it to the Utility :(

https://github.com/LipkeGu/OpenRA/commit/71254a958b056a4a11bfdc1de3a5da6900d24273

**Comment by Mailaender** [comment]
Probably seek some inspiration from https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.TS/UtilityCommands/LegacyTilesetImporter.cs

**Comment by LipkeGu** [comment]
when i compile it, the command is not available :(

**Comment by Phrohdoh** [comment]
@LipkeGu when I get on IRC tonight I'll probably start working on something very similar to this (not quite the same approach), if you're interested in collaborating hop on or email me.

**Comment by obrakmann** [comment]
What I could see in the editor looked ok. YAML looks good as well. :+1:

**Pull request merged**
