### PR TITLE
Get rid of unit pathing delay completely

### PR DESCRIPTION
**Pull request by chrisforbes**
This was a fairly halfbaked idea. Let's get rid of it and then reintroduce a path request throttling system if we need to.

### CODE REVIEW

**Review by cjshmyr — APPROVED** [review]
Tested locally + online, didn't see any regression. Perf graph looked roughly the same spamming infantry scatter/move orders.

**Comment by drogoganor** [comment]
Nice one guys

**Comment by teinarss** [comment]
Works fine most of the time, getting some lag spikes when moving a large army over a large distance. I do think we should merge this and because it will improve the gameplay a lot (micro). And then add group pathfinding and other improvements that we have talked about.

**Comment by pchote** [comment]
A simpler way to avoid those lag spikes would be to keep a counter of "potentially long" pathfinds (e.g. not immediately rejected by the DomainIndex and longer than 10 cells) and have Move wait for a tick if a certain number has been reached in the current tick.

**Review by pchote — APPROVED** [review]
I'm not convinced that we aren't going to regret this, but lets give it a go.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ffe234b02c4f5d201e9b0163a465be0d6d3a9ab5

**Comment by Mailaender** [comment]
You can collect your bounty at https://www.bountysource.com/issues/335983-units-stop-whenever-they-get-a-new-move-order

**Pull request merged**
