### PR TITLE
Made projectile shadows heightmap-aware

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes projectile shadow position on higher terrain in TS.

### CODE REVIEW

**Comment by pchote** [comment]
Isn't this already covered by #8717?

**Comment by Unit158** [comment]
No, that only modifies missile.cs

**Comment by Mailaender** [comment]
Dune 2000 and Tiberian Sun artillery shell shadows are still looking properly. :white_check_mark:

**Comment by abcdefg30** [comment]
Looks also good to me. :+1: / :white_check_mark:

**Pull request merged**
