### PR TITLE
Update TD playtest maps

### PR DESCRIPTION
**Pull request by pchote**
This updates Axis of Advance, Order of Battle, and Vectors of Battle with the fixes from @Irnub in #12798.

I have left out Valley of Gold because having 1 fixed variant and 5 unfixed variants is less polished than having a matching set (but would happily include it if we can get the others to match).

### CODE REVIEW

**Comment by SoScared** [comment]
The new Order of Battle 8p is easier on the eye for sure. There's a 10 player version of Order for battle as well tho. ping @Irnub

Looks like the tib change plays into dynamics of map progression. Looks good from an overall RTS point of view regards to land grabbing.

**Review by obrakmann — COMMENTED** [review]
Vectors of Battle uses a lot of green trees from the temperate terrain on a desert map.  Do we want to keep that? IIRC, we've replaced those in the past with desert trees.

Looks otherwise ok, once the mpspawn ownership Travis complains about has been fixed.

**Comment by pchote** [comment]
Vectors of Battle uses those trees to hide tiling errors, which become visible when replacing them with the proper trees.  Fixing this will require heavier surgery than I can put in, so lets just remove it for now.

**Review by obrakmann — APPROVED** [review]
👍

**Review by reaperrr — APPROVED** [review]

**Comment by Irnub** [comment]
Re the Valley of Gold variants:

2P version:

http://resource.openra.net/maps/19939/

Revised from the earlier 2P version by Combine to remove the patterned tib and some further alterations to hopefully make the map more suitable for 1v1 play

4P version:

http://resource.openra.net/maps/19943/

Removed patterned tib, moved a few central tib trees further apart (so that they're just a touch more difficult to control through one base expansion) and some minor fixes to clipped cliff tiles

6P version:

Removed patterned tib, moved a few central tib trees further apart (so that they're just a touch more difficult to control through one base expansion) and some minor fixes to clipped cliff tiles

http://resource.openra.net/maps/19944/

The 2P version is quite different to the other larger versions now, but hopefully better balanced for a 1v1 game. The 'decoration' on the 4P and 6P versions do not match cell-for-cell but the differences are v. minor. 

I'll probably upload a last revision of the 8P map soon, maybe tomorrow. I'm not sure if I'll get to the larger ones. BLACK's versions have several clipping errors and should not be included in their current state. 

The 10P Order of Battle by BLACK really squishes the back two spawns together and punts off some tib trees to the sides.. It looks a bit off and to be honest I'd want to have a crack at re-doing the spawns more 'properly' if there's going to be a 10P version of this map included. I'm not sure if I'll get to that soon, but can do if there's a real call for this to be done.. Re SoScared's comment above, yeah the reduced tib should somewhat discourage v. early base expansions on this map which will probably improve it.

The map pool is def. a step forward and while I'd probably have some further thoughts I think it's looking a lot better :)

**Comment by Irnub** [comment]
Valley of Gold 8P update:

http://resource.openra.net/maps/19970/

Fixed some clipped cliffs and added a few misc. obstacles such as trees and rocks to the central area, mainly to make it look a bit better but partially also to add a bit of tactical interest and make it that little bit less suited to mass blobspam style play

**Pull request merged**
