### PR TITLE
Updated ExtractEmmyLuaAPI command to fix issues

### PR DESCRIPTION
**Pull request by penev92**
Spiritual successor of #19763.

Fixes the tons of warnings inside the generated Lua API file as well as adds several new things to fix warnings in our mission scripts.

Issues:
 - The generated API file caused a ton of diagnostics warnings.
 - Perhaps due to EmmyLua moving forward since the extract command was created, we were missing out on some features.

Changes:
 - Disabled diagnostics about missing return values for functions.
 - Added `add` and `sub` operator definitions because by default CPos+CVec would be assumed to return a number and assignments would cause warnings about type mismatches.
 - Added explicit `@enum` annotations. This also fixed warnings in the generated API file about missing types.
 - Changed default type of properties from an empty table to nil. This fixed warnings in the generated API file about type mismatch.
 - Renamed local variable "required" -> "requiredTraits" for readability.
 - Disabled duplicate function/property  name warnings
 - Updated trait docs URL.

Resources:
 - https://emmylua.github.io/annotation.html
 - https://github.com/sumneko/lua-language-server/wiki/Annotations

May or may not be relevant for `Next release`, not sure.

P.S.: To test install VSCode with the OpenRA Lua extension, open a mission and navigate to a base symbol. That should open
image
or similar, depending on your OS. There should be a bunch of warnings inside that file, as well as the mission scripts. Replacing the contents of the file with the new output of this utility command should fix all warnings inside `OpenRA.lua` as well as a ton of warnings from mission scripts.

### CODE REVIEW

**Comment by Mailaender** [comment]
I still get
image

**Comment by Mailaender** [comment]
You can probably fix another syntax problem by changing

https://github.com/OpenRA/OpenRA/blob/1dc44c4047cf24e0ed755dbd82f5518097cb9dbf/OpenRA.Mods.Common/UtilityCommands/ExtractEmmyLuaAPI.cs#L291

into 

```csharp
 { "String[]", "string|table" }, 
```

etc. to resolve the error when single values are entered.

**Comment by penev92** [comment]
👍  will look into those when I'm home, thanks.

**Comment by penev92** [comment]
> I still get

This is because `hpad` is a parameter of a local function, not a part of our Lua API, so the language server doesn't know its type. So as far as it knows, this is `unknown + cvec` (`hpad` is `unknown`, so `hpad.Location` is also `unknown`), which it somehow decides returns a `number`.
The only way I see to fix this is to add annotations:
```diff
end

+---@param hpad actor
InsertAlliedChinookReinforcements = function(entry, hpad)
	local units = Reinforcements.ReinforceWithTransport(allies, "tran",
		HelicopterUnitTypes, { entry.Location, hpad.Location + CVec.New(1, 2) }, { entry.Location })[2]
```

This fixes the warning and makes things overall much nicer, so I think we should be doing that everywhere in our mission scripts, but it definitely needs to have its own discussion and PR.

**Comment by penev92** [comment]
@Mailaender can you give me an example of a warning the `string[]` -> `string|table` thing fixes?

**Comment by Mailaender** [comment]
~~Try removing the brackets from `{ Rambo }`~~

https://github.com/OpenRA/OpenRA/blob/faf12f93a430609cc8cda0ce51712562266c6e40/mods/cnc/maps/nod10b/nod10b.lua#L32

~~There are also existing ones in the code base. You can spot them with the IDE.~~

**Comment by penev92** [comment]
I see. `string|table` means either a single string or a table. `table` is too generic and we can't type-check that (meaning I can put `{1, "Rambo", 3}` there). How about `string|string[]`?

*Now that I think about it, the function parameter is called `cargoTypes`. Why do we want to allow single values (not wrapped in an array/table)?*

**Comment by abcdefg30** [comment]
We don't allow single string values, it has to be a table with string elements.

**Comment by Mailaender** [comment]
Okay, ignore that. I am on a wrong track there. Only warning I get is this
image

**Comment by penev92** [comment]
>  Only warning I get is this

This is why I asked on Discord
> "is `cargoTypes = nil` legit?"
image

I still don't have an answer, but also have no idea how we can reasonably deal with it if it is legit, as then the door is open for potentially any parameter of nullable type to also have `nil` as a valid value in some case.

**Comment by Mailaender** [comment]
There is a safety check so it seems legit at least for this case.

https://github.com/OpenRA/OpenRA/blob/7cdc8c4ec52cf3814f75004e40dfeee4b209b081/OpenRA.Mods.Common/Scripting/Global/ReinforcementsGlobal.cs#L125

I guess we have to change `string[] cargoTypes = null` in

https://github.com/OpenRA/OpenRA/blob/7cdc8c4ec52cf3814f75004e40dfeee4b209b081/OpenRA.Mods.Common/Scripting/Global/ReinforcementsGlobal.cs#L118

to tell EmmyLua it is nullable.

**Comment by abcdefg30** [comment]
Can we use the syntax from https://github.com/OpenRA/OpenRA/pull/20609#issuecomment-1382738157 to do something like `String[]|nil` as type definition instead?

**Comment by penev92** [comment]
We can, but allowing `nil` is a slippery slope 😞 
(actually I need to see *how* we can do it, because there is nothing on the method signature that says "this is nullable, but none of the other string arrays aren't")

@Mailaender we can't because parameters with default values can't sit **before** parameters without default values and so we either need to reorder them (which is not going to end well) or we need to give them all default values.

**Comment by abcdefg30** [comment]
> We can, but allowing `nil` is a slippery slope 😞

Why? `string[]` can be `null` in C# as well and this is used as a valid value to indicate that the transport should not have passengers. (Although one can argue that this use-case should be utilizing ReinforceWithTransport then.)

**Comment by penev92** [comment]
Yes, that would be technically correct, but in reality I expect a null value to be valid for this specific parameter of this specific function to be an exception rather than the rule. But anyway, I will look into it later.

**Comment by penev92** [comment]
I see no way to tell the export command that this particular `string[]` can be `nil` and no other array can, so the way I see it we can either:
1. Do that manually after generation - simplest option.
2. Figure out a way to mark this specific parameter (`cargoTypes` on `Reinforcements.ReinforceWithTransport()`) as exclusively nullable, unlike all other arrays - this would likely be more trouble than it's worth.
3. Allow all arrays in the API documentations to be nullable - I am against this as this one parameter seems to be an exception rather than the rule and if we do that we'll have misleading documentation.
4. Change the mission scripts to pass an empty array instead of `nil` to hide the issue - there will be no more warnings, but the documentation will keep not telling people they actually *can* use `nil` (but why would they?).

Personally I vote for 1. with 4. being my fallback option.

**Comment by Mailaender** [comment]
Let's avoid manual touchups. I vote for 4 or live with it.

**Comment by abcdefg30** [comment]
Changing the scripts from a valid input just to avoid warnings doesn't seem like an ideal solution. Instead we should throw exceptions where necessary. The example of `Reinforcements.ReinforceWithTransport` won't work with an empty array instead of nil/null for the path either. I don't know if there is anything to be done here really.

**Review by Mailaender — DISMISSED** [review]

**Comment by penev92** [comment]
I need to add the latest add() and sub() operator definitions.

**Comment by penev92** [comment]
Updated with the extra `add` and `sub` operators and rebased.

**Comment by penev92** [comment]
Rebased due to conflicts with code style rule changes.

**Comment by penev92** [comment]
FWIW this has actually been "in production" for a while now.

**Comment by anvilvapre** [comment]
> ```diff
> +---@param hpad actor
> ```
> 

i feel a typescript coming ;  )

**Review by RoosterDragon — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a3e05a05298c20c479a51bec2a07f7305f99f942...4ef2669084754359d9ae2366b9dae7218a5a829a)

**Pull request merged**
