### PR TITLE
Fix the extraction helicopter not showing up in Monster Tank Madness

### LINKED ISSUE #13068: The helicopter not appear when Dr.Demitri rescued in RA Monster Tank Madness playtest20170304.
In the RedAlert mod, solo mission: Monster Tank Madness
All The primary and secondary mission done, but the helicopter never arrive, the bug also in bleed branch.

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #13068.

It had something to do with the spawnpoint lying outside the map bounds (#12458 ?).
Further fixes:
- Intial cash is set to 0 in rules.yaml (otherwise it would start with 5000 and tick down to 0 as the game starts).
- Fixed the explosions of the civilian buildings. They spawned infantry (which looked weird) and all other civilian buildings on the map had wrong explosions.
- On that note: The mod rules let Oil Pumps spawn infantry as well (in addition to the normal husk), which looks kind of weird as well, imho.
- Removed a misplaced barrel, which looked glitchy:
mtmbarrel

### CODE REVIEW

**Comment by reaperrr** [comment]
I haven't had time to test this yet and probably won't tomorrow, either, but all fixes look sensible. If push comes to shove, you can count this as +1 if needed to get the playtest out this weekend.
Would be better if this was tested by 2 reviewers, of course.

**Comment by reaperrr** [comment]
Uhm... I just tried to test this, but I got attacked by one of these super tanks so early on I had no chance to rescue Dr. Demitri... is it supposed to be like this?

**Comment by obrakmann** [comment]
The fixes look fine to me, but I found another issue: The tanks don't reveal shroud anymore.
screenshot from 2017-04-08 16-01-17

**Comment by obrakmann** [comment]
Fix:
```diff
diff --git a/mods/ra/maps/monster-tank-madness/monster-tank-madness.lua b/mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
index 24cbec8..5813bca 100644
--- a/mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
+++ b/mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
@@ -131,6 +131,7 @@ SuperTankDomeInfiltrated = function()
        SuperTankAttack = true
        Utils.Do(SuperTanks, function(tnk)
                tnk.Owner = friendlyMadTanks
+               tnk.GrantCondition("friendly")
                if not tnk.IsDead then
                        Trigger.ClearAll(tnk)
                        tnk.Stop()
diff --git a/mods/ra/maps/monster-tank-madness/rules.yaml b/mods/ra/maps/monster-tank-madness/rules.yaml
index 6345be5..be3d57e 100644
--- a/mods/ra/maps/monster-tank-madness/rules.yaml
+++ b/mods/ra/maps/monster-tank-madness/rules.yaml
@@ -64,6 +64,13 @@ PBOX:
                Crushes: wall, mine, crate, infantry
        RevealsShroud:
                Range: 6c0
+               RequiresCondition: !friendly
+       RevealsShroud@friendly:
+               Range: 6c0
+               RequiresCondition: friendly
+               ValidStances: Ally, Enemy
+       ExternalCondition@revealsshroud:
+               Condition: friendly
        Turreted:
                TurnSpeed: 1
        Armament@PRIMARY:

```

**Review by obrakmann — APPROVED** [review]
👍

**Review by pchote — APPROVED** [review]
Fixes confirmed :+1:

I have added an extra commit that sets the super tank turret facings to polish the intro a little more.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/65ead1204805cbefc8831eb8ea2651e991e2c958)

**Comment by abcdefg30** [comment]
Thanks for the further polish.

**Pull request merged**
