### PR TITLE
Fixed ClientInSlot: Sequence contains more than one matching element

### LINKED ISSUE #18496: lobby crash
i was not the admin

OpenRA engine version release-20200503
Red Alert mod version release-20200503
Date: 2020-08-06 21:48:48Z
Operating System: Linux (Unix 4.15.0.112)
Runtime Version: Mono 6.10.0.104 (tarball Fri Jun 26 19:38:24 UTC 2020) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <a63e4875bcd94dc2960d31c0cf2bbd30>:0
  at OpenRA.Network.Session.ClientInSlot (System.String slot) [0x0000d] in OpenRA.Game/Network/Session.cs:94
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () [0x00108] in OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs:580

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/18496.

### CODE REVIEW

**Comment by pchote** [comment]
Doing this client-side will mean that the server and client state will be out of sync. I would be surprised if this doesn't cause further issues.

We really need to fix this on the server side, wherever the problem is being actually created.

**Comment by Mailaender** [comment]
It seems there is already a check in place server side:
https://github.com/OpenRA/OpenRA/blob/9cf38c178420467af333b45569828bd8f58e267e/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs#L177-L178

**Comment by Mailaender** [comment]
I suspect the proper solution may to be resolve this
https://github.com/OpenRA/OpenRA/blob/06a1c88e86ed4205acd50af5a96f201c44ebe352/OpenRA.Game/Server/Server.cs#L940-L941

**Comment by pchote** [comment]
That TODO would reduce the amount of redundant data sent, but will change nothing regarding the bogus state. If that check really works then this could potentially be caused by the same race condition as #18253, and may be similarly fixed by adding the required locks.

**Pull request closed without merging**
