### PR TITLE
Removed bounties from D2k

### PR DESCRIPTION
**Pull request by reaperrr**

### CODE REVIEW

**Comment by Unit158** [comment]
:+1:

**Comment by Unit158** [comment]
By posting here with a :-1: and causing the same stuff that happened with #8162, you waive the right to not get beat with a roughly cylindrical stick no longer than one meter and with a radius no larger than an inch.

**Comment by penev92** [comment]
Ignoring the comment above, which, despite its playful tone, has no place on GitHub, I guess if we're aiming for a "full" recreation that would be attractive to the original game's fans, bounties should go.
At the very least until the dusts settles from all the other rebalancing.
:+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/f2353d79b565531dd4f64fe62fb08609fff09514...9bdd9ae22e0a5d43cda0d256ebde839441202aa9)

**Pull request merged**
