### PR TITLE
Add Tiberian Dawn Nod Campaign 10a

### PR DESCRIPTION
**Pull request by dtluna**
Add the 10a mission a.k.a. ["Terminate Doctor Wong"](http://cnc.wikia.com/wiki/Terminate_Doctor_Wong) for the Tiberian Dawn Nod campaign.

[Playthrough of the original mission](https://www.youtube.com/watch?v=U99GcDc6Hko)

This mission is a little bit different from the original:
1.  the Transport Helicopter comes in when you actually discover the Tech Center
1.  it comes from the side where your forces were originally spawned, not from the upper right as in the original

**Important note**: there is nothing in the docs on the `EnemyWatcher` trait and `OnDiscover` Lua trigger about the `AnnounceOnSeen` trait [being required](https://github.com/OpenRA/OpenRA/pull/15870/files#diff-6809888b825fe864a470a3659b5e71d6R35).

### CODE REVIEW

**Comment by Muh-Muh** [comment]
Woohoo, more campaign :)

I found a couple of minor things,

(1) the map preview is not aligned correctly.
(2) You can cause a lua exception if you kill the R&D-center before revealing it. (Repro-case: use the visibility cheat and fire with the artilleries from the south; In principle this is of course also possible without cheating, but you would have to remember where to shoot.)
(3) In general I feel like the artilleries are too powerful here. I believe (also I didn't make sure) they had much less range in the original. Point in case: you can kill the R&D basically from the starting location. The helicopter also serves little purpose since your artilleries will do all the killing anyway. I tentatively suggest changing the artillery for another unit with less range. That might make it less true to the original but more fun to play.

**Comment by dtluna** [comment]
@Muh-Muh I've addressed your requests 2) and 3), but I don't know how to make the preview aligned correctly. I followed the guide in the wiki, but it seems I did something wrong. Can you help me with that?

**Comment by dtluna** [comment]
@Muh-Muh I replaced artillery with flame tanks, removed the "Locate R&D Center" objective and realigned the map preview. Please review once again :)

**Comment by Muh-Muh** [comment]
@dtluna The image is still aligned differently than all the other maps. I tried to do it myself but mine also looks misaligned ^_°.

I can't get this to crash anymore and as far as I can tell it plays as it should. I have two more suggestions.

(1) Perhaps you could add a  lose-condition: all infantry killed before the helicopter arrives. That happened to me while I was playing around.

(2) I feel this mission is still a bit easy. I think on normal and hard (or at least on hard) the player should start with less units. But for the exact balancing it would be best if someone else who knows more about that could chime in

**Comment by dtluna** [comment]
@Muh-Muh This mission was easy in the original campaign as well, to be honest.

**Comment by pchote** [comment]
IMO it would be better to focus on the technical issues or game-breaking balance issues now, but defer general difficulty-level tweaks to a followup - better to merge something that is too easy than to merge nothing at all.

**Comment by obrakmann** [comment]
There's a tiling error on this map which leads OpenRA to believe that there's a bridge where there isn't one: https://i.imgur.com/7oKA33b.png

https://seacloud.cc/thumbnail/5d1adbebce/1024/Screenshot%20from%202018-12-19%2023-20-21.png

Can you please replace that single tile with a normal desert tile?

**Comment by dtluna** [comment]
@obrakmann Yes, sure

**Review by obrakmann — COMMENTED** [review]
:+1: This works well enough for my taste, unless @dtluna wants to use his newly-learned powers to add more to this :)

**Comment by reaperrr** [comment]
Works and plays fine, only some really minor things left:

- One of the northern oil derricks in front of the GDI base is GDI-owned, which looks a bit weird (might have been carried over from original, but there it would have been unnoticable since Neutral used GDI colors). Please either make that one neutral as well, or make all of them GDI.
- The two(?) minigunners below that oil field are on the same sub-cell.
- The map image in the selection screen is still a bit horizontally misaligned, too far to the left (vertically it's fine).

**Comment by dtluna** [comment]
@reaperrr The minigunner and neutral structure issues are definitely fixed and the map preview is probably fixed too (I tried aligning it, but I'm not sure I did it correctly).

**Comment by reaperrr** [comment]
The alignment was better, but not perfect yet, and there were some strange gaps in der green borders that the other previews didn't have.

Fixed with GIMP and pushed it over.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b7e0de6103b050c8949540146624b9e488e7ea98...644d1e0852e5e51352e5d039263626f43a31c18c)

**Pull request merged**
