### PR TITLE
Implement Building/UnitDelays and make D2k AI wait to upgrade ConYard

### LINKED ISSUE #16087: AI Production Time Limit
Remembered while trying to rebease the Generals Alpha engine, i had time limits for AI per queue (tho per actor can be a better way to implement this) to prevent the AI from wasting their early cash to build a second dozer, mines or upgrading their Cold Fusion Reactors.

Should be pretty easy to move it to upstream, but i don't see much of a use for it in main mods, so i dunno if it would be adding useless checks to the AI code. So wanted to create an issue instead of a PR.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Closes #16087

### CODE REVIEW

**Comment by reaperrr** [comment]
I guess we could take this first, but I think it would be more ideal to do #16180 first (at least the refactor of BuildingFractions/Limits) and make this another sub-property.
Pinging @pchote for opinion.

**Comment by abcdefg30** [comment]
> Pinging @pchote for opinion.

**Review by abcdefg30 — COMMENTED** [review]
Code changes look good however. :+1:

**Comment by pchote** [comment]
>  I think it would be more ideal to do #16180 first

I agree that it would be better to wait, but I don't think we have any PRs for that in the pipeline so I don't think its worthwhile holding up this relatively simple PR for it.

**Review by abcdefg30 — APPROVED** [review]
Looks good to me. Note that priority overwrites (power, refineries) are not affected by this.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1dad10e1c83f9ad9a6b6a73101d153f796b0526b...4a34cf09216ca5e809598ed8273e38f3a7d23021

**Pull request merged**
