### PR TITLE
Removed bogus traits from ra FLARE

### PR DESCRIPTION
**Pull request by abcdefg30**
As detected in #8123 (https://github.com/OpenRA/OpenRA/pull/8123#discussion_r30552625, https://github.com/OpenRA/OpenRA/pull/8123#discussion_r30552929).

### CODE REVIEW

**Comment by Phrohdoh** [comment]
:+1:

**Comment by penev92** [comment]
Please check if the flare really needs `BodyOrientation`.

**Comment by obrakmann** [comment]
Looks like `BodyOrientation` isn't needed. And either the `Tooltip` needs to go, or `Selectable` needs to be added.

I'm scope-creeping now, but could you change the crate definitions as well, while you're at it? Filed https://github.com/abcdefg30/OpenRA/pull/4 against your branch. Thanks!

**Comment by abcdefg30** [comment]
Merged your changes.

**Comment by obrakmann** [comment]
Thanks. We still need to decide whether to remove Tooltip from the flare or add Selectable to it. I'd vote for adding Selectable, but I don't know what Bounds should be set to.

**Comment by abcdefg30** [comment]
Added a tooltip (by adding `Selectable`).

**Comment by Mailaender** [comment]
Thanks.

**Comment by Mailaender** [comment]
No regression on all 4 mods. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ba057fd6a9f5ef8a130d4811be7500a787a62a74...1424c9ab32899a6ebf848dd092f83fbf56af69ee)

**Pull request merged**
