### PR TITLE
Modified the text inside "Install Required" dialogs to be consistent across all mods

### LINKED ISSUE #7389: TD "Install Game Content" dialog incorrectly states music cannot be downloaded
playtest: 20150118 / win32

TD "Install Game Content" dialog incorrectly states music cannot be downloaded but has to be installed from original media when it has been possible to download it easily from within openra for some time now

edit: I realized after submitting that the text means that music will not be downloaded using this dialog, however it may be worthwhile to point out the music can be easily downloaded later

tdmusic

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8075953-td-install-game-content-dialog-incorrectly-states-music-cannot-be-downloaded?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by suvjunmd**
Fixes #7389.
### Install Required

Before:
td install before
d2k install before
After:
td install after
d2k install after
ra install
ts install
### Installing from CD

Before:
td cd before
d2k cd before
ra cd before
ts cd before
After:
td cd after
d2k cd after
ra cd after
ts cd after
### Downloading Content

Before:
td download before
After:
td download after
d2k download
ra download
ts donwload

### CODE REVIEW

**Comment by penev92** [comment]
Hm. RA, D2k and TS all share the same UI (for the most part), so they are pretty much identical.
TD however has it's own UI with a quite different style (absolutely intended), and that is perfectly fine. You can find such discrepencies in every aspect of TD's UI.

While I'm all for consistency, this is intentional, and it was done to set the mods apart. Might be even better to have unique styles for D2k and TS (which now inherit RA's UI), again to highlight that they are their own mods and not just copies of RA.

**Comment by pchote** [comment]
Note that TD follows the convention that buttons that take you "forward" are positioned on the right, and back are on the left. Changing the installer button layout therefore makes things *less* consistent.

**Comment by suvjunmd** [comment]
I will return the buttons to their original positions. What do you think about the modified text ?

**Comment by penev92** [comment]
I'm OK with the text, but I'm pretty sure Dune 2000 had only one CD.

**Comment by suvjunmd** [comment]
Updated

**Comment by penev92** [comment]
Looks good :+1: 
But since we're polishing stuff, you might want to move the header labels on the TD dialog a few pixels lower, because these screens show them way too high.

**Comment by suvjunmd** [comment]
How about this ?

**Comment by obrakmann** [comment]
Looks fine. :+1:

**Comment by GraionDilach** [comment]
This was already your second contribution. You should add yourself to AUTHORS.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/a722a2508f9f871aaab457e26bbf9f70684635ca%5E...a722a2508f9f871aaab457e26bbf9f70684635ca)

**Comment by suvjunmd** [comment]
> This was already your second contribution. You should add yourself to AUTHORS.

Thanks for letting me know :wink:

**Pull request merged**
