### PR TITLE
use appimagetool with non-glibc linux support

### PR DESCRIPTION
**Pull request by Drsheppard01**
use appimagetool with non-glibc linux support

### CODE REVIEW

**Comment by pchote** [comment]
From https://github.com/AppImage/appimagetool:
> Unlike previous versions of this tool provided in the [AppImageKit](https://github.com/AppImage/AppImageKit/) repository, this version downloads the latest AppImage runtime (which will become part of the AppImage) from https://github.com/AppImage/type2-runtime/releases.

and from https://github.com/AppImage/type2-runtime:
> This repository builds a statically linked runtime for type-2 AppImages in a [Alpine Linux](https://alpinelinux.org/) chroot with [musl libc](https://www.musl-libc.org/).
>
> Since the runtime is linked statically, libfuse2 is no longer required on the target system.

This is an important fix that allows our AppImages to finally again run by default (without requiring the user to know to install `libfuse2` first) on modern distros. I have confirmed locally that this is indeed the case on a fresh x86_64 Ubuntu 24.04.

**Review by pchote — COMMENTED** [review]
Can you please also remove this now redundant line from the Linux packaging?
https://github.com/OpenRA/OpenRA/blob/bleed/.github/workflows/packaging.yml#L56

**Comment by Drsheppard01** [comment]
Thanks Paul for quickly reply! I remove this line from packaging.yml

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6ba918dc1f5d5adcffbc4d3267380e2001e727b2

**Pull request merged**
