### PR TITLE
Fixed enemy missiles not being deflected by Radar Jammers

### LINKED ISSUE #11977: Mobile radar jammer doesn't block missiles [playtest-20160904]
Reported in IRC by framelimiter: "The mobile radar jammer doesn't appear to block missiles in the playtest(20160904)"

### PR DESCRIPTION
**Pull request by abc013**
I'm really sorry about that :(.

Fixes #11977

### CODE REVIEW

**Comment by obrakmann** [comment]
No worries, happens to everyone. :+1:

**Comment by Phrohdoh** [comment]
👍

**Comment by GraionDilach** [comment]
@abcdefg30 Don't forget to merge this into stable as well!

**Comment by abcdefg30** [comment]
Give me time for the [changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/bfadd1bd19c2ff7f68c49bffca520445d256bd38...8107ecc01e42a792b4e230ac7f7fe67a765f4e69) first. :D

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/commit/fcab4e9eedc833e78887a5a620c2b4af6ad81152

**Pull request merged**
