### PR TITLE
Rebalance man-to-man.oramap for the RA mod

### PR DESCRIPTION
**Pull request by ghost**
In relation to #10298

map on resource centre http://resource.openra.net/maps/8269/ (parsed on bleed...)

Original
m1

Rabalanced
m2

### CODE REVIEW

**Comment by r34ch** [comment]
-Oil derricks on islands gave allies a massive economy advantage with a single chinook and engi. Now two derricks are situated in the middle which should encourage early skirmishes. The out of place gems have been replaced by the other two derricks

-Islands have been turned into flanking attack paths. Water corners still allow for flanking air attacks. Middle oil derricks can be destroyed from paths with artillery units. Expansions to the middle are now more vulnerable due to the flanking paths. Only one ore mine remains in the middle to lessen the advantage of taking it.

**Comment by Mailaender** [comment]
Can't spot tiling errors. :white_check_mark: Water tiles are a bit repetitive wallpaper like in the top right lake.

**Comment by r34ch** [comment]
Gave all the water tiles another pass. Added a little more terrain decoration in the top right.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/c05ec05f8d01e069a1ea819b4ad597760d99224a)

**Pull request merged**
