### PR TITLE
Prepare TD and content installer chrome for fractional DPI/UI scaling

### PR DESCRIPTION
**Pull request by pchote**
The most important requirement for fractional DPI / user-controlled UI sizes is to be able to render the UI artwork with bilinear interpolation. Bilinear interpolation works by taking an average of 2x2 pixels, weighted based on exactly where the screen pixel falls relative to the texture pixels. This has an unavoidable consequence that (screen) pixels at edge of a mapped region will generally be contaminated by whatever (texture) pixels are immediately outside the mapped region.

To avoid ugly visual artifacts we must ensure:
 * regions that will be tiled must be surrounded by pixels of the same color as the opposing side
 * regions that are the edge of something must be surrounded by transparent pixels

This PR adjusts the TD and content installer chrome layout to obey these rules - these are the two easy cases because they are based on SVG sources. This also adds 2x and 3x versions, which will be enabled in one of the next PRs.

Depends on #17489.
Artwork source are PRed in: https://github.com/OpenRA/ArtSrc/pull/8.

In addition to testing mods on the PR branch (which should be done to verify correctness ingame), I suggest checking out https://github.com/pchote/OpenRA/tree/render-wip and running the `--debug-chrome-regions` utility command. This will generate a web page you can open to view the `chrome.yaml` regions. This makes it easy to verify that all of the regions are mapped correctly. If you enable your browser's web console, mousing over a region will print its name to the console log.

The `render-wip` branch also includes prototypes for the remaining work towards #10382. It may be useful to try that branch (or ask questions about it) to get the wider context. Beware that the changes there are still rough and maybe buggy.

### CODE REVIEW

**Comment by dragunoff** [comment]
I did a quick test - things looks good. Only the loading bars are a little off:
изображение

**Comment by pchote** [comment]
I can't reproduce that - are you sure you compiled first? The hardcoded rectangles in the load screen class have changed.

**Comment by dragunoff** [comment]
Derp. Sorry. Ignore that. Everything looks good.

**Comment by pchote** [comment]
Rebased.

**Review by dragunoff — DISMISSED** [review]
Everything looks good in-game. Code and asset changes look good.

@pchote However I highly recommend that we stick to a grid for the chrome sprites (at least for the icons). I think that makes it way easier to think about the sprite-sheet, to add new icons, to calculate coordinates. What do you think about splitting the icons into their own glyphs.svg file (like you did for the other mods) **in a potential future PR**?

**Comment by pchote** [comment]
I'm not sure what you mean - the glyphs are still in a grid, the grid spacing just happens to be 17px so we can get the 1px margin required to avoid bleeding?

**Comment by dragunoff** [comment]
I had established a grid for the whole document (a gridline every 8 pixels) and took the care to add invisible bounding boxes to icons so they are all of equal size (16px and 24px). That way the icons and all other assets were aligned to the grid. Having the icons follow their own grids (17px and 25px) makes it harder to move things around (by grid snapping) and to reason about the sprite as a whole:
изображение

**Comment by pchote** [comment]
I see. I'd prefer that we stick to a single image because this makes it easier to keep track of the different resolution versions, and reduces wasted texture space (which is even more important with the 3x scaling forcing us to round up to the next power of 2).

We could define a convention that icon margins should be on the bottom-right, and update the bounding boxes for the icons.

**Comment by dragunoff** [comment]
> We could define a convention that icon margins should be on the bottom-right, and update the bounding boxes for the icons.
>
Having the margin always on the same side is a good convention. Though I don't think we should change the bounding boxes - the boxes represent the size of the icon and the 1px margin is outside of the icon itself. We could define more grids in the SVG document (for the small icons, for the large icons, etc.). This is not a blocker at this point, I will think about it more. We can implement it when the time comes for the next refactor of the sprite.

**Comment by pchote** [comment]
Rebased and updated with a glyph for #17549.

**Comment by pchote** [comment]
I haven't heard of any further issues in release-20191117 backport build that I shared on IRC and Discord. It would be good if we can get progress moving on this and #17495 again.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7046a6c7637800f14a85bb577b22d5b8dc8a8869...37102e9cd030a7f1e7a87f27df06b3ac66da034d

**Pull request merged**
