### PR TITLE
Add GPS icons for oil derricks, hospitals and biolabs

### PR DESCRIPTION
**Pull request by abc013**
During a game I noticed that hospitals and oil derricks aren't shown if you have GPS.
I added an hospital and an oil derrick icon to fix this.
Hospital:
openra-2016-08-26t120349331z

Oil Derrick:
openra-2016-08-26t112543636z

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by obrakmann** [comment]
Can you do one for the biolab as well? Maybe just a biohazard sign?

**Comment by abc013** [comment]
@obrakmann, i tried, but a biohazard sign would be to imprecise in this shp size.
openra-2016-08-26t144114772z

I created another Image:
openra-2016-08-26t145611790z

Is this ok?

**Comment by abc013** [comment]
Added the new Symbol.

**Comment by obrakmann** [comment]
Works for me, :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/323f207cc2356412e668b6635a8baea2b09137dc)

**Pull request merged**
