### PR TITLE
Added the windmill to the Red Alert civilian buildings

### PR DESCRIPTION
**Pull request by Mailaender**
Complementing https://github.com/OpenRA/OpenRA/pull/7923

Windmill

Thanks to @MicroJOo for fixing the SHP.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Why are you removing @penev92 from AUTHORS?

**Comment by Mailaender** [comment]
That was an accident.

**Comment by pchote** [comment]
```
paul@MacBook-Air:OpenRA+pr/7924$ mono OpenRA.Utility.exe ra --check-sequence-sprites
Tileset: Snow
	File not found: windmill.shp
	File not found: windmill.shp
Tileset: Interior
	File not found: windmill.shp
	File not found: windmill.shp
Tileset: Temperate
	File not found: windmill.shp
	File not found: windmill.shp
Tileset: Desert
	File not found: windmill.shp
	File not found: windmill.shp
```

**Comment by Mailaender** [comment]
Already fixed.

**Comment by MicroJOo** [comment]
:+1: 
some

**Comment by abcdefg30** [comment]
Looks good to me and works ingame. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
But needs a rebase.

**Comment by Mailaender** [comment]
Rebased (this was ugly).

**Comment by abcdefg30** [comment]
Looks still good to me.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fe3cf4a2386c9caef0e042e4f233998bdc89c289...6097924ac745e70b211333e2e9cbb15dc4c84cb6)

**Comment by TheRaffy** [comment]
nice job! I guess alot small islands will get now an additional lighthouse!

**Pull request merged**
