### PR TITLE
Yoga layout

### PR DESCRIPTION
**Pull request by IceReaper**
For an example what exactly Yoga is, and how it works, see: https://yogalayout.com/
Basically all old Bounds stuff is completely replaced by a proper layout engine, which supports basics like margins, borders, padding and min/max and preferred width/height attributes.

**Whats missing:**
- The yoga dlls!
They are currently build by hand under Ubuntu 19.04 by building the official repository version.
[Yoga.zip](https://github.com/OpenRA/OpenRA/files/3414729/Yoga.zip)
And here are the sources (which are un-editied variants from their latest release) along with the makefile i added to build the native binary (did not want to install their whole build environment)
[Facebook.Yoga.zip](https://github.com/OpenRA/OpenRA/files/3438585/Facebook.Yoga.zip)

**Whats not part of this PR:**
- Refactoring of all the chrome yaml files to make use of the flex layouting.

**Features i want to add in the future:**
- addition of more css styles for gradients, shadows, border images, etc.
- support for auto layouting of nine-patches for borders
- Implementation of "classes" which can be used to group the style of widgets
- rewrite all the uis to make use of the flex layout

### CODE REVIEW

**Comment by pchote** [comment]
Why is the `*` &rarr; `Classic*` rename needed? Does `YogaNode` already implement these? If so, why can't our legacy layout code be changed to use those values (with transformations if needed) when evaluating the bounds?

**Comment by IceReaper** [comment]
The core idea is to remove the classic behavior in the future. The whole evaluation of PARENT_RIGHT etc has to be removed (as the yoga layout supports this anyway, just differently).
First yoga has Width and Height props, however i think its way cleaner to make use of the layouting system properly when using those, moving the custom calculation stuff into different props to make clear you are using an old feature here. X and Y are ofcourse not part of yoga, as it has Left,Right,Top,Bottom, however as they belong to the same concept of above, i renamed those too.
Basicaly you can use the proper flex layouting system which yoga provides, or the "classic" one, which may hopefully be removed in the future.

**Comment by pchote** [comment]
Summarising my thoughts from Discord: I think the best (and, to be honest, probably the only realstic) way forward with this is to have this first PR implement a shim / wrapper around Yoga so that we can focus on the way it works instead of being drowned out by 15k lines of yaml and ChromeLogic renames.

For example, instead of replacing `w.Bounds.Width` &rarr; `(int)widget.LayoutWidth`, `w.Bounds.X` &rarr; `(int)label.LayoutX`, and so in all of the chrome logic classes we could change `Widget.Bounds` to a new `YogaBoundsBridge` class that defines properties `int X { get { return (int)LayoutX; } }`, `int Width { get { return (int)LayoutWidth; } }` and so on. 

Something similar can hopefully done with the yaml interface so that the current definitions remain compatible unless we/modders explicitly opt in to Yoga-powered flex or absolute positioning.

**Comment by IceReaper** [comment]
Ill redo the implementation from scratch to avoid the need to merge all the new stuff.

**Comment by pchote** [comment]
Activity is slowly progressing on this behind the scenes (the focus so far has been on migrating to .NET core and sorting out a toolchain to compile native Yoga binaries), but it will likely take a while longer before this can be updated for a serious rereview.

Closing for now to help clean up the PR queue.

**Pull request closed without merging**
