### PR TITLE
Split maps into system and custom maps in the map chooser

### PR DESCRIPTION
**Pull request by obrakmann**
Additional changes:
- non-hosts are allowed to view the map chooser (but not to change the map, obviously)
- Deleting one or all custom maps is possible (needs testing if it works under Windows)

### CODE REVIEW

**Comment by Mailaender** [comment]
Works as promised. Tested deleting one and all custom maps. :white_check_mark: This is a nice addition to the in-game map editor. :+1:

**Comment by penev92** [comment]
Deleting maps works well under Windows, but:
1. The map counter (at the upper right corner) does not get updated when doing so.  (*bug*)
2. When you delete all custom maps, the "Custom maps" tab disappears, but you have to manually switch to the "Official maps" tab. Until then you are left with a blank screen.  (*polish*)

**Comment by obrakmann** [comment]
Updated. Fixed both mentioned issues, plus a third one where the game would crash when you had a game mode filter on while switching tabs, and the new tab didn't have any maps of that sort.

**Comment by penev92** [comment]
Works as advertised, and looks pretty nice :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/c5deac560ea4016ccb5f2e7286b695ba373eeb86...4682a084fb831ba3824915aa3f3ac644887b7aa1)

**Pull request merged**
