### PR TITLE
Fix yak attack in Evacuation

### PR DESCRIPTION
**Pull request by obrakmann**
Depends on #12160.

### CODE REVIEW

**Comment by reaperrr** [comment]
You can rebase now.

**Comment by obrakmann** [comment]
Rebased.

**Comment by reaperrr** [comment]
It seems the Yak doesn't attack Tanya if she's on her own, is that intentional?
Otherwise the trigger seems to work, though.

**Comment by abcdefg30** [comment]
> It seems the Yak doesn't attack Tanya if she's on her own, is that intentional?

Yes. It would be kind of unfair otherwise, as the mission fails if Tanya is killed (and you can't really do much against those yak attacks, at least not before they killed their target).

Looks good to me as well. 👍 / ✅

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/edb23e307db51538c7cb3258cd6223679215b4f7...f7a41cd98e8cf73cdd3a5bedf35c2131913e90a0)

dd50004d91e6afd21183226527aa857f62f0f9c4

**Pull request merged**
