### PR TITLE
D2K - Add The Shield Wall to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
http://resource.openra.net/maps/21630/

### CODE REVIEW

**Comment by ltem** [comment]
I would add a worm spawner to the left side of the map else the map looks fine to me. Every player has more or less two spice blooms and a good position to reach it.

**Comment by MustaphaTR** [comment]
Updated.

**Comment by ltem** [comment]
:+1:

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1a5a02e6bd6e257967e5611f8bd0dae0c3cc6836)

**Pull request merged**
