### PR TITLE
Allow mission use lobby options

### PR DESCRIPTION
**Pull request by dnqbob**
Btw, I didn't fix all mods on this new UI here for I don't know if you will accept this implementation, and I am not a good UI designer.

Update: OK then, I will fix other mods.

### CODE REVIEW

**Comment by dnqbob** [comment]
Change name of some vars (player options -> mission options)

**Comment by Mailaender** [comment]
Why would you want this? Missions are usually crafted with specific game options in mind. Changing them could break the game. It also complicates testing to avoid those blockers.

**Comment by dnqbob** [comment]
> Missions are usually crafted with specific game options in mind. Changing them could break the game. 

Why allowing player use the legacy RA setting of fog check, build radius and disable redeploy MCV can break the game? You can always lock and hide the option if you don't want it change.

**Comment by abcdefg30** [comment]
> Why would you want this? Missions are usually crafted with specific game options in mind. Changing them could break the game. It also complicates testing to avoid those blockers.

We shouldn't enable this in the default mods, but might want to consider it in the future. In any case I don't see a reason why we shouldn't allow this for modders.

**Comment by Mailaender** [comment]
Can you squash the first two commits?

**Comment by dnqbob** [comment]
Rebased and squashed

**Comment by dnqbob** [comment]
Rebased again

**Review by Mailaender — DISMISSED** [review]

**Comment by Mailaender** [comment]
Removed test case 05952163d184426700e3c157b45853ee2989186a

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e25263508bf62288de99ed3efae21588c39435a8...ca475c5935357e16c39a9ae94fac7bdeac794cf6)

**Pull request merged**
