### PR TITLE
Send the external port in game advertisements.

### LINKED ISSUE #14832: MasterServerPinger uses ListenPort instead of ExternalPort
With the 20180218 release it's not possible to run multiple server instances on the same IP but different ExternalPorts. This was possible using a mixture of ListenPort/ExternalPort confguration settings and very useful with docker based deployments where routable IPv4 addresses are usually limited to the host address.

e.g.

```
docker run -d -p 1234:1234 \
             -e Name='Server 1' \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1234" \
             --name trolling \
             --restart unless-stopped \
	     $IMAGE

docker run -d -p 1235:1234 \
             -e Name="Server 2" \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1235" \
	     --name notrolling \
             --restart unless-stopped \
	     $IMAGE

docker run -d -p 1236:1234 \
             -e Name="Server 3" \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1236" \
	     --name chat \
             --restart unless-stopped \
	     $IMAGE
```

https://github.com/OpenRA/OpenRA/commit/3ba610b53534e9da2da9ea2a843f2f47c7b2fbdc#diff-e4bcdcd60c4fd417a17c73d84a5d9641R177 uses the ListenPort to announce the server, not the ExternalPort

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14832.

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]

**Comment by reaperrr** [comment]
Although it might be something on my end, this PR didn't have the desired result when I tested it.

Just mentioning it here so it doesn't get merged prematurely.

**Comment by reaperrr** [comment]
@rmoriz Can you test/confirm whether this PR works as intended for you?

**Review by abcdefg30 — COMMENTED** [review]
This doesn't appear to work for me.

**Comment by pchote** [comment]
Superseded by #15003.

**Pull request closed without merging**
