### PR TITLE
Fix d2k grenadier sequences.

### LINKED ISSUE #11785: D2k grenadier's prone sequences are wrong.
They currently break-dance and then turn into holes in the ground when firing.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #11785.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by reaperrr** [comment]
Am I right that this was a regression from the switch to original 1.06 assets, so it happened after last release and doesn't need a changelog entry?

**Comment by pchote** [comment]
Best would be to add it as a second pr on the entry explaining the switch to the 1.06 assets.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e4c7bd12e0feb5d7432c5a9cb9055aee3f91ea31...3220d57e9f0e9135a37d9308321ff09efb400996)

**Pull request merged**
