### PR TITLE
Avoid PowerShellisms to fix the AppVeyor build

### PR DESCRIPTION
**Pull request by Mailaender**
as suggested in https://github.com/OpenRA/OpenRA/pull/7661#issuecomment-80761740

### CODE REVIEW

**Comment by ScottNZ** [comment]
This might want to use the /Y option
```
  /Y                      Suppresses prompting to confirm you want to
                          overwrite an existing destination file.
```
`MOVE [/Y | /-Y] [drive:][path]filename1[,...] destination`

**Comment by Mailaender** [comment]
Thanks. Updated.

**Comment by obrakmann** [comment]
:+1:

**Comment by penev92** [comment]
:+1:

**Comment by Mailaender** [comment]
```
move /Y %NSIS_ROOT%\Plugin\nsProcess.dll %NSIS_ROOT%\Plugins\nsProcess.dll
The system cannot find the file specified.
```

Damn it. No idea why this keeps being so annoying and hard to fix.

**Comment by obrakmann** [comment]
That was a rather stupid error. `7z e` discards the directory hierarchy, `7z x` preserves it.

**Pull request merged**
