### PR TITLE
D2K: Fix refinery smoke anim, hi-tec factory offset and tile 401 terrain type

### PR DESCRIPTION
**Pull request by reaperrr**
The refinery overlay played too slowly and was positioned a few pixels too far to the left compared to the original.

Tile 401 is "infantry-only rocks" on rock terrain and should therefore be "Rough" terrain, yet had "Sand"(!) on bleed. This affected Harkonnen mission 5 for example (north-east of starting position).

Fixes are simple and obvious enough to make this a playtest blocker.

### CODE REVIEW

**Comment by reaperrr** [comment]
Pinging @ltem and @MustaphaTR for review.

**Review by MustaphaTR — APPROVED** [review]
Looks good to me.

**Review by ltem — APPROVED** [review]
All good. 👍 from me.

-------------

Maybe you could add this as well or I would do it in an other PR. I noticed while comparing with the gruntmods that our `Research Center` offset is by 4 pixels too low (not sure what that means in x,y,z offset). 

|image|image|
|:---:|:---:|
|Gruntmods|OpenRA|

(The four small red dots symbol the offset)

**Comment by reaperrr** [comment]
Updated, fixed factory:
hitec-facto

**Review by ltem — APPROVED** [review]

**Review by penev92 — APPROVED** [review]
I count 2 valid reviews.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a5f0464b0aa77b9bf61fe7f25762a18ffe337cfe...1b49e8fcb5d315b44bc14e42205e2394a6acebcf)

**Pull request merged**
