### PR TITLE
Add map Climax to the RA official map pool.

### PR DESCRIPTION
**Pull request by SoScared**
Adding Climax (2v2) to the official map pool. Seem like a popular request, following #16865

Updated with the latest Playtest (map preview): https://resource.openra.net/maps/32473

### CODE REVIEW

**Comment by SoScared** [comment]
Pinging @airetaM @wippie-openra @KSKNico @Phrohdoh

**Comment by reaperrr** [comment]
```
Testing map: Climax

OpenRA.Utility(1,1): Error: Actor Actor431 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor441 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor442 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor443 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor470 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor472 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor473 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor485 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor496 owner Creeps is not one of ValidOwnerNames: Neutral

OpenRA.Utility(1,1): Error: Actor Actor504 owner Creeps is not one of ValidOwnerNames: Neutral
```

Looks like some actors that should have 'Neutral' owner are owned by 'Creeps' instead (probably some trees). This needs to be fixed to fix the Travis error and to prevent AI from targeting them.

**Comment by SoScared** [comment]
Fixed!

**Review by airetaM — COMMENTED** [review]
There are still some cutted cliffs in here.
51,39 has been fixed with the wrong endcliff
Tile 155 can be set at 51, 38 and the cliff at the left is cutted now too ( Tile 154 )
The right endtile at 117,70 is tile 149
1,124 missed cliff
and 4,124 cutted cliff ( tile 144 )
81,57 can be replaced with tile 149

**Comment by wippie-openra** [comment]
@airetaM ; Thank you for taking the time to review this. 
I performed rework on the areas mentioned. Also performed some visual updates on the map involving rockwork. Redrew them from scratch so I was absolutely sure to pick the right tiles. 

Please find the update at [here](https://resource.openra.net/maps/32611/) .

@SoScared how did you manage to do the updated map preview?

**Review by airetaM — COMMENTED** [review]
Well done all broken cliffs are fixed now looking good for going official i would say.

**Comment by SoScared** [comment]
@wippie-openra Just open and save your map with the playtest editor. It'll generate the new map preview.

**Comment by SoScared** [comment]
Updated the PR with the latest map revision (including map preview update): https://resource.openra.net/maps/32626/

**Review by wippie-openra — APPROVED** [review]
Review was done above by airetaM. File was checked in by SoScared afterwards

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a2f4d1af591d14e4f2452ae125d6d46efe5d2df3...942601c71f509524ebb7c53d1a2e6d3ecbd5c0b2)

Added to prep since this has no regression risk: https://github.com/OpenRA/OpenRA/commit/46425adfe00443e1e6ccc1f767544f61d571e33c

**Pull request merged**
