### PR TITLE
ShroudRenderer UpdateShroud only when at least one cell is dirty.

### PR DESCRIPTION
**Pull request by anvilvapre**
ShroudRenderer UpdateShroud only when at least one cell is dirty.

`UpdateShroud` shows up in profile reports as one of the most
active methods (2.3% CPU time, main mono thread).

This commit introduces `anyCellDirty` to indicate that at least one
of the cells was marked as dirty.

Avoiding the need to traverse all projected cells of the map
to find any dirty cell.

This reduces the number of renderer shroud updates by at least 50% during a
test game. I assume this is related to renders occurring more
often than ticks(?).

### CODE REVIEW

**Comment by pchote** [comment]
Back in https://github.com/OpenRA/OpenRA/pull/17383#issuecomment-558404592 I suggested that we spatially partition the shroud updates (we have a `SpatiallyPartitioned` class specifically for this) so we can avoid traversing large parts of the map even when at least one cell was marked as dirty. I expect that this approach would work well in the rendering here as well as the shroud ticking. The two together may offer significantly better wins than just a basic boolean here?

**Comment by anvilvapre** [comment]
This is the minimal case where a check is performed on if any cell is touched. I would see it as a separate case from spatial separation. This check merely avoids the complete - or parts of - the region being searched for touched cells when no cells are touched. Perhaps a future spatial partitioning solution can indicate if any changes at all occurred and replace the bool. 

About spatial partitioning, i did some experiments my self today:

a. Creating a segmented projected cell layer. A single layer 4x4 grid on top of the map. However it causes a lot of additional calculations for each cell being marked as touched/dirty. The overhead typically does not live up to do iterating all cells in a region to check if touched.

It showed that during a 2 minute game on a map with 20k cell that often 6k cells are touched with - of that - a max of 600 cells being changed to a new resolved state. This resulted in general of less than 6 of 16 segments being marked as touched. However the map had 6 separate somewhat idle AI players.

I didn't finish the implementation as it required me to be able to iterate over the regions of a spatial area. 

In general i think the map dimensions are somewhat too small for managing the overhead of spatial separation. I.e. marking a cell as dirty results in additional method calls in which a cell poss is div and modded to a segment. Also iterating the segments after would become more complex, would likely require enumerators - becoming expensive to maintain per tick.


b. A simpler attempt was to store a Enum byte TouchState in the touched cell layer. Each touched state either indicate NotTouched, CellTouched or BlockTouched. Whenever marking a cell as touched also the first cell of a block of X cells (8, 16, 32) is marked BlockTouched. 

In the Tick method it allow for fasting skipping of blocks of (horizontal, 1 row height) cells. This way map cells can also be traversed in the same order from top left to bottom right.

The performance improvement is not significant. On the testing map - largely idle bots - 600 blocks of 8 cells could be skipped of about 950 blocks in total i believe. Skipping a block of 8 or 16 cells helps somewhat, only the overhead of first extra marking - for each touched cell - of  the start of a cell block has additional cost. The overall benefit is limited. 

My code used arrays over a cell layer. Too much code change for limited benefit.


c. In - only - a 2 minute game with bots - typically a maximum of 6k of total 20k cells are touched during any render. I converted the touched cell layer to an int array and added a touchedIndexes int array storing all the indexes of cells being touched. In the Tick method I iterate the touchedIndexes - not the map region. This has some benefit in early games. It allows you to skip untouched cells. However again the overhead is storing a value in two arrays when marking a cell as touched.

Also here i on purpose used two int arrays over cell layers. 


I noticed the class you mention works with Bins. For Shroud it may not be suitable enough to be able to quickly mark a cell as touched and/or changed. The marking is only for that game Tick.


My suggestion - before using spacial separation - to investigate if it it wouldn't be beneficial to in large parts of the code replace PPos with a PIndex type that stores the array index as an integer. Specifically in the Shroud code the u and v value of PPos objects are rarely used however the many cell layers often convert them often to array indexes resulting in significant overhead.  Based on that option B could become a more elegant solution.

**Comment by pchote** [comment]
4x4 binning is very fine grained, we generally have used ~10x10 binning in previous cases.

**Comment by RoosterDragon** [comment]
Agree with @pchote here, you probably just need to find the sweet spot for bin size.

A 4x4 region for a bin means the bins array is 25% of the size compared to the number of cells on the map, that's a large array to iterate over. We expect very few bins to be marked, even in a busy frame.

A 10x10 region means the bins array is 1% of the size of the map, that's pretty fast to iterate over. In a busy frame, a fair number of bins could get marked, but hopefully not *that* many.

You boolean flag is effectively one gigantic bin, very fast to check, but means we have to iterate the whole map when anything changes at all.

We'd probably prefer to improve the "busy frame" case where a lot of units move over improving the already-best case scenario where there's nothing changed - so I'd back the idea of some partitioning.

**Comment by anvilvapre** [comment]
I divided the map in 16 squares 4x4. Not areas of 4x4 pixels. I stopped working on my experiment for now.

Awaiting a spacial division solution a `dirty flag` boolean is still relevant. `ShroudRenderer.UpdateShroud` is called per render - while changes can only occur per tick. It means that currently the map region is traversed at least twice to three times too often.

So don't see the boolean as a bin but rather as a `dirty` marker for logic tick updates. A check on WorldTick perhaps can also work.

Similarly in Shroud, the regions of many Shroud instances are iterated over each time without any touches. Using a flag there causes 40% tick time drop (separate pull request).

**Comment by pchote** [comment]
To be clear, I also meant 100 cells 10x10, as in 240x240px.

**Comment by RoosterDragon** [comment]
> `ShroudRenderer.UpdateShroud` is called per render - while changes can only occur per tick. It means that currently the map region is traversed at least twice to three times too often.

Ah, that's something that hadn't occurred to me - in which case this change would make sense on its own, even if you added partitioning later.

**Review by RoosterDragon — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1f5b6118d13352d94aa782178cd34a8fb0188740...6e13f5339c4bc0230aff17ef19193839873d8fcd)

**Pull request merged**
