### PR TITLE
Fix badge label padding.

### LINKED ISSUE #15424: [Auth] The User description window is not long enough
Might want to setup a code to make it change dinamically.

unknown 2

### PR DESCRIPTION
**Pull request by pchote**
Fixes #15424.

### CODE REVIEW

**Comment by matjaeck** [comment]
cnc_
ra
d2k

This is windowed mode but it looked the same in fullscreen mode.

**Comment by pchote** [comment]
Can anyone confirm @matjaeck's results? This is how the same badges look for me:
screen shot 2018-08-11 at 19 42 09
screen shot 2018-08-11 at 19 43 42

**Review by ghost — APPROVED** [review]
This was a mistake by me, I forgot to switch to the new branch. Badge labels look good now.

**Review by Smittytron — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/42263c0effa865257bc92c68f0b003de9c1a4619...5b99e7a81e8ef32d56a2f4654eaf4dfd1129041e)

**Pull request merged**
