### PR TITLE
Use HashSets for AI

### PR DESCRIPTION
**Pull request by reaperrr**
There are a few `.Contains` checks involving these.

Not sure whether this has any tangible benefits (or unwanted side-effects), but i thought putting this up for review wouldn't hurt.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Seems fine to me as I can't think of a scenario where duplicate values makes sense here.
I haven't tested this though.

**Comment by chrisforbes** [comment]
:+1:

**Comment by Mailaender** [comment]
Still works in-game. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/96ad5f2df2a5a31930cdb8b233ae1aaeaff703f0...cfff98fbde4c9ea88a4180253a1c78fabe9d620a)

**Comment by Mailaender** [comment]
Thanks.

**Pull request merged**
