### PR TITLE
Split RA weapons.yaml into multiple roughly categorized files

### PR DESCRIPTION
**Pull request by reaperrr**
Took the same approach as for CnC mod.

Note: For what it's worth, I did compare the number of weapons, it was 62 before and after splitting the file.

### CODE REVIEW

**Comment by obrakmann** [comment]
Shellmap still works as expected, nukes go off, too, so :+1: 

Needs a rebase, though

**Comment by reaperrr** [comment]
Rebased.

**Comment by reaperrr** [comment]
Pinging @Phrohdoh, @Mailaender, @ScottNZ or anyone else to spare a few minutes for this. I know this isn't something urgent, but I have a PR in the pipeline that will go through rebase hell if I apply the yaml upgrade rules there before this is merged.

**Comment by Phrohdoh** [comment]
I'm not a fan of the filenames as I don't think by caliber instead by names/operators, but ok. :+1:

**Pull request merged**
