### PR TITLE
Added the Helicarrier

### LINKED ISSUE #16998: Adding Helicarrier to RA
It would act like Aircraft Carriers from RA2, releasing Hinds to attack. They would be armed with machine guns for anti-ground and missiles for anti-air. Helicarriers would be a Soviet unit that fits the role of Destroyers, shore harassment and anti-air. 

In order to properly balance naval a minimal amount of one Soviet naval unit needs to be added as the current number (2 combat units) is not enough to provide good gameplay dynamics. Technically helicarrier existed in the main game it won't be a completely new unit. It would also be a way to get Hinds back to Soviet

I was made aware that boolbada had already created carrier logic and that it is being used in Shattered Paradise for Scrin's Assault Carriers and Romanov's Vengeance's Aircraft Carriers

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/16998.

### CODE REVIEW

**Comment by pchote** [comment]
As I commented in that issue, I am strongly against the concept of shoehorning RA2's aircraft carrier logic into RA1 for the sake of finding a use for the Hind artwork.

**Comment by Mailaender** [comment]
Changed the helicopter type.

**Comment by dnqbob** [comment]
A very good point for mod. But IMO add a carrier may make the game hard to balance.

My suggestion here is that we can consider not applying this feature in creating a new buildable unit, instead we can create a tech building that use one/two hind as attack force, which can be considered as an tech defence that OpenRA-RA not yet have. A little bit cool but also not very helpful at late game (maybe just an advanced anti-infantry tower).

Meanwhile make it tech building can let this feature exposes to players more frequently while many good pvp maps exclude the sea combat, and players can find many bugs out of our testcase in many ways of using this tech building in a shorter time.

"unmanned helicopter controll center"
"capture to get advanced anti-infantry firepower"

Background: 
Soviet use {its cyber or whatever technology} to R&D unmanned fire support platform secretly by using a newly test helicopter series called hind at a time, but get abandoned when there is {many reason}. And half-finished unmanned hind prototype only has minigun.

**Comment by Mailaender** [comment]
The unit is disabled just like in the original game.

**Comment by reaperrr** [comment]
> The unit is disabled just like in the original game.

Then I honestly don't see the point of adding it. This is hard enough to balance that I don't even see many (if any) worthwhile custom maps enabling it, and certainly no official maps.

**Comment by dnqbob** [comment]
Why not make hind transport like carryall to vehicle? I know it will result in new balance issue but it is a most simple way to use this old assert

**Comment by dnqbob** [comment]
But for modder/game maker I support carrier logic here. If you are tired on maintaining I will also not against you on not applying this.

**Comment by Smittytron** [comment]
> Then I honestly don't see the point of adding it. This is hard enough to balance that I don't even see many (if any) worthwhile custom maps enabling it, and certainly no official maps.

I have no objection to adding the asset as long as there is an understanding that it won't be enabled in the core rules. I've got an idea where to use it in a Real tough guy difficulty only capacity in missions.

**Comment by penev92** [comment]
What is a `BaseSpawner` and why aren't those two classes abstract? I never liked the naming for all the carrier/spawener/whatever code that was used in the codebases where this PR comes from, but since it's here let's do something about it.

**Comment by PunkPun** [comment]
> This is hard enough to balance that I don't even see many (if any) worthwhile custom maps enabling it

> But IMO add a carrier may make the game hard to balance.
Helicarrier is a unit that can let us actually balance naval gameplay, and its not too far fetched to be in ra universe. I see plenty of maps taking advantage of this new logic or this exact unit

As for actual feedback to this pr
- hellicarrier is an omnidirectional unit, so it should have turn speed of 255. Just like naval transport
- I didn't update it in my issue, but it would actually look better if helis were able to land on moving hellicarriers. Helis are faster after all
- I think it would look better if aircraft were physically on helipads and their ammo was shown

Bugs
- If you give hellicarriers an attack order and quickly press stop while helis are ascending they will hover idle in air
- Helicopters when going to rearm don't immediately go to helicarrier but instead they go to a location the helicarrier was when the ream was triggered. This waypoint behaviour continues until helis reach the carrier
- even if helis are still fully armed after returning to hellicarrier they will wait the full reload delay before attacking
- if you shift queue targets hellicarriers will hesitate before moving onto the next target. By hesitate I mean they will go back in the direction of helicarrier for 1 second and then decide to move onto a new target
- sometimes situations happen where 2 helicopters try to push eachother out of the way but can't and stay in a forever loop, until they or carrier dies, or unitil an attack order is issued

**Comment by Mailaender** [comment]
> What is a `BaseSpawner` and why aren't those two classes abstract? I never liked the naming for all the carrier/spawener/whatever code that was used in the codebases where this PR comes from, but since it's here let's do something about it.

It is also used for https://github.com/OpenRA/ra2/pull/702 downstream.

**Comment by penev92** [comment]
I am aware. That was in fact part of the reason for my comment.
First of all those should be abstract. Then we should think about coming up with better names, but that is of course secondary.

**Comment by Mailaender** [comment]
It was already renamed in the initial review of https://github.com/OpenRA/ra2/pull/682 but okay. I don't understand how you want a base trait to be abstract? What should it look like instead?

**Comment by KOYK** [comment]
The artwork is in the MIX files any way, so if any one wants to use it in a map, well its possible.
The problem I see with this PR is that people will start asking to be added in the game, just because is a beta artwork, and there will be an other circle of balance discussions on how it should work and so on. And to be honest there is no need for it so far. 

There are no gaps to be filed by this artwork.

**Comment by Mailaender** [comment]
This does not add artwork, but a significant chunk of code that can't be added to a map without this submission.

I made the base classes `abstract` and changed the turn speed of the carrier. I also added a landed heli however synchronizing the facings is a problem.

**Comment by KOYK** [comment]
@Mailaender Sorry but that issue asks to add the heli carrier into the ra mod, with arguments and ideas about how it will be balanced, if that is not the point of this PR then why have that issue marked as being closed by this PR, and not make a new issue that will fit with this PR? I mean it is kinda misleading.

Tho I will be honest, I did not see the new code additions, not until now.  So that is on me.

By the way I like the idea of adding a carrier logic into the engine, it will help with other mods. But not the heli carrier it self into the official RA mod.

**Comment by abcdefg30** [comment]
I suppose if we are really going to add carrier logic to the common dll, we'd be better off with a testcase than without. (Seeing how this is won't disturb any balance, but will be available through the dev commands.)

Fwiw, the current state seems to have a compiler error:
> Traits/CarrierChild.cs(34,6): error CS1729: 'BaseSpawnerChild' does not contain a constructor that takes 2 arguments [/home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj]

**Comment by Mailaender** [comment]
Fixed the compile error. I don't think we need more tickets for this tech demo that has potential to become part of something more. I always planned for a custom mission using this asset: aircraft-carrier

**Comment by pchote** [comment]
To get straight to the point: I don't think this feature should be upstream at this point in time (this may change in the future, after TS has been released), and, after all the effort i've put into making sure that features like this are well supported through dlls in the Mod SDK, I resent the idea of being forced to maintain it for all future time. So, if others really want this upstream, I would like this to be done with an agreement that we can remove it again without major complaint if it becomes a roadblock for feature/performance PRs for the upstream mods. We already know that the `Enter` logic needs to be rewritten to resolve the various issues surrounding ownership, fog of war, and conflicts between capture/infiltrate/repair/etc. This is already going to be difficult to do without the extra workload of rewriting and testing aircraft carriers on top.

**Comment by dnqbob** [comment]
So if we add the code here will result in code fix-up becoming harder I guess we need to be cautious about it. The nightmare of `TechTree` is still in my head.

**Comment by tovl** [comment]
It doesn't seem like this will get resolved soon. Let's close and park this in "future" for now to declutter the PR queue a bit.

**Comment by Leo512bit** [comment]
> Fixed the compile error. I don't think we need more tickets for this tech demo that has potential to become part of something more. I always planned for a custom mission using this asset: aircraft-carrier

I do have to ask where did you get that?

**Comment by Mailaender** [comment]
https://forum.openra.net/viewtopic.php?p=285062#p285062

**Comment by Leo512bit** [comment]
Was the unit ever finished and if so was it archived somewhere? Because [this link is dead.](https://github.com/xanax/OpenRA/commits/bleed)

**Pull request closed without merging**
