### PR TITLE
Fixed "Cannot change state when game started (state NotReady)"

### PR DESCRIPTION
**Pull request by Mailaender**
This is a proposed fix for https://github.com/OpenHV/OpenHV/issues/181 which was most likely introduced in https://github.com/OpenRA/OpenRA/pull/18494.

### CODE REVIEW

**Comment by pchote** [comment]
The state shouldn't be dispatched at all! The server is in full control of this, and should simply update its internal player state directly.

**Comment by deleted-user-1** [comment]
Not sure if identical, but what can happen in RA is that a player unchecks the lobby ready-checkbox in the moment all ready-boxes are checked, for example if somebody unchecks the ready-box in the moment the admin checks theirs. The result will be that the playerwho unchecked sees a similar or identical chat message in the ingame chat. It's been like this for years however.

**Comment by Mailaender** [comment]
Changed it, but the server still needs to sync the changed client state. Otherwise, it won't work.

**Comment by pchote** [comment]
That looks more like what I was expecting, but can we please do that from `LobbyCommands.Option` (which is where things actually change state) instead of having this as an unexpected side-effect of SyncLobbyGlobalSettings, which shouldn't be changing any state?

**Comment by pchote** [comment]
I'm also not sure why we are only resetting this on lobby option changes. Aren't things like map/team/bot changes just as important if not more so regarding resetting the ready state?

I'm not sure we really want to be mixing a regression fix and behaviour fixes here (unless you are happy to do it), so it might be better to revert #18494 here, and leave it to a new PR to reimplement the feature with the full behaviour?

**Comment by Mailaender** [comment]
Moved it to `LobbyCommands.Option`. I'm fine with just fixing it as this was a first time contribution and I don't want to be rude by simply reverting things. Plus I like the feature and get the reasoning behind it. The game options are rather hidden. A map change is more noticeable. We can still opt for unchecking for every change. It may be annoying, so I won't do it here.

**Comment by abcdefg30** [comment]
Map changes already reset the ready state.

**Comment by abcdefg30** [comment]
Does the server send the sync order right before the game starts (in that case why?) or right after it starts? (For the replay recorder; in that case we could simply check `world == null` to get if we're still in the lobby?)

**Comment by pchote** [comment]
> Map changes already reset the ready state.

Ah yes, I see. This is actually quite a different case because clients are switched to `Invalid` and then need to signal to the server that they have the map.

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/62297bc46f42ee5ba29b6316a4b062ea3a118e0a...45b49319e41eb78c682c1578ff1336db89421839)

**Pull request merged**
