### PR TITLE
Tiedied up d2k building build menu icon order

### PR DESCRIPTION
**Pull request by abcdefg30**
Supersedes #11687.

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by pchote** [comment]
Style nit: Please put two line breaks between the two sentences in each of the commit messages, which is the easiest way to bring them in line with the standard git conventions (so they don't break in git log or the github ui)

**Comment by pchote** [comment]
I'm not sure that this new order makes sense.  The layout doesn't match the order that tech is unlocked: e.g. the Palace sits immediately to the left of the IX Lab, which is its only prereq.

**Comment by penev92** [comment]
My two cents:
```
[17:09:15] php_bg: turrets are way too far down to have any meaningful hotkey
[17:09:20] php_bg: palace should be further down
[17:09:38] php_bg: not sure I like the "starport before outpost" idea
[17:10:14] php_bg: IMO move palace & IX lab to the last row
[17:10:22] php_bg: and move the turrets up
[17:10:41] php_bg: also switch the palace and IX lab
[17:11:02] php_bg: as the palace is your "endgame" building, being the "superweapon" and all
```
Also possibly change row 3 to Outpost, Heavy Factory, Starport?

**Comment by abcdefg30** [comment]
Changes:
- Switched Outpost and Starport
- Switched Palace and IX Lab
- Moved turrets above the High Tech Factory

d2kbuildmenu

**Comment by reaperrr** [comment]
Both commits look fine to me.

I faintly remember that making the CYard an explicit prerequisite had to do with upgrades, so we need to make sure there aren't any regressions. 
I couldn't spot any, though, so maybe the original reason for listing it has already been taken care of.

**Comment by CH4Code** [comment]
(My) The previous order made some sense, since the two linear tech paths
pp->barracks->outpost->high tech factory      (and rocket turret)
(pp)->refinery-> lt. factory / hvy. factory -> repair pad
were in line.
I see why turrets must be in front. But please switch starport and outpost back
(they made up a linear tech line too: starport <- outpost <+ hvy factory )
and replace row 4 with (gun-turret, rocket-turret, silo) so silo is in line with ref, and rocket-turret is in line with outpost.
Thank you.

**Comment by reaperrr** [comment]
> I see why turrets must be in front. But please switch starport and outpost back
(they made up a linear tech line too: starport <- outpost <+ hvy factory )
and replace row 4 with (gun-turret, rocket-turret, silo) so silo is in line with ref, and rocket-turret is in line with outpost.

@abcdefg30: The above suggestions by @CH4Code make sense, and this PR has been sitting idle for quite long, would be nice to finally get this in.

**Comment by reaperrr** [comment]
Superseded by #12534.

**Pull request closed without merging**
