### PR TITLE
Detonate refactor

### PR DESCRIPTION
**Pull request by Unit158**
I decided to fix it after Mailaender was kind enough to finish the spicebloom pr. ~~NOTE: WithChargeAnimation is dumb. I'm not really sure how to make it less dumb.~~

### CODE REVIEW

**Comment by Unit158** [comment]
Rebased.

**Comment by abcdefg30** [comment]
Needs a rebase again.

**Comment by Unit158** [comment]
I won't do that until it gets attn for a review. 3 rebases and no attention so far. (I also don't have the computer handy.)

**Comment by Phrohdoh** [comment]
Do we want a refactor that introduces something the author labels as dumb?

**Comment by Unit158** [comment]
This is precisely why I asked for a review, not for a merge.

**Comment by penev92** [comment]
We do want the refactor, and the code was fine last time I looked at it (in the previous PR).

**Comment by Phrohdoh** [comment]
@Unit158 That question is part of a review. No attitude about it is necessary.

**Comment by Unit158** [comment]
The question itself was somewhat demeaning. I'm really not sure what you expected.

**Comment by Unit158** [comment]
Updated

**Comment by RoosterDragon** [comment]
Code looks pretty reasonable (haven't tested it yet though) - can I ask ask what the shortcomings with ```WithChargeAnimation``` are exactly?

**Comment by Unit158** [comment]
Ask reaperrr, I used his code.

**Comment by RoosterDragon** [comment]
@reaperrr

**Comment by reaperrr** [comment]
I don't see or know about anything wrong with `WithChargeAnimation`, but it's possible `AttackCharge` has flaws. I don't know the `Attack*` code that well, though.

**Comment by RoosterDragon** [comment]
Tested this - all the attacking and exploding mechanics seem to be working fine including chained explosions and detonation both manually and via an attack. I did noticed a couple of small issues though.
- The MAD tank's "charging" animation no longer seems to play.
- The screen shake effect whilst this is happening now seems to have a bias which makes the viewport drift to the side - previously this did not seem to be the case.

**Comment by Unit158** [comment]
Fixed.

**Comment by RoosterDragon** [comment]
:+1: Yup animation is fixed. Looks like the shaking bias I was talking about is present on bleed so nevermind on that one.

Needs a rebase.

**Comment by Unit158** [comment]
Rebased.

**Comment by Unit158** [comment]
So sorry to close this again. I don't have any time in the foreseeable future to maintain this. School takes a much greater priority over OpenRA right now.

**Comment by Mailaender** [comment]
This will need to rename into `ChargedDetonation` or something after https://github.com/OpenRA/OpenRA/pull/10371 is merged.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/OpenRA/pull/10808.

**Pull request closed without merging**
