### PR TITLE
Fix ActorMap spatial partitioning to actually work.

### PR DESCRIPTION
**Pull request by RoosterDragon**
The bin partitioning in ActorMap worked by dividing the map up into a few chunks of cells, each of which would contain some actors. Unfortunately, the bins were accessed directly in world coordinates which are on a scale 1024x greater than cell coordinates. This lead to all actors being placed into the bottom right bin. When checking for actors in a box, only this bottom right bin would be iterated for actors. Thanks to the fact this bin indeed contained all the actors, some clamps on the input ranges and filtering required per bin anyway, this actually returned correct results. Effectively, it was as if there was no spatial partitioning at all.

Not surprisingly however, this is fairly inefficient. By correcting the spatial partitioning to actually partition we see a 7x speedup in ActorsInBox on the RA shellmap.

I tested this programatically by having the results of this new method compared against those from just checking all the actors each time ActorsInBox was called. There were no differences whilst the RA shellmap was running.

### CODE REVIEW

**Comment by chrisforbes** [comment]
*headdesk*

**Comment by Mailaender** [comment]
:+1: I see no regressions in the ts nor d2k mod.

**Comment by obrakmann** [comment]
:+1: from me too.

Stupid question, though: is there any reason not to write `ActorsInBox` like below, instead of duplicating `BinsInBox` like it currently does?

```csharp
		public IEnumerable<Actor> ActorsInBox(WPos a, WPos b)
		{
			var left = Math.Min(a.X, b.X);
			var top = Math.Min(a.Y, b.Y);
			var right = Math.Max(a.X, b.X);
			var bottom = Math.Max(a.Y, b.Y);
			foreach (var bin in BinsInBox(a, b))
			{
				foreach (var actor in bin.Actors)
				{
					if (actor.IsInWorld)
					{
						var c = actor.CenterPosition;
						if (left <= c.X && c.X <= right && top <= c.Y && c.Y <= bottom)
							yield return actor;
					}
				}
			}
		}
```

**Comment by RoosterDragon** [comment]
Only for performance reasons. By manually inlining the BinsInBox code we can avoid the overhead introduced by IEnumerable. Since ActorsInBox gets called pretty often this is worthwhile.

**Comment by obrakmann** [comment]
Alright, thanks.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5807584dcd8a516d9e20511ca0843d127c2b7ac2%5E...5807584dcd8a516d9e20511ca0843d127c2b7ac2)

**Pull request merged**
