### PR TITLE
Add xmldoc to Widget.HandleMouseInput

### PR DESCRIPTION
**Pull request by phrohdoh**
cc @pchote, @RoosterDragon

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Sure why not :+1:

**Comment by obrakmann** [comment]
I don't quite see the point of documenting just that one method. At least do `HandleKeyPress` as well.

**Comment by Phrohdoh** [comment]
Are you going to require all of these too?

```csharp
		public static bool HandleInput(MouseInput mi)
		public static bool HandleTextInput(string text)
		public bool HandleMouseInputOuter(MouseInput mi)
		public virtual bool HandleKeyPress(KeyInput e) { return false; }
		public virtual bool HandleKeyPressOuter(KeyInput e)
		public virtual bool HandleTextInput(string text) { return false; }
		public virtual bool HandleTextInputOuter(string text)
		public override bool HandleKeyPress(KeyInput e) { return OnKeyPress(e); }
		public override bool HandleMouseInput(MouseInput mi)
```

**Comment by obrakmann** [comment]
no, just `HandleKeyPress`, since it's essentially the same text. :+1:

**Pull request merged**
