### PR TITLE
Updated the list of active developers participating in maintenance and code review

### PR DESCRIPTION
**Pull request by Mailaender**
Source: 
- https://github.com/OpenRA/OpenRA/graphs/contributors
- https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_history

### CODE REVIEW

**Comment by penev92** [comment]
Well :+1: from me if I get a vote :D

**Comment by pchote** [comment]
IMO @abcdefg30, @penev92, @reaperrr, and @RoosterDragon all deserve to be included in the developer list, so I'm up for this if they are.

**Comment by reaperrr** [comment]
> if they are.

Sure :)

**Comment by GraionDilach** [comment]
:+1: and congratz for everyone willing to be pushed up there.

**Comment by abcdefg30** [comment]
:+1: ^^

**Comment by chrisforbes** [comment]
:+1:

**Comment by Phrohdoh** [comment]
:+1:

**Pull request merged**
