### PR TITLE
Add installer metadata for the new Steam release of C&C TUC.

### PR DESCRIPTION
**Pull request by pchote**
This is a big improvement over the Origin release due to it working on Linux and macOS instead of just Windows.

### CODE REVIEW

**Comment by kevin-wijnen** [comment]
> This is a big improvement over the Origin release due to it working on Linux and macOS instead of just Windows.

Thanks in advance (as an end user) for this PR! Did you happen to test it on Linux by any chance, with detection (or selecting of the directory) of the new Steam versions on external storage media (SD cards, HDDs/SSDs etc.)?

I'm asking this, because of Steam Deck compatibility. It would be fantastic if the PR detected the installations off my Micro SD Card as well, compared to only scanning the internal storage.

**Comment by pchote** [comment]
I've only tested it on macOS, but I have no reason to believe that shouldn't work on Linux.

**Review by deadpahn — APPROVED** [review]
Looks good

**Review by penev92 — APPROVED** [review]
Thank you! 🎉

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/95e5c6c89d7d16cd32ec131001c9a605f5e46aab...0f72a0c23c52aa4efa1be117886b6e6bbd8b9e2d)

**Comment by Pentazer** [comment]
Awww yes, I'm glad this is on the next release! Looking forward to it! Thanks!

**Pull request merged**
