### PR TITLE
Expose the rest of the SupportPowers to lua

### LINKED ISSUE #11011: .lua support powers doesnt include nuke power
I was looking through https://github.com/OpenRA/OpenRA/wiki/Lua-API and it doesn't seem to show support powers such as nukepower or iron curtain.powers to use. It would be nice to have them as a reference instead of me manually finding out how to use these options.

### PR DESCRIPTION
**Pull request by abcdefg30**
Exposes the `NukePower` and the `IonCannonPower`.

`Iron Curtain` (`GrantUpgradePower`), `GpsPower`,  `ProduceActorPower` and `SpawnActorPower` can already be done by manually granting upgrades etc., while `AirstrikePower`, `ParatroopersPower` and `ChronoshiftPower` already are exposed.

Fixes #11011.

### CODE REVIEW

**Comment by pchote** [comment]
I'm not convinced that this is a good idea.. we have planned for years to change the nuke and ion cannon to be regular weapons that are fired by a support power (also used for the TS emp cannon and probably others).  Adding script interfaces that rely on the old implementations means either breaking scripts that use the interfaces, or adding in hacks to keep them working with the new generic implementation.

**Comment by GraionDilach** [comment]
That plan is insanely complicated though due to missile-flying-time is undetermistic, breaking beacon/camera actor lifetimes.

**Comment by pchote** [comment]
Its not trivial, sure, but it's far from insanely complicated.

**Comment by abcdefg30** [comment]
I'll see what I can do with that `Fire Armament` stuff.

**Comment by abcdefg30** [comment]
This is on hold at the moment.
> 17:48:15 (pchote) abcdefg30: where are we at on #11030?
17:48:50 (abcdefg30) I stopped my work firearmament as teees already pr'd something
17:48:57 (abcdefg30) so we kinda depend on his pr

His PR is #11108.

**Comment by abcdefg30** [comment]
Will close this for the time being.

**Pull request closed without merging**
