### PR TITLE
Added Tiberian Sun waterfall animations

### PR DESCRIPTION
**Pull request by Mailaender**
This is a rework of https://github.com/OpenRA/OpenRA/pull/13932. This time it's sprite offset compatible with the original .ini files, there is no manual placement involved and no actors are used.

### CODE REVIEW

**Comment by pchote** [comment]
Note to self: think about how/if this could integrate with the missing cliff shadow rendering

**Comment by pchote** [comment]
Having every overlay variation check every map cell isn't going to be great for load-time performance. We probably want to think about having a single trait that contains a dictionary of overlay types and only needs to enumerate the map cells once.

**Comment by pchote** [comment]
Tiles don't move and very rarely (currently: never) change during gameplay, so we may be able to win even further here by building a vertex buffer and bypassing all of the standard renderable overheads. This was my original plan for the cliff shadows, but animated tiles (which may change size/position as well as texture coordinates, thanks to shp(ts)'s virtual frame sizes) make this a little more complicated.

**Comment by pchote** [comment]
> Note to self: think about how/if this could integrate with the missing cliff shadow rendering

My current plan is, once #18728 is merged and we split out a specific `TSTerrain` tileset parser and `TSTerrainRenderer` trait, is to add `Shadows` and `Animations` sections to the TS tileset yamls. These would define the template type and index and the image/offset/palette/etc to use. The terrain renderer would then automatically manage putting these into vertex buffers and rendering them. Animations are trivial to handle provided all of the overlays have the same number of frames (which they do).

**Comment by Mailaender** [comment]
I assume we don't need this then.

**Pull request closed without merging**
