### PR TITLE
Make mammoth tanks capable of crushing concrete walls

### PR DESCRIPTION
**Pull request by abcdefg30**
Like the do in TD.

CC @SoScared, @kyrylo (as this was suggested on stream, too).

### CODE REVIEW

**Comment by SoScared** [comment]
Awesome! This is gonna make Mammoth tank a really fun unit to play. Especially on late-game team matches. :+1:

**Comment by kyrylo** [comment]
This idea has been floating around for ages (or months) :)
This is a big improvement for mammoths, but I am not totally sure it's enough.

**Comment by MustaphaTR** [comment]
:+1: That would be better if we make them crush light vehicles too as in my maps, but this is a start.

**Comment by obrakmann** [comment]
Well, neither walls nor mammoths are used much at all from what I can see, so I doubt this change would make any big impact.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/861e135cfb795d2a93087837056d56ca4333a132)

**Pull request merged**
