### PR TITLE
Don't cancel attack move cursor when holding shift

### LINKED ISSUE #16924: Keep attack move cursor if shift is held
To see the issue hold `shift` then press and release `a` then hold `a`. First mouse click will be an attack order followed by a MOVE order then followed by attack move orders. That move order shouldn't exist

### PR DESCRIPTION
**Pull request by PunkPun**
Closes #16924

This how it works in SC2. While you hold down shift the attack cursor remains

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]

**Review by dragunoff — APPROVED** [review]
I understand the rationale for this change and I tentatively agree that this is how it should work. Should guard order behave in the same way?

Also there is another problem with the a-move in OpenRA - once you enter a-move mode by pressing "A" there's no easy way to exit that mode from the keyboard (pressing "A" again doesn't toggle the mode). The only ways to exit the a-move mode are by issuing an order, by deselecting, by switching to another order mode (e.g. guard) or by double tapping `Esc` to open and close the menu. I bet SC2 has a way of exiting the order mode (maybe right click or `Esc`).

**Comment by PunkPun** [comment]
Since attack move is a mouse only order so I doubt that it has many other ways of cancelation. But this is unrelated to this PR

> Should guard order behave in the same way?

It could be considered. Now that I think about it more people may want to put guard order on multiple units

**Comment by PunkPun** [comment]
Adding it to guard won't be as simple and since this PR already has +2 it's better served in another PR

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5fbefc2854386286433a0d5b63a769255f719dc0...b2aea7d84724de9a4524499c4e92f63f43814c6e)

**Pull request merged**
