### PR TITLE
Music separated by Factions 

### PR DESCRIPTION
**Pull request by Shkarlatov**
Implement #19320 

Currently only for RA
Faction music theme taken from the original https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/REDALERT/THEME.CPP

For other mods need change /audio/music.yaml

### CODE REVIEW

**Comment by pchote** [comment]
> Currently only for RA

This is going to be a problem, since the setting is going to be exposed in all mods (both upstream and community). This ties in with #8276 which is a huge can of worms.

**Comment by Shkarlatov** [comment]
I think this is not a problem. RA and D2K support themes. For other mods, the setting is ignored.

**Comment by IceReaper** [comment]
Signing in for openkrush. Need that too. With switch to toggle between faction Tracks or all tracks depending on peoples favour

**Comment by penev92** [comment]
IMO if the main problem is the checkbox being visible in the Settings window for mods that don't want it, we can just have `AudioSettingsLogic` check with `MusicPlaylist` and show/hide the checkbox if there are any tracks that are faction-specific. That would solve the per-mod problem here.
That said, won't a better solution to the underlying issue (separate music per factions) be better handled by simply creating separate playlists that the user can choose from? (Actually ideally we would have both.)

**Comment by penev92** [comment]
This is obviously dead. @IceReaper please leave a comment below (for the record) if my last suggestion above missed any case and you still need this in some form.

**Pull request closed without merging**
