### PR TITLE
Hide ammobox healthbar.

### LINKED ISSUE #10036: Ammo boxes in RA should not be selectable
This is quite noticeable in the Sidestep map where they are mixed with (unselectable) boxes.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28407123-ammo-boxes-in-ra-should-not-be-selectable?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10036

Uses the same logic as #9758

### CODE REVIEW

**Comment by chrisforbes** [comment]
:+1:

**Comment by pchote** [comment]
This is a nice polish fix for a now-shipped map.  Would anyone object to taking this on prep?

**Comment by obrakmann** [comment]
Nope

**Comment by pchote** [comment]
Fix confirmed :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/b47510b591ea96dfa3348b4891f0242488e7932a

**Pull request merged**
