### PR TITLE
Fix Europe Map

### LINKED ISSUE #19740: RA: Official Map Europe is Bugged
2021-10-10 20_59_30-Window

Some map actors are flagged as creeps, which screws up the AI into trying to attack them.

### PR DESCRIPTION
**Pull request by Orb370**
Fixes #19740. Megatank cleared the creep labels on some of the actors and fixed some tile errors. Verified the creep labels are gone. Made a PR with his updated version.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]

**Comment by JMegaTank** [comment]
Europe map fixed 2nd time round 100% better than before 
fixed spawn letter A,B,C,D,E,F,G,H,I,J so it looks better 
fixed Italy starting spawn moved 2 oil derricks so you can build your base
fixed the roads so they look better than before but still keeping it to the original map
added 2 more communication centres for vision
added forward command in Sicily and a small gem mine
uploaded to resource centre https://resource.openra.net/maps/44362/

**Comment by Orb370** [comment]
Updated the PR with the new map. Renamed the map to Europe v2 since it has some significant changes.

**Review by abcdefg30 — DISMISSED** [review]
I'd prefer `Europe II` over `Europe v2` but that's ok. @Smittytron is your 👍 still valid?

**Comment by Orb370** [comment]
> 
> 
> I'd prefer `Europe II` over `Europe v2` but that's ok. @Smittytron is your 👍 still valid?

Oh right. I'm a bit scattered brained today. Agreed. Fixed.

**Comment by JMegaTank** [comment]
Europe II sounds good

**Comment by PunkPun** [comment]
I'd say there's no need to rename the map. There are already a hundred versions out there and it would be nice to have an official one

**Comment by Orb370** [comment]
Alright. I've reverted the name back to just Europe. I don't really feel strongly about this and I've received a few messages saying people would prefer it stick to the original name.

**Review by Smittytron — APPROVED** [review]
> @Smittytron is your 👍 still valid?

Yep, checked again for posterity.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7fe5d387088baebb5ec75503bde52f96a272567e...c8e941ae8a1d708fc0db7c951ac342c69a406f7b)

**Pull request merged**
