### PR TITLE
Improve pathfinder performance

### PR DESCRIPTION
**Pull request by RoosterDragon**
A number of commits intended to make the pathfinder faster by reducing small inefficiencies in the parts of the engine it relies on.

This PR should not affect the pathfinder output at all. For testing I recommend recording a replay on bleed and replaying it with this PR - there should be no desyncs unless I've messed up.

Overall, these changes save ~21% in pathfinding time.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Updated. Dependencies are now met so this is ready for review.

**Comment by Phrohdoh** [comment]
I tested with the method you suggested and got out of sync immediately.

**Comment by pchote** [comment]
@Phrohdoh: make sure that you test on the version of bleed that this is based on, as the current HEAD may have introduced sync-affecting changes that won't be present on this branch.

**Comment by Mailaender** [comment]
Can't spot regressions. Veterancy and roads still give unit speed upgrades and infantry avoids Tiberium. :white_check_mark:

**Comment by reaperrr** [comment]
Recorded a replay on the bleed this is based on and played it on this branch, no desyncs or visible regressions.

No crashes or regressions in a quick skirmish and on RA shellmap either.

:+1: once the typo is fixed.

**Comment by RoosterDragon** [comment]
Fixed the typo.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/f793edd6e31d5379bbf86a60573860d05f2c3e97...afdcdb050cea0b41ab9f94c6117e41768ead181f)

**Pull request merged**
