### PR TITLE
Rename the remaining properties in ScrollItemWidget

### LINKED ISSUE #20325: Uncorrected "BaseName" for "ScrollItem" in yaml
image
Cause crash when open related UI.

### PR DESCRIPTION
**Pull request by PunkPun**
Fixes #20325

Regression from #20285

### CODE REVIEW

**Comment by dnqbob** [comment]
Missed one:
image

**Comment by PunkPun** [comment]
Fixed. Again, it didn't find it for me. I see I'll have to use a different tool to search for yaml values

**Comment by dnqbob** [comment]
The fix lgtm now, I cannot find another place on "BaseName"

**Review by RoosterDragon — APPROVED** [review]

**Review by dragunoff — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0120b7da806b146adea094a28e66f252733688ad...0b7eb51ac58d0d75c745be299dcbaf50a6d030bd)

**Pull request merged**
