### PR TITLE
Remove junk ProximityCaptor values

### PR DESCRIPTION
**Pull request by abcdefg30**
I don't think we want walls, civilian field, trees, etc. to capture something.

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by Mailaender** [comment]
What were they used for @geckosoft?

**Comment by pchote** [comment]
The discussion predates the irc logs, but IIRC he wanted to use them as a general "unit class" label.  We had low standards for merging things at the time.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/ed07006c8e7d7d3015561c097b76882d5547cf7d)

**Comment by mylemans** [comment]
@pchote ouch man :P

**Pull request merged**
