### PR TITLE
Renamed the C&C load screen

### PR DESCRIPTION
**Pull request by Mailaender**
as there is nothing really Tiberian Dawn specific to it.

### CODE REVIEW

**Comment by pchote** [comment]
The positions and sizes are kind of tied to the TD artwork...

**Review by PunkPun — APPROVED** [review]
While generalising it's logic with other load screens would be better, renaming is a good start

**Comment by pchote** [comment]
Load screens can't really be generalized - lots of things need to be hardcoded because we want to be able to render them as early in the load sequence as possible. The `SheetLoadScreen` in `Mods.Common` already implements the generalised logic; the `CncLoadScreen` *only* defines the hardcoded artwork parameters used by cnc. Other mods should be subclassing `SheetLoadScreen` and defining their own artwork parameters themselves.

**Comment by Mailaender** [comment]
What if a mod has two factions and wants to re-use this load screen, but doesn't want the gameplay from the C&C dll?

**Comment by pchote** [comment]
They should create their own `SheetLoadScreen` that uses image rects based on their own artwork, and which won't break when we inevitably want to tweak the C&C load screen artwork in the future.

**Pull request closed without merging**
