### PR TITLE
AI AirState repair function

### PR DESCRIPTION
**Pull request by dnqbob**
Add Repair behavior for Aircraft unit when they retreat and IDLE.

### CODE REVIEW

**Comment by pchote** [comment]
Can you please describe in the PR description the problems with the existing behaviour and how this addresses them? This sets important context for reviewers.

**Comment by dnqbob** [comment]
OK,  because this one is just the standalone pr for a big pr,  and I guess title can explain everything

**Comment by pchote** [comment]
There are a lot of fiddly edge cases in selecting appropriate buildings for repair and reload, and we've had a lot of trouble in the past with making and keeping this logic working correctly. For this reason, I really don't like the approach here of using `ReturnToBase` as normal for reloading and then implementing custom logic that partially duplicates it for the repair case.

A more robust and maintainable solution would be to adapt `ReturnToBase` to accept flags for repair and rearm. The existing uses can keep `rearm: true` and `repair: false` to maintain current behaviour, and the AI can use `rearm: true` and `repair: true`.

**Comment by dnqbob** [comment]
> A more robust and maintainable solution would be to adapt ReturnToBase to accept flags for repair and rearm. The existing uses can keep rearm: true and repair: false to maintain current behaviour, and the AI can use rearm: true and repair: true.

So this will need to fix into the `ReturnToBase`? (I mean the order)

If doing so this will be a basic fix affecting all repair branches here. And somewhere else.

**Comment by dnqbob** [comment]
And should we do that first? Although I think it may be complex as well as "Repair" order will no longer put into use if we are doing that for simplifying (a good thing, though).

**Comment by dnqbob** [comment]
Besides, there is other problem to be solved, which cannot be solved by simply apply the combination of repair and reload flag.

>Because the idle-state-keeping is strange. Sometime it can last for several ticks in idle, sometimes it can only last for a short time, then the squad seems dismissed. When it last longer, it makes AI give out massive orders in idle state, which makes units frequently get on repairpad when last unit is not even finishing repairing and can lag the game in TS mod. Therefore, I only allow one of the squad units to go to repairpad in each tick(), and let other go to random building when flee..

If we directly apply repair orders here without limitation for AI and send every individual into repairpad, the game may lag due to lots of repair orders per tick, and the repairing may not be finished when other units get into pad. "Rearm first or repair first" in `ReturnToBase` will be also a problem, when both of them triggered.

To conclusion, I think if we decide to combine rearm and repair into `ReturnToBase`, other issues should be considered:

~1. Optimaze repair activity for group~ (If we only use it in flee state, and achieve 2. and 3. , 1. can be ignored)

2. Let aircrafts queue at repairpad like vechicles. 

add: in doing so every unit needs repairing will correctly queue, which allows us to not to use iterative tick() in idle-state to pick up every damaged units.

add: but this will affect normal human players. If what I see is right some people like this side effect of repair aircrafts.

3. "Rearm first or repair first" when both the flag is on. And how to queue those two activity.

**Comment by pchote** [comment]
> And should we do that first? 

Because it is difficult to understand, maintain, or be confident about code that has been copied and pasted into many different places and then slight tweaked in different ways in each. Code maintainability is important in any project, but especially in open source projects where other people will have to understand and change your code in the future.

The original AI code was merged without concern for this maintainability, and this has lead to many bugs and hundreds of hours of wasted time and frustration over the years while we have tried to understand what the original author meant and tried to fix broken logic and assumption each time a new problem occurs. We are still trying to overcome this, and adding more duplication makes this much harder.

**Comment by dnqbob** [comment]
Agree with you. But it seems it will be a big project to renew those things. 

update:

and as for "ReturnToBase" do you mean fix it on activities layer or order layer or just in these state-related files? I can do the last but I am not sure about the activities layer and order layer.

**Pull request closed without merging**
