### PR TITLE
Redesign the MP server browser.

### LINKED ISSUE #9451: Re-design server browser and lobby
I think the server browser (and to some extent the lobby) are in need of an overhaul. Here's a mockup I created fairly quickly with a few concepts highlighted. I'm not a self proclaimed design expert at all :), please chime in!

Server
- Show up to 10 servers at a time now with a flatter lobby list. Currently with the chat we only see 3!
- Show a panel on the right for more detailed information, we don't really care about some of this stuff for every single server (minimap preview, ip, version, and potentially players)
- Potentially allow players to sort by clicking on the server list columns
- Move the server filter into its own popup panel, which would show over the server list
- Change the chat to be tabbed - this means once you join a server, you can alternate between global and lobby chat

Lobby
- Added a Music button and moved the Change Map button. The Music panel would cover the player bin when opened.
- Changed the chat to be tabbed - let you switch between lobby and global chat.

Mockups (the OpenRA window is 1280x1024)
- It was suggested we keep the geometry of the server browser and game lobby the same size
- This has to fit the user interface's design limitation of 1024x768 size resolution

serverbrowser
lobby

These mockups are available as a Balsamiq file so anyone can tweak them

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26971269-re-design-server-browser-and-lobby?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
rtk6npk

Now displays up to 10 games at a time (up from three) and streamlines the flow for direct connect and creating servers.

Closes https://github.com/OpenRA/OpenRA/issues/9451.

### CODE REVIEW

**Comment by obrakmann** [comment]
Looking good so far.

One style issue: in !cnc, the tab buttons have gaps between them, whereas in the lobby they don't.

And one suggestion: the smallprint in direct ip mode could be moved into the tab proper. There's a lot of empty space there, so it wouldn't look as cramped below the minimap, and not as bland in main content area. Also you could choose a bigger font size to improve readability for that text. As I said, just a suggestion, not a request. Do with it what thou wilt.

**Comment by pchote** [comment]
Fixed the tabs, well spotted.  Not sure what to do about the description - I wrote that specifically to fill the gap between the map preview and the join button.  Could move it to the main bin, but we'd then need to come up with something to fill the new gap, and also the create server panel.

**Comment by obrakmann** [comment]
There's one more problem with the spawnpoints display:
screenshot from 2015-10-24 21 48 35

Fixing that would require some surgery in `MapPreviewWidget`, which I think is out of scope for this PR. We could ignore it for now, since TS isn't shipped so the bug wouldn't be exposed, or we could remove the spawnpoints display until it is fixed. I'd probably go with the second option. Enough people are now checking out TS themselves for them to notice bugs.

Other than that, :+1:

**Comment by pchote** [comment]
Yeah, I also noticed that (and commented about it in IRC) while testing.  That issue has always been there, but was previously hidden by not showing the spawn points in the map chooser.  Fixing that will require changes to both the widget and the master server (because we don't necessarily know what map grid style another mod uses), so can't be fixed here.

**Comment by pchote** [comment]
Updated:
* Rebased.
* Fixed the width of the refresh button in !td.
* Fixed cross-mod spawn rendering (depends on https://github.com/OpenRA/OpenRA-Resources/issues/265).

**Comment by Mailaender** [comment]
It suffers from the same layout problems mentioned in https://github.com/OpenRA/OpenRA/issues/9451#issuecomment-149784520 with a lot of empty space in the row of the back button as well as the direct IP and create server panels.

image

No doubt the multiplayer browser scales far better with the number of servers we have nowadays. Great job! This can be polished in later releases / pull requests.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/126b3c59e4285413e0dd29e3b2a8e9bc8fbe09c2...669cf43b6322eb58559b1d82097d38a7aba8d6c3)

**Comment by Mailaender** [comment]
@Phrohdoh Keep these chrome.yaml changes in mind when rebasing your RA2 mod.

**Comment by penev92** [comment]
Already done.

**Pull request merged**
