### PR TITLE
Add more D2k asset installers

### PR DESCRIPTION
**Pull request by penev92**
It recently turned out that there were numerous distributions of D2k floating around with minimal differences (**Important difference: the package SETUP.Z has different contents!** ... from what I've seen the different distributions contain packaging fixes). Our assets installers are quite picky, though, and the two we have are not enough.
I have added THREE new asset installers based on #14289, #14319 and my own version of the game.

I was *very* thorough in checking that all 5 installers produce the exact same output when installing from each and every one of them, but it would be nice if someone on Linux/Mac can verify, as we apparently have special installers for those.

Testing this is going to be a PITA if you intend to install. Personally I got the SETUP.Z files from #14289 and #14319 and ended up having to create an ISO based on my CD and modify it with those in order to test.

### CODE REVIEW

**Comment by penev92** [comment]
[This comment](https://github.com/OpenRA/OpenRA/issues/14289#issuecomment-347416742) from #14289 is a direct confirmation by the issue reporter that `d2k-d` works.

**Comment by penev92** [comment]
And [this comment](https://github.com/OpenRA/OpenRA/issues/14319#issuecomment-347996687) from #14319 is a direct confirmation by the issue reporter that `d2k-e` works (apparently under Linux).

**Comment by penev92** [comment]
With the above two comments I consider this now easy to review.

**Review by reaperrr — APPROVED** [review]
Although confirmation that they work on linux would be nice, since all of them have been tested and verified as working by at least 1 tester and can only improve the installer situation and not regress anything, I'll just give this the benefit of the doubt 👍

**Comment by penev92** [comment]
Note that I myself have tested all of them on Windows ;)
We now have confirmation for 2 of the 3 that they work on mac/linux by the people that originally complained that they can't install from their CDs.

**Comment by reaperrr** [comment]
Ah whatever, I'll count those confirmations from other people as 👍

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9d207e78f9c52c3c52751ae49fcb7fb925643c00...c8fd7821ef782d3cf69ac8fff70146e85155c7db

**Pull request merged**
