### PR TITLE
Adjust the description of allies05a

### LINKED ISSUE #10265: Spy gets shot
OpenRA.exe ver 12/13/2015. Mission 5a, Tanya's Tale: spy gets noticed and shot by soldiers.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29349204-spy-gets-shot?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
To prevent issues like #10226 and #10265.
-> Fixes #10265.

In addition we could disguise the spy automatically at mission start, if you feel like this change in the description is not enough.

### CODE REVIEW

**Comment by GraionDilach** [comment]
It's still kinda confusing, as the tooltip would still imply that the spy would pass all enemy units while only the disguised enemy player's allies would not shoot him.

But I guess people are just such stupid.

**Comment by ScottNZ** [comment]
An actual tutorial popup would help the most with this I think

**Comment by abcdefg30** [comment]
Added a small message to the beginning of the mission, as discussed on IRC.

**Comment by obrakmann** [comment]
:+1:

**Comment by Bynnar18** [comment]
While I do agree this is good, I think the message could use some rewording. Something like "Commander! I'll need a disguise to get past enemy patrols." Since technically the commander is suppose to just be giving the orders to get a disguise. Right now it's a little too direct, but maybe that's just me.

**Comment by atlimit8** [comment]
Please add "fixes #10226" and "fixes #10265" or equivalent to the description so that they are closed when this is merged.

**Comment by Mailaender** [comment]
Good idea. Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6a1a64209e1c1229ca5025d8cf5da6417d2f1f7d...a888a1fcf9db91b1924696e23c4ea01f11cc9c0f)

**Pull request merged**
