### PR TITLE
Fix the sietch being DamagedWithoutFoundation

### LINKED ISSUE #9517: Fremen sietch should not spawn at half health
The sietch is spawned with half health ingame, which is weird. I guess it inherits `^Building`, but doesn't remove the `DamagedWithoutFoundation` trait.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27137593-fremen-sietch-should-not-spawn-at-half-health?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #9517.

### CODE REVIEW

**Comment by penev92** [comment]
:+1:
If anyone is interested, I [this map](http://resource.openra.net/maps/5879/) uses them as terrain decorations.

**Comment by Mailaender** [comment]
Thanks for the convenient test case. I am not sure if it should be selectable and destructable at all.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/09ff3d52141c0ed09b4021c60a9f6468eaa51896...87416fdfc96e31e0d40444603a5b51d293799783)

**Comment by penev92** [comment]
Perhaps we should have them like trees and rocks - unselectable, indenstructable, basically a terrain decoration.

**Pull request merged**
