### PR TITLE
Replaced OpenAL Soft Windows DLL with a fetch script from Nuget

### PR DESCRIPTION
**Pull request by Mailaender**
I uploaded https://www.nuget.org/packages/OpenAL-Soft/1.16.0/ to get rid of the last native Windows DLL in our source code control system. https://github.com/OpenRA/OpenRA/issues/5485

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Tested this - works as advertised.

**Comment by obrakmann** [comment]
I'll count that as a :+1:, @RoosterDragon

**Comment by obrakmann** [comment]
Hmm... I was looking for the place that `make windows-dependencies` is actually called, but I didn't find it in either the `Makefile`, `.travis.yml` or anywhere in `/packaging`. I suppose we will need that somewhere to build a working windows installer (outside of appveyor), right?

**Comment by Mailaender** [comment]
We can't use Travis to build NSIS builds anymore https://github.com/OpenRA/OpenRA/pull/7345, remember?

**Comment by obrakmann** [comment]
yeah, but we can still build windows packages using the `package-all.sh` script.  But if you want to do that, you have to run `make windows-dependencies` manually now.

Either that should be fixed, or the whole windows package build in `package-all.sh` should be removed.
I agree that that's out of scope for this PR, though.

**Comment by Mailaender** [comment]
It also has nothing to do with it. Just check that the nuget download works for you and merge it. =)

**Comment by obrakmann** [comment]
it certainly does, :+1:

**Pull request merged**
