### PR TITLE
fix Engineer capturing (TS)

### PR DESCRIPTION
**Pull request by vgaming**
Engineers were able to capture buildings from first attempt (first Engineer) IIRC.

### CODE REVIEW

**Comment by vgaming** [comment]
Offtopic: I don't remember if Engineers were able to capture "defense" structures, too. Were they? If they indeed weren't able to, I can traverse over buildings and get them fixed (capturable=no) too.

**Comment by reaperrr** [comment]
> Offtopic: I don't remember if Engineers were able to capture "defense" structures, too. Were they? If they indeed weren't able to, I can traverse over "defensive" buildings and get them fixed (capturable=no) too.

No, 99.99% sure defenses weren't capturable.

**Review by reaperrr — APPROVED** [review]

**Comment by GraionDilach** [comment]
Pretty sure WW TS had the Multi-Engineer checkbox in skirmish so I'm not certain about this one tbh.

**Comment by vgaming** [comment]
Yes, @pchote even shared a image with that in chat: https://cnc-comm.com/news-images/cncnet5-ts.png

The problem is: we have to decide whether to follow original official TS or the new rules. Or maybe have a checkbox for that too? I'm basically waiting for your input. I only played original TS.

**Comment by pchote** [comment]
I just fired the original game up in Wine, and it's there too:
screen shot 2018-06-13 at 22 47 48

Maybe this was added in an official patch?

**Comment by GraionDilach** [comment]
Think RA already had multi-engineer, so I would assume it was there since day #1. Notsure how the legacy MP players went with though and I'd presume that should be the setting we should go with - for now atleast.

**Comment by vgaming** [comment]
@pchote that, or I have bad memory xD
Anyway, it seems this PR should be closed. One alternative for the checkbox is as good as the other. Should be a real option instead.

**Comment by vgaming** [comment]
Closing if you don't mind.

**Comment by vgaming** [comment]
@GraionDilach but in RA2, there is no multi-engineer option at all I think. So an alternative explanation is that they were slowly moving away from it. Doesn't matter though, closing.

**Comment by GraionDilach** [comment]
RA2 has the multi-engineer checkbox code disabled. AFAIK it's ignored in the ini/hidden from the UI pretty much instead of being removed from the game entirely in particular.

**Pull request closed without merging**
