### PR TITLE
Fix the d2k protected lobby icon being off

### PR DESCRIPTION
**Pull request by abcdefg30**
Before:
d2klocka
After:
d2klockb

### CODE REVIEW

**Comment by pchote** [comment]
Have you checked that the other (except admin, since I have just fixed that) entries in that block aren't also offset?

**Comment by abcdefg30** [comment]
Hm, yeah. I think the spawn points are off as well.
Before:
d2kspawna
After:
d2kspawnb

**Comment by abcdefg30** [comment]
Colorpicker before:
d2kcolora
After:
d2kcolorb

Huepicker before:
d2khuea
After:
d2khueb

**Comment by reaperrr** [comment]
Looks good to me :+1:

**Review by phrohdoh — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2ce741d521ad6097a1ffd7dd3e67cbfe143ca928...19ad799d70fa51c8446936fbd43415222b8a771d)

**Pull request merged**
