### PR TITLE
Added a dynamic prefix in front of replays

### PR DESCRIPTION
**Pull request by Mailaender**
~~It is either skirmish or the server name with the timestamp as we know it. This should help people find things quicker.~~

### CODE REVIEW

**Comment by pchote** [comment]
This triggers several sets of warning alarms in my head: server names may contain arbitrary non-path characters, or intentionally craft a name starting with "../../arbitrary/other/location" to write the replays to arbitrary locations.

Giving third parties control over filenames on the players system is a very bad idea in general.

**Comment by Mailaender** [comment]
Updated it to use the static mod title.

**Comment by pchote** [comment]
The mod title may also contain invalid characters. Please use the mod ID.

**Comment by Mailaender** [comment]
Changed it to the mod ID.

**Review by IceReaper — APPROVED** [review]

**Review by obrakmann — APPROVED** [review]
Not sure if this helps much since the replays are in per-mod directories already, but I guess it will help when exchanging replays with others. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b4b1501bb5fb3aee56707ffc47bd2ffa5dd002cb)

**Pull request merged**
