### PR TITLE
Fixed long bridge demolition

### PR DESCRIPTION
**Pull request by Mailaender**
Reverts https://github.com/OpenRA/OpenRA/commit/c23ee1be2e58bcc512ceb106d56a619bab48eb33#diff-0e19aa72642d1c8ffcf6cc9c47e4471c.

Fixes https://github.com/OpenRA/OpenRA/issues/9592.

### CODE REVIEW

**Comment by steelphase** [comment]
:+1: this resolve the bridge issue for Tanya. It also looks like the bridges render correctly at the edge of the screen.

**Comment by reaperrr** [comment]
Ultimately this means `CustomSelectionSize` is not working properly, so we should at least open a ticket for that.

**Comment by steelphase** [comment]
i also don't think this resolves #9192. I still can't use an engineer to repair the bridge.

**Comment by reaperrr** [comment]
Same here. #9592 works, #9192 still doesn't.

**Comment by reaperrr** [comment]
Actually, #9592 already works with `CustomSelectionSize` for me.

**Comment by Mailaender** [comment]
Can you give me the name and a screenshot of the bridge, because I tested this and it worked.

**Comment by reaperrr** [comment]
Any bridge on the Burlesca map in RA mod (didn't notice any differences between them).

**Comment by pchote** [comment]
The bridges in Burlesca are bogus - one of the end tiles on the bridge is missing (and theres a road tile there instead).  This confuses the bridge logic, and this appears to confuse the engineer repairing code.  The same issue exists in the last release.

**Comment by pchote** [comment]
The southern ends of the two bridges in Styrian Mountains also won't repair, and also have missing tiles (and also had the same problem in the last release).

**Comment by pchote** [comment]
Confirmed that this fixes #9592, but i'm removing the reference to #9192, which predates the Selectable change.

**Comment by pchote** [comment]
Unfortunately this does not address the real problem, it just hides it.  So i'll have to :-1: it in its current form.

The real regression for the bridge issues was introduced by 26ce7b5e1c3e6f8c7eaf359e14faaedf9954e470, not c23ee1b.

**Comment by pchote** [comment]
I have identified the real issue, and will file a pr later tonight.

**Pull request closed without merging**
