### PR TITLE
Fix production of dummy actors from producers without Exit trait

### PR DESCRIPTION
**Pull request by MustaphaTR**
The Conditional Exit PR broke this because it is now passing exit.Info instead of exit, which when exit is null is crashing. DoProduction has necessary checks in it that passing null there do not crash the game.

### CODE REVIEW

**Comment by pchote** [comment]
> DoProduction has necessary checks in it that passing null there do not crash the game.

It only checks for `self.OccupiesSpace != null`, so it technically works (because `Produce` will only give a null `Exit` if `OccupiesSpace` is null) but is extremely fragile.

Can you please add an explicit `exitInfo != null` check to that case in `DoProduction`?

**Comment by MustaphaTR** [comment]
Updated.

**Comment by pchote** [comment]
I tested this by removing the `Exit` trait from D2k's conyards, but the dummy upgrade actors stay on "Ready" rather than being produced.

**Comment by MustaphaTR** [comment]
The OccupiesSpace check is for the producer not producee i just noticed. I think the best course of action would be to change that because i don't think it would work fine if you try to build a real actor from player actor.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0740ee7c0e2893911efbcd9c374b935ee3f2895e...ef9bcde0a194471dc20ec778beff73b0a09177e4

**Pull request merged**
