### PR TITLE
Fixup new lines of units descriptions and encyclopedias

### LINKED ISSUE #21660: Automatic ftl intendation normalisation broke unit destriptions
https://projectfluent.org/fluent/guide/multiline.html

playtest
Screenshot_2024-11-30_at_20 25 14

release
Screenshot_2024-11-30_at_20 25 03

ftl does indentation normalization so about half of the descriptions broke. 

for example, sam site didn't break
Screenshot_2024-11-30_at_20 30 26

the lines have differences in indentation

The fix is making sure there's always a difference in indentation
Screenshot_2024-11-30_at_20 27 36

### PR DESCRIPTION
**Pull request by PunkPun**
fixes #21660

### CODE REVIEW

**Comment by penev92** [comment]
1. Was the previously-there indentation even an intentional feature? Honestly it looks a bit weird.
image

2. the PR adds hardcoded indentation of 4 spaces to the first text line (in FTL), but we use 3 spaces for some reason, so this looks odd
image

**Comment by penev92** [comment]
From Discord:
```
penev92 — Today at 00:12
I'm going to assume that someone just assumed 4 out of habit initially 😐
because the FTL files are configured to use 3 and do use 3
but the place I see it now is your newly added (and modified) code, so you can "fix" it there at least 🙂 
otherwise we can add an override to .editorconfig to switch FTL files to 4-space indentation to match our other stuff, but that's a bigger can of worms
```

Can we change the extraction code to hardcode 3 spaces instead of 4 so we reduce the number of inconsistencies in FTL files rather than introduce more inconsistencies please?

Unless we're planning to override the default FTL indentation from 3 to 4 spaces?

**Comment by PunkPun** [comment]
the extraction does 3 spaces, and when it comes to new lines, it replaces with 4 spaces.

> Was the previously-there indentation even an intentional feature? Honestly it looks a bit weird.

It was intentional, however it was not consistently applied. I went through all mods and ingame checked for all indentation, I fixed up incorrect usage so now it should look much better.

I also changed up d2k upgrade descriptions as I though the old way of listing unlocked units sucked

**Review by penev92 — APPROVED** [review]
👍

**Comment by penev92** [comment]
Commits on `prep-2411`:
https://github.com/OpenRA/OpenRA/commit/2192a6b4f97c6e6cd4ea827097c63634ed725b64
https://github.com/OpenRA/OpenRA/commit/34c29f872a575c9f2cf292541ae09e65a0feff0d
https://github.com/OpenRA/OpenRA/commit/e2821933a4f315e9c87f3fc88857ef815bbf1d41
https://github.com/OpenRA/OpenRA/commit/0566b6f78709953cba02a743bfa1082d238e2aa9

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/compare/68ad9163ffd2...0566b6f78709

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ce699eefb76cfd297f3d97d4921540e09edbbe76...67869e667617c5596744a5a28235f214df6ca706)

**Pull request merged**
