### PR TITLE
[D2k] Added the 'Damage' UncloakType to several units

### LINKED ISSUE #12192: RA Phase Transport, TD Stealth tank & D2k Stealth Raider don't uncloak on damage
Aside from `Move`, which is obviously intentional, `Damage` is the only trigger not listed in the internal default of `Cloak.UncloakOn`.

`UncloakType.Damage` was most likely ommitted by accident in
https://github.com/OpenRA/OpenRA/commit/f46185b85f458f44f32787f481983d91575d6808
because unlike the other 5 possible triggers, damage was previously hardcoded to trigger an uncloak and did not have a boolean field.

This also means this is a regression and should probably go into stable, as it affects at least 1 unit in each shipping mod + actors collecting stealth crates in TD.

### PR DESCRIPTION
**Pull request by abc013**
Changed: Saboteur, Fremen and Stealth Raider. Closes #12192.

### CODE REVIEW

**Comment by pchote** [comment]
Is this consistent with the behaviour in the original game?

**Comment by abc013** [comment]
@reaperrr wrote :
> IIRC, we want at least D2k to stay as true to the original as possible, so we might want to change it at least on the Stealth Raider, Fremen and possibly Saboteur.

So, should be.

**Comment by reaperrr** [comment]
> Is this consistent with the behaviour in the original game?

I just checked, it is.

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3600dd0192ca45d300bc32fb3e44bc7c66a2eed0)

**Pull request merged**
