### PR TITLE
Fix D2K units not auto-targeting defenses in Defend stance.

### PR DESCRIPTION
**Pull request by pchote**

### CODE REVIEW

**Comment by rob-v** [comment]
It seems not working - infantry doesn't attack Defense in Defend stance, Light vehicles attack them, but they also attack units.

**Comment by rob-v** [comment]
I guess not caused by this PR, but Defend stance doesn't work on infantry.

**Comment by pchote** [comment]
Works fine for me, so i'm not sure what to suggest.  Are you sure you're not accidentally still on bleed?

**Review by rob-v — APPROVED** [review]
👍 
sorry, was complete pebcak.

btw this problem is also in TS (Defense missing TargetTypes?)

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
No changelog entry since it just fixes a regression.

**Comment by pchote** [comment]
Would be good to list this in with the original PR entry.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/93e7dc8c3820853c9be3eb24a693a5fbd147e7fa...58588fbb27e244af2a027c313294a278430a3fd0

**Pull request merged**
