### PR TITLE
Yaml style clean-up

### PR DESCRIPTION
**Pull request by reaperrr**
It annoys me that these come up whenever I apply upgrade rules, I think it's time to actually adress them on bleed.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by pchote** [comment]
Why have the map.pngs changed? If this is. Windows vs everyone else problem then it just makes things dirty for others.

**Comment by reaperrr** [comment]
> Why have the map.pngs changed? If this is. Windows vs everyone else problem then it just makes things dirty for others.

I don't know.

Maybe someone not on Windows could run upgrade rules on this branch (with something like 20160823 as date, so no real upgrade rules get applied), if the pngs don't change again, they should be fine for all OSes.

FWIW, the PNGs that @abcdefg30 & Co. 'crushed' for singleplayer missions were not changed, so I suspect the PNGs that the upgrade rules touched were saved with some old engine revision or some other 3rd-party software.

**Comment by pchote** [comment]
The singleplayer missions define `LockPreview: True`, which tells the game to never overwrite them.

**Comment by obrakmann** [comment]
FWIW, the `map.png`s don't get flagged here when I run `./OpenRA.Utility.exe ra --upgrade-mod 20160823`, neither on this branch nor on bleed. So I guess that is indeed a windows-only thing

**Comment by GraionDilach** [comment]
These map.pngs gets flagged on bleed on my Kubuntu 14.04.5 x64, but I haven't tested this branch yet.

**Comment by pchote** [comment]
The `map.png`s don't get flagged for me, and the versions here are bigger than those in the repo.

**Comment by reaperrr** [comment]
> The singleplayer missions define `LockPreview: True`, which tells the game to never overwrite them.

Do upgrade rules also 'listen' to `LockPreview: True`?

Anyway, I've removed that commit so we can get at least the style fixes merged quickly.

**Comment by abcdefg30** [comment]
👍

**Pull request merged**
