### PR TITLE
[TS] Polish the Unit Movement

### PR DESCRIPTION
**Pull request by LipkeGu**
This Pr changes the Speed of Units
- Damaged Infantry moves now slower.
- Units gets slower on Sand and Tiberium

### CODE REVIEW

**Comment by pchote** [comment]
@reaperrr does this look correct to you?

**Comment by GraionDilach** [comment]
>Damaged Infantry moves now slower.

This was introduced in Generals.

>Units gets slower on Sand

The Sand terraintype doesn't exist.

>Units gets slower on [...] Tiberium

They already were and already had the respective TS setup. https://github.com/LipkeGu/TSIniFiles/blob/master/rules.ini#L10401

**Comment by LipkeGu** [comment]
@GraionDilach  As far i know sand does exist in TS and wasn a valid buildTarget for buildings

**Comment by reaperrr** [comment]
@LipkeGu The 'sand' in TS didn't have its own terrain type. It used the 'Rough' terrain type instead. 

And infantry didn't slow down on damage in the original TS, like @GraionDilach already pointed out.

> @reaperrr does this look correct to you?

No. Bleed already uses the correct original values.

**Comment by GraionDilach** [comment]
@LipkeGu Beach exists as a terraintype and not Sand. However, this Beach terraintype was never used either. You could look up the tilesets or the original TMP data - they are indeed using Rough and Clear terrain.

**Comment by LipkeGu** [comment]
These TileTypes are taken from temperate.yaml :/ and they works :/

**Comment by GraionDilach** [comment]
Please reread https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/tilesets/temperate.yaml#L12315.

In any case, this PR is completely arbitrary and should be closed as it goes against the current TS plan.

**Pull request closed without merging**
