### PR TITLE
Fix reinforcements appearing in soviet04a/b despite killed radar dome

### LINKED ISSUE #9892: RA, Soviet 04a mission, radar dome reinforcements
I tried asking this in IRC, but got no response - so here it is:

(playtest 20151031)
When I was playing the single player mission (RA, soviet 04a) the briefing states that killing the enemy radar dome would cut of their reinforcements. It didn't *seem* to be true.

Can you please check the mission scripting?
Thanks.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27991509-ra-soviet-04a-mission-radar-dome-reinforcements?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Closes #9892.

### CODE REVIEW

**Comment by abcdefg30** [comment]
What about the `ReinfInf` function(s)?

**Comment by obrakmann** [comment]
True, added that check there, too. Less likely to happen, but still. Updated.

**Comment by abcdefg30** [comment]
Looks good to me. :+1:

**Comment by penev92** [comment]
Seems legit :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/0427378afaec38d90938ecbdbbb82293a64d9247...9485e6f5a01f822998d378fd4f9ad83f69754a0b)

**Pull request merged**
