### PR TITLE
Make Contrail conditional and public

### LINKED ISSUE #19073: Make Contrail a conditional trait
mod support. we want different looks of a same air-transport actor on different factions, contrails is part of them.

### PR DESCRIPTION
**Pull request by reaperrr**
Also moved it to 'Render' subfolder while at it.

Suggested testcase: Add `RequiresCondition: ammo` to Contrail trait on RA Yak or MiG and make it deplete its ammo.

Closes #19073.

### CODE REVIEW

**Comment by Smittytron** [comment]
Testcase works, but I wonder if for polish sake the contrail needs to run its course when conditioned off instead of just disappearing.

**Comment by reaperrr** [comment]
> but I wonder if for polish sake the contrail needs to run its course when conditioned off instead of just disappearing.

Maybe, but I'm not sure live switches during movement will be the most common scenario, and I'm not really in the mood for scope-creeps, either.

**Review by Smittytron — DISMISSED** [review]
> Maybe, but I'm not sure live switches during movement will be the most common scenario, and I'm not really in the mood for scope-creeps, either.

Fine by me 👍

**Comment by pchote** [comment]
> but I wonder if for polish sake the contrail needs to run its course when conditioned off instead of just disappearing.

This probably wants to tie in with fading out instead of just disappearing when the actor leaves the map or disappears under the shroud. In any case, this is something for a later PR.

**Review by abcdefg30 — DISMISSED** [review]

**Comment by abcdefg30** [comment]
Needs a rebase though.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9609a83be8de64751caae625c949321ee6f8a839...79cc86449cbb4f57371ae1ceadc3cf6ce698ae74)

**Pull request merged**
