### PR TITLE
Cleaned up the ingame widget initialization

### PR DESCRIPTION
**Pull request by Mailaender**
This makes integrating the ingame map editor https://github.com/OpenRA/OpenRA/pull/4496 easier, but is also a nice cleanup in itself.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: . Tested shellmap, missions, skirmish, becoming an observer during skirmish and replays in the cnc and d2k mods.

**Comment by Mailaender** [comment]
Rebased.

**Comment by Mailaender** [comment]
Rebased.

**Comment by huwpascoe** [comment]
:+1: Can't find any faults with this

**Pull request merged**
