### PR TITLE
Add lint tests for unknown trait and weapon fields

### LINKED ISSUE #15201: [Suggestion] - Force the mod to crash at startup when inputting invalid propierties on traits.
Im referencing my comment in #9810 , as an user who has to update mods constantly, I believe this will solve the issues with renaming properties of traits.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #15201, with several key improvements over #15264:
* Doesn't hook into the internal game logic.
* Lists all errors in a single pass.
* Displays filenames and line numbers instead of just actor/trait name.

### CODE REVIEW

**Comment by pchote** [comment]
Testcase: rebase this PR onto `release-20180307` and notice that all the recently fixed errors in the default mods are reported.

**Comment by pchote** [comment]
Nope, looks like this is RIP too.

Definitions like the following break the approach here because we don't know what type of warhead it corresponds to:

```
BarrelExplode:
	Warhead@1Dam:
		ValidTargets: Ground, Prisoner
```

**Comment by GraionDilach** [comment]
I'll be honest - I thought respecifying the warhead types in definitions were good practice.

**Review by GraionDilach — APPROVED** [review]
:+1: though.

**Comment by ABrandau** [comment]
``Testing mod: Red Alert

OpenRA.Utility(1,1): Error: ra|rules/defaults.yaml:77 refers to a trait field `FirepowerMultiplierDoesntContainThis` that does not exist on `FirepowerMultiplier`.
OpenRA.Utility(1,1): Error: ra|rules/defaults.yaml:78 refers to a trait field `FakeTrait` that does not exist on `FirepowerMultiplier`.
OpenRA.Utility(1,1): Error: ra|weapons/smallcaliber.yaml:6 refers to a weapon field `InvalidWeaponProperty` that does not exist.
OpenRA.Utility(1,1): Error: ra|weapons/smallcaliber.yaml:10 refers to a projectile field `InvalidProjectileProperty` that does not exist on `Bullet`.
OpenRA.Utility(1,1): Error: ra|weapons/smallcaliber.yaml:14 refers to a warhead field `WrongDamageWarheadProperty` that does not exist on `SpreadDamage`.``

Only detail is that look at the sequences, not like that matters much anyway, I didnt made it look at Chrome, metrics or other details like that (might be important for some).

Otherwise, it works like a charm. :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/db56521d985535e9044719449389dd646d2d8f42

**Pull request merged**
