### PR TITLE
Remove sniper

### LINKED ISSUE #5578: Sniper Unit: Adding standing firing frames & Voice
Using the flame-trooper as a template to create the sniper unit, the "standing" firing frames were never created for the sniper unit since it was established that the sniper would always "prone" fire. Now, this isn't the case, as the Sniper unit fires standing up, but the standing firing frames need to be added. 

Also, the sniper unit currently uses GenericVoice, maybe it would be a good idea to distinguish selecting/ordering a sniper unit with a different voice than that of the typical e1,e3, etc.

Edit: Firing frames are added, also added in some "reloading" frames for the sniper in between shots.

comparison
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2555651-sniper-unit-adding-standing-firing-frames-voice?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PunkPun**
Closes #5578

https://github.com/OpenRA/OpenRA/issues/5578#issuecomment-158754424

Snipers are a custom unit in openra and we don't even use it. I'm removing it as it only causes confusion within the community and is just adding unnecessary maintenance costs to the project.

I dunno much about fort lonestar, so I'm keeping the sniper there. This PR basically moves all the sniper files and definitions from the game to fort lonestar

### CODE REVIEW

**Comment by Leo512bit** [comment]
I don't think this is a good idea I know that this will break some compatibility on some maps. And I think we should just give it to France, it's cloaking ability will play nice with the phase transport.

**Comment by PunkPun** [comment]
Just to make it clear, Sniper isn't ever getting enabled in the main game. Sniper is a custom unit and strays too far from the original game. Not to mention that he doesn't add anything to the gameplay / fixes no game design issues. Only creates them.

**Comment by Leo512bit** [comment]
>Sniper is a custom unit and strays too far from the original game.

I disagree I remember reading when the unit was removed in normal games the logic was that the shock trooper was effectively the sniper.

>Not to mention that he doesn't add anything to the gameplay

That's because it's disabled.

>Fixes no game design issues.

It will fix France by making it less _highly_ situational.

>Only creates them.

With that logic remove the demo truck. Most people would welcome that change.

**Comment by Smittytron** [comment]
Does Fort Lonestar need the sniper to be playable? If we're going to kill it we might as well kill it right.

**Comment by PunkPun** [comment]
> Does Fort Lonestar need the sniper to be playable? If we're going to kill it we might as well kill it right.

I haven't player Fort Lonestar. I ahve no idea

**Comment by Leo512bit** [comment]
> Does Fort Lonestar need the sniper to be playable? If we're going to kill it we might as well kill it right.

Yes it does at the moment, the lua script will have to be rewritten atleast in part.

**Comment by abcdefg30** [comment]
The sniper is a very useful unit on the player side in Fort Lonestar, would be sad to see it go. (Also, it fits way better at the borders of the map as invisible enemies than say Shok Troopers would.)

**Comment by abcdefg30** [comment]
Fwiw, personally I don't think having it in a single map is a problem.

**Review by pchote — APPROVED** [review]

**Review by Smittytron — APPROVED** [review]

**Comment by Smittytron** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3c4c39899291e95628a96b0162f81643aeacf8eb)

**Pull request merged**
