### PR TITLE
Make FlipX/FlipY flip respective embedded offsets as well

### PR DESCRIPTION
**Pull request by reaperrr**
When a sequence is flipped along an axis, flip embedded offsets for that axis as well.

### CODE REVIEW

**Comment by reaperrr** [comment]
This should have zero effect on our maintained mods. It is a requirement for my MechCommander mod. The only Westwood-related mod where this might play a role is Dune 2, pinging @evgeniysergeev whether this causes any regressions there.

**Comment by Phrohdoh** [comment]
Do you happen to have a set of gifs comparing before and after this commit so we can see a difference?

**Comment by pchote** [comment]
Does this really need to be optional?  Offsets are there to fudge the sprites, so I don't see a situation where you *wouldn't* want to flip the offsets.  Using offsets to fake in-world offsets is a hack.

**Comment by reaperrr** [comment]
@Phrohdoh screenshots should be enough:
without flipping offsets:
no-offset-flip

with flipped offsets:
offset-flip

@pchote: I just wanted to play it safe, but personally I wouldn't mind at all if this was non-optional.

**Comment by reaperrr** [comment]
Updated.

**Comment by pchote** [comment]
Looks fine to me :+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/991bd25de1d966995016ce9b4da83684813119bf...8c16969a90785a50b1d7e98423e5ec619dbdbbdb)

**Pull request merged**
