### PR TITLE
Merge Mods.RA into Mods.Cnc

### PR DESCRIPTION
**Pull request by reaperrr**

### CODE REVIEW

**Comment by GraionDilach** [comment]
The makefile wasn't updated.

**Comment by reaperrr** [comment]
Updated (a while ago, actually).

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
Confirmed that this hasn't broken the OSX packaging (and assuming that it works for the rest).

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ad7bd3f4c13a45ec49cde6b45436d9fcab1e45f9...08e0b3ecaed17231550982058e78c4e574a97b6d)

**Pull request merged**
