### PR TITLE
Tick VoxelWalker move animation when turning

### PR DESCRIPTION
**Pull request by teees**
Before: http://gfycat.com/BabyishSoupyIrishsetter
After: http://gfycat.com/FloweryUniqueArthropods

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by RoosterDragon** [comment]
You'll need to add `Requires<IFacingInfo>` to the Info class since you need to get at the facings now.

**Comment by teees** [comment]
Thank you, changed and rebased

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a360fa7101fa80fcb9108d815724d2529481bc96...85dd57f2a829d15e7194c675adfc49b2b2c134ca)

**Pull request merged**
