### PR TITLE
Fix invalid target crash in SupportPowerManager.Activate.

### LINKED ISSUE #16287: Crash when launching GPS satellite
Regression from #15891 
```
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
  at OpenRA.Traits.Target.get_CenterPosition () [0x00056] in /Users/paul/src/OpenRA/OpenRA.Game//Traits/Target.cs:172 
  at OpenRA.Mods.Common.Traits.SupportPowerInstance+<Activate>c__AnonStorey0.<>m__0 (OpenRA.Mods.Common.Traits.SupportPower a) [0x00032] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//Traits/SupportPowers/SupportPowerManager.cs:242 
  at OpenRA.Exts.CompareBy[T,U] (System.Collections.Generic.IEnumerable`1[T] ts, System.Func`2[T,TResult] selector, System.Int32 modifier, System.Boolean throws) [0x0004a] in /Users/paul/src/OpenRA/OpenRA.Game//Exts.cs:203 
  at OpenRA.Exts.MinByOrDefault[T,U] (System.Collections.Generic.IEnumerable`1[T] ts, System.Func`2[T,TResult] selector) [0x00005] in /Users/paul/src/OpenRA/OpenRA.Game//Exts.cs:182 
  at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate (OpenRA.Order order) [0x00052] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//Traits/SupportPowers/SupportPowerManager.cs:237 
  at OpenRA.Mods.Cnc.Traits.GpsPower.Charged (OpenRA.Actor self, System.String key) [0x00021] in /Users/paul/src/OpenRA/OpenRA.Mods.Cnc//Traits/SupportPowers/GpsPower.cs:67 
  at OpenRA.Mods.Common.Traits.SupportPowerInstance.Tick () [0x00138] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//Traits/SupportPowers/SupportPowerManager.cs:213 
  at OpenRA.Mods.Common.Traits.SupportPowerManager.OpenRA.Traits.ITick.Tick (OpenRA.Actor self) [0x00021] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//Traits/SupportPowers/SupportPowerManager.cs:102 
  at OpenRA.World.<Tick>m__4 (OpenRA.TraitPair`1[T] x) [0x0000e] in /Users/paul/src/OpenRA/OpenRA.Game//World.cs:366 
  at (wrapper delegate-invoke) System.Action`1[OpenRA.TraitPair`1[OpenRA.Traits.ITick]].invoke_void_T(OpenRA.TraitPair`1<OpenRA.Traits.ITick>)
  at OpenRA.WorldUtils.DoTimed[T] (System.Collections.Generic.IEnumerable`1[T] e, System.Action`1[T] a, System.String text) [0x00022] in /Users/paul/src/OpenRA/OpenRA.Game//WorldUtils.cs:78 
  at OpenRA.World.Tick () [0x000a6] in /Users/paul/src/OpenRA/OpenRA.Game//World.cs:366 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0023d] in /Users/paul/src/OpenRA/OpenRA.Game//Game.cs:602 
  at OpenRA.Game.LogicTick () [0x00055] in /Users/paul/src/OpenRA/OpenRA.Game//Game.cs:626 
  at OpenRA.Game.Loop () [0x000d6] in /Users/paul/src/OpenRA/OpenRA.Game//Game.cs:756 
  at OpenRA.Game.Run () [0x00042] in /Users/paul/src/OpenRA/OpenRA.Game//Game.cs:796 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in /Users/paul/src/OpenRA/OpenRA.Game//Game.cs:254 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/paul/src/OpenRA/OpenRA.Game//Support/Program.cs:37 
```

Repro case:
* Start a game and use `/all`
* Use `/instantcharge` to disable instant changing granted by `/all`
* Build two allied tech centers
* Use `/instantcharge` or wait for the GPS timer to complete

### PR DESCRIPTION
**Pull request by pchote**
Fixes #16287.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by fusion809** [comment]
This PR works for me. This file I'm attaching is a zip archive containing:

* A Red Alert AppImage (OpenRA-Red-Alert-25777-without-patch-x86_64.AppImage) built from commit 25777 (b8a85091d4cc61746d98f6b7bee99bbf3a33626b).
* A Red Alert AppImage (OpenRA-Red-Alert-25777-pr-16288-patch-applied-x86_64.AppImage) built from commit 25777 (b8a85091d4cc61746d98f6b7bee99bbf3a33626b), with [the patch this PR provides](https://github.com/OpenRA/OpenRA/commit/373a354676a8bd5ba04434066bad8e981456189b.patch) applied. 
* A replay (OpenRA-2019-03-10T034944Z.orarep) that when run under OpenRA-Red-Alert-25777-without-patch-x86_64.AppImage, produces the crash described in #16287. 

[OpenRA-Red-Alert-25777-pr-16288-appimages-replay.zip](https://github.com/OpenRA/OpenRA/files/2949078/OpenRA-Red-Alert-25777-pr-16288-appimages-replay.zip)

Providing this to make it easier for others to reproduce the bug, try the fix provided by this PR and thereby verify that it works.

**Review by MustaphaTR — COMMENTED** [review]
Didn't test the GPS but applying the changes locally fixes the same crash happening with SpawnActorPower for Satellite Scan in RV.

**Comment by reaperrr** [comment]
In my opinion that's enough to count as 2nd +1.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d2b757d4c9447e4821060570865dba6c3ffaf876...4b8471b6bd886e9d4e1abc7b79dafc5999ef62ef

**Pull request merged**
