### PR TITLE
Bump mono requirement to 4.2 in the deb package.

### LINKED ISSUE #14504: [Crash] Latest bleed, NotImplementedException, Arch Linux
```
Exception of type `System.NotImplementedException`: The method or operation is not implemented.
  at System.IO.Stream.Write (System.ReadOnlySpan`1[T] source) [0x00000] in <7403a1ce1bb645ddb8f0aa7250aed945>:0 
  at OpenRA.Network.EchoConnection.Send (System.Int32 frame, System.Collections.Generic.List`1[T] orders) [0x00013] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Network.OrderManager.Tick () [0x00052] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001ed] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Game.Loop () [0x000d6] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Game.Run () [0x00042] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <1cb3b40242f14d03b7a545dc92393682>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <1cb3b40242f14d03b7a545dc92393682>:0 
```
```
Platform is Linux
Engine version is {DEV_VERSION}
Using SDL 2 with OpenGL renderer
Desktop resolution: 1280x1024
No custom resolution provided, using desktop resolution
Using resolution: 1280x1024
Using window scale 1.00
OpenGL version: 3.0 Mesa 17.2.5
Using default sound device
```
Trying to play RA
No mods work
Mono -V output:
```
Mono JIT compiler version 5.9.0.375 (master/c58ab6f Tue Dec  5 23:21:27 EET 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

I am very interested to know which change causes this

### LINKED ISSUE #14788: Improve error message if connection to master server fails
`Failed to query server list.` does not help at all to find the cause and fix the issue.

### PR DESCRIPTION
**Pull request by pchote**
Closes #14504.

### CODE REVIEW

**Comment by pchote** [comment]
Suggested changelog entry (under 
General Improvements): Fixed a compatibility issue with mono 5.8 and newer.

**Comment by Mailaender** [comment]
Doesn't https://github.com/OpenRA/OpenRA/pull/14871 already do that?

**Review by reaperrr — APPROVED** [review]
Can't test it, but looks obvious enough

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/39c754d8df0a31bd9119f8c4db552bf6ebed4fb8...9049a470128192d36f68e128bf331e225202b60d)

https://github.com/OpenRA/OpenRA/commit/8ad8c227f07508a0861f45945a125e22a0c42b9e

**Pull request merged**
