### PR TITLE
Moves Disguise and related traits from Mods.RA to Mods.Common.

### PR DESCRIPTION
**Pull request by deniz1a**
Also fixes some issues.

### CODE REVIEW

**Comment by deniz1a** [comment]
And satellite code should probably also move to Mods.Common since RA2 will use it too.

**Comment by penev92** [comment]
Not yet.

**Comment by deniz1a** [comment]
After satellite code refactor?

**Comment by penev92** [comment]
After it is actually needed.

**Comment by deniz1a** [comment]
But it will be needed?

**Comment by deniz1a** [comment]
Also currently IgnoresDisguise.cs is in Mods.Common. So this patch would move the rest of the disguise stuff there too.

**Comment by penev92** [comment]
Moving of files is pretty easy to follow, but what exactly are you fixing in Disguise.cs?

**Comment by deniz1a** [comment]
* Incorrect example in comments. Spies can't disguise as dogs anymore.
* Radar color and displayed owner are corrected. Now all states of current player are checked and the real owner is shown to allies.

**Comment by reaperrr** [comment]
:-1: to moving RA-specific stuff to Common just because the RA2 mod will use it. If it's just the RA2 mod that will use it (which is likely), the RA2 mod should simply use the Mods.RA.dll, in my opinion. Otherwise we might as well ditch the concept of mod-specific dlls.

**Comment by Phrohdoh** [comment]
FWIW RA2 does not currently reference the RA assembly.

Just Common and TS and eventually RA2.

**Comment by Mailaender** [comment]
I agree this is a very specific (and hacky) Red Alert feature. We didn't move it to Mods.Common on purpose.

**Comment by deniz1a** [comment]
What if a custom mods wants to have disguise trait?

**Comment by reaperrr** [comment]
> What if a custom mods wants to have disguise trait?

Then it should use the Mods.RA assembly.

**Comment by Phrohdoh** [comment]
To be fair we did move the voxel stuff to Common.

**Comment by GraionDilach** [comment]
To be fair, TS also uses the Disguise trait already.

**Pull request closed without merging**
