### PR TITLE
First step towards Async Communication

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
This is a first step towards complete async IO (wether network or file reading).

I started off by rethinking the relaying of commands by the server. By creating "SendDataAsync" I was able to create room for the runtime to decide wether to issue orders in a parallel manner or not. 

Calling `socket.SendAsync` by itself does not make the operation parallel, it only signals the runtime that IF POSSIBLE this should be delegated to a "background" thread (aka IOCP). If those are available the loop will continue and send more orders, waiting for their completion on `Server.cs` line 830.

This should decrease the total time taken to dispatch orders in multiplayer games, relieving the server and making it more suitable to handle more players.

I didn't take this "all the way up" because I wasn't sure on how it would be received, and since this implementation is working (and I like MVPs) I decided to share it now.

### CODE REVIEW

**Comment by pchote** [comment]
I would be interested in seeing some measurements to indicate whether order dispatching really is a problem in practice. In my mental model of the networking, this is actually one of the least bottlenecked parts of the system.

**Comment by Leonardo-Ferreira** [comment]
On a 6v6 game if each player issue 1 order per second the dedicated server will have to deliver 121 orders each second (11 players issuing commands and 11 have to receive them). In this scenario, to maintain a in-second sync, the server would have 8.26 milliseconds per network IO. That is unrealistic for open-internet. Given this high-load scenario, I'd bet good money that `WouldBlock` would be triggered for a high percentage of times, specially during combat, where commands are issued in higher frequency.

BUUUUUUUTTT, for a 1v1 it's not a problem.

This not being a problem can be easily explained by the fact that 1 instance of a server can only handle 1 game. This however does not mean that the current implementation is ideal, specially if you take into consideration that 1 server handles a single game.

>this is actually one of the least bottlenecked parts of the system

Ok, one step at a time, im getting to know the system... if you'd like to point out places where you believe the bottleneck is more critical, I would love to help solving it...

I have a heavy background on server side and previous similar implementations have yielded enormous benefits. Not only it allows a better usage of available resources, it also improves the perceived response time by the client. Having this in place would even be a first step on having a single instance of the server handling multiple games.

**Comment by deleted-user-1** [comment]
Check out what @adammitchelldev has been working on. Adam has been working on the netcode for months, only to find out that fixing one thing breaks 2 other things and that the great potential for improvements (which he has made promising PRs for) is only topped by the complexity of not breaking the whole system by implementing them. I think you picked one of the hardest parts to work on and you might want to get more familiar with network model and OpenRA specific oddities before rushing changes. I'd be surprised if any of your server-side background included a lockstep network model.

**Comment by pchote** [comment]
I apologise if any of my comments are coming across as dismissive - i'm trying to be helpful by leaving to-the-point comments that can hopefully steer discussion from others, but I have too much going on right now to be able to write the kind of detailed explanations that would be needed to bring someone new up to speed on OpenRA's internal systems.

Like @matjaeck said, the lockstep networking model likely works differently to what you are expecting: the short version is that orders aren't sent in realtime and instead go through a couple of stages of batching and are forecast forward in the future to mean that the network protocol generally allows a ~360ms latency between an order being issued and it needing to be recieved by all other players. If you do a search for "OrderLatency" in the code you should be able to find the key parts of this system.

The biggest issue/potential win actually is related to your point though; right now spectators are treated the same way as normal players, which often leads to performance problems in games with large "spectator trains" (its not uncommon for a 1v1 game to have 10+ spectators in some cases) because any one person having performance problems will stall the game for all other players. OpenRA has three different types of orders; immediate, non-immediate, and sync. Only the immediate orders are needed for spectators, and these exist outside the lockstep. We could therefore significantly improve the stability of large spectator games by making sure that the client does not consider spectators in the lockstep loop, and by adjusting the main game loop for spectators to catch up at faster than real time if they lag behind. But again i'm sorry but I can't elaborate on all of these new terms in more useful detail.

**Comment by Leonardo-Ferreira** [comment]
> [...] to find out that fixing one thing breaks 2 other things [...]

yeah I came across one or two of these hehehehehe didn't touched them though

> I think you picked one of the hardest parts to work on and you might want to get more familiar with network model and OpenRA specific oddities before rushing changes

It's a fact that I don't know much about openRA, but the very reduced scope of this change compensates for that. By maintaining the compatibility and acting cirurgical-ly, I think I made a great trade off: very small change with a "good" impact on server performance.

If I know OpenRA better, I'd probably think of other places that needed maintenance/improvement also, but that doesn't disqualify my PR. I think its size is an added bonus.

On the end of the day, it's all about how "aggressive" you wanna be with your change and how much you want to fight for... I saw several improvements I could perform on the order distribution, ranging from grouping/queueing order by players, creating a dedicated tasks per player, segregating chat commands to a second connection, all the way up to getting rid of the lock stepping... but I decided to go small for now...

> I'd be surprised if any of your server-side background included a lockstep network model.

Never actually worked with it on real-world problems but I did already knew it from a class in college... but the beauty of my small PR is that all my changes are used AFTER the lock has been acquired! and it has no effect on it!

PS: I tested it playing 1v1 matches with my wife and the output was "as expected". I was able to maintain a moderate ping by playing via wifi while keeping the router on a closed room... ping was consistently above 50ms.

**Comment by Leonardo-Ferreira** [comment]
>I apologise if any of my comments are coming across as dismissive

Please, by all means, keep them coming... I really don't mind or thought of them in this way

>because any one person having performance problems will stall the game for all other players.

this is one of the things I noticed and decided not to touch right now directly... but, I hope, soon hehehehe

> We could therefore significantly improve the stability of large spectator games by making sure that the client does not consider spectators in the lockstep loop, and by adjusting the main game loop for spectators to catch up at faster than real time if they lag behind.

yeah this is a great idea and does not conflict in any way with my PR, if any, it would be enhanced by it!

if we could figure out a way to test high load scenarios, whether 6v6 or 1v1 + spectators, I'm sure my PR would output better numbers... would that be definitive enough to have this approved?

**Comment by adammitchelldev** [comment]
Hey @Leonardo-Ferreira it's the guy from the other networking PRs. I just saw this thread and feel like I can help clear up some of the communication here.

First, my understanding of this PR is that it shifts the network I/O to a non-blocking API. This shouldn't have any overall effect on the way that the networking works (lockstep or not) because lockstep is managed at a higher protocol level. In theory, this is a straight improvement that could help the server handle a higher number of concurrent players. However, I agree with @pchote here that this probably isn't a significant bottleneck right now, I'd hazard an educated guess that the blocking network send calls are actually still very fast, this improvement would probably only see a significant performance different in the hundreds to thousands on concurrent connections, assuming it is done correctly.

Unfortunately, their is risk when introducing these kinds of changes and there is a significant playerbase that want to depend on the reliability of OpenRA (tournament players). We'd need to do some rigorous performance testing or expert review to justify it IMO, making changes for theory's sake just introduces risk. For example here, you need a new method to handle exceptions, and I don't know what kind of exceptions it expects to handle; it is conceivable that the async method fails under slightly different conditions to the sync one (outgoing buffer full etc.) and that this will have difficult to measure impacts on reliability.

Now, I'd also like to talk about the other networking improvements I was working on, because it would be great to have someone with some enthusiasm behind this stuff to check them out! (And motivate me to work on them more!)

IMO, the critical failure of OpenRA networking is that it induces a very high, static, artificial latency and proceeds to "spend" that time inefficiently. The expected latency of a given order is as bad as 500ms (most games will target an input latency between 15 and 30ms when conditions allow, the less the better.) The design is pretty haphazard, which makes it difficult to follow and understand the "layers" of protocol and of the lockstep algorithm. This frequently means that there end up being implementation and design "mistakes" that cause orders to wait for 100s of ms before even being sent, basically negating the point of having the latency in the first place.

The latency *is* required to deal with the jitter of a player with a poor network connection and keep things running at a stable and full speed; any missing orders from any player necessarily stall the entire game. If the latency is too low, a player with a bad connection will cause the game to slow down significantly. The more connections there are, the higher the chance that jitter or a bad connection will ruin the game, and currently this is also true for spectators.

The changes I was working on attempt to address this problem first and I can prove that the result is very measurable because the PRs did actually work and I playtested it in real games to great effect. However, the changes themselves are a bit arcane and scary, they carry *much higher* reliability risks than the ones in this PR, and may create a debugging headache far beyond the netcode and into the actual game code, mainly due to the fact that orders being moved to different frames is not something the system has been tested against.

I already know that it causes crashes. We pushed off the changes because @pchote was dealing with too many things already for us to tackle it, and I couldn't do it alone, it would probably take over a major update cycle and playtesting phase (scary stuff.)

I actually have some time to work on this again, I'll be on the discord to chat about it.

**Comment by Leonardo-Ferreira** [comment]
Tks for your input @adammitchelldev.

I believe that the current implementation of server side order dispatching exacerbates whatever latency problem any single player is experiencing. This is because at some point the socket it will get block (delivering the order to the "lagged guy", and then caught in a exception) and retried with the intentional blocking setting. While this happens the server IS NOT dispatching to the others players. 
By using `async` the runtime could dispatch each order dispatch to a different thread (if as many are idle) and the notification phase could be done in 1/n (n=number of players+spectators) of the time. I know you guys focus more on the game player experience and not the server health/performance but this is a BIG win. And I'm not even talking about the server receiving communication from clients yet!

> The changes I was working on attempt to address this problem first and I can prove that the result is very measurable because the PRs did actually work and I playtested it in real games to great effect.

Well, mine are bit more subtle. You will feel them when you have a high number of orders flying around... or a packed game (3v3 at least, medium-high numbers of players to be notified of other players actions)... I also did several playtest (mostly 1v1 + 2 or 3 bots) with my proposed changes and would like to expand to a bigger human crowd. And yes, in several instances I did got the order dispatching at 1/4th of avg time (meaning that ALL the orders where dispatch and `await`ed in parallel)...

My question is simple: **what do I have to do to get this approved?** Wanna setup a 6v6 match on this dedicated server? Want to setup a 1v1 with 50 spectators?!? want me to instrument the code so we can compare

>Now, I'd also like to talk about the other networking improvements I was working on, because it would be great to have someone with some enthusiasm behind this stuff to check them out! (And motivate me to work on them more!)

To be honest, I don't think you will ever get your changes done... they are just too big and you're stale for almost 7 months... I'm trying to do the opposite of what you're doing: im trying to implement very small changes that will add up to something huge...

**Comment by adammitchelldev** [comment]
Hey @Leonardo-Ferreira I'm looking through this again and I want to clarify my assumption about the behaviour of `Socket.Send` as described here: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.send?view=netcore-3.1

A successful synchronous/blocking `Send` does not mean a network packet was sent and acked, it means only that the data has been buffered to be sent by the OS eventually. The only time it should block is if the outgoing buffer is full (due to the connection dropping out for a while), otherwise the operation should be on the order of ns or low us. A TCP window is 32k and orders very rarely exceed more than 100 bytes per net frame (120ms), so I find it unlikely that we'd actually ever block.

Please, check for me if you can by measuring the actual time taken for the send operation, and whether or not it ever blocks (run in non blocking mode and throw an exception if it ever fails to buffer the whole message). Try using Shopify/toxiproxy to simulate different latencies.

I don't doubt that going async is technically an improvement, but I think the server architecture for multiplexing clients should be better designed with this in mind first. I'd like to have a UDP driver too, which wouldn't benefit from this change. We should also look to define the actual timeout and failure handling behaviour, because right now it's ad-hoc.

**Comment by OpenOP2Admin** [comment]
ok, this is a very deep discussion and over my understanding. But just to ask:

1. Does this place more of the burden of the game on dedicated servers? (I hope so)
2. Will this allow OpenRA to act like every other modern game, where if one player is lagging, it doesn't cause lag or jitter for the other players? Meaning, the server will send the data, and if the client doesn't get back, then the ticks continue forward?

**Comment by Leonardo-Ferreira** [comment]
@adammitchelldev 

> A successful synchronous/blocking Send does not mean a network packet was sent and acked

No, it's the opposite. A blocking Send only returns after the ack (per documentation `If you are using a connection-oriented protocol, Send will block until all of the bytes in the buffer are sent`). The non-blocking on the other hand has no guarantees (per docs `In nonblocking mode, Send may complete successfully even if it sends less than the number of bytes in the buffer`).

You are correct about that 32kb TCP window, what you're not taking into account is that most OSs have that "adjustable" (decreasing/increasing that value according to RTT and other metrics) and that despite a single order not taking more than 100 bytes, on larger matches (during combat especially) their volumes increases immensely (moving lots of units at once)... its no surprise that there's the fallback for blocking send...

Because the async implementation actually happens in a separated thread (in windows, they are known as IOCP, `io_uring` for linux) there is no need to use the non-blocking setting. So, it's guaranteed delivery, on completely group of threads, not blocking computation... its a win win!

@OpenOP2Admin 
>Does this place more of the burden of the game on dedicated servers? (I hope so)

Dedicated server

>Will this allow OpenRA to act like every other modern game, where if one player is lagging, it doesn't cause lag or jitter for the other players?

this, alone, no it will not. but this is a first step to that goal also. This could reduce the sensitiveness of a player with a bad connection. Today all other are derived to players sequentially. What happens if the first player on the loop lags? all other simply sit there awaiting, doing nothing. The whole operation also takes a lot longer, because the duration is the sum of all players acknowledging the orders.
Now, when orders are delivered in parallel, the duration of. order distribution is the slowest player only, and not the sum! We will await for all acknowledgements but also in parallel.

>Meaning, the server will send the data, and if the client doesn't get back, then the ticks continue forward?

No, but this also open the door to that possibility

**Comment by pchote** [comment]
> its no surprise that there's the fallback for blocking send...

Actually this fallback is there for the lobby state! Some of the orders there to sync the server / client state contain large blobs of miniyaml. Has anyone done a test to measure if/how often we fall back to the blocking send after the game has started?

**Comment by deleted-user-1** [comment]
> what do I have to do to get this approved?

@Leonardo-Ferreira Over the past months an important aspect of it was to wait (there are even people who get their PR closed after 7 months and thankfully resubmit).

**Comment by adammitchelldev** [comment]
@Leonardo-Ferreira this is also written after the part you quoted:

>There is also no guarantee that the data you send will appear on the network immediately. To increase network efficiency, the underlying system may delay transmission until a significant amount of outgoing data is collected. A successful completion of the Send method means that the underlying system has had room to buffer your data for a network send.

My interpretation of this is that it applies to both blocking and non-blocking mode, and that the difference between those two is the behaviour when the outgoing buffer cannot accommodate the whole message. I would believe that the outgoing buffer would stretch to 32k if needed. If our messages were large, they would likely end up blocking on a round trip (or more), which would be a problem, but I have a very hard time believing that this will be the case in OpenRA.

In fact, it wouldn't make sense at all, TCP connections 
at the application layer have no concept of a message, it is a continuous bi-di stream. There is no meaning to waiting for an ACK because you can't give TCP a message *to* ack. Instead, acks are done by sending data back from the server side in response.

**Comment by adammitchelldev** [comment]
@OpenOP2Admin

My PR here does exactly what you're asking for: #18783

**Comment by Leonardo-Ferreira** [comment]
> the underlying system may delay transmission until a significant amount of outgoing data is collected

Although technically possible, we use the [`NoDelay` switch](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.nodelay?view=netcore-3.1#remarks) which should override that.

I believe that whatever came after `In nonblocking mode, Send may ...` only applies to non blocking mode, but i'll open a documentation issue with MS asking for clarification. My experience in low level networking (including [Cassandra database drivers](https://github.com/datastax/csharp-driver and other proprietary code) tells me otherwise...

 >There is no meaning to waiting for an ACK because you can't give TCP a message to ack

_ack_ representing the confirmation that the package was delivered is why we use TCP. If we have no use for the ACK we should be using UDP. Thats why I do believe that a blocking send will actually wait for the network ACK... [TCPClient docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient?view=netcore-3.1) also back my view...

Although I love a good discussion I think we're getting out of point here though...

**Comment by adammitchelldev** [comment]
I don't think we're getting out of point here, this discussion is pretty
fundamental to understanding this PR.

I am 99% confident that socket send does not block until an ACK is
received. This would mean that each send is blocked for a full network
round-trip, and that would have been noticeable long before now. My
rewritten netcode doesn't suffer from this problem; I can attach clients
with 5 seconds of latency and the socket Send does not block for 5 seconds.

TCP is not about guaranteeing that you know that a message will be
delivered, it's about guaranteeing that the data stream will be processed
in the exact order it is logically sent, transparently to the user. It is
also about flow control and traffic management.

A TCP send from an operating system API perspective places data into the
network out buffer, the actual sending and receiving is handled separately.
This is how it works on Linux and .Net would have to jump through
significant hoops to behave differently.

I can write up some test scenarios for you if you'd like using toxiproxy
(it has a .Net API) that prove that send doesn't block for a network
round-trip.

**Comment by pchote** [comment]
This was superseded by the server and order rewrites, closing to help clean up the PR queue.

**Pull request closed without merging**
