### PR TITLE
Remove the dead ActorGroupProxy trait

### PR DESCRIPTION
**Pull request by abcdefg30**
It didn't receive any updates in a long time, so I don't think there's a reason to keep it.

### CODE REVIEW

**Comment by reaperrr** [comment]
If we're completely removing this, I'd vote for doing so for this release already (i.e. merge before playtest, if possible).

**Comment by pchote** [comment]
This has shipped as-is in the last 41 releases.  One more isn't going to change much!

**Comment by reaperrr** [comment]
...Point taken :)

**Comment by GraionDilach** [comment]
It will! That makes it The Answer To Everything!

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by reaperrr** [comment]
Needs rebase.

**Comment by abcdefg30** [comment]
Rebased.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9bc45e9c364cf7fea6c17c43071e29cbaa5d1ab8...177a97ac84541dad1e975905faae3dd6552c84f0)

**Pull request merged**
