### PR TITLE
Add unique beacon and join/leave/change sounds in lobby

### PR DESCRIPTION
**Pull request by Porenutak**
Sound file MULTI1.WAV is not used anywhere and there for can be used as becon sound instead of CHAT1.WAV

### CODE REVIEW

**Review by PunkPun — COMMENTED** [review]
Ah, it seems I forgot to leave a comment here.

I dunno when and if #6246 is going to get implemented, but it would be good to think about the sounds d2k should use. It would not be great if this sound overlapped with join / leave

**Comment by Porenutak** [comment]
> I dunno when and if #6246 is going to get implemented, but it would be good to think about the sounds d2k should use. It would not be great if this sound overlapped with join / leave

@pchote suggested on discord that it should be added in separate PR. But I need to by this PR merged first, because I wanna use new beacon sound also for joining/leaving

**Comment by PunkPun** [comment]
my entire point that these things should have unique sounds. I think beacon and join/leave matching sounds would be confusing to say the liest

**Comment by Porenutak** [comment]
As you suggested here:
https://github.com/OpenRA/OpenRA/issues/6246#issuecomment-1598720579

I would like to go
For Join lobby: CHAT1.WAV

[CHAT1.ZIP](https://github.com/OpenRA/OpenRA/files/14493343/CHAT1.ZIP)

For leaving lobby: CHAT1.WAV but reversed (Can ORA reverse sound?)
[CHAT1_REVERSE.zip](https://github.com/OpenRA/OpenRA/files/14493354/CHAT1_REVERSE.zip)

and for chat it self ENDLIST1.WAV or SIDEBAR1.WAV
or just stay with CHAT1.WAV

[ENDLIST1.ZIP](https://github.com/OpenRA/OpenRA/files/14493389/ENDLIST1.ZIP)
[SIDEBAR1.ZIP](https://github.com/OpenRA/OpenRA/files/14493390/SIDEBAR1.ZIP)

**Comment by Porenutak** [comment]
Added lobby sounds:
Join: CHAT1.WAV
Leave: CHAT1REVERSE.WAV
Options: SIDEBAR1.WAV



Know issue:
Because of Default variant in notification definition I cannot use nameming convention in bits folder for CHAT1REVERSE

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9cc927e3c4ad0beb6da030c92c266959d192ecca...7f3976eeab3b3af38c00679df9507b46142a5588)

**Pull request merged**
