### PR TITLE
Hide the owner row of FCOM

### LINKED ISSUE #9565: Soviet02a shows owner row for forward command and oil pump
Soviet02a shows owner row for forward command and oil pump

fcom
op

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27230391-soviet02a-shows-owner-row-for-forward-command-and-oil-pump?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Follow up of #9448.
Fixes #9565.

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
There must be some regression, I was running June release and the tooltip was hidden on both. Updated to current release and it is here.

**Comment by abcdefg30** [comment]
Yeah, I got it now. `^TechBuilding` (and also `^CivBuilding`) don't inherits `^Building` anymore.
Should I just disable the tooltip at `^BasicBuilding` and drop the rest?

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0b2ca66206d1851a474e213af9178766a6037e86...29921d4f580101406cc9baa5a1c12c1c3437bfcb)

**Pull request merged**
