### PR TITLE
RA - Add more Long Bridges

### PR DESCRIPTION
**Pull request by MustaphaTR**
These were wanted by mappers for a long while. For now it is just Temprate and Snow. I asked Nooze to make Desert version too, he said he won't be able to complete it before next release, and i would like to see these in for it. We can add the Desert ones later.

temprate bridges

snow_bridges

This PR also moves Bridges to its own .yaml file, i guess we have enough of them.

Another thing, i added small Targetable offsets to 2x2 bridge repair hut. Engineers were not entering from north (west for horizontal one) otherwise.

### CODE REVIEW

**Review by Arular101 — COMMENTED** [review]
This is a nice addition to improve the original game.

There are sadly some issues. If the horizontal bridge is attacked by a submarine from the north side, it gets destroyed way too fast. But if the submarine attacks it from the south side, it doesn't get destroyed.

~Second issue is with the vertical bridge. If it gets destroyed, the north side doesn't look good.~ Edit: you are right, the bridge tiles overlapped there.

**Comment by MustaphaTR** [comment]
You probably placed the bridges wrong, it is not how it is meant to look like. I guess you overlapped them.

**Comment by Smittytron** [comment]
@Arular101 is right about the sub damage on the horizontal bridge. Four torpedoes will down it from the top and it cant be damaged from the bottom. 
If you select a sub and hold down force fire, then hover over each cell you'll see the south of the bridge is untargetable. I reckon that has something to do with it. The top tiles for the vertical and the new diagonal bridge also have a couple of untargetable spots.

**Comment by MustaphaTR** [comment]
Updated. Wanted to give submarine issue a proper fix, bridges in ra mod now have proper hitshapes and footprints. Previously all Long Bridges had 4x2 footprint and 1x1 hithape. This increases the damage that would be dealth by submarine if i haven't edited its weapon, so i got rid of `Concrete: 500` from `TorpTube` instead.

This PR may effect balancing a bit now.

Here are screenshots of HitShapes, as you can't see without adding `CombatDebugOverlay:` to `^Bridge:`

newlongcombat
oldlongcombat
shortcombat

**Review by Arular101 — APPROVED** [review]
👍 Nice work!

Code and balance looks good to me. The only thing that maybe needs to slightly change is the horizontal bridge again. From the bottom the submarine can destroy it with 6 torpedo's. I think if the hitshape is 1 or 2 pixels higher it should receive a little less damage. From the top it takes 17 torpedo's.

The diagonal bridges varies a bit with the angle of the torpedo's, but it is between 8 and 18 torpedo's, so I consider this as fine.

Destroying the bridge with Tanya/tanks/V2, and repairing with the engineer works.

The art work is also fine. The horizontal and vertical bridges uses the artwork of the single cell bridges. It looks slightly different compared to the diagonal bridges, but this is also fine.

Looking forward to see these bridges in new maps. We just needs to get used to see different bridges now :P

**Comment by MustaphaTR** [comment]
Updated, decreased Horizontal bridge `BottomRight:`s a bit.

**Comment by Arular101** [comment]
untitled
The left segments are forgotten. The rest is good now (11 torpedo's).

On the horizontal bridge again, if I force-fire the sides of the bridge (the sidewalls), the cursor is invalid. Any idea why this happens only at that bridge?

**Comment by MustaphaTR** [comment]
Updated.

> On the horizontal bridge again, if I force-fire the sides of the bridge (the sidewalls), the cursor is invalid. Any idea why this happens only at that bridge?

`Interactable:` traits were not properly set either. Should be fixed now.

**Comment by Smittytron** [comment]
> Interactable: traits were not properly set either. Should be fixed now.

Can't speak for the code, but bridges work and look good too. 👍

**Comment by Arular101** [comment]
I tested the bridges again, and I found another thing. Hope you don't mind it that I didn't find it at the first time. The damaged horizontal en vertical bridges can't be force-fired too. It's about these parts:
untitled
These parts can be destroyed but the cursor gives invalid target again. After this it should all be good now.

**Comment by MustaphaTR** [comment]
Looks like dead bridge tiles are not targetable. I'm not sure if it is something that can be fixed in .yaml level and same is happening with other 2 too, not just vert. and hor.

**Comment by Arular101** [comment]
Hmm I think the issue is that the horizontal and vertical parts are 3 cells long, where the last cell can be destroyed (but not passable, but it is needed to destroy it to pass the bridge in the picture from my last comment). The diagonal bridges are 2 cells long, and don't have a part that can be destroyed.

You won't belief it, but I found another strange issue :( I wanted to measure the cells by parking some submarines in the gaps. But strangely the submarines in the horizontal and vertical bridges would get stuck there, also the submarine in the bottom right. There is no way to move them. This didn't happen at the diagonal bridge.
openra-2017-12-24t120457220z

**Comment by MustaphaTR** [comment]
Middle pieces at the previous images are techically dead. Tile to use is selected depending on if there is a not dead bridge attached to them. I got similar thing with diagonal one, will send a SS in vase you didn't understand and take a look to Subs geting stuck when i get to PC, i'm on phone rn.

**Comment by Smittytron** [comment]
> Looks like dead bridge tiles are not targetable.

#11632

**Comment by Arular101** [comment]
I don't know. This is what I did:
1 - Build a horizontal bridge with the following tiles: 1x left, 1x middle, 1x right.
Also build a damaged horizontal bridge (that is still passable for land units) with the following damaged tiles: 1x left, 1x middle, 1x right.
2 - Force-fire the middle of the bridge with submarines.
3 - The middle of the bridge is now destroyed but not passable for the submarines.
4 - Force-fire the left and/or right tiles. The damaged left and/or right tiles are not targetable, but by force-firing the sidewalls it can still damage and destroy those tiles.
5 - Now there is a gap for the submarines to pass.
6 - Order the submarines to cross the gap.
7 - When they are in the gap. Give a stop command.
8 - Now give an order to move around. The submarines are stuck in the gap.

untitled
_All submarines are selected and ordered to go to the top left. Only the top submarine moves._

This doesn't happen with the diagonal bridges.
The real case scenario for this is that it could happen when a submarine is attacking an enemy ship and the submarine is at that moment in the gap of a _broken_ bridge.

**Comment by Arular101** [comment]
untitled

You where talking about part 2 and 4 not targetable. That's correct and that also happens to the diagonal bridges. But I was talking about part 4 and 6.

Part 1 and 3 are targetable. But when they are damaged like in part 4 and 6, they are not targetable anymore. They are however still destroyable. Same for the vertical bridge.

**Review by chrisforbes — CHANGES_REQUESTED** [review]
Seems this still needs more work.

**Comment by MustaphaTR** [comment]
I tested that stuck units problems, and managed to reproduce that with land units too, on an initially broken bridge. Something in pathfinder looks like isn't checking current state of the bridge, but only the initial state/actual terrain. I can aslo move the stuck land unit in bridge fine, when i order it out, it doesn't move.
resim

I guess it isn't happening with diagonal bridges due to their shape.

**Comment by MustaphaTR** [comment]
And it looks like that is not something i can solve myself.

If we really want the NW-SE bridge, i may drop the vertical and horizontal bridges for now and get that added.

**Comment by GraionDilach** [comment]
That stuck bug sounds like #9378.

**Comment by Arular101** [comment]
Okay, for now we can have the other diagonal bridge to be on the safe side. That will give map makers already a big flexibility.

**Comment by Smittytron** [comment]
> Okay, for now we can have the other diagonal bridge to be on the safe side. 

Would close #12874 if we can get that through.

**Comment by Arular101** [comment]
Any news from Nooze about the diagonal desert bridge?

**Pull request closed without merging**
