### PR TITLE
Fix units warping from an exit subcell to cellcenter when produced

### LINKED ISSUE #9678: Weird visual 'drop' when vehicles exit factory in TS
Only noticable in isometric perspective. They suddenly 'drop' by a few pixels when they move past a certain point after exiting the factory. Applies to voxel and sprite actors alike, so probably not just a visual issue.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27509822-weird-visual-drop-when-vehicles-exit-factory-in-ts?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by teees**
Fixes #9678

Before:
https://streamable.com/jhed
After:
https://streamable.com/p5wg

### CODE REVIEW

**Comment by pchote** [comment]
Oops, well that was silly!  How does this behave for infantry, which should ideally be making use of subcells?

**Comment by teees** [comment]
Hmm I checked that shortly and thought it was alright, turns out it isn't. Infantry clips through each other. Probably better to fix it in Mobile.MoveIntoWorld and check if the unit can actually use subcells?

**Comment by teees** [comment]
This should now be the right behavior for `MoveIntoWorld`, which also fixes the production bug

**Comment by Mailaender** [comment]
:+1:

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3eb9b4a2a04f54c11b7f66412b982e6912702b53...c4ef2f40894524c00434ed2c7f65768747699a31)

**Pull request merged**
