### PR TITLE
Enable mechanic voices from Aftermath

### LINKED ISSUE #18962: Wrong and unused Mechanic audio files in Red Alert
Field mechanics (Allied support units) are missing two "Move" audio files **myes1.aud**, **mrise1.aud** which were falsly coded as their "Select" voices. These were also missing the file **mlaff1.aud**. Furthermore their "Action" voices are lacking the **myeehaw1.aud**.

Those missing aud files are all available in OpenRA's Red Alert sounds.mix.

I fixed my **voices.yaml** in OpenRA\mods\ra\audio like this:

MechanicVoice:
	Voices:
		Select: mhuh1,mhowdy1,**mlaff1**
		Move: mboss1,mhear1,myes1,mrise1
		Action: mhotdig1,mwrench1,**myeehaw1**
		Die: dedman1,dedman2,dedman3,dedman4,dedman5,dedman7,dedman8
		Burned: dedman10
		Zapped: dedman6

Now our mechanics have the appropriate aud files Weswood Studios originally assigned to them in 1997's Aftermath expansion for Command & Conquer: Red Alert.

I hope that this issue gets fixed for the next OpenRA release.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #18962.

As said in https://github.com/OpenRA/OpenRA/issues/18962#issuecomment-751285143 I'm not a fan of `mlaff1`, but included it in this PR so others can easily test it and give their own opinion.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]
Personally I'd add `mlaff1` just because it's an original asset. It's dumb, but it's rather tame compared to the direction RA2 and RA3 took.

+1 Yee Haw for sure.

**Comment by VonNah** [comment]
Abcdefg30, you didn't remove **myes1,mrise1** from "Select" and didn't add them to "Move".  

As I wrote in my issue it has to look like this:

MechanicVoice:
Voices:
Select: mhuh1,mhowdy1,**mlaff1**
Move: mboss1,mhear1,**myes1**,**mrise1**
Action: mhotdig1,mwrench1,**myeehaw1**
Die: dedman1,dedman2,dedman3,dedman4,dedman5,dedman7,dedman8
Burned: dedman10
Zapped: dedman6

Thank you!

**Comment by abcdefg30** [comment]
Fixed.

**Review by pchote — APPROVED** [review]
*Yee Haw* 🤠

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/65be4f93ff0ac708f979f34c508c9b49d3d8fd77

01204eb414cfc12555580a5c867cc4a813e72dd2
5249841ab761972aecd785e5fa93f1cea3e5c20b

**Pull request merged**
