### PR TITLE
Fixed a crash when replay is selected in the wrong mod

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/10101.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Perhaps we should just remove the flag widget if the faction doesn't exist, in case a mod doesn't provide a "Random" flag?

:+1: Works though, so happy to take as-is.

**Comment by Mailaender** [comment]
I also thought about it, but the faction "Random" is hard-coded in other parts of the engine as well.

**Comment by obrakmann** [comment]
I'm a bit torn on this. On the one hand, I think it's wrong that the replay browser even considers invalid replay files at all, since #10101 is clearly a user error (I just came up with [this](https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:fix10101_discard-invalid-replays-in-browser) to fix that), on the other hand, there'd be no way - at least not a nice one - to inform the user about the issue, which also sucks.

Ho-hum. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/e9f4161a484539117537f78b16c2435917f53dbf)

**Pull request merged**
