### PR TITLE
Refresh TD 1v1 map choices

### PR DESCRIPTION
**Pull request by pchote**
This adds some maps suggested [on the forum](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=18726): [LostSouls](http://resource.openra.net/maps/5913/), [Island Duel](http://resource.openra.net/maps/4924/), [Sandstorm](http://resource.openra.net/maps/4609/), and [Aggressive Tendencies](http://resource.openra.net/maps/5858/).  I've also removed Deterring Democracy and Letters from Lexington as a start towards balancing out the map author distribution.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: Also can't spot any tile placement errors. :white_check_mark:

**Comment by abcdefg30** [comment]
:+1:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0866ef76eaceeead4ca882c2708f7c39bc2fa61f...26ffa935a4a33f1a51872b5bf2754b43562b1208)

**Comment by AoAGeneral** [comment]
Looks good to me. Though I would suggest removing Profit over People instead of Deterring. Deterring is a very popular 1v1 map and Profit is rarely played as it is. Letters doesnt get played to often due to the Visceroid movements in the start.

**Pull request merged**
