### PR TITLE
Replace INotifyCreated with a priority queue & block upgrades until manager is notified

### LINKED ISSUE #8444: Elite weapon(s) in TS broken
I don't know yet whether this is a yaml or code issue, but in any case elite weapons don't work.

The Nod bike should get the HoverMissile @ elite, but it doesn't.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21036885-elite-weapon-s-in-ts-broken?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by atlimit8**
This replaces INotifyCreated with a priority queue and gives UpgradeManager a much more immediate priority.

Should be what was requested in #8444.
Assuming TimedUpgradeBar is the problem, this fixes #8444.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Something like that, as I seen in this diff. https://github.com/OpenRA/OpenRA/compare/bleed...matija-hustic:upgradable_construction_order

**Comment by atlimit8** [comment]
That might cause problems if the actor is constructed without entering the world; passengers for example.

**Comment by GraionDilach** [comment]
Well, I don't take a side in this particular PR. This is something you, @matija-hustic  and someone with a lot more experience about trait-load-orders should discuss.

**Comment by atlimit8** [comment]
Is that in a PR?

**Comment by penev92** [comment]
You can simplify (and beautify) this by having an `IsInitialized` field on `UpgradeManager`, that is set by `INotifyCreated`.
However, the whole idea that we need such a workaround doesn't sit well with me.

**Comment by matija-hustic** [comment]
I had a rough idea of removing `IUpgradable` in favor of using only `UpgradableTrait` seeing how basically all upgrades can be derived just from that one trait (the only exception being `GainsStatUpgrades` and its descendants now with #8572). If this were the case, the construction order might be able to be resolved by simply using `Requires<UpgradableTraitInfo>`. Haven't looked into this more deeply tho. Just an idea

**Comment by atlimit8** [comment]
UpgradeManager may not be the first trait to recieve `INotifyCreated.Create(this)`; I considered using it.
However, It must unlock on (or before) the first call after all of the traits are created even if that is *another_trait*`.Created(this)`.
The only other solution that comes to mind is integrating UpgradeManager into Actor, which is probably undesirable.

**Comment by atlimit8** [comment]
Well, another interface could be constructed, but that would be introducing degrees of Created.

**Comment by atlimit8** [comment]
I suppose a `INotifyTraitManagerOfTraitsCreaeted` that is implemented only by trait managers and those managers are careful about accessing each other.

**Comment by pchote** [comment]
This looks super overcomplicated. Just run the offending code in UpgradeManager from a FrameEndTask instead.

**Pull request closed without merging**
