### PR TITLE
Clear LastSearchFailed when starting a new FindAndDeliverResources activity

### LINKED ISSUE #16982: Harvester.LastSearchFailed leaks between activities
If a new `FindAndDeliverResources` activity starts running while (a) having a partial load and (b) `Harvester.LastSearchFailed` was set to `true` by a previous activity the harvester will insist on dumping its partial load before moving to harvest anything new. Originally reported by Willow on the Discord channel.

Simple repro case:

1. Add
   ```csharp
   if (order.OrderString == "Stop")
       LastSearchFailed = true;
   ```
   to the top of `Harvester`'s `ResolveOrder`
2. Build a harvester and let it harvest a partial load
3. Issue a stop command
4. Issue a harvest command.

Expected behaviour: harvester harvests the requested cell until it is full.
Actual behaviour: harvester insists on unloading before continuing.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #16982.

### CODE REVIEW

**Comment by tovl** [comment]
This looks good. However, it would probably be cleaner if `LastSearchFailed` was a field of `FindAndDeliverResources` instead of `Harvester.` There is only one reference to `LastSearchFailed` outside of `FindAndDeliverResources`: in `HarvesterBotModule`.

As an aside, that particular line in `HarvesterBotModule` looks a bit fishy anyway. I'm not sure if `Nextactivity` is at all relevant here.

**Comment by pchote** [comment]
Good point. Updated.

On closer inspection that `NextActivity` check was preventing `HarvesterBotModule` from ever rescuing harvesters stuck in the `FindAndDeliverResources.Wait` state, so I removed that in addition to moving the flag.

A simple testcase to verify the fix is to create a map with a small resource patch (with no tree/mine) near the AI base, and a second path far away. On bleed the harvester will stop outside the refinery after harvesting the first patch. Now they will move to the next patch.

**Review by reaperrr — APPROVED** [review]

**Review by tovl — APPROVED** [review]
:+1:

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e3719d067d2d20a3c6dffff312d02c2bc1b0d77a...faccbcc217701a5363a2f1d0e3e003c9cb9c2d0b

**Pull request merged**
