### PR TITLE
Fix water splashes on bridge in RA

### LINKED ISSUE #13989: Attacks on bridges play both water and ground impact animations
Using Playtest 20170902 and the base RA mod.

Pretty easy to reproduce. Attack bridge sections that are over water. Both animations get played.
Not present in Playtest 20170304 or Release 20170527

openra-2017-09-06t182144151z

### PR DESCRIPTION
**Pull request by reaperrr**
On bleed, both the explosion as well as the water splash warhead of weapons triggered on bridges, since they have both the Ground and Water target types.

Ground cannot be made invalid for water splashes without causing regressions elsewhere, so a new Bridge target type is introduced to explicitly make bridges invalid targets for water splash effect warheads.

Fixes #13989.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
The Submarine's TorpTube CreateEffect isn't functioning vs bridges.

-All other weapons & explosions look good. :+1:

**Comment by reaperrr** [comment]
Updated, fixed TorpTube. See commit desc for details.

**Review by ghost — APPROVED** [review]

**Review by obrakmann — APPROVED** [review]
lgtm, 👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5d8cd5183500f980faeb864852d0d26135fcc688)

**Pull request merged**
