### PR TITLE
Removed myself from the active developer list

### PR DESCRIPTION
**Pull request by Mailaender**
as my commitment to the code has been pretty low recently and I don't see making a huge comeback. I am happy that new contributors are resuming what I started.

### CODE REVIEW

**Comment by pchote** [comment]
Thanks for all your contributions over the last 5 years!

**Review by pchote — APPROVED** [review]

**Comment by GraionDilach** [comment]
Sad to see this happening. :(

**Comment by TheRaffy** [comment]
Thanks for all the work Mailänder!!! have a great time, with what ever you will do now 👍

**Comment by reaperrr** [comment]
Thanks for all the work, I hope you'll still contribute occasionally if you find the time!
You're still 3rd place in terms of merged commits and 2nd place in terms of changed lines, and I think even I won't be able to catch up, which shows just how much this project owes to you 👍

**Pull request merged**
