### PR TITLE
Red Alert: Corrects spelling in "Asymetric Battle" map.

### PR DESCRIPTION
**Pull request by deniz1a**
Changes map name to "Asymmetric Battle".

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
:+1:for polish

**Comment by deniz1a** [comment]
This map: http://resource.openra.net/maps/50/

**Comment by Mailaender** [comment]
Thanks.

@ihptru Can you update http://resource.openra.net/maps/50/ please?

**Comment by ihptru** [comment]
New revision: http://resource.openra.net/maps/4453/

**Comment by Mailaender** [comment]
Thanks.

**Pull request merged**
