### PR TITLE
Fix crate drop aircraft spawn height.

### LINKED ISSUE #8877: Planes coming in from map edge start at higher altitude
...than their cruise altitude.

Best seen on RA badgers with shroud/fog disabled.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25258621-planes-coming-in-from-map-edge-start-at-higher-altitude?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #8877.

### CODE REVIEW

**Comment by reaperrr** [comment]
Same for ProductionAirdrop in Mods.Cnc.

**Comment by pchote** [comment]
Nope, that one is fine as-is.

**Comment by Mailaender** [comment]
Fixed as promised. :white_check_mark:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/f47f0bc9551731c902f0a91355410da2f1b135b2%5E...f47f0bc9551731c902f0a91355410da2f1b135b2)

**Pull request merged**
