### PR TITLE
Add Docker files to compile and launch games inside container

### PR DESCRIPTION
**Pull request by randomnoise**
Minimally invasive Docker files and shell scripts to compile the code, launch the games inside the container and to work with Linux's visual and audio devices, download necessary external files and see the Multiplayer servers from container.

I've tried not to change the rest of the code, to make this stand-alone as possible as a first phase. It is not optimized to work for publishing the games, it is more of a development image; though compiled games run performantly in container for Linux.

I have tried to create small interface for this. For example, when below commands run from the terminal:
```
make clean
docker build . --tag openra
chmod -v +x docker-launch.sh
./docker-launch.sh
```
it should compile and launch the initial zenity's Game Mod's choice prompt.

You can interact with and get in the container with:
```
./docker-launch.sh bash
```
and it should give you
`
/openra# 
`
prompt. Then, you can work with it however you want, e.g.:
```
/openra# make && ./launch-game.sh Game.Mod=ra
``` 
and you can enter the OpenRA directly.

Related to #20997.

---
**A known situation**: If any internet browser (Firefox in my case), audio/video players are open, the container cannot access the audio devices, it is locked out. For that situation, audio does not work. Other than that, audio works without a problem.

### CODE REVIEW

**Comment by randomnoise** [comment]
When it works, zenity menu working from container:

zenity-from-container-23-08

And container can access to video device:

openra-in-container-23-08-

**Comment by Mailaender** [comment]
I think @docker is useful in server scenarios, but not on the client. This feels wrong. What I could see is that we maintain something like https://github.com/rmoriz/openra-dockerfile in the @OpenRA namespace but separately.

**Comment by abcdefg30** [comment]
Hi and thanks for the contribution. I fear a docker container would get outdated pretty fast as no one on the core team uses it. A good compromise could indeed be having the scripts etc. in a separate repository like what @Mailaender suggested.

**Comment by abcdefg30** [comment]
@randomnoise do you think it is feasible to host everything needed for Docker in a separate repository? I could create an empty repository under the OpenRA org and you could send a PR to that then. Of course you can also just create your own repository if you like that better.

**Comment by randomnoise** [comment]
@abcdefg30, putting Dockerfile and shell file in the same directory with repo made the most sense, because one can easily linked the files from the repo in container as a volume, hence the PR.
As a second option, I think Docker files can work with the OpenRA repo if it is added as a `git submodule` or `git subtree`, so yes, I think it is feasible.

I don't know anybody will be interested to use Docker container for OpenRA development, if anyone tries it and encounters any problems, I think I will be responsible initially to solve those issues. Opening my repository will be easier for that, I think.

If enough people is interested and make more sense to move it under OpenRA, we can transfer it easily here, without much problem.

Thanks for getting back to me about this after the pr is closed 👍

**Comment by abcdefg30** [comment]
Ok, that makes sense. 👍

**Pull request closed without merging**
