### PR TITLE
Added a warning about custom game rules

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/8651.

### CODE REVIEW

**Comment by penev92** [comment]
Works :+1:

**Comment by Unit158** [comment]
:+1:

**Comment by pchote** [comment]
In the longer term I think this would be better represented with some kind of icon on or near the minimap display, but this solves the problem acceptably in the short term.

**Comment by penev92** [comment]
Yeah, a visual representation on the map would be nice.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/6dc7b0f05ebeaafd0365829e516e7aafe3743b97...ec4cee53d9d35d50aad40cf901e1f54bcf2dba53)

**Pull request merged**
