### PR TITLE
Fix SpawnActorPower not playing launch sounds

### LINKED ISSUE #13735: SpawnActorPower: Sound Bug
When using **SpawnActorPower:** for mods etc.

On current release build, 

Both:

`LaunchSound:`  and `LaunchSpeechNotification:`

Fail to function when they are used.

`DeploySound:`  works, but this is also heard by all players. (I imagine thats intentional?)

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #13735.

Simple and obvious enough to go into stable, I think.

### CODE REVIEW

**Comment by reaperrr** [comment]
@Inqubi confirmed the fix in #13735.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
Actually, now that I think of it. Shouldn't this go after the `info.Actor != null` check? (I.e. next to `Game.Sound.Play(SoundType.World, info.DeploySound, location);`?).

**Comment by reaperrr** [comment]
Actually, that `info.Actor != null` check is bogus, because the Actor field has FieldLoader.Require.

**Comment by abcdefg30** [comment]
What happens when you use just `Actor: ` in yaml? The field would probably be parsed as `""`, so that check should be replaced by `IsNullOrEmpty`?

**Comment by reaperrr** [comment]
> What happens when you use just Actor: in yaml? The field would probably be parsed as "", so that check should be replaced by IsNullOrEmpty?

In my opinion using `Actor:` in yaml is bogus, if someone wants to disable it the whole power should be disabled.

Anyway, I don't want to take any risks or delays for stable so I just moved the PlaySounds() into the FrameEndTask, we can still file a follow-up for bleed later.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9ade25e38a25d80acae789d81ced18cb1ad31f74

4adee762d9

**Pull request merged**
