### PR TITLE
Shift+hotkey queues 5 units for production. Fixes #5544

### LINKED ISSUE #5544: Shift-keystroke for queueing 5 units at a time
It would be great if you could use the keyboard to queue 5 units at a time.

Take building a rifleman (shortcut key = `i`) as an example. Currently,
* clicking the Rifleman tile queues 1 unit
* shift-clicking the tile queues 5 units
* hitting the `i` shortcut key queues 1 unit
* hitting `shift-i` queues 1 unit

It would be great if the last case (`shift-i`) queued 5 units, so the shift modifier works the same whether you're clicking or using a keyboard shortcut. I swear it used to work this way in a previous release (could be mis-remembering), but it would be a nice addition regardless.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2494508-shift-keystroke-for-queueing-5-units-at-a-time?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ace-timr**

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
Works as promised :+1:

**Comment by x-a-n-a-x** [comment]
I could queue 15 riffle infantry units very quickly and I also added 5 rocket soldiers to the queue. 
Then, I tried to un-queue all these rocket soldiers at once with shift+right click without any problem.

It works fine. :+1:

**Comment by obrakmann** [comment]
Seems to work as expected. Didn't find any unwanted side-effects. :+1: 

It would be nice to also be able to cancel production using hotkeys, eventually.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/4eab3dd1146fc92735b763f11813c5b1223ded79)

**Pull request merged**
