### PR TITLE
When restarting the game, Swap .dll for .exe in the path

### LINKED ISSUE #19518: Crash when restarting the game after changing between fullscreen and windowed mode
I consistently get the following when changing from `Windowed` mode to `Fullscreen` or back and then restarting from the settings menu using "Restart Now":
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### PR DESCRIPTION
**Pull request by chrisharris333**
Fixes #19518.

### CODE REVIEW

**Comment by pchote** [comment]
Nice work finding out what is causing the crash, but this doesn't look like the right fix!

The path should be fixed before it is written into the metadata database, rather than after reading it back.
On Windows, this is done around https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.WindowsLauncher/Program.cs#L89.

I don't understand why this would be giving .dll here, this might need more investigation.

**Comment by chrisharris333** [comment]
Thanks for pointing me in the right direction, I'll look around where you mention and see if I can figure anything out.

**Comment by pchote** [comment]
Actually, I guess that #19518 was probably after running through launch-game.cmd rather than the exe launchers. That should be passing `Engine.LaunchPath` similarly to `launch-game.sh`, but isn't.

**Comment by penev92** [comment]
Actually #19518 also happens when running via an IDE.

**Comment by pchote** [comment]
Same thing there: the IDE launch arguments should specify the correct launch path, but its not clear to me how that would work (restarting with the IDE debugger and stdout, but not launched through the IDE itself).

The best solution might be to disable the metadata registration and restart prompt if `Engine.LaunchPath` isn't explicitly specified.

**Comment by chrisharris333** [comment]
I have thoroughly tested this on windows and linux (no macs here) and while I do see the error mentioned in #19518:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

The game seems to restart fine every way but from the IDE.  I don't think actually restarting the game in this situation would be the right thing to do, as it does break the debugger.  The debugger can be reattached in various ways though.

Thoughts?

**Comment by pchote** [comment]
IMO this reinforces my comment above:

> The best solution might be to disable the metadata registration and restart prompt if `Engine.LaunchPath` isn't explicitly specified.

**Comment by penev92** [comment]
Tbh I'm fine with restarting when in debug not working, even though it's annoying and your can reattach the debugger. If all else works then okay. (What about running from an IDE without debugger?)

**Comment by pchote** [comment]
> (What about running from an IDE without debugger?)

I expect this would also crash due to the missing/incorrectly assumed `Engine.LaunchPath`.

**Comment by penev92** [comment]
That was really bad wording in my part - what I mean to say was that even if we ignore restarting with an attached debugger because that comes with its own issues, we should restart when the is no debugger.

~~But taking a step back, none of this should matter because IMO the initial changes that moved the engine in a `bin` folder has the misguided idea that that's not the engine. We shouldn't be forcing everything to specify `".."` all the time, we should fix the distinction between game folder and engine folder and more specifically don't bodge the engine folder just because outdated code is looking for the mods folder in it.~~

**Comment by pchote** [comment]
I created #19687 with a new fix so we can move ahead towards the playtest.

**Pull request closed without merging**
