### PR TITLE
Fix MRV not auto targeting friendly vehicles

### PR DESCRIPTION
**Pull request by PunkPun**
Just a typo :)

### CODE REVIEW

**Comment by GraionDilach** [comment]
Haven't this regressed a while ago? The MRV should drop the target if it's on full health, akin to RA1 Mechanic - which is why RA1 has an explicit Repair targettype.

**Comment by Punsho** [comment]
It does drop. The repair type also exists

**Comment by tovl** [comment]
They only autotarget when they are standing right next to the damaged vehicle. You should probably set a `ScanRadius`, since their healweapon is melee range.

**Comment by Punsho** [comment]
What was the logic in the original? We shouldn't deviate much from it until the game is in a more finished state

**Comment by GraionDilach** [comment]
https://github.com/LipkeGu/TSIniFiles/blob/4cc5adac88b012e27a6a82ba7c93d182451d9d64/rules.ini#L2166

**Comment by Punsho** [comment]
Added 8 cell scan radius

**Review by tovl — APPROVED** [review]
LGTM :+1:

**Review by abcdefg30 — APPROVED** [review]

**Pull request merged**
