### PR TITLE
[WIP] End Mission Score

### LINKED ISSUE #15900: Add final score tab to missions
The victory screen in the original displayed the casualties and structures lost for both factions; as well as ending credits for the player.

I personally see no need for ending credits, but I would love to see casualties and structures lost added for missions so that players can see not only that they won a mission, but how well they won the mission.

### PR DESCRIPTION
**Pull request by AlexanderRavenheart**
I've been working on implementing an end score screen for CnC Tiberian Dawn.
This is a WIP PR to keep track of the work and discuss what to add/change/improve regarding this.
Once there is an implementation approved for CnC TD I will also implement corresponding ones for RA and D2k.
This fixes #15900 and #11568.

Tasks:
- [X] Animate text: Done using RevealingLabelWidget, a new widget type that is derived from LabelWidget
- [X] Animate progress bars
- [ ] Define and implement Total Score

Should anything else be added? Should Leadership and Efficiency be replaced by something else?
Preview of current status:
CnC TD End Score Screen

V2 update:
Updated animations with an additional animation order for widgets, changed layout to be more space efficient, changed progressbars to be similar to the ones used in Starcraft thanks to a new custom widget (ProgressiveBarCounter), included time, replaced leadership and efficiency with primary and secondary objectives count (done/total). Sounds have also been included in the custom widgets: one for RevealerLabel and one for ProgressiveCounter.
(Note: The stuttering is not present in the game, just a .gif issue)
Peek 2019-09-08 07-52

V3:
Updated layout, reveal animations and sound playback.
The RevealingLabelWidget can now be set to use one of three modes of reveal: Blank, Underline and Block. Shown below are Block and Underline modes.
Peek2019-09-2919-19
Peek2019-09-2919-42

### CODE REVIEW

**Comment by tovl** [comment]
Great job! This will greatly enhance the single player experience.

Suggestions for additions/improvements (also see https://www.youtube.com/watch?v=NIcM9mDYmQ8 for a reference):
- In the original, when the text appears there is a white shine effect. Adding this will help to make the animation pop out a bit more.
- Don't reveal everything at once. For example, wait with revealing the casualty bar until after the scores have counted. Staggering the reveal in this way creates a bit of anticipation and enhances the excitement.
- Add some continuously revolving animation widget. It doesn't have to be useful, just to give it a bit of visual flair. All the originals had something like this. In TD there was a revolving clock animation, in RA there where the revolving knobs and in TS the GDI/NOD logo was itself revolving. This adds a sense of movement even after everything is revealed and synergizes with the music to sustain the excitement.
- Hide the map. The score screen comes after the outro movie. Returning to the battlefield at this point is immersion breaking and disrupts the flow. The easiest way to do this is probably to reset the shroud. It could also be nice to have a full screen background image instead, similar to the background in the original.

Suggestion for a follow-up :
In the original, the high-scores list always seemed kind of pointless to me. It would in most circumstances just be filled with your own name over and over. However, it would be really cool if we could store a global leaderboard on the website server and link the score screen to that.

**Comment by matjaeck** [comment]
> However, it would be really cool if we could store a global leaderboard on the website server and link the score screen to that.

Out of scope: It would make sense to tie the score to the player profile but the authentication system can only work with GET but not POST/PUT/DELETE requests, which blocks any kind of meaningful highscores / stats etc. And the last time a dev worked on auth features, they were "criticised" for wasting time on things that don't improve the engine, are not 100% secure etc. Validation of score is also a problem. After all I don't think it's a realistic feature tbh.

**Comment by tovl** [comment]
Well, the leaderboard is not something I expect to see implemented anytime soon, but I just wanted to point out the potential is there.

Some more suggestions after seeing it in-game:
- Hide the score tab until the mission has ended. It is the mission end screen after all. (Although maybe that was already your intention and this is just for testing.)
- Don't forget the sound effects to go with the animated text, progress bars etc.
- You might want to consider hiding the briefing tab on game end. It seems a bit out-of-place at that point, but your mileage may vary.
- Related to the previous point and depending on how much effort this would be: It might be nice to have a special version of the objectives screen with animated tick marks and text to replace the normal one after the mission ends. This tab would then be in the foreground after the outro video and then automatically roll over to the score tab shortly after the animations complete. (After that the player would be free to switch back-and-forth between the tabs). Alternatively, just have a bigger window without tabs that also shows the objectives.

**Comment by AlexanderRavenheart** [comment]
>  * In the original, when the text appears there is a white shine effect. Adding this will help to make the animation pop out a bit more.
>  * Don't reveal everything at once. For example, wait with revealing the casualty bar until after the scores have counted. Staggering the reveal in this way creates a bit of anticipation and enhances the excitement.

Added in V2.

>  * Add some continuously revolving animation widget. It doesn't have to be useful, just to give it a bit of visual flair. All the originals had something like this. In TD there was a revolving clock animation, in RA there where the revolving knobs and in TS the GDI/NOD logo was itself revolving. This adds a sense of movement even after everything is revealed and synergizes with the music to sustain the excitement.
>  * Hide the map. The score screen comes after the outro movie. Returning to the battlefield at this point is immersion breaking and disrupts the flow. The easiest way to do this is probably to reset the shroud. It could also be nice to have a full screen background image instead, similar to the background in the original.

Will include in V3.

> Suggestion for a follow-up :
> In the original, the high-scores list always seemed kind of pointless to me. It would in most circumstances just be filled with your own name over and over. However, it would be really cool if we could store a global leaderboard on the website server and link the score screen to that.

Could be good to track time of completion, units, buildings and resources stats for creating a leaderboard but as of this moment it is not possible due to requiring some major server side changes. Noted as a good future improvement.

> * Hide the score tab until the mission has ended. It is the mission end screen after all. (Although maybe that was already your intention and this is just for testing.)

Yes, it is just for testing. I changed the first gdi mission lua to autocomplete on start so that I don't have to actually play a mission to completion for testing changes. :-)

> * Don't forget the sound effects to go with the animated text, progress bars etc.

Added in V2  although those sounds are not as good as I remember them being.

> * You might want to consider hiding the briefing tab on game end. It seems a bit out-of-place at that point, but your mileage may vary.

Yes, will do that in V3.

> * Related to the previous point and depending on how much effort this would be: It might be nice to have a special version of the objectives screen with animated tick marks and text to replace the normal one after the mission ends. This tab would then be in the foreground after the outro video and then automatically roll over to the score tab shortly after the animations complete. (After that the player would be free to switch back-and-forth between the tabs). Alternatively, just have a bigger window without tabs that also shows the objectives.

Will try both suggestions.

**Comment by pchote** [comment]
> Some more suggestions after seeing it in-game:

These points are mostly covered by the campaign progression UI, which I will be implementing in separate PRs. We should limit the scope of this PR to just the score screen visuals/sounds, which will then drop it (very nicely) to the campaign flow.

**Comment by pchote** [comment]
A couple of UI thoughts:
* The Time / Objectives / Score section on the top should be aligned along the colons instead of staggering the data horizontally
* Some of the missions do weird things with the enemy income (e.g. granting / removing cash) and teams (e.g. using multiple players with the same name and colour), so their earned and spent values can't be trusted. It would be best to only show the player's resources here.

**Comment by tovl** [comment]
> Added in V2 although those sounds are not as good as I remember them being.

The sound effects do seem very off in game. Taking a glance at your code, it seems like you are retriggering the sounds at every single animation frame. This would make the sounds overlap or even clip, which would explain why it sounds so wrong. For the revealing text it is probably best to play the sound only once per animation. For the progress bars, the sounds need to be played in a loop, replaying only when the sound has ended.

It also seems the originals used a few other sounds as well; You might want to experiment a bit with different clips to hear which ones might be most appropriate.

**Comment by tovl** [comment]
Some thoughts on score calculation:

For single player mission score it makes sense to look at it from the perspective of "competitive single-player" aka bragging rights, and also to some extent whether it is thematically appropriate. I think we should reward fast, efficient and flawless execution of mission objectives and punish brute-forcing and using more resources than is strictly needed.

From that, I think mission score could be based on the following things:
1) Completing optional objectives if applicable. This one is obvious.
2) Time to completion (less is better). Perhaps the most important one from a competitive single-player perspective (see also speed-runs). Also interesting to note that RA2 did away with the score completely and just showed your time to completion compared with a par time.
3) Units lost (less is better). Keeping your units alive is tough and an interesting bonus challenge. It also makes a lot of thematic sense.
4) Efficient use of resources. Cash at mission end would be one straightforward way to measure this. It would be thematically appropriate since obtaining Tiberium/Spice is the source of the conflict to begin with. It would also create an interesting strategic dilemma: Do I spend resources now to increase my odds of winning this fight or do I hold back to reap a bigger reward if I win? It's again an interesting bonus challenge to use only the absolute minimum instead of just building a big ball of tanks/riflemen. We should watch out though, that we do not encourage farming for resources after the mission is mostly won (which would be boring). That could be mitigated by weighing the time-to-completion more in the calculation, so that that kind of behaviour would be counter-productive.

I don't think we should award points for enemy units killed. Many missions already have an objective to eliminate all enemies. In those cases, if you end up killing more enemies it just means you where less efficient in accomplishing the objective. It could also encourage farming behaviour like in point 4 above.

As a formula it could look like this:
1) Each objective (including bonus objectives) is worth a certain base score defined by the mission manifest. If the mission does not define this (initially none will), we can just use a default divided by the total number of objectives.
2) The base score is multiplied by the difficulty level (e.g. 0.5 for easy, 1 for normal, 1.5 for hard).
3) Subtract points for each second of elapsed in-game time (with a scaling factor).
4) Subtract points for each friendly unit or building killed (with a scaling factor).
5) Add bonus points for each dollar at game end.

Anyway, just my two cents. Do with it what you will.

**Comment by pchote** [comment]
I like the idea of presenting the individual metrics but then not aggregating them into an arbitrary overall score.

**Comment by tovl** [comment]
@AlexanderRavenheart It has been a while since the last update here. Are you still interested in continuing this? 

Btw, I love what you have been doing with this so far.

**Comment by AlexanderRavenheart** [comment]
Hey @tovl , yeah it's been a while since I made my last commit on this. I've been dealing with IRL issues and working on other projects.

I'm interested in continuing the work I started if there's still interest in what I made here.

**Comment by tovl** [comment]
I think there is definitely still interest in this. Real-life goes first though.

**Comment by abcdefg30** [comment]
We'd really like to get this in, but it has been sitting idle in the draft state for quite a while now, so closing and adding to the future milestone to reduce the PR queue. Please re-open when you can continue this.

**Comment by pchote** [comment]
TBH I think the bigger issue is for us to block out a release cycle when we want to prioritize campaign features, and actively prioritize our review and development around the engine features needed to nicely integrate this and related things. Integrating this well is going to take more than just one PR and more than just one new contributor!

**Comment by AlexanderRavenheart** [comment]
@abcdefg30  I understand. That is okay as I have been unable to focus on this topic recently. If anyone else wants to take over and continue this they are more than welcome to do so.

**Pull request closed without merging**
