### PR TITLE
Add libmono-i18n4.0-all to the list of Debian package dependencies

### LINKED ISSUE #11256: Error codepage 850 not supported
Basically a follow-up of this:
https://github.com/OpenRA/OpenRA/issues/10197

still not working. 

OS:
Linux Mint 17.1 64 Bit

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #11256 for real, hopefully.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
Can we bump the min mono requirement to 3.2 while we're here?

**Comment by obrakmann** [comment]
Done. There are 21 (of 4384, or 0.47%) mono users still on 2.10. I guess that's negligible.

**Comment by pchote** [comment]
They're probably all running fedora anyway.  #11255 was the final straw for me wrt mono 2.10, so we should be actively pushing people to move away from it.

**Comment by obrakmann** [comment]
Most of them actually running Debian or a derivative. Still, the number is insignificant.
screenshot from 2016-05-14 14 03 35

**Comment by Mailaender** [comment]
I supply Fedora/Cent OS players with a recent Mono version via https://build.opensuse.org/package/show/games:openra/mono

I doubt the game runs well with those ancient versions of Mono.

**Comment by obrakmann** [comment]
Removed the second commit changing the min mono version in favor of the same change in #11284.

**Comment by GraionDilach** [comment]
Has no effect on my Windows, so dunno if I can :+1: this.

**Comment by reaperrr** [comment]
> Has no effect on my Windows, so dunno if I can :+1: this.

Same here.

**Comment by pchote** [comment]
This can have a :+1: from me, but I can't merge / changelog it currently.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/e81aac6a30f68b17360e907117b9556da63c1950...4022bbd49c4e9cf2c2292a14cb3cdc7ad0469630)

**Pull request merged**
