### PR TITLE
Fix some tiling errors in the map Haos Ridges [RA]

### PR DESCRIPTION
**Pull request by abc013**
ridgesfix1
ridgesfix2
ridgesfix3

---
I'm not sure what do to here, so I just kept it as it was.
ridgeswhat

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Maybe like that, i don't see any reason why there has to use 4 way cliffs:
resim

4 way cliffs on other side may also be edited to:
resim

**Comment by reaperrr** [comment]
I agree with @MustaphaTR's suggestions.

**Comment by abc013** [comment]
Updated with @MustaphaTR's solution.

**Review by reaperrr — APPROVED** [review]

**Review by Smittytron — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1ad624192ea95dedbbb08e690b4a2560e455c8fe...9ea4dcb8ce130acc40ca1d5f1d62178a16570070)

**Pull request merged**
