### PR TITLE
Add TheRaffy to AUTHORS

### PR DESCRIPTION
**Pull request by abcdefg30**
To credit him for the `WeatherOverlay` which is featured in releases for quite some time now.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
CC @TheRaffy

**Comment by TheRaffy** [comment]
Thanks!!

**Comment by abcdefg30** [comment]
Cherry-picked this into prep, as a) this won't hurt and b) we ship that feature since quite a while now without the credit.

**Pull request merged**
