### PR TITLE
Polish TD ScrollItem UI

### PR DESCRIPTION
**Pull request by PunkPun**
I add a pressed state it to `scrollitem` so that the art wouldn't disappear when pressed and add artwork on highlighted item when it is hovered

### CODE REVIEW

**Comment by PunkPun** [comment]
before

https://user-images.githubusercontent.com/37534529/189659704-a51122c7-5db9-419b-8d04-b828964e25a6.mov

after

https://user-images.githubusercontent.com/37534529/189659720-dedc93e0-26b6-4ae0-9c10-fe3cc8cca43b.mov

before 

https://user-images.githubusercontent.com/37534529/189659867-358b9e98-8b03-44bf-bd8f-232446346213.mov

after

https://user-images.githubusercontent.com/37534529/189659885-e851f321-db8e-4c14-9eb5-0c8593780be5.mov

before

https://user-images.githubusercontent.com/37534529/189660741-50890969-41c4-4f56-a165-3a19270daf2b.mov

after

https://user-images.githubusercontent.com/37534529/189660775-6bc220a9-961e-4c37-9c88-cf0d3215e2e0.mov

**Comment by PunkPun** [comment]
Actually @dragunoff it appears that it is better left like it works currently. It feels more responsive. From these videos IMO only TD feels more polished

**Comment by dragunoff** [comment]
@PunkPun you should compare the scrollitem interactions with release and not with bleed. So if we look at release then this PR restores the behavior for "common UI" mods. For TD it's a bit more complicated as it has artwork for all states and variants. 
As far as styling for TD goes I'm on the fence about what to do :thinking: Restore the old style (release-20210321) or set up proper states for everything.

I've also spotted several scroll headers which need touching up:
Screenshot from 2022-09-12 16-46-51
Screenshot from 2022-09-12 16-45-58
Screenshot from 2022-09-12 16-45-41

IMO these should all be changed to the new style that we use in "Settings" and in "Missions":
image

**Comment by PunkPun** [comment]
fixed headers

**Comment by dragunoff** [comment]
@PunkPun What do you say about restoring the styles from release for TD? So we can merge this as a fix and maybe think about adding more styles for the scroll items in another PR.

**Comment by PunkPun** [comment]
I've split the D2K fix change to #20303. 

And renamed `BaseName` to `Background` as I'm already messing with `BaseName` in this PR

**Comment by PunkPun** [comment]
I've also split RA and TS fix to #20304

**Review by dragunoff — APPROVED** [review]

**Comment by PunkPun** [comment]
@dragunoff I just though of something. Pay attention to the borders. This is how scroll widget looks in the PR

https://user-images.githubusercontent.com/37534529/192103082-402a6d3e-67d4-4827-96cf-25bf2157d8ac.mov

This is when `button-hover` and `button-highlighted-pressed` art switched. I think it looks much better

https://user-images.githubusercontent.com/37534529/192103109-4b51f08b-ab10-405e-81ac-9df7f3effaae.mov

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c224ff56805c7b596ff1611cb8563a32461d4fff...99a289b40201e1a4c1e52e2d50cc796f59818939)

**Comment by dragunoff** [comment]
> @dragunoff I just though of something. Pay attention to the borders. This is how scroll widget looks in the PR
> This is when `button-hover` and `button-highlighted-pressed` art switched. I think it looks much better
>

Yes, it looks better - there's feedback when pressing the selected item :+1:

**Comment by PunkPun** [comment]
Should i open a mini PR for it?

**Comment by dragunoff** [comment]
> Should i open a mini PR for it?

Yes, please go ahead.

**Pull request merged**
