### PR TITLE
Added additional notification support to infiltration

### PR DESCRIPTION
**Pull request by Mailaender**
as Red Alert 2 has a lot of lines that are not setup yet.

### CODE REVIEW

**Comment by pchote** [comment]
The `SuccessNotification` name doesn't feel right IMO. How about `InfiltrationNotification` for the perpetrator and `InfiltratedNotification` for the victim?

**Comment by Mailaender** [comment]
Yeah, it is ambiguous. Renamed it and added an update rule.

**Comment by sorcerer86pt** [comment]
Tested using 2 instances of ra, one british, another random

For british side, infiltration successful played when infiltrated the ore refinery
For the random one, credits stolen notification. 
[credist_stolen_movie.zip](https://github.com/OpenRA/OpenRA/files/4351483/credist_stolen_movie.zip)

**Review by sorcerer86pt — DISMISSED** [review]

**Comment by Mailaender** [comment]
Rebased.

**Review by atlimit8 — APPROVED** [review]

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/adb5a226bfd91f11b8c49d0eb5c7a2c940e9f106...7d45e763f44b4116d844bde18d97a51480a1b794)

**Pull request merged**
