### PR TITLE
Fix replay freeze 2

### PR DESCRIPTION
**Pull request by RoosterDragon**
Depends on #9389. The extra commit fixes style and also implements the check suggested in  https://github.com/OpenRA/OpenRA/pull/9389#issuecomment-150823608 which ensures the replay for the user who disconnected ends at the right time and doesn't just keep going.

(I think @Herve-M would like their PR to count to hacktoberfest, so it would be nice to merge that PR and rebase this one, rather than closing the original)

### CODE REVIEW

**Comment by pchote** [comment]
Haven't tested the fixes here, but I'm completely ok with merging this as two prs.

**Comment by RoosterDragon** [comment]
Dependency met - rebased and ready for review.

**Comment by penev92** [comment]
:+1:

**Comment by abcdefg30** [comment]
Replays stop again. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1f83e1350ebc05b4b013d32f5440260da83d47b4...e662cb58d69423e98c11bb9893ad2a7335b77d5f)

**Pull request merged**
