### PR TITLE
Introduce TextField.Type to prevent invalid input for filenames and integers.

### PR DESCRIPTION
**Pull request by pchote**
Supersedes #14447.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Wouldn't this TextField.Type provide a necessity for an upgrade rule?

**Comment by pchote** [comment]
That is a tricky question: where do we draw the line between mod feature additions (which shouldn't have update rules) vs engine compatibility changes (which should)?

**Comment by GraionDilach** [comment]
At first I misread this as something which would have introduced regressions when unset properly in third party mod UIs, but now I see that those would just lack the bugfix until modder intervention. TBH I'm okay with either case, was more of a question than a demand in particular.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3eb2f46a607ea804d6e5b29fa10b3043727b2793...5163c087c2236171369990dc02802b3eda158d34

**Pull request merged**
