### PR TITLE
Truncate long user-defined strings.

### LINKED ISSUE #9840: Lobby-interface text overlapping
graphical issues

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27862735-lobby-interface-text-overlapping?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9840 and a bunch of other overlap cases.

### CODE REVIEW

**Comment by Mailaender** [comment]
Seems to work well. I could only test the too long map name case though. :+1:

**Comment by obrakmann** [comment]
Seems to do its job. :+1:, aside from penev's comments.

**Comment by pchote** [comment]
Updated.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/5321ade8bf35a6e605ccd74d08cdc963321e6dfd)

**Pull request merged**
