### PR TITLE
Reduce Ornithopter damage

### PR DESCRIPTION
**Pull request by reaperrr**
Reduces base damage from 1000 to 750, and re-increases the delay between bombs, making first and last bomb usually miss the target.

### CODE REVIEW

**Comment by reaperrr** [comment]
Pinging @MustaphaTR for review.

**Comment by MustaphaTR** [comment]
Still too powerful vs buildings compared to release, it kills everthing except CYard, Barracks, Palace and 1x1 buildings with one shot in this PR, while it couldn't even kill a Wind Trap in release.

And less powerful vs units now, even light infantries survive from them.

I think for a better balance, we may need to play with Versus: values.

**Comment by GraionDilach** [comment]
Couldn't you add a second layer of armor to buildings and then decrease the damage through that? That would leave the balance unaffected on the rest.

**Comment by pchote** [comment]
Our new hitshape setup now matches the original game, so shouldn't it be sufficient to change the damage/versus/drop rate to match the original values?

**Comment by MustaphaTR** [comment]
> Our new hitshape setup now matches the original game, so shouldn't it be sufficient to change the damage/versus/drop rate to match the original values?

Original Ornithopters didn't work like how we implemented them here. They were in a line (not V shape) and did a 3 pass, not 1 in original. Also were targetable by AA. Of course recreating the original behaviour would be better. But it would require code changes, not just .yaml.

**Comment by reaperrr** [comment]
> Original Ornithopters didn't work like how we implemented them here. They were in a line (not V shape) and did a 3 pass, not 1 in original. Also were targetable by AA. Of course recreating the original behaviour would be better. But it would require code changes, not just .yaml.

For the record, I knew that, but didn't feel like opening the can of worms of refactoring airstrikes now.
In my opinion we should just aim for some acceptable quick fix before the playtest and then try to fix the airstrike properly for next release, which should be a few months away.

**Comment by pchote** [comment]
@MustaphaTR: sure, but that just impacts on *where* the bombs land.  You shouldn't need to adjust per-building armor types or versus to compensate for that.

**Comment by GraionDilach** [comment]
I have a working airstirke code already AFAIK though, without the TD bombs hack and without the 1:1 Lua interfaces.

**Comment by abcdefg30** [comment]
Works for now, I guess. 👍

**Comment by reaperrr** [comment]
Fwiw, I'm also a bit hesistant to further reduce damage for now because I think it would become too weak compared to Death Hand and Saboteurs.

**Comment by MustaphaTR** [comment]
Instead of trying to reduce the damage even more, we can nerf them by making them targetable. They were targetable in original game anyway.

**Review by pchote — APPROVED** [review]
Looks reasonable to me. We can tweak further if needed after the playtest.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/005a244737e99b237b721ba56a60d3d568eccff3

**Pull request merged**
