### PR TITLE
Fix Cruiser's Turret

### LINKED ISSUE #14550: The Cruiser's secondary turret no longer rotates when firing.
(On bleed)

cruiser

### PR DESCRIPTION
**Pull request by MustaphaTR**
Fixes #14550.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Do you really need both lines? Either would be already enough AFAIK.

**Comment by MustaphaTR** [comment]
Which both lines? `Armament:>Name:` is removed, not added.

**Comment by GraionDilach** [comment]
I meant both lines of the diff.  If you're removing the secondary Name from the Armament, why add secondary to AttackTurreted? If you're adding secondary to AttackTurreted, why revert the secondary cannon's armament name to primary?

**Comment by MustaphaTR** [comment]
AttackTurreted no longer checks `Armament:>Name:`, but `Turreted:>Turret:` and `AttackTurreted:>Turret:` defatults to just `primary`.

**Comment by pchote** [comment]
> AttackTurreted no longer checks `Armament:>Name:` 

https://github.com/OpenRA/OpenRA/blob/27cc487575b0017c8b009e4fd6878bb8de16cb72/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L74-L80

?

**Comment by MustaphaTR** [comment]
Ok, i'm not sure what is going on here. But this is working fine.

Is what wanted here to keep secondary Name for Armament?

**Comment by pchote** [comment]
That is the simplest approach, yeah.

**Review by Arular101 — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4b57942f102c60941de632c41b5491ff697eb10f...a28a984ee2232cabaaf571aa7ae5daf9581e275e)

**Pull request merged**
