### PR TITLE
Implement animation priority system for sprite turrets

### PR DESCRIPTION
**Pull request by reaperrr**
For the longest time, we've had the problem that certain animations would unconditionally override already-running animations and as result cause visual glitches or prevent previously running animations from resuming.

Part of the problem were uses of PlayFetchIndex and ReplaceAnim, but the main issue is that the engine has no way of knowing which animation should take priority.

This PR solves that for turrets, which currently only have 2 animation traits (though I plan to add a `WithTurretMoveAnimation` once this PR + #15675 are merged), so they're comparatively easy to review and test.
Testcase is the TD Rocket Launcher, though the shp only works for north and west facing.

Body sprite traits will be adapted in a later PR (or possibly split over multiple PRs), as there are still a few dependencies to solve first (including #15675).

### CODE REVIEW

**Comment by pchote** [comment]
I had some thoughts on animation priorities in IRC [a few days ago](https://logs.openra.net/index.php?year=2019&month=03&day=08#21:13:30), having forgotten that this PR already existed.

> [21:13:30]	&lt;pchote&gt; btw reaperrr i'm not sure where you're going wrt the animation priorities but I did have some thoughs there
> [21:13:44]	&lt;pchote&gt; about encoding different states rather than transient animations
> [21:13:58]	&lt;pchote&gt; and then automatically looking up transition animations between states
> [21:14:06]	&lt;pchote&gt; e.g. prone &lt;-&gt; stand
> [21:19:53]	&lt;reaperrr&gt; pchote: hmm... you mean (for example) something like a central AnimationStateManager that decides the anim states/flags,
> [21:19:55]	&lt;reaperrr&gt; and then a generic anim trait that triggers on a customizable anim state/flag and cancels when that ends?
> [21:20:11]	&lt;pchote&gt; i'm thinking that trait can be the spritebody
> [21:20:45]	&lt;pchote&gt; but basically i'm wondering whether we need to have a distinction between "event" animations and "state" animations
> [21:20:48]	&lt;pchote&gt; maybe we don't
> [21:20:58]	&lt;pchote&gt; is an "active animation" state enough?
> [21:21:18]	&lt;pchote&gt; the priorities would then live on the states
> [21:21:32]	&lt;pchote&gt; but need to think about how to deal with overlapping states
> [21:21:38]	&lt;pchote&gt; e.g. for infantry prone and attack are distinct
> [21:21:45]	&lt;reaperrr&gt; yeah
> [21:21:46]	&lt;pchote&gt; can have either or both active at once
> [21:21:57]	&lt;pchote&gt; and this is where my thoughts ended
> [21:24:23]	&lt;reaperrr&gt; did you mean spritebody for anim state decisions, or for animating based on states decided elsewhere? or all in one (but that would be too monolithic imo)?
> [21:28:50]	&lt;pchote&gt; i don't know
> [21:39:05]	&lt;reaperrr&gt; pchote: the main issue we'd have to solve would probably be how to handle all these rare special-cases (WithBuildingPlacedAnim etc) without turning that spritebody into a monolithic monster
> [21:39:44]	&lt;pchote&gt; i suspect the answer will be to invert the problem
> [21:39:55]	&lt;pchote&gt; right now we have traits tell the sprite body to play an animation
> [21:40:09]	&lt;pchote&gt; it is probably more tractable if the sprite body asks the traits which ones want to be active
> [21:40:23]	&lt;pchote&gt; and then based on the priority it decides what takes precidence
> [21:40:56]	&lt;pchote&gt; but i'm not sure how that should work for these event-style animations
> [21:41:17]	&lt;pchote&gt; maybe transition to the active state for one tick, then have the active animation as the active -&gt; idle transition?

IMO the same points apply here, but in this case I don't think we really need any state management - this can all be implemented on `WithSpriteTurret` directly by introducing an `AimPrefixes` dictionary that defines armament name &rarr; sequence prefix and then automatically detect and play an attack animation if it is defined in the sequences for the current prefix.

**Comment by pchote** [comment]
I suspect we can implement the same approach for the `WithSpriteBody` traits too - have the default ones expose a `PlayActiveAnimation(string sequence)` that has the lowest priority, autodetect things like move and maybe attack, and then require anything more difficult to be implemented in a custom subclass.

**Comment by reaperrr** [comment]
Ok, but that pretty much means a complete rewrite, and for movement support I'd like to get #15675 merged first.

**Comment by reaperrr** [comment]
Due to the above, I'll close this for now to clean up the PR queue a bit.

**Pull request closed without merging**
