### PR TITLE
Server launch scripts

### PR DESCRIPTION
**Pull request by ThomasChr**
Came up in Discord. User wanted to override Server.Map when using launch-dedicated.sh - didn't work.
I'm not quite sure if I should squash those two commits, the other one is kind of unrelated.

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
LGTM

**Comment by PunkPun** [comment]
Could you also rename `JoinChatDelay` to `FloodLimitJoinCooldown`?

**Comment by ThomasChr** [comment]
Done. Shall I squash the three commits?

**Comment by penev92** [comment]
> Shall I squash the three commits?

IMO it's fine.
If you do squash them make sure to list all 3 changes in the commit message.

**Comment by ThomasChr** [comment]
Okay, then I‘m not squashing 😊

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e3cf75d78694458640f1b95df79a9a8a061ff448...7998e76926ee0ddf76d17e34632516ac9d9fe349)

https://github.com/OpenRA/OpenRA/commit/512f7c4c4a9d3071e7da0cb66726cf2f07df58cd
https://github.com/OpenRA/OpenRA/commit/5a5dfcc3971afe2f0ea16b05254f7b13a3865dba
https://github.com/OpenRA/OpenRA/commit/3e18761df133dac3fd088b7bee096acb17b17b5c

**Pull request merged**
