### PR TITLE
Sort 'Playing' games in the lobby by play time. #12959

### PR DESCRIPTION
**Pull request by rob-v**

### CODE REVIEW

**Comment by rob-v** [comment]
The compare here is wrong, in VS it shows properly that only few lines were changed:

`				foreach (var modGamesByState in modGames.GroupBy(listOrder).OrderBy(g => g.Key))
				{
					// Sort 'Playing' games by Started, others by number of players
					
foreach (var game in modGamesByState.Key == 2 ? modGamesByState.OrderByDescending(g => g.Started) : modGamesByState.OrderByDescending(g => g.Players))
					{
						if (Filtered(game))
							continue;`

**Comment by abcdefg30** [comment]
Using `?w=1` makes it easier to read as well: https://github.com/OpenRA/OpenRA/pull/12973/files?w=1

**Comment by rob-v** [comment]
thanks, you're right.

**Review by abcdefg30 — APPROVED** [review]
👍

**Review by obrakmann — APPROVED** [review]
👍 
I'm not sure if the person requesting this change would like a ascending or descending sort order, but I guess it makes sense for games to slowly trickle down the list (from 'waiting with players' to 'just started' to 'going on for a while' to 'server just restarted and is now empty')

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5fdcd87cf433606b4b19c0224e42ab5f94947699...e91787df5d18da8cbd4030376675dcd8d3936eca)

**Pull request merged**
