### PR TITLE
Restore missing minelayer pips.

### PR DESCRIPTION
**Pull request by pchote**
Fixes a regression from #17808.

### CODE REVIEW

**Comment by sorcerer86pt** [comment]
Base Profile Screenshot 2020 03 28 - 19 23 29 03
Base Profile Screenshot 2020 03 28 - 19 23 40 34

**Review by sorcerer86pt — DISMISSED** [review]

**Review by atlimit8 — DISMISSED** [review]

**Comment by abcdefg30** [comment]
Reminder from IRC: Engineer pips are no longer yellow in TD.

**Comment by pchote** [comment]
Minigunner + engineer passengers in `release-20200202`:


Minigunner + engineer passengers on this PR:



So it appears that Engineer pips did not regress, there is just very poor contrast between the green and yellow pips.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/114f2b372a2f419b4943d8de354f19a7cf17d5a1...952d9040abeea2bb2312f98f90172a7c17581387)

**Pull request merged**
