### PR TITLE
Added a fake .zsync suffix parameter to pass appimaged linting

### LINKED ISSUE #20232: Error with zsync - OpenRA is not a proper AppImage
This started popping up after installing [appimaged](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md):
image

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/20232

No server side changes required: https://master.openra.net/appimagecheck?mod=ra&channel=release&format=.zsync already works.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]

**Comment by dragunoff** [comment]
This should fix it though I was not able to verify it with a local AppImage build (the warning doesn't show up with or without the fix). It would be best to tag a pkgtest (or devtest?) on this commit.

**Comment by pchote** [comment]
>  I was not able to verify it with a local AppImage build

This suggests that it has probably already been fixed in appimagetool and that the workaround here may no longer be needed.

**Comment by dragunoff** [comment]
> > I was not able to verify it with a local AppImage build
> 
> This suggests that it has probably already been fixed in appimagetool and that the workaround here may no longer be needed.

I still get the warning with release-20210321 and with [the recent devtest](https://github.com/abcdefg30/OpenRA/releases/tag/devtest-20220910).

**Comment by penev92** [comment]
Seems to me like the best way to go here would be to merge and see what happens when we tag the next devtest.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1717645e8acf94ad3117d0812dd4fbdf2f21df04...67d0f5f1925c0dc5f3b96625a38cb56ee0666ed8)

**Pull request merged**
