### PR TITLE
Add customizable properties to observer clocks.

### PR DESCRIPTION
**Pull request by GraionDilach**
I need help here though - the properties ain't read from the yaml (neither does the `Icon*`s, checked).

### CODE REVIEW

**Comment by RoosterDragon** [comment]
The protected constructors need to copy across these properties (i.e. add all the missing ```Blah = other.Blah``` lines) - then it'll work. Might as well fix it for the icon bits too since you're here.

I have tested with the above fix, and it works fine so :+1: once applied.

**Comment by GraionDilach** [comment]
Knew it would be something seriously simple, thanks! Done.

**Comment by RoosterDragon** [comment]
You need to do the same thing in ```ObserverSupportPowerIconsWidget.cs```.

**Comment by GraionDilach** [comment]
I'm stupid.

**Comment by RoosterDragon** [comment]
Looks fine now. :)

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/318ceea6a4015e59d9f5b9cd003a450dae0946a3...6e1538a7bfc79b70770194c736f8ae39ef59b1d1)

**Pull request merged**
