### PR TITLE
Retire classic mouse orders

### PR DESCRIPTION
**Pull request by pchote**
This feature has never worked properly, and is one of our most frequent support requests / complaints by non-technical players on IRC / comments.  Nobody has shown an interest in fixing and maintaining this feature, so it is time to remove it.

### CODE REVIEW

**Comment by Mailaender** [comment]
Now everyone wants it back... http://www.openra.net/news/playtest-20150118/#disqus_thread *sigh*

**Comment by pchote** [comment]
Lets bring back a fixed version before the next release then.

**Comment by Mailaender** [comment]
I don't think this is easily done and will take a lot longer so I filed https://github.com/OpenRA/OpenRA/issues/7381.

**Comment by pchote** [comment]
I wouldn't object too loudly to a quick fix that reverted this and introduced a small dead zone that prevents the selection rectangle from triggering until the mouse moves by a few (maybe 5?) pixels.  That would fix the worst user-facing complaint.

**Comment by kaneCVR** [comment]
I use the classic left click mouse orders... also, removing this feature makes the game unplayable on touchscreen devices. 

Wish someone could make a proper implementation of this as well as touchscreen support (simple UI for scrolling or multitouch would be nice).

**Comment by Mailaender** [comment]
Seems to be indeed the major complaint of this playtest. http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=17044

**Comment by dan9550** [comment]
@pchote a deadzone would really fix it up IMO, apart from constantly always drawing a tiny selection box i never found much wrong with it.

**Pull request merged**
