### PR TITLE
Replaced DelayedAction with ITick in Bridge related traits

### PR DESCRIPTION
**Pull request by Mailaender**
as described in https://github.com/OpenRA/OpenRA/issues/12310.

### CODE REVIEW

**Comment by reaperrr** [comment]
Since you didn't mention anything about an exception, this seems to be missing the non-legacy `BridgeHut` (only used in TS, I think).

**Comment by Mailaender** [comment]
Refactored those as well.

**Comment by pchote** [comment]
The reason `DelayedAction` is a problem is because it stores a deferred callback to run at a later time, which can't be serialized. This currently just moves the action into `Bridge`, which doesn't solve the problem but rather kind of obfuscates it. The non-legacy `BridgeHut` / `GroundLevelBridge` code already implements repairing without this, so the best solution will be to finish porting RA/TD to use these newer traits and finally remove the legacy versions.

**Comment by abcdefg30** [comment]
There hasn't been activity here for a while, so I guess interest in continuing this is gone. Please re-open if you want to return to this.

**Comment by Mailaender** [comment]
I didn't understand the concern how this is being obfuscated in the `Bridge` trait. I removed `DelayedAction` entirely.

**Pull request closed without merging**
