### PR TITLE
Fix a crash in nod07b

### LINKED ISSUE #17878: Fatal error on TD Nod mission 7b
> Fatal Lua Error: [string "nod07b.lua"]:103: attempt to call global 'GetCargo' (a nil value)
>    at OpenRA.Scripting.ScriptContext.FatalError(String message)
>    at OpenRA.Mods.Common.Scripting.TriggerGlobal.<>c__DisplayClass23_0.<OnEnteredFootprint>b__0(Actor a)
>    at OpenRA.Mods.Common.Traits.ActorMap.CellTrigger.Tick(ActorMap actorMap)
>    at OpenRA.Mods.Common.Traits.ActorMap.OpenRA.Traits.ITick.Tick(Actor self)
>    at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
>    at OpenRA.World.Tick()
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
>    at OpenRA.Game.LogicTick()
>    at OpenRA.Game.Loop()
>    at OpenRA.Game.Run()
>    at OpenRA.Game.InitializeAndRun(String[] args)
>    at OpenRA.WindowsLauncher.RunGame(String[] args)
>    at OpenRA.WindowsLauncher.Main(String[] args)
> 

[lua.log](https://github.com/OpenRA/OpenRA/files/4406129/lua.log)

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes an oversight from #16568.

Closes #17878.

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Comment by abcdefg30** [comment]
Rebased and updated to fix the issues @pchote found.

**Comment by pchote** [comment]
Fixes confirmed, although as mentioned in IRC I would like to see a second engineer added to nod07b so the capture can have a chance of succeeding.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
LGTM but we probably should get another set of eyes on the new changes before merging.

**Review by deleted-user-1 — APPROVED** [review]
Played the mission and let the APC arrive in my base. AI captured one building and damaged another one. Not sure if the third engineer is needed - the fix works.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e7d370be78eace56a7d01aa77cd87dd346ba760b...50a2547461f52266bea14b8481c94ba440997138)

https://github.com/OpenRA/OpenRA/commit/63cee6a0e3abfe60e53cb37717ebee1aad6fc76a
https://github.com/OpenRA/OpenRA/commit/bf2640308aed9faddc7830a6006be5765799b5e1
https://github.com/OpenRA/OpenRA/commit/5ff2546a5d69bdbc5caba5c8730c207387596305

**Pull request merged**
