### PR TITLE
Revert granting condition from HackyAI

### LINKED ISSUE #15794: [Bleed] Starting a multiplayer game with bots causes desync.
This happens with dedicated or local. 2+ players with bots crash the game.

[exception-2018-11-05T225423Z.log](https://github.com/OpenRA/OpenRA/files/2550941/exception-2018-11-05T225423Z.log)
[syncreport-2018-11-05T225423Z.log](https://github.com/OpenRA/OpenRA/files/2550946/syncreport-2018-11-05T225423Z.log)

I assume it's related to https://github.com/OpenRA/OpenRA/pull/15750

### PR DESCRIPTION
**Pull request by reaperrr**
In favor of using GrantConditionOnBotOwner.
Updated update rule and shipping mods accordingly.

TD and D2k changes were re-applied using the updated update rule to make sure that works as intended. RA and TS were updated manually.

Fixes #15794.

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
update Fort Lonestar

> Testing map: Fort Lonestar
OpenRA.Utility(1,1): Warning: Actor type `player` grants conditions that are not consumed: enable-rush-ai, enable-normal-ai, enable-turtle-ai, enable-naval-ai
OpenRA.Utility(1,1): Error: Actor type `player` defines conditions but does not include a ConditionManager

**Review by TheChosenEvilOne — APPROVED** [review]
LGTM

**Review by obrakmann — APPROVED** [review]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/fe55315608c58f2ce65df8a4ea2f2c7963e1f9ea)

**Pull request merged**
