### PR TITLE
Fix a bug in Server

### PR DESCRIPTION
**Pull request by penev92**
I derped in #8629...

### CODE REVIEW

**Comment by RoosterDragon** [comment]
:+1:

**Comment by deniz1a** [comment]
Is that needed?

**Comment by penev92** [comment]
Yes. Long story short, `DropClient()` modifies `Conns` by removing a connection from it, and you don't want to be modifying a collection that you are enumerating at the moment.

**Comment by Mailaender** [comment]
Underp accepted.

**Comment by deniz1a** [comment]
Ok thanks.

**Pull request merged**
