### PR TITLE
Fix sprite control group decoration position.

### LINKED ISSUE #12032: Ctrl group glyph positions are wrong.
screen shot 2016-09-14 at 22 55 26

### PR DESCRIPTION
**Pull request by pchote**
Fixes #12032.

### CODE REVIEW

**Comment by obrakmann** [comment]
Vehicles look ok again, but infantry now has the decoration in the center (zoomed out, zoomed in looks fine).

**Comment by pchote** [comment]
That is how our decorations have always looked for infantry.  This screenshot is taken on `release-20160508`: 
screen shot 2016-09-21 at 16 25 29

**Comment by obrakmann** [comment]
Well, that sucks then.

**Review by chrisforbes — APPROVED** [review]

**Comment by RoosterDragon** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9fa04790bbbcbeee9eac1fcdea15849a829a7d3c...92511e02a2dfbf9fa77e396ce2dd10051253c1f0)

**Pull request merged**
