### PR TITLE
Make SNIPER available for France

### PR DESCRIPTION
**Pull request by abcdefg30**
As suggested on [Sleipnir's Stuff](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=292926#292926).

### CODE REVIEW

**Comment by kyrylo** [comment]
Thanks, that would be cool. Maybe we need to think through Sniper's vision/range? I don't remember the original behaviour.

**Comment by MicroJOo** [comment]
:-1:  sry , no ... 

we worked this one out ... and im sick of the discussion

you can read everything here : https://github.com/OpenRA/OpenRA/pull/7794

and beside that , if you give france the sniper ... that means , it has 3 faction-specials .. mobile gaps, fake structures and now snipers ... this is not fair towards the other factions

allies can use hinds to kill enemy infantry ... thats good enough , and then they have also infantry to counter infantry ... and "every" allies - faction has tanya ... what more meatgrinders do you need ?

**Comment by kyrylo** [comment]
> we worked this one out 

I quickly skimmed through that discussion and it seemed like everyone was liking sniper except you :)

**Comment by MicroJOo** [comment]
@kyrylo : then you didnt read that it got approved by chrisf and pchote ...

**Comment by pchote** [comment]
There have been a lot of changes to shroud and fake structures (assuming we take #9730) since the last release.  I think it would be premature to make any further changes to France based on assumptions from the last release - they have already changed a lot since then!

**Comment by Mailaender** [comment]
Fits to the stealth theme and has many supporters of the idea on the forum thread. :+1:

**Comment by epicelite** [comment]
I'm_ok_with_this.jpg

**Comment by penev92** [comment]
Let's put this on ice until we can get some proper feedback on the current balancing.

**Comment by obrakmann** [comment]
Alright, closing for now.

**Comment by Mailaender** [comment]
We are now in a new release cycle so I gave this another shot: https://github.com/OpenRA/OpenRA/pull/11295.

**Pull request closed without merging**
