### PR TITLE
Don't allow to unspy a spy

### PR DESCRIPTION
**Pull request by ThomasChr**
See #19182
Up for discussion, of course

### CODE REVIEW

**Review by abcdefg30 — COMMENTED** [review]
Won't this prevent people from hiding their own Tanya by building spies and disguising them as her?

**Review by PunkPun — COMMENTED** [review]
I dunno, I like the fact that spies can disguise using the disguise of allied actors

**Comment by ThomasChr** [comment]
This will only prevent disguising as one of your own spys. So you should still be able to disguise as your own Tanya and use any allied unit as a disguise.

**Comment by abcdefg30** [comment]
> This will only prevent disguising as one of your own spys. So you should still be able to disguise as your own Tanya and use any allied unit as a disguise.

The problem would be if you have one spy disguised as an enemy unit, then build more spies and use the first spy as "template" to disguise the rest. Will that still be possible with this PR? Would it be enough if a spy can't target itself? Then it cannot "undisguise" by accident.

**Comment by ThomasChr** [comment]
I understand.
So I'm doing the following:
1. Unspying a spy by (right) clicking on itself won't work anymore.
2. If unspying a group of spys by (right) clicking on one of them I will make sure that all spys are affected and that it doesn't seem to be random which spy isn't a spy anymore. Also I will make sure that the "spy"-Tag is correctly set afterwards.

**Comment by ThomasChr** [comment]
Simply disallowing a spy the disguise Action by clicking on itself fixed all the problems.
So are we good with that? Does anyone care to test?

**Review by abcdefg30 — APPROVED** [review]
Lgtm. One thing I noticed is that you can still get the "SPY" tag even if the spy is not disguised by clicking on an undisguised spy, but Imho this doesn't need to be fixed here as that issue is not about targeting. (It should still allow targeting, just not display the tag/disguise as the same type.)

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/db878ad65c1b8c557f28128f3fc0bbc1fe76c099...51ac28b5778834163c6f5d73e8136ee33c5fea10)

**Comment by ThomasChr** [comment]
from abcdefg30 discord: if you want to do a follow-up https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Cnc/Traits/Disguise.cs#L188-L194 would need to be adapted to not register as a disguise when the target actor type is the same as the own actor type (it should just clear any existing disguise)

**Pull request merged**
