### PR TITLE
Fix MAD Tank command bar deploy.

### LINKED ISSUE #13698: QTNK (RA1) doesn't deploy with F key
I think this is an inconsistency when DTRK can be deployed with F key.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #13698 and the missing tooltip description.

### CODE REVIEW

**Comment by obrakmann** [comment]
👍

**Review by rob-v — APPROVED** [review]
👍 

side note: it would be better to have as convention a OrderName constant in traits for cleaner code. E.g. MadTank uses "Detonate" string 4 times now.

**Review by obrakmann — APPROVED** [review]
Whoops, need to approve properly. 👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/8d8eaf1caab05c46cd14302a531846da4c62c985)

**Pull request merged**
