### PR TITLE
Issues/16183

### LINKED ISSUE #16183: GrantExternalConditionToProduced isn't within Traits/Conditions folder.
Even such external conditions are within - GrantExternalConditionToCrusher is an older example.

### PR DESCRIPTION
**Pull request by mdb-uk**
Moved **GrantExternalConditionToProduced.cs** from:

_OpenRA.Mods.Common/Traits_ 

to:

_OpenRA.Mods.Common/Traits/Conditions_.

The namespace remains the same as per other files in the Conditions folder.

I have run make.test and make.check which passed, and I tested the 4 core mods to check they function ok and found no issues.

Closes #16183

### CODE REVIEW

**Comment by teinarss** [comment]
Hi MDBarbier, thanks for your PR! It looks like you have two commits too many.

**Comment by abcdefg30** [comment]
The last commit looks like a merge commit, which should go away after a rebase. (https://help.github.com/en/articles/about-git-rebase might help if you are not familiar with that. You can also drop by our IRC channel or Discord server if you have questions/need help.)

**Comment by MDBarbier** [comment]
Hi - thanks for your comments. Sorry for the multiple commits, rebasing/forking on git is new to me. I've made some changes to my branch, and I think I've resolved it. Only one commit seems to be showing now anyway on the PR. Hopefully that's ok but let me know if any further changes neeeded?

**Review by abcdefg30 — APPROVED** [review]
Looks good to me now.

**Review by RoosterDragon — APPROVED** [review]

**Comment by RoosterDragon** [comment]
Thanks @MDBarbier. PS: If you wish, you're welcome to add yourself to [AUTHORS](https://github.com/OpenRA/OpenRA/blob/bleed/AUTHORS), just send another PR if you do.

**Pull request merged**
