### PR TITLE
Fix backwards movement not working correctly when turning in an arc

### PR DESCRIPTION
**Pull request by PunkPun**
Supersedes #20429

See that PR's description

### CODE REVIEW

**Comment by dnqbob** [comment]
It works well in my test. And I already have the way to implement https://github.com/OpenRA/OpenRA/pull/20428 https://github.com/OpenRA/OpenRA/pull/20419 and https://github.com/OpenRA/OpenRA/pull/20434, just wait for this pr merged

**Comment by Mailaender** [comment]
Can you remove the test case?

**Comment by PunkPun** [comment]
Dropped and rebased

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ef6d8d7345b75f5c61a21b3233327eddd1b86667...2801e0ee5baec30e0c2b7d10da2e6145403b58f6)

**Pull request merged**
