### PR TITLE
Fix some ts structure bounds

### PR DESCRIPTION
**Pull request by abcdefg30**

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by Phrohdoh** [comment]
Needs a rebase.

**Comment by abcdefg30** [comment]
> I don't think we should match pixel bounds here; the purely decoration parts can be left out.

Sounds logical, but I think,
tsbounds
looks worse than:
tsbounds2

> I cannot select a gapowr that is behind another gapowr (this applies to any structure placed to the top-right of another)

I can't reproduce that.
I'll update this once we agreed about ^.

**Comment by LipkeGu** [comment]
instead of ssetting this, we could change this on code level.

**Comment by LipkeGu** [comment]
needs additional Rebase :/

**Comment by abcdefg30** [comment]
Rebased. But kept the requested changes locally unil someone puts his/her foot down about ^.

**Comment by Phrohdoh** [comment]
You and I will have to agree to disagree on that.

**Comment by obrakmann** [comment]
In our other mods, the selection box always surrounds the whole shp, so I feel we should do the same in ts. :+1:

**Pull request merged**
