### PR TITLE
Fix units not attack moving to waypoints after resupply/takeoff

### PR DESCRIPTION
**Pull request by abcdefg30**
Units attack move in all other cases when they move to rally points.

### CODE REVIEW

**Comment by pchote** [comment]
Are you sure that we didnt have a specific reason for the current behaviour?

**Comment by abcdefg30** [comment]
The origin of those lines dates back more than four years. Even if there was a valid reason (which I doubt) I don't think it is still valid.

**Comment by pchote** [comment]
I was more wondering about why the 10 PRs that touched aircraft rally points last year didn't fix this, possibly because of review comments / issues undoing proposed changes to these lines?

**Comment by abcdefg30** [comment]
The reason was to be consistent with resupply/repair: https://github.com/OpenRA/OpenRA/pull/17017/files#r323977965
I'm making all cases consistent now, so this is no longer relevant.

**Comment by tovl** [comment]
I vaguely remember some discussion about whether rallypoints should be `AttackMove` or `Move`, but I don't think anybody really argued that they should be `Move` in one case and `AttackMove` in another. The reason it wasn't fixed is because everybody (including me) just assumed someone else had a good reason for it at some point, but that is looking increasingly unllikely (or the old reasons are no longer relevant.)

In any case, it makes sense to have it be consistent, so :+1: from me. An interesting follow up could be to have it be configurable per mod.

**Comment by pchote** [comment]
Actually, I now remember the logic here: RA's standard gameplay defines that aircraft should not autotarget units, and only respond to player orders. Attack-moving to the rallypoint breaks this expectation by making aircraft ignore the hold-fire stance and shoot the first thing that they see.

**Comment by tovl** [comment]
Good point, but in that case it should be a `Move` order from production (of aircraft) as well. So it seems that we need some more configurability here.

**Comment by pchote** [comment]
We could perhaps have an `AttackMove: true` flag on the `RallyPoint` trait?

**Comment by abcdefg30** [comment]
As I said before: I don't want to touch aircraft production rallypoint behaviour in this PR, so we either close this or do follow-ups that adjust the attack-move behaviour for aircraft in all cases. (Also do note that resupply is not strictly bound to aircraft.)

**Comment by tovl** [comment]
> We could perhaps have an AttackMove: true flag on the RallyPoint trait?

Actually, there are also units like the stealth tank that similarly default to hold-fire and attack-moving would be similarly out of place there. So, it would be more useful to add the flag to the unit being produced than to add it to the building that produces it.

> so we either close this or do follow-ups that adjust the attack-move behaviour for aircraft in all cases.

I think we have established by now that attack-move vs. move is actually orthogonal to production vs. resupply so it still makes sense to at least make the rallypoint behaviour consistent between production and resupply, before we start adding exceptions.

My +1 still stands. I might take a stab at a follow up myself.

**Comment by pchote** [comment]
This topic came up again today on the community discord. I commented there
> since the topic came up again in #openra, i'll poke at the discussion again here:
we should change the default behaviour from rallypoints from attack move back to move
> * all the original games used standard move
> * it was added to openra back in the early days without any real discussion or consideration for gameplay implications
> * it isn't applied consistently, with aircraft ignoring it half of the time
> * opportunity fire has made it obsolete for most vehicles
>
> it would be good to seriously evaluate whether attack move offers enough benefits to justify the current behaviour (including the fix at #18161 which needs to happen if we decide to keep it), and if not we should remove it

Good point about Stealth tanks, etc. That's another point for the "can we really justify these inconsistencies?" list.
If it turns out that we can justify it then I agree that it would make sense to tie move/amove to the units stance (no need to have a separate flag) instead of the structure.

**Comment by tovl** [comment]
I think that in the long term, tying it to the unit stance makes the most sense of all the options. Then you could even tie attack everyting stance to assault move (not that that would affect any currently existing unit). Tying unit stances and the regular order system more together would be a good thing to strive for in general since unit stances as they are now feel a bit awkwardly tacked on, especially with regards to order queueing.

In any case, whatever we decide to do further down the road, this PR presents a very simple change that at least gets us one step in the right direction by at least making it internally consistent.

**Review by pchote — APPROVED** [review]
I still think that we risk complaints in changing this behaviour, without the justification of fixing the actual underlying problems. It seems i'm alone in this opinion however, so i'm prepared to be proved wrong.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/cf08d7e002c71790e8ee41ad87ef280ba37ae075

**Pull request merged**
