### PR TITLE
Simplify and polish D2k effects/palettes.

### PR DESCRIPTION
**Pull request by pchote**
This PR does some initial housekeeping around D2k palettes in preparation for using the R16 sprites (aka D2kHDR 🌈).

I compared most of our effects against the "Dune 2000 Map and Mission Editor" tool which caught some discrepencies that I have now also fixed.

Screenshot 2023-11-13 at 20 16 30

The cloak palette will be handled in its own PR.

~~The fog now looks slightly different, i'm hoping this won't be too controversial.~~

### CODE REVIEW

**Comment by penev92** [comment]
Code changes look fine, but this needs to be scrutinized in game. 🧐

**Comment by Porenutak** [comment]
New Fog of War change whole color tone instead of just make scene darker or foggy. Its awkward and not very eye pleasing.

Screenshot (235)

Rest is OK.

**Comment by PunkPun** [comment]
I agree. The new fog feels like it has a high contrast filter applied. The east and north facing cliffs look quite ugly

Old
New

**Comment by PunkPun** [comment]
Screenshot 2023-11-14 at 19 31 48

**Comment by pchote** [comment]
Updated to restore the previous fog visuals, and added a new commit to use the correct trike icon (4305 is a duplicate of 4277 in DATA.R8, but garbage in DATA.R16).

**Comment by Porenutak** [comment]
LGTM

**Review by PunkPun — DISMISSED** [review]
LGTM

**Review by PunkPun — COMMENTED** [review]
Actually shouldn't there be an update rule for the trait removal?

**Comment by pchote** [comment]
They are d2k-specific traits in the Mods.D2k.dll, so IMO no (and this would cause problems with visibility since `UpgradePath` can't see into Mods.D2k.dll).

**Comment by PunkPun** [comment]
But in update we only deal in strings. We don't use actual classes that could have dependency issues unless it's basic structs such as CPos.

And we do write update rules for Mods.Cnc.dll

**Comment by pchote** [comment]
Added update rules.

**Comment by PunkPun** [comment]
needs a rebase

**Comment by pchote** [comment]
Rebased.

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8da696808226a5f4cac08523158704f63a0ac048...a93596e6cc7abced453269b4d6cec126c1a2d680)

**Pull request merged**
