### PR TITLE
Fix mpspawn ownership

### LINKED ISSUE #11333: System.IndexOutOfRangeException in Dune 2000
Good evening OpenRA developers!

When playing Dune 2000, the game often crashes, usually when in combat with enemy units.  Here is the exception.log from the most recent crash:

Dune 2000 Mod at Version release-20160508
on map b9c74c6501ba964e2eaf0eddc617b7734b126cda (The Duell by CombineCnR).
Operating System: Windows (Microsoft Windows NT 5.2.3790 Service Pack 2)
Runtime Version: .NET CLR 4.0.30319.1022
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Mods.Common.Traits.MPStartLocations.<WorldLoaded>c__AnonStorey0.<>m__0(Client c)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Traits.MPStartLocations.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

I'm not sure exactly how to reproduce the crash, but each time it has happened, my units have been in combat with enemy units.  The game freezes, the sound loops for several seconds, and then I receive the warning that the game has crashed.

The issue is intermittent, and apart from it, the game runs well.  Any help you guys can offer would be greatly appreciated!

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #11333.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by GraionDilach** [comment]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me :+1: and the lint check works. :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b93868c65b103997bf51fbf32a9249e96e277fa2...894d740667ac6aa7594d4cf23e1d0a73a05e1dbc)

**Pull request merged**
