### PR TITLE
Improve projectile blocker scan efficiency and remove RA gates

### PR DESCRIPTION
**Pull request by reaperrr**
On bleed, the largest OuterRadius out of all actors is unconditionally used for the actor overscan of blockable projectiles.

This is wasteful, because we only really need the largest OuterRadius out of all _blocking_ actors.
In case of D2k and TD that's just walls, in RA and TS the gates.

Furthermore, in RA none of our official maps use the gates, so a case could be made for either moving them to an optional yaml file that maps need to load directly (I did that in the 2nd commit), or removing them entirely, because otherwise they just hurt performance of many bullet projectiles despite not even being used by us.

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1: on the first commit.

Notsure on the second one. Madmaps cannot include additional base yaml files AFAIK, so the new yaml file will just turn to be an artifact + since it's not the part of the base mod, the gates will no longer be affected by rule updates either. I'd pretty much axe the yaml entirely.

**Comment by pchote** [comment]
> I'd pretty much axe the yaml entirely.

:+1:

**Comment by reaperrr** [comment]
> I'd pretty much axe the yaml entirely.

Done.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by abcdefg30 — COMMENTED** [review]
Why are we removing the entire gate yaml, but keeping the artwork?

**Comment by reaperrr** [comment]
> Why are we removing the entire gate yaml, but keeping the artwork?

No particular reason, other than that the artwork has been there for years, even before it was added to yaml.
Personally I don't mind removing that as well, just didn't feel like making the call myself (and possibly receive flak from those 2 or 3 people that might be using the gates in their mods/maps).

**Comment by pchote** [comment]
Lets remove it then.  Map authors can always add it back themselves.

**Comment by reaperrr** [comment]
Updated.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/21715857987d77d2c1b0568af067863a1a1b171a...fc51fd4efb9acc19134455cb839eea1c7d11bfe6)

**Pull request merged**
