### PR TITLE
Reduce the size of battlefield news when messages are short

### PR DESCRIPTION
**Pull request by PunkPun**
# Bleed

Screenshot 2024-12-10 at 23 43 33

Screenshot 2024-12-10 at 22 52 44

# Suggested

Screenshot 2024-12-10 at 23 39 25
Screenshot 2024-12-10 at 23 36 37
Screenshot 2024-12-10 at 23 42 09
Screenshot 2024-12-10 at 23 42 50

### CODE REVIEW

**Comment by penev92** [comment]
Top spacing seems to be bigger than the bottom spacing. Feels like it should have some more at the bottom.
Other than that I'm sold 👍

**Comment by PunkPun** [comment]
that's an optical illusion. I dunno what is the cleanest way to address it apart from rewriting out box model

**Comment by penev92** [comment]
I think something as simple as
```diff
-newsPanel.Bounds.Height = Math.Min(newsPanel.ContentHeight, maxNewsHeight);
+newsPanel.Bounds.Height = Math.Min(newsPanel.ContentHeight + 5, maxNewsHeight);
```
makes it look better (despite not being the greatest solution out there).
The text is still not aligned horizontally though, so I may be overthinking it
image

**Review by penev92 — APPROVED** [review]
Alright, not an important deal anyway.

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/19bdcd6f5c8c38d92e464835b5ad6c4167b353a0...1f401b977a40ef1e2ff5ca047c882b91a60bfb81)

[`prep-2411` commit](https://github.com/OpenRA/OpenRA/commit/5f6eecc1f613f9f96a4afb6329fc1ccf4d77fa5e)

**Pull request merged**
