### PR TITLE
Show replay percentage as a tooltip.

### LINKED ISSUE #12017: Show percentage as tooltip for the timer in the replay viewer
Currently, the percentage is always shown behind the time index and this kind of spoils the replay.

The progression percentage in the replay viewer could be shown as a tooltip.
That way, if you want to know the progression, you can still check the progression.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #12017.

### CODE REVIEW

**Review by Micr0Bit — CHANGES_REQUESTED** [review]
theres another thing that is annoying as hell ... when you fast-forward the replay ... the timer will get switched with the current "%-speed up" every second ... so i cant constantly see the timer when im fast-forwarding ... since this is in the same area ... could you maybe remove that bs ? ... or do you want a ticket for that ? ...

**Comment by pchote** [comment]
No, that serves a useful purpose so I'm not going to remove it.  We could adjust the timings so that it doesn't show quite as often, but that would be its own issue/pr.

**Comment by Micr0Bit** [comment]
useful purpose ? ... i mean , when i click on the 200% button , why would want the game to tell me that the speed is 200% ... the button is already highlighted ...

**Comment by pchote** [comment]
The main purpose is to distinguish pausing, which can be triggered by a hotkey.

**Comment by reaperrr** [comment]
Needs rebase.

**Comment by Micr0Bit** [comment]
:+1:

**Comment by pchote** [comment]
Rebased.

**Comment by reaperrr** [comment]
Works in the shipping mods, but crashes when trying to open the replay browser in TS:
https://gist.github.com/reaperrr/35d8603bd7701a6bf875ed568dddd582

**Comment by pchote** [comment]
There is something weird with one of your replay files, I can't reproduce this locally.

Can you please find and upload the replay thats causing trouble?  You can find the culprit by logging `fileName` at https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs#L113.

**Comment by pchote** [comment]
Those replays crash on bleed, with an error that isn't related to this PR.  I'll investigate and maybe make a new PR for that.

**Comment by reaperrr** [comment]
> with an error that isn't related to this PR.

Suspected as much, but I wanted to wait for confirmation.

:+1:

**Comment by pchote** [comment]
FYI the problem is that old replays serialized the player colors in the old format (e.g. ` hsl,75,255,180`) that the game doesn't understand anymore.

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c8971941dd5ece90511a16a9035f03d9b4913353...20578e47af7b98641b8a6775b424d091fb1ad766)

**Pull request merged**
