### PR TITLE
Avoid BuildUnit crash if the item is invalidated before the task runs.

### LINKED ISSUE #18970: Playtest TD Crash (Engineer/Airstrip Bug?)
Replay: [Playtest Crash.zip](https://github.com/OpenRA/OpenRA/files/5743905/Playtest.Crash.zip)

[Logs.zip](https://github.com/OpenRA/OpenRA/files/5743907/Logs.zip)

^Moments before crash

### PR DESCRIPTION
**Pull request by pchote**
Fixes #18970.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
Changes lgtm but untested.

**Comment by deleted-user-1** [comment]
So the problem was not the item that was currently building but a new order to build an item which has become invalid when the owner changed in a tick before the frame end task had run? I'm wondering why MD suggested it crashed at the mentioned line when debugging. As said, I don't know how to reproduce the original crash.

**Comment by pchote** [comment]
It did crash at the line you reported, but the problem originated in the method that called the function that has that line.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ae703659fd83845706dddb13f1284d06c6bbf3f0...60404902bc81081073ca3bb144936260818fb701

eea0ca1

**Pull request merged**
