### PR TITLE
Added more blend modes

### PR DESCRIPTION
**Pull request by Mailaender**
I also set up translucency on the TS mod.

### CODE REVIEW

**Comment by reaperrr** [comment]
Supporting more blend modes is a good thing, but we can't take the 2nd commit in its current form, for two reasons:
1) We already apply 25% alpha translucency via palette in most cases, so several effects like missile smoke and artillery explosions are now _too_ translucent.
2) `Translucent=yes` in original TS was dynamic, increasing translucency per frame (presumably), which a static blend mode can't reproduce.

So even if we used the blend mode instead of palettes with alpha (which is questionable, since the latter at least give us control over the static translucency level), this wouldn't be the end solution either way, so the question is whether we should apply any yaml changes here at all.

**Comment by Mailaender** [comment]
I think `wake` has no translucency added using palette effects and it's what impressed me most.

**Comment by reaperrr** [comment]
OK, but I still think we shouldn't mix and match both approaches on the same sequences, and in most other cases the translucency is still too strong compared to the original. I'm fine with leaving it on `wake` and `moveflsh` as examples for now, but the rest should stick to the pre-defined alpha palettes and just chose one with higher translucency where necessary. But that should be done in a separate PR, in my opinion, to prevent discussions and potential disagreements from blocking the merge of the new blend modes.

**Comment by Mailaender** [comment]
Removed the controversial entries.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
As discussed with @pchote on IRC, we'll merge them for now.
We might still remove them again in the future if they ever cause any problems, though.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ca5af93199f6482eb0d012e33004bb6d61000c9f...4a079be6c571158c1ad3c556aa3bed6c1c03e906

**Pull request merged**
