### PR TITLE
Fix map previews and order in TD

### PR DESCRIPTION
**Pull request by abcdefg30**
Follow-up to #18714. The previews and maps are now in order with the remasters.

### CODE REVIEW

**Review by Smittytron — APPROVED** [review]
LGTM

**Comment by pchote** [comment]
Can you explain where all the changes in the first commit come from?
nod04a and nod04b are a clean swap, but when I swap back gdi04a/b i see many changes to the actor placement and lua script so these do not appear to be a simple rename.

**Comment by abcdefg30** [comment]
I can only assume that git doesn't display that correctly. I didn't change any of the files directly.

**Comment by pchote** [comment]
Hmm, looks like I made a mistake when first testing. I don't reproduce my original problem when I repeat it more deliberately now.

**Review by pchote — APPROVED** [review]
Technical changes look fine, and i'll trust that you are correct in this matching the remaster.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/56ed09c230f2c7df5a6e565a1662332441b304d0...ea2b6d52a56aa7692aa31c9ffbba9f0499662fe1

**Pull request merged**
