### PR TITLE
Fix yaml merging (again).

### LINKED ISSUE #12362: Crash in Survival02 mission
Hey guys,

Trying to figure out a fix for a crash that keeps re-occuring in survival02 mission when bombs drop from the bombers right before the final wave comes in.  I tried to search through the forums for an answer but the one thread I found wasn't clear on the fix.

I generate this exception log:

Red Alert Mod at Version release-20161019
on map 85e6243ee3c8d6aa7c6634a805678e30a508243b (Survival 02 by Nuke'm Bro.).
Date: 2016-11-08 01:46:47Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `bomblet` does not have a sequence named `open`
   at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName)
   at OpenRA.Graphics.Animation.GetSequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName)
   at OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after)
   at OpenRA.Mods.Common.Projectiles.GravityBomb..ctor(GravityBombInfo info, ProjectileArgs args)
   at OpenRA.Mods.Common.Projectiles.GravityBombInfo.Create(ProjectileArgs args)
   at OpenRA.Mods.Common.Traits.Armament.<CheckFire>c__AnonStorey0.<>m__1()
   at OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a)
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target)
   at OpenRA.Mods.Common.Traits.AttackBomber.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

'preciate it!

### LINKED ISSUE #12519: (Map?) Yaml merging broken (at least for map-specific weapon yamls)
Using #12512 as testcase I tried negating the `Image` of RA's 90mm and 105mm, neither `-Image:` nor `Image:` worked.

Tried the same on RA shellmap as well to make sure it's not map-specific, same result, image still shows.

### PR DESCRIPTION
**Pull request by pchote**
Node removal was previously only run on the first level children unless they require additional merging.  This propagates it further down the tree.

Fixes #12362.
Fixes #12519.

### CODE REVIEW

**Comment by reaperrr** [comment]
Seems like TS has a bogus `DepthSprite` removal somewhere.

**Comment by pchote** [comment]
This is caused the hacked sequence `Defaults` code, which is completely incompatible with managing node removals at the yaml level.  I'm not prepared to rewrite our sequences again at this point, so i'm going to give up on fixing this properly.

**Comment by pchote** [comment]
Reopened using a more pragmatic approach that solves the problems (only) with the weapon definitions.

**Review by abcdefg30 — APPROVED** [review]
This resolves the crash.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0cdc758a7b601fb5e8e96042442e6935a84778d1...b85a6ffd7548a1305a81d0788014d4e82e7418cd)

**Pull request merged**
