### PR TITLE
Registered Linux MIME type to directly load replays

### PR DESCRIPTION
**Pull request by Mailaender**
I adapted our RPM and tested it on @openSUSE with KDE.

opensuse-kde-openra-mime

Maybe @obrakmann can help with the Debian package. It should be similar to the spec file changes.

### CODE REVIEW

**Comment by Mailaender** [comment]
Removed the `StartupNotify=false`.

**Comment by Mailaender** [comment]
Added it to the next release milestone as this needs testing (after installing a packaged version) by more people on more distributions and it seems this was forgotten and ignored last week.

**Comment by obrakmann** [comment]
Nice, it accepted my novell login from work for the download :p

Anyway. I can confirm that this works as advertised. Icons are still the distro ones as I mentioned in an earlier comment.

I believe the problem that replays from different versions could be opened still exists, at least it was possible for me (I always run with the version set, so I know I'm opening replays from different versions). I couldn't open replays from the last release, but I assume that was because the maps all changed (the game just dropped me into the main menu and didn't crash or anything, so that was nice. A dialog box stating the reason may be nice, though. Not sure if that's possible).

**Comment by obrakmann** [comment]
You need to `make install-linux-mime prefix="/usr" DESTDIR="$PWD/packaging/linux/$ROOTDIR"` in `packaging/linux/buildpackage.sh` as well, otherwise the built package is missing the .xml files

**Comment by obrakmann** [comment]
And I still get crashes when opening an incompatible replay with this rebased onto current bleed. Ideally, it shouldn't even start the replay at all.

**Comment by Mailaender** [comment]
Fixed.

**Comment by Mailaender** [comment]
> And I still get crashes when opening an incompatible replay with this rebased onto current bleed. Ideally, it shouldn't even start the replay at all.

I filed https://github.com/OpenRA/OpenRA/pull/7353 to resolve this.

**Comment by obrakmann** [comment]
This works wonderfully now (together with #7353). :+1:

**Comment by obrakmann** [comment]
Adding Windows integration doesn't look to difficult according to http://nsis.sourceforge.net/File_Association (assuming it works :p)

**Comment by Mailaender** [comment]
Sorry, this is only about the Linux FreeDesktop specifications. This has already been in development for over a year so I don't want to expand the scope of this further. It will be pretty easy for others to do the followup changes for their favorite OS though later on.

**Comment by pchote** [comment]
:+1: now works properly for me under Ubuntu.  I assume that other WMs will conform to similar standards as either/both of Unity and KDE.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/52b8a3cffb55db641777947d711a852d6382ed9a%5E...52b8a3cffb55db641777947d711a852d6382ed9a

**Pull request merged**
