### PR TITLE
Make modchooser's loadscreen consistent

### PR DESCRIPTION
**Pull request by GraionDilach**
as described in #8592.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1: We probably should do a re-release of the playtest tomorrow.

**Comment by penev92** [comment]
I am still getting `Exception of type `System.IO.FileNotFoundException`: File not found: ./mods/modchooser/chrome.png` though.

**Comment by Mailaender** [comment]
Removed the "Fixes", but we still want to get this for consistency.

**Comment by GraionDilach** [comment]
I ran out of ideas how to take care of #8592 for now. :disappointed:

**Comment by abcdefg30** [comment]
> but we still want to get this for consistency.

Not a big deal then. :+1:

**Pull request merged**
