### PR TITLE
Fix Hovers desync caused by changing 'WorldVisualOffset' in renderer.

### LINKED ISSUE #21297: Desync related to Hovers
At 0741439dd6face978a46bf3b0e7a3e4f363280b2
[disnyc.zip](https://github.com/OpenRA/OpenRA/files/13919524/disnyc.zip)

### PR DESCRIPTION
**Pull request by dnqbob**
Fix #21297

### CODE REVIEW

**Comment by dnqbob** [comment]
Under testing, I also need your testing result on ensuring the fix. Please set the frame option like below during testing:
捕获

**Review by PunkPun — APPROVED** [review]
Changes makes sense to me, untested

**Comment by abcdefg30** [comment]
Why is this marked as draft?

**Comment by dnqbob** [comment]
Because it was under testing.
捕获

We hardly fully test the PRs merged recently and flaws and crash like this will happen in unexpected ways.

**Comment by PunkPun** [comment]
it was tested, but it's hard to catch everything, especially bugs hidden in barely related areas. I thought I did consider desyncs, no idea how I didn't catch the error

**Comment by dnqbob** [comment]
I think it should be the problem of frame setting. Limited frame will make this problem hard to expose.

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4c6cdaae7aa71f37a4bc7d1776f47a4760ecfe40...db878ad65c1b8c557f28128f3fc0bbc1fe76c099)

**Pull request merged**
