### PR TITLE
Add BotModule sync check debug setting.

### LINKED ISSUE #15858: Add a sub-checkbox for checking sync around bot modules
https://github.com/OpenRA/OpenRA/pull/15830#discussion_r235820774

### PR DESCRIPTION
**Pull request by pchote**
Fixes #15858.

### CODE REVIEW

**Comment by reaperrr** [comment]
Looks good. We should at least check if the building repair module can be performance-optimized as checking sync around it can lag even fast machines, but that's a separate issue.

**Review by reaperrr — DISMISSED** [review]

**Comment by pchote** [comment]
The issue won't be the repair module, but with the sync calculation itself which is really expensive.

**Comment by pchote** [comment]
I wonder whether it would be smarter to not implement a GUI option for this - we don't want people accidentally enabling this considering the perf overheads.

**Comment by obrakmann** [comment]
> I wonder whether it would be smarter to not implement a GUI option for this - we don't want people accidentally enabling this considering the perf overheads.

What I'd do is keep all the checkboxes, but hide them all behind a config option that doesn't have one. So for normal users, the whole Debug section on the advanced page wouldn't be visible.

**Comment by pchote** [comment]
Done. I also added a checkbox for your strict activity checking (will hopefully remind people that this work is still not complete), and additional description tags for https://github.com/OpenRA/OpenRA/wiki/Settings.

**Review by obrakmann — COMMENTED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d54cc51d494e4351eff387a3df630c7d95accef3...cb2c37c3307842959cbe5c31498f96ff05700145

**Pull request merged**
