### PR TITLE
Removed the artsrc directory

### PR DESCRIPTION
**Pull request by Mailaender**
Placed it at https://github.com/OpenRA/ArtSrc instead.

### CODE REVIEW

**Comment by x-a-n-a-x** [comment]
Maybe we could also fill the README.md file with a small text, explaining what artsrc contains.

**Comment by Mailaender** [comment]
Send a pull request there. I also already set you as a maintainer for that repository.

**Comment by penev92** [comment]
Well :+1:

**Comment by Unit158** [comment]
:+1:

**Pull request merged**
