### PR TITLE
More map churn

### LINKED ISSUE #10708: [RA] The official map pool. Out with the old...
As requested here's a list of maps I believe think should be wiped off the official map pool. We need to take advantage of newer and better maps from the resource center and make sure we regularly replace the outdated and old. This will also encourage people to make more and better maps for the future.

This list I think presents the worst ones and imo are beyond salvage. The list progress in the same order as in the official map tab in-game.

[Burlesca](http://resource.openra.net/maps/7126/) (2 players)
[Styrian Mountains](http://resource.openra.net/maps/7284/) (2 players)
[Contact](http://resource.openra.net/maps/7537/) (4 players)
[Island Hoppers](http://resource.openra.net/maps/6925/) (4 players)
[Pearly Wastelands](http://resource.openra.net/maps/7292/) (4 players)
[Breaking Point](http://resource.openra.net/maps/7544/) (8 players)
[Central Conflict](http://resource.openra.net/maps/7541/) (8 players)
[Raraku](http://resource.openra.net/maps/7179/) (8 players) (swap with Caffeinated, see #10710)
[Ring of Fire](http://resource.openra.net/maps/7273/) (8 players)
[High & Low Extended](http://resource.openra.net/maps/7357/) (10 players)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30615247-ra-the-official-map-pool-out-with-the-old?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10710: [RA] The official map pool. ...in with the new.
The hardest maps to replace are the 6 player maps and up since few people are making regular mass player maps, and they vary greatly in quality. However here's a list containing some 2-player maps, and a variety of team and FFA maps. 

**Playtested**:

[Behind The Veil](http://resource.openra.net/maps/8795/) (2 players)
[Dual Cold Front](http://resource.openra.net/maps/9160/) (2 players)
[Northwest Passage](http://resource.openra.net/maps/8564/) (2 players)
[Warwind](http://resource.openra.net/maps/8925/) (2 players)
[Winter Storm](http://resource.openra.net/maps/6902/) (2 players)
[Sunstroke](http://resource.openra.net/maps/9020/) (3 players, FFA)
[Sudden Death](http://resource.openra.net/maps/9356/) (5 players, FFA)
[Pool Party](http://resource.openra.net/maps/9134/) (10 players, 5v5)

**Re-instate map removed from the latest playtest/bleed**:
[Caffeinated](http://resource.openra.net/maps/7369/) (8 players)

This map is the same map type, size and has the same player number (8) as Raraku. Raraku is a monstrosity and is suggested for removal in #10708. Imo, Raraku looks hideous, the map itself and in the map chooser, but also has poor options for team play and FFA. Caffeinated on the other hand looks decent as a non-symmetrical map, has multiple options for team-play, even multiple 4v4 positions. Personally, the games I remember on this map was generally fun. The are numerous maps  in the map pool currently that should be dumped _way_ before Caffeinated.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30615640-ra-the-official-map-pool-in-with-the-new?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10954: [RA] Official Map Pool: Alter Keep Off The Grass 2 (2 players) - balance, aesthetics
[**Keep Off The Grass 2, current**](http://resource.openra.net/maps/7242/), (2 players)

Changes:
Moved the first ore patch for both spawns to balance ore access.
Changed ridges and debris to balance fields around the players.  #10347
Tweaked the players spawn's first ore field after discussion below.

[**Keep Off The Grass 2, altered**](http://resource.openra.net/maps/9542/), Playtested (revision 4), altered to revision 5 after discussion below.

keep off the grass 2 compare revision

keep off the grass 2 rew

### PR DESCRIPTION
**Pull request by obrakmann**
Closes #10708.
Closes #10710.
Closes #10954.

//cc: @SoScared

### CODE REVIEW

**Comment by pchote** [comment]
We'll want these for the playtest too, right?

**Comment by obrakmann** [comment]
I suppose so.

**Comment by Mailaender** [comment]
A fine selection of maps without tile nor spawnpoint problems. :white_check_mark:

**Comment by abcdefg30** [comment]
Looks good to me, too. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ef081102f57310ea51f8e83b870a5d8327ac4ae4...3b777ae609a9efbd0ce3b7cb5185f5fda236b3cc)

**Pull request merged**
