### PR TITLE
Fix left click orders

### LINKED ISSUE #11041: Can't deploy MCV, send vehicles to service depot or land aircraft in left-click order mode
It seems the latest playtest has a bug where I can't use the deploy or similar action on a vehicle or building, it just selects the building instead. I was able to deploy the MCV using the keyboard shortcut instead, but this makes the game quite unplayable for the rest.

I am using classic left-click orders and have verified it working with right-click orders.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #11041.

### CODE REVIEW

**Comment by reaperrr** [comment]
:white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/35940b2b8eaa2e0d0654c0fa1771fe9f04e550aa...7489b40276f3f6cd53c0af73118a0e8cc2e594f7)

**Comment by mjmartin** [comment]
FYI, it's not fixed in playtest-20160403.

Download playtest-20160403, make sure left-click orders is on.
Start a skirmish, try deploying the MCV

**Comment by pchote** [comment]
This PR fixes those issues.  It came after playtest-20160403 and will be shipped in the next one.

**Comment by mjmartin** [comment]
thanks Paul

**Pull request merged**
