### PR TITLE
Fix FCOM still providing space while being captured

### LINKED ISSUE #17354: Placing structures next to a FCOM still possible while it is being captured
Expected behaviour is to act like Conyards. Reported by Printer at https://forum.openra.net/viewtopic.php?p=310932#p310932.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #17354.

### CODE REVIEW

**Comment by reaperrr** [comment]
> OpenRA.Utility(1,1): Warning: Actor type `fcom` grants conditions that are not consumed: being-captured

I'm actually at a loss, no friggin' clue what's missing here.

**Comment by pchote** [comment]
The campaign-rules.yaml overrides FCOM, removing the BaseProvider to turn it into a normal campaign structure. You’ll need to remove the granted condition there too.

**Comment by reaperrr** [comment]
> The campaign-rules.yaml overrides FCOM, removing the BaseProvider to turn it into a normal campaign structure. You’ll need to remove the granted condition there too.

...which brings us back to #16278, because
```
	CaptureManager:
		-BeingCapturedCondition:

	CaptureManager:
		BeingCapturedCondition:

	-CaptureManager:
	CaptureManager:
```
none of these attempts worked.

**Comment by reaperrr** [comment]
Updated. It seems the Capturable `~disabled` approach was taken for the same reason, so until these yaml merge issues are solved, I think this is a tolerable work-around, especially since this should be picked for a potential bugfix release.

**Review by tovl — APPROVED** [review]
:+1:  to this workaround until  #16278 gets a proper fix.

**Comment by abcdefg30** [comment]
Do we want to add a yaml comment indicating that this is a workaround?

**Comment by reaperrr** [comment]
There are probably quite a few other work-arounds for the yaml merge bug that don't have a comment either, and I'm not in the mood to look for them and add comments everywhere.
Filed #17375 instead.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2c76f8e60815891c77e2aedbbfa1a111d40a8dd6...db19d48d5bb296490bf4f8aedcd6ea4967689163)

https://github.com/OpenRA/OpenRA/commit/99bc783eb838443b2facf5887b10d138fc9b42e3

**Pull request merged**
