### PR TITLE
Fix the attack-move cursor appearing for units which can't attack-move

### LINKED ISSUE #9383: Attack Move order doesn't work for Tanya in Allies01 (and probably other missions)
You can issue the attack-move order for a group of actors, but tanya will stay at her original location.  She should at least move to the target location, even though these missions have explicitly disabled auto-targeting.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26805794-attack-move-order-doesn-t-work-for-tanya-in-allies01-and-probably-other-missions?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by abcdefg30**
Easily noticeable with tanya on the higher difficulties.
Fixes #9383.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Updated as requested by @pchote.
Fixes #9383 now.

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
Looks good to me :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/80316f1ee101c5e8c50b570b7bdada5c4e2180a5

**Pull request merged**
