### PR TITLE
Fix flickering tooltip in slow speed game and Map editor

### LINKED ISSUE #12356: Map editor sidebar tooltips are flickery
The tooltips flicker in and out of existence as you move the mouse across the sidebar.

### LINKED ISSUE #13335: Tooltip on build menu flickers when game is set to 'slow' speed.
sdfg

When moving the mouse slowly over the build menu the tooltip flickers. It happens only when the game is set to 'slow' speed.

### PR DESCRIPTION
**Pull request by rob-v**
Closes #13335
Closes #12356

### CODE REVIEW

**Comment by pchote** [comment]
I found an interesting issue while testing this: opening the ingame menu and mousing over the game host (so it shows the "game admin" tooltip) completely disables the tooltip delay after you close the menu.

**Comment by rob-v** [comment]
Interesting... this also happens in release. If it was really needed to support different behaviour, it could be set in OnMouseEntered.

Fixed by hiding widget instead of TooltipContainer like in another case.

**Review by reaperrr — APPROVED** [review]

**Comment by pchote** [comment]
This is a simple fix to something that really bugs me, so &rarr; playtest.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ad617ba03584af81569a43046577dfdc2e06588d

**Pull request merged**
