### PR TITLE
Fixed possible NREs in AI.StateMachine

### PR DESCRIPTION
**Pull request by Mailaender**
Discovered by Coverity.

### CODE REVIEW

**Comment by penev92** [comment]
Doesn't sound very likely to happen, but OK :+1:

**Comment by obrakmann** [comment]
I guess the `Update` method should get a null check as well, then.

**Comment by Mailaender** [comment]
Better safe than sorry.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/53c6c88ae3ce71044dba11b4fa5c93e1056bcbc5%5E...53c6c88ae3ce71044dba11b4fa5c93e1056bcbc5)

**Pull request merged**
