### PR TITLE
Switch WithSpriteRotorOverlay to WithRotorSpriteOverlay

### PR DESCRIPTION
**Pull request by reaperrr**
In accordance with other render traits and suggestion in #9541.

Note: While not strictly necessary for this release, it would spare modders from another rename with Next+1 if this went into prep-1512.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Upgrade rule?

**Comment by pchote** [comment]
I think it may be better to wait so that mods written for these playtests remain compatible with the final release.

**Comment by pchote** [comment]
@Phrohdoh raised an interesting point in IRC: This trait is redundant now that we have upgrades for flying vs landed aircraft.

**Comment by reaperrr** [comment]
Oh right, we could use `WithIdleOverlay`. I'll close this for now, might revive it later to remove the trait instead.

**Pull request closed without merging**
