### PR TITLE
D2K - Add Mauddib's Cave to map pool.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Depends on #12784.

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Rebased.

**Review by reaperrr — APPROVED** [review]

**Comment by abcdefg30** [comment]
I think you need to reimport this map is it's one of the maps affected by the final update in #12784.
mauddibs_cave

**Comment by MustaphaTR** [comment]
Updated.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/cd69537d7d4b76557b069784508cd5f06e8bb026...1a9afe8f752a3c3a94fe7a8075496815c458cf14)

**Pull request merged**
