### PR TITLE
Add more TD maps.

### PR DESCRIPTION
**Pull request by pchote**
Restores Deterring Democracy as requested in #9534, and adds Escalations and Vectors of Battle from http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=18786

### CODE REVIEW

**Comment by clemty** [comment]
:+1:

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9e467787300821e72a418da483cf7c983d1faa4e...22c81d1f6e70338ab16bbd24a3f641ca52ec4a54)

**Comment by psydev** [comment]
I thought Letters from Lexington was a really great 1vs1 map, I played it a lot with AoAGeneral.
I know there's a viceroid wander issue, but I think it's a good map for inclusion.

**Pull request merged**
