### PR TITLE
Added carryalls to spectator Economy statistics

### PR DESCRIPTION
**Pull request by PunkPun**
supersedes #20079

### CODE REVIEW

**Comment by pchote** [comment]
Can we rename `UpdatesDerrickCount` to `UpdatesSpecialActorCount` (or `UpdatesModActorCount` or something else sufficiently generic) and reuse the rest of the derrick ui plumbing instead of hardcoding multiple mod-specific actors here?

**Comment by PunkPun** [comment]
I think here hardcoding is the way to go. Unless a spectator UI refactor is planned I think we should just follow the convention. Using the tag for both will just cause issues in the future.

**Review by dragunoff — APPROVED** [review]
Works and LGTM :+1: 

I gotta agree with @PunkPun here - hardcoding seems like the simpler way to go instead of trying to lump dericks and caryalls together. The observer UI is anyways full of CNC-specific idioms and stuff. I don't consider it generic at all.

**Comment by Mailaender** [comment]
[bleed](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/71e3fd5f5faf86d6b86c921d293ebb50b9db8946...481cda94f4c3c6934601b692ddf933751609c804)
[prep](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/a3732e660f3ddce911fb9247999c4e98f3e60615...9398350f0e1e271ebeb403096da42bbaf94593b3)

**Pull request merged**
