### PR TITLE
Fixed possible NREs in WithMuzzleFlash

### PR DESCRIPTION
**Pull request by Mailaender**
Discovered by Coverity. Similar to https://github.com/OpenRA/OpenRA/pull/8327/.

### CODE REVIEW

**Comment by penev92** [comment]
:+1:

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
Changelog: https://github.com/OpenRA/OpenRA/wiki/Changelog/7a56b971ecc85248725f57752ef842cb6c202a5a

**Comment by GraionDilach** [comment]
@reaperrr Why you added that to the playtest's changelog? That should be a new entry in bleed's one.

**Comment by reaperrr** [comment]
Because I didn't pay attention... fixed.

**Pull request merged**
