### PR TITLE
Enable 2 more Code Quality Rules

### PR DESCRIPTION
**Pull request by RoosterDragon**
Following on from #20802, #20812

Enforces 2 code quality rules across the project. I have batched together a PR for these rules as the diff is large but boring.

See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ for explanation of each rule.

### CODE REVIEW

**Review by Mailaender — DISMISSED** [review]

**Comment by penev92** [comment]
The rules are fine, but `IOrderTargeter`s and traits that are left as `internal` (making them as unintentional violations of the sealing rule) should become `public` rather than `sealed`.
I don't know if we want to deal with that here, but it's worth mentioning.

**Comment by RoosterDragon** [comment]
Future PRs that make things public can choose to unseal them at the same time if it is appriopriate.

**Comment by abcdefg30** [comment]
Seems like this needs a rebase again.

**Comment by RoosterDragon** [comment]
Rebased

**Review by penev92 — APPROVED** [review]
OK

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f5879892a966c04841bafd43832e586a554fab36...3a3e80824ecc4860a3281486f350723b5d856fe4)

**Pull request merged**
