### PR TITLE
Smarter Variable Linting (Removal of Dummy Properties)

### PR DESCRIPTION
**Pull request by atlimit8**

### CODE REVIEW

**Review by pchote — COMMENTED** [review]
I'm a bit concerned that this would back us into a corner if we ever wanted to use condition references on dictionary keys.  I wonder whether it would be more futureproof to do this with arguments on the attribute e.g. `[ConsumedConditionReference(keys: true, values: true)]`"?

**Comment by abcdefg30** [comment]
@atlimit8 what's the status here (i.e. what about @pchote's question)?

**Comment by pchote** [comment]
Moving to future milestone.

**Comment by atlimit8** [comment]
Superseded by #18132.

**Pull request closed without merging**
