### PR TITLE
Remove redundant Effects

### PR DESCRIPTION
**Pull request by reaperrr**
`SpriteEffect` can (now) do everything that `Explosion`, `Corpse` and `Smoke` could do, so I scrapped those three to get rid of some redundancy and duplication.

Additionally, the only thing in `Game` that used `SpriteEffect` was the `WorldInteractionControllerWidget`, which itself is not required by anything in `Game`, so I moved both up to `Mods.Common`.

### CODE REVIEW

**Comment by GraionDilach** [comment]
I'm unsure about shifting WICW, but I welcome `SpriteEffect` phasing out the rest. :+1:

**Comment by pchote** [comment]
Shifting WICW is extremely welcome.  It was the bottleneck that was forcing several other mod-level things (e.g. Selection bars, target flashing, SpriteEffect) to live in engine.

**Comment by chrisforbes** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/4e8de774d41b241bce3e4609bb30b5f9061e4500...cf438bf3c2647ff617132dfb8424b79ed6783a10)

**Pull request merged**
