### PR TITLE
Add unit command bar to D2K.

### PR DESCRIPTION
**Pull request by pchote**
As discussed on IRC, the D2K source artwork uses proprietary layer styles that are not compatible with Gimp or Pixelmator, so I cannot complete the artwork myself.

I am hoping that @x-a-n-a-x or another photoshop-wizard can backport the layout changes to the source psd and then build some proper bar artwork, ideally IMO using some of the styling influences from around the minimap.

If worst comes to worst, we can take the artwork as-is and just accept ugly programmer art for the first playtest.

### CODE REVIEW

**Comment by rob-v** [comment]
It seems not working - no visual feedback if buttons are pressed and on, Deploy doesn't work.

**Comment by pchote** [comment]
> no visual feedback if buttons are pressed and on

Indeed.  This requires proper artwork.

**Comment by x-a-n-a-x** [comment]
I will take care of updating the source psd.

**Comment by pchote** [comment]
@x-a-n-a-x has done some nice looking artwork for this.  I have partially set up the chrome.yaml, but still need to move the buttons around and set up the backgrounds.

**Comment by pchote** [comment]
Updated properly with @x-a-n-a-x's new artwork:

screen shot 2017-06-28 at 21 29 30

**Review by reaperrr — APPROVED** [review]

**Comment by rob-v** [comment]
There are some differences compared to RA, all/some of them probably intentional, but there are some inconsistencies in D2K, which seems like not intentional.
RA
Stop - visual feedback on click and press
Stance - visual feedback on click, not on press
Tooltips - all transparent
D2K
Stop - visual feedback only on press
Stance - no visual feedback
Tooltips - some transparent, some not

image

image

Notice also color, it is hardly visible which is activated, in RA it is clearer, should be changed IMO:
image

**Comment by reaperrr** [comment]
> Notice also color, it is hardly visible which is activated, in RA it is clearer, should be changed IMO:

Seeing his example, I have to agree.

**Comment by x-a-n-a-x** [comment]
I modified the chrome.png file and now, here is how it looks. Comments are welcome.

commandbar_newcolors

**Comment by reaperrr** [comment]
Much better, imo 👍

**Comment by pchote** [comment]
Fixed.

**Review by rob-v — APPROVED** [review]
👍

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5fb515e012c1427a2a14b547f1eb0e2582a63fc5...17f364a963d65d268cbdf693a0864d6367c8c3dc

**Pull request merged**
