### PR TITLE
Fix observer GUI showing disabled support powers.

### LINKED ISSUE #8750: Statistics show two chronosphere icons
Map is the official Vegetation.
stat

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24612035-statistics-show-two-chronosphere-icons?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by GraionDilach**
Fixes #8750.

### CODE REVIEW

**Comment by pchote** [comment]
A simple fix for a visible polish issue, so promoting to [For Stable].

**Comment by penev92** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/bdc7fb53bac465ee3802a24755226b26caffe0bb)

**Pull request merged**
