### PR TITLE
Handle Out-of-Sync at server level

### PR DESCRIPTION
**Pull request by ubitux**
While working on the protocol winstate thing (https://github.com/OpenRA/OpenRA/pull/17578), the discussion of having the winstate desync handled at server level versus the syncstate desync handled at client level was raised. This PR attempt to move the desync code from client to server. Aside from the consistency benefit with the future winstate thing, it also is much more user-friendly error wise: the players get kicked out of the game instead of their game crashing.

One thing I don't know how to handle though is the sync report. What should we do about it?

Edit: looks like this now client side (we still have to close the game though):
2020-04-26-141258-jaeX3ash

### CODE REVIEW

**Comment by pchote** [comment]
> One thing I don't know how to handle though is the sync report. What should we do about it?

This *must* still be generated (if enabled), for all clients.

See also #4084 and #2850.

**Comment by ubitux** [comment]
> > One thing I don't know how to handle though is the sync report. What should we do about it?
> 
> This _must_ still be generated (if enabled), for all clients.
> 
> See also #4084 and #2850.

I see; well then I can keep the code in the client side and just remove the exception throwing, but I don't think we want that code duplicated between client & server. Feel free to close this PR if you think this is the wrong approach.

**Comment by abcdefg30** [comment]
@ubitux do you plan to pick this up again now that #17578 is merged?

**Comment by ubitux** [comment]
> @ubitux do you plan to pick this up again now that #17578 is merged?

I'm a pretty busy with other activities currently, but if people wants it I can try to allocate some time. The patch was pretty simple and straightforward IIRC, so it shouldn't be hard for someone to refresh it.

**Comment by pchote** [comment]
Theres not much we can do here, so closing to help clean up the PR queue.

**Pull request closed without merging**
