### PR TITLE
Fix Joystick scrolling stuck

### LINKED ISSUE #13300: Right click joystick scrolling getting stuck
I have my mouse set up to right click joystick scrolling (like in generals), however sometimes when issues orders (also with right click), and panning the camera around, the camera seems to randomly start moving one way, and the only way to stop it is to right click, which often means troops end up being sent to the other side of the map.

If it helps, I think it may be something to do with left click too. Immediately left clicking while in a right click joystick move maybe.

I've attached a screenshot of my input settings:

openrainputsettings

To replicate pretty easily:
1. Enter an openra game.
2. Make sure you have right mouse scrolling set to joystick in input options as in the screenshot.
3. In one quick action, right click + hold, move mouse,  left click while panning, release right click. This needs to be done pretty quickly.
4. Screen will continue panning after right mouse is released.

### PR DESCRIPTION
**Pull request by rob-v**
Closes #13300

### CODE REVIEW

**Comment by reaperrr** [comment]
I'll count @dsimmons87 last comment on #13300 as +1, but this branch seems to be based on the bleed when it had that widget `map` conflict, so could you please rebase to latest bleed?

**Comment by rob-v** [comment]
Rebased.

**Review by pchote — APPROVED** [review]
I have pushed an extra commit that allows scrolling (both joystick and "standard") to continue if another  mouse button is pressed while the scroll mode is active.  This makes our behaviour consistent with the original games.

:+1: with my fix included, but we'll need another :+1: before merging.

**Comment by pchote** [comment]
This is otherwise a simple bug fix that is simple to review, so adding to the playtest milestone.

**Review by reaperrr — APPROVED** [review]
Looks good to me.

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ab28b0bf101a9d10ac76845a407c1299ec8126a7...6e1f68d9a37594755424b576273868a95b10f183

**Pull request merged**
