### PR TITLE
Remove automatic GeoIP download from the build scripts.

### PR DESCRIPTION
**Pull request by pchote**
This PR implements a quick first step towards #17529, removing the database fetching so people/robots can at least compile the project again. I have kept the references in the packaging script for now (which is why AppVeyor is still failing) because I expect that the solution for the prep branch will be to ship the file.

The game is already set up to gracefully fail back to showing "Unknown Location" if the database is missing. A followup PR will be needed to fix the ingame behaviour after we decide on an approach in #17529.

### CODE REVIEW

**Comment by pchote** [comment]
We should hold off merging any other PRs to bleed before this one, to avoid breaking the build on bleed.

**Comment by pchote** [comment]
Added a second commit to remove the database from install/packaging. This should be merged to bleed but not picked to prep.

Once this has been merged I (or someone else) can push a commit straight to prep that adds https://github.com/flathub/net.openra.OpenRA/blob/master/GeoLite2-Country.mmdb.gz to the root of the repo.

**Review by reaperrr — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
First commit:
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/b7bddf19f7057ac09ea2ad48c969c9fbba623f53...f78565363a9607efa2fb7f1ebf72788209f9523b)
https://github.com/OpenRA/OpenRA/commit/e31bcd3f02f5d4af9e4cb3aed1bd18348e771f6e

Second commit (not on prep):
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5b2822e58c9b4a80dbe45e2f177144ebf9b2e84d...2359936ee689f994dc5369d88b4ae1bc096018ff)

**Comment by pchote** [comment]
#17535 fixes an omission and f5e4c1d9528fc54a34448d9348dab9b9e5a4cba0 adds the last license-compatible version of the GeoIP database to prep.

**Pull request merged**
