### PR TITLE
Fixed the GeoIP download on blacklisted machines

### PR DESCRIPTION
**Pull request by Mailaender**
This should fix the build on Travis CI. See https://github.com/OpenRA/GeoIP-Database/actions where the magic happens.

### CODE REVIEW

**Comment by obrakmann** [comment]
I'm not sure if github properly understood that you updated the geoip.yml file. When you look at the workflow file under the Actions tab, it still says "on: push", while it says "on: schedule" in the repo.

**Comment by Mailaender** [comment]
I initially set it up with `on: push` to get a download and check permissions. The `on: schedule` is a test for tomorrow and the future as we don't want to trigger this manually.

**Comment by obrakmann** [comment]
So the scheduled job seems to have run, but didn't actually update the release as far as I can tell, even though the logs say it did. No idea what to make of this.

**Comment by pchote** [comment]
When I asked about this earlier, the suggestion was that the file would be replaced in the release without necessarily updating any other metadata on the tag.

The latest version of the database was released on 2020-07-13. The current artifact on the tag is dated 2020-06-24, but the job ran 12 days ago on 2020-07-07 - before the latest version was released. So afaik it is still inconclusive as to whether it works or not - we will need to wait another two weeks and check whether the date in the file (the third byte is year, fourth is month, fifth is day) updates.

**Comment by pchote** [comment]
The database on the monthly release is now dated 2020-07-27, which matches the version I download locally. This confirms that the action is indeed running correctly.

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Pull request merged**
