### PR TITLE
Improve aircraft unreserving of structures

### PR DESCRIPTION
**Pull request by reaperrr**
I thought the issue with multiple helicopters landing on the same helipad still existed, but couldn't reproduce it.

Still, these changes might be wanted anyway.

### CODE REVIEW

**Comment by penev92** [comment]
Can you please drop the last commit?
I have a branch ready for PR-ing that merges `Plane`, `Helicopter` and `Aircraft` into a single `Aircraft` trait and I am waiting for aircraft-related PRs to be dealt with before I PR it. I have dealt with that there, so I'd like to keep the merge conflicts to a minimum.

**Comment by reaperrr** [comment]
Done.

**Comment by penev92** [comment]
Thanks.
Looks good to me :+1:

**Comment by abcdefg30** [comment]
:+1:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a8017c81acbfd688120d6de89209773fc9f2f7f0...344a8ed9dd3f8559c2387e0a38be006771fc6663)

**Pull request merged**
