### PR TITLE
fix stance icon not updating when selecting units

### LINKED ISSUE #20755: units stance icon reverts after savestate
Basically what title says. If you change your units to a different stance and then save the game when you reload the game the unit's stance icon will be back to the default. (The unit will retain whatever stance it was in though)

### PR DESCRIPTION
**Pull request by ThomasChr**
Will fix #20755

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
LGTM

**Review by RoosterDragon — CHANGES_REQUESTED** [review]
Two of the callers to `SetStance` manually set `PredictedStance` as well. You could remove those extra sets if `SetStance` will now deal with them.

**Review by RoosterDragon — DISMISSED** [review]

**Comment by ThomasChr** [comment]
@RoosterDragon 
Good catch!
Both locations are removed and we're saving at least 2 cpu cycles now ;-)

**Review by RoosterDragon — APPROVED** [review]

**Comment by RoosterDragon** [comment]
Candidate for prep?

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
> Candidate for prep?

Picking to prep isn't as simple. There are quite a few changes

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c0acc64efc407d891e473a3f9017f8d82dbe7d41...a3e05a05298c20c479a51bec2a07f7305f99f942)

**Comment by PunkPun** [comment]
https://github.com/OpenRA/OpenRA/commit/989dfb6b67ad16bcb26e5b2dc41d5d03ad585c71

**Pull request merged**
