### PR TITLE
Fix yaml merging

### LINKED ISSUE #2922: Bib: removal in modded maps won't work and crashes the game.
Was making a modded map in the RA in the INTERIOR theater and wanted to remove the Bib: stat from the OILB ( just added -Bib: ) but it won't work and to see if that happened to other structures like the power plant, i added too but I had the same problem. I think that removing Bibs from modded maps causes game crashes...
(Did this in Version 20130330)

Exception Log:
```
Exception of type `OpenRA.FileFormats.YamlException`: Actor type powr: Bogus yaml removals: [Bib, False]
   em OpenRA.ActorInfo..ctor(String name, MiniYaml node, Dictionary`2 allUnits)
   em OpenRA.Rules.<LoadRules>m__35(MiniYamlNode k, Dictionary`2 y)
   em OpenRA.Rules.<LoadYamlRules>c__AnonStorey28`1.<>m__3F(MiniYamlNode kv)
   em System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   em System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   em OpenRA.Rules.LoadYamlRules[T](String[] files, List`1 dict, Func`3 f)
   em OpenRA.Rules.LoadRules(Manifest m, Map map)
   em OpenRA.ModData.PrepareMap(String uid)
   em OpenRA.Game.StartGame(String mapUID, Boolean isShellmap)
   em OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   em OpenRA.Network.OrderManager.TickImmediate()
   em OpenRA.Game.<Tick>c__AnonStorey3A.<>m__A7()
   em OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey30.<>m__6A()
   em OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   em OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   em OpenRA.Game.Tick(OrderManager orderManager)
   em OpenRA.Game.Tick(OrderManager orderManager, Viewport viewPort)
   em OpenRA.Game.Run()
   em OpenRA.Program.Run(String[] args)
   em OpenRA.Program.Main(String[] args)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/136867-bib-removal-in-modded-maps-won-t-work-and-crashes-the-game?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6818: Actor type afld: Bogus yaml removals: [RallyPoint, False]
```
Rules:
	AFLD:
		-RallyPoint:
```

results in 

```
Exception of type `System.InvalidOperationException`: No free spawnpoint.
  at OpenRA.Mods.RA.MPStartLocations.ChooseSpawnPoint (OpenRA.World world, System.Collections.Generic.List`1 available, System.Collections.Generic.List`1 taken) [0x000aa] in /home/matthias/Projekte/OpenRA/OpenRA.Mods.RA/MPStartLocations.cs:86 
  at OpenRA.Mods.RA.MPStartLocations.WorldLoaded (OpenRA.World world, OpenRA.Graphics.WorldRenderer wr) [0x000d9] in /home/matthias/Projekte/OpenRA/OpenRA.Mods.RA/MPStartLocations.cs:44 
  at OpenRA.World.LoadComplete (OpenRA.Graphics.WorldRenderer wr) [0x00043] in /home/matthias/Projekte/OpenRA/OpenRA.Game/World.cs:182 
  at OpenRA.Game.StartGame (System.String mapUID, Boolean isShellmap) [0x000b7] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Game.cs:147 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x00443] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Network/UnitOrders.cs:96 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00117] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Network/OrderManager.cs:113 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00007] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Sync.cs:165 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00008] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Sync.cs:173 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x0001b] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Sync.cs:165 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00122] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Game.cs:431 
  at OpenRA.Game.LogicTick () [0x0004e] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Game.cs:476 
  at OpenRA.Game.Loop () [0x000ca] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Game.cs:589 
  at OpenRA.Game.Run () [0x00042] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Game.cs:628 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Support/Program.cs:116 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /home/matthias/Projekte/OpenRA/OpenRA.Game/Support/Program.cs:39
```

Happened during development of https://github.com/OpenRA/OpenRA/pull/6796.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5441177-actor-type-afld-bogus-yaml-removals-rallypoint-false?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7999: MiniYaml unit tests are completely bogus
4 / 5 of the tests are about testing "Inherits:", but that has nothing to do with MiniYaml merging (it is part of ActorInfo).  I will include some proper tests as part of my fix for #2922 and #6818.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11670362-miniyaml-unit-tests-are-completely-bogus?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #2922
Fixes #6818 
Fixes #7999

The existing merge/inherits code was hairy, and mostly bogus.
We will need to be careful about regressions from other code that may be assuming the bogus behaviour.

### CODE REVIEW

**Comment by pchote** [comment]
A side effect of this is that `make test` now detects more types of map rule errors...

**Comment by chrisforbes** [comment]
Need to explain *somewhere* why this is more correct.

I'm not really thrilled with the sense of `throwErrors` being reversed at the same time as changing a pile of other logic, it makes following the actual changes more difficult.

**Comment by pchote** [comment]
The old code removed the requested nodes in MiniYaml.Merge, but then kept the removal nodes in the tree(!) and left it to ActorInfo to ignore them when it parses the traits.  This explodes as soon as you do a second merge, as it tries (and usually fails) to remove the same node a second time.  Oops..

This isn't quite just reversing `throwErrors`, the bool (and MergeLiberal) now has a subtly different meaning: it indicates whether this should be considered as a partial merge, leaving any unresolved removal nodes in the tree for a future merge to deal with.

**Comment by pchote** [comment]
Added support for multiple Includes so that we can further reduce rule duplication.

**Comment by penev92** [comment]
This will call for an overhaul of the other mods' rules. Not only would it in theory enable some long-standing cleanups, the multiple inheritance thing looks good and would be nice to use in all of the mods.

**Comment by chrisforbes** [comment]
:+1:

**Comment by Mailaender** [comment]
I played some test games and can't spot any obvious rule regressions. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d0b14dddcbe79afc120ddc17807490e08824fedf...d8b0bdd262f0dc8f8b636ccbb3f281f70f4cd008)

**Pull request merged**
