### PR TITLE
Make objectives panel visible to spectators/observers

### PR DESCRIPTION
**Pull request by obrakmann**
It also allows switching the context of the panel by selecting a certain player's view in the player view spectator drop down.

### CODE REVIEW

**Comment by Mailaender** [comment]
It looked a bit blant with just the minimap and no text. This definitely improves the situation. :+1:

**Comment by pchote** [comment]
I get a crash when opening the menu as the spectator of a bot-only skirmish.
The exception is pretty horrible, so i'll let you repro it.

**Comment by obrakmann** [comment]
Fixed. A widget in TD's chrome had a wrong name.

**Comment by pchote** [comment]
dbd58b922f6172fcdde0a151c3e76fdde674fc48 expands the stats window to cover the empty space from the hidden objective description.  Can you please include it or something similar here?

**Comment by obrakmann** [comment]
Updated

**Comment by obrakmann** [comment]
Adjusted the d2k chrome as well

**Comment by pchote** [comment]
:+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/eae6b23f80e5a6d7aada8033c440f771370d41fc

**Pull request merged**
