### PR TITLE
Fix aircraft fly endlessly in a circle when ordered to attack inside own...

### LINKED ISSUE #7083: Aircraft fly endlessly in a circle when ordered to attack inside own turning radius
Steps to reproduce:
1. Use either MiG or Yak that's in flight 
2a. Ctrl + Right click on ground really close\* to where the aircraft is flying
2b. Right click on enemy unit that is really close to where the aircraft is flying
*Doesn't have to be the same grid, inside the aircraft's turning raidus seems to be enough.

Both 2a and 2b can be used to reproduce the bug. Expected behavior would be that the aircraft enters an attack run pattern directly, which it does after successfully firing otherwise.  
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6829621-aircraft-fly-endlessly-in-a-circle-when-ordered-to-attack-inside-own-turning-radius?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Gishten**
... turning radius

Fixes #7083 

This fixed is based on the minimum range of the aircraft's weapons and seems to be working quite well. If the target is inside the minimum attack radius of the aircraft, it simply does an extra attack run turn before attacking.

### CODE REVIEW

**Comment by pi99y** [comment]
It looks like it still happens in playtest 20151129.
See replay at ~56% there's my Yak tyring to shoot at AI's artilery on a (north eastern) bridge above my base (violet). I had to move it away first before it could target it.
replay: http://www.filedropper.com/yakcircle

**Comment by abcdefg30** [comment]
Hm, I can't reproduce the issue on latest bleed, but it's clearly noticeable in the replay.

**Comment by pi99y** [comment]
I'll try to reproduce later od different versions and report back. Meanwhile: Do you think this might involve bridges - since bridges had "cursor" issues?

**Comment by pi99y** [comment]
Test #1:
- It's recreateable on playtest 20151129 (but it's tricky)
- It's not the bridges (happens on other terrain too)!
- To recreate (what I figured out so far): You move (standart move, not attack move) your Yak near enemy and click on enemy (which attacks it) just as the yak flies by or possibly during it's turn (which it does when it reaches its destination) - I'm not yet exactly when it's the right time. 

Here are two captures (sorry for poor gif quality, idk why it reduced colors without asking) to get the idea about the angle of attack / movement. It also shows it can happen on different terrain (so it's not the bridges)

https://i.imgur.com/WGyXre3.gif

https://i.imgur.com/NsIOTjK.gif

Right now I don't have time to test it on bleed. But I'll report back when I do. Please try to recreate it on your own too to help me find the exact way to reproduce. Thanks

**Comment by pi99y** [comment]
Reproduced on current (yesterday's) bleed.
You need to get the Yak close to its target with a normal move, wait for it to circle/turn and then directly target the close enemy. It's tricky but it happens.

(Replay + map)
http://www.megafileupload.com/e1ck/yaksCircleAttack.zip
At the end of the replay, just before I placed a beacon to indicate it happening.

**Comment by pi99y** [comment]
Should this get reopened or posted as a new issue?

**Comment by abcdefg30** [comment]
Reopened #7083 for the moment.

**Comment by Gishten** [comment]
I initially thought that I was able to reproduce this on d7f321e04d8c6467865c37a395646c99c9894537 and on current bleed with Soviet 01 using yaks and that there was an issue with the patch, but since the cursor switches from "attackable" to "movable" when a friendly unit is above an enemy, the bug's behavior can be triggered when any friendly aircraft is covering the enemy at the time you think you are giving an attack order, since the aircraft starts circling when having finished a move order. It seems likely that that's what we're seeing in http://i.imgur.com/NsIOTjK.gif

I've spent a couple of hours trying this with Soviet 01 and a custom skirmish map, with bleed and d7f321e04d8c6467865c37a395646c99c9894537 and was able to reproduce it multiple times, but after discovering the cursor issue, I wasn't able to reproduce it in a separate way. 

@pi99y, can you confirm if it's only the cursor that's causing the problems?

**Comment by pi99y** [comment]
Hi @Gishten, sorry for the late response.
I am unable to reproduce the "friendly unit under attack cursor" bug in the current release. It just clears the red attack line a bit early (I feel), but then attacks anyway as it should. 
Also I am unable to reproduce the initial bug, so this is possibly fixed.

**Pull request merged**
