### PR TITLE
Set a fallback default for "Symbols" font

### LINKED ISSUE #15958: Crash when adding InfiniteBuildLimit to a production queue
This is an issue on bleed. Steps to reproduce:
1. Add `InfiniteBuildLimit` to any production queue and set it to `5` for example
2. Start the game and queue more than 5 units on the infinite queue

Here is the exception:
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Widgets.ProductionPaletteWidget.Draw () [0x004f0] in <b580ac0ae42e4ceead9c67d3d54b55df>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00012] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00032] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Widgets.Ui.Draw () [0x00001] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Game.RenderTick () [0x000ba] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Game.Loop () [0x00142] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Game.Run () [0x00042] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <314c493a06a14ad4a2e22c57e31f6733>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in 
<314c493a06a14ad4a2e22c57e31f6733>:0
```
I have tracked this down to:
https://github.com/OpenRA/OpenRA/commit/0fca984463f29fec38bb9d21aea93c520b8ae001#diff-6b8b708073f7d1d3ef01dd77c279c596R147

It crashes because the `Symbols` font (used for the infinity glyph) is not defined by default.

### PR DESCRIPTION
**Pull request by dragunoff**
I've added a testcase that enables infinite build queue for RA baracks. 

Fixes #15958

### CODE REVIEW

**Comment by pchote** [comment]
Mods that want to use the feature can define the font in their yaml. Code changes are unnecessary.

**Comment by dragunoff** [comment]
Yes, mods definitely can do that and modded maps are not likely to use that feature...

But I think that this needs to be documented at least. Because it's frustrating to get a crash like that.

**Comment by matjaeck** [comment]
> But I think that this needs to be documented at least.

Agree, and I couldn't find any documentation about it. If you have the motivation for it, you could ask the KKnD people how they included/defined their font and then create a wiki article about it. This would be a much greater help for modders than any fallback.

**Comment by dragunoff** [comment]
I don't know how kknd does it but adding a definition for the font works:
```
Fonts:
	Symbols:
		Font: common|FreeSans.ttf
		Size: 10
```

**Comment by pchote** [comment]
IMO the better long term fix for this is to draw the infinite symbol as a sprite glyph rather than requiring a new font definition.

**Comment by dragunoff** [comment]
Yes, a sprite would be better. Closing this.

**Pull request closed without merging**
