### PR TITLE
Fix D2k weapons

### LINKED ISSUE #12756: D2K - Almost all weapons are blocked by walls
In original game only Combat Tank and Devastator bullets were blocked by walls and turrets. On our OpenRA D2K mod, Weapons except Turrets, Siege Tank, Missile Tank, Sonic Tank and Deviator are blocked.

Also looks like Devastator has unnecessarily `Blockable: true` on it.

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #12756.
Plus some minor other cleanups.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]

**Review by pchote — APPROVED** [review]
Confirmed that walls in the original game don't block MG or missile fire.  Changes here look good, so :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c1197e2c261d84b4d85f9f3d408107d6e824d31f

**Comment by CH4Code** [comment]
Wow, this change makes trikes even more potent, o.o  Shouldn't this be like in the other mods (only rockets pass walls) ??

**Comment by reaperrr** [comment]
Our goal for D2k is to remake the original as accurately as possible, and Trikes could shoot over walls. It's possible they are now a bit better than in the original because we couldn't figure out how exactly accuracy and area of effect works for warheads in D2k, but other than that, they should be no better than Westwood intended them to be.

**Pull request merged**
