### PR TITLE
BindActorTriggers for APC passengers

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes a part of #16960.

### CODE REVIEW

**Review by pchote — DISMISSED** [review]
Awful, but :+1:

**Comment by tovl** [comment]
Why not make `UnloadPassengers` return the actor list? Like so:

``` diff
 		[ScriptActorPropertyActivity]
 		[Desc("Command transport to unload passengers.")]
-		public void UnloadPassengers(CPos? cell = null, int unloadRange = 5)
+		public Actor[] UnloadPassengers(CPos? cell = null, int unloadRange = 5)
 		{
 			if (cell.HasValue)
 			{
 				var destination = Target.FromCell(Self.World, cell.Value);
 				Self.QueueActivity(new UnloadCargo(Self, destination, WDist.FromCells(unloadRange)));
 			}
 			else
 				Self.QueueActivity(new UnloadCargo(Self, WDist.FromCells(unloadRange)));
+
+			return cargo.Passengers.ToArray();
 		}
```

**Comment by pchote** [comment]
`UnloadCargo` isn't guaranteed to unload everything - there may not be enough space.

**Comment by pchote** [comment]
I just noticed that we have a `Trigger.OnPassengerExited`. We can/should use this to call `BindActorTriggers` on the new actors for both the cargo and paradrop case.

**Comment by pchote** [comment]
Superseded by #16964 - I wanted to make sure we had a fix ready for the new test build I will be spinning today.

**Pull request closed without merging**
