### PR TITLE
Updated Break of Day

### PR DESCRIPTION
**Pull request by Unit158**
Updated at Petrenko's request.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
The difference being?

**Comment by clemty** [comment]
I polished Petrenko's map (so posting this wasn't at Petrenko's request, strictly speaking), then posted it to the IRC channel.

Changes:
- top right quarter was a large empty field with graphical error in the rubbles, I added canyon walls and roads
- concrete walls around the biomed center ended abruptly

gameplay should not be affected by theses changes
before1
after1
before2
after2

**Comment by Unit158** [comment]
Ask him.

**Comment by Mailaender** [comment]
:+1:

**Comment by Mailaender** [comment]
@ihptru Can you upload this one as a new revision at http://resource.openra.net/maps/20/?

**Comment by Mailaender** [comment]
Nevermind, you already uploaded it: http://resource.openra.net/maps/2144

**Comment by Mailaender** [comment]
There are also other Tiberian Dawn maps with a lot of tile errors: https://github.com/OpenRA/OpenRA/issues/6447. I already removed some of them.

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/59c6f0d3395d0d409295c121e67b1db9717ad075%5E...59c6f0d3395d0d409295c121e67b1db9717ad075)

**Pull request merged**
