### PR TITLE
Corrects England's flag.

### LINKED ISSUE #8024: England faction has wrong flag
The flag for the England faction in Red Alert mod is this: 
flag

But this flag is wrong. This is the flag of England: http://en.wikipedia.org/wiki/File:Flag_of_England.svg

The flag shown in game is that of United Kingdom: http://en.wikipedia.org/wiki/File:Flag_of_the_United_Kingdom.svg

So either the flag has to change or the name of the faction.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12082744-england-faction-has-wrong-flag?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by deniz1a**
Fixes #8024.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
I don't think is as universally known or recognizable. It is also bland compared to the existing flags. :-1:

**Comment by deniz1a** [comment]
Well this is the flag of England... And what can we do if their flag is bland? Tell that to the English, maybe they'll change it to a more colorful one.

**Comment by Mailaender** [comment]
In German "England" is colloquial for the whole UK. The redirect http://cnc.wikia.com/wiki/England sounds to me that in the English speaking countries this inaccuracy in everyday language is also common or at least in the C&C games. Also come on, this is a fantasy cold alternate history game. I think you are overdoing it with your correctness here. Also I have to agree with @Phrohdoh: the union jack :gb: is far more recognizable.

**Comment by deniz1a** [comment]
That article is for Britain, not England. And why does England have to have British flag in fantasy cold war game? This isn't part of the Red Alert storyline as far as I know. All the other countries have correct flag. So the only reason is because British flag is more recognizable? Well Westwood or openra chose England as faction... So if recognizability is important, why choose England instead of Britain?

This is like having Bavaria as faction but with German flag...

**Comment by ScottNZ** [comment]
:-1:

**Comment by deniz1a** [comment]
Why?

**Comment by deniz1a** [comment]
ScottNZ, why do you hate England?

**Comment by obrakmann** [comment]
Isn't it enough to go over this in the chat?

Just no. :-1:

**Comment by deniz1a** [comment]
But why?

**Comment by MicroJOo** [comment]
:-1:

**Comment by MustaphaTR** [comment]
:-1: as i said in issue about this, change name not flag.

**Comment by deniz1a** [comment]
So changing faction name to Britain would be accepted?

**Comment by chrisforbes** [comment]
I'd be happy with a name change too.

**Comment by WolfGaming** [comment]
I find this whole thing to be quite unnecessary but the name change (without changing the internal name) would be the most uncontroversial of the options (if we dont include leaving it as is which I find better).

**Comment by deniz1a** [comment]
Also see #8159. So it is not possible to change internal faction name because that would require maps to be ported and there is no tool to do upgrading of lua scripts... And I didn't want to change the display name of the faction if that would be different than the internal one, it would just be confusing.

**Comment by turkeyphant** [comment]
In what world is that more confusing than having the flag of one entity and the name of something different?!

**Pull request closed without merging**
