### PR TITLE
Move blossom trees south one cell on cnc64gdi01.

### PR DESCRIPTION
**Pull request by ghost**
ame_21 46 02

Pretty sure this is a misplaced blossom tree on the TD GDI N64 mission.

### CODE REVIEW

**Comment by GraionDilach** [comment]
https://youtu.be/z-SAWwI4Yts?t=20m45s It was there.

**Comment by r34ch** [comment]
...Maybe misplaced by the original N64 devs? I'll let people decide in that case.

**Comment by pchote** [comment]
Why not shift it south by a cell or two?

**Comment by GraionDilach** [comment]
I favor the shifting it down a cell option as well.

**Comment by r34ch** [comment]
Shifted down one cell and updated commit message.

**Comment by r34ch** [comment]
A more logical edit; thanks @GraionDilach 

(I shouldn't file PRs when tired..)

**Comment by GraionDilach** [comment]
:+1:

**Comment by pchote** [comment]
It looks like all of the tib trees need to move one cell south on that map, not just that one.  Can anyone else confirm?

**Comment by reaperrr** [comment]
> It looks like all of the tib trees need to move one cell south on that map, not just that one. Can anyone else confirm?

Yes. This was caused by my foundation change from 1x2 `_ x` to 1x1 waaay back when I didn't know how to write and run proper upgrade rules.

There might be a few newer maps where this is already corrected, though, so we need to be careful about which maps to update.

**Comment by r34ch** [comment]
All blossom trees have been moved south one cell.

**Comment by obrakmann** [comment]
When looking at the map in the editor, the shifted locations become really apparent. :+1:

**Comment by Mailaender** [comment]
Looks like you forgot to setup your e-Mail address in your git client or you are using a different one on your GitHub account which causes the commits to not match.

**Comment by pchote** [comment]
Looks fine to me, too.  We talked in IRC about how to associate additional emails with @r34ch's github account.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/8bd549cc625b82cedfd62f0b66596b8b83e553a2

**Pull request merged**
