### PR TITLE
Re-instate owner row for oil pumps and tech buildings in TD

### LINKED ISSUE #11219: Player owned Oil Derricks nameless. (TD)
A player owning an oil derrick in TD does not show who owns the oil derrick. It simply just has the name "Oil Derrick" on it. Yet the color shows the owner of the structure.

(Unsure if this is a bug or intentional.)

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #11219.

### CODE REVIEW

**Comment by reaperrr** [comment]
:+1:

**Comment by abcdefg30** [comment]
Now the oil derricks in the campaign missions (e.g. `Sudanese Prison Break (a)`) have an owner row again.

**Comment by pchote** [comment]
The behaviour of Sudanese Prison Break (a) looks correct to me.  Derricks owned by the neutral player don't have the owner row, and those captured by the enemy or player do.

**Comment by abcdefg30** [comment]
But we don't show an owner row for all other actors owned by the enemy or player in missions.
Imho it would be very inconsistent to show it for oil derricks / tech buildings but not for other actors.

**Comment by pchote** [comment]
Ah, now I get you.  It sounds like we're missing a GenericTooltip (or whatever we call it) mission override for the tech buildings.

**Comment by obrakmann** [comment]
Updated.

**Comment by reaperrr** [comment]
My +1 still stands.

**Comment by pchote** [comment]
Looks good to me :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/980334dffc216461a6698357ad248044f6d4f24a

**Comment by HenrytheSlav** [comment]
:+1:, pchote is 2fast4me

**Pull request merged**
