### PR TITLE
Fix infantry death animations

### LINKED ISSUE #15244: Incorrect infantry death animations
RA: The civilians (c1,c2,c3,einstein,delphi,chan) use the wrong death animations for deathtype 4 & 5. For (c1,c2,c3) the die4 should be 168(explode_large), die5 should be 180(burn). For (einstein,delphi,chan) the die4 should be 135(explode_large), die5 should be 147(burn).
->civilians are currently exploding from flame & burning from ballistics
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/sequences/infantry.yaml#L1005-L1291

RA: Infantry use the ripped-apart animation for deathtype bulletdeath. This animation should only be applied to HeavyMG while the correct DefaultDeath should be applied to LightMG. Currently the only weapons using DefaultDeath are the flak/claw/mandible/ATMine.
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/smallcaliber.yaml

TD: There is no death sound for RippedApartDeath. RippedApart is currently only used for dinos... This deathtype should be used for HeavyMG.
https://github.com/OpenRA/OpenRA/blob/bleed/mods/cnc/rules/defaults.yaml#L345-L453

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #15244.
In addition to what @FrameLimiter listed, I also changed the mandible and ATMine animations.

### CODE REVIEW

**Review by GraionDilach — DISMISSED** [review]
:+1:

**Comment by reaperrr** [comment]
https://github.com/Smittytron/OpenRA/blob/36491191c894f6f80cb0242132870738796c781e/mods/cnc/weapons/smallcaliber.yaml#L73 should become RippedApartDeath too, then.

👍 after that.

**Comment by Smittytron** [comment]
Updated

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bad4bc908232956d723e37eba106c763632ecc2e...2c7935a0e0a861a04533d9d210d530260cfde069)

**Pull request merged**
