### PR TITLE
Reduce lag spikes from SquadManagerBotModule.

### LINKED ISSUE #18825: Make 'squadmanager' does not tick squads all in one tick
## Motivation
`SquadManagerBotModule` ticks all squads in one tick after every `AttackForceInterval`, but squad logic can include some heavy performance cost lines, such as scanning enemy from all actors, scanning the entire map and using some function in 'AttackOrFleeFuzzy' in a loop. More squads AI have, more possibilities of spikelag after each `AttackForceInterval`. It will be also a important thing needs putting into consideration when we refactoring the `SquadManagerBotModule`.

## Proposed solution
`SquadManagerBotModule` tick 1~2 squad each tick and remember the index/key of the ticked squad, which will refreshed after `AttackForceInterval`.

## Side effects
Need to solve an edge case that refresh index/key of the ticked squad after `AttackForceInterval` but squads are not all ticked.

## Alternatives
Make squad logic very simple.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Updating squads is the most expensive part of SquadManagerBotModule. It involves ticking the current squad state. This usually involves finding nearby enemies and evaluating the fuzzy state machine to decide whether to interact with those enemies. Since all the AI squads for a player get ordered on the same tick, this can result in a lag spike.

To reduce the impact, we'll spread out the updates over multiple ticks. This means overall all the AI squads will still be refreshed every interval, but it'll be a rolling update rather than all at once. By spreading out the updates we avoid a lag spike from the cumulative updates of all the squads. Now the lag spike is reduced to the worst any single squad update can incur.

Fixes #18825

### CODE REVIEW

**Comment by anvilvapre** [comment]
It can do not harm if at the next tick the AI comes up with either the same or different orders? Causing some sort of effect that orders are executed multiple times possibly with strange side effects.

**Comment by RoosterDragon** [comment]
The goal of the squad update is to assess the situation and issue orders. Those orders will change over time, but that's what we want it to do. For example, maybe an AI squad decides to attack some nearby enemies. Then at the next update interval it will check again whether it wants to attack the nearby enemies. If the situation is still the same, then it will choose to attack as it did before. But if the situation has changed, it might decide on something else. e.g. if more enemies have turned up nearby, it might decide to flee instead because of the greater enemy numbers.

None of this logic is affected by this PR as such, this is just what the SquadManagerBotModule is designed to do.

**Review by PunkPun — APPROVED** [review]
LGTM

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6f8a071f3f07ebd2d5b94969ed87a0b2fab2cae7...1193cb5d52085d621dc9096df9627658396f0646)

**Pull request merged**
