### PR TITLE
fix mapping errors in shipped maps

### LINKED ISSUE #7973: Some desert maps use temperat trees.
This is probably the correct behavior, but it is markedly different from earlier versions of openra
screenshot is from Tiberium Oasis, included in the latest playtest

trees

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11445689-some-desert-maps-use-temperat-trees?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by clemty**
this fixes mapping errors in:
- chokepoint (TD) (temperat trees in desert scenario)
- haos ridges (TD)
- the hot box (TD) (temperat trees in desert scenario)
- instant karma (TD) (temperat trees in desert scenario)
- into the river below (TD) (also some cosmetic changes to the lake)
- intervention (RA)

I've marked the problematic areas:
- http://imgur.com/a/9fpx3 (TD)
- http://imgur.com/LlZXZAb (RA)

edit: I can provide "after" screenshots if needed

Closes https://github.com/OpenRA/OpenRA/issues/7973

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by abcdefg30** [comment]
It seems like you placed a tree in the river in "into the river below":
rivertree

And this tree looks also a bit off to me ("haos ridges"):
clifftree

**Comment by abcdefg30** [comment]
Looks good to me otherwise.

**Comment by clemty** [comment]
"into the river below"
I placed these trees there to hide an ugly transition between the river tiles - I've redone the river now (as a result the island is now slightly larger)
another change I made is that there are now a lot more decorative elements all over the map (snow debris), but this should not change gameplay

"haos ridges"
I didn't change them when I worked on it since it looked believable that trees grow that far to the edge of a cliff - but I've replaced them now with smaller trees

**Comment by abcdefg30** [comment]
Sorry, found another tree in the water. :(
rivertree2

But I think we can merge this after above is fixed. :+1: / :white_check_mark:

**Comment by clemty** [comment]
should be ok now

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/94cc51ac627b5aaa69a295a9c9089320b3c8e9c4...92164ae9edd13e71dbed6dffd950b530b3c03932)

**Pull request merged**
