### PR TITLE
Suppress scroll events from the DropDownWidget fullscreen mask.

### LINKED ISSUE #13920: "Disconnected" dropdowns
Release-20170527.
It works with any dropdown (team, faction, ...).
To reproduce : click on the arrow to show the dropdown, move your cursor away and play with the wheel.
(Glitches from Fraps, not OpenRA)

dropdowns

### PR DESCRIPTION
**Pull request by pchote**
Fixes #13920.

### CODE REVIEW

**Review by rob-v — APPROVED** [review]
👍

**Comment by reaperrr** [comment]
@pchote Since we still have 2-3 days, should this possibly go into stable (before the playtest)?

**Comment by pchote** [comment]
Yeah, I guess that makes sense.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
a293e16

https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6d13863093396f70c3c4a4b4231b68bd86083633...0ae57b65c8f2286550de54f54b780e338dba6416

**Pull request merged**
