### PR TITLE
Updated Windows SDL2 to version 2.0.5

### PR DESCRIPTION
**Pull request by Mailaender**
See https://forums.libsdl.org/viewtopic.php?t=12160 for the changelog.

I noticed several SDL related bugs being reported such as https://github.com/OpenRA/OpenRA/issues/6341 and https://github.com/OpenRA/OpenRA/issues/10172 which should be tested against the new version and otherwise reports towards upstream SDL2 should be filed.

https://github.com/OpenRA/OpenRA/pull/12501 might be affected by this.

### CODE REVIEW

**Comment by pchote** [comment]
The changes from 2.0.4 &rarr; 2.0.5 don't appear to touch anything we use (except maybe `SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING`), so this is unlikely to affect #12501.

**Comment by pchote** [comment]
Pinging @abcdefg30, @cjshmyr, or any other windows-user who can test this...

**Comment by reaperrr** [comment]
I haven't been able to reproduce any issues with cursor, fullscreen or alt-tabbing on either SDL version (W7x64). I guess updating won't hurt 👍 , but I can't tell if this fixes the SDL-related bugs others have run into.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/98af728381931d4200456d8b31760ae594ae73a9...3ebd244f74bfa066c524b6cc54374c503c218ae7)

**Pull request merged**
