### PR TITLE
Adds ships to the MECH's autotarget priority list

### PR DESCRIPTION
**Pull request by ghost**
The mechanic was not automatically targeting & repairing damaged ships.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]
Ok, it looks a bit weird though when they repair submerged subs. 😄

**Comment by pchote** [comment]
IMO it doesn't make sense to be able to repair submerged subs.

**Comment by Smittytron** [comment]
Can you squash commits?

**Comment by FrameLimiter** [comment]
@Smittytron - Not AFAIK using the github web interface.

**Comment by Smittytron** [comment]
I've got my noob cheat-sheet of git commands if you're up for making the switch.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
@FrameLimiter Squashed them for you to get it merged, but in the longer run I agree with @Smittytron that using git locally - regardless of UI or command line - would have advantages, mostly to squash or edit commits.

[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/2b8d8a5d8f4fa6303d315104045d4de8f9abcefd...21715857987d77d2c1b0568af067863a1a1b171a)

**Pull request merged**
