### PR TITLE
[RA] Added Huey Gunship as replacer for Hind

### PR DESCRIPTION
**Pull request by ghost**
Related to:
https://github.com/OpenRA/OpenRA/issues/12810
https://github.com/OpenRA/OpenRA/issues/12197#issuecomment-281485039
https://github.com/OpenRA/OpenRA/pull/12831

gunship-cameo

ingame

huey-idle-hover-circel-preview

huey-gunfire-circel-preview

- Completely custom shp matching the standard of other Westwood's vehicles.
- Complete replacement of Hind rules
- Better than token edits to the Hind, even without it's stub wings, the Hind is still a Hind. 
- Small version of rotor used. Images feature the large one.

### CODE REVIEW

**Comment by GraionDilach** [comment]
The cameo is completely wrong.

**Comment by SamKeightley** [comment]
Hinds are being replaced by Yaks and you're just nitpicking:P

**Comment by pchote** [comment]
#12831 is more in line with OpenRA's philosopy of repurposing original game units/assets for rebalanced roles (e.g. RA thief -> hijacker, TD SSM Launcher -> Mobile SAM), and only adding completely new things as an absolute last resort.

**Comment by GraionDilach** [comment]
Drama King, you're not funny. The fact that you made a cameo from a random image (is the source in public domain? - we had this issue with the Flak Truck cameo before) using SHP Builder's Cameo Generator using the RA2 settings - there's even a RA1 template there, which is actually faulty since taht still uses the RA2 font instead of the thinner RA1 one - makes your nitpicking regarding SoScared's art edit completely void.

The cameo is ultralow quality and doesn't blend with the others at all. Same reason why the RA2-akin spy chevrons were thrown out in favor of the upscaled simple chevrons during the infiltration-veterancy playtest cycle.

**Comment by SamKeightley** [comment]
Sounds like a cop out to me but it's your call. I was happy to make it regardless and now it will become a public asset. The process has been quite helpful anyway for future mod work so that is a plus. Shame this wont be included in RA though as the alternative is inferior. 

Keep talking Graion, no one takes you seriously, even back in the day when you where a scrub on PPM:P

**Comment by GraionDilach** [comment]
This still uses a wrong font and no cameo uses plainblack text bar. Also the image lacks contrast and sky details.

At this point, I'd even suggest mishmashing this art with SoScared's cameo.

**Comment by FiveAces** [comment]
I see a handful of problems with this pull request:

-The camo looks really low-quality and doesn't fit with the tone of camos in vanilla RA; plus, it's extremely blurry.

-The unit is visually too similar to the Longbow; this might sow some confusion in hectic games.

-The name "Gunship" is too generic. Now I'm fully aware that most vehicles and units had generic names, but the air units have historically been a noteworthy exception. I'd much rather prefer "Cobra" or even "Huey" despite the latter being hard to pronounce for non-native English speakers.

**Comment by SamKeightley** [comment]
I agree with all of your points there Five aces. I woke up this morning and realised that Huey was a much better name to be calling it than Gunship which is rather generic and applies to all attach helicopters. 

As for the identification issues, I have created a 2 bladed rotor animation that makes it stand out much better against the Longbow. 

The Cameo has been updated. The first one was atrocious and I only really spent like 20 mins on it just to get the PR started. I have spent most of the day working on one which not only looks good, but fits in with the Westwood cameos nicely.

ingame-toolbar-final-cameo

**Comment by GraionDilach** [comment]
Still the wrong font - http://nyerguds.arsaneus-design.com/cnc95upd/cc95p106/language/icon_alphabet.png.

**Comment by MustaphaTR** [comment]
That's SHP builder's fault tho. It uses RA2 font even on RA1 cameo style. You need to fix it manually.

**Comment by SamKeightley** [comment]
I'll fix that up. Here's a preview of the two bladed anim, only a quarter float chcyle is shown hence you it's jumpy, but it shows the rotor anim well.

ingame-twoblade-short-anim

**Comment by SamKeightley** [comment]
Updated font, it now uses the correct one. I was skeptical about readability at first but it actually turned out well. 

I also realised that Huey is the slang name for this helicopter, and the official one is "Iroquois". Using this name conforms to a semi implemented naming convention as Chinook is used. If you rename the Longbow to Apache you'll have all their official and American Indian names:P

The shading has also been darkened by 10% to better match the other cameos it's surrounded by. 

huey cameo

**Comment by GraionDilach** [comment]
I believe the text would've fit with the wide font as well, wouldn't it?

**Comment by SamKeightley** [comment]
huey cameo

This will hopefully end all the discrepancies with the font. Got confused as the larger font looks exatcly like the RA2 font so thought the smaller font was used throughout. It was only when I compared it with other unit cameos that I realised my error.

**Comment by GraionDilach** [comment]
RA1 font is generally wider than RA2's however, this is most noticable on the E IMO. Font looks fine now.

**Comment by SamKeightley** [comment]
I think so too. 

I've tweaked it further by adjusting the sharpness. It was slightly blurry before which made it stand out a tad against the others. Now it's just right. 

huey cameo

ingame-toolbar-final-cameo

**Comment by pchote** [comment]
The tone of the discussions around the hind/cobra/huey topic across Github/forums/IRC has been downright disgusting, and at this point it seems clear that merging *any* of these changes will only continue the toxic drama.

The Allied Hind will have to stay.

**Pull request closed without merging**
