### PR TITLE
Fix multi-line tooltip padding.

### LINKED ISSUE #9986: Map editor tooltip margins are incorrect
The margins of the tooltip type introduced by #9925 have at least three problem cases:

1. The top/bottom margins are wrong for all mods.
2. The margin between lines are wrong for all mods.
3. Leading / trailing newlines are not stripped, allowing empty rows.

screen shot 2015-11-11 at 23 11 08
screen shot 2015-11-11 at 23 10 43
screen shot 2015-11-11 at 23 14 36
screen shot 2015-11-11 at 23 13 25

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28245052-map-editor-tooltip-margins-are-incorrect?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9986.

### CODE REVIEW

**Comment by obrakmann** [comment]
The padding at the top looks wrong to me:
screenshot from 2016-03-13 15 05 46

For some items in the build palette, there's a huge empty space at the bottom:
screenshot from 2016-03-13 15 05 17

**Comment by pchote** [comment]
Those use the `BUTTON_TOOLTIP` and `PRODUCTION_TOOLTIP`, neither of which are touched by this pr!

**Comment by obrakmann** [comment]
:+1: then

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/51fb5a54d41f062f1d92a1f6f880a791a00e7a30)

**Pull request merged**
