### PR TITLE
Map editor tiles filters

### PR DESCRIPTION
**Pull request by rob-v**
Closes #15888
1. move some common logic to CommonSelectorLogic
2. add Category multiple selection for tiles like for actors

### CODE REVIEW

**Comment by pchote** [comment]
Stylecop reports:
```
OpenRA.Mods.Common/Widgets/Logic/Editor/TileSelectorLogic.cs(91,8): error CS0219: Warning as Error: The variable `categorySelector' is assigned but its value is never used
```

**Comment by rob-v** [comment]
I moved widget init into GetCategorySelector function to be reused by ActorSelectorLogic and TileSelectorLogic. Not sure how to handle this 'false' report. 
var categorySelector = GetCategorySelector(searchTextField, panel);
So the variable isn't used further in the code but I need it to live.

**Comment by rob-v** [comment]
Fixed. The update for tile multi selection could be simpler to do and review if preferred without moving common code to new class.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
This goes well with the other editor improvements, so lets get this in for the playtest.

**Review by Smittytron — APPROVED** [review]
Looks good

**Pull request merged**
