### PR TITLE
Added original D2k debris

### PR DESCRIPTION
**Pull request by reaperrr**
...and removed our Shrapnel weapon.

Additionally made first step towards splitting weapons.yaml.

### CODE REVIEW

**Comment by penev92** [comment]
This seems like quite the overkill ingame. You should perhaps lower the amount of pieces.
Also it feels like they fly somewhat slower than they should. Not sure what to do about that.

**Comment by reaperrr** [comment]
Original d2k *was* overkill in terms of spawning debris, though. But yeah, I guess it should be tweaked more to match the individual structures' size.

**Comment by penev92** [comment]
Well you may be right - https://www.youtube.com/watch?v=6aOen-y6K1g&feature=youtu.be&t=600
But they definitely go away faster, and don't appear to fly that far.

**Comment by LavenderMoon** [comment]
Debris are implemented as `Bullet`s and could be made to do the same in OpenRA without any additional C# code, right? (Bare with me, I'm still getting used to this codebase.)

**Comment by reaperrr** [comment]
Updated, reduced the range and slightly increased max speed.

@LavenderMoon Yes, that can be done entirely in yaml.

**Comment by GraionDilach** [comment]
Is there a reason why the first debris doesn't have trail?

**Comment by penev92** [comment]
They still feel a bit slow, but I guess it's nothing to cry over, so :+1:

**Comment by Mailaender** [comment]
On normal game speed this feels like playing on a low/no gravity and the debris is also very deadly to infantry on direct hit, but I assume this is the original balancing which will be improved later on. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7f3c87ae1c762704615c86e843cf4672db4dbae4...01097bc17f82b5d5a296374bf935281a071d317b)

**Pull request merged**
