### PR TITLE
Fix singleplayer game latency.

### LINKED ISSUE #9817: Restore OrderDelay = 1 for missions/skirmish
Before the refactorings related to gamespeed, singleplayer games were always set to an order delay of 1. This is no longer the case, and particularly on 'fastest', the delay is very noticable when navigating the UI.

It would be nice if we could restore the old "force order delay to 1 when it's a singleplayer game, regardless of game speed" behavior.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27853410-restore-orderdelay-1-for-missions-skirmish?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9817.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
This makes sense. :+1:

**Comment by abcdefg30** [comment]
```OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:L698: [SP2000] Invalid spacing at the end of the line.

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/54cb033786750eacfc9593e57dc56752c31ab069...1871c2a2e1450e1098d1e872fc93292c47571efa)

**Pull request merged**
