### PR TITLE
Fix bad behavor while pinging Clients

### LINKED ISSUE #6941: NRE in player pinger code
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Server.PlayerPinger.Tick (OpenRA.Server.Server server) [0x000a9] in /home/ubuntu/OpenRA/OpenRA.Mods.Common/ServerTraits/PlayerPinger.cs:44
  at OpenRA.Server.Server.<Server>m__0 (System.Object _) [0x001ff] in /home/ubuntu/OpenRA/OpenRA.Game/Server/Server.cs:184
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
```
Crashes my dedicated server. Appears in the current release.

$10 says GetClient(c) is returning null at line 44 of PlayerPinger.cs
```
server.SendMessage(server.GetClient(c).Name + " is experiencing connection problems.");
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/5968442-nre-in-player-pinger-code?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LipkeGu**
fixes #6941

### CODE REVIEW

**Comment by LipkeGu** [comment]
Travis error ...

**Comment by Mailaender** [comment]
I filed https://github.com/OpenRA/OpenRA/pull/7235 to finally get rid of those.

**Comment by LipkeGu** [comment]
again ...

**Comment by Mailaender** [comment]
I just merged #7235 without waiting for additional +2 so you may want to rebase to test it.

**Comment by LipkeGu** [comment]
updated & rebased :)

**Comment by Phrohdoh** [comment]
Let's not violate the +2 rule.

**Comment by Mailaender** [comment]
Tested the timeout again by halting a second client with the IDE pause button:

image

Also no regressions in regular games. :+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/df69139ce69523152095a72bd79ef36e77a54f02...3a6045375f95caa5de46cd2977872eabc9c787a4)

**Comment by LipkeGu** [comment]
neue bitmap

the fix works... in fact!

**Pull request merged**
