### PR TITLE
Prevent resources from spawning on ramps.

### PR DESCRIPTION
**Pull request by pchote**
For TS/RA2 compatibility.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
:+1:

**Comment by OmegaBolt** [comment]
Well... in TS Tiberium and even Veins IIRC could grow on ramps. They couldn't start on ramps because TS crashed but they did grow on them. Doesn't happen in RA2 at all though.

**Comment by pchote** [comment]
@OmegaBolt: Do you have a screenshot showing that?  TS doesn't include any artwork for tib/veins on slopes, so I imagine it looks rather bad.

**Comment by Ten-Tacles** [comment]
vein on slope
tiberium on slope

Vein and Tiberium can spread to slopes, but it's slow, and they don't spread further than 1 slope.
I helped with cyborgs, but the tiberium below the reaper happened natural.

**Comment by pchote** [comment]
Veins include specific artwork for slopes, so we will be able to define `AllowOnRamps: true` and adjust the renderer to use the correct artwork when we get around to implementing them.

**Comment by OmegaBolt** [comment]
It cannot spread on those corner slopes but it does on straight slopes.

**Comment by Mailaender** [comment]
I am okay with disabling the growth to prevent glitches for now. :+1:

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4dcca57c57eb057eaa3c54bc410c39405266e598...9076970eec9e439a7b1039ee3cb2fd8c35683735)

**Pull request merged**
