### PR TITLE
Change Subs to use the Defend stance by default

### PR DESCRIPTION
**Pull request by abcdefg30**
This has been asked for several times already. As is you have to change the Subs stance, otherwise you will lose them when not paying constant attention since other naval units will just pick them off when attack moving.

### CODE REVIEW

**Comment by abcdefg30** [comment]
We also might want to think about making the AI stance to `AttackAnything` by default. Missions already define overrides to do that.

**Comment by deleted-user-1** [comment]
:+1: to the changing the default stance to `Defend` but is it expected that subs will autotarget enemy shipyards / sub pens (shouldn't they only do in when in `AttackAnything` stance?

**Comment by abcdefg30** [comment]
I'll fix that and make the AI use `AttackAnything` then.

**Comment by KOYK** [comment]
Finally!

**Comment by abcdefg30** [comment]
Updated.

**Review by Smittytron — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/40dbc851bb1fad21eb2b3c08d30e3bda120cd7fe...33278e30ffc3955e60b9ce1f1cdd0c6762a96955

**Pull request merged**
