### PR TITLE
Added 3 new maps from PizzaAtomica

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/8970.

### CODE REVIEW

**Comment by abcdefg30** [comment]
:+1:

**Comment by MicroJOo** [comment]
:+1: works , ty for your time @Mailaender

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/14b0fad871208a5440e52b89d7fb9fbb16147a7b...ac7641585386a21d36f131810c41bef04f0b97cd)

**Comment by TheRaffy** [comment]
He deserved it! He's one of the best mappers .

**Pull request merged**
