### PR TITLE
Fixed missing dispose on stream in LegacyMapImporter

### PR DESCRIPTION
**Pull request by Mailaender**
Similiar to https://github.com/OpenRA/OpenRA/pull/8251.

### CODE REVIEW

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8252/files?w=1 makes the diff readable.

**Comment by Phrohdoh** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/947fead5b37fab91fdee1ec3cd6417021251b02f%5E...947fead5b37fab91fdee1ec3cd6417021251b02f)

**Pull request merged**
