### PR TITLE
Enable ExploredMap by default

### PR DESCRIPTION
**Pull request by MustaphaTR**
Just opening a PR after the discussions on Discord.

### CODE REVIEW

**Comment by pchote** [comment]
As per the discussion in #11531 :-1: to enabling explored map by default before #3654 and #5908 are fixed.  Shipping a default configuration that has two very obvious graphical (and some would argue cheaty) bugs is bad form.

**Comment by penev92** [comment]
👎 as said on Discord.

**Comment by abcdefg30** [comment]
\<What the posts above say.>

**Comment by FRenzy-OpenRA** [comment]
Rewriting some arguments in favour of it, from Discord : 
- Most games (casual or not) are played in "Explored" anyway
- (In RA at least), the trick is not used (minimap comes late)

**Comment by penev92** [comment]
I don't know, Bob... we already have -3 votes.
Well, I'm sure the fans are going to hate us, but sounds like closing time.

**Comment by GraionDilach** [comment]
I have numerously explained this on the Discord already. :-1: ofcourse.

**Comment by abcdefg30** [comment]
Sorry, looks like we are not getting anywhere here...
This might have a chance of getting resurrected *once* the "blockers" are resolved.

**Comment by GraionDilach** [comment]
It's a duplicate of #11531 on the milestone though.

**Pull request closed without merging**
