### PR TITLE
Replaced Chocolatey with more reliable alternatives

### PR DESCRIPTION
**Pull request by Mailaender**
TIL that NSIS is already pre-installed http://www.appveyor.com/docs/installed-software#tools and there is an API to render GFM using https://developer.github.com/v3/markdown/ getting rid of @chocolatey so we will hopefully get a more reliable Windows CI post compile.

### CODE REVIEW

**Comment by abcdefg30** [comment]
👍 once `ConvertFrom-Markdown.ps1` is (visually) cleaned up.

**Comment by Mailaender** [comment]
"visually" cleaned?

**Comment by abcdefg30** [comment]
Ah well, never mind.

**Comment by Mailaender** [comment]
Updated with 2365fbdabe1f72d83b22919ebfbecfe80b7a64cf.

**Comment by obrakmann** [comment]
:+1:

**Pull request merged**
