### PR TITLE
Updated the utility

### PR DESCRIPTION
**Pull request by suvjunmd**
Modified the commands layout to be more readable and applied some refactorings to the code.

Before:

After:

### CODE REVIEW

**Comment by Mailaender** [comment]
Thanks for the cleanup. :+1:

**Comment by suvjunmd** [comment]
Replaced spaces with tabs

**Comment by obrakmann** [comment]
This makes a world of a difference regarding readability. Code looks sane, too. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/81ac059880d5aaadeffef8c9b30315156b2bf630%5E...81ac059880d5aaadeffef8c9b30315156b2bf630)

**Pull request merged**
