### PR TITLE
Create singletons for AttackOrFleeFuzzy rulesets

### PR DESCRIPTION
**Pull request by RoosterDragon**
This avoids the cost of recreating the engines and rules for every AI and AI squad.

For a 200% speed replay with a 4 AI FFA on Tournament Island, RA, this saves 1.55% in total CPU used.

### CODE REVIEW

**Comment by Mailaender** [comment]
No negative side effects in a bot battle with multiple AI types. :white_check_mark:

**Comment by jtyle6** [comment]
look's good, I was getting around 40% to 60% Cpu.
The navel ai get's owned early in game by rush ai.
 
[OpenRA-2016-02-13T142216Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/129188/OpenRA-2016-02-13T142216Z.orarep.zip)

**Comment by obrakmann** [comment]
The AI is as awful as ever, so I guess it works :p :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/pull/10728)

**Comment by Mailaender** [comment]
Coverity detected data race conditions. Not sure how serious the issue is: https://scan8.coverity.com/reports.htm#v24414/p10888/fileInstanceId=10683098&defectInstanceId=3772629&mergedDefectId=135614&fileStart=251&fileEnd=277

**Pull request merged**
