### PR TITLE
Send additional mod metadata in master server game advertisements

### PR DESCRIPTION
**Pull request by pchote**
This PR sends three new fields to the master server:
* `ModTitle` includes the mod's human readable title.
* `ModWebsite` includes the mod's website URL (new mod.yaml field).
* `ModIcon32` includes a URL to a web-hosted version of the mod's icon  (new mod.yaml field, `WebIcon32`, should match icon.png).

The `ModTitle` is used as the primary source of the mod name in the server list, and so fixes the "Unknown mod (id)"'s in the server list (for mods that have been updated to include this PR).

The other fields will be used in the web server listings, and I plan a future PR (probably not this cycle) to use them in a dialog similar to the mod-switch dialog when double clicking on a server for a mod that isn't installed and/or mod header tooltip.

Depends on https://github.com/OpenRA/OpenRAMasterServer/pull/56 (already merged).
Depends on https://github.com/OpenRA/OpenRAWeb/pull/383 - the master server will complain about missing icons, but still accept the rest of the data.

### CODE REVIEW

**Comment by GraionDilach** [comment]
>ModIcon32 includes the mod's website URL (new mod.yaml field, WebIcon32, should match icon.png).

C'N'P error in the initial post?

**Comment by pchote** [comment]
Fixed initial post.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/282ff19cd095a3c4b39dca49384e495b0b21bd4e...209e060c5eb977976ab7273f8ea711771481c78f

**Pull request merged**
