### PR TITLE
Fixed the initial turret preview facing

### PR DESCRIPTION
**Pull request by Mailaender**
Split from https://github.com/OpenRA/OpenRA/pull/4496 as this is useful elsewhere.

### CODE REVIEW

**Comment by penev92** [comment]
Can you please point me to how I can test this ingame?

**Comment by Mailaender** [comment]
This is only used for the ingame map editor.

**Comment by Phrohdoh** [comment]
>as this is useful elsewhere

**Comment by Mailaender** [comment]
@pchote upcoming `WithCargo` changes and the planned ingame encyclopedia #3788 will benefit.

**Comment by penev92** [comment]
OK, but what's the point of having it in the map editor if you can't use it in-game?
I assume that the idea is to create maps with actors placed (and probably custom rules), where you can set the initial turret facing of actors to a direction of your choosing, so they start like this when you start the mission?

**Comment by Mailaender** [comment]
This only fixes visual glitches in the actor palette and placement preview. It does not introduce initial turret facings, but respects the existing init dictionary values for previews.

**Comment by Mailaender** [comment]
Closing as you seem to be unable to review it without a use-case and no one else is interested.

**Pull request closed without merging**
