### PR TITLE
Fix crate spawned actors not crushing crushable actors and spawning inside other actors.

### PR DESCRIPTION
**Pull request by PunkPun**
I fix it by pushing cell selection logic into end world task, and by calling SetPosition after the actor was spawned

### CODE REVIEW

**Comment by anvilvapre** [comment]
> I fix it by pushing cell selection logic into end world task

Side question. This seems like a fix for more and more things. Which makes sense. But if so much tasks become frame end tasks, being executed after a logic tick, won't you have the frame end tasks competing as well.

**Comment by PunkPun** [comment]
I don't think so. End frame tasks are mostly there to handle object creation as to avoid modified collection during enumeration crashes. And as it seems much of the older code processes creations checks at the wrong time. It's not unlikely that some major refactor screwed a lot of code up.

Fwiw I've also seen end frame tasks used for multithreading.

**Comment by abcdefg30** [comment]
Does that mean we can just put the `SetPosition` part into the frame end task?

**Comment by PunkPun** [comment]
I'm not sure what exactly you mean. But I don't really see a reason why we can't put SetPosition there.

**Comment by abcdefg30** [comment]
I was asking if we can just put the SetPosition stuff inside the task and leave the rest outside.

**Comment by PunkPun** [comment]
No, then none of the bogus behavior would be fixed

**Review by Mailaender — DISMISSED** [review]

**Comment by PunkPun** [comment]
rebased

**Comment by Mailaender** [comment]
Can you remove the test case?

**Comment by PunkPun** [comment]
removed

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/40e47d4924f93b95645db9df1e11c240d89d2356...e660fe57eca40a06b7ef4fde65b95cf873d787c7)

**Pull request merged**
