### PR TITLE
Set explored map as the default lobby option for all mods

### PR DESCRIPTION
**Pull request by ghost**
This seems to be how the majority of players in TD and recently [RA](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19611) wish to play on-line. Aside from the points raised about helping new players, I have found this actually removes _a lot_ of frustration out of playing early game in general, so I just set it for all mods.
- Eliminates units refusing to move if you click on impassable terrain under the shroud. Also eliminates having to shift click spam a black screen to get around this. 
- If playing random spawns, you no longer have to pan the screen in four different directions to figure out where the map border is (and hence your spawn position)
- No more memorizing a map for REF placement, tech buildings, debris / ore in the spawn blocking building placement etc. No more shift click spamming scouts just to uncover the map - now you can focus on scouting the enemy and countering their scouts.
- No longer at a disadvantage on new maps so you can focus on just playing. Much less frustrating to try different tactics like changing your initial MCV deployment and rushes.

### CODE REVIEW

**Comment by pchote** [comment]
:+1: to the idea, but we should make fixing #5908 a priority (I'm tempted to say a prerequisite) if we take this.

**Comment by HenrytheSlav** [comment]
^Basically what Paul says, the minimap really bothers me. Recently I was able to expect ambush from behind only because I saw ore being eaten elsewhere than expected. Otherwise probably good idea, I am jsut worried that over time people will forget about using shroud altogether, and that would be sad imho. It still is fun thing to have, combined with GPS loss etc.

**Comment by Micr0Bit** [comment]
:-1: 

oh and btw. entering a RadarDome with a Spy will have no effect ... theres also the "exploration crates" settiing back shroud , or revealing it , that might need a different effect instead ...so you guys might consider fixing that too ... since we are talking about changing something to default those things should still have effect even when shroud is off

i have nothing more to say here , other then 

@pchote : the only applause you will earn here , comes from a temporary community and 2014-16 rookies ... and changing rules by having a crowd of newbies (in terms of invested openra-time) that add momentum to your ideas , although you personally are hardly effected by them ... won't make you happy in the future

**Comment by pchote** [comment]
@Micr0Bit the community vote at http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19611 is overwhelmingly in favour of enabling it by default.  If the "hardcore" player base wants their voice heard on this matter then they need to actually participate in the discussion.

**Comment by Micr0Bit** [comment]
@pchote : most of the "overwhelmingly" votes for "yes please" could be also just multi-accounts ... 

and beside that , the poll had really bad voting-options at the beginning (before you changed it) ... and earned a good amount of "yes-please" voters that way ...

**Comment by Micr0Bit** [comment]
you should consider fixing your forum before thinking about influencing open-source decisions with votes from it ...

**Comment by Mailaender** [comment]
Also :+1: to this default setting. However indeed we should fix the known problems first to avoid a bad first impression. Guess we need to add #11279 to that list.

**Comment by pchote** [comment]
If we are going to impose all of
- [ ] #3654
- [x] #5908
- [x] #11279

(which seems a bit overkill, IMO) then we probably want to close this for the near (and probably medium-to-long term) future until someone wants to tackle those.

**Comment by SoScared** [comment]
:-1: I believe the majority vote was somewhat skewed on Sleipnir. Regardless I think this change would lessen the experience of the mods. The role of the shroud is discovery and casual players are coming in for the fun. I don't think there's an experience of frustration among the vast majority of players when it comes to the shroud. It's something that is there that rewards you for exploring. It's satisfying to wipe away the dark with units. Defaulting explored map would take this away from a lot of players that don't consider tactics or strategy.

**Comment by pchote** [comment]
The obvious next step is to poll the wider community instead of relying on the relatively closed group of active forum and IRC members.  We can have a news post asking for player feedback and syndicate that to social media and the rest of our usual community places.

**Comment by pchote** [comment]
It's clear that this is going nowhere fast, so I'll close this for now to clear up the PR queue.

**Comment by SoScared** [comment]
Just wanna nudge in a change of heart from my earlier statement on this. Despite the good intentions there's no denying that new players in the MP lobby quickly starts favoring explored map once they get used to the UI. Seems then counter-productive to impose a 'better experience' for newcomers if they don't care for it.

Would be nice to have https://github.com/OpenRA/OpenRA/pull/11531#issuecomment-231556362 fixed as a part of such a change tho.

**Comment by Micr0Bit** [comment]
>Just wanna nudge in a change of heart from my earlier statement on this. I'm seeing new players in the MP lobby quickly starts favoring explored map once they get used to the UI. Seems then counter-productive to impose a 'better experience' for newcomers if they don't care for it.

after being forced many times to play public team-games where the shroud gets turned off "manually" ... 80-90% of the games im playing,  without a sign of this trend finding an end ... i have to second this

@pchote : im sry again for the troubles i have caused on sleipnir about this issue ... though i would assume , that the constant stream of changes on the mods towards gameplay and/or balance (not the engine itself) can get depressing for some of the deep-rooted regular players

**Pull request closed without merging**
