### PR TITLE
Fix display of progress text in Advanced Install when total file size is unknown.

### PR DESCRIPTION
**Pull request by emmalynrenato**
Hopefully I've got this correct...

### CODE REVIEW

**Review by Mailaender — DISMISSED** [review]
Looks good and I can't spot a regression in-game.

**Comment by pchote** [comment]
It looks like #15588 was filed, reviewed, and then merged while this was waiting for review.  Sorry for that, this is a rather unfortunate situation caused by 2/3 of our main reviewers being tied up over the summer.

This one looks like a more complete fix, as #15588 doesn't appear to set the progress bar to indeterminate.  Would you mind rebasing this on the current bleed so we can get that part of the fix in too?

**Comment by dmsnell** [comment]
Oh totally sorry I didn't find this when I wrote #15588! I hope I looked first but I honestly can't remember if I did. I thought for sure I at least searched through the issues but maybe I didn't search the open PRs

My apologies!

**Comment by abcdefg30** [comment]
Sorry for the confusion, @emmalynrenato! Could you rebase this PR? Then we can get it merged right away.

**Comment by Mailaender** [comment]
You didn't rebase properly. I tried to help with the web interface, but didn't quite get it. At the end of https://github.com/OpenRA/OpenRA/wiki/Contributing there are some hints. In this case you need to squash everything together.

**Comment by emmalynrenato** [comment]
Sorry, I got completely lost with trying to squash the commits in my existing fork, so I forked again and just applied the changes that were still needed. You can see them at:

https://github.com/emmalynrenato/OpenRA/commit/5b3606ffec596cc6a710e9002c8c03e6938e48d3

**Comment by abcdefg30** [comment]
You could try resetting this branch (`git reset --hard upstream/bleed`) to OpenRA's bleed and then cherry pick your new commit on top (`git cherry-pick [commit hash]`). Or you close this PR and open a new one. :)

**Comment by emmalynrenato** [comment]
I did the latter. New PR is #15611.

**Pull request closed without merging**
