### PR TITLE
D2K - Reimport Habbanya Erg and Imperial Basin

### PR DESCRIPTION
**Pull request by MustaphaTR**
I'm not sure what exactly are changed but those maps should be same as original now, if they weren't.

http://resource.openra.net/maps/21623/
http://resource.openra.net/maps/21621/

### CODE REVIEW

**Comment by obrakmann** [comment]
err... if you weren't aware of any problems with the maps, why did you reimport them?

**Comment by ltem** [comment]
Hmm the wormspawner positions could be polished/rearranged. Right now it seems that certain spawn points have an advantage.

**Comment by MustaphaTR** [comment]
> err... if you weren't aware of any problems with the maps, why did you reimport them?

Those maps are added before #12784, so it was clear that they had errors, some tiles possibly didn't even exists before that PR. I manually fixed brokenly imported tiles for Habbanya Erg, and old Imperial Basin was possibly also suffering that, i wanted to reimport them while importing other 8PLAYX maps too. That was what i was thinking.

I just compared them to be sure. Imperal Basin had some wrong, even missing rock-detail tiles. It was also missing Dunes. Habbanya Erg just had wrong rock-detail tiles that are now fixed with reimport.

> Hmm the wormspawner positions could be polished/rearranged. Right now it seems that certain player spawn points have an advantage.

It looks like old Imperal Basin had manually placed Worm Spawners, which are changed to their original locations with this PR. I haven't touched to Habbanya Erg when adding it first. I'll take a look to that.

**Comment by pchote** [comment]
Any progress here @MustaphaTR?

**Comment by MustaphaTR** [comment]
I just took a look to that, but couldn't really find any better location for wormspawners. Actually Habbanya Erg ones look pretty balanced to me. Unless @ltem you have a better idea, imo we can go with PR as is.

**Comment by ltem** [comment]
I'm fine with Habbanya Erg but I think that the upper left player in Imperial Basin has an advantage due to the lack of a worm spawner close to him but if we just added one it seems to alter the situation for him to a disadvantage.

Possible solutions:
1. We add it as it is (we wait for feedback from the players)
2. We try to balance all the worm spawners of Imperial Basin
3. We don't add the map ( :( )

I favor solution 1 and so I would approve this PR 👍

**Comment by reaperrr** [comment]
I'd vote for 1, too. If worms become too big of a problem, we can still try to rebalance them (or remove the spawners entirely).
I'll wait a bit with merging to give others time to respond if they disagree, though.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1e6476d1223e235e405c9522c6eaae39ec434867...d040a21c2fccd6f4598c85de861a129623b1db23)

**Pull request merged**
