### PR TITLE
Have some activities count as idle activities

### LINKED ISSUE #13015: Suggestion: Allow idle checks for actors that defaults their CurrentActivity to some Activity instead of null
**Issue:** 
Aircraft actors that default their CurrentActivity to FlyCircle instead of null will never pass any IsIdle() checks.
This also means that aircrafts cannot normally fire any OnIdle script trigger.

Units tested to be affected: "yak", "mig" (RA)
Suspected affected units as well (but not tested): Ora Bomber (TS)

**To Reproduce:**
Just try making an affected aircraft fire any Trigger.OnIdle function without using Stop(). You can use the full Lua arsenal for your attempt.

**Suggestion:**
Either
 - Allow IsIdle() actor checks to return true if CurrentActivity is the FlyCircle type, or
 - Allow Lua exposure of parts of the Activity class so that actor.CurrentActivity can be queried directly. That function can then be used in place of IsIdle().

### PR DESCRIPTION
**Pull request by abcdefg30**
I don't know exactly if that is a good idea. It didn't look like it regressed anything however.
Fixes #13015.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Leaving a note to myself to check if this can fix some of the issues I had in AS.

**Comment by reaperrr** [comment]
I might be too optimistic about that, but the plumbing for this might allow us to fix the infantry animation issues properly.

**Comment by obrakmann** [comment]
This will probably help with something I have a long-term plan for (making some actors run a specified  activity when they become idle, like `FlyCircle` for aircraft, for example. 👍

**Review by obrakmann — APPROVED** [review]

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/666d5b7885f08a50a6904abb77ed5693c6935760...cd62d5d958c523b90a2a6f9e5a4972007f44b094)

**Pull request merged**
