### PR TITLE
Fix damage of RA/TD minigunners and RA Jeep vs. Heavy armor

### LINKED ISSUE #11425: Veterancy on Heavy Armour makes them invincible to riflemen
Found this bug in RA and TD
Heavy Armour vehicles receive no damage from rifleman

http://logs.openra.net/index.php?year=2016&month=06&day=10#16:08:39

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes #11425.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by pchote** [comment]
The balance implications should be negligible in practice, so this looks completely reasonable to me.  :+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a76ee1959155c1624bf2c669a5754c528e453847

**Comment by MurtoTheRay** [comment]
This balance change makes tanks melt to riflemen. It was also based on a false claim, riflemen can damage heavy tanks: https://snag.gy/8OGMJt.jpg The top right one has been fired on by a single rifleman, the top right by two and the bottom middle by around 10.

**Comment by AoAGeneral** [comment]
This actually didn't fix the issue. As @MurtoTheRay mentions it is now killing tanks like crazy. The issue that Anjew was pointing out that tanks with veterancy was immune to minigunner fire. But only tanks with veterancy.

**Comment by SoScared** [comment]
Compared to the release the riflemen deals twice the damage against Heavy Tanks with this change (280 shots to kill the Heavy tank in the bleed vs 550 in the realease). Tanks cannot support infantry with this fix.

Riflemen doing little to no damage vs heavy armor was never an issue.

**Comment by SoScared** [comment]
Alternatively #11719 could fix this issue rather than give riflemen more damage.

**Pull request merged**
