### PR TITLE
Remove the possibility of ReloadDelay becoming 0 with modifiers

### LINKED ISSUE #21073: Modifiers can lead to ReloadDelay becoming 0, freezing the game when unit fires.
Noticed a new freeze in GenAlpha after engine update, i assume this is a regression from #20675. The PR adds check for ReloadDelay being defined as 0, but seems to have forgotten about modifiers.

Here's a full scrap upgraded Quad Cannon (ReloadDelay of 1) under the influence of a Speaker Tower (%90 Reload Delay modifier). You can see Selection UI shows its ReloadDelay as 0. Ordering the unit to fire freezes the game. 
image

On the version before the engine update the same setup still gives 0 as ReloadDelay on the UI, but seems to act same as 1. I think ReloadDelay should be properly capped at 1 to avoid the crash.

### PR DESCRIPTION
**Pull request by PunkPun**
Fixes #21073

### CODE REVIEW

**Review by MustaphaTR — APPROVED** [review]
I can confirm that it fixes the freeze issue.

**Comment by michaeldgg2** [comment]
Doesn't this change the behavior #21073 originally wanted to solve? That is not needing separate armaments for actors with two barrels?

**Comment by PunkPun** [comment]
having reload delay of 0 was never supposed to be allowed. I had explicitly added a check to crash the game if the game defined such a value

**Comment by MustaphaTR** [comment]
> Doesn't this change the behavior #21073 originally wanted to solve? That is not needing separate armaments for actors with two barrels?

It is `BurstDelay: 0` that was fixed, not `ReloadDelay`.

**Review by anvilvapre — APPROVED** [review]
untested.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/9f3d01017d3f37b18be548af8f05b6ad53b617ec...3da8bdd23af7ee02360d2a36ddfc78197b3855ed)

**Pull request merged**
