### PR TITLE
Fix crash when selecting the same map

### LINKED ISSUE #20194: Crash when starting a game
Likely a regression from #19752 as the code crashes in OrderBuffer. 

To reproduce the crash

- launch the game
- open Skirmish
- open the map browser
- click OK without selecting a map
- click Start Game.

[exception-2022-08-15T160012Z.log](https://github.com/OpenRA/OpenRA/files/9338837/exception-2022-08-15T160012Z.log)

This is most likely related to #20057.

### PR DESCRIPTION
**Pull request by teinarss**
Closes #20194

### CODE REVIEW

**Comment by PunkPun** [comment]
Could we consider #20057 as superseded? Or is this just losing a reliable reproduction case?

**Comment by penev92** [comment]
There seem to be indentation issues in the added code.

**Comment by teinarss** [comment]
fixed

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
https://github.com/OpenRA/OpenRA/blob/ae3a1c256167ec5daebbad9cbf483680eeaaa910/OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs#L186-L188 seems to be a `&&` while it should be `||`. Please fix this location instead.

**Comment by PunkPun** [comment]
Oh, it's an error on my part in the original PR #19885. It would be great to disabled the Ok button as well though.

https://github.com/OpenRA/OpenRA/blob/ae3a1c256167ec5daebbad9cbf483680eeaaa910/OpenRA.Mods.Common/Widgets/Logic/MapChooserLogic.cs#L55

`okButton.Disabled = this.onSelect == null || selectedUid == initialMap;`

**Comment by abcdefg30** [comment]
A map is already pre-selected when opening the chooser, so I don't agree with disabling the Ok button.

**Comment by PunkPun** [comment]
Oh right, then nevermind. The MapChooserLogic would need plumbing added for it to know what map is actually selected in LobbyLogic

**Comment by teinarss** [comment]
updated

**Review by PunkPun — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/480a3a7d457a8a2bc2fb48b72cd20e89a92d7917...309ca188872ef82d3dcd204aff48be17ad5a40e7)

**Pull request merged**
