### PR TITLE
Add InstantHit projectile and fix Trike/Raider muzzle flashes

### LINKED ISSUE #12270: Trike and Raider muzzle flashes not visible
The sequences start at the right frame of DATA.R8, so it must be something else.

### PR DESCRIPTION
**Pull request by reaperrr**
Armament requires a projectile to fire.

Fixes #12270.

### CODE REVIEW

**Comment by GraionDilach** [comment]
I'd vote for TeslaZap without any bolts, should be a lot less stressing.

**Comment by reaperrr** [comment]
> I'd vote for TeslaZap without any bolts, should be a lot less stressing.

That would require loading the RA assembly just for that.

My intention is to add a new invisible inst-hit projectile (basically LaserZap without any rendering) to Mods.Common, which we can use for machine guns, sniper rifles, "melee" weapons etc. across all mods. But that's for a later, separate PR.

**Comment by pchote** [comment]
Didn't @Mailaender add one of those in the dog PR?

**Comment by reaperrr** [comment]
> Didn't @Mailaender add one of those in the dog PR?

Yes, although that didn't even support blocking or inaccuracy, so at least for machine guns etc. it wouldn't really be usable (in that form).

**Comment by GraionDilach** [comment]
The dog PR wasn't even merged.

**Review by GraionDilach — APPROVED** [review]
Looks alright. :+1:

**Comment by reaperrr** [comment]
Updated.

> The dog PR wasn't even merged.

I know, I scavenged the projectile from there and added some minimum required bits for MG-weapons.

**Comment by Unit158** [comment]
This feature has been needed for a long time. Works fine on my end, the code is simple and sensible. 👍

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/74b3cf437391f4ac7b23a24d266b9b2122a755b2...d0c090b2b1bcb95361b64eba3fde65d3163d25c2)

**Pull request merged**
