### PR TITLE
Fix color picker actors being abstract

### LINKED ISSUE #15000: Colorpicker no longer works with actors starting with ^
I have rebased my mod's engine and noticed colorpicker was crashing. Tested on bleed to be sure and RA mod is also crashing. Removing the ^ on the actor name solved the issue for my mod.

    OpenRA engine version {DEV_VERSION}
    Red Alert mod version {DEV_VERSION}
    Date: 2018-03-26 14:42:11Z
    Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
    Runtime Version: .NET CLR 4.0.30319.42000
    Exception of type `System.Reflection.TargetInvocationException`: Özel durum bir çağırma hedefi tarafından oluşturuldu.
    Inner
      Exception of type `System.Collections.Generic.KeyNotFoundException`: Verilen anahtar sözlükte yoktu.
         konum: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       konum: OpenRA.ReadOnlyDictionary`2.get_Item(TKey key) c:\OpenRA\Bleed\OpenRA.Game\Primitives\ReadOnlyDictionary.cs içinde: satır 78
       konum: OpenRA.Mods.Common.Widgets.Logic.ColorPickerLogic..ctor(Widget widget, ModData modData, World world, HSLColor initialColor, Action`1 onChange, Dictionary`2 logicArgs) c:\OpenRA\Bleed\OpenRA.Mods.Common\Widgets\Logic\ColorPickerLogic.cs içinde: satır 36
       konum: System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       konum: System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       konum: System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
       konum: OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args) c:\OpenRA\Bleed\OpenRA.Game\ObjectCreator.cs içinde: satır 133
       konum: OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) c:\OpenRA\Bleed\OpenRA.Game\ObjectCreator.cs içinde: satır 98
       konum: OpenRA.Widgets.Widget.<>c__DisplayClass3.<PostInit>b__2(String l) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 274
       konum: System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       konum: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       konum: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       konum: OpenRA.Widgets.Widget.PostInit(WidgetArgs args) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 274
       konum: OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) c:\OpenRA\Bleed\OpenRA.Game\Widgets\WidgetLoader.cs içinde: satır 75
       konum: OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w) c:\OpenRA\Bleed\OpenRA.Game\Widgets\WidgetLoader.cs içinde: satır 44
       konum: OpenRA.Game.LoadWidget(World world, String id, Widget parent, WidgetArgs args) c:\OpenRA\Bleed\OpenRA.Game\Game.cs içinde: satır 136
       konum: OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.ShowColorDropDown(DropDownButtonWidget color, Client client, OrderManager orderManager, World world, ColorPreviewManagerWidget preview) c:\OpenRA\Bleed\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyUtils.cs içinde: satır 163
       konum: OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.<>c__DisplayClass8b.<SetupEditableColorWidget>b__8a(MouseInput _) c:\OpenRA\Bleed\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyUtils.cs içinde: satır 409
       konum: OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Mods.Common\Widgets\ButtonWidget.cs içinde: satır 179
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 400
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 391
       konum: OpenRA.Widgets.Ui.HandleInput(MouseInput mi) c:\OpenRA\Bleed\OpenRA.Game\Widgets\Widget.cs içinde: satır 105
       konum: OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() c:\OpenRA\Bleed\OpenRA.Game\Input\InputHandler.cs içinde: satır 50
       konum: OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) c:\OpenRA\Bleed\OpenRA.Game\Sync.cs içinde: satır 174
       konum: OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) c:\OpenRA\Bleed\OpenRA.Game\Input\InputHandler.cs içinde: satır 50
       konum: OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2GraphicsDevice device, IInputHandler inputHandler) c:\OpenRA\Bleed\OpenRA.Platforms.Default\Sdl2Input.cs içinde: satır 102
       konum: OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) c:\OpenRA\Bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs içinde: satır 493
       konum: OpenRA.Renderer.EndFrame(IInputHandler inputHandler) c:\OpenRA\Bleed\OpenRA.Game\Renderer.cs içinde: satır 162
       konum: OpenRA.Game.RenderTick() c:\OpenRA\Bleed\OpenRA.Game\Game.cs içinde: satır 671
       konum: OpenRA.Game.Loop() c:\OpenRA\Bleed\OpenRA.Game\Game.cs içinde: satır 781
       konum: OpenRA.Game.Run() c:\OpenRA\Bleed\OpenRA.Game\Game.cs içinde: satır 799
       konum: OpenRA.Game.InitializeAndRun(String[] args) c:\OpenRA\Bleed\OpenRA.Game\Game.cs içinde: satır 253
       konum: OpenRA.Program.Main(String[] args) c:\OpenRA\Bleed\OpenRA.Game\Support\Program.cs içinde: satır 37

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #15000.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Could we have a new-generaion upgrade rule along?

**Comment by pchote** [comment]
I agree we want an update rule, but it would be best if it were not tied to this specifically, but instead a more general thing that reports that actors starting with `^` can no longer be used directly and appropriate changes should be made (maybe then with a reference back to the color picker).

**Comment by abcdefg30** [comment]
Opened #15005.

**Review by pchote — DISMISSED** [review]
As mentioned in IRC, the color picker actors show up ingame and in the map editor.  The buildable and editor filter traits will need to be removed.

**Comment by abcdefg30** [comment]
Updated.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
Didn't test map editor since #14997 isn't merged yet (and I didn't feel like cherry-picking it), but I don't expect any issues there and the rest works fine now.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/e6991a25a0d67ba20032a2f9317d1bc22a8d305c...0d43a42d03eaf594e32856f2d874a26e7a1b58f8

**Pull request merged**
