### PR TITLE
RA - Added Fake Power Plants for France

### PR DESCRIPTION
**Pull request by MustaphaTR**
As discussed in #10437.

### CODE REVIEW

**Comment by Micr0Bit** [comment]
i honestly see no reason to add those ... it might even have a bad effect on basewalking  (disturbing defense to shoot on even cheaper fakes instead of the enemy defense or atleast the real "money-wasting version of powerplants) 

sry , but i was involved at the time on introducing the fakes together with scott ... and i think it is fine as it is now ... could find more interesting ways to buff france (if its even really necessary)

:-1:

**Comment by MustaphaTR** [comment]
> bad effect on basewalking 
They don't give buildable area, at least they aren't supposed to do.

As @ShadowA said their primary purpose is being against spies. That would be really bad for Spy owner to waste its spy even worse failing to power down enemy base may cause big bad effects on attacker.

**Comment by pchote** [comment]
Fake power plants seem like a reasonable addition to me
* It obfuscates your actual power usage vs generation, which a decent player can otherwise estimate by looking at your base.
* It disrupts the tactic of destroying your power plants to put you into low power.
* It disrupts spies.

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4323ff4bd5e6198931e57f710474537c59b53325...3042ea078f707eba41d50645cf4bf6790e931634)

**Pull request merged**
