### PR TITLE
Removed unused SDL2-CS code paths

### PR DESCRIPTION
**Pull request by Mailaender**
The real change can be inspected at https://github.com/OpenRA/SDL2-CS/pull/1. It shouldn't cause any changes except us shipping a slightly smaller DLL.

### CODE REVIEW

**Comment by pchote** [comment]
We should use this chance to resync with upstream so that we get the SDL 2.0.4 bindings (wanted for #10382).

**Comment by Mailaender** [comment]
Upstream https://github.com/flibitijibibo/SDL2-CS doesn't implement `GetDisplayDPI` yet. You have to contribute a patch for a DLLImport yourself.

**Comment by pchote** [comment]
It does: https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L1262

**Comment by Mailaender** [comment]
Strange that GitHub code search didn't find it.

**Comment by Mailaender** [comment]
I decided to go another route with this. https://github.com/OpenRA/OpenRA/pull/11793

**Pull request closed without merging**
