### PR TITLE
TD Balances

### PR DESCRIPTION
**Pull request by AoAGeneral**
Changes:

Light tanks were changed as followed to prevent them from being en massed and overpowering medium tanks.

Artillery changed due to frustration of explosions. Chance to explode also counted towards chance to chain explode. Resulting in 75% chance to lose 3-5 artilleries at once. Explosion also killed infantry.

Chemspray fire rate changed to help defend vs fast moving vehicles that crush. This includes stealth tanks and APCs.

Hummers/buggies damage vs heavy reduced to prevent them from countering light tanks and APCs when they shouldn't. They still make great harvester herassments.

Grenadier projectile speed increase to help vs en mass flame infantry and chem troopers. Making them a useful counter once more.

### CODE REVIEW

**Comment by Unit158** [comment]
You should remove the explodes trait if it has a chance of 0%.

Also, is -10 HP really enough to counter the ltnk spam? I'll test it, but I'm doubtful.

**Comment by AoAGeneral** [comment]
Its enough. Ive tested it in single player run and with the heavy reducement it makes a big difference.

**Comment by Unit158** [comment]
You forgot the damage reduction that you mentioned on the forums.

**Comment by AoAGeneral** [comment]
None: 25
 			Wood: 75
 			Light: 100
-			Heavy: 100
+			Heavy: 90

But for some reason its showing the tag line under grenade.

**Comment by AoAGeneral** [comment]
Placed edited files back into commit the long way. Slightly messy. Apologies.

**Comment by abcdefg30** [comment]
Now you need to rebase against latest bleed again. :)
(Please squash those commits down to one as well.)

**Pull request closed without merging**
