### PR TITLE
Reduce cash tick volume

### PR DESCRIPTION
**Pull request by pchote**
This PR adds the ability to define volume modifiers on individual notifications, and uses this to make the cash ticks a bit less prominent (and balance out the up/down volume mismatch in TD).

This is pretty simple polish, so i'm not sure whether we want to sneak this in for the next playtest or defer it to next + 1.

### CODE REVIEW

**Comment by matjaeck** [comment]
I would like it if these modifiers could be set in the game settings and their values be applied to notifications that have the modifier trait. For example, instead of adding a generic `VolumeModifier`, add a `ChatNotificationVolumeModifier` and `GameNotificationVolumeModifier` (and others that can be used for a group of notifications.) 

Or, allow to define a modifier per notification in a `NotificationVolumeModifier` trait and bind that definition and a value to some sort of `NotificationVolumeManager`.

**Comment by jaZzKCS** [comment]
There are a variety of sounds that are still standing out in comparison to their companions (example being the money up/down sounds in Tiberian Dawn) which I would love to see fixed via this matter. All in all this would give over a much more polished vibe regarding the whole project. These things are small but important.

The money ticks themselves being a nuisance or not is not widely debated, as the last attempt of fixing them (which resulted in the mute-option as we have it today) gave players that were annoyed by it (which is directly connected to it's volume most of the times) the chance to turn it off, whereas the vast majority simply doesn't care.

If it leads to more people not being inclined to turn it off because of it being too loud, then I am all for this fix.

**Comment by netnazgul** [comment]
ok, I gave it a quick test. I'd say for me it makes little difference, I'm comfortable with both. So for those who have it disabled it will make no difference at all (obviously), and it will comfort the all-too-loud sounds into bearable zone. So subjectively I'm up for the fix.

Also, if I get it right, people will be able to modify other notification sounds volume via [simple enough] yaml modification.

**Comment by pchote** [comment]
> (example being the money up/down sounds in Tiberian Dawn)

Fixed in this PR.

**Comment by pchote** [comment]
This integrates nicely with the other sidebar sound fixes, and generated some good discussion on discord - so adding to the milestone.

**Review by Smittytron — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/e809a4e47c02f3968e2edccac8f13bcca417283c...b172a446a004d0bb049dcc1767c9758615ae2369

and picked to prep.

**Pull request merged**
