### PR TITLE
Style fixes (.NET 8 SDK)

### PR DESCRIPTION
**Pull request by RoosterDragon**
If you're using the .NET 8 SDK that came out today (or e.g. updated Visual Studio which ships it) then some of the style rules have been updated and trigger additional warnings locally. We can also except them to be flagged by CI once the runners move to .NET 8, even if we continue to specify .NET 6 as the build target.

Fix these issues to improve the local dev experience for anybody using this SDK:

```
> dotnet --version
8.0.100
```

### CODE REVIEW

**Review by PunkPun — DISMISSED** [review]
Overall LGTM, untested

**Review by penev92 — DISMISSED** [review]
👍

**Comment by penev92** [comment]
But needs a rebase already.

**Comment by RoosterDragon** [comment]
Rebased.

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[Chnagelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b424e10100e46b56b184b762083afb35155a8ad5...bb7d0735f7fec0b471c7ab6835a032633584fffe)

**Pull request merged**
