### PR TITLE
Disable legacy coordinate hack in TS.

### LINKED ISSUE #8274: LocalOffset doesn't work correct in TS viewing angle
It looks like OpenRA doesn't use the right viewing angle for LocalOffset. I tested the same unit with the same settings in the RA mod - result was that the offset was 100% correct while in TS I got this result:
localoffset

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18165457-localoffset-doesn-t-work-correct-in-ts-viewing-angle?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
This should fix #8274.  It could do with some testing by @penev92 or @DoGyAUT to confirm this.

### CODE REVIEW

**Comment by penev92** [comment]
Code seems legit. Will test as soon as I can.

**Comment by reaperrr** [comment]
:+1:

**Comment by GraionDilach** [comment]
@DoGyAUT went to a vacation of a week with his sister's family starting from yesterday afaik. >_>

**Comment by pchote** [comment]
The disruptor tank turret provides a useful visual test case of this fix in action.

**Comment by penev92** [comment]
Confirmed!
Please include my small fix for the `4TNK` offsets (my test case):
```
		Armament@PRIMARY:
			Weapon: 120mmx
			LocalOffset: 500,60,360, 500,-85,360
			MuzzleSequence: muzzle
		Armament@SECONDARY:
			Weapon: MammothTusk
			LocalOffset: 0,200,410, 0,-200,410
```
The result ingame:

**Comment by pchote** [comment]
Updated.

**Comment by penev92** [comment]
Thanks.
:+1:

**Pull request merged**
