### PR TITLE
Fixed Makefile check of MacOS architecture

### LINKED ISSUE #20641: Manual linking required on M2 with .NET
## Issue Summary

The manual linking as described here still seems to be required: https://github.com/OpenRA/OpenRA/issues/19805 , at least when using .NET.

A PR was submitted that supposedly fixed the issue: https://github.com/OpenRA/OpenRA/pull/19887

However that doesn't seem to have fixed it? Either that or the build instructions need to be updated.

Even on `bleed` at commit e1b78c482119e961cb9352802bafc2a73f14233f `./launch-game.sh` fails, requiring the manual linking described in #19805:

```
-> % ./launch-game.sh Game.Mod=ts
Platform is OSX (Arm64)
Engine version is {DEV_VERSION}
Runtime: .NET CLR 6.0.13
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 364
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 307
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Launcher/Program.cs:line 32

OpenRA has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /Users/user/Library/Application Support/OpenRA/Logs/
The FAQ is available at http://wiki.openra.net/FAQ
```

With the following in `graphics.log`:

```
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/user/Games/C&C Red Alert/ra2/engine/libSDL2' (no such file)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.CanCreateGLWindow(GLProfile profile, List`1 errorLog) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 548
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.<>c__DisplayClass49_0.<.ctor>b__0(GLProfile profile) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 156
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 155
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /Users/user/Games/C&C Red Alert/ra2/engine/OpenRA.Game/Game.cs:line 382
```

Curiously, this isn't needed when building the project with mono. But my understanding is that .NET is better than mono...? And ra2 mod ~~requires .NET to build...~~ (EDIT: [it doesn't](https://github.com/OpenRA/ra2/issues/804#issuecomment-1405775023)!) so it would be great if the linking issue with homebrew and .NET was addressed.

## Reproduction

Err, see here: https://github.com/OpenRA/ra2/issues/804#issuecomment-1405694114

## Expected behavior

For no manual linking of homebrew library dependencies needed.

### PR DESCRIPTION
**Pull request by penev92**
Closes #20641.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
Untested, but lgtm.

**Comment by taoeffect** [comment]
Saw you guys pushed a PR for this and needed some testing. Confirm this version works too 😄 👍

**Comment by penev92** [comment]
@taoeffect thank you!

**Comment by taoeffect** [comment]
No problem, thank you guys for your quick help! ^_^

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/3366c97ebd097e0f2b0c6033416e153dd9b49c94...3f86cc0b908728f09c2d6ae35806a0c4f5af9ec9)

https://github.com/OpenRA/OpenRA/commit/f707b9c97588f62bff1258441bab3ed9b90eb438

**Pull request merged**
