### PR TITLE
Misc ra balance changes

### PR DESCRIPTION
**Pull request by Amelia55555**
Some bite-sized misc ra balance changes based on past discussions on IRC and on the forums. More changes to follow in a future PR.

### CODE REVIEW

**Comment by chrisforbes** [comment]
:+1:

**Comment by MicroJOo** [comment]
:+1:  tested and works 

i just wanna say a last word for the sniper ... theres a good chance that we receive a shitstorm for removing it from the gameplay ... but we should not give up on this idea , and keep the mod "clean" from any external content ... and rather tweak some units instead of getting jelly legs and add the sniper back 
its a nice unit though !

pillbox needs some attention , we should keep an eye on it on the playtests ...

**Comment by penev92** [comment]
OK, I'm going to assume there are lengthy discussions that ended well argumented decisions behind these chances.
I won't bother looking those up or reading them.
I'm going to keep my opinion that half of the changes here make no sense at all to myself and go with the popular opinion.

The code part seems OK and popular opinion says "aye" to the rest :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/65413d50180059f5590840c050ef04b4448442a4...ee14aff673fc807d8e4f048b9d3785c729961b08)

**Comment by TheRaffy** [comment]
I will miss the sniper. I used him alot, he was a good counter to tanya in my opinion. It looks like that shocktropers are the new snipers then. I aggree that the shocktroopers were abit useless but that are sandbags and silos too. 
And i don't like the argument of keeping it clean, just use the original units is like, just using the original balancing in my opinion. Say goodby to the hijackers, too? Or what? You take away my toy :(
Snipers are cool. In my opinion a longer recharge would also done it. Instead of kicking him he also would be a good subfaction unit. Just mentioning that. 

greetings yellow

**Comment by MicroJOo** [comment]
the sniper just has nothing to do with red alert ... if we focus on the westwood content and balance the game without adding "new content" ... then its atleast "somewhat" red alertish ...

the hijacker is just a converted unit ... its still original content just with different rules ...

**Comment by TheRaffy** [comment]
I would understand you, if you are afraid of low quality fan made units, i share that fear, but snipers aren't crap or ugly. ;) I see the sniper as the "new" allies tents (terrain fitting) - new content, but they are fitting to the rest and extend the game gracefully. Tweaking the balances might be one of the hardest things, hornestly big respect for that, but detecting missing pieces of the jigsaw is the supreme discipline in my opinion. Creating & Adding fitting new content like the radar ping or the sniper included. And that's far way from featurecreap. 

I think the developers are capable and smart enough to understand how things intertwine and shouln't be afraid of touching every aspect of the game to improve it and don't stick, or even restrict the possibilities, to the original art-content.
I just don't think that it's wrong to create new red alertish additional stuff like the sniper.
To be exact i think it's just the opposite. It's awesome to find additional details added with much blood, sweat and tears. ;) 

Do you know the game dune2 the golden path? One of the best things i saw in that whole dune2 remake was the new Flak Trikes unit. I had to salute to Drackbolt for that brilliant adding.
Or do you know the Diablo 1 MOD - Belzebub? Same here, a stunning and mindblowing amount of new and fitting content. This mod is better than the official Hellfire addon. But I'm digressing here... Back to OpenRA..

Its not my decision, but please do consider a voting at fb for example. This could show how the majority is thinking about the sniper.

The other hypothetical way would be to remove the sniper and watch the bounty rising to undo that :)

**Comment by pchote** [comment]
> It looks like that shocktropers are the new snipers then. I aggree that the shocktroopers were abit useless

This is really what it came down to.  The shock trooper naturally fits the sniper role, but was left being rather useless because the sniper was already there.  The shock trooper fits the soviet theme much better than a rather generic sniper, so it made a lot of sense to combine the two units using the assets of the existing shock trooper.

**Comment by TheRaffy** [comment]
I agree to that fact that shocktroopers are fitting more to the soviets theme and to the epic battle between Tesla and Einstein. But that's not my point. Even if shocktroopers might now can kill other infantry with a zzap, that will not make them equal. I'm still favouring the sniper. Because snipers can be used a lot more tactically. I see three additional purposeways compared to the shocktrooper:

1.Stationary hidden scouts:
I sometimes use them as a stationary hidden scout, with a hold fire order "no attack". That helps especially when you need to detect enemy movment on the map, because normal scouts like dogs and yaks will get killed or hunted down. Snipers are a really great way to gain additional view at the front that will support fast hit and run attacks of other units especially if you are facing an basewalking pro allies player. As soviets it's a pain in the ass to find enemy artys standing close to an aa, because of the high range of the artys and the lag of view and additional the gap-gens. In such situations you will be very happy to have the view of a hidden sniper.

2. The soviet camouflage pillbox
Hidden stationary defence in your base, in range of your nuclear silos, techcenters, consturctionyards,.. to kill any evil infantry sneaking in your base, like paratroopers, engineers, apc rushes, chinook drops, phase transporters, and of course tanya,...  
You will definitively have the fist shot.

3. Oil-deck babysitting
Oil decks are often spread over the map, far away, some at smaller islands and rarely in your base. In such cases you can use snipers to catch some enemy engineers approaching.

**Comment by pchote** [comment]
I have proposed that we let the hijacker cloak when idle so it can fill the stationary hidden scout role, as well as opening up new tactics for sneaky steals.  It is just a proposal at this stage, so it may not be included.

**Comment by TheRaffy** [comment]
Wow, that's a very good proposal, sneaky hijacker ;) that idea has potential.
Okey, hidden scout role check!  and new sneaky steal check!

One thing that I also love at the sniper is that the bullet doesn't have any trace or effect. That supports his sneakiness. -> you can't tell from what direction he was shooting, if hes out of your view. You theoretically could do some evil micro management with fooling the enemy to run back an forth, with more as one sniper.^^ by switching hold fire off and on, depending on where the enemy is. But I never saw that happen in a match.
The white trace of atrys for example is a good way to guess the artys position. The same effect will have the tesla zzaap from the shock troopers. but I think that's okey as trade off.

**Comment by lasselaak** [comment]
One more vote for keeping the sniper or adding the camo feature to another infantry unit.

the use as a "hidden scout" with don't attack stance has been really useful in some maps

**Comment by MicroJOo** [comment]
@pchote : i like this idea

**Comment by TheRaffy** [comment]
I don't agree to the argument that spam of hijackers might be op. If somebody will do that you could answer with infantry spam as an counter.

**Comment by MicroJOo** [comment]
im talking about pchotes "cloaked" hijackers ... just imagine a army of cloaked hijackers , and around 5-10 tanks drive by ... thats would be just stupid

**Comment by TheRaffy** [comment]
I also was talking about the cloaked version. Hijackers can still get overdriven, espesially if they don't move, and you still have to move your hijackers unit to capture the tank, and with the movement the unit will get visible again. As i said, other infantry can kill them, dogs might see them, or jeeps or flacktruks can shoot them down very fast.
Imagine 5-10 Tanks driving in a field of mines. all would get lost, would'nt that be stupid.
What I try to say is that yes you might losse a tank, but you can react to that, and avoid more looses.
You will need to invested time and money in every army of units,.. why should that be stupid at all.

**Comment by MicroJOo** [comment]
as i allready said , soviet isnt meant to be the sneaky faction ... buffing the shocktrooper should be enough

**Pull request merged**
