### PR TITLE
Updated SharpFont to version 4.0.1

### PR DESCRIPTION
**Pull request by Mailaender**
See https://www.nuget.org/packages/SharpFont/4.0.1 for a changelog.

### CODE REVIEW

**Comment by pchote** [comment]
This probably wants to wait for Next + 1.  Doing a major-version update on a dependency immediately before shipping a new release is a bad idea.  There doesn't seem to be a changelog for 4.0.0, so its hard to say what this actually gives us.

**Comment by Mailaender** [comment]
4.0.1 was just a re-release https://github.com/Robmaister/SharpFont/compare/v4.0.0...v4.0.1

**Comment by pchote** [comment]
Freetype 2.7 has just come out, do you know if we expect any SharpFont changes to go with that?

**Comment by Mailaender** [comment]
No, I am not really in contact with the author. Just updated this, because I checked all dependencies systematically for old versions.

**Comment by pchote** [comment]
Ok.

**Review by pchote — APPROVED** [review]
No objections here, and works fine on OSX. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1d315e8323162d3ec6f9c0b21e126773050eac71)

**Pull request merged**
