### PR TITLE
Fix ants teleporting into the map area in ant-01

### PR DESCRIPTION
**Pull request by abcdefg30**
Waypoint17 is not at the map edge, waypoint7 is.
Also fixes a path, since waypoint20 -> waypoint10 is going back and makes no sense.
Going directly waypoint20 -> waypoint2 works and as compensation I added
waypoint21 -> waypoint10 -> waypoint2.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]

**Comment by pchote** [comment]
Why aren't we using the teams or paths from the original mission?
Applying a basic translation of the [TeamTypes] from `sca01ea` shows:
```
scare=  ANT3 x 1 (Germany): Spawn at W.27, Attack Ukraine, Attack Germany
scout=  ANT3 x 1 (Germany): Spawn at W. 4, Move to W.4, Move to W.3, Move to W.2, Move to W.0, Attack Greece
scout2= ANT3 x 1 (Germany): Spawn at W. 7, Move to W.7, Move to W.16, Move to W.1, Move to W.0, Attack Greece
scout3= ANT3 x 1 (Germany): Spawn at W.12, Move to W.12, Move to W.14, Move to W.9, Move to W.0, Attack Greece
nwharv= ANT3 x 2 (Germany): Spawn at W. 8, Move to W.8, Move to W.13, Move to W.16, Move to W.17,11:10
seharv= ANT3 x 1 (Germany): Spawn at W. 4, Move to W.4, Move to W.2, Move to W.10, Move to W.9,11:10
m020=   ANT3 x 2 (Germany): Spawn at W. 8, Move to W.4, Move to W.5, Move to W.15, Move to W.0
loop1=  ANT3 x 2 (Germany): Spawn at W.12, Patrol to W.13, Patrol to W.1, Patrol to W.16,6:0
m025=   ANT3 x 2 (Germany): Spawn at W. 7, Move to W.7, Move to W.16, Move to W.1, Move to W.0, Attack Ukraine
loop2=  ANT3 x 2 (Germany): Spawn at W. 4, Patrol to W.18, Patrol to W.3, Patrol to W.5,6:0
m040=   ANT3 x 2 (Germany): Spawn at W. 8, Move to W.8, Move to W.9, Attack Greece
m042=   ANT2 x 1 (Ukraine): Spawn at W. 4, Move to W.4, Move to W.5, Move to W.15, Attack Ukraine, Attack Greece
m060a=  ANT3 x 2 (Germany): Spawn at W. 4, Move to W.4, Move to W.3, Attack 2
m060b=  ANT3 x 2 (Germany): Spawn at W. 7, Move to W.7, Move to W.16, Move to W.1, Attack Neutral, Attack 2
m060c=  ANT2 x 1 (Ukraine): Spawn at W. 8, Move to W.8, Move to W.9, Move to W.19, Attack Ukraine, Attack Greece
sat1=   ANT3 x 1 (Germany): Spawn at W.20, Move to W.20, Attack Greece
sat2=   ANT3 x 1 (Germany): Spawn at W.21, Move to W.21, Attack Greece
wait1=  ANT3 x 2 (Germany): Spawn at W.12, Move to W.12, Move to W.11, Move to W.1,5:3, Patrol to W.0,11:14
wait2=  ANT3 x 2 (Germany): Spawn at W. 8, Move to W.8, Move to W.10, Move to W.2,5:3, Patrol to W.0, Attack 2
wait3=  ANT3 x 2 (Germany): Spawn at W. 7, Move to W.7, Move to W.6, Move to W.15,5:2, Patrol to W.0
p2min=  ANT3 x 1 (Germany): Spawn at W.12, Move to W.11, Move to W.1,11:14
ditch1= ANT3 x 5 (Germany): Spawn at W. 4, Move to W.18, Move to W.5, Attack Greece
ditch2= ANT3 x 5 (Germany): Spawn at W. 7, Move to W.17, Move to W.16, Patrol to W.1, Attack Greece
ditch3= ANT3 x 4 (Germany): Spawn at W.12, Move to W.11, Move to W.14, Patrol to W.9, Attack Ukraine, Attack Greece
ditch4= ANT2 x 2 (Ukraine): Spawn at W. 8, Move to W.10, Patrol to W.2, Attack Greece
m130=   ANT3 x 2 (Germany): Spawn at W.12, Move to W.12, Move to W.11, Move to W.14, Move to W.9, Attack Ukraine, Attack Neutral
m140=   ANT3 x 2 (Germany): Spawn at W. 7, Move to W.17, Move to W.6, Move to W.15, Attack 8, Attack 7
m145=   ANT3 x 2 (Germany): Spawn at W. 4, Move to W.18, Move to W.3, Move to W.2
m149=   ANT2 x 1 (Ukraine): Spawn at W. 8, Move to W.8, Move to W.9, Attack Ukraine, Attack Germany, Attack 2
m165b=  ANT3 x 3 (Germany): Spawn at W. 7, Move to W.17, Move to W.16, Move to W.1, Attack Ukraine, Attack Germany
m180=   ANT3 x 2 (Germany): Spawn at W. 4, Move to W.18, Move to W.3,1:26, Patrol to W.0, Attack Greece
m186=   ANT2 x 1 (Ukraine): Spawn at W.12, Move to W.12, Move to W.11, Move to W.13, Move to W.1, Attack Ukraine, Attack Germany,11:14
m210=   ANT3 x 3 (Germany): Spawn at W. 4, Move to W.18, Patrol to W.26, Attack 2
m214=   ANT3 x 2 (Germany): Spawn at W.12, Move to W.11, Patrol to W.1, Attack Ukraine
m280a=  ANT3 x 2 (Germany): Spawn at W. 7, Move to W.17, Move to W.6, Attack Ukraine, Attack Greece
m280b=  ANT3 x 2 (Ukraine): Spawn at W. 8, Move to W.10, Patrol to W.2, Attack Greece
```

**Comment by reaperrr** [comment]
That's a good question.
But I think at least for the hotfix, the PR as-is would be safer than rewriting half the lua script under time pressure, which would then also require more testing.

**Review by pchote — APPROVED** [review]
Indeed. Confirmed that this improves the current script.

**Comment by pchote** [comment]
c60ee03a580b3c62c010569fbaf266bc0a89f74b

https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/7971961f27f7f45fbe995c21b792f2cddf5ab50c

**Pull request merged**
