### PR TITLE
Added a check for Byte Order Marks

### PR DESCRIPTION
**Pull request by Mailaender**
So the Travis build will alert us when they are re-introduced again.

### CODE REVIEW

**Comment by Mailaender** [comment]
Hmm, damn. Looks like grep exits with 1 if it can't find anything.

**Comment by obrakmann** [comment]
There are several issues with that test:

1. grep returns 0 on success (if the given string is found), 1 if the string isn't found, and 2 on failure
2. you're scanning all files, but only the .cs files have been cleaned

**Comment by Mailaender** [comment]
I wonder why Travis does not display the remaining files which are shown to me locally.

**Comment by obrakmann** [comment]
``find . -name '*.cs' -print0 | xargs -0r grep -bHo `printf '^\xef\xbb\xbf'` | grep ":0:" && exit 1``

should work

**Comment by Mailaender** [comment]
Travis says no.

**Comment by RoosterDragon** [comment]
Should this also check .csproj and .sln extensions?

**Comment by Mailaender** [comment]
Probably, but for CI integration we need it to exit 0 when it finds nothing (== everything is fine).

**Comment by RoosterDragon** [comment]
For informational purposes:
Visual Studio defaults to creating new files with the BOM. However it will respect the current encoding of the .sln and .cs files and not reintroduce a BOM if one was not present originally.

It will however rewrite the .csproj file itself whenever it needs to be changed and it doesn't care about the existing file. It will always add a BOM and a trailing newline.

**Comment by pchote** [comment]
This isn't very informative in its current state (from travis):
```
$ make check
Checking source code for Byte Order Marks
make: *** [check] Error 1
The command "make check" exited with 2.
```

**Comment by Mailaender** [comment]
I also don't know why Travis swallows the output. It is more verbose in my local installation.

**Comment by pchote** [comment]
I don't recall seeing any BOM issues in the last couple of years.  Perhaps newer versions of VS were updated to respect the convention of the file?  Is this PR still needed for the future?

**Comment by Mailaender** [comment]
> Is this PR still needed for the future?

I guess not.

**Pull request closed without merging**
