### PR TITLE
Fix ProductionOverlay crash.

### LINKED ISSUE #14573: Crash when killing palace on Harkonnen 8.
With the current status of #14427, killing or capturing Ordos Palace crashes the game with following:

    OpenRA engine version {DEV_VERSION}
    Dune 2000 mod version {DEV_VERSION}
    on map 1bebeb7df480c93d45f48430a5595e2c1668fea3 (Harkonnen 08 by Westwood Studios).
    Date: 2017-12-25 10:07:32Z
    Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
    Runtime Version: .NET CLR 4.0.30319.42000
    Exception of type `System.InvalidOperationException`: Can't find production queues.
       konum: OpenRA.Mods.Common.Traits.Render.WithProductionOverlay.SelectQueue(Actor self) h:\OpenRA\Harkonnen 8\OpenRA.Mods.Common\Traits\Render\WithProductionOverlay.cs içinde: satır 80
       konum: OpenRA.Mods.Common.Traits.Render.WithProductionOverlay.OpenRA.Traits.INotifyOwnerChanged.OnOwnerChanged(Actor self, Player oldOwner, Player newOwner) h:\OpenRA\Harkonnen 8\OpenRA.Mods.Common\Traits\Render\WithProductionOverlay.cs içinde: satır 97
       konum: OpenRA.Actor.<>c__DisplayClass18.<ChangeOwner>b__17(World w) h:\OpenRA\Harkonnen 8\OpenRA.Game\Actor.cs içinde: satır 295
       konum: OpenRA.World.Tick() h:\OpenRA\Harkonnen 8\OpenRA.Game\World.cs içinde: satır 360
       konum: OpenRA.Game.InnerLogicTick(OrderManager orderManager) h:\OpenRA\Harkonnen 8\OpenRA.Game\Game.cs içinde: satır 605
       konum: OpenRA.Game.LogicTick() h:\OpenRA\Harkonnen 8\OpenRA.Game\Game.cs içinde: satır 629
       konum: OpenRA.Game.Loop() h:\OpenRA\Harkonnen 8\OpenRA.Game\Game.cs içinde: satır 759
       konum: OpenRA.Game.Run() h:\OpenRA\Harkonnen 8\OpenRA.Game\Game.cs içinde: satır 799
       konum: OpenRA.Game.InitializeAndRun(String[] args) h:\OpenRA\Harkonnen 8\OpenRA.Game\Game.cs içinde: satır 253
       konum: OpenRA.Program.Main(String[] args) h:\OpenRA\Harkonnen 8\OpenRA.Game\Support\Program.cs içinde: satır 37

### PR DESCRIPTION
**Pull request by pchote**
`WithProductionOverlay` was still assuming the old behaviour for `ProductionQueue.Enabled` (set once during creation, then never touched), which was changed by #14387.  This makes the queue filtering dynamic so that the overlay is disabled if there queues themselves haven't been initialized yet.

Fixes #14573.

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]
Not tested, but code looks good to me

**Comment by reaperrr** [comment]
Maybe @MustaphaTR or @ltem could test this, I won't have time until tomorrow.

**Review by MustaphaTR — APPROVED** [review]
I have hit another issue with Har8 but this is fixing the crash at #14573.

**Review by ltem — APPROVED** [review]
Tested as well and it fixed the issue.

**Comment by ltem** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/499666cff743c80e2e2bc488a629e51148f45250...e790a47a64a244ff71afa2eca681f817ccb60f3c)

**Pull request merged**
