### PR TITLE
Fix crash in RallyPointIndicator.

### LINKED ISSUE #17461: Regression after rallypoint queuing merge
On bleed (203fff0ab70f2444b5e2ab64250aeac6c221ea46), just got the following crash:

```
Exception of type `System.InvalidOperationException`: Sequence contains no elements
  at System.Linq.Enumerable.Last[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <528d6080a81043639dcbdd923e15ce19>:0 
  at OpenRA.Mods.Common.Effects.RallyPointIndicator.OpenRA.Effects.IEffectAboveShroud.RenderAboveShroud (OpenRA.Graphics.WorldRenderer wr) [0x00088] in <bfd095d3490b40859d2f55c9d566a578>:0 
  at OpenRA.Graphics.WorldRenderer.<GenerateOverlayRenderables>b__30_6 (OpenRA.Effects.IEffectAboveShroud e) [0x00000] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00051] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () [0x0002b] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) [0x000f4] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00000] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at OpenRA.Graphics.WorldRenderer.PrepareRenderables () [0x00067] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.RenderTick () [0x00059] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.Loop () [0x0014d] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.Run () [0x0003c] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00044] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
```

(against an AI 22 seconds after game start while placing the rax)

It seems to be related to https://github.com/OpenRA/OpenRA/pull/17021

Edit: I might have mess up something with my build. If the traceback makes no sense I'll close the issue until I can reproduce it.

Edit2: OK, reproduced: spam click while placing, that is trying to select the building as soon as it starts building. Took me a few tries to re-trigger, it seems to require a tick-exact selection.

### PR DESCRIPTION
**Pull request by tovl**
Fixes #17461

I can't click fast enough to actually reproduce the issue, but this should fix it. Can you check @ubitux?

### CODE REVIEW

**Comment by ubitux** [comment]
Fix doesn't seem correct:

```
Exception of type `System.ArgumentOutOfRangeException`: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at OpenRA.Mods.Common.Effects.RallyPointIndicator+<RenderInner>d__12.MoveNext () [0x00026] in <5ce9b37057134e9d8eff3d65c415a433>:0 
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x0006f] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () [0x0002b] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <528d6080a81043639dcbdd923e15ce19>:0 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) [0x000f4] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00000] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
  at OpenRA.Graphics.WorldRenderer.PrepareRenderables () [0x00078] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.RenderTick () [0x00059] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.Loop () [0x0014d] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.Run () [0x0003c] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00044] in <13c5b2c443af44d3b43ac276e6031aa9>:0 
```

**Comment by pchote** [comment]
That's actually a different issue to the first, but the cause and fix will be the same.

**Comment by tovl** [comment]
Updated.

**Comment by ubitux** [comment]
Looks like I'm unable to reproduce the crash with that last update.

**Review by abcdefg30 — COMMENTED** [review]
I suppose we want to add some saveguards in the Lua API too? (It uses a `Last` call as well.)

**Comment by tovl** [comment]
What Lua API do you mean? `RallyPointIndicator.targetLineNodes` is not public.

**Comment by abcdefg30** [comment]
As far as I understood, `targetLineNodes` is using the `Path` from `RallyPoint`. So if there are no target line nodes, there are no entries in the path either. (Or is this an issue where just `targetLineNodes` is uninitialized? If so you can ignore my request.) If `Path` can be empty, https://github.com/OpenRA/OpenRA/blob/203fff0ab70f2444b5e2ab64250aeac6c221ea46/OpenRA.Mods.Common/Scripting/Properties/ProductionProperties.cs#L82 can crash as well.

**Comment by pchote** [comment]
IMO it would be logical to return the location of the highest priority exit if/when `Path` is empty.

We way end up using an empty path for https://github.com/OpenRA/OpenRA/pull/16701#issuecomment-554766034, but even if we don't we should try make sure this is robust.

**Comment by tovl** [comment]
This is just an issue with `targetLineNodes` being uninitialized. `Path` is actually never empty, because it will always contain at least the starting point. 

This is a simple bugfix; speculative fixes for features that don't exist yet and may not need fixing at all are not something I'm going to do.

**Comment by abcdefg30** [comment]
Thinking about it: Wouldn't it make more sense to fix the initialisation of `targetLineNodes` instead of "hiding" the issue in case it is uninitialized? Since the crash doesn't seem to be obvious, it is probably not too unlikely that the next person working on this code is breaking it again not knowing about this oddity. (I.e. why don't we set an initial value in the ctor?)

**Comment by pchote** [comment]
At the very least it should detect the issue and throw a `LuaException` about querying too early instead of a nasty (from a scripting perspective) linq exception.

**Comment by tovl** [comment]
> Wouldn't it make more sense to fix the initialisation of targetLineNodes instead of "hiding" the issue in case it is uninitialized?

Not if we want to deliberately hide rally point indicators in the future; Then this will be a common and expected situation.

> At the very least it should detect the issue and throw a LuaException about querying too early

Are we even talking about the same thing here? This has nothing to do with the Lua API and `Path` can never be empty. If in the future something changes that would make `Path` empty somehow, there is no reason to assume that will be because of querying too early or something else entirely. Such an exception message would be actively misleading!

**Comment by abcdefg30** [comment]
> Not if we want to deliberately hide rally point indicators in the future; Then this will be a common and expected situation.

If I understand https://github.com/OpenRA/OpenRA/pull/17462#issuecomment-566460018 correctly the plan is to use an empty path in case we want to hide the indicators, which would mean initialising them as usual would still work.

**Comment by tovl** [comment]
There is no plan for that currently, and it would probably be better to not leave the path empty in that case (see https://github.com/OpenRA/OpenRA/pull/16701#issuecomment-555495431). This is also beside the point.

`targetLineNodes` _is_ properly initialized; the problem is that it is initialized as an empty list. Even if we end up having an empty `Path` list (which currently isn't even possible), what would you then fill `targetLineNodes` with in order to not make it also an empty list? More importantly, why would you _want_ to fill `targetLineNodes` with anything in that case, when the whole point is to not show anything and the whole purpose of `targetLineNodes` is to indicate what needs to be shown?

**Comment by abcdefg30** [comment]
I wasn't asking to remove the check for if `targetLineNodes` is empty, that would indeed make no sense if we wanted a case without indicators. I was more wondering why you are initialising it with an empty list instead of directly adding the path. I guess it doesn't matter much in the end though.

**Comment by tovl** [comment]
I see what you mean now. Updated.

**Review by abcdefg30 — APPROVED** [review]

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/800fde8158d4a353ac5459faf0cdeca6e5ee3e20

**Pull request merged**
