### PR TITLE
Added a new checkbox to settings, where you can turn off the silo war…

### PR DESCRIPTION
**Pull request by SzabKel**
Added a new checkbox to settings, where you can turn off the silo warnings, also changed the default silo warning time to 30s
Did the following request: #6955

### CODE REVIEW

**Comment by pchote** [comment]
I don't like the idea of adding a checkbox for this.  We should instead fix the warnings to be less annoying, which will improve the game for everyone.

**Comment by Phrohdoh** [comment]
I'm behind the idea of not forcing the notification but to compromise perhaps a value `< 0` could be introduced as a "never play the sound" option.

**Comment by SzabKel** [comment]
I thought a checkbox would be a good idea, because the Cash Ticks option is basically the same.

**Comment by SzabKel** [comment]
What do you think about the following: If the notification goes off, the first time it does we add +15s for the next notification, if the notification does not go off, we reset the timer. Something like this: Warning 1st time(+15 to the next notif), after 15 sec the 2nd warning goes off, after 30 sec the next one...etc.

**Comment by obrakmann** [comment]
@SzabKel: I like your last suggestion. Sounds like a good solution.

**Comment by pchote** [comment]
IMO the simplest and best fix is to set the notification up the same way as the new insufficient funds notification, triggered on the harv unloading being blocked.

**Comment by LipkeGu** [comment]
@pchote :+1:

**Comment by LipkeGu** [comment]
I compared the TS silo logic and the one from OpenRA and indeed the Logic from openra is different as the original silo logic from TS. Fixing the OpenRA Logic should avoid this silo spam

1. Refinery is empty ... -> http://imgur.com/Dl7e5Ve
2. Refinery is get filled up -> http://imgur.com/SdV0PFH
3. but silo is empty -> http://imgur.com/IwPZXA8

**Comment by MustaphaTR** [comment]
I find this shared storage logic more. This is also like that in D2K. Making them load to the Refinery first has an annoying problem that if u lose it u lose every money u have. But in current OpenRA logic if you lose Refinery u lose only money that is refinery which leaves some money is Silos.

I'm not sure if this is really working like that tho. Do we lose money when we lose Ref in OpenRA? This does happen in TS and RA2(Ares) and quite annoying with their Silo Logic.

**Comment by abcdefg30** [comment]
@SzabKel what's the status here?

**Comment by SzabKel** [comment]
@abcdefg30 I think this should be closed, the code here is not needed and I don't think I will work on it anymore.

**Pull request closed without merging**
