### PR TITLE
Grant Condition Integers

### PR DESCRIPTION
**Pull request by atlimit8**
This replaces #12925 (Plug Slot, Health, & Damage State Condition Variables) for laying the groundwork for sharing integer values via conditions. This PR uses pseudo-property conditions to utilize the condition linter and organize multiple attributes of a trait with a common prefix identifying the trait without making the modder name a condition for each integer/Boolean value shared. As an example, this PR replaces `TimedConditonBar` with `ConditionBar` and exposes the timers of a few traits to demonstrate. `ConditionBar` also shows using `ConditionExpression`s as dynamic field values, which I would like to apply to `TurnSpeed`, `Speed`, `Power`, etc.

---
### Future Direction:
The reason I had #12925 expose health was to do this: `Power: 200 * health / health.max`, replacing `ScalePowerWithHealth` and making it possible to apply the same thing to values of fields in other traits. Being able to set `Speed` and `TurnSpeed` in `Mobile` separately as `ConditionExpression`s would allow for deploying infantry to turn without being able to move (`Speed: speed-value * !deployed`) without adding custom logic such as a `MovementSpeedMultiplier` and maybe a `TurnSpeedMultiplier`.

Using `enum`s to select exposed properties allow for exposing a range of values without a lot of MiniYaml. For example, expressions like `health.damage >= DamageStates.heavy` are fairly clear, and can be given its own name using `GrantCondition`.
```yaml
	Health:
		Condition: health
		ConditionProperties: damage #, max
		ConditionDamageStateConstants: critical # all under DamageStates condition
	GrantCondition@CRITICAL:
		RequiresCondition: health.damage >= DamageStates.critical
		Condition: criticalspeed
		GrantPermanently: true # NOTE: must be added to GrantCondition
...

       
	Health:
		Condition: health
		ConditionProperties: damage
		ConditionDamageStateConstants: heavy, critical # all under DamageStates condition
	...
	SpeedMultiplier@DAMAGED:
		RequiresCondition: health.damage == DamageStates.heavy
		Modifier: 80
	SpeedMultiplier@CRITICAL:
		RequiresCondition: health.damage == DamageStates.critical
		Modifier: 60
```

### CODE REVIEW

**Comment by pchote** [comment]
It will probably take a while for me to chew through the fine details of this PR (especially since I want to prioritize finishing my mod support PRs and then wresting the PR queue to something managable), but my initial reactions based on the PR description are:

* I like where you're going with this, and it will be a really powerful feature if we do it right.
* Before we go any further down the rabbit hole we *really* need to think about how to and then implement auto-generated documentation for the ConditionProperties, etc, that each trait exposes.  Maybe not in this PR, but certainly no later than the next one.

**Comment by GraionDilach** [comment]
I only skimmed through the code so far, but my initial impression is good. This instantly got me reminded to the Generals EMP logic with it's SuppressionThreshold feat, which is nice and while that can be done in a way already, it'd look a bit messy.

I have to let the code contents sink in fora  while, because i need some time to pick up the direction's mindset.

**Comment by pchote** [comment]
Depends on #13074.

**Comment by reaperrr** [comment]
#13074 was merged.

**Comment by pchote** [comment]
Continuing from our earlier discussions, now that we have a plan for our naming conventions I think it would be best if the yaml interface mirrored what we do for conditions.  For example:

```
 PortableChrono:
 	ChargeDelay: 300
 	ChargeProgressVariable: charge-progress
 	ChargeDurationVariable: charge-duration
ConditionBar@PORTABLE_CHRONO:
	ValueVariable: charge-progress
	MaxValueVariable: charge-duration
	Color: FF00FF
```
```
ExternalCondition@INVULNERABILITY:
 	Condition: invulnerability
 	TimerValue: invulnerability-remaining
 	TimerDuration: invulnerability-duration
ConditionBar@INVULNERABILITY:
	ValueVariable: invulnerability-remaining
	MaxValueVariable: invulnerability-duration
```

This makes the code self documenting, and removes the overheads of having a special dot syntax.
For the Health example I don't think we gain much from the special syntax over using regular conditions:
```
Health:
	UndamagedCondition: no-damage
	LightDamageCondition: light-damage
	...
	CriticalDamageCondition: critical-damage
GrantCondition@CRITICAL:
	RequiresCondition: critical-damage
	Condition: criticalspeed
	GrantPermanently: true # NOTE: must be added to GrantCondition
```

**Comment by pchote** [comment]
@atlimit8: What do you want to do here? This has been a couple of months without any further activity.

**Comment by pchote** [comment]
This implicitly depends on #13719.

**Comment by pchote** [comment]
#13719 has been merged.

**Comment by pchote** [comment]
This has been inactive for a couple of months, so moving to the Future milestone and closing to help clean up the PR queue.

**Pull request closed without merging**
