### PR TITLE
Map update: Symmetrification of some popular maps

### PR DESCRIPTION
**Pull request by psydev**
- Rogue States, Manufacturing Consent and Necessary Illusions are now near-perfectly symmetrical. Hopefully this will make them more appealing for tournament play. Their overall form hasn't changed much, but they had some lines redrawn and a general cleanup. Necessary Illusions is now a temperate tileset because people complained the snow tileset hurts their eyes.
- Letters from Lexington was re-added after symmetrification and some minor layout adjustments for playability and fairness, including removal of viceroids due to their new "roaming" behaviour.

Link to maps at Resource center:
Necessary Illusions http://resource.openra.net/maps/11716/
Manufacturing Consent http://resource.openra.net/maps/11715/
Rogue States http://resource.openra.net/maps/11098/
Letters from Lexington http://resource.openra.net/maps/11721/

### CODE REVIEW

**Comment by psydev** [comment]
Pleas, please merge this before next release.

**Comment by obrakmann** [comment]
I only looked at Letters from Lexington, and I didn't even look very hard, but still found four glaring tiling errors. In this state this will not make the release.

screenshot from 2016-05-03 14 49 31
screenshot from 2016-05-03 14 49 43
screenshot from 2016-05-03 14 49 54
screenshot from 2016-05-03 14 49 58

**Comment by psydev** [comment]
I fixed the tiles you pointed out in Letters from Lexington and uploaded the map to Resource (and updated the link above), but I'm not sure how add the commit into this PR on github.

**Comment by Mailaender** [comment]
You could have used `git amend` to just update the previous commit. Now with this merge commit you can clean up things with https://help.github.com/articles/about-git-rebase/

**Comment by pchote** [comment]
It might be best for someone more familiar with git to create a new PR with the latest versions of the maps.  That's what we did for @SoScared's RA maps.

**Comment by abcdefg30** [comment]
Superseded by #11443.

**Pull request closed without merging**
