### PR TITLE
Fixed a NullReferenceException in WorldTooltipLogic

### PR DESCRIPTION
**Pull request by Mailaender**
Found by Coverity Scan. Introduced by https://github.com/OpenRA/OpenRA/pull/6613. Not sure how likely it is to happen.

### CODE REVIEW

**Comment by penev92** [comment]
I'd say highly unlikely, but we do have `o == null` checks around there, so...
:+1:

**Comment by obrakmann** [comment]
Please fix [line 63](https://github.com/OpenRA/OpenRA/pull/8329/files#diff-6ab1d7d9150bf2c10e6c23e3a85bb80dR63) as well then.

**Comment by Mailaender** [comment]
Done.

**Comment by obrakmann** [comment]
Thanks. :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/2e87c22ac018aa1fff9aa777afe94908fedd21f2%5E...2e87c22ac018aa1fff9aa777afe94908fedd21f2)

**Pull request merged**
