### PR TITLE
Disable DetectCloaked on low power (TD)

### LINKED ISSUE #12346: Comm and Advanced Comm Center detect stealth when low power
In TD the  the Communication Center and Advanced Communication Center still detect stealth when the player is in low power.
I assume this isnt intended

### PR DESCRIPTION
**Pull request by Smittytron**
Closes #12346

### CODE REVIEW

**Comment by FrameLimiter** [comment]
I think the TMPL needs to be included in this as well. Also probably the ATWR & OBLI as they become disabled when in low power.

**Comment by MustaphaTR** [comment]
> Also probably the ATWR & OBLI

I agree with TMPL, not sure about ATWR and OBLI, we don't disable it for Tesla Coil on RA.

**Comment by pchote** [comment]
> we don't disable it for Tesla Coil on RA.

We should fix that too, but it would be better to address that in its own PR.

**Review by reaperrr — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a642cf58164d5c3ebc99169f8102f8f95193f5b4...7983f666d64e1191c006f0d4d76a12d922f8ae68)

**Pull request merged**
