### PR TITLE
Add new d2k mod logo

### LINKED ISSUE #13121: Missing high resolution and source artwork for D2K mod logo
We have two problems with the D2K logo:
* The sources for the current version were not added to the [artwork source repository](https://github.com/OpenRA/ArtSrc/tree/master/d2k).  The moons are noticeably different.
* The logo was created in 2D, and is too small to use for native system icons for the new mod launchers.  OSX requires sizes rendered up to 1024px for best results, and even windows wants at least a 256px version.  The largest version we have is ~110px.

The most efficient approach will be to recreate the logo in 3D so that we can render out the resolutions we need.

### PR DESCRIPTION
**Pull request by pchote**
This adds Warman's new logo to the d2k loadscreen and packaging.  Closes #13121.

https://github.com/OpenRA/ArtSrc/tree/d2k-logo is ready to merge onto the artsrc master once this is done.

I have tested that this works correctly on all platforms, but if you want to try for yourself there are packages for [windows](https://www.dropbox.com/s/o4s0ueuq6c0juhy/OpenRA-logotest-201704229.exe?dl=1), [macOS](https://www.dropbox.com/s/qtnytok77iw00qt/OpenRA-logotest-201704229.dmg?dl=1), and [Debian/Ubuntu](https://www.dropbox.com/s/dhnixjc1so8e8yy/openra_logotest.201704229_all.deb?dl=1).

### CODE REVIEW

**Comment by pchote** [comment]
I just noticed that I wasn't using the latest version of the logo on the loadscreen.  Fixed here, but not in the test packages.

**Comment by pchote** [comment]
Rebased.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/87bf984915ab01b9469985198ec1090713b052fb...bf141550ca2cf900273cf175f8a91a661b144a25)

**Pull request merged**
