### PR TITLE
Fix the debris spawned when walls are destroyed in d2k

### PR DESCRIPTION
**Pull request by abcdefg30**
Looks like this on bleed:
https://www.dropbox.com/s/790kwftd2x4mfcv/d2kwalls.gif?dl=0 (File too big to upload it on github).

The debris configuration I added is taken from `^Defense`.

(Discovered by my brother, btw. ;))

### CODE REVIEW

**Comment by MustaphaTR** [comment]
Not, sure. IIRC that happens in original game too. Someone needs to check this.

**Comment by reaperrr** [comment]
I think this is good enough as fix for stable :+1: 

For the next release cycle we should probably take another look at debris count in general, because I think it scaled with value or occupied cells in D2k.

**Comment by GraionDilach** [comment]
:+1:

**Comment by pchote** [comment]
I second @reaperrr's suggestion to revisit debris for the next release cycle.  There is more to it than just count: the debris in the original also had a probability of bouncing like the TS disk thrower disks.

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/67e8bd52e6f3873b4bdcdbb899fd83a554f4ecb6)

**Pull request merged**
