### PR TITLE
Mobile and Move refactor

### PR DESCRIPTION
**Pull request by reaperrr**
Rebased and cleaned the rest from #7565.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Did you accidentally pushed this into an OpenRA/OpenRA branch too? It got a mobile-refactor1 branch... https://github.com/OpenRA/OpenRA/tree/mobile-refactor1

**Comment by reaperrr** [comment]
Hm yeah, seems something went wrong with my initial push. Removed that from OpenRA/OpenRA.

**Comment by reaperrr** [comment]
This stuff is mostly out of my league, so I'd actually prefer if someone with better understanding of the code ( @pchote ? @RoosterDragon ? ) took over (provided we still want this to begin with, now that we have #9141 and its dependencies).

**Comment by RoosterDragon** [comment]
We still want most of this, since it's nice cleanup (although #9141 would indeed negate a few small refactorings) so we should keep this around until we can iron out the few remaining issues.

**Comment by reaperrr** [comment]
I'm leaving this as-is since I'm afraid I might break something if I try to rebase this.

**Comment by RoosterDragon** [comment]
Actually - on taking a second look at this it's probably rotted too much to justify the effort to rebase it in. :/

Unless somebody else desperately wants to grab it I think you could safely close this, @reaperrr.

**Comment by reaperrr** [comment]
Ok. I won't delete the branch for now so anyone still interested in it can scavenge for salvagable bits.

**Pull request closed without merging**
