### PR TITLE
Some more renaming from "race" to "faction"

### PR DESCRIPTION
**Pull request by penev92**
Next step toward #7873.
This takes care of the last occurrences of "race" in class member names (except `PlayerProperties.Race`, which will stay until the release is out, I guess).
Split into nice small commits for easy reviewing.

### CODE REVIEW

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by Mailaender** [comment]
This needs a rebase and rule re-run as I merged https://github.com/OpenRA/OpenRA/pull/8912 before this. Sorry.

**Comment by reaperrr** [comment]
Rebase doesn't seem necessary, but TS GDI repair bay yaml needs to be updated.

**Comment by penev92** [comment]
Updated with the TS repair pad.

**Comment by Mailaender** [comment]
Thanks. Let's get this over with.

**Pull request merged**
