### PR TITLE
Fixed Tiberian Sun multiplayer spawn and waypoints

### PR DESCRIPTION
**Pull request by Mailaender**
I redid them based on `blank01.tem`:

image

image

as the ones copied from RA1 were in the wrong shape, tilesize and palette which undid the transparency effect as depicted in http://www.ppmforums.com/viewtopic.php?p=530427#530427.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Awesome! :+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by OmegaBolt** [comment]
These look better but I honestly prefer the way Final Sun / Alert 2 simply displays the number on the waypoint image. When you're working with 100 waypoints on a map you've really gotta be able to see what number they are immediately.

waypoints

**Comment by chrisforbes** [comment]
No reason why we can't show the waypoint names, but that's out of scope for
this fix.

**Pull request merged**
