### PR TITLE
Link the server hosting Patreon

### PR DESCRIPTION
**Pull request by Mailaender**
This will give @Baxxster some more attention. See https://github.com/sponsors Sadly this doesn't preview things. It will look like this:

image

### CODE REVIEW

**Comment by pchote** [comment]
TBH i'm not comfortable with this.

I've been happy to direct people to baxxster when they approach us informally on discord etc, but if we are going to formally advertise sponsorship options then we really need to discuss this properly and decide who/how funding is split.

**Comment by Mailaender** [comment]
If you want your share of money, then I suggest you https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-user-account

**Comment by Mailaender** [comment]
https://discord.com/channels/153649279762694144/256063291330265090/1048988742565777419 was officially announced by @abcdefg30.

**Comment by abcdefg30** [comment]
Fwiw the first announcement of this in Discord was way back already. Is there a way to change the "Sponsor this project" text?

**Comment by Mailaender** [comment]
No. That stems from GitHub.

**Comment by ThomasChr** [comment]
About discussing how the funding is split I totally agree that the funding goes torwards all those people who are giving their money for OpenRA. So thats @Baxxster for the servers and I remember giving @Mailaender some money for the certificats.
If there really would be enough money to provide for the servers and the certs, then we can think about giving all those millions to all the contributors and making all of us rich!
But I doubt that will be anytime soon.

Maybe it would be best if we open up an "official" Patreon account - which (at the moment) - gives all the raised funds to Baxxster until his expenses are covered? I don't mind Baxxster's Patreon Account at all, but it doesn't look like the "official OpenRA Patreon Account", and it's stated there that the money will be primarily for the OpenRA Servers. It could be that some people just don't care enough about maintaining Servers for OpenRA, but would give money to maintain the source code, or even get Tiberian Sun going.

Also the official account could be linked on the OpenRA Download Page ( https://www.openra.net/download ).
And, as stated in discord, I would like for the Patreon Accounts to start with 1 €. Some people (like me) don't care about the Perks they're getting, they just want to help. But at the moment Baxxsters Patreon starts at 5 €, which is a little bit too much for me.

**Comment by Mailaender** [comment]
I have set up https://opencollective.com/openhv now, and you won't get rich. Almost nobody donates anything.

**Comment by ThomasChr** [comment]
At the moment you are getting an estimated 4$ a month. That could be enough for a small coffee, don‘t get greedy ;-)

**Review by PunkPun — APPROVED** [review]

**Review by ThomasChr — APPROVED** [review]
I‘m having no problems with it beeing merged

**Comment by Mailaender** [comment]
There are no dependencies for this.

**Comment by PunkPun** [comment]
I believe this was the dependency https://discord.com/channels/153649279762694144/388282819371204608/1115251670251737130

**Comment by Mailaender** [comment]
I think you are overcomplicating this.

**Comment by PunkPun** [comment]
this PR was accidentally merged as part of #21427

**Comment by Mailaender** [comment]
I thought it was cherry picked on purpose.

**Pull request closed without merging**
