### PR TITLE
Fetch battlefield news once per game launch.

### LINKED ISSUE #9843: Battlefield News does never update
It never did. I can only refresh by deleting the news yaml. Might be a localized (running de_DE Linux) Mono problem with dates.

image

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27867553-battlefield-news-does-never-update?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9843.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1: . This will also make the news post available earlier to all players, which is another plus.

**Comment by penev92** [comment]
:+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c68c078cb8682ac2953bdc6a442b147056e7312e)

**Comment by Mailaender** [comment]
Finally it works. Thanks.

**Pull request merged**
