### PR TITLE
Fix unrelated CVE warnings

### PR DESCRIPTION
**Pull request by Mailaender**
that happen because .NET changed `<NuGetAuditMode>` to `all`. See https://github.com/OpenHV/OpenHV/actions/runs/11987849692/job/33422489150 for example.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Do you still get warnings after updating the package but using the new mode? It seems valuable to use the new setting if we can.

**Comment by Mailaender** [comment]
You mean I should skip https://github.com/OpenRA/OpenRA/pull/21657/commits/d866823d0548e3fa1877940a1b3c1500816d455b?

**Comment by RoosterDragon** [comment]
> You mean I should skip [d866823](https://github.com/OpenRA/OpenRA/commit/d866823d0548e3fa1877940a1b3c1500816d455b)?

Yes, I think getting these warnings is valuable.

**Comment by Mailaender** [comment]
Okay. Kept the audit mode covering also indirect dependencies. This is not fixable downstream because the setting is at project level. https://github.com/OpenHV/OpenHV/pull/1231 solved it by downgrading Windows and therefore the .NET version.

**Review by RoosterDragon — APPROVED** [review]

**Comment by michaeldgg2** [comment]
If newer version of the SDK is bothering you, you can force different in `global.json`, you don't have to downgrade entire Windows version because of that.

https://learn.microsoft.com/en-us/dotnet/core/tools/global-json

**Comment by Mailaender** [comment]
I haven't tried that, but I assume that would only change the targeted SDK not the default setting of `<NuGetAuditMode>` as .NET 9 would still be responsible for the compilation.

**Comment by michaeldgg2** [comment]
No, if you force a specific version of SDK via `global.json`, you need to have that version installed, otherwise the .NET CLI command will fail to run (taking into account `rollForward` configuration of course).

> In CI (continuous integration) scenarios, however, you typically want to specify an acceptable range for the SDK version that is used. The global.json file has a rollForward feature that provides flexible ways to specify an acceptable range of versions.

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3acff85712383e4620f09a2c00a6c09428209482...bc80929bc3f3121f70b69a61a30a8ffe721b85e0)

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2e7e0f6f06d968c26385f4fb17fb5fa25969eff5...521590f25250b8d286983b5f6abc301cccac554a)

https://github.com/OpenRA/OpenRA/commit/f316d4c7571fd11855445c3cf48ffe90859d6eb3

**Pull request merged**
