### PR TITLE
Fix subcell crusher logic.

### LINKED ISSUE #4826: Only one infantry unit can move into a cell with a crushable actor at a time
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1435883-only-one-infantry-unit-can-move-into-a-cell-with-a-crushable-actor-at-a-time?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
This PR cleans up the last pieces missed by #17222 to fix #4826.

### CODE REVIEW

**Comment by teinarss** [comment]
Did notice while testing that not the whole squad will move to the cell.
Often one or more will stay at the previous cell.

**Comment by pchote** [comment]
Are you sure that isn't the standard bogus nearenough behaviour that #17541 aims to fix?

**Review by Mailaender — APPROVED** [review]
Looks sane.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5cf2a020d39cbee4fde560e7be37aa94b095740d...96f9421a857ef180d19f1657e9fb2efceaeb63e2

**Pull request merged**
