### PR TITLE
Check for dead destination airfield in ReturnToBase

### LINKED ISSUE #13147: Aircraft reservation crash
```
Attacque Superior Mod at Version DEV-VERSION
on map 264bd672f076b8be94fc0e8def7c54124b5e0611 (Blank Testmap Mk IV (Ore+Gold) by Graion Dilach).
Date: 2017-04-17 16:33:47Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (faairc 854 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in d:\OpenRA-AS-dev\OpenRA.Game\TraitDictionary.cs:line 83
   at OpenRA.TraitDictionary.GetOrDefault[T](Actor actor) in d:\OpenRA-AS-dev\OpenRA.Game\TraitDictionary.cs:line 94
   at OpenRA.Actor.TraitOrDefault[T]() in d:\OpenRA-AS-dev\OpenRA.Game\Actor.cs:line 248
   at OpenRA.Mods.Common.Traits.Reservable.IsReserved(Actor a) in d:\OpenRA-AS-dev\OpenRA.Mods.Common\Traits\Buildings\Reservable.cs:line 64
   at OpenRA.Mods.Common.Activities.ReturnToBase.Calculate(Actor self) in d:\OpenRA-AS-dev\OpenRA.Mods.Common\Activities\Air\ReturnToBase.cs:line 52
   at OpenRA.Mods.Common.Activities.ReturnToBase.Tick(Actor self) in d:\OpenRA-AS-dev\OpenRA.Mods.Common\Activities\Air\ReturnToBase.cs:line 117
   at OpenRA.Activities.Activity.TickOuter(Actor self) in d:\OpenRA-AS-dev\OpenRA.Game\Activities\Activity.cs:line 175
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in d:\OpenRA-AS-dev\OpenRA.Game\Traits\ActivityUtils.cs:line 37
   at OpenRA.Actor.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\Actor.cs:line 163
   at OpenRA.World.Tick() in d:\OpenRA-AS-dev\OpenRA.Game\World.cs:line 342
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 587
   at OpenRA.Game.LogicTick() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 611
   at OpenRA.Game.Loop() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 738
   at OpenRA.Game.Run() in d:\OpenRA-AS-dev\OpenRA.Game\Game.cs:line 778
   at OpenRA.Program.Run(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Support\Program.cs:line 133
   at OpenRA.Program.Main(String[] args) in d:\OpenRA-AS-dev\OpenRA.Game\Support\Program.cs:line 40
```

Best I could find is #11947?

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #13147.

### CODE REVIEW

**Review by phrohdoh — APPROVED** [review]
LGTM

**Comment by reaperrr** [comment]
Maybe fix it here as well, just in case?
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/HeliReturnToBase.cs#L46

**Comment by obrakmann** [comment]
Makes sense, added

**Comment by reaperrr** [comment]
Unless I'm missing something,

https://github.com/obrakmann/OpenRA/blob/b50f15c645303294313aa3bf4dc4996c352514dc/OpenRA.Mods.Common/Activities/Air/HeliReturnToBase.cs#L55

can return a dead actor as well, so I think we should exclude those.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/bf00831cc347c6df09d521b4c884560edae069b7...1b8014e7fde7deeceffe432b5f9dba874f809106)

**Pull request merged**
