### PR TITLE
Add more map editor hotkeys

### PR DESCRIPTION
**Pull request by dragunoff**
Adds hotkeys to map editor tabs (Tiles, Actors, Overlays, History) and overlay toggles (Grid, Buildable Terrain).

image

Depends on #20028 (not really dependent on it, but the copy, undo/redo keys are)

### CODE REVIEW

**Review by pchote — DISMISSED** [review]
LGTM. Tested on macOS and Linux.

**Comment by pchote** [comment]
Needs a rebase now.

**Comment by dragunoff** [comment]
Rebased.

**Review by abcdefg30 — DISMISSED** [review]

**Review by PunkPun — COMMENTED** [review]
TD map editor seems to be working very well, however that is not true in all 3 other mods. Overlay hotkeys do nothing and one can't even open the overlay checkbox panel

**Comment by dragunoff** [comment]
Rebased and fixed the oversight of not adding the keyhandler to the common editor yaml (https://github.com/OpenRA/OpenRA/pull/20029#pullrequestreview-1000087034).

**Review by PunkPun — APPROVED** [review]
lgtm

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c5aee354d8d08cc39da241b7a4554b6c99dcf46d...e6ac43928440fded05034746c10498d368da03cc)

**Pull request merged**
