### PR TITLE
disable beacon button if game is in single player mode

### LINKED ISSUE #8535: UI: single player missions should not have a button for beacon placement
there's nobody who can see the signal

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22664037-ui-single-player-missions-should-not-have-a-button-for-beacon-placement?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by small-fishes**
Check to see if the game is in single player mode and if it is disable the beacon button.

Closes #8535

### CODE REVIEW

**Comment by pchote** [comment]
I like to use beacons to point out crates to myself in singleplayer, so that I can select a unit and then jump immediately back to order them to pick it up.

**Comment by Mailaender** [comment]
No consensus. Closing both this and the issue then. Sorry.

**Comment by pchote** [comment]
I intended that as a discussion point (written wearing my occasional-player hat) rather than a review comment!  If my use case is out of the ordinary or something we don't want to support then there may well be a case for disabling this in singleplayer (note: this includes both skirmishes as well as missions).

**Comment by abcdefg30** [comment]
> 14:12 (+Phroh|work) #8967 was not nearly given enough time or discussion
14:13 (+Phroh|work) Can someone reopen that please?
14:13 (+Phroh|work) I'm all for that PR.

**Comment by abcdefg30** [comment]
Personally I'm not really convinced, but I'm not using beacons in singleplayer either.
Code looks good anyway and this works ingame. :white_check_mark: 

But we probably want to gray the button out (or sth similar), otherwise this could look like a bug to users.

**Comment by GraionDilach** [comment]
Beacons would be useful to mark mission objectives as well.  My vote goes for keep.

**Comment by abcdefg30** [comment]
> Beacons would be useful to mark mission objectives as well. My vote goes for keep.

That can be done via lua and shouldn't be affect by this change.
(Assuming you refer to singeplayer missions/campaigns.)

**Comment by MicroJOo** [comment]
keep

**Comment by nalidixic** [comment]
"But we probably want to gray the button out (or sth similar), otherwise this could look like a bug to users." 

What about just removing the button all together instead of disabling it in single player mode?

**Comment by abcdefg30** [comment]
> What about just removing the button all together instead of disabling it in single player mode?

Hm, you could try using `IsVisible` instead of `IsDisabled`, yeah.

**Comment by pchote** [comment]
That will look weird in D2K, which has the beacon button near the middle.

**Comment by dan9550** [comment]
as @pchote said i don't mind using beacons in single player also just for little reminders and such.

**Comment by nalidixic** [comment]
You guys won't hurt my feelings if you close this... 

This seems like it's just not an issue to most people.

I'll find another bug to work on.

**Comment by Phrohdoh** [comment]
Now closing with a pretty clear consensus.

**Pull request closed without merging**
