### PR TITLE
Update D2k map pool

### PR DESCRIPTION
**Pull request by Porenutak**
Adds some popular maps to d2k map pool. Based on Discord discussion here:
https://discord.com/channels/153649279762694144/632295260428566529/1037104941539532891

map list:
- Side Step Dune 03
- Sunstroke - D2k
- Spice mesa
- Source
- Stone Plateaus

Maps are updated to map format 12.

### CODE REVIEW

**Comment by PunkPun** [comment]
Does Sunstroke need D2K to be mentioned in the title? Same with Side Step

**Comment by Porenutak** [comment]
Probably no. Map authors named them like that. Do you want remove that  part?

**Comment by PunkPun** [comment]
We could ask the authors. I think it's a bit weird and kinda redundant to have D2K in the title when the map is for D2K and only played on D2K

**Comment by Porenutak** [comment]
Names updated

**Review by PunkPun — COMMENTED** [review]
The original Sidestep was created by SoScared, and Sunstroke by PizzaAtomica. I think it would be unfair to not mention them in the credits

Other than that LGTM

**Comment by dragunoff** [comment]
Can we also change the filenames so that they are all kebab-case?

```
sidestep03.oramap
source.oramap
spice-mesa.oramap
stone-plateaus.oramap
sunstroke.oramap
```

Also that "03" on sidestep looks weird but I guess it's OK.

**Comment by Porenutak** [comment]
updated credits and names. For some reason Github always rename **source.oramap** to **Source.oramap**

**Review by PunkPun — DISMISSED** [review]

**Comment by abcdefg30** [comment]
> updated credits and names. For some reason Github always rename source.oramap to Source.oramap

Renamed it to `source.oramap`. Git is a bit tricky there.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9816888322f56c7199dce000495440f003fc5fbf...39fda3d48e8ba28f42cae07afd34d767d32900d2)

https://github.com/OpenRA/OpenRA/commit/9bb0409f19e58fb73b21dac8ecf6e5851cf811a8

**Pull request merged**
