### PR TITLE
Fix bogus owner check in Lua API production code

### LINKED ISSUE #8462: The map script has encountered a fatal error
When playing GDI mission 3, where you have to destroy the SAM sites (secondary objective) and the Nod base, my game ended, when a fatal error was encountered. It seems that I killed all units on the map but not all buildings were destroyed yet.
Here's lua.log:
```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   v OpenRA.Scripting.ScriptContext.FatalError(String message)
   v OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   v OpenRA.World.Tick()
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   v OpenRA.Game.LogicTick()
   v OpenRA.Game.Loop()
   v OpenRA.Game.Run()
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)

Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   v OpenRA.Scripting.ScriptContext.FatalError(String message)
   v OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   v OpenRA.World.Tick()
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   v OpenRA.Game.LogicTick()
   v OpenRA.Game.Loop()
   v OpenRA.Game.Run()
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)

Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   v OpenRA.Scripting.ScriptContext.FatalError(String message)
   v OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   v OpenRA.World.Tick()
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   v OpenRA.Game.LogicTick()
   v OpenRA.Game.Loop()
   v OpenRA.Game.Run()
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)

Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   v OpenRA.Scripting.ScriptContext.FatalError(String message)
   v OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   v OpenRA.World.Tick()
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   v OpenRA.Game.LogicTick()
   v OpenRA.Game.Loop()
   v OpenRA.Game.Run()
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)


```

Screenshot of error:
gdi-fatal

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21561265-the-map-script-has-encountered-a-fatal-error?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9863: CnC64 Special Ops GDI01 crashes after training an engineer from a captured Hand of Nod
The title says it all. After capturing the Hand of Nod to the east of the player's base, I tried to train an engineer there. The engineer popped out properly, and the game crashed immediately after.
The corresponding log entry says
"Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   в OpenRA.Scripting.ScriptContext.FatalError(String message)
   в OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   в OpenRA.World.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)"

I guess one should fall back to simple move if no AttackMove is possible...

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27886827-cnc64-special-ops-gdi01-crashes-after-training-an-engineer-from-a-captured-hand-of-nod?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #9863.
Fixes #8462.

### CODE REVIEW

**Comment by abcdefg30** [comment]
The same happens at #8462, i guess.
But anyway, isn't this just hiding another bug?
We shouldn't even run that function if a player builds a unit.

**Comment by obrakmann** [comment]
Eh, you're right. For one, I didn't even remember that this check existed, and also it didn't work in the first place.

I have no idea why I wrote it that way back then. I'm sure it seemed like a good idea at that time. Updated.

**Comment by penev92** [comment]
:+1:

**Comment by pchote** [comment]
I can't repro the crash in CnC64 on the current prep branch, but this makes the code more correct so :+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fa8b3aaf1e6a3e20f27673710063e4d426f6ce87)

**Pull request merged**
