### PR TITLE
Finish reverting multiline support for SimpleTooltipLogic

### PR DESCRIPTION
**Pull request by atlimit8**

### CODE REVIEW

**Comment by pchote** [comment]
This still doesn't look right in the editor

**Comment by pchote** [comment]
```diff
paul@Mjolnir:OpenRA+pr/10057$ git diff ff6dbde8d766fa07b53adc8851e9f6208f6e6cb9 7a07c90b093a7906f83bf6ceccf9c6a651dc0aa4 -- OpenRA.Mods.Common/Widgets/Logic/SimpleTooltipLogic.cs
diff --git a/OpenRA.Mods.Common/Widgets/Logic/SimpleTooltipLogic.cs b/OpenRA.Mods.Common/Widgets/Logic/SimpleTooltipLogic.cs
index a33fc14..d63e2d1 100644
--- a/OpenRA.Mods.Common/Widgets/Logic/SimpleTooltipLogic.cs
+++ b/OpenRA.Mods.Common/Widgets/Logic/SimpleTooltipLogic.cs
@@ -13,7 +13,7 @@
 
 namespace OpenRA.Mods.Common.Widgets.Logic
 {
-       public class SimpleTooltipLogic
+       public class SimpleTooltipLogic : ChromeLogic
        {
                [ObjectCreator.UseCtor]
                public SimpleTooltipLogic(Widget widget, TooltipContainerWidget tooltipContainer, Func<string> getText)
@@ -26,15 +26,17 @@ public SimpleTooltipLogic(Widget widget, TooltipContainerWidget tooltipContainer
                        tooltipContainer.BeforeRender = () =>
                        {
                                labelText = getText();
-                               var textWidth = font.Measure(labelText).X;
-                               if (textWidth != cachedWidth)
+                               var textDim = font.Measure(labelText);
+                               if (textDim.X != cachedWidth)
                                {
-                                       label.Bounds.Width = textWidth;
-                                       widget.Bounds.Width = 2 * label.Bounds.X + textWidth;
+                                       label.Bounds.Width = textDim.X;
+                                       widget.Bounds.Width = 2 * label.Bounds.X + textDim.X;
+                                       label.Bounds.Height = textDim.Y;
+                                       widget.Bounds.Height = 4 * label.Bounds.Y + textDim.Y;
                                }
                        };
 
                        label.GetText = () => labelText;
                }
        }
-}
\ No newline at end of file
+}
```

Those two height changes need to be removed too.

**Comment by atlimit8** [comment]
Changed and that was all I was as still changed by #9925 or #9715.

**Comment by pchote** [comment]
Yup, looks better now :+1:

**Comment by abcdefg30** [comment]
Didn't spot anything either. :+1:

**Pull request merged**
