### PR TITLE
Add hover and disable states to dropdown button separator

### LINKED ISSUE #9392: Disabled dropdown button separator is using the enabled variant
Noticed during testing https://github.com/OpenRA/OpenRA/pull/9387 when seeing the two buttons side by side:

image
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26814614-disabled-dropdown-button-separator-is-using-the-enabled-variant?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9392.

### CODE REVIEW

**Comment by dragunoff** [comment]
Wouldn't it be better to handle this similarly to button states? Instead of creating properties for each state, just pass an image collection and rely on hard-coded state suffixes: `separator`, `separator-disabled`, `separator-hover` (with fallback to the base image if variants are not defined). The only place where a different separator style is used is for RA observer UI. So it can become just this:
```yaml
# define the collection
dropdown-observer:
	Inherits: ^Dialog
	Regions:
		separator: 769, 258, 1, 19
		separator-hover: 769, 258, 1, 19
		separator-disabled: 769, 386, 1, 19
```
```yaml
# pass it to the widget
	SeparatorCollection: dropdown-observer
```

**Comment by pchote** [comment]
Updated.

**Review by dragunoff — APPROVED** [review]
LGTM :+1:

**Review by abcdefg30 — COMMENTED** [review]
As discussed on IRC: We should either add the missing definitions to RA or remove the duplicates from TS/D2k.

**Comment by dragunoff** [comment]
I've looked at this in a bit more detail (while trying to implement a custom dropdown) and I think a more thorough overhaul is necessary in order to support custom artwork. Namely - the "scrollbar" image part should not be hard-coded. How about we tackle all the image parts in a single collection?

Something along the lines of:
```yaml
dropdown:
	Inherits: ^Dialog
	Regions:
		arrow:
		arrow-hover:
		arrow-pressed:
		arrow-disabled:
		separator:
		separator-hover:
		separator-pressed:
		separator-disabled:
```

**Comment by pchote** [comment]
Honestly, with the large scope and slow speed of progress on the UI scaling changes, i've burnt out of willpower to do any additional work on the UI code in the near future.

This feature isn't needed for Next + 1, so I'll leave it for someone else.

**Comment by dragunoff** [comment]
> 
> 
> As discussed on IRC: We should either add the missing definitions to RA or remove the duplicates from TS/D2k.

I can take over but please clarify what this means ^

**Pull request closed without merging**
