### PR TITLE
Add some smaller, performance-friendly TS maps

### LINKED ISSUE #12518: Add some performance-friendly TS maps
Most of our currently included TS maps are closer to worst-case in terms of cliffs, bridges/water and size.

We should focus on the following smaller maps next.

FS:
- [x] Tiers of Sorrow (2): Very small, no water, no tunnels. #13941
- [x] They All Float (2): Quite small and no relevant water. #14576
- [ ] Dueling Islands (2): Small 2-player map, water should actually help performance once bridges/domains work better (due to lots of cells the pathfinder doesn't need to consider for most actors).

TS:
- [ ] Limited Access (4): Despite the name, performance should be ok due to medium size, max 4 players <s>and no bridges</s>. #14034
- [ ] Pit or Plateau (4): Similar reasoning to Limited Access.

### PR DESCRIPTION
**Pull request by reaperrr**
Adds 4 of the maps from Shattered Paradise recommended by @ABrandau in #12518.

Enough that this closes #12518, in my opinion.

The Pit (2p) https://resource.openra.net/maps/25956/
Tournament Rift (2p) https://resource.openra.net/maps/25957/
Oasis Trouble (2p) https://resource.openra.net/maps/25993/
Way to Uganda (4p / 2-team-co-op) https://resource.openra.net/maps/25990/

Note: I pulled the spawnpoints on Way to Uganda a bit apart so it *can* be used as 4P-FFA, if players wish to.

### CODE REVIEW

**Comment by ABrandau** [comment]
Think we might need to double check tournament rift, the author says imported by V, but in truth i think it was made by MadHQ , see here https://zombapro.ppmsite.com/index.php?page=Tiberian+Sun

Also a few extra
https://resource.openra.net/maps/26832/
https://resource.openra.net/maps/26835/
https://resource.openra.net/maps/25941/
https://resource.openra.net/maps/26838/

Most of the maps we gathered are from MadHQ

**Comment by GraionDilach** [comment]
Tournament Rift has also been remade by Hogo at a point.

**Comment by ABrandau** [comment]
His layout is different than the one on the resource center, so I would point at MadHQ image

**Comment by reaperrr** [comment]
Fixed TR author.

**Comment by GraionDilach** [comment]
Does any of these maps include veins? IIRC SP axed that feature, but we *will* need veins for all TS maps ultimately.

**Comment by reaperrr** [comment]
I assume you mean for balance reasons?

IMO TS super weapons were more balanced on maps that *didn't* have veins, a cluster + chem missile is much more devastating than a puny ion cannon blast.

Also, snow terrain doesn't support veins AFAIK.

One possible alternative might be to tie the availability of the chem missile to some GDI superweapon (drop-pod reinforcements or C&C3-style space bombardment).
Or we could force Nod players to choose between cluster- and chem missile (or at least force players to build one missile silo for each).

Anyway, the idea of making veins a prerequisite on all maps just doesn't sit well with me. I think we can and should come up with a better solution when the time comes.

**Comment by GraionDilach** [comment]
Hm, I was completely unaware of the snow-maps-lacking-veins stuff. The artworks exist for snow nevertheless, but I haven't checked if they fit to/use the correct palette of the tileset. I also could find topics on PPM where people recolored veins to suit snow terrain - https://ppmforums.com/viewtopic.php?p=201960#201960 - which implies to me that the logic could have worked, but the art became a lousy c'n'p and it went unused.

The thing with veins is that without the explicit maps-must-have-it statement, the vein tech themselves end up more map-situational than navy is, which doesn't sit well with me. Although considering how the whole logic works (just kill the vh monster ASAP and let veins die off thenafter = Nod denied from chems).

Ahwell, balance concerns shouldn't be our ones at this point anyway, TS will need to be revamped after we consider the implementation finished in terms of engine gameplay. Either way, we should still aim to have atleast 33%-40% ratio of our maps with veins for the completionist PvE techrushers. Notsure how 4 veinless map disrupts the WW map balance.

**Comment by ABrandau** [comment]
We axed vein harvesting because its not doable on the engine atm and it also because it is not balanced, and Graion already pointed out, but on the other hand, vein degrowth or resource destruction doesnt work either, so there is no way to implement this even if we wanted to.

imo, the official TS mod should follow the original sadly, maybe just add a method to compensate for the lack of veins, make the chem missile load slowly or have a sub apc show up from time to time to deliver veins, but dont trouble yourself too much by this issue.

**Comment by GraionDilach** [comment]
Anyway, shouldn't the maps be uploaded to the resource center as well?

**Comment by ABrandau** [comment]
I double checked the maps and can confirm they work and the authors are correct, it is nice to have some balanced maps on TS.

**Review by pchote — APPROVED** [review]

**Pull request merged**
