### PR TITLE
Fixed GDI09 gunboat triggers

### LINKED ISSUE #17780: Gunboat Trigger.OnFootprintEntered request
Maby I'm missing something ~~in #17514~~ but it looks like TD gunboats don't Trigger.OnFootprintEntered but e.g. an LST does.

I guess this would be less of a bug and more a feature request?

Testcase:
1.  ~~checkout branch #17514~~
2. launch mission gdi 9 "secure the danube"
3. destroy north/south gunturrets
4. let the gunboat move to west side of the river
5. gunbaot doesn't trigger.

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenRA/OpenRA/pull/17514. Closes https://github.com/OpenRA/OpenRA/issues/17780

### CODE REVIEW

**Review by reaperrr — DISMISSED** [review]

**Comment by Smittytron** [comment]
Tested this. The gunboat turns around, activates the message twice, and isn't removed until it gets a few cells to the east.

**Comment by Mailaender** [comment]
Fixed.

**Review by Smittytron — APPROVED** [review]
Works

**Review by fruestueck — APPROVED** [review]
Works great! Thank you

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/269a8fee6732e9091549592118ae415bb77bda4c...95fb88e1d0c27d4ffbae3d13a1ed21476659b3bd)

**Pull request merged**
