### PR TITLE
make: don't assume luac is installed

### PR DESCRIPTION
**Pull request by clemty**
the diff on this commit looks really weird

### CODE REVIEW

**Comment by abcdefg30** [comment]
> the diff on this commit looks really weird

Try https://github.com/OpenRA/OpenRA/pull/9330/files?w=1

**Comment by Mailaender** [comment]
:+1: Makes sense, but needs someone on Windows to verify it works.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/725a50a67a5cc698db3e0aa5637edb558c7819e4...74077bedcb9e825f0b6a67b9cd4a4057c13b3d60)

**Pull request merged**
