### PR TITLE
D2K - Add more tile types to possible places Crates can spawn

### PR DESCRIPTION
**Pull request by MustaphaTR**
I'm pretty sure crates can spawn on spice, concrete or transition tiles in original game.

### CODE REVIEW

**Comment by ltem** [comment]
It seems that you have to modify this line in the `world.yaml` as well ([LinkToLine](https://github.com/OpenRA/OpenRA/blob/678f9563f6dab8277570ce7c70c88bc7ad56b942/mods/d2k/rules/world.yaml#L75)) 
else no crates will spawn, even if you create a extra concrete map and wait for 20 minutes :)

**Comment by ltem** [comment]
:+1:

**Comment by MustaphaTR** [comment]
Squashed Commits.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/359300071cce73138f6dc7f1fc1bda621a8d25b1...6ef5fec4c1f1e5c00e01119585e279cc4ffd3ad8)

**Pull request merged**
