### PR TITLE
Make spy plane non-targetable

### PR DESCRIPTION
**Pull request by obrakmann**
as often requested on irc and social media

### CODE REVIEW

**Comment by MicroJOo** [comment]
:+1:  thank you @obrakmann

**Comment by penev92** [comment]
:+1:

**Comment by Mailaender** [comment]
Tested with http://resource.openra.net/maps/495/

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/10c7eacd38df4e8a9edc2dc1109ef9f13ff96606...ad230f4a0b9bd14d31ffecd0db34fbc153a651b7)

**Pull request merged**
