### PR TITLE
Fix bug with Crushable moving ally

### LINKED ISSUE #16848: Unloading actors ignore passability (and sometimes infantry)
Regressions from #16698 (only noticed them now, unfortunately):

- actors being unloaded ignore passability, tanks on the southern beach landing spot on RA shellmap - as well as infantry unloaded on bridges - will go to impassable cells and as a consequence get stuck there.

- I saw a tank entering a cell occupied by (allied) infantry at least once.

### PR DESCRIPTION
**Pull request by teinarss**
Closes #16848

### CODE REVIEW

**Comment by reaperrr** [comment]
Unfortunately, the first point of #16848 still happens.

**Comment by pchote** [comment]
Is it correct for CanMoveFreelyInto to not be checking the terrain type? That could explain why units are moving into impassible cells.

**Comment by teinarss** [comment]
Updated

**Comment by reaperrr** [comment]
Can confirm both bugs seem to be gone. 👍 once @pchote is happy with the code changes.

**Comment by pchote** [comment]
This appears to be removing the per-player distinction from `Blocking` - is this intentional? If it is, can we please change it to a bool and drop the `PlayerBitMask` stuff?

**Comment by reaperrr** [comment]
Needs a rebase now.

**Comment by teinarss** [comment]
This is on hold, trying to fix it without removing the PlayerMask etc

**Pull request closed without merging**
