### PR TITLE
Download failure error.

### PR DESCRIPTION
**Pull request by darkademic**
Currently when downloading mod content, if a download fails (e.g. due to 404), there's no error message or indication that anything failed, and it just returns to the downloads list. This adds an error message so it's clear something went wrong and allows retrying.

### CODE REVIEW

**Review by RoosterDragon — APPROVED** [review]

**Review by PunkPun — COMMENTED** [review]
Is there an easy way to test this?

**Comment by RoosterDragon** [comment]
Invert the condition to `== HttpStatusCode.OK` - to pop the error in the success case.

**Comment by anvilvapre** [comment]
Wouldn't it be practical then to also show the status code and message and even log the URL?

**Comment by Mailaender** [comment]
`OnError` already has logging:
https://github.com/OpenRA/OpenRA/blob/0aac5885fb88cbd10256c4b9ba14dd81b8f3cc6f/OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs#L143

**Comment by Mailaender** [comment]
However you are combining a localized string with a non-localized one:
https://github.com/OpenRA/OpenRA/blob/0aac5885fb88cbd10256c4b9ba14dd81b8f3cc6f/OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs#L147
Would be nice if you could complete it.

**Comment by PunkPun** [comment]
that's scope creep, it's an issue that's already present and not introduced by this PR

**Review by PunkPun — APPROVED** [review]

**Comment by PunkPun** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/d380de43882fdf7aef33e9f69a67b6ba03dda69e...81cf909344a99dc3686d27f69a661cc1bb315110)

**Pull request merged**
