### PR TITLE
Expose separate middle and right mouse scroll config.

### LINKED ISSUE #9399: More options for scrolling with the mouse button and scrolling speeds. [$70]
I'm at a loss to explain but scrolling with the middle mouse button doesn't feel right to me. It would be nice to have an customizable option on this, or to simply be able to choose between several options including the right mouse button.

Seeing that there's been quite a few requests in the past on scroll speed options, I'd like to include in this issue as well. Now also with a small bounty;) 

<bountysource-plugin>
---
There is a **[$35 open bounty](https://www.bountysource.com/issues/26824947-more-options-for-scrolling-with-the-mouse-button-and-scrolling-speeds?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #9399 and cleans up some labeling inconsistencies in the Input settings panel.

### CODE REVIEW

**Comment by SoScared** [comment]
It's happening!

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

**Comment by reaperrr** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/e55a457609e1263ade21550ffa30f0b5733e6fda...11e324f36332bc3e801fda533ff130e2b6fa0e89)

**Comment by SoScared** [comment]
Right click scrolling needs to release move command when units are selected.

**Pull request merged**
