### PR TITLE
Fix a collection of color picker issues

### LINKED ISSUE #19471: [bleed] "Preferred color" rectangle thumbnail displays value from settings.yaml, not actual ingame color
It is possible to supply "settings.yaml" with any value for color picker. Current color picker reimplementation modifies this value for the game, but the invalid value is still displayed in "Preferred color" in Settings. However the value is displayed correctly in game lobby.
image
image

Also, when pitch black is added, it is replaced by gray in Color picker example display, but pink is actually selected after Color picker is closed.
image

### PR DESCRIPTION
**Pull request by pchote**
Fixes #19471.

### CODE REVIEW

**Review by dragunoff — DISMISSED** [review]
Fix confirmed :+1:

**Comment by teinarss** [comment]
Bug: Look what happens when picking purple .
colorpicker

**Comment by pchote** [comment]
Pretty sure thats an unrelated issue, but I don't mind scope creeping this into a more general "fix the remaining nits with the color picker" PR. We can do the sound feedback here too.

**Comment by pchote** [comment]
Updated.

**Review by teinarss — APPROVED** [review]

**Comment by teinarss** [comment]
do we need a re-review from one more?

**Review by Smittytron — APPROVED** [review]

**Comment by Smittytron** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/15cd6073bae058b0c2f189fc273dc2359e536b39

**Pull request merged**
