### PR TITLE
Make the lobby teamchat selector match the in-game selector.

### LINKED ISSUE #4516: Chat/Team button in the lobby
to make it look and behave like the in-game chat.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1388999-chat-team-button-in-the-lobby?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #4516.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]
This doesn't work for spectators in the lobby (while they have their own team chat ingame).

**Comment by pchote** [comment]
This is intended to be a simple UI change.  I'm not interested in building the spec-chat feature for the lobby, so will close this if you think it is a major blocker.

**Comment by abcdefg30** [comment]
```
19:08:42 (abcdefg30) actually, now I remember what I meant here: https://github.com/OpenRA/OpenRA/pull/15595#issuecomment-427587854
19:08:55 (abcdefg30) you can select "team:" chat as spectator, but it has no effect
19:09:16 (abcdefg30) can't we add a simple check if a player is in a spectator slot and disable the team chat then?
19:09:24 (pchote) ok
19:09:29 (pchote) please leave a comment
```

**Comment by pchote** [comment]
> 19:08:55 (abcdefg30) you can select "team:" chat as spectator, but it has no effect

Can you please provide steps to reproduce this? The selector defaults back to "all" and correctly disables itself when switching to spectator in a MP lobby for me.

Also rebased.

**Review by abcdefg30 — APPROVED** [review]
Looks good to me now.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a0c0a87af207ddf43a0004bb53d8791771bd13aa...9d05605699a0ed10dc4d39fc38b397527cade57a)

[Mod SDK wiki entry](https://github.com/OpenRA/OpenRAModSDK/wiki/Update-notes:-release-20180923-to-next/_compare/570cf8c2a3b2d380e644757929836a9544f24d6a...899e1393585f0feb825854b2cd84a2973a6940a9)

**Pull request merged**
