### PR TITLE
Added new 1v1 RA map by MicroBit - Ore Lord

### PR DESCRIPTION
**Pull request by cjshmyr**
Resource link: http://resource.openra.net/maps/1052

### CODE REVIEW

**Comment by MicroJOo** [comment]
thx @cjshmyr 

orelord screen

**Comment by obrakmann** [comment]
Map looks and plays ok, didn't spot any tiling errors. :+1:

**Comment by obrakmann** [comment]
Oh, whoops. I just noticed that the game auto-updated the map. We probably want to commit the updated map itself instead of an outdated version.

**Comment by cjshmyr** [comment]
Updated, @MicroJOo you likely want to upload this updated map to the resource site as a new revision

**Comment by TheRaffy** [comment]
nice map

**Comment by Mailaender** [comment]
Thanks everyone. [Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/6d2c42b576a474cd07da7d50cfbd9fc7be8edd9c...a003c342aa082b4e2e5adb591ecc58e14effceb0)

**Comment by Mailaender** [comment]
You will still want to update the map at the resource center. Otherwise it will display as unknown map at www.openra.net/games/ later on.

**Pull request merged**
