### PR TITLE
Introduce trait granting upgrades at specified DamageStates

### LINKED ISSUE #6272: Units slow down depending on damage taken.
Having a setting on/off, where units slow down movement when damaged. For example, a tank is too shot up to move fast enough, or a soldier is limping after being attacked.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3784038-units-slow-down-depending-on-damage-taken?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
Used to implement slowdown for damaged vehicles, but I'm sure there are many more possibilities (disabling certain weapons at critical damage etc.).

Closes #6272.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Uhm, uhm... don't get me wrong, but I fear the balance changes in the TD/RA/D2K mods will make the playerbase rage. The idea is great though.

**Comment by Mailaender** [comment]
Works as promised. :white_check_mark:

I suggest you limit this to the TS mod for now to avoid balancing discussions in a feature addition pull request.

**Comment by reaperrr** [comment]
> Uhm, uhm... don't get me wrong, but I fear the balance changes in the TD/RA/D2K mods will make the playerbase rage.

Uh, yeah, didn't think of that. I'll remove it from the shipping mods.

**Comment by reaperrr** [comment]
Updated.

**Comment by GraionDilach** [comment]
:+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/ae721bf65a638edf47fb0f958612cc99aca4100a...caf0f75a7345de7c7cf88fa12210aac7eb46bd36)

**Pull request merged**
