### PR TITLE
Removed harvester search radius restrictions

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/9232.

### CODE REVIEW

**Comment by pchote** [comment]
:-1: to removing the limit.  This regresses gameplay.

If your harvesters run out of local fields there is no benefit for them to travelling hundreds of cells to find a new field. If they don't die on the way (very likely if they pick a field near an enemy base) then the time it takes for them to travel there and back would be comparable to the time it would take for the local field to regenerate.

**Comment by reaperrr** [comment]
I'm also against this. The current defaults are certainly too low, but removing the code entirely just robs us of any kind of fine-grained control.

**Comment by Mailaender** [comment]
You will have to tweak this for every map as ore patch to next ore patch distances vary. This is actually what is currently being done in the Lua scripted maps. I highly advise against it.

**Comment by LipkeGu** [comment]
We could override this limit via rules in the map

**Comment by reaperrr** [comment]
> We could override this limit via rules in the map

@Mailaender's point is that it would be too much work to do that for each map individually.

**Pull request closed without merging**
