### PR TITLE
Added all ra notifications to notifications.yaml

### PR DESCRIPTION
**Pull request by abcdefg30**
I renamed "Win" to "MissionAccomplished" and "Lose" to "MissionFailied", because IMHO it sounds more reasonable and added "Repairing" and "Unit repaired" notifications to the service depo, as well.

Updated some year numbers and fixed a stupid mistake in utility.cmd (td vs cnc).

The notifications can be tested with [this lua code](https://gist.github.com/abcdefg30/651546fd409e01f401a0).

### CODE REVIEW

**Comment by obrakmann** [comment]
> I renamed "Win" to "MissionAccomplished" and "Lose" to "MissionFailied", 

I'd prefer to keep those two for backward compatibility.  We could duplicate them with those new names, though.

**Comment by abcdefg30** [comment]
Updated.

**Comment by obrakmann** [comment]
:+1: 
What's up with the "Harvester under Attack" sound, though? Didn't RA have one (I don't remember)?

**Comment by abcdefg30** [comment]
I couldn't find one.

**Comment by ScottNZ** [comment]
Would it be too much to ask to have the code additions as part of a different PR? I'm a bit hesistant on merging this because of that.

**Comment by abcdefg30** [comment]
> Would it be too much to ask to have the code additions as part of a different PR? They aren't really related to the PR's goal of adding new notifications to the yaml. I'm a bit hesistant on merging this because of that.

Done.

**Comment by Mailaender** [comment]
Thanks.

**Pull request merged**
