### PR TITLE
Add MaxBackwardCells for better backward option

### PR DESCRIPTION
**Pull request by dnqbob**
Now it depends on #20429, a correctness on actor's facing when backward moving .

### CODE REVIEW

**Comment by dnqbob** [comment]
Going to fix a bug when moving backward, which will be the dependency of this branch

**Comment by PunkPun** [comment]
Wouldn't it be better to deprecate `BackwardDuration` if we are introducing `MaxBackwardCells`?

**Comment by dnqbob** [comment]
> Wouldn't it be better to deprecate `BackwardDuration` if we are introducing `MaxBackwardCells`?

Nope, some hover unit may needs that to make it looks more TS style

going to apply it in #20419, after I finally fix the backward facing bug

**Comment by dnqbob** [comment]
Sorry if I did not make it clear, but this PR should use "Has  Dependencies" tag, instead of "Is Dependency". https://github.com/OpenRA/OpenRA/pull/20429 is the dependency.
@PunkPun 

I mention https://github.com/OpenRA/OpenRA/pull/20419 in this PR just for answer https://github.com/OpenRA/OpenRA/pull/20428#issuecomment-1300054490, they don't depend on each other.

**Pull request closed without merging**
