### PR TITLE
Added AI capturing of neutral tech buildings

### LINKED ISSUE #4561: AI should make use of oil derricks
Currently AI players ignore capturable oil derricks. Capturing these should be prioritised from the start. When oil derricks are available and ore is limited or unavailable, AI players should not build multiple refineries. Small teams of infantry and light vehicles could be assembled to escort the engineers or their transports, and then guard the captured derricks. An AI-owned derrick under attack should cause the AI to send support units and repair it if damaged.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1398351-ai-should-make-use-of-oil-derricks?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/4561.

### CODE REVIEW

**Comment by pchote** [comment]
This appears to simply reenable `CaptureManagerBotModule` without addressing the reasons that it was disabled in the first place (see the discussion from #4561 and linked issues). I strongly doubt that we will want to take this.

**Comment by MustaphaTR** [comment]
As i described in OpenRA/ra2#687, it should be easy to fix the old issue now.

**Comment by Mailaender** [comment]
Added a safeguard to prevent the AI running into a trap over and over. An easy test case is the map Tournament Island. The AI will start to capture their oil derricks first, after it is done it will go for the hospital. Add some defenses there. It will not make a new attempt. Added a debug message to verify.

**Comment by pchote** [comment]
Readding tag because this has not addressed my concerns about the AI behaviour of engineers that I explained in IRC.

Additionally, that discussion -- where you repeatedly dismissed my and @abcdefg30's concerns, insisted that it was our responsibility, not yours to demonstrate that issues have been resolved, called me a bad maintainer, and said that the project has "severe organisational problems" for giving negative feedback on PRs -- left me feeling very offended, and with a strong prejudice against this PR in general. As far as i'm concerned this is now a hard :-1: from me. I will not stand for being treated that way.

**Comment by Mailaender** [comment]
Neither do I. You still haven't addressed the reasons here properly. You just state that some exist and I have to find them out on my own, which I tried. Instead you take this on a personal level which is very unprofessional. I feel very insulted by your behavior and state that you are violating #13831. Don't try to emotionally blackmail me here. That is very offensive.

**Comment by abcdefg30** [comment]
For what it's worth, I don't see any CoC violation on @pchote's side. In fact, from my point of view @Mailaender brought this to a personal level first (but I don't see the need to act with the CoC there either). However, I might be biased in this matter (it's hard to tell myself if I'm not), so if you really think there is a big issue here you should contact another team member.

To put that behind us and focus on this PR, I'll summarise what I remember and found out by quickly skimming the tickets: We should have removed the capture manager, but were in the middle of preparing the next release when several "half baked" AI features turned out to be regressions, so things were just quickly disabled.
Now this PR appears (I haven't tested it yet) to bypass/fix issues of the past, namely by just letting the AI attempt to capture neutral structures once.
We now have to decide if it is worth to take in this workaround, since it could be an improvement over the current situation but most likely has to be completely replaced later on to address for example:
- No assessment of the risk of sending a capture team to a location. The AI already has code to estimate how dangerous a place is for example.
- No recapture of lost structures.
- The current "avoid capturing twice" mechanism will make it harder for the AI to capture husks in the future.
- Probably no mechanism to ship/fly engineers to capture sites that are inaccessible by foot. (I haven't tested this yet, how does the current code handle this? Does it still build an engineer that doesn't move?)

**Comment by Mailaender** [comment]
> Does it still build an engineer that doesn't move?

If there is nothing worth capturing then yes it will build 1 excess engineer. That was @MustaphaTR's concern. There is even a proposed solution to build engineers on demand. The issue to me was minor as one spare engineer doesn't hurt the economy too much. It is easy to implement though so I can add it.

**Comment by abcdefg30** [comment]
I was more refering to this situation:
grafik
But I suppose it's still not as big of a problem because of the build limit.

**Comment by anjew175** [comment]
If you constantly killed the engineer, would it rebuild it?

**Comment by abcdefg30** [comment]
Yes, but it won't take priority, so the AI would usually build other infantry too.

**Comment by reaperrr** [comment]
My concern here is that one of the highest priorities regarding further refactoring the AI, and therefore one of the things that will come sooner rather than later (we should aim for Next+2 at the latest, in my opinion), is to split out and revamp squad types from squad manager, and that will be the exact thing that will make all of this PR completely obsolete and probably throw the entire module out the window for good.

If we take this now, it will likely live for only 1 release, and after that notably increase update rule complexity and rebase conflicts when that squad refactor happens.

I understand that there's some impatience to finally give the AI the ability to capture at least neutral tech buildings, but I honestly think for a stop-gap solution like this we're simply at least 2-3 years too late and too close to that squad refactor happening.

**Comment by Mailaender** [comment]
After the lessons learned from https://github.com/OpenRA/OpenRA/pull/18290 and my https://github.com/OpenHV/OpenHV/commit/57eb19923b4f1d203701c1d02806c5b4cd92bcb8 I rewrote this. Instead of avoiding targets that didn't work last time the AI now does a check using the pathfinder. It seems that was the plan for this module all along as I found some unused code that might have been targeted in this direction.

**Comment by pchote** [comment]
I've noted this PR in #19247 to track this for the future, but for now are closing this to help address the unsustainable state of the PR queue.

**Pull request closed without merging**
