### PR TITLE
TS polishing pass: More depth sorting fixes

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes depth sorting of
- muzzle flashes
- Harpy rotor
- deployed sensor array
- tiberium veins and their attack anim
- crate effects

### CODE REVIEW

**Comment by reaperrr** [comment]
Updated.

**Comment by reaperrr** [comment]
Updated. Crate effects are now fixed as well.

**Review by pchote — APPROVED** [review]
LGTM :+1:

I suspect that we have a code issue for voxels with height (world-z, not screen-z) offsets, because both the titan barrel and tick tank turret have draw-order issues.  That's a job for another ticket, I think.

**Comment by abcdefg30** [comment]
Needs a rebase.

**Comment by reaperrr** [comment]
Rebased.

**Comment by pchote** [comment]
Needs another rebase, but I think you're to blame for that.

**Comment by pchote** [comment]
> I suspect that we have a code issue for voxels with height (world-z, not screen-z) offsets, because both the titan barrel and tick tank turret have draw-order issues. That's a job for another ticket, I think.

This is probably caused by my temporary billboard-z hack from #11791.

**Comment by reaperrr** [comment]
> Needs another rebase, but I think you're to blame for that.

Yeah, I forgot this also had a sensor array fix, but the one from the other PR was better anyway, so I'll just skip that commit.

**Comment by reaperrr** [comment]
Rebased.

**Comment by abcdefg30** [comment]
👍

**Pull request merged**
