### PR TITLE
Refresh lobby server list when switching to the Servers tab.

### LINKED ISSUE #14635: Server list is not refreshed after entering/leaving server lobby
When entering any PT server and pressing "Servers" - you will still see the list as it were before you joining (i.e. if you enter empty server, it will still be empty until you press "Reload"). The same is when you leave the server into the main lobby - you still see 1/2 near the server you just left, but no tooltip for players (because there are no players there) and no list to the right.

Simple solution would be to explicitly refresh the server list after joining and/or leaving the server, the same as entering the MP lobby for the first time from the main menu.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14635.

### CODE REVIEW

**Comment by reaperrr** [comment]
This seems to work only on entering, not on leaving a server (at least when I tested it with DirectIP, it still showed 2/2 after leaving).

**Review by reaperrr — APPROVED** [review]

**Comment by netnazgul** [comment]
@reaperrr yes, there are two separate issues - in-lobby server list not being refreshed after you join a server (so that server shows 0/X players); and general server list not being refreshed after you leave a server (so that server still shows your name in its players' list)

**Review by obrakmann — APPROVED** [review]
👍

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/9c894d8c3e93a34cd147c4d8ea23c95e54ffacdc)

eadf38184363185a9da91064973e05f18417a1a7

**Pull request merged**
