### PR TITLE
Add missing music tracks to global mix database.

### LINKED ISSUE #10983: TD campaign: Mission victory / failure music not playing
The faction specific mission victory / failure music is missing since the map rules changes.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #10983, which only happens for people who have installed the content from CD.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/96481433bfcf2b45e060448696e89b0b298f3821)

**Comment by GraionDilach** [comment]
This was a bleed regression I think though.

**Pull request merged**
