### PR TITLE
allowed resources to be grown under Actors

### LINKED ISSUE #7008: Resource growth should not be blocked by transient units
no ore under

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6524852-resource-growth-should-not-be-blocked-by-transient-units?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by besuikerd**
Fixes #7008, by modifying the Gem and Ore resource being allowed to grow under Actors. If this has some unexpected side effects please let me know

### CODE REVIEW

**Comment by pchote** [comment]
I expect this will also let resources grow under buildings, which we don't want.  The BuildingMap may take care of that, but it would be pretty silly if the fix was this simple and hadn't been done yet.  The final fix (whatever form it takes) will also need to be applied to all four mods.

**Comment by besuikerd** [comment]
Yes that was also my concern, I tried building several buildings directly next to a mine. Resources did not grow under those buildings. But indeed, maybe the problem should be handled in a more directed way.

**Comment by pchote** [comment]
The grow resources button in the debug menu will be useful for testing this:

1.  Place a structure near a resource field.
2.  Keep pressing the grow resource button until it is completely surrounded.
3.  Sell the structure, and verify whether there is a footprint-shaped hole in the field.

**Comment by besuikerd** [comment]
Great tip, thanks!

As I can see there is an added check `AllowUnderBuildings` specific for buildings, so that should explain why it does not allow it under buildings

```c#
public bool AllowResourceAt(ResourceType rt, CPos cell)
		{
			if (!world.Map.Contains(cell))
				return false;

			if (!rt.Info.AllowedTerrainTypes.Contains(world.Map.GetTerrainInfo(cell).Type))
				return false;

			if (!rt.Info.AllowUnderActors && world.ActorMap.AnyUnitsAt(cell))
				return false;

			if (!rt.Info.AllowUnderBuildings && buildingInfluence.GetBuildingAt(cell) != null)
				return false;

			return true;
		}
```

**Comment by Mailaender** [comment]
I can confirm that this fixes #7008 and `AllowUnderBuildings` also works as promised. :white_check_mark:

**Comment by besuikerd** [comment]
Awesome, I'll fix it for the other mods aswell :+1:

**Comment by Phrohdoh** [comment]
But do we want resources under actors? Specifically structures.

**Comment by penev92** [comment]
I don't think infantry or tanks should interfere with resources, especially tiberium (although it is illogical for ore, gems and spice). So... we really should only want tiberium to grow under tanks.
Anyway, buildings should restrict resource spreading.

**Comment by obrakmann** [comment]
First of all, this works as advertised, stuff grows beneath units but not beneath buildings, so :+1: 

I think we should allow that for all kinds of resources as those patchy fields just look bad. Also people in the mentioned ticket are in agreement that this should be fixed, so I'm gonna merge now.

**Comment by obrakmann** [comment]
Thanks!

[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ae8c0d24bded1130e4ce0af8627f8ad07fca5435%5E...ae8c0d24bded1130e4ce0af8627f8ad07fca5435)

**Comment by penev92** [comment]
Yeah, I was saying that it was illogical, not that we shouldn't have it :)
The C&C games have enough weird things like this :D

**Pull request merged**
