### PR TITLE
Change the RA harvester SHP file

### LINKED ISSUE #7949: Unloading harvester has pixel errors
There are three red dot pixels visible while a harvester is unloading at refinery.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11110550-unloading-harvester-has-pixel-errors?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by penev92**
Fixes #7949 with the file provided by @MicroJOo.

### CODE REVIEW

**Comment by reaperrr** [comment]
This file is quite large due to poor/lack of compression.

I recompressed it with XCC Mixer, shrunk it to 65 KB. Link: https://github.com/reaperrr/OpenRA/commit/43644a6259a6c6f6dfd32a23c2ae7ce5c5ded7f6

**Comment by MicroJOo** [comment]
yeah ... from 250 down to 65 is a win ... we somehow need some compressing - support for our utility tool ... should make a ticket for that

**Comment by Mailaender** [comment]
I believe https://github.com/OpenRA/OpenRA/issues/2063 is describing the old limitation of our SHP writer already.

**Comment by penev92** [comment]
Updated with @reaperrr's SHP.

**Comment by reaperrr** [comment]
:+1:

**Comment by Mailaender** [comment]
Confirmed that frame 104 is fixed now. :white_check_mark:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/59a3f9b5da1083919836d12f8ab9413e94ea7e29...0c4c14a5e4db8762631e37702b4e966cd69041ff)

**Comment by Mailaender** [comment]
Pinging @Iran and @cncnet as this may be also be useful for the legacy game community maintainers.

**Pull request merged**
