### PR TITLE
fixed picture position

### PR DESCRIPTION
**Pull request by 42foobar42**
fixed the picuture in mission nod06b like it was requested in #8297

### CODE REVIEW

**Comment by 42foobar42** [comment]
fixed typo

**Comment by obrakmann** [comment]
:+1:

**Comment by Mailaender** [comment]
nod06a/b/c are still jumpy for me.

**Comment by 42foobar42** [comment]
@Mailaender This is not because of the margin of the picture, that is because the country borders on the picture are a little bit different.

I have no drawing skills to fix that ;)

**Comment by clemty** [comment]
I still plan to look into the "jumpy borders" thing when I have time

**Pull request merged**
