### PR TITLE
Always show the building fake tags

### LINKED ISSUE #10456: Permanent "Fake" tag for fake buildings
Similar to the "Always show status bars" option, but for Fake buildings.

To keep track of your own buildings / fake buildings, without having to select them.

Also could be used on enemy identified fake buildings, if this #10355 is implemented 

" pchote:  IMO the most logical behaviour is for the spy to be consumed, and the 'fake' tag being revealed to the infiltrator. "
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29676515-permanent-fake-tag-for-fake-buildings?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/10456.

### CODE REVIEW

**Comment by pchote** [comment]
Please lets wait until after #17808 to avoid rebase nightmares.

**Review by fruestueck — DISMISSED** [review]
Works as advertised. Looks good as well.

**Comment by penev92** [comment]
The dependency was merged. Now needs a rebase.

**Comment by Mailaender** [comment]
Rebased.

**Review by atlimit8 — APPROVED** [review]

**Comment by atlimit8** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8246e13311c063ced2f9435029beab64b9bb8e14)

**Pull request merged**
