### PR TITLE
Added ReShaper dupFinder scans

### PR DESCRIPTION
**Pull request by Mailaender**
~~Just playing around with https://confluence.jetbrains.com/display/NETCOM/Introducing+ReSharper+Command+Line+Tools. Not meant to be actually merged (yet).~~

### CODE REVIEW

**Comment by Phrohdoh** [comment]
What are we waiting on to merge this?

**Comment by Mailaender** [comment]
http://help.appveyor.com/discussions/suggestions/696-pre-install-msxslexe-and-add-it-to-the-path at the moment.

**Comment by LipkeGu** [comment]
@Mailaender  you can this by yourself :/ to PATH

**Comment by Mailaender** [comment]
I managed to solve this with xmlstar.sourceforge.net which is already available through @Chocolatey. We now get a nice HTML report. I am satisfied now. We may need to unclutter the build though (at least for pull requests).

**Comment by penev92** [comment]
OK so what are we doing with this?
What's the plan on how we use it and how can I see some test output?

**Comment by Mailaender** [comment]
You can download dupReport.html from https://ci.appveyor.com/project/OpenRA/openra/build/1.0.4226/artifacts

**Comment by penev92** [comment]
It will find false positives, that's for sure, but I see it found some legit stuff as well, so :+1:

**Comment by GraionDilach** [comment]
It won't be fun cleaning up all that, but honestly I expected a lot worse and I guess we'll get it shorter by time anyway.  :+1:

**Comment by Mailaender** [comment]
I want to run it periodically though and not for every pull request like https://github.com/OpenRA/OpenRA/pull/8313.

**Comment by Mailaender** [comment]
I set this up to do it only once per day now.

**Comment by Unit158** [comment]
Looks reasonable. I have no clue how to test this, however.
From what I've seen it works though so :+1:

**Comment by Mailaender** [comment]
You can download the dupReport.html from https://ci.appveyor.com/project/OpenRA/openra/build/1.0.4500/artifacts

**Comment by Mailaender** [comment]
But we can only be sure it works until the next day 4 am UTC once this is merged.

**Comment by Mailaender** [comment]
It worked https://ci.appveyor.com/project/OpenRA/openra/build/1.0.4518/artifacts both Coverity and dupFinder ran this night.

**Pull request merged**
