### PR TITLE
Add an Offset property to SpawnActorOnDeath

### PR DESCRIPTION
**Pull request by abcdefg30**
As requested in https://github.com/OpenRA/OpenRA/pull/12980#issuecomment-287516394.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Shouldn't there be an edge-of-map check?

**Comment by abcdefg30** [comment]
We don't check on any other uses of `LocationInit` I'm aware of either.

**Comment by Phrohdoh** [comment]
This would be a good place to start adding those checks.

**Comment by pchote** [comment]
Adding checks to block spawning opens a huge can of worms.  What happens if an important unit feature requires this to work, but it is blocked?

My preference for a simple solution is to add a warning to the `[Desc()]` explaining undefined behaviour if the spawned unit extends outside the footprint/influence of the spawner.

**Comment by GraionDilach** [comment]
Valid points, I'm fine with the description update.

**Comment by abcdefg30** [comment]
Added the warning.

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by atlimit8 — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4f30664e841a70e55f9db57a7d2cbfa154a626cf...a624deeeb21259614978b0f1f8e7b61ed1a26f9e)

**Pull request merged**
