### PR TITLE
Fix naming in editor

### LINKED ISSUE #17493: Can't rename actors in the map editor
Setting health or owner works.

### PR DESCRIPTION
**Pull request by teinarss**
Fixes #17493

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]
Fix confirmed.

**Comment by pchote** [comment]
I haven't wrapped my head around the specific details of the undo/redo support yet - can you describe why we want to `Do()` `EditActorEditorAction` here but not the options?

**Comment by teinarss** [comment]
> 
> 
> I haven't wrapped my head around the specific details of the undo/redo support yet - can you describe why we want to `Do()` `EditActorEditorAction` here but not the options?

The options (e.g. health, facing, turret etc) are set directly on the actor as these are manipulated in real time when the user changes these values, in the edit actor dialog. This was done to keep the "preview" working.

Updating the actor's ID is only done when clicking OK in the dialog.

**Comment by pchote** [comment]
Would it make sense to apply the ID changes when the text field loses focus? This would make it consistent with the other options, right?

**Comment by teinarss** [comment]
> 
> 
> Would it make sense to apply the ID changes when the text field loses focus? This would make it consistent with the other options, right?

Not sure its worth it. The whole edit actor feature is a bit messy atm and a rewrite would be better.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/6715e41cb58f274e3ae7857b59017a98efb88d9c

**Pull request merged**
