### PR TITLE
Game loop. Skip render frames on slow systems.

### LINKED ISSUE #18491: performance, remove the forced renders
as once discussed in discord developer chat,

release latest. at Game.cs Loop().

the game main loop use a force render. on systems where rendering becomes slow the force render causes the main loop to become slower and slower - ending up loop resulting in 120% cpu usage, locking up multi player games.

the game also forces a minimum of 16 fps at the default game speed.

background: i have the issue that render time drops from 6-9ms to 20+ ms at times. likely gl, driver, cooling related. but i assume the full CPU usage happens on any slow systems.

request:
- let the game detect if rendering is slow, skip frames
- let the game detect that in general it can't keep up in both rendering and logic frames, perhaps drop in game speed or log console message, pause to catch up, exit
- let the game skip render frames - rather than forcing them
- send warnings to the console, indicating 
- bring back the possibility - like in previous releases - to run the game at 10 to 20 fps. works fine.

additional:
- register also a network delay, next to render and logic delay
- differentiate in the network ping/latency stats between network delays and render delays, allowing players to determine if the network is causing the issue or their PC

### PR DESCRIPTION
**Pull request by anvilvapre**
Closes #18491.

#19595 does not solve the situations where the game can get caught up in contineously rendering each game loop iteration.

Rewrite of the main loop. Not because I wanted to but because of unclarity and some bugs.

Motivation:
- Flatten the logic. Make it more readible. 
- Bug/dead-code: `now >= forcedNextRender` could never evaluate to true as not considered in `nextUpdate` and `renderTime` always being less (or eqaul) than `forcedNextRender`. 
- `forcedNextRender` makes the logic much harder to read. While the game still expects to render each `renderInterval`.
- Bug/dead-code: `haveSomeTimeUntilNextLogic` always evaluated to `true` or else `forceRender` would be. 
- Avoid `nextRender` lying in the past - after system interrupts, process pauses or on systems with slow GPU.
- Possible bug: In suspended mode `forcedNextRender` was not updated. 

Changes:
- Drop `forcedNextRender`. Rather drop once to minimum FPS if logic+rendering took too long. Or skip frame if needed.
- Assumes that `logicWorld.IsReplay == OrderManager.World.IsReplay`

Disadvantage:
- Request `RunTime` up to three times per iteration. Not realliy an issue.
- Temporarily drop to lowest FPS in case any slowness is detected. Could try to stay closer to preferred FPS, but this may allow the system to more easily catch up. 

other:
- You could introduce `haveSomeTimeUntilNextLogic` once more - but use `RunTime - timeNeededToRenderFrame` over `now` to calculate the value. However it would still always be true after running a logic tick. It would give priority over logic ticks in the situation that `nextLogic > nextRender && nextLogic < nextRender+renderTimePerFrame`.

I believe this would also benifit multi player games where some clients may be slow due to system causes - rather than network related causes.

### CODE REVIEW

**Comment by pleasejustgo** [comment]
Thank god for this.

**Comment by RoosterDragon** [comment]
I've come up with a makeshift test suite for this code. The test copy-pastes in the `Game.Loop` logic because mocking it would be near impossible. When pasting adjust `state == ...` to `state() == ...` and `Thread.Sleep` to `Thread_Sleep`.

I've added two test suites covering the behaviour of the existing loop and the one from this PR. The suites are not fully comprehensive due to the amount of conditional logic so there is room to expand them.

On this proposed code, I am seeing several failing test scenarios. I think these are bugs.

<details>
<summary>Test Code</summary>

```c#
using System;
using NUnit.Framework;
using OpenRA.Widgets;

namespace OpenRA.Test
{
	class IWorld
	{
		public bool IsReplay;
		public int ReplayTimestep;
		public int Timestep;
		public bool IsLoadingGameSave;
	}

	class IWorldRenderer
	{
		public IWorld World;
	}

	class IOrderManager
	{
		public IWorld World;
		float tickScale = 1f;
		public int SuggestedTimestep
		{
			get
			{
				if (World == null)
					return Ui.Timestep;

				if (World.IsLoadingGameSave)
					return 1;

				if (World.IsReplay)
					return World.ReplayTimestep;

				if (tickScale != 1f)
					return Math.Max((int)(tickScale * World.Timestep), 1);

				return World.Timestep;
			}
		}
	}

	class IRenderer
	{
		public class IWindow
		{
			public Action<IInputHandler> PumpInput;
		}

		public bool WindowIsSuspended;
		public IWindow Window = new IWindow();
	}

	class ISettings
	{
		public class IGraphicsSettings
		{
			public bool CapFramerate;
			public int MaxFramerate;
		}

		public IGraphicsSettings Graphics = new IGraphicsSettings();
	}

	class BleedGame
	{
		public Func<RunStatus> state;

		public long RunTime;
		public IWorldRenderer worldRenderer = new IWorldRenderer();
		public IOrderManager OrderManager = new IOrderManager();
		public ISettings Settings = new ISettings();
		public IRenderer Renderer = new IRenderer();
		public Action LogicTick;
		public Action RenderTick;
		public Action<int> Thread_Sleep;

		public void Loop()
		{
			// The game loop mainly does two things: logic updates and
			// drawing on the screen.
			// ---
			// We ideally want the logic to run every 'Timestep' ms and
			// rendering to be done at 'MaxFramerate', so 1000 / MaxFramerate ms.
			// Any additional free time is used in 'Sleep' so we don't
			// consume more CPU/GPU resources than necessary.
			// ---
			// In case logic or rendering takes more time than the ideal
			// and we're getting behind, we can skip rendering some frames
			// but there's a fail-safe minimum FPS to make sure the screen
			// gets updated at least that often.
			// ---
			// TODO: Separate world/UI rendering
			// It would be nice to separate the world rendering from the UI rendering
			// so that we can update the UI more often than the world. This would
			// help make the game playable (mouse/controls) even in low world
			// framerates.
			// It's not possible at the moment because the render buffer is cleared
			// before rendering and we don't keep the last rendered world buffer.

			// When the logic has fallen behind by this much, skip the pending
			// updates and start fresh.
			// For example, if we want to update logic every 10 ms but each loop
			// temporarily takes 100 ms, the 'nextLogic' timestamp will be too low
			// and the current timestamp ('now') will have moved on. Even if the
			// update time returns to normal, it will take a long time to catch up
			// (if ever).
			// This also means that the 'logicInterval' cannot be longer than this
			// value.
			const int MaxLogicTicksBehind = 250;

			// Try to maintain at least this many FPS during replays, even if it slows down logic.
			// However, if the user has enabled a framerate limit that is even lower
			// than this, then that limit will be used.
			const int MinReplayFps = 10;

			// Timestamps for when the next logic and rendering should run
			var nextLogic = RunTime;
			var nextRender = RunTime;
			var forcedNextRender = RunTime;
			var renderBeforeNextTick = false;

			while (state() == RunStatus.Running)
			{
				var logicInterval = Ui.Timestep;
				var logicWorld = worldRenderer?.World;

				// ReplayTimestep = 0 means the replay is paused: we need to keep logicInterval as UI.Timestep to avoid breakage
				if (logicWorld != null && !(logicWorld.IsReplay && logicWorld.ReplayTimestep == 0))
					logicInterval = logicWorld == OrderManager.World ? OrderManager.SuggestedTimestep : logicWorld.Timestep;

				// Ideal time between screen updates
				var maxFramerate = Settings.Graphics.CapFramerate ? Settings.Graphics.MaxFramerate.Clamp(1, 1000) : 1000;
				var renderInterval = 1000 / maxFramerate;

				// Tick as fast as possible while restoring game saves, capping rendering at 5 FPS
				if (OrderManager.World != null && OrderManager.World.IsLoadingGameSave)
				{
					logicInterval = 1;
					renderInterval = 200;
				}

				var now = RunTime;

				// If the logic has fallen behind too much, skip it and catch up
				if (now - nextLogic > MaxLogicTicksBehind)
					nextLogic = now;

				// When's the next update (logic or render)
				var nextUpdate = Math.Min(nextLogic, nextRender);
				if (now >= nextUpdate)
				{
					var forceRender = renderBeforeNextTick || now >= forcedNextRender;

					if (now >= nextLogic && !renderBeforeNextTick)
					{
						nextLogic += logicInterval;

						LogicTick();

						// Force at least one render per tick during regular gameplay
						if (OrderManager.World != null && !OrderManager.World.IsLoadingGameSave && !OrderManager.World.IsReplay)
							renderBeforeNextTick = true;
					}

					//var forceRender = renderBeforeNextTick || now >= forcedNextRender;

					var haveSomeTimeUntilNextLogic = now < nextLogic;
					var isTimeToRender = now >= nextRender;
					if (!Renderer.WindowIsSuspended && ((isTimeToRender && haveSomeTimeUntilNextLogic) || forceRender))
					{
						nextRender = now + renderInterval;

						// Pick the minimum allowed FPS (the lower between 'minReplayFPS'
						// and the user's max frame rate) and convert it to maximum time
						// allowed between screen updates.
						// We do this before rendering to include the time rendering takes
						// in this interval.
						var maxRenderInterval = Math.Max(1000 / MinReplayFps, renderInterval);
						forcedNextRender = now + maxRenderInterval;

						RenderTick();
						renderBeforeNextTick = false;
					}

					// Simulate a render tick if it was time to render but we skip actually rendering
					if (Renderer.WindowIsSuspended && isTimeToRender)
					{
						// Make sure that nextUpdate is set to a proper minimum interval
						nextRender = now + renderInterval;

						// Still process SDL events to allow a restore to come through
						Renderer.Window.PumpInput(new NullInputHandler());

						// Ensure that we still logic tick despite not rendering
						renderBeforeNextTick = false;
					}
				}
				else
					Thread_Sleep((int)(nextUpdate - now));
			}
		}

		public void LoopNew()
		{
			// The game loop mainly does two things: logic updates and
			// drawing on the screen.
			// ---
			// We ideally want the logic to run every 'Timestep' ms and
			// rendering to be done at 'MaxFramerate', so 1000 / MaxFramerate ms.
			// Any additional free time is used in 'Sleep' so we don't
			// consume more CPU/GPU resources than necessary.
			// ---
			// In case logic or rendering takes more time than the ideal
			// and we're getting behind, we can skip rendering some frames
			// but there's a fail-safe minimum FPS to make sure the screen
			// gets updated at least that often.
			// ---
			// TODO: Separate world/UI rendering
			// It would be nice to separate the world rendering from the UI rendering
			// so that we can update the UI more often than the world. This would
			// help make the game playable (mouse/controls) even in low world
			// framerates.
			// It's not possible at the moment because the render buffer is cleared
			// before rendering and we don't keep the last rendered world buffer.

			// When the logic has fallen behind by this much, skip the pending
			// updates and start fresh.
			// For example, if we want to update logic every 10 ms but each loop
			// temporarily takes 100 ms, the 'nextLogic' timestamp will be too low
			// and the current timestamp ('now') will have moved on. Even if the
			// update time returns to normal, it will take a long time to catch up
			// (if ever).
			// This also means that the 'logicInterval' cannot be longer than this
			// value.
			const int MaxLogicTicksBehind = 250;

			// Try to maintain at least this many FPS during replays, even if it slows down logic.
			// However, if the user has enabled a framerate limit that is even lower
			// than this, then that limit will be used.
			const int MinReplayFps = 10;

			// Timestamps for when the next logic and rendering should run
			var nextLogic = RunTime;
			var nextRender = RunTime;
			var renderBeforeNextTick = false;

			while (state() == RunStatus.Running)
			{
				// Ideal time between screen updates
				var settings = Settings.Graphics;
				var maxFramerate = settings.CapFramerate ? settings.MaxFramerate.Clamp(1, 1000) : 1000;
				var renderInterval = 1000 / maxFramerate;

				var world = OrderManager.World;
				var logicInterval = Ui.Timestep;
				var isReplayOrLoadingGameSave = false;

				// Retrieve logic interval
				if (worldRenderer != null)
				{
					var logicWorld = worldRenderer.World;
					var isPaused = false;
					if (logicWorld.IsReplay)
					{
						// We need to keep logicInterval as UI.Timestep to avoid breakage
						isPaused = logicWorld.ReplayTimestep == 0;
						isReplayOrLoadingGameSave = true;
					}

					if (!isPaused)
						logicInterval = logicWorld == world ? OrderManager.SuggestedTimestep : logicWorld.Timestep;
				}

				// Tick as fast as possible while restoring game saves, capping rendering at 5 FPS
				if (world != null && world.IsLoadingGameSave)
				{
					logicInterval = 1;
					renderInterval = 200;
					isReplayOrLoadingGameSave = true;
				}

				var now = RunTime;

				// If the logic has fallen behind too much, skip it and catch up
				if (now - nextLogic > MaxLogicTicksBehind)
					nextLogic = now;

				// Logic
				if (now >= nextLogic && !renderBeforeNextTick)
				{
					nextLogic += logicInterval;

					LogicTick();

					// Force at least one render per tick during regular gameplay
					if (!isReplayOrLoadingGameSave)
						renderBeforeNextTick = true;
				}

				// Render
				if (renderBeforeNextTick || now >= nextRender)
				{
					nextRender = now + renderInterval;

					if (Renderer.WindowIsSuspended)
					{
						// Still process SDL events if suspended to allow a restore to come through
						Renderer.Window.PumpInput(new NullInputHandler());
					}
					else
						RenderTick();

					// In the normal situation - on performant systems - 'nextRender' lies in the future.
					// In an exceptional situation (logic plus) render time may exceed the next render time.
					// I.e. due to a (temporary) slow system or this process being paused or interrupted.
					// Avoid getting caught in contineous (forced) rendering resulting in full CPU utilisation.
					if (RunTime > nextRender)
					{
						// Temporarily fall back to minimum allowed FPS. The maximum time allowed between screen updates.
						var maxRenderInterval = 1000 / MinReplayFps;
						if (maxRenderInterval > renderInterval)
							nextRender = now + maxRenderInterval;

						now = RunTime;

						// Skip frames
						if (now > nextRender)
							nextRender = now + maxRenderInterval;
					}

					renderBeforeNextTick = false;
				}

				// Sleep until next update
				var nextUpdate = Math.Min(nextRender, nextLogic);
				now = RunTime;
				if (nextUpdate - now > 0)
					Thread_Sleep((int)(nextUpdate - now));
			}
		}
	}

	[TestFixture]
	public class GameLoopTest
	{
		[TestCase(50, null, false, 10, false, 0, 20, 19, 805)] // Should be 20 renders ideally, but 19 is the current behaviour.
		[TestCase(1, null, false, 50, false, 0, 100, 100, 0)] // NOTE: We have too much to do. Forced-rendering means we are seeing equal logic to renders rather than dropping frames to catch up.
		[TestCase(50, null, false, 50, false, 0, 20, 50, 650)]
		[TestCase(50, null, false, null, false, 0, 20, 180, 0)]
		[TestCase(50, 25, false, 50, false, 0, 40, 50, 550)]
		[TestCase(50, 0, false, 50, false, 0, 25, 50, 625)]
		[TestCase(50, 5, false, 50, false, 0, 190, 10, 0)]
		[TestCase(50, 5, false, 5, false, 0, 195, 5, 0)]
		[TestCase(50, 25, true, 50, false, 0, 195, 5, 0)]
		[TestCase(50, null, false, 50, true, 50, 20, 0, 650)]
		public void RunsGameLoop(
			int timestep, int? replayTimestep, bool isLoadingSaveGame, int? maxFramerate, bool suspendWindow,
			int pumpInput, int logicTick, int renderTick, int threadSleepDelay)
		{
			RunGameLoopInner(
				timestep, replayTimestep, isLoadingSaveGame, maxFramerate, suspendWindow,
				pumpInput, logicTick, renderTick, threadSleepDelay,
				false);
		}

		[TestCase(50, null, false, 10, false, 0, 20, 20, 800)] // This now shows 20 renders, which is nice.
		[TestCase(1, null, false, 50, false, 0, 100, 50, 0)] // FAIL: This is still showing forced-render behavior, ignoring our 50 FPS cap.
		[TestCase(50, null, false, 50, false, 0, 20, 50, 650)] // FAIL: This is giving 60 renders, ignoring our 50 FPS cap.
		[TestCase(50, null, false, null, false, 0, 20, 180, 0)] // FAIL: We have uncapped FPS and spare time but are only seeing 20 FPS.
		[TestCase(50, 25, false, 50, false, 0, 40, 50, 550)]
		[TestCase(50, 0, false, 50, false, 0, 25, 50, 625)]
		[TestCase(50, 5, false, 50, false, 0, 190, 10, 0)] // FAIL: We have too much to do during a replay. We should give min 10 FPS and as much logic as possible. We are seeing 50 FPS but falling behind on logic.
		[TestCase(50, 5, false, 5, false, 0, 195, 5, 0)]
		[TestCase(50, 25, true, 50, false, 0, 195, 5, 0)]
		[TestCase(50, null, false, 50, true, 50, 20, 0, 650)] // FAIL: This is giving 60 pump-inputs, ignoring our 50 FPS cap.
		public void RunsGameLoopNew(
			int timestep, int? replayTimestep, bool isLoadingSaveGame, int? maxFramerate, bool suspendWindow,
			int pumpInput, int logicTick, int renderTick, int threadSleepDelay)
		{
			RunGameLoopInner(
				timestep, replayTimestep, isLoadingSaveGame, maxFramerate, suspendWindow,
				pumpInput, logicTick, renderTick, threadSleepDelay,
				true);
		}

		static void RunGameLoopInner(
			int timestep, int? replayTimestep, bool isLoadingSaveGame, int? maxFramerate, bool suspendWindow,
			int pumpInput, int logicTick, int renderTick, int threadSleepDelay,
			bool useNewLoop)
		{
			var world = new IWorld
			{
				Timestep = timestep,
				IsReplay = replayTimestep != null,
				ReplayTimestep = replayTimestep ?? 0,
				IsLoadingGameSave = isLoadingSaveGame
			};
			var game = new BleedGame();
			game.RunTime = 0;
			game.worldRenderer.World = world;
			game.OrderManager.World = world;
			game.Settings.Graphics.CapFramerate = maxFramerate != null;
			game.Settings.Graphics.MaxFramerate = maxFramerate ?? 60;
			game.Renderer.WindowIsSuspended = suspendWindow;

			var loopCountCalls = 0;
			game.state = () =>
			{
				var state = game.RunTime < 1000 ? RunStatus.Running : RunStatus.Success;
				if (state == RunStatus.Running)
					loopCountCalls++;
				return state;
			};
			var pumpInputCalls = 0;
			game.Renderer.Window.PumpInput = _ =>
			{
				pumpInputCalls++;
				game.RunTime += 5;
			};
			var logicTickCalls = 0;
			game.LogicTick = () =>
			{
				logicTickCalls++;
				game.RunTime += 5;
			};
			var renderTickCalls = 0;
			game.RenderTick = () =>
			{
				renderTickCalls++;
				game.RunTime += 5;
			};
			var threadSleepCalls = 0;
			var threadSleepCallsDelay = 0;
			game.Thread_Sleep = delay =>
			{
				threadSleepCalls++;
				threadSleepCallsDelay += delay;
				game.RunTime += delay;
			};

			if (useNewLoop)
				game.LoopNew();
			else
				game.Loop();

			Assert.Multiple(() =>
			{
				Assert.That(pumpInputCalls, Is.EqualTo(pumpInput), "Pump Input");
				Assert.That(logicTickCalls, Is.EqualTo(logicTick), "Logic Tick");
				Assert.That(renderTickCalls, Is.EqualTo(renderTick), "Render Tick");
				Assert.That(threadSleepCallsDelay, Is.EqualTo(threadSleepDelay), "Thread Sleep Delay");
			});
		}
	}
}

```
</details>

**Comment by anvilvapre** [comment]
Thanks for the test, very useful. 

One issue is that after a logic tick i directly without delay also perform the rendertick. Not setting `renderBeforeNextTick` will let 5 test cases pass. Or similary by respecting the render delay. But this won't help me fix the remaining issues. 

The issue is unlikely in the variable initialization part - purely in the execution of logic and render ticks. 

I one day need to rewrite - when i have time/focus. Probably will have to stick closer to the original implementation. 

I'd like to asks. Did you decide on the required test case outcome based on running bleed, or by theoretically reasoning what they output should be based on input. I.e. where does the 190 come from in below example?


``` 
Failed RunsGameLoopNew(50,5,False,50,False,0,190,10,0) [3 ms]                 
  Error Message:                                                                
   Multiple failures or warnings in test:                                       
  1)   Logic Tick                                                               
  Expected: 190                                                                 
  But was:  150                                                                 
                                                                                
  2)   Render Tick                                                              
  Expected: 10                                                                  
  But was:  50

```

**Comment by PunkPun** [comment]
> I one day need to rewrite - when i have time/focus. Probably will have to stick closer to the original implementation.

Then this PR should be turned into a draft

**Comment by RoosterDragon** [comment]
> I'd like to asks. Did you decide on the required test case outcome based on running bleed, or by theoretically reasoning what they output should be based on input. I.e. where does the 190 come from in below example?

Bit of both I suppose.

For that scenario specifically, we have the replay timestep set to 5ms. In the test setup we have logic and render ticks both taking 5ms, and we run for 1000ms.

Under these conditions, we can see we have too much work to do. If we logic every 5ms and it takes 5ms we use our entire time budget on logic only with no rendering. If we wanted to logic+render for everything then we'd need 2000ms but only have 1000ms.

On bleed, we can tell the existing policy in replays is to use a minimum FPS, currently set to 10. Bleed is happy to drop frames to try and make time for logic ticks. So if we say we will render 10 times to meet the min FPS policy, then we use 50ms of our budget for rendering and the remaining 950ms is available for logic. 950ms/5ms = 190 logic ticks. The same test case is used on bleed to prove the existing behaviour.

We can define whatever policy we would like, so if we wanted to do something else I am open to it, but for any scenarios where we haven't consciously decided to change the policy I shall expect the behaviour to remain the same as bleed.

**Comment by anvilvapre** [comment]
@RoosterDragon Could I ask you to review my new implementation. I only implemented as a test for now.

Two variants.

1. Test as is. Near compatible with bleed. However the game gives (more) prio to logic ticks. Also checks more often if it can/should sleep. This causes still 3 tests to fail. But this is because either more logic ticks could be done, or because the FPS adheres better to the frame limit.

2. Based on 1. Line 313 replaced with the line above. Where `haveTimeUntilNextLogic` assumes that a render tick duration will take `renderInterval` time - and will not start a render tick - unless forced - when a logic tick should run before the render tick has ended. (In pratice a render tick call duration should ideally take less than `renderInterval` time.)

[GameLoopTest.cs.gz](https://github.com/OpenRA/OpenRA/files/9471657/GameLoopTest.cs.gz)

Changes:
- Similar to bleed
- Kept forcedNextRender and forceRender
- Update now after logic and render tick - for more accurate timing
- Skip render frames if it means we fall behind on logic ticks - can in theory cause fps to drop somewhat
- Check once more/earlier if a logic tick should not already take place - before sleeping
- Respects forced renders - but if slow will also skip the next render frame. Drop a frame.
- If `haveTimeUntilNextLogic` includes/adds `renderInterval` - it will ensure that logic ticks have priority and that render ticks will run in sync as child - where only durnig forced renders a render can take up some time of when the next logic tick should have already been started. 

Additional future possible improvements (future pr): maintain avg/moving-max of actual render tick function call duration and use that of `renderInterval` to determine if there is time left - before the next logic tick - to render.

**Comment by RoosterDragon** [comment]
The test failures still seem troublesome.

- We're sleeping the thread, but not trying to get close to the max framerate. There's tests that have huge amounts (>500ms) of budget available but are only achieving 25, 10, or 8 fps when we asked for 50.
- We have reinstated the forced rendering behaviour, which, as with bleed, allows the FPS to go over the users max framerate setting. This does seem odd to me.

I think we should step back from the implementation and start with the policy. Given the various existing tuning knobs, what do we how many logic and renders we except in a variety of scenarios, such as:

- The tick rate is 10ps and max framerate is 50fps.
- The tick rate is 50ps and max framerate is 10fps.
- Repeat test cases above with uncapped fps.
- Repeat all cases above when we have sufficient time, and when we don't have enough time.
- Repeat all above tests cases again for normal gameplay, a replay, and loading a save.
- Repeat the replay test cases with a replay timestep tick rate higher and lower than the default tick rate.

We need to define what we're trying to achieve, before we know if the implementation is getting us there or not.

**Comment by anvilvapre** [comment]
> The test failures still seem troublesome.
> 
> * We're sleeping the thread, but not trying to get close to the max framerate. There's tests that have huge amounts (>500ms) of budget available but are only achieving 25, 10, or 8 fps when we asked for 50.

Are you referring to my second version? Since the first non modified version seems good?

To me this is not incorrect behaviour if the logic tick is always the start point for a following number of render frames. Running the render ticks out of sync with the logic tick seems troublesome to me - you will always have to deal with the two overlapping which is the start of running out of sync. 

In non modified version of the test there are 3 failures.
The first, render tick 20 in bleed, now 10 because of the frame limit of 10. 
The second has a higher render tick count, 67 over 50?
The third, the render tick is 40 where bleed did 50. Sleeping 50 additional ms. 


> * We have reinstated the forced rendering behaviour, which, as with bleed, allows the FPS to go over the users max framerate setting. This does seem odd to me.

Yes.

> 
> I think we should step back from the implementation and start with the policy. Given the various existing tuning knobs, what do we how many logic and renders we except in a variety of scenarios, such as:
> 

Prior my above question. Do you believe the render loop - timing wise should run asynchrounous from the logic tick. For me it is the start of unpredictable behavior. You allow the game to peek in FPS during moments where render or logic ticks may be short. Sure this increases your FPS counter but result in render spikes/unbalanced behavior.

> * The tick rate is 10ps and max framerate is 50fps.
> * The tick rate is 50ps and max framerate is 10fps.
> * Repeat test cases above with uncapped fps.
> * Repeat all cases above when we have sufficient time, and when we don't have enough time.
> * Repeat all above tests cases again for normal gameplay, a replay, and loading a save.
> * Repeat the replay test cases with a replay timestep tick rate higher and lower than the default tick rate.
> 
> We need to define what we're trying to achieve, before we know if the implementation is getting us there or not.

a. Bleed compatible
b. Logic tick prio, rendering is a nice to have
c. If a user wants 1000 fps, let them set that cap - then between logic ticks they will get that high fps.
d. At last, a way for the loop to be able to deal with long up to lock tick long pauses/spikes (if possible even seconds).

**Comment by RoosterDragon** [comment]
I don't have particular feelings around the game loop - but if you've got some clearly stated goals then you can write some tests that prove the behaviour on bleed is poor, and that this PR fixes it. And for anything else that we're not regressing the behaviour.

Then it becomes much easier to review the PR.

**Comment by pleasejustgo** [comment]
no particular feelings about the game loop? Clearly it's bugged. It wastes CPU cycles and energy causes older systems to lag, is one of the major contributors to lag online. People have even reported that this game has fried their video cards in another thread. It has to change.

**Comment by anvilvapre** [comment]
i suspect it is partly a mono issue. the game seems to have become slower on my host over time. suspect mono keeps allocating and can't free up enough.

try increasing nursery memory size, it can help somewhat. logging to an in memory tmpfs partition also helps - in the current release.

logic ticks at times would take 20ms and render ticks 26, which leaves you at <25 fps and a 125% cpu. this is in a 8 multi player game in the mid, before the end battles.

so no matter how you write the main loop, the game just can't run on Linux with an i7 at 2000+ MHz. my aim was just to let the game drop frames to as low fps as needed. to give prio to logic ticks, so games can continue.

in the next release it should be much better because of using dotnet over mono, but also many optimizations and some structural issues being solved. although also new features are added that may have a negative impact.


example GC log. Mono does not log timestamps. Seems memory growth of 6-10M each minor GC.
```
Loading mod: ra                                                                 
Mono: GC_MAJOR: (user request) time 310.28ms, stw 314.32ms los size: 667420K in use: 378912K
Mono: GC_MAJOR_SWEEP: major size: 166416K in use: 161137K                       
Mono: GC_MAJOR: (user request) time 104.40ms, stw 109.04ms los size: 694064K in use: 413838K
Mono: GC_MAJOR_SWEEP: major size: 181680K in use: 175544K                       
Mono: GC_MAJOR: (user request) time 87.30ms, stw 91.67ms los size: 694064K in use: 413838K
Mono: GC_MAJOR_SWEEP: major size: 181680K in use: 175811K                       
Mono: GC_MAJOR: (user request) time 88.41ms, stw 93.01ms los size: 694064K in use: 413830K
Mono: GC_MAJOR_SWEEP: major size: 181456K in use: 175371K                       
Mono: GC_MAJOR: (user request) time 127.70ms, stw 133.19ms los size: 698672K in use: 425911K
Mono: GC_MAJOR_SWEEP: major size: 212800K in use: 203923K                       
Mono: GC_MAJOR: (user request) time 102.16ms, stw 107.52ms los size: 728236K in use: 461132K
Mono: GC_MAJOR_SWEEP: major size: 204112K in use: 195728K                       
Mono: GC_MAJOR: (user request) time 95.79ms, stw 100.97ms los size: 727208K in use: 460108K
Mono: GC_MAJOR_SWEEP: major size: 204112K in use: 195885K                       
Mono: GC_MINOR: (Nursery full) time 31.73ms, stw 31.91ms promoted 15439K major size: 219488K in use: 212422K los size: 735424K in use: 486880K
Mono: GC_MINOR: (Nursery full) time 27.38ms, stw 27.52ms promoted 9622K major size: 229760K in use: 222656K los size: 735424K in use: 494048K
Mono: GC_MINOR: (Nursery full) time 19.81ms, stw 19.97ms promoted 6971K major size: 237248K in use: 230010K los size: 735424K in use: 496236K
Mono: GC_MINOR: (Nursery full) time 23.10ms, stw 23.25ms promoted 8618K major size: 246512K in use: 239042K los size: 735424K in use: 496880K
Mono: GC_MINOR: (Nursery full) time 22.74ms, stw 22.89ms promoted 6771K major size: 253856K in use: 246166K los size: 735424K in use: 498591K
Mono: GC_MINOR: (Nursery full) time 21.11ms, stw 21.26ms promoted 5993K major size: 260320K in use: 252488K los size: 735424K in use: 499220K
Mono: GC_MINOR: (Nursery full) time 25.94ms, stw 26.09ms promoted 7252K major size: 268128K in use: 260161K los size: 737480K in use: 504607K
Mono: GC_MINOR: (Nursery full) time 24.95ms, stw 25.08ms promoted 10190K major size: 279216K in use: 271033K los size: 737480K in use: 505261K
Mono: GC_MINOR: (Nursery full) time 28.86ms, stw 29.00ms promoted 11655K major size: 291888K in use: 283474K los size: 737480K in use: 506333K
Mono: GC_MINOR: (Nursery full) time 24.44ms, stw 24.57ms promoted 9185K major size: 301968K in use: 293265K los size: 737480K in use: 506843K
Mono: GC_MINOR: (Nursery full) time 21.90ms, stw 22.06ms promoted 7260K major size: 309808K in use: 300942K los size: 737480K in use: 508066K
Mono: GC_MINOR: (Nursery full) time 18.63ms, stw 18.77ms promoted 5916K major size: 316128K in use: 307164K los size: 737480K in use: 508066K
Mono: GC_MINOR: (Nursery full) time 24.75ms, stw 24.87ms promoted 10168K major size: 327152K in use: 317945K los size: 737480K in use: 508380K
Mono: GC_MINOR: (Nursery full) time 30.53ms, stw 30.69ms promoted 12415K major size: 340800K in use: 331227K los size: 737480K in use: 509236K
Mono: GC_MINOR: (Nursery full) time 19.25ms, stw 19.39ms promoted 6976K major size: 348464K in use: 338747K los size: 737480K in use: 509856K
Mono: GC_MINOR: (Nursery full) time 15.34ms, stw 15.47ms promoted 6343K major size: 355472K in use: 345608K los size: 737480K in use: 510299K
Mono: GC_MINOR: (Nursery full) time 21.61ms, stw 21.78ms promoted 6167K major size: 362224K in use: 352222K los size: 737480K in use: 510662K
Mono: GC_MINOR: (Nursery full) time 2.98ms, stw 3.16ms promoted 0K major size: 362224K in use: 352223K los size: 737480K in use: 510662K

```

**Comment by anvilvapre** [comment]
Closing for now.

**Pull request closed without merging**
