### PR TITLE
Fix spurious unit deaths during bridge transitions

### PR DESCRIPTION
**Pull request by chrisforbes**
To test this, place actors near TD short bridges (which have generous footprints) and destroy or repair the bridge.

### CODE REVIEW

**Comment by pchote** [comment]
Why is GitHub showing the Fossa and second appveyor check here?

**Review by pchote — COMMENTED** [review]
I haven't tested this, but it is the correct approach.

**Comment by chrisforbes** [comment]
Ugh, it seems I pushed the branch for this to OpenRA/OpenRA rather than my own fork -- so it triggers everything. I've turned off the FOSSA integration, it appears to be misconfigured still.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/3067cb50292bbaca063e7ba0ce66c8d7a964a005...0c80b8a6e84a4d09b70fe0fbab6d2b0e22d72929)

**Pull request merged**
