### PR TITLE
Fix speech notifications not playing in some SupportPowers when selecting a target.

### PR DESCRIPTION
**Pull request by abc013**
This now also plays the `SpeechNotification` set for the RA Chronoshit power.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Comment by pchote** [comment]
`ProduceActorPower` is still not using `SelectTargetSpeechNotification` or `SelectTargetSound`. All other powers now duplicate the same two lines to play the audio - wouldn't it be better to do this once inside `SupportPowerManager.Target` before calling `SelectTarget`?

**Comment by abc013** [comment]
You are right. Moved the lines to `SupportPowerInstance.Target`.

**Comment by pchote** [comment]
I have just merged #17920 - can you please rebase this and make the same change to `NukePower`?

**Comment by abc013** [comment]
Updated. Sorry for the delay.

**Review by pchote — APPROVED** [review]

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/8fa4f67422ef5c2542515a4e6e6306ed2b765252

**Pull request merged**
