### PR TITLE
Update Linux packaging for per-mod launchers.

### PR DESCRIPTION
**Pull request by pchote**
This completes the set (with #13133, #13129) of packaging changes for #12554.

~~Once again, depends on #13049.~~

Test build (fake playtest): [openra_playtest.20170416_all.deb](https://www.dropbox.com/s/bj24fn27ctruiqx/openra_playtest.20170416_all.deb?dl=0)

### CODE REVIEW

**Comment by ltem** [comment]
I (only) playtested it (deb-package and via git merge and rebase `--onto` , so the dependencies should be included for my tests) and there were no problems so far. What I see looks pretty good :)

| Screenshots |
|:----:|
| deb-package |
| image |
| image |
| bleed terminal |
| image |

**Comment by pchote** [comment]
Rebased after #13049.

**Review by phrohdoh — APPROVED** [review]
LGTM, I think @obrakmann's review would be valuable

**Comment by paulvt** [comment]
All seems good. The resulting package shows the proper changes (note that it loses opening .orareps from the desktop now) and is as Lintian clean as it first was. I do see that the following HTML files no longer provided, but this might be intentional:
```
-rw-r--r--  root/root   /usr/share/doc/openra/CHANGELOG.html
-rw-r--r--  root/root   /usr/share/doc/openra/CONTRIBUTING.html
-rw-r--r--  root/root   /usr/share/doc/openra/DOCUMENTATION.html
-rw-r--r--  root/root   /usr/share/doc/openra/Lua-API.html
-rw-r--r--  root/root   /usr/share/doc/openra/README.html
```

**Comment by pchote** [comment]
> I do see that the following HTML files no longer provided, but this might be intentional

This wasn't intentional.  I believe this is a regression from an older PR, and in any case I have already fixed this in the next PR.

> All seems good. 

You have expertise and experience with our deb packaging, so i'm taking this as a second :+1:

**Pull request merged**
