### PR TITLE
Fix the flare being invisible

### LINKED ISSUE #10830: Flares don't get rendered in allies01, soviet07 and possibly other maps
They appear to be rendered in the map editor but not ingame.

### PR DESCRIPTION
**Pull request by abcdefg30**
Fixes #10830.

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
What the hell... needs a rebase.

**Comment by obrakmann** [comment]
Also :+1:. Does anyone know what introduced the breakage? I'm asking for a ~~friend~~ changelog

**Comment by abcdefg30** [comment]
> What the hell... needs a rebase.

Huh, I don't get it too... Rebased and it still can't be merged?!
(Didn't need to resolve any conflicts as well...)

**Comment by pchote** [comment]
Confirmed that this restores the flares. :+1:

**Comment by pchote** [comment]
(no changelog because this was fixing a bleed-only regression)

**Pull request merged**
