### PR TITLE
Fix resizing of packaged maps.

### LINKED ISSUE #11597: resize map command is broken
Works with the last release, broken on bleed.

`mono OpenRA.Utility.exe ra --resize-map /home/dr/.openra/maps/ra/\{DEV_VERSION\}/oasis.oramap 86 86`

 > Unhandled Exception:
System.IO.FileNotFoundException: Unable to find parent package for /home/dr/.openra/maps/ra/{DEV_VERSION}/oasis.oramap
  at OpenRA.FileSystem.ZipFile..ctor (IReadOnlyFileSystem context, System.String filename) <0x416a3b50 + 0x002bf> in <filename unknown>:0 
  at OpenRA.FileSystem.FileSystem.OpenPackage (System.String filename) <0x4167c280 + 0x00157> in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.ResizeMapCommand.Run (OpenRA.ModData modData, System.String[] args) <0x416a3360 + 0x00077> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) <0x4163f9e0 + 0x005f0> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Unable to find parent package for /home/dr/.openra/maps/ra/{DEV_VERSION}/oasis.oramap
  at OpenRA.FileSystem.ZipFile..ctor (IReadOnlyFileSystem context, System.String filename) <0x416a3b50 + 0x002bf> in <filename unknown>:0 
  at OpenRA.FileSystem.FileSystem.OpenPackage (System.String filename) <0x4167c280 + 0x00157> in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.ResizeMapCommand.Run (OpenRA.ModData modData, System.String[] args) <0x416a3360 + 0x00077> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) <0x4163f9e0 + 0x005f0> in <filename unknown>:0 

[Logs_utility.zip](https://github.com/OpenRA/OpenRA/files/354025/Logs_utility.zip)

### PR DESCRIPTION
**Pull request by pchote**
Fixes #11597, which was missed by #11482.

### CODE REVIEW

**Comment by Mailaender** [comment]
Are

* OpenRA/OpenRA.Mods.Common/UtilityCommands/GetMapHashCommand.cs
* OpenRA/OpenRA.Mods.Common/UtilityCommands/OutputActorMiniYamlCommand.cs
* OpenRA/OpenRA.Mods.Common/UtilityCommands/ExtractMapRules.cs

effected as well?

**Comment by pchote** [comment]
Yes.  Fixed them too.

**Comment by Mailaender** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/32970fe2d9996f2862d36c1a2bb6b70484196f80)

**Pull request merged**
