### PR TITLE
Fixed a NullReferenceException when not using the optional MAP LabelWidget

### PR DESCRIPTION
**Pull request by Mailaender**
Obviously a copy & paste error. Only a problem if you use a custom chrome though.

### CODE REVIEW

**Comment by obrakmann** [comment]
:+1:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by abcdefg30** [comment]
I count :+2: here and this looks reasonable.

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/284a2ddbafaeca5f5a48e9b1fe2eff2e779ac125...aaa2465c29cf2b5f77a5b3beb27b29e5f76d6151)

**Pull request merged**
