### PR TITLE
Support mod defined vertex buffers and shaders.

### PR DESCRIPTION
**Pull request by IceReaper**
Title says all. This allows mods to load up their own glsl shaders and assign a proper vertex buffer to it. This allows mods for example to load up 3d assets from any custom mod, animate it, and render it as it should.

### CODE REVIEW

**Comment by pchote** [comment]
I was really hoping to wait until after the veldrid port to do this! All of the code that this touches is going to either disappear or completely change as part of that.

**Comment by IceReaper** [comment]
> I was really hoping to wait until after the veldrid port to do this! All of the code that this touches is going to either disappear or completely change as part of that.

Im totaly okay with that :)

**Comment by pchote** [comment]
I'm fairly sure that we are going to need to invent some new plumbing that allows mods to define their own rendering pipeline / shaders. Even with the upstream mods, the desire for supporting remastered assets VS tiberian sun create too many conflicts to reasonably solve with the same rendering code.

For example, the per-pixel depth sorting in TS drives the need for 1:1 scale rendering of the world into a frame buffer, which is then upscaled using a special shader while the remaster doesn't care about this and really needs to be down scaling at the world level to avoid performance issues.

There are also various special effects, such as the chroma keyed faction colours in the remaster assets, the desaturation menu effect in TD, the distortion effects of the chrono vortex and D2k sonic weapons, which all become much easier / more performant if hardcoded into the shader instead of being treated generally.

I still don't know how this should actually look in code! But I think this is more general than your goal here, but would allow you to cover your use cases within it.

**Comment by pchote** [comment]
The PR as it currently exists is basically just unhardcoding `Vertex`, which I don't have a problem with and doesn't really impact my thoughts above - the overlap / conflict is going to be in the things you'll be building downstream on top of this.

So I don't think theres any need to delay or scope creep this PR too much, although I would like it if we could rethink the way that `CompileShaderObject` gets the shader text. Digging back up into `Game.ModData.DefaultFileSystem` from the low level platform code isn't a good idea - could we pass this a `Stream` instead, and leave it to the calling code to either hardcode the filepath or search the vfs?

**Comment by pchote** [comment]
I don't see a clear direction forward here, but hopefully this will change in the near future after we can finally remove GL2 support and overhaul the vertex and texture systems. Closing this to help clean up the PR queue.

**Pull request closed without merging**
