### PR TITLE
Automated correctness fixes for tileset definitions.

### LINKED ISSUE #5272: Remove magic sprite filename resolution (support TS-style terrain-specific artwork) [$20]
Automatically resolving extensionless filenames to tileset-specific versions made sense back in 2007, but the engine is now a completely different beast and this now causes more problems than it solves.

* It makes it very difficult to statically verify sequence errors. #2283
* It makes it difficult to effectively cache data to reduce load times (see #5234).
* It's not needed for D2K, which doesn't have tileset-specific art.
* It won't work at all in TS or RA2, which use different names (not just extensions) for tileset-specific art.

We should rip out this legacy code, require mods to define tileset-variants in sequences, and then use name mangling (like we do for damage states) to resolve them in mod-level code.

<bountysource-plugin>
---
There is a **[$20 open bounty](https://www.bountysource.com/issues/2076095-remove-magic-sprite-filename-resolution-support-ts-style-terrain-specific-artwork-20?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
This adds a `--fix-classic-tilesets` utility command that parses the tilesets in a mod and inserts tile definitions that were previously implicit.  It also fixes some missing `PickAny` cases and adds explicit filename extensions for the tile images.  Finally, it enables the per-tile minimap colors that are defined for TS and RA2.

This is part of a larger series of patches (along with #7700 and future prs that build on these two) that fixes #5272.

### CODE REVIEW

**Comment by reaperrr** [comment]
Spotted no ingame regressions and the command seems to work (it didn't change anything for RA, but that's the logical result since the fixes are already included). :+1: / :white_check_mark: 

Needs a rebase, though

**Comment by Phrohdoh** [comment]
This needs a rebase.

**Comment by pchote** [comment]
Rebased.

**Comment by Phrohdoh** [comment]
Didn't break any of the shipped mods for me.
Games (including AIs) played nicely with no crashes. :+1:

**Comment by Phrohdoh** [comment]
[Changelog entry](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c9dd4891a49859674435f49b7ff8923286030021...01dba39e112b0a3b44fe0b513879e7479b2146ca).

**Pull request merged**
