### PR TITLE
Cleanup in OrderManager

### PR DESCRIPTION
**Pull request by teinarss**
Removing some properties that did not belong to the OrderManager.  Had to put these on a static class unfortunate, the other option is to have them on the Game class, but that class is already a monster. Hopefully i can find a proper place for them in a future refactoring.

### CODE REVIEW

**Review by abcdefg30 — APPROVED** [review]
Ok.

**Comment by reaperrr** [comment]
@pchote Before I merge this, anything in here you disagree with?

**Comment by pchote** [comment]
This is a good idea but I don't have any time spare to think about the implications of the specific changes. Lets take it, can always revert or fix it if regressions are found during playtesting.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/4fb85ce7a6da5fd105995d6aeeb8f057352613be...c1d8503a810ae00a378f33cb02793b11619514af

**Comment by abcdefg30** [comment]
> This is a good idea but I don't have any time spare to think about the implications of the specific changes. Lets take it, can always revert or fix it if regressions are found during playtesting.

Too soon? #19448

**Pull request merged**
