### PR TITLE
Rebalance keep-off-the-grass-2.oramap for the RA mod

### PR DESCRIPTION
**Pull request by ghost**
In relation to #10298

map on resource centre http://resource.openra.net/maps/8264/ (parsed on bleed...)

Original
k1

Updated
k2

-Ore patches in spawns and expansions have been adjusted to remove the northern REF disadvantage.
-Ore mines at corner expansions have been reduced from three to two; terrain made less chokey
-Both ore mines in gem patch have been replaced by a single gem mine
-Trees, debris and detailing

### CODE REVIEW

**Comment by cjshmyr** [comment]
:+1:

**Comment by MicroJOo** [comment]
:+1:

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0b3a94a3a480364f12e63b7d7702644dd04e1d85...628789a8521ff4c040e8b25c098d91f1d8a05ecd)

**Comment by SoScared** [comment]
Just a heads-up, two separate ore patches at the starting position will pull builds orders towards getting your 2nd ref there as opposed to moving early for an expansion.

**Comment by r34ch** [comment]
@SoScared Please feel free to make changes as you see fit, you make a valid point. 

Fwiw my reasoning was such; The large ore patch hinders base placement for those who stayed in spawn. Those who moved out at game start could get good eco with a single large base (3 mines in each corner plus the two in the middle if you didn’t mind redeploying your initial MCV a couple times). It almost made little sense to stay in spawn.

By splitting the ore in spawn it gave people in spawn a little more room for defensive placement of tech structures and by removing 1 ore spawn from each corner, lessened the advantage of taking and entrenching these areas so early.

That said, I didn't think of the changing 2 REF start. And it was only theory crafting.

**Comment by SoScared** [comment]
Here's the upload of mine (see screenshot): http://resource.openra.net/maps/8905/

The only changes was the original patch and I re-positioned one of the three ore mines at the corner expansion to free up more space for more equal ref placements there. The three ore mines at the corner expansion are almost void of ore so it cannot support a build-up of ore harvesters alone. If a player wants to move the MCV from the start he may take that chance but that's gonna require the player successfully take full control of the middle ore as well as the expansion to benefit the move.

I suggest setting the ore patches this way to preserve the map's playstyle.

**Comment by SoScared** [comment]
I'm inspired to go back and decorate the other maps more after seeing your detailing.

**Comment by SoScared** [comment]
Ok so here's your map with some reverses in ore placements: http://resource.openra.net/maps/8990/

keep off the grass 2 rew2

**Pull request merged**
