### PR TITLE
Map update: Symmetrification of some popular maps

### PR DESCRIPTION
**Pull request by GraionDilach**
- Rogue States, Manufacturing Consent and Necessary Illusions are now near-perfectly symmetrical. 
  Hopefully this will make them more appealing for tournament play. Their overall form hasn't changed much, but they had some lines redrawn and a general cleanup. Necessary Illusions is now a temperate tileset because people complained the snow tileset hurts their eyes.
- Letters from Lexington was re-added after symmetrification and some minor layout adjustments for playability and fairness, including removal of viceroids due to their new "roaming" behaviour.

Maps included:
Letters from Lexington: http://resource.openra.net/maps/14560/
Necessary Illusions: http://resource.openra.net/maps/11829/
Manufacturing Consent: http://resource.openra.net/maps/11844/
Rogue States: http://resource.openra.net/maps/13588/

Supersedes #11221.

### CODE REVIEW

**Comment by obrakmann** [comment]
Rogue States:
screenshot from 2016-06-12 18 14 11
screenshot from 2016-06-12 18 17 28
screenshot from 2016-06-12 18 17 50

Manufacturing Consent:
screenshot from 2016-06-12 18 38 58
screenshot from 2016-06-12 18 40 44
screenshot from 2016-06-12 18 42 21

Necessary Illusions:
screenshot from 2016-06-12 18 47 47
screenshot from 2016-06-12 18 48 25

Letters from Lexington:
screenshot from 2016-06-12 18 53 18
screenshot from 2016-06-12 18 54 22
screenshot from 2016-06-12 18 55 13
screenshot from 2016-06-12 18 56 07
screenshot from 2016-06-12 18 56 25
screenshot from 2016-06-12 18 56 39
screenshot from 2016-06-12 18 56 59
screenshot from 2016-06-12 18 57 42

**Comment by GraionDilach** [comment]
I remember we had a discussion on IRC regarding this where this PR had not much interest, but should I still aim to fixup these maps?

**Comment by obrakmann** [comment]
I'd rather someone spend some time on getting the good maps from the map contest into openra than fixing up maps that don't need fixin'.

**Comment by GraionDilach** [comment]
Closed because of lost interest.

**Pull request closed without merging**
