### PR TITLE
Fix MiG missiles damaging airborne actors

### PR DESCRIPTION
**Pull request by abcdefg30**
Reported by @Orb370 on Discord: https://clips.twitch.tv/InquisitiveAlluringPeachKevinTurtle

Only disables the damage of the impact.

### CODE REVIEW

**Comment by deleted-user-1** [comment]
Works as promised but not sure if this is an improvement - now the MiG keeps chasing the Yak forever, even if it is out of ammo (unless yak lands, then MiG will either shoot or RTB). I'd rather live with the bug tbh ~~or MiG A2A~~.

**Comment by abcdefg30** [comment]
Fwiw, the MiG chasing the Yak is already present on bleed.

**Review by deleted-user-1 — APPROVED** [review]
The issue about chasing invalid targets is addressed in another PR.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/06c07a3ba988163d196926a7c66255a6c7d15699...e237832a928d38b3caa530872f18a9b303b53a5d)

**Pull request merged**
