### PR TITLE
D2K - Fix Starport unit prerequisites.

### PR DESCRIPTION
**Pull request by MustaphaTR**
Combat tanks, Carryalls and MCVs was prerequisited by same building with real ones. But we should be allowed to build them from starport with only starport. This is a discussable thing but i left `repair` for `MCV.starport`s

### CODE REVIEW

**Comment by penev92** [comment]
Looks good, but I'll have to test it ingame later.

**Comment by Mailaender** [comment]
Is that original Dune 2000 balancing/behavior?

**Comment by Unit158** [comment]
Starports allowed you to buy a unit before you had it's prereqs in the original.

**Comment by Mailaender** [comment]
Why require the repair pad then for MCVs?

**Comment by WolfGaming** [comment]
Currently this would be op though until we got the real starport behavior. (IMO since I havent tested this)

**Comment by penev92** [comment]
MCV without any prerequisites sounds dangerous to gameplay.

**Comment by Mailaender** [comment]
The whole thing is dangerous to game-play as it effectively disables the tech tree for every vehicle, but that seems to be wanted here.

**Comment by Mailaender** [comment]
:+1:

**Comment by penev92** [comment]
:+1: I think we should use the upcoming playtest to see how this affects gameplay.

**Comment by Mailaender** [comment]
It will make more sense if you simply can't order MCVs from the Starport though.

**Comment by penev92** [comment]
I can agree to that, but then we're just asking for people to rage that it's not how it went in the original...

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/c6a360314ea6ad5aee3ce1bc25598730665158a4...d6ed3e1dfaf18f94b187a8bbec61af76d85cc66a)

**Pull request merged**
