### PR TITLE
Add support for aggregate sequences

### PR DESCRIPTION
**Pull request by pchote**
As requested in #9261.

### CODE REVIEW

**Comment by chrisforbes** [comment]
:+1:

**Comment by reaperrr** [comment]
I'd like to try reproduce whatever issue I had with this before someone else merges this.

**Comment by reaperrr** [comment]
Ok, I managed to reproduce the problem (I think this was the problem, at least).

If I want an *actor* to use an .shp per facing with 2 (or more) frames per facing, regardless of whether I use `Length: 2` or `Stride: 2`, I get

``Exception of type `System.FormatException`: Failed to parse sequences for htnk.idle at E:\OpenRA_work_clean_20150501\mods/cnc/sequences/vehicles.yaml:95:
System.FormatException: The index, based on 0 (zero), must be larger or equal to zero, and lower than the size of the list of arguments.`` 
(rough translation from German)

I pushed my failing test case here: https://github.com/reaperrr/OpenRA/tree/aggregate-sequences

**Comment by pchote** [comment]
@reaperrr: That crash was caused by bogus formatting parameters in the exception string.  Fixed those.  The (now correct) exception showed that you missed the `Length: 2` on each of the sub-sequences in order to load all 64 frames (32 facings * stride of 2).

**Comment by reaperrr** [comment]
Tested both the fixed exception and the fix for my testcase, works fine now :+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/2cc4aedc487f6d839c160a4b0c99ed07f4c45e5e...b1540f7409c20a25037971371c664df2a7cd33ec)

**Comment by evgeniysergeev** [comment]
```
Exception of type `System.InvalidOperationException`: Unit `quad.dune2` does not have a sequence named `idle`
  at OpenRA.Graphics.SequenceProvider.GetSequence (System.String unitName, System.String sequenceName) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.Animation.PlayRepeating (System.String sequenceName) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.WithSpriteBody..ctor (OpenRA.ActorInitializer init, OpenRA.Mods.Common.Traits.WithSpriteBodyInfo info, System.Func`1 baseFacing) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.WithFacingSpriteBody..ctor (OpenRA.ActorInitializer init, OpenRA.Mods.Common.Traits.WithFacingSpriteBodyInfo info) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.WithFacingSpriteBodyInfo.Create (OpenRA.ActorInitializer init) [0x00000] in <filename unknown>:0 
  at OpenRA.Actor..ctor (OpenRA.World world, System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00000] in <filename unknown>:0 
  at OpenRA.World.CreateActor (Boolean addToWorld, System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00000] in <filename unknown>:0 
  at OpenRA.World.CreateActor (System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.Production+<DoProduction>c__AnonStorey1.<>m__0 (OpenRA.World w) [0x00000] in <filename unknown>:0 
  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
OpenRA needs zenity installed to display a graphical error dialog. See ~/.openra. for log files.
./launch-game.sh: line 7: --question: command not found
./launch-game.sh: line 7: xdg-open: command not found
```
then trying to use this yaml in d2k mod:
```
quad.dune2:
	idle: UNITS.SHP
		Combine:
			a: UNITS.SHP
				Frames: 0, 1, 2, 3, 4
			b: UNITS.SHP
				Frames: 3, 2, 1
				FlipX: true
		Facings: -8
	icon: SHAPES.SHP
		Start: 74
		Offset: 0,0
```

**Comment by atlimit8** [comment]
@evgeniysergeev
Try removing `UNITS.SHP` after `idle:`
Yea, there should be an error message, but the error must be discovered first.

**Comment by evgeniysergeev** [comment]
the same error. initially I was check without UNITS.SHP after idle. it was added after crash

**Comment by yaaaaa** [comment]
> OpenRA engine version release-20180307
Red Alert 2 mod version release-20180307
on map 1a848cb4377fc30745fe9ada0914e29d05dc5b8b (Arctic Circle by Westwood Studios).
Date: 2018-07-23 14:49:05Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `tsgapowr` does not have a sequence named `idle`
   в OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Graphics\SequenceProvider.cs:строка 78
   в OpenRA.Mods.Common.Traits.QuantizeFacingsFromSequenceInfo.QuantizedBodyFacings(ActorInfo ai, SequenceProvider sequenceProvider, String race) в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Mods.Common\Traits\QuantizeFacingsFromSequence.cs:строка 31
   в OpenRA.Mods.Common.Traits.Render.RenderSpritesInfo.<RenderPreview>d__0.MoveNext() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Mods.Common\Traits\Render\RenderSprites.cs:строка 65
   в System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в OpenRA.Mods.Common.Orders.PlaceBuildingOrderGenerator.<RenderAboveShroud>d__1b.MoveNext() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Mods.Common\Orders\PlaceBuildingOrderGenerator.cs:строка 221
   в System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в OpenRA.Graphics.WorldRenderer.GenerateOverlayRenderables(HashSet`1 actorsInBox) в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Graphics\WorldRenderer.cs:строка 154
   в OpenRA.Graphics.WorldRenderer.Draw() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Graphics\WorldRenderer.cs:строка 208
   в OpenRA.Game.RenderTick() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Game.cs:строка 650
   в OpenRA.Game.Loop() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Game.cs:строка 781
   в OpenRA.Game.Run() в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Game.cs:строка 799
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Game.cs:строка 253
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\OPENRA-ra2\engine\OpenRA.Game\Support\Program.cs:строка 37

> tsgapowr:
	Defaults:
		Offset: 0, -24, 24
		UseTilesetCode: true
		DepthSprite: isodepth.shp
	idle:
		ShadowStart: 3
	damaged-idle: tsgapowr
		Start: 1
		ShadowStart: 4
	dead: tsgapowr
		Start: 2
		ShadowStart: 5
		Tick: 400
	idle-lights: gtpowr_a
		Length: 12
		Tick: 200
	damaged-idle-lights: gtpowr_a
		Start: 12
		Length: 12
		Tick: 200
	idle-plug: gtpowr_b
		Length: 12
		Tick: 200
	damaged-idle-plug: gtpowr_b
		Length: 12
		Tick: 200
	idle-powrupa: gtpowr_b
		Length: 12
		Tick: 200
		Offset: -48, -24, 24
	damaged-idle-powrupa: gtpowr_b
		Length: 12
		Tick: 200
		Offset: -48, -24, 24
	idle-powrupb: gtpowr_b
		Length: 12
		Tick: 200
		Offset: -24, -12, 24
	damaged-idle-powrupb: gtpowr_b
		Length: 12
		Tick: 200
		Offset: -24, -12, 24
	make: gtpowrmk
		Length: 20
		ShadowStart: 20
	emp-overlay: emp_fx01
		Length: *
		Offset: 0, 0, 25
		UseTilesetCode: false
		ZOffset: 512
		BlendMode: Additive
		-DepthSprite:
	icon: powricongdi
		Offset: 0, 0
		UseTilesetCode: false
		-DepthSprite:

**Comment by yaaaaa** [comment]
it's crash than i trying to place  tsgapowr building in game (tsgapowr.shp is in the BITS folder)

**Comment by reaperrr** [comment]
You have `UseTilesetCode: true` on Defaults, which looks up the 2nd letter of the filename (must be 't' for temperate or 'a' for snow). Since you added 'ts' in front of the filename, it doesn't find any file with correct filename.

Either change it to `gapowrts` (if you have a 'gt' variant, too) or set `UseTilesetCode: false` on `idle`, `damaged-idle` and `dead`.

**Comment by yaaaaa** [comment]
Thanks for Your helping, IDLE sequence is displayed correctly now, but why make sequence not found?

> gapowrts:
	Defaults:
		Offset: 0, -24, 24
		UseTilesetCode: true
		DepthSprite: isodepthts.shp
	idle:
		ShadowStart: 3
	damaged-idle:
		Start: 1
		ShadowStart: 4
	dead:
		Start: 2
		ShadowStart: 5
		Tick: 400
	idle-lights: gtpowrts_a
		Length: 12
		Tick: 200
	damaged-idle-lights: gtpowrts_a
		Start: 12
		Length: 12
		Tick: 200
	idle-plug: gtpowrts_b
		Length: 12
		Tick: 200
	damaged-idle-plug: gtpowrts_b
		Length: 12
		Tick: 200
	idle-powrupa: gtpowrts_b
		Length: 12
		Tick: 200
		Offset: -48, -24, 24
	damaged-idle-powrupa: gtpowrts_b
		Length: 12
		Tick: 200
		Offset: -48, -24, 24
	idle-powrupb: gtpowrts_b
		Length: 12
		Tick: 200
		Offset: -24, -12, 24
	damaged-idle-powrupb: gtpowrts_b
		Length: 12
		Tick: 200
		Offset: -24, -12, 24
	make: gtpowrtsmk
		Length: 20
		ShadowStart: 20
	emp-overlay: emp_fx01
		Length: *
		Offset: 0, 0, 25
		UseTilesetCode: false
		ZOffset: 512
		BlendMode: Additive
		-DepthSprite:
	icon: powricongdi
		Offset: 0, 0
		UseTilesetCode: false
		-DepthSprite:

**Comment by GraionDilach** [comment]
For the very same reason - the game expects gapowrtsmk on artctic. IIRC you mod RA2 though which also uses u on Urban.

@yaaaaa this isn't really the right place for your modding errors though. Try the forums instead.

**Pull request merged**
