### PR TITLE
Hotkey remap dialog

### LINKED ISSUE #3986: Keys Settings: it's possible to affect the same hotkey to several commands
It seems to be possible to affect the same hotkey to several commands. :-/
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1032086-keys-settings-it-s-possible-to-affect-the-same-hotkey-to-several-commands?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #13200: Be able to set NoKey('unknown') to a hotkey.
First off i noticed that when i remove all hotkeys in settings.yaml it gets rewritten with default values that doesnt even get written out in the file (if you change a hotkey in the game it gets added into settings.yaml)

Its a small concern but my biggest one is not being able to 'delete' a key ingame so its value becomes 'unknown' that some hotkeys have by default. Instead i have to move keys i dont use to a corner of my keyboard to isolate em out of my game. This might sound silly but i do not like hotkeys hotkeyed if i dont use em.

The 'unknown' value maybe can be set but if so i dont know how to. 

Also i dont think its reasonable you can have multiple things hotkeyed to same key. It should be overwritten and become 'unknown'.

### LINKED ISSUE #14670: No warning if a hotkey is used multiple times
There is no warning of any kind when you set a duplicate hotkey. The result is that all of the conflicting hotkey mappings stop working.

On playtest-20180102 but I assume this is also true for current release.

### LINKED ISSUE #16001: Hotkey widget UX improvements
The hotkey remapping widget is not very user friendly. There are several issues with it:
- There is no way for the user to cancel a remap in case of an input error 
- Hotkeys can not be cleared (set to an undefined state)
- An individual hotkey can not be reset to its default value
- There is no visual distinction between default and remapped keys
- Duplicate hotkeys can be set

Related issues: #14670, #3986, #13200

I will propose here a couple of approaches for how this widget can be reworked. 

### Inline variant
* **Rebind:** When clicking inside the input field the value starts blinking and a new hokey can be set
* **Accept:** A valid hotkey is automatically accepted
* **Cancel:** `Esc` key cancels the operation
* **Reset/Clear:** Reset and clear buttons are inside (or next to) the input as small icon-buttons; Default value is a slightly transparent color (like a placeholder); custom value is fully opaque; To reduce clutter these buttons should only show up when a remap is in progress;
* **Duplicate:** In case of a duplicate the input value changes to a red color and blinks until a proper key is set or the remap is cancelled
default

### Dialog variant
* **Rebind:** When a hotkey input is clicked a dialog opens up; The dialog has buttons for all possible actions: _Clear_, _Reset_, _Accept_ and _Cancel_
* **Accept:**: Click _OK_ or press `Enter`
* **Cancel:**: Click _Cancel_ or press `Esc`
* **Reset/Clear:** Reset and clear buttons are inside (or next to) the input as small icon-buttons; Default value is a slightly transparent color (like a placeholder); custom value is fully opaque;
* **Duplicate:** In case of a duplicate a warning message is displayed in the dialog and the _OK_ button is disabled
default

### PR DESCRIPTION
**Pull request by dragunoff**
Implement a hotkey remap dialog with validation (to prevent duplicate hotkeys) and buttons to unbind and reset to default.

d2k-hotkey-default
Default binding

d2k-hotkey-invalid
Invalid binding (can not be saved)

d2k-hotkey-valid
Valid binding (can be saved)

d2k-hotkey-reset
Cleared binding (sets the key to `UNKNOWN None`)

This probably needs and upgrade rule somewhere. I'm very much open to feedback (code and UI/UX related).

Closes #16001
Closes #14670
Closes #3986
Closes #13200

### CODE REVIEW

**Comment by abcdefg30** [comment]
Can we rename `Unknown` to `Unset` (or similar) in the UI (don't need to touch internals)? I think that is more clear.

**Comment by pchote** [comment]
IMO the usability of this would improve a lot the modification widgets were displayed inline instead of in their own popup. Right now you have to move the mouse ~100px up to interact with the dialog, and then ~100px back down when complete which isn't great especially if you want to change multiple keys in a row. We have a precedent for this in the behaviour of the lobby player/options/music/servers bin, and in particular the confirmation dialog when kicking or force-starting a game.

Crude mockup:

mockup

This also gives us room to display extra information if we want to, such as always displaying what the default hotkey is (it currently only says if it is currently set to the default), and perhaps even a text string defining what the hotkey does.

**Comment by dragunoff** [comment]
> 
> 
> Can we rename `Unknown` to `Unset` (or similar) in the UI (don't need to touch internals)? I think that is more clear.

Yeah, I was thinking of that too. "Unknown" is confusing. "Undefined" perhaps?

**Comment by dragunoff** [comment]
Update:
* Made the input field focuse upon opening the dialog
* Added a notice saying which is the default hotkey
* Fixed build error

**Comment by dragunoff** [comment]
> IMO the usability of this would improve a lot the modification widgets were displayed inline instead of in their own popup. Right now you have to move the mouse ~100px up to interact with the dialog, and then ~100px back down when complete which isn't great especially if you want to change multiple keys in a row. 
>
I have made the input field focused upon opening the dialog. This alleviates that problem a bit. 

> We have a precedent for this in the behaviour of the lobby player/options/music/servers bin, and in particular the confirmation dialog when kicking or force-starting a game.
>
The kick dialog is what you're suggesting here but IMO it's not great UI and won't bring much benefits over a dialog - the distance to travel with the mouse will be only slightly reduced. 


> This also gives us room to display extra information if we want to, such as always displaying what the default hotkey is (it currently only says if it is currently set to the default), and perhaps even a text string defining what the hotkey does.
>
We can make the dialog bigger if we want to display more info. 

After the discussion on discord and looking at the StarCraft II examples I'm starting to think about a dialogless solution. But in order to achieve that I think we need to pull the hotkey setting into their own tab because the current scroll panel is very claustrophobic.

**Comment by abcdefg30** [comment]
`Undefined` sounds good to me.

**Comment by dragunoff** [comment]
So, I pondered at the inline variant a bit. This may work. Here's a screenshot:

inline-hotkey-remap

The hotkeys are moved to their own tab to open up space for the dialog. The remap would be automatically saved if valid. If not valid it would keep blinking.

**Comment by dragunoff** [comment]
Closing in favor of #16552

**Pull request closed without merging**
