### PR TITLE
Fix D2k Trike and Raider muzzles

### LINKED ISSUE #9876: D2k, Trikes and Raiders muzzle anim no longer displays
As the title says, on playtest-20151031 the muzzle flashes don't appear.

Had a look into the yamls but couldn't see why myself.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27932246-d2k-trikes-and-raiders-muzzle-anim-no-longer-displays?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by reaperrr**
Weapons appear to need some warhead to fire at actors.

Closes #9876.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
Do we want a lint pass for that?

**Comment by GraionDilach** [comment]
Why not just simply `Damage` instead of the `Spread` variant if this is only for validation? That's better perfwise.

**Comment by reaperrr** [comment]
@GraionDilach I just tried, but that gives a NRE.

**Comment by GraionDilach** [comment]
Okay, nevermind and :+1: then.

**Comment by UberWaffe** [comment]
@GraionDilach @reaperrr As a sidenote: I encountered this same problem (directly applying ```Damage```).
There will have to be some overhaul / refactor of the warhead and projectile code to support this.

**Comment by GraionDilach** [comment]
Now that I look at it again, `DamageWarhead` is an abstract class - which is probably the sole reason.

**Comment by penev92** [comment]
:+1:

**Pull request merged**
