### PR TITLE
Make RA and TD aircraft reveal shroud from the point on the ground below them.

### LINKED ISSUE #12330: Aircraft reveals shroud/fog based on animation, not actual position.
Actual position meaning the cell the aircraft hovers above. It's a balance issue really. Aircrafts approaching from the south has a significant advantage due to being able to fire and being fired upon from the occupied cell. This concerns all mods.

Left vs Right, no difference.
gap1

Top vs Bottom, big difference.
gap2

AA Gun targeting range edging the Longbow's cell position (shadow).
gap3

Longbows' missile range based upon cell position.
gap4

This discrepancy plays out in all air to ground engagements giving the south position a significant advantage of about 2-4 cells (due to variable shroud rendering) in vision/targetting involving helicopters and even more so with YAK/MiGs which has an higher altitude - giving the south position a staggering 4-6 cells advantage.

This issue has probably gone unnoticed because of the shroud reveal visually looks logical from the placement of the animated aircraft.

### PR DESCRIPTION
**Pull request by pchote**
Fixes #12330.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Looks good to me. :+1:

**Comment by reaperrr** [comment]
👍

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/00e630390e58a0eb5473c15a5c48b1d21c386127...9d51402c80f0e1a1254e35b49a5b299e5ea5600f)

**Comment by SoScared** [comment]
Nice!! Super excited about this fix. Thanks pchote.

**Pull request merged**
