### PR TITLE
Add the unused 105mm medium tank cannon for TS

### LINKED ISSUE #19180: Add Yaml rules for Tiberian Sun 1tnk 2tnk 3tnk and ftnk
## Motivation

The RULES.INI in TS had the code for them.

## Proposed solution

I would add them but I don't have the time to learn git right now.

## Side effects

Extra complexity for the civilian-vehicles.yaml.

## Alternatives

Don't add them.

### PR DESCRIPTION
**Pull request by Leo512bit**
Adding the unused 105mm medium tank cannon which will start to resolve #19180

### CODE REVIEW

**Comment by Leo512bit** [comment]
Ahh somehow the readme.md got in there sorry about that 
edit: Okay I think its gone

**Comment by reaperrr** [comment]
This weapon doesn't exist in original TS. The Versus values also look really, really strange, there was no warhead in the original game with such values.

**Comment by Leo512bit** [comment]
> This weapon doesn't exist in original TS. The Versus values also look really, really strange, there was no warhead in the original game with such values.

Hmm thats odd its in my copy TS and was used by the medium tank should I close this PR?

**Comment by reaperrr** [comment]
> Hmm thats odd its in my copy TS and was used by the medium tank should I close this PR?

Yes, sorry. We appreciate the effort, but those were definitely not in the unmodified original, which we want to get as close as possible to before we even think about adding customized units and weapons. Original TS only had voxel files for those older TD/RA units, but no rules or art.ini entries, including this weapon.

**Pull request closed without merging**
