### PR TITLE
Add the size of the map to the Lua API

### PR DESCRIPTION
**Pull request by Mailaender**
This was asked for on @Discord.

### CODE REVIEW

**Comment by pchote** [comment]
These were deliberately rejected from the original Lua API, and the reasons for this haven't changed in the years since.

`Map.MapSize` is defined in `PPos` coordinates, which are equivalent to `CPos` for mods that don't use terrain height, but are *not* equivalent conceptually or in general. Scripts that attempt to use these to determine the edge of the map will break, and this will invariably increase the support burden that we have to deal with.

The `TopLeft` and `BottomRight` properties were included because there are some use cases where there is no better option (and the API description notes they will break), but for the case of the edge cells we expose several functions covering different use cases that always behave correctly. Map authors should be using these instead, or filing specific feature requests so that we don't have to work through the [XY problem](https://en.wikipedia.org/wiki/XY_problem).

**Comment by Mailaender** [comment]
The utility exposes this 

https://github.com/OpenRA/OpenRA/blob/6810469634d43a7a3e8ab2664942e162c3f4436a/OpenRA.Mods.Common/UtilityCommands/ResizeMapCommand.cs#L52

**Comment by Mailaender** [comment]
I found an example of this used

```lua
mapWidth = 32 --SETTING: Map Width
mapHeight = 32 --SETTING: Change this to your map's height

local centerPosition = WPos.New(1024 * mapWidth/2, 1024 * mapHeight/2, 0)
Camera.Position = centerPosition
```

The solution was just to hard-code it into a variable.

**Comment by pchote** [comment]
That example could have used the existing Map.TopLeft and Map.BottomRight and avoided hardcoding the factor of 1024 (which would break for isometric mods, where the scaling factor is 724 not 1024).

**Comment by Mailaender** [comment]
In that case it might be easier to just place a camera actor as you can't do math operations:
> attempt to perform arithmetic on field 'BottomRight' (a userdata value)

**Pull request closed without merging**
