### PR TITLE
Allow minelayer gain XP from mine kills

### PR DESCRIPTION
**Pull request by dnqbob**
Supersedes #21103.
[minelayer-test.zip](https://github.com/OpenRA/OpenRA/files/12848658/minelayer-test.zip) as test map.

### CODE REVIEW

**Comment by dnqbob** [comment]
I separate parent recording as `HasParent` for better extension and third party mod support.

For example, we can pass the kill to parent in `GivesExperienceToMaster` to allow summoned actor give XP to parent:
new-exp
new-exp2

**Comment by PunkPun** [comment]
All traits have access to inits, I don't see why HasParent trait is necessary

**Comment by dnqbob** [comment]
> All traits have access to inits, I don't see why HasParent trait is necessary

in `HasParent`, we will pass the parent actor when actor transforms itself.

For example, we have spawned actor A use trait like "TransformsNearResources" to transform itself as unit B at certain condition. If we don't has HasParent, then we cannot pass parent actor correctly. 
transfrom-problem

In the picture, egg transform into creep and still gives parent XP when kill. Egg only need a trait to pass the parent with no other function, so `HasParent` is born to solve this parent transfer issue.

**Comment by dnqbob** [comment]
On the other hand, if we has the `ITransformActorInitModifier` interface for every trait related to parent in order to pass parent on to the new actor, then `ParentActorInit` will be constructed and given multiple time when transform, which is unnecessary.

**Comment by PunkPun** [comment]
HasParent trait can definitely exist to pass inits, but it should definitely not be used directly. Explodes should fully relly on inits

Also, if we are to add this trait it needs a better name. I can't think of a good one atm

**Comment by PunkPun** [comment]
Perhaps traits that transform a unit should be in charge of keeping this init

**Comment by dnqbob** [comment]
Then it would be headache that every transform trait needs to record parent, and Transform activity needs a parameter to recieve parent actor specifically.

Moreover, there can be many way to spawn actor, maybe later they all need interface like this to pass some trait information from spawner actor (for example, we spawn a pilot with rank when a aircraft with rank is killed) to created actor. Pass&record parent actor will also be a problem here.

**Comment by dnqbob** [comment]
Another reason of refusing store parent individually is,

Suppose that we make a trait which is called "GiveXPToParent", and we have many spawner traits on spawning the actor, even actor that spawned from warhead needs a trait to store parent.

To simplify, we have following trait on spawned actor store parent:
1. `SpawnerChild` series, for aircraft carrier or infantry using drones.
2. `HasParent` for actor spawned by warhead or death spawn. Just a single trait.
3. `Transform` series

Then when actor dead, **"GiveXPToParent" will have to search all these traits (in this case, it is `SpawnerChild` series, `Transform` series and `HasParent`) to find the parent**. That will be a disaster in both performance and maintaining.

One may say we could use a `IHasParent` on those traits. Yeah, it solve the problem of coding and maintaining, but once again, **why do we need all of these traits to store the parent when "GiveXPToParent" only need one valid parent when iterating?** Should not we only store the parent once and use it once?

**Comment by dnqbob** [comment]
The concept of keeping parent is not correct for `Transform` series, either. `Transform` should not care about if the previous actor has anything needs to pass on, as it should not care about if the previous actor has XP needs to pass on. It should only care about that it need to change the new actor according to `ITransformActorInitModifier`.

**Comment by PunkPun** [comment]
I'd merge this PR now if HasParent was removed

**Comment by dnqbob** [comment]
I am still in favor of my old stuff here, maybe let this PR be a idea showcase on using `ParentActorInit`.

**Comment by PunkPun** [comment]
We are not keeping PR's just for show. I can reiterate that I'm not against adding a trait with the functionality of `HasParent`, but it just needs to have a better name and `Explodes` should be using inits instead of the trait

**Comment by dnqbob** [comment]
I think it is better that we use a specific trait for mine explodes for now, bring #21103 back.

**Pull request closed without merging**
