### PR TITLE
Cached the NSIS installation on AppVeyor CI

### PR DESCRIPTION
**Pull request by Mailaender**
Following the advice of https://www.appveyor.com/docs/build-cache#caching-chocolatey-packages

### CODE REVIEW

**Comment by Mailaender** [comment]
Looks like https://sourceforge.net/ is down for the moment.

**Comment by Mailaender** [comment]
Restarted the build. Everything seems to be fine now.

**Comment by GraionDilach** [comment]
:+1:

**Comment by obrakmann** [comment]
:+1:

**Pull request merged**
