### PR TITLE
Remove CNC95Launcher.exe from the IDFiles of the origin cnc install

### LINKED ISSUE #15445: Investigate reports of the Origin (TUC) asset installation failing
I suspect that they may have released an update that changes `CNC95Launcher.exe`.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #15445.

### CODE REVIEW

**Review by GraionDilach — DISMISSED** [review]
:+1:

**Review by pchote — DISMISSED** [review]
Confirmed that this fixes #15445, but the same fix is required for RA and TS before we merge.

**Comment by abcdefg30** [comment]
Updated.

**Review by pchote — DISMISSED** [review]
Missed the `cnc-origin` definition at the bottom of RA's origin.yaml.  Can you please update this too?

**Comment by abcdefg30** [comment]
Good catch. Updated.

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/7f2ebebf5a38006ec7c0e433b2864317ec940489...42263c0effa865257bc92c68f0b003de9c1a4619)

**Pull request merged**
