### PR TITLE
D2K - Fixed some tiles

### PR DESCRIPTION
**Pull request by MustaphaTR**
That two tiles are Cliff-Type-Changer and sorted at false place. Also they are cliff but their tiles were Rough.
adsiz

### CODE REVIEW

**Comment by penev92** [comment]
I don't really agree with either of the changes (category and type) for both tiles.

**Comment by penev92** [comment]
`Rough` is terrain only infantry can move on. `Cliff` (I believe) is unpassable?
Also `Sand-Cliff` are rocks on the sand. `Cliff-Type-Changer` is where the terrain changes from sand to solid rock.
From the screenshot I'd say these are exactly `Rough sand-cliffs`. If you have a reason to think otherwise - I'm open.

**Comment by MustaphaTR** [comment]
I'm sure they are Cliff-Type-Changer and Unpassable Cliff at orginal game. Look Pasty Mesa at Orginal D2K and OpenRA. There is one of this tiles at Right Top base.

**Comment by penev92** [comment]
I'll have to consult the Dune 2000 tilesets (the originals) and check some maps before commenting further.

**Comment by obrakmann** [comment]
Played a bit with this in the editor, and it seems to do the right thing.  These two tiles indeed switch from a sand-cliff to rock-cliff. :+1:

**Comment by penev92** [comment]
OK, so after finally finding Pasty Mesa in the Dune 2000 maps, I compared [original](http://i.imgur.com/nCX8BR2.jpg) to [our](http://i.imgur.com/qX1x6wM.jpg).
Found left tile at the bottom left corner of the top right base.
I'm convinced about the category.
But a quick test game of the original showed that frames 13 and 33 should be `Transition`, not `Cliff`.
I assume the same is true for frames 15 and 35.
I'll give a thumb up after this is changed.

**Comment by MustaphaTR** [comment]
Updated

**Comment by penev92** [comment]
:+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/fa145b1d74ad2d54ae0c569c5b209c3ffbf4508d%5E...fa145b1d74ad2d54ae0c569c5b209c3ffbf4508d)

**Pull request merged**
