### PR TITLE
Integrate global chat with the lobby.

### PR DESCRIPTION
**Pull request by pchote**
The next step towards #9451.  A future PR will add unread message counts to the tab labels, but that depends on some wider widget refactoring that will come in the next PR.

### CODE REVIEW

**Comment by obrakmann** [comment]
The two 'disconnect' buttons right next to each other irk me. Can we change the label on one of them (I'd probably go with 'Leave [match|game|lobby]')?
screenshot from 2015-10-20 21 13 24

**Comment by pchote** [comment]
In TD we use "Back" for skirmish, and "Leave Game" for MP.  I never noticed that RA used different terminology.  I'll change them to match TD, and then use "Leave Chat" for the IRC button.

**Comment by pchote** [comment]
Updated.

**Comment by MicroJOo** [comment]
this works :+1:

**Comment by pchote** [comment]
Rebased.

**Comment by obrakmann** [comment]
What do you think about making the buttons all the same width? It pleases my OCD ;)

screenshot from 2015-10-21 20 47 25

Diff:
```diff
index bf0c684..de45eb0 100644
--- a/mods/ra/chrome/lobby.yaml
+++ b/mods/ra/chrome/lobby.yaml
@@ -124,16 +124,16 @@ Background@SERVER_LOBBY:
                        Width: PARENT_RIGHT - 40
                        Height: 229
                Button@START_GAME_BUTTON:
-                       X: PARENT_RIGHT - WIDTH - 150
+                       X: PARENT_RIGHT - WIDTH - 205
                        Y: PARENT_BOTTOM - HEIGHT - 20
-                       Width: 120
+                       Width: 172
                        Height: 25
                        Text: Start Game
                        Font: Bold
                Button@DISCONNECT_BUTTON:
                        X: PARENT_RIGHT - WIDTH - 20
                        Y: PARENT_BOTTOM - HEIGHT - 20
-                       Width: 120
+                       Width: 172
                        Height: 25
                        Text: Leave Game
                        Font: Bold
```

**Comment by pchote** [comment]
The button widths are matched to the map chooser, and (will be matched to) the new server browser, so that ends up being a rather major style change.  The current button widths / positions are consistent across most of the UI panels.

**Comment by obrakmann** [comment]
hmm... ok. maybe we can come up with another solution eventually. for now, :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/427df889772cc4a4ab35c4d386d7e2063d3b7545)

**Pull request merged**
