### PR TITLE
Removes paradrop and carryall.infantry from D2k

### PR DESCRIPTION
**Pull request by reaperrr**

### CODE REVIEW

**Comment by Mailaender** [comment]
It stayed there as a placeholder for too long I guess. :+1:

**Comment by penev92** [comment]
You'll also want to remove the 3 `SupportPowerDecision@Paratroopers:` from `ai.yaml` and tweak the `Targetable:` trait on `^Infantry:` to not care about a "parachute" upgrade.
Also remove the `Parachutable:` and `WithParachute:` traits.
Also cleaning up the sequences (`misc.yaml`) from both occurances of "para" would be nice, and you can then remove `\d2k\bits\parach-shadow.shp`.

**Comment by penev92** [comment]
:+1:

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/cf2e1166d2c248180c12ea24fd3b610eca7ba6e4...539d06bc3fa2ea92a5a151efc49c4278c37eb0eb)

**Pull request merged**
