### PR TITLE
Optimize aircraft repulsion a little

### PR DESCRIPTION
**Pull request by reaperrr**
See commit description.

### CODE REVIEW

**Comment by pchote** [comment]
Repulse is *supposed* to already do this, see: 
https://github.com/OpenRA/OpenRA/blob/b774556a5f41310393915fa036a5b6731f9a689c/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L372-L375

Can we identify why this has broken and fix it instead?

**Comment by reaperrr** [comment]
Huh, hadn't seen that. I can't reproduce the issue on bleed, either. Maybe in #16470 the repulsion triggers before the aircraft starts to descent.

Anyway, we can still turn this PR into a minor clean-up/perf optimization, by re-using the `cruising` boolean instead of doing another DAT check in `GetRepulsion()`, and checking for `WVec.Zero` in `Repulse()` makes more sense, too (most returns in `GetRepulsion` return exactly that, and the rest should never return a Z value other than zero either, so this saves us a WVec -> HorizontalLengthSquared conversion).

**Comment by matjaeck** [comment]
It looks like something has fixed the weird repulsion behavior that I noticed while testing #16241 (https://imgur.com/a/x8HonbW / https://imgur.com/a/EwLyZfX, [log](http://logs.openra.net/?year=2019&month=03&day=31#21:11:58)).

**Review by pchote — APPROVED** [review]

**Review by teinarss — APPROVED** [review]
Looks good!

**Pull request merged**
