### PR TITLE
Change TS service depots footprint

### LINKED ISSUE #16465: Polish ts service depot footprint
You can currently dock at the service depot through the bay with the roboter arm. This section of the footprint should IMO be impassable.

### PR DESCRIPTION
**Pull request by PunkPun**
Closes #16465

### CODE REVIEW

**Comment by reaperrr** [comment]
> This makes service depot passable by units

Not making it passable like that was intentional, partially because that's how it was in the original and partially to prevent larger numbers of vehicles clogging it up too much, potentially blocking vehicles that try to enter it for repairs.

Might not be that much of an issue anymore with the improvements to nudging we've recently had, but at the very least something to keep in mind while testing this (and while deciding whether we take this as a whole or only the fix for #16465).

**Comment by matjaeck** [comment]
> Not making it passable like that was intentional, partially because that's how it was in the original 

#16934

**Comment by MustaphaTR** [comment]
Shouldn't it be `x== x== x==`?

**Comment by Punsho** [comment]
> Shouldn't it be `x== x== x==`?

Screen Shot 2019-09-15 at 19 04 20 

there's nothing there to block movement

**Comment by GraionDilach** [comment]
That cell was still blocked in the WW game, regardless of the artwork. `NumberOfImpassableRows` had no way to affect a single cell within a row and all used foundation were box foundations.

**Comment by tovl** [comment]
I don't think this really closes #16934 unless we also do it for the other mods or there is a clear reasoning why it should only be a feature in TS.

As far as units clogging up the depot: #16408 should have made sure that gridlocks won't occur under any realistic circumstances.

**Comment by abcdefg30** [comment]
> I don't think this really closes #16934 unless we also do it for the other mods or there is a clear reasoning why it should only be a feature in TS.

👍

**Comment by Punsho** [comment]
I didn't realise that all other service depots were impassable too. I'm reducing this pr to just fixing #16465 and leaving discussion down to #16934

**Comment by tovl** [comment]
This doesn't actually solve the issue. The unit can still drive through the repair arm when ordered to repair. This is because the entire repairbay gets ignored by the `MoveTo` in `Resupply`.

**Comment by Punsho** [comment]
Then one of the solutions is the solutions is to make the sd itself passable and make resupply not ignore impassable cells.

**Comment by Punsho** [comment]
superseded by #17141

**Pull request closed without merging**
