### PR TITLE
Polishing up mission UI

### PR DESCRIPTION
**Pull request by PunkPun**
- Fixing a glitch when in mission browser when switching missions briefing can flicker when in options panel
- Fixing database covering up the mission load button in TD
- Fixing common mission objectives panel not being adjusted to the new size of ingame menu. #20100

Please do not ask for scope creep in this PR

### CODE REVIEW

**Review by dragunoff — APPROVED** [review]
LGTM :+1:

**Comment by pchote** [comment]
Seems a bit odd to fix the encyclopedia button in TD but then leave the panel that button opens broken!

**Review by pchote — APPROVED** [review]
LGTM otherwise

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/c726d924402881c35787af8a6d76108ed0b4fc14

**Pull request merged**
