### PR TITLE
Add target validation to GrantUpgrade warheads.

### PR DESCRIPTION
**Pull request by GraionDilach**
This seems like a bug to me.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Forget this, I overlooked it.

**Comment by GraionDilach** [comment]
It's okay now.

**Comment by chrisforbes** [comment]
:+1:

**Comment by chrisforbes** [comment]
Can you send another PR that removes the 0% assumptions from the mods?

**Comment by GraionDilach** [comment]
If it doesn't conflict with @penev92"s plans, I can look into it.

**Comment by penev92** [comment]
I actually don't know what those comments refer to.

**Comment by GraionDilach** [comment]
In the Westwood games, 0% versus on the warhead would not just make the target immune to the weapon, but also untargetable. Achieving this via TargetTypes only would be a lot more elegant.

**Comment by penev92** [comment]
Looks reasonable :+1:

**Pull request merged**
