### PR TITLE
Fix SAM shapes & targetable offsets in RA/TD

### LINKED ISSUE #13713: [RA - Playtest] SAM ought to have a single hitpoint.
As the only heavy armor structure affected by the new hitshapes it ought to retain a single target point. Rebalancing AoE damage output vs heavy armor isn't happening.

openra 2017-07-24 16-06-00-05

Might also be solved through #13675

### PR DESCRIPTION
**Pull request by reaperrr**
TD:
tdsam

RA:
rasam

Closes #13713.

### CODE REVIEW

**Comment by ltem** [comment]
👍 works as displayed

**Review by ltem — APPROVED** [review]

**Comment by reaperrr** [comment]
Pinging @SoScared for testing/review.

**Comment by SoScared** [comment]
Damage wise the issue is resolved but the reduced hitshape (2-cells rectangle to 1-cell square centered between cells) has resulted in units' weapon range to drop 1 cell range vs the SAM.

Balance wise the side-effect seem pretty negligible but might be regarded as awkward as units will move and target it last if the SAM is lined up with other targets, especially medium/heavy/mammoth tanks' weapons with their range being 4c768 meaning the discrepancy will be noticeable from more angles compared to "whole" numbered range values (4c0, 5c0, 6c0...).

I don't fully understand how the hitshape mechanism work still but is it possible to retain the 2-cell rectangle hitshape but still only 1 hitpoint? I guess that's sort of how it works in the release.

**Comment by reaperrr** [comment]
> I don't fully understand how the hitshape mechanism work still but is it possible to retain the 2-cell rectangle hitshape but still only 1 hitpoint? I guess that's sort of how it works in the release.

That's technically possible, but range is now calculated from the closest hitpoint, whereas it was calculated from closest cell center in previous releases, so it wouldn't fix the range problem.

What I could try - instead of just a single hitpoint and 1-cell shape - would be compressing the shape and side-hitpoints to match the *visual* size of the sam site.
That would still make it a bit larger than other defenses, but not nearly as much as on the playtest, and maybe reduce the difference enough that it doesn't matter anymore, balancing-wise.

**Comment by reaperrr** [comment]
@SoScared I've pushed a test branch here: https://github.com/reaperrr/OpenRA/tree/fix-sam-shapes-test
sam-shape2

**Comment by SoScared** [comment]
Hmm. Same results. I'm guessing the weapons range only recognizes the hitshape border when it fills up the targeted cell 100%. Pretty tough to explain but visualized in the image below it's compared to the hitshape of a "fully celled" Gun Turret hitshape.

uten navn

**Comment by reaperrr** [comment]
I see what you mean, but the only way to avoid that is to leave the target positions like they are on bleed/playtest, and just make the hitshape rectangle a little less wide vs. bleed/pt. Note that in this case we can't shrink the shape as much vs. bleed as in the above example, though, since slightly inaccurate weapons like most missiles could then occasionally land outside the shape and deal less than full damage.

**Comment by SoScared** [comment]
I can't say I understand it but it looks to me then you have a choice between a balance change and a design flaw. In case of the former the SAM would be weaker vs AoE damage but I feel like that's more preferable vs players experiencing inconsistent unit behavior around it.

For what it's worth, if I get my way on the latest balance patch the SAM will have a +1 vision upgrade and $50 price reduction.

Just out of curiosity, what would happen if, or is it possible, the hitshape rectangle stayed as per playtest but with only _one_ target position in the middle?

**Comment by reaperrr** [comment]
> Just out of curiosity, what would happen if, or is it possible, the hitshape rectangle stayed as per playtest but with only one target position in the middle?

Then the range issue would persist, and the higher AoE vulnerability would stay, too.

The target positions are responsible for weapon range calculations, not the shape (if distance between attacking actor and closest target point is less than weapon range, the attacker will move one cell closer).
The shape is only responsible for damage calculations (the closer the impact is to the closest shape edge/corner, the higher the damage will be, an impact inside the shape will deal 'full' damage (max damage the warhead can deal vs this armor type).

**Comment by reaperrr** [comment]
Updated PR.

Now the targeted points don't change, only the shape is shrinked by 1/4 cell on each horizontal side.
That should bring AoE vulnerability closer to other defenses without affecting the distance from which they can be attacked.

I also bumped the RA SAM HP up from 400 to 420, but I'll leave it to @SoScared to decide whether than change should go in or not.

**Comment by SoScared** [comment]
Ah ok nice, I understand how it works now, thanks.

I think it better to keep the HP at 400. My approach has always to keep values whole and relateable to a certain class as much as possible, in this case the SAM, AAGun, Pillboxes, Gun Turret , Tesla Coil and Flame Tower all have 400HP (Also why I dropped C.Pillbox back down to 400HP from 450).

**Comment by reaperrr** [comment]
Ok, dropped the HP change.

**Comment by SoScared** [comment]
:+1: Decent improvement on the playtest SAM.

Just for future reference I noticed the latest commit target points positions moved a few pixels towards the edges compared to the playtest which suggest there are room to fiddle with these in the future.

**Review by SoScared — APPROVED** [review]

**Comment by abcdefg30** [comment]
@AoAGeneral any comment on the TD SAM Site change here?

**Comment by AoAGeneral** [comment]
No comment here. Changes work in favor of TD and don't have any range issues in regards to ground units.

Nice buff vs the airstrikes as well. ^^

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/ec4d1ac5c5dd87f4e21ced816e33d094c03f9528...b21cfa6d3af2187e34e6b8658167cc4aa9c6697c)

https://github.com/OpenRA/OpenRA/commit/17b4158a56df4d61568c0f40817ff0f8da8a81b4
https://github.com/OpenRA/OpenRA/commit/5e0a789dac8dee7463376921580113abe6bae683

**Pull request merged**
