### PR TITLE
Added Dock Uncloak type.

### LINKED ISSUE #10991: Cannot add uncloaking of harvesters in mod when docking
I am making a C&C3-like mod for TD and I have made steath harvesters for Nod. They must uncloak when they are docking to a refinery but there isn't a property for that in `Cloak` trait.
screenshot_2016-03-28_16-53-31

### PR DESCRIPTION
**Pull request by ghost**
Closes #10991.

### CODE REVIEW

**Comment by GraionDilach** [comment]
:+1:

**Comment by Phrohdoh** [comment]
`Dock` needs to be appended to the description as an option.

Unfortunately I cannot confirm this working as I cannot get my harv to cloak.
```diff
diff --git a/mods/cnc/rules/vehicles.yaml b/mods/cnc/rules/vehicles.yaml
index 04984c3..118f675 100644
--- a/mods/cnc/rules/vehicles.yaml
+++ b/mods/cnc/rules/vehicles.yaml
@@ -76,6 +76,8 @@ HARV:
 		Weapon: TiberiumExplosion
 	SelectionDecorations:
 		VisualBounds: 36,36
+	Cloak:
+		UncloakOn: Dock
 
 APC:
 	Inherits: ^Tank
```

**Comment by dtluna** [comment]
I have tested `UncloakOn: Dock` in my [mod](https://gitgud.io/dtluna/kw/) and it works as intended.

**Comment by obrakmann** [comment]
The way other traits interact with `Cloak` is kinda inconsistent now. Some traits check for the `Cloak` trait directly and call `Uncloak()` on their own, in other cases - such as this - `Cloak` implements interfaces and code itself that provides the interaction. Maybe we should replace all those with an `IPreventsCloaking` interface. But for now, this is fine, :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-%28bleed%29/_compare/504026b67097b030830080c4ab6f8954c0797fb5)

**Pull request merged**
