### PR TITLE
Populate MapLocations from LoadMaps.

### LINKED ISSUE #14066: Unable to install maps in lobby on Ubuntu (playtest-20170923)
Maps will fail to install on the latest round of playtests (`playtest-20170722` though `playtest-20170923`). They installed fine on the latest release (`release-20170527`). I'm running the playtest on Ubuntu 16.04 and the playtest installation has replaced the release. 

The problem seems to be folder permissions as the map folders are owned by `root`. 

screenshot from 2017-09-24 17-34-16

Here is the exception log:
```
OpenRA engine version playtest-20170923
Tiberian Dawn mod version playtest-20170923
Date: 2017-09-24 13:43:58Z
Operating System: Linux (Unix 4.4.0.96)
Runtime Version: Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) CLR 4.0.30319.17020
Exception of type `System.UnauthorizedAccessException`: Access to the path "/home/username/.openra/maps/cnc/playtest-20170923/Dont_Mess_It_Up-1.oramap" is denied.
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x7f25480dd2c0 + 0x005ed> in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) <0x7f25480dcf80 + 0x0004d> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.Create (System.String path, Int32 bufferSize) <0x7f25480da000 + 0x0003b> in <filename unknown>:0 
  at System.IO.File.Create (System.String path) <0x7f25480d9fe0 + 0x00011> in <filename unknown>:0 
  at OpenRA.FileSystem.Folder.Update (System.String filename, System.Byte[] contents) <0x405d5ae0 + 0x00090> in <filename unknown>:0 
  at OpenRA.MapPreview+<Install>c__AnonStorey2+<Install>c__AnonStorey3.<>m__1 (System.Net.DownloadDataCompletedEventArgs i) <0x405d5890 + 0x0013f> in <filename unknown>:0 
  at OpenRA.Download+<Download>c__AnonStorey1.<>m__1 (System.Object _, System.Net.DownloadDataCompletedEventArgs a) <0x405a0220 + 0x0002f> in <filename unknown>:0 
  at System.Net.WebClient.OnDownloadDataCompleted (System.Net.DownloadDataCompletedEventArgs e) <0x405a01d0 + 0x00035> in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataOperationCompleted (System.Object arg) <0x405a0150 + 0x00050> in <filename unknown>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) <0x7f2548035720 + 0x00048> in <filename unknown>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f254802f850 + 0x0016e> in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x7f254802f820 + 0x00020> in <filename unknown>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x7f25480356b0 + 0x00053> in <filename unknown>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x7f2548033cc0 + 0x001d6> in <filename unknown>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x7f2548035530 + 0x00008> in <filename unknown>:0 
```

### PR DESCRIPTION
**Pull request by pchote**
Fixes #14066 and https://github.com/OpenRA/OpenRA/issues/13922#issuecomment-326042177. 

Test deb package: [Dropbox](https://www.dropbox.com/s/xetqxm17e2m57kn/openra_test.20170626_all.deb?dl=1)

### CODE REVIEW

**Review by reaperrr — APPROVED** [review]
Code looks good to me

**Comment by pchote** [comment]
Note that I did test this myself before opening the PR.

**Review by phrohdoh — APPROVED** [review]

**Review by Mailaender — APPROVED** [review]
I can confirm that this fixes #13922.

**Comment by Mailaender** [comment]
No RPM test package due to https://github.com/openSUSE/open-build-service/issues/3930, but I tested a local build.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/commit/c4239fd16eb816d5fbd22a58717a2c308727d349

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2614e763116f1923d41589d2f5e365983e5c825f

**Pull request merged**
