### PR TITLE
Disable sync reports when we know we won't need them.

### PR DESCRIPTION
**Pull request by pchote**
See commit message for details.

Desyncs in MP are now very rare, so I plan on disabling these by default in MP too after implementing #4084 and adding a server flag so that we can turn them back on without shipping a new release if any desyncs return in the future.

### CODE REVIEW

**Comment by pchote** [comment]
For context, the regular large spikes in


are caused entirely by the report generation.

**Comment by RoosterDragon** [comment]
Thought for if you do disable reports by default for MP: If `DumpSyncReport` doesn't have the a report for the frame in question. Is it worth generating a report for the current frame and dumping that (with a warning in the report to indicate as such) just in case the reports from several players happen to generate for the same frame? I'm wondering if that might prove useful on occasion even if per-frame reports are turned off.

**Comment by pchote** [comment]
Good idea

**Comment by RoosterDragon** [comment]
:+1:

**Comment by RoosterDragon** [comment]
Two tangential thoughts:
- Why does the `SyncReport` class maintain the last 5 reports? If everything is in lockstep wouldn't the last report be sufficient?
- If we do change reports to not run every frame, we should remove the `if (hash != 0)` checks in `GenerateSyncReport`. These make perf even worse (hence why I don't suggest this now) but fix a correctness issue.

**Comment by pchote** [comment]
> * Why does the `SyncReport` class maintain the last 5 reports? If everything is in lockstep wouldn't the last report be sufficient?

We are not quite lockstep, but instead transfer/simulate ticks in groups of three.  In a 3p game you may therefore have two players who agree having simulated to N+1 before they realize that the other player desynced on tick N.

I don't know why we made this choice, hopefully @chrisforbes can chime in here.  If we can eliminate the aggregate netticks then we would be able to eliminate this completely and generate the reports only on an actual desync.

**Review by RoosterDragon — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/cb49146506efd20c4fbb5f6b9f4365714e425c24...df0f25ffe4a81007310567517efdd088598ad512)

**Pull request merged**
