### PR TITLE
Exposed muzzle sequence (prefix) to lint testing

### PR DESCRIPTION
**Pull request by Mailaender**
I have to account for `MuzzleSplitFacings` in this case.

### CODE REVIEW

**Comment by pchote** [comment]
Can you elaborate on the description - is this a self-request for changes?

**Comment by Mailaender** [comment]
A limitation of the current system. I would rather add something like `[SequenceReference(null, MuzzleSplitFacings > 0)]` but that won't work. This is better than nothing imho.

**Comment by pchote** [comment]
That limitation can be solved by copying [this example](https://github.com/OpenRA/OpenRA/pull/18007#issuecomment-623182799). Change `CheckSequences` to support properties, then add a linted dummy property to `Armament` that returns the muzzle sequence if `MuzzleSplitFacings > 0`, otherwise nothing.

**Comment by pchote** [comment]
#18067 made me realize that a better course of action here would be to remove `MuzzleSplitFacings` completely, and combine the sprites using a `Combine` block in the sequences instead.

**Comment by Mailaender** [comment]
I had to write a complicated update rule, but I think it was worth it. This is a followup of https://github.com/OpenRA/OpenRA/pull/9664 now.

**Comment by abcdefg30** [comment]
Needs a rebase and the update rule placed in path the subfolder.

**Comment by Mailaender** [comment]
Rebased.

**Review by abcdefg30 — COMMENTED** [review]
Something doesn't seem right with the muzzle sequences compared to bleed. (They flash to short while I can see the animation on bleed.)
Regarding the update rule: Can we make it report the yaml locations in the sequence files (like we do in other rules)? The current output doesn't look to helpful to me tbh:
```
RemoveMuzzleSpitFacings: MuzzleSplitFacings was removed.
   Updating mod... COMPLETE
   Updating system maps... COMPLETE
   Manual changes are required to complete this update:
    * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\1ice6:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\2temp7:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\arivruns:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\cliffsin:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\drawbrid:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\fields-of-green:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\float:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\forestfr:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\karasjok:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\ot11:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\rivrrad4:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\springs:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\sunstroke:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\tactical:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\terrace:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\ThePit:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\tiers:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\tread_l:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\ts_rift:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\t_garden:
       * You need to manually set the sprite length of each combined muzzle frame.
    * Map: \OpenRA\mods\ts\maps\uganda:
       * You need to manually set the sprite length of each combined muzzle frame.
```

**Comment by Mailaender** [comment]
Rebased, added sequence.yaml locations to the update rule and fixed the length of the Tiberian Sun muzzle.

**Comment by pchote** [comment]
We don't gain much by trying to be clever in the update rule, and this will actually fail if the actor uses faction-specific artwork or other `RenderSprites` overrides to change the `Image` to something other than the actor name. Can we please instead do 1e8dd0502bae75612e75e3486bfea5435d89ae92 as a simpler and more robust/correct approach for the update rule?

**Comment by Mailaender** [comment]
Merged your "requests".

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/36c314094fc7f2d47401976d196acceffbce66c5...55e8048153a466e58ca685251f6d4c466bb53dad)

**Pull request merged**
