### PR TITLE
Fix map editor radar ignoring color from terrain

### LINKED ISSUE #18212: Map Editor ignores RadarColorFromTerrain
It is more apparent when trees :evergreen_tree: are green and the owner is white neutral:

### Editor

image

### Thumbnail

image

### PR DESCRIPTION
**Pull request by nikitapozdeev**
Hi. I'm new here, not sure if this is the best way to fix the bug.
These changes Fixes #18212 issue.

### CODE REVIEW

**Review by Mailaender — DISMISSED** [review]
Works as promised and the code changes look tidy.

**Review by Smittytron — DISMISSED** [review]

**Comment by Mailaender** [comment]
Needs a rebase.

**Comment by nikitapozdeev** [comment]
> crabn3bula dismissed stale reviews from Smittytron and Mailaender

It seems like I did something wrong when I did rebase? Excuse me

**Comment by abcdefg30** [comment]
> It seems like I did something wrong when I did rebase? Excuse me

Don't worry, that is normal behaviour when the branch is force pushed.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a6803b4613cf56d1ceef3119597930fd1721a400...f80f26284cf29cdfed9098eba2592e7c005cacfe)

**Pull request merged**
