### PR TITLE
Restore threaded renderer on Windows in windowed mode.

### PR DESCRIPTION
**Pull request by RoosterDragon**
Previously, when running in windowed-mode on Windows, the threaded renderer would cause the minimize/restore behaviour to become unreliable. It was disabled under this configuration to avoid the problem.

This no longer occurs (perhaps fixed by an intervening SDL update?), so we can remove the workaround and always use the threaded renderer for a performance improvement.

### CODE REVIEW

**Comment by PunkPun** [comment]
#19698

**Comment by PunkPun** [comment]
#15422

**Review by penev92 — APPROVED** [review]
YOLO, I guess?
(I can't reproduce the original issue)
image

**Comment by penev92** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/f3554172a93be064c18be608df5a0c167542e7d4...95842a0e7be037a07ea943b68f68c145be7ccae4)

**Comment by abcdefg30** [comment]
I can still reproduce this locally, but everything seems to work fine running the playtest builds.

**Pull request merged**
