### PR TITLE
Add a bin directory for generated binaries

### PR DESCRIPTION
**Pull request by pchote**
This PR backports the bin output directory change from #17989 for the playtest. A new `Engine.EngineDir` argument is supported for the game and server, and an `ENGINE_DIR` environment variable for the utility. These can be used to specify the engine root directory as a different location from the binaries.

The special `^` and `.` file path prefixes have been replaced with the more obvious `^SupportDir|` and `^EngineDir|`, and a new `^BinDir|` variable. These look like explicit mounts, but for now are implemented in `Platform.ResolvePath`. At some point in the future we can hopefully move these into the filesystem code as real explicit mounts, removing `ResolvePath` completely.

Depends on #18844. Again, this PR should be straighforward to review provided you go commit by commit.

Test builds: https://github.com/pchote/OpenRA/releases/tag/devtest-20201121-5

### CODE REVIEW

**Comment by pchote** [comment]
Updated:
* Fixed dedicated servers
* Fixed EngineDir not being passed through mod metadata

Updated test build: https://github.com/pchote/OpenRA/releases/tag/devtest-20201121-5

**Comment by abcdefg30** [comment]
Needs a rebase now.

**Comment by pchote** [comment]
Rebased.

**Comment by teinarss** [comment]
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=File not found: temperat.pal
  Source=OpenRA.Game
  StackTrace:
   at OpenRA.FileSystem.FileSystem.Open(String filename) in C:\projects\OpenRA\OpenRA.Game\FileSystem\FileSystem.cs:line 208
   at OpenRA.Mods.Common.Traits.PaletteFromFileInfo.OpenRA.Traits.IProvidesCursorPaletteInfo.ReadPalette(IReadOnlyFileSystem fileSystem) in C:\projects\OpenRA\OpenRA.Mods.Common\Traits\World\PaletteFromFile.cs:line 48
   at OpenRA.Graphics.CursorProvider.<>c__DisplayClass2_1.<.ctor>b__4(String p) in C:\projects\OpenRA\OpenRA.Game\Graphics\CursorProvider.cs:line 41
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.Graphics.CursorProvider..ctor(ModData modData) in C:\projects\OpenRA\OpenRA.Game\Graphics\CursorProvider.cs:line 38
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem) in C:\projects\OpenRA\OpenRA.Game\ModData.cs:line 136
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in C:\projects\OpenRA\OpenRA.Game\Game.cs:line 448
   at OpenRA.Game.Initialize(Arguments args) in C:\projects\OpenRA\OpenRA.Game\Game.cs:line 401
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\projects\OpenRA\OpenRA.Game\Game.cs:line 270
   at OpenRA.Program.Main(String[] args) in C:\projects\OpenRA\OpenRA.Game\Support\Program.cs:line 31
``

**Comment by pchote** [comment]
~How are you launching the game to trigger that?~

Confirmed on IRC that this only happens when the RA mod (others are fine) is launched with a different working directory to the engine dir.

**Comment by pchote** [comment]
Fixed. I had forgotten to replace `.` with `^EngineDir` in the `ra` and `all` mod.yaml, which meant that the game couldn't find `global mix database.dat` when launched from a different working directory, which meant that it couldn't load anything out of the mix files.

**Review by abcdefg30 — APPROVED** [review]

**Review by teinarss — APPROVED** [review]

**Comment by teinarss** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/1d69e41779c4989325bc32384a44a3ca77f38431...6eab03c56ab1600897c0d2dc3d90254e62cae51b

**Pull request merged**
