### PR TITLE
Adds a debug symbol (RA mod)

### PR DESCRIPTION
**Pull request by xan2622**
This PR changes the debug symbol (it currently uses the Options one) to its own new symbol.

### CODE REVIEW

**Comment by pchote** [comment]
You'll need to add this to the source psd file and then re-export the png.  We can't take changes to the png by itself.

**Comment by Mailaender** [comment]
:+1: Works well in-game.

**Comment by obrakmann** [comment]
:+1: looks good, nice job

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/608534bd35048bb79a2ec1c9185b8a21026945f7%5E...608534bd35048bb79a2ec1c9185b8a21026945f7)

**Pull request merged**
