### PR TITLE
Warhead refactor part 1: Shared InflictDamage

### PR DESCRIPTION
**Pull request by reaperrr**
Some 'small fries' I'd like to get out of the way before the bigger stuff.
Would be nice if this didn't sit around unreviewed/unmerged for too long.

### CODE REVIEW

**Comment by reaperrr** [comment]
I don't know what's wrong with the first commit, anyone any idea?

**Comment by pchote** [comment]
Probably related to the abstract class. Moving the `IWarhead` implementation from `Warhead` to each of the subclasses should fix the issue.

**Comment by teinarss** [comment]
Im also getting these errors: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'WarheadArgs' could not be found (are you missing a using directive or an assembly reference?)	OpenRA.Mods.Common	OpenRA.Mods.Common\Warheads\Warhead.cs	61	Active
Error	CS0539	'Warhead.DoImpact(Target, WarheadArgs)' in explicit interface declaration is not found among members of the interface that can be implemented	OpenRA.Mods.Common	OpenRA.Mods.Common\Warheads\Warhead.cs	61	Active
```

**Comment by reaperrr** [comment]
@teinarss At least that should already be fixed with the update I pushed.

**Comment by reaperrr** [comment]
> Probably related to the abstract class. Moving the IWarhead implementation from Warhead to each of the subclasses should fix the issue.

There's no such issue with `IWarhead.Delay`, though, and at least going by some tests neither making `DoImpact` virtual instead of abstract, nor moving the interfaces to the sublasses seems to have any effect, I always get the same 39 violations listed.

Could it be that the compiler has trouble telling the interfaces and local methods apart, since they're named the same?

**Comment by reaperrr** [comment]
Updated, dropped the first commit. Explicit interfaces would be nice to have, but they aren't necessary for my follow-ups and I'm not in the mood to delay my entire roadmap over them.

**Review by abcdefg30 — APPROVED** [review]

**Review by teinarss — APPROVED** [review]
Looks good

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ede44d1ab39288b04611a3e2b3398656435d4504...422df0279973daea626efae863a01436d6de481c

**Pull request merged**
