### PR TITLE
Add a description for AttackBomber

### PR DESCRIPTION
**Pull request by PunkPun**
I have taken the description from #19864

### CODE REVIEW

**Comment by Mailaender** [comment]
You added a typo in the commit message.

**Review by Mailaender — APPROVED** [review]

**Comment by Mailaender** [comment]
See also https://github.com/OpenRA/OpenRA/pull/19678.

**Review by JovialFeline — APPROVED** [review]

**Comment by PunkPun** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/7352d2d4f3628eab08ee9de0c9258a32a92d1023...5f81563f0cbb4d1db68c07ddb3be0957bef3b73f)

**Comment by Mailaender** [comment]
It will only be visible to https://docs.openra.net/ so it is not a change loggable towards players.

**Comment by PunkPun** [comment]
I assumed that engine category is also for modders

**Pull request merged**
