### PR TITLE
Fixed map saving into writable system directories

### LINKED ISSUE #19903: Map editor suggest saving into user folder when editing unpacked system maps
This is annoying during development as it is consistently the wrong choice.

## Reproduction
Open `allies-01` in the editor. Save it and it will default to the user directory even though your development system directory is writable.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/19903

### CODE REVIEW

**Comment by Smittytron** [comment]
I see two sides to this. The positive is that there have been several times where I've saved to the wrong folder, and I'm sure this change will save time for my inattentive self in the future.

I do see an issue where a user might open an official map out of curiosity, make a change that results in a crash, then doesn't know how to make the mission playable again without reinstalling OpenRA. If someone can tell me how I'm overthinking this +1 from me.

**Comment by Mailaender** [comment]
A user would not be able to save into that directory as we do a write check first. This only applies to you checking out this git repository.

**Review by Smittytron — APPROVED** [review]
Been so long since I've fired up release I forgot about it.

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/a3b4316e44a03a09ad78a861e10a687a5acf99b7...a863c848b28799cf8ecb646727e2135837867d0f)

**Pull request merged**
