### PR TITLE
Allow granting a condition to Carryalls currently carrying units

### LINKED ISSUE #18105: Carryall should able to grant a condition to self while being carrying an actor
Carryall can be sold on Service Depot while carrying a vehicle, causing the unit its carrying and self to disappear, wasting the value of carried unit. Have to prevent that and carryall trait doesnt have any condition for granting to self while carrying something. So i can suggest adding an field that functions similar to the LoadedCondition of Cargo trait.

In my RA based mod, made Chinooks able to carry select few light Vehicles. At the same time made it so that Vehicle and Aircraft can get sold when docked on the Service Depot for half their value.
Now if an Chinook docks on the Service Depot while carrying an Vehicle it can be sold for its own value, wasting the value of carried unit.
On APC's managed to prevent getting sold when on FIX via utilizing the loadedcondition.
For Carryalls this was not possible due to lack of condition to grant to self while carrying something.

### PR DESCRIPTION
**Pull request by obrakmann**
Closes #18105 

cc: @MlemandPurrs

### CODE REVIEW

**Comment by pchote** [comment]
:+1: to the first commit.

The second commit and test case really show how broken the selling on service depot idea is:
* You have to force-attack your own units before you can order them on, and then have to very quickly sell them before they are repaired and move off.
* The UI plays the sell sound immediately, but then the unit has to move off the service depot before it is removed from the world (existing bug, I guess).
* Selling a carryall will indeed release the cargo, but that unit will stay on top of the depot in violation of the standard transit-only tile rules (new bug with this PR).

The eject-on-sell logic makes sense for buildings (which is why it is set up this way on `Cargo`) but is IMO more trouble than it is worth on transport units. It looks like the first commit should be good enough to solve #18105, or we could perhaps add some new logic to both `Carryall` and `Cargo` that adds the refund value of the cargo to the refund, the same as we do for bounties?

**Comment by obrakmann** [comment]
I'm fine with dropping the second commit, I just added it since you mentioned it in the issue. For what it's worth, the code makes no assumptions about service depots whatsoever. I adjusted the test case to work without service depots.

**Comment by Jushdrug** [comment]
perhaps a new Action Menu could be used for units or buildings with more than one ability, much like in C&C3's UI.

**Comment by obrakmann** [comment]
As discussed here and on IRC, dropped the second commit (and testcase as well).

**Review by pchote — APPROVED** [review]

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/0042844fc47423d5c07e87b64c6db94486f43743...d8c85dfa23bdfcc4388d940ffe56b5c4ea083bee)

**Pull request merged**
