### PR TITLE
Add ParentActorInit when create mine

### PR DESCRIPTION
**Pull request by dnqbob**
For consistency.

### CODE REVIEW

**Comment by PunkPun** [comment]
I see that this is only used for bridges. What else is it useful for?

Also I'd recon quite a lot of other traits are not adding this init

**Comment by dnqbob** [comment]
One of the application is allowing Minelayer get XP from mine. Write a new `MineExplosion` use `ParentActorInit` will do the trick.

**Comment by dnqbob** [comment]
And I saw FreeActor, SpawnActorOnDeath and even Cargo give this initialization, but nowhere except bridge actually use it. For those place, maybe just some deprecated codes undeleted.

**Comment by dnqbob** [comment]
I add a showcase of minelayer gain XP from mine and mine accept damage buff from minelayer here. It is just a showcase. I can turn it to PR if you think it is valuable.

[minelayer-test.zip](https://github.com/OpenRA/OpenRA/files/12848658/minelayer-test.zip) as test map.

**Comment by PunkPun** [comment]
Mines giving XP would be a fun addition to Red Alert

**Comment by dnqbob** [comment]
See #21106

**Pull request closed without merging**
