### PR TITLE
Fix a crash when RallyPoint creates RallyPointIndicator

### LINKED ISSUE #20938: Crash when RallyPoint actor is created
## System Information

- Operating System:  Win10 64
- OpenRA Version: sp engine (https://github.com/OpenRA/OpenRA/commit/096af533b44056dccc1a44d1c2f599ecffe8077f)
- OpenRA Mod: sp

## Exception log

```
OpenRA engine version https://github.com/OpenRA/OpenRA/commit/096af533b44056dccc1a44d1c2f599ecffe8077f
OpenRA Language: zh
Shattered Paradise mod version {DEV_VERSION}
on map 63eb45db45ae54517cb8bbd29981f2871788e580 (Cabal 01: Hacky Situation by Nolt, jrb0001, dnqbob).
Date: 2023-06-25 16:40:42Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.13
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List1.Enumerator.MoveNextRare() at OpenRA.WorldUtils.DoTimed[T](IEnumerable1 e, Action`1 a, String text) in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\WorldUtils.cs:line 73
at OpenRA.World.Tick() in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\World.cs:line 450
at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\Game.cs:line 630
at OpenRA.Game.LogicTick() in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\Game.cs:line 645
at OpenRA.Game.Loop() in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\Game.cs:line 814
at OpenRA.Game.Run() in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\Game.cs:line 867
at OpenRA.Game.InitializeAndRun(String[] args) in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Game\Game.cs:line 305
at OpenRA.Launcher.Program.Main(String[] args) in D:\OpenRA\shattered-paradise-campaign test\engine\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[Replay.zip](https://github.com/OpenRA/OpenRA/files/11896032/Replay.zip)

You can try this[ link](https://gitee.com/dnqbob/shattered-paradise-sdk-mirror/repository/archive/aac2d8f1b86fb121f768cc67413bbd477410df6a.zip) to download the project files. (The project in git cannot find the map in replay so I have to do it like what the tester did)

## Additional information
So this is how I debug:
1. use vars in `World` to storage the latest operation(add/remove) to effects. I confirmed that it was "adding the `RallyPointIndicator`" cause the crash
2.  then, use a var to storage the latest actor with `RallyPoint` that just add to world. I found that it was the problem of an actor that was created by Lua.

My #20937 fix this issue, but I don't know if this result from deeper problem from OpenRA.

### PR DESCRIPTION
**Pull request by dnqbob**
Fix #20938

## How it happens
When actor with `RallyPoint` is created by Lua Script, it has a low chance that the `RallyPointIndicator` is created when effect is ticking (I can only guess so). It was reported by a tester on my mission map testing. 

Use this fix and the replay is no longer crash

### CODE REVIEW

**Comment by dnqbob** [comment]
I have the replay and the game project (non-git) used by my tester, but it is very strange that my project in git cannot read the replay (cannot find the map).

The effective game project is now holded by Hans (tester),  and we all have that replay file:
[Replay.zip](https://github.com/OpenRA/OpenRA/files/11896032/Replay.zip)

Update:
You can try this[ link](https://gitee.com/dnqbob/shattered-paradise-sdk-mirror/repository/archive/aac2d8f1b86fb121f768cc67413bbd477410df6a.zip) to download the project files.

**Comment by abcdefg30** [comment]
Why would `INotifyCreated.Created` run inside the `Tick` of an effect? That would mean that an effect created an actor.

**Comment by dnqbob** [comment]
So I can only guess so.

I have the same thought as you said, but the fix is working while I am still confused

**Comment by dnqbob** [comment]
So this how I debug:
1. use vars in `World` to storage the latest operation(add/remove) to effects. I confirmed that it was "adding the `RallyPointIndicator`" cause the crash
2.  then, use a var to storage the latest actor with `RallyPoint` that just add to world. I found that it was the problem of an actor that was created by Lua.

**Comment by abcdefg30** [comment]
What was triggering the Lua callback that created the actor?

**Comment by dnqbob** [comment]
Triggered by 
```
	Trigger.OnAnyKilled(Shopkeepers, function(a)
		EnrageMercenaries() ...

```

**Comment by PunkPun** [comment]
You shouldn't be adding any actors to world on the lua trigger frame

**Comment by dnqbob** [comment]
That is weird then. I don't see any description or comment in Lua Trigger about this limitation.

**Comment by dnqbob** [comment]
meanwhile, if we cannot use call back inside trigger frames to spawn actor, then coding basic story plot like reinforcement after certain mission completed or actor killed will be impossible or too complicated.

**Comment by PunkPun** [comment]
> That is weird then. I don't see any description or comment in Lua Trigger about this limitation.

In the lua scripting openra provides we always make sure that actors are only added to world on end frame tick. Though I suppose rally point creates the actor even before it's added to world?

**Comment by dnqbob** [comment]
> In the lua scripting openra provides we always make sure that actors are only added to world on end frame tick. 

No. In `Actor.Create()`, you create an actor in Lua ticking, and only add it to world at the frame end.

`Reinforcement` does everything in Lua ticking. Update: Nope, the same as `Actor.Create()`

**Comment by dnqbob** [comment]
And at line 206, in Actor.cs, the `INotifyCreated` is called no matter you add it to world or not.

**Comment by dnqbob** [comment]
And at line 206, in Actor.cs, the `INotifyCreated` is called no matter you add it to world or not.

**Comment by abcdefg30** [comment]
Yes, that makes sense now. The effect should be added in `INotifyAddedToWorld.AddedToWorld` instead of `Created`, see for example https://github.com/OpenRA/OpenRA/blob/56b5ace109c8fd8221684a24e897156bbcefa4f0/OpenRA.Mods.Cnc/Traits/GpsDot.cs#L43-L56

**Comment by dnqbob** [comment]
In addition, the example shows us most of the `IEffect` should be added to frame end task, instead of adding them in actor tick.

**Comment by dnqbob** [comment]
I am still very curious about it: this bug is not a 100% crash, or I have to say this is a rare crash, consider OpenRA has so many mods and we don't see crash like this. And I cannot reproduce this crash myself, have tried many times. Only crash in this replay.

Can someone explain in detail on how the timing cause the problem?

Meanwhile, this will lead to a problem that we have to check all of the traits and related places on the timing of effect added&removed.

**Comment by abcdefg30** [comment]
Automatic checks fail:
```
RallyPoint must explicitly implement the interface member INotifyAddedToWorld.AddedToWorld
RallyPoint must explicitly implement the interface member INotifyRemovedFromWorld.RemovedFromWorld
Explicit interface violations: 2
make: *** [Makefile:117: check] Error 1
```

**Comment by dnqbob** [comment]
Fixed

**Review by abcdefg30 — APPROVED** [review]

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ed51bf732768475979f2ac2b7bc5821b09b648b2...9151f3cb94425cf10feef6bcf04f2ff2454a571c)

**Pull request merged**
