### PR TITLE
Fixed Tiberian Sun mod not being versioned

### PR DESCRIPTION
**Pull request by Mailaender**
and some related inconsistencies.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
:+1: Confirming that TS versioning works, I don't know how to check the other two commits.

**Comment by Mailaender** [comment]
`make docs` and check the *.md files for a proper version stamp.

**Comment by Phrohdoh** [comment]
:+1: doc versioning works for me.

**Comment by pchote** [comment]
Looks good :+1:

**Pull request merged**
