### PR TITLE
Set the correct PlatformTarget for OpenRA.Test

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/9114 or at least makes it consistent with other libraries.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
I don't think this would fix it (the other assemblies that are still x86 presumably would suffer the same problem). But maybe somebody suffering from this issue can try it and see if I'm wrong.

**Comment by Mailaender** [comment]
For some reason it seems to fix the annoying warnings I get all the time:
image

**Comment by RoosterDragon** [comment]
Those are totally different warnings from the linked issue and should be suppressed by #10345, besides.

**Comment by Mailaender** [comment]
For some reason they aren't on MonoDevelop.

**Comment by RoosterDragon** [comment]
Well you should file a compiler bug/feature request so it respects that pragma then.

We can't just change the Test dll - it has 32-bit dependencies for one thing:

> There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\...\OpenRA\OpenRA.Game.exe", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

(Same again for the Mods.Common dll)

**Pull request closed without merging**
