### PR TITLE
Fixed AppVeyor error on Windows dependency download

### PR DESCRIPTION
**Pull request by reaperrr**
Fixes the AppVeyor build.

### CODE REVIEW

**Comment by abcdefg30** [comment]
Updated with the suggestion from @pchote.

**Review by MustaphaTR — DISMISSED** [review]
Make works fine on my PC. AppVeyor looks like working fine too. 👍

**Comment by reaperrr** [comment]
Updated, now only uses Tls12 for the github dependencies.

**Review by abcdefg30 — APPROVED** [review]

**Comment by pchote** [comment]
Cherry picked to `prep-1801` for a future hotfix release: 8b9744066888738c1d9acb65d45747dcd3e87435

**Comment by pchote** [comment]
Added a changelog entry for the hotfix release: https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/8c78fa4299a05b4cf10948a8026c5c2926d7914c

**Pull request merged**
