### PR TITLE
Increase ShippedSoundtracks of the TD mod.

### LINKED ISSUE #9043: Cannot install Tiberian Dawn Music
I have my The First Decade disc in, but the "Install Music" button doesn't appear in the Music window  for the Tiberian Dawn mod, but I was able to install the music for Red Alert from the TFD Disc just fine. Am I doing something wrong? 

 openra-2015-08-12t060347z

This was using the latest test version. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25672426-cannot-install-tiberian-dawn-music?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by GraionDilach**
Fixes #9043.

I broke this with my first music PR actually. >_>

### CODE REVIEW

**Comment by Mailaender** [comment]
Fixed as promised. :white_check_mark: Thanks for taking care of it yourself.

**Comment by GraionDilach** [comment]
This was the least. I feel kinda bad for suddenly disappearing anyway.

**Comment by pchote** [comment]
:+1:

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/1b74b952216659f471b06e2ee393dabf87eaacf3

**Pull request merged**
