### PR TITLE
Multiply damage and HP by 100 for TS

### LINKED ISSUE #11719: Multiply all damage and health values by 100 or 1000 in the nonD2K mods.
One of the actual benefits of Dune 2000's arbitrarily huge health pools and damage values is to have more bits for the float-integer conversion during actual damage calculation, preventing issues like #11425 to happen.

I think it would be useful to add this D2k trait to the other mods as well (would give more freedom to balancers without triggering rounding-to-0 possibilities).

### PR DESCRIPTION
**Pull request by Arular101**
Before:
ts1

After:
ts100

Yellow: value that needs to be changed.
Green: increased.
Red: decreased.
Orange: value that needs to be added.
Dark gray: value that should stay because it is an inherits (and not used anywhere else).

Almost all values are the same as before. The exceptions are:
`^Railgun` and `LtRail` vs concrete (0.5 more damage)
`MammothTusk` vs concrete (0.2 more damage) (only air targets)
`SmallDebris` vs wood, heavy, concrete (0.5 more damage)
`JumpCannon` vs concrete (0.05 more damage)
`Sniper` vs wood, light, heavy, concrete (0.5 more damage)
These differences don't have impact for the gameplay.

`DamagedByTerrain@VEINS:` is the only instance the upgrade ruler didn't catch. I didn't add it to the upgrade rules because I think this is not very common.

Related to #14301, #14448, #14461.
Closes #11719.

### CODE REVIEW

**Review by abcdefg30 — DISMISSED** [review]

**Comment by reaperrr** [comment]
@Arular101 I really appreciate the effort with the manually adjusted values, but since TS hasn't been balanced yet I'd prefer to keep the original values * 100 intact for now, except for obvious fixes like the ammo crate HP, `^DamagedByVeins` damage and LaserFence damage, of course.

**Comment by Arular101** [comment]
No problem, removed the adjustments. I'm only a bit concerned about the Minigun being 20% stronger vs wood armor. Rifle infantry can destroy buildings faster this way. But for now we can keep it like this.

**Review by reaperrr — DISMISSED** [review]

**Comment by reaperrr** [comment]
> No problem, removed the adjustments. I'm only a bit concerned about the Minigun being 20% stronger vs wood armor. Rifle infantry can destroy buildings faster this way. But for now we can keep it like this.

The Minigun is an extreme case that might indeed turn out to be a problem, going by damage per second vs. wood armor compared to other infantry. 
Maybe we should make an exception here and drop its versus against wood to 50 (in a dedicated commit with commit message explaining why).

**Comment by Arular101** [comment]
Added the Minigun adjustment back in a separate commit.

**Review by reaperrr — APPROVED** [review]

**Comment by penev92** [comment]
Note that such adjustments can easily break mission gameplay eventually.

**Comment by Arular101** [comment]
I'll have a close eye on the missions. I try to keep the units in campaign missions and skirmish/multiplayer behave the same as much as possible. If something conflicts, then most likely the mission needs adjustments. OpenRA uses after all a different rules set (TS probably also in the future when it is done). The changes at the other mods shouldn't be noticeable, they are adjusted to behave the same as before (except that veteran units now actually do 5% more damage per level). The external missions are covered with the upgrade rules, they have a chance to do 0.5 more damage than it used to do without the adjustments. Hopefully this is acceptable. Biggest concern is if they have units doing 1.5 damage. That means it does 0.5 and thus 50% more damage. But this can always be fixed afterwards.

**Pull request merged**
