### PR TITLE
Also trigger mission fail when subpen is sold

### PR DESCRIPTION
**Pull request by cacfd3a**
#16176

### CODE REVIEW

**Comment by digitalheir** [comment]
Is it better to trigger the check `OnRemovedFromWorld` than on both `OnKilled` and `OnSold`?

**Comment by abcdefg30** [comment]
> Is it better to trigger the check `OnRemovedFromWorld` than on both `OnKilled` and `OnSold`?

Capturing temporarily removes the actor from the world (or used to, and I doubt that changed in the recent rewrite), so we would have to be careful with `OnRemovedFromWorld`. `OnKilled` and `OnSold` should be good enough.

**Comment by pchote** [comment]
`Trigger.OnSold` doesn't seem to exist ingame (script fails immediately on start), or on https://github.com/OpenRA/OpenRA/wiki/Lua-API. The backend code exists for selling and sold triggers, but this doesn't appear to be exposed to Lua, so I really don't know what is going on there.

**Comment by digitalheir** [comment]
Oops. I found it through C# code so I assumed that it existed. Do you know of any equivalents?

**Comment by pchote** [comment]
The best and simplest fix is to finish adding the half-defined triggers, but this will likely push it outside of the Next Release timescale - aiming for the next and hopefully final playtest this weekend.

**Comment by abcdefg30** [comment]
Depends on #16300 now.

**Comment by abcdefg30** [comment]
#16300 was merged.

**Review by abcdefg30 — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/da71a0f4709637b05d6e38f664c6f09d9fd3b10a...275da1727db5afcfb454074d7fbd63e786a06b26

**Pull request merged**
