### PR TITLE
Notify the server after installing a map.

### LINKED ISSUE #8233: Starting a game on a map that has just been downloaded/installed kicks the player
Downloading, leaving the lobby, entering again and then starting the game works.

Looks like some state isn't updated properly.

The bug already exists in at least release-20150424. Haven't investigated further.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17252383-starting-a-game-on-a-map-that-has-just-been-downloaded-installed-kicks-the-player?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pchote**
Fixes #8233.

### CODE REVIEW

**Comment by Phrohdoh** [comment]
Why does the `NotReady` state need to be set after installing a map?

**Comment by pchote** [comment]
Clients have the `Invalid` state if the map isn't installed, which tells the server that they can't start the game (and should be kicked if the game is force-started).

**Comment by pchote** [comment]
Rebased.

**Comment by obrakmann** [comment]
Had to backport this to -release for testing, but it does indeed fix the issue. :+1:

**Comment by Mailaender** [comment]
I can confirm that this does seem to solve the problem I had just like https://github.com/OpenRA/OpenRA/pull/10816 although map parsing at that point is now also pretty quick.

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/5ff240d7145e61bd3fbe8d35bc176cedc56fa8de...a40d7554b4c030d0c254383ba199bf1a473c5598)

**Pull request merged**
