### PR TITLE
Singleton Traits - Implicit & Interface

### PR DESCRIPTION
**Pull request by atlimit8**
Requires #8848.
This is how I discovered the issue addressed by #8774.

Allows for singleton traits, that coordinate or otherwise manage other traits, such as `UpgradeManager` to be included automatically and allows checking for inclusion of multiple traits implementing the same singleton interface (usually accessed by `.Trait[OrDefault]` or `.Traits.Get[OrDefault]`).
Is part of my effort to improve inter-trait handling (#8786).

### CODE REVIEW

**Comment by pchote** [comment]
There's some good ideas here, but i'm not convinced about the specific abstraction that you're proposing in #8786.

I believe a cleaner appropach would be to start by splitting `Requires` into two interfaces that handle its two (actually quite seperable) jobs:
*  `Requires<>` (keeping the same name) - used when this trait doesn't make sense without the named trait.  Used primarily by lint tests to check for bogus rule setups and docs generation.  Does not affect the trait load order.
*  `InitializeAfter<>` - used when this trait accesses another trait (if it is available) from the constructor.  Affects the load order, and can be used together with `Requires<>` if a trait is needed from a constructor, or by itself if the dependency is optional.  There are a bunch of cases where we currently use Lazy to work around the lack of this capability which could be cleaned up.

Once this is in place, we can then add (in a second PR) `RequiresSingleton<>` and `Uses<>` and cover all of your use cases with a smaller number of clearly named tags.

Would you be willing to do these changes as a prerequisite PR first?

**Comment by atlimit8** [comment]
@pchote: Started.

**Comment by atlimit8** [comment]
I'll just scavenge from my `LoadAfterIfAvailableAndRequires` branch and then rebase.

**Comment by atlimit8** [comment]
FYI: that won't handle mutually cached traits; that is why I created this design (#8786).

**Comment by penev92** [comment]
Depends on #8848 now.

**Comment by atlimit8** [comment]
WIP

**Pull request closed without merging**
