### PR TITLE
Add money crates to GDI08a and GDI09

### LINKED ISSUE #17877: TD GDI missions 8 and 9 missing money crates
In the original, GDI mission 8 had a money crate in the southwestern civilian village, at the northernmost part of the village by some trees. GDI mission 9 also had a money crate, on a hill in the southwesternmost part of the map. For some reason these are missing in the versions added to the latest playtest.

### PR DESCRIPTION
**Pull request by abcdefg30**
Closes #17877.

### CODE REVIEW

**Comment by pchote** [comment]
It looks like `ImportTiberianDawnLegacyMapCommand` is missing crates from its list of overlays to convert. Can we please fix that while we're here, and someone (I can do it if you don't have an easy way to check) grep the original mission inis to check for missing crates in the other missions?

**Comment by abcdefg30** [comment]
Updated. I still need to find the TD mission ini's so I didn't check all missions so far, but I think at least nod07 is missing a crate.

**Comment by fruestueck** [comment]
[scg08ea.zip INI](https://github.com/OpenRA/OpenRA/files/4432540/scg08ea.zip)
```
...
[OVERLAY]
...
2693=WCRATE
```
---
[scg09ea.zip INI](https://github.com/OpenRA/OpenRA/files/4432544/scg09ea.zip)
Seach for `*crate*` without luck.

**Comment by pchote** [comment]
We have
```
paul@Ragnarok:missions$ grep CRATE *.ini
scb06ea.ini:2811=SCRATE
scb06eb.ini:1775=SCRATE
scb06ec.ini:1432=SCRATE
scb07ea.ini:3086=WCRATE
scb08ea.ini:807=SCRATE
scb08eb.ini:3480=SCRATE
scb09ea.ini:516=WCRATE
scb11ea.ini:3471=WCRATE
scb11eb.ini:3403=WCRATE
scb12ea.ini:301=SCRATE
scb13ec.ini:1222=WCRATE
scg04ea.ini:3737=SCRATE
scg04ea.ini:1528=WCRATE
scg04wa.ini:846=SCRATE
scg05wa.ini:2604=WCRATE
scg05wb.ini:2714=WCRATE
scg08ea.ini:2693=WCRATE
scg09ea.ini:3077=WCRATE
scg12ea.ini:2551=WCRATE
scg12eb.ini:1179=WCRATE
```

So for the missions we have ported, that is two of the three gdi04's (not sure which ones our a and b map to), both gdi05's, gdi09 and 08 (already added in this PR), all three nod06's, one of the nod07s, both nod08s, and nod09.

The map cell can be calculated by taking the number (e.g. 2811 for scb06ea), doing an integer division by 64 to get the y coordinate, and then taking the remainder (or taking the original number modulo 64) to get the x coordinate.

**Comment by reaperrr** [comment]
> So for the missions we have ported, that is two of the three gdi04's (not sure which ones our a and b map to), both gdi05's, gdi09 and 08 (already added in this PR), all three nod06's, one of the nod07s, both nod08s, and nod09.

Just to make sure this doesn't cause any confusion, only the `WCRATE`s are money crates, the `SCRATE`s are usually what you need to collect as mission objective.

**Comment by abcdefg30** [comment]
Added all the remaining crates. Two notes:
- The crate of gdi04a is outside of the map. You can't build anything in this mission so I left the crate there as 'easteregg'.
- The crate of nod09 is supposed to spawn when the church is destroyed, but our civilian buildings leave husks when destroyed and there is no nearby space available to spawn the crate, so I placed it in the shadow of the tree instead.
grafik

**Comment by abcdefg30** [comment]
One more thing maybe. That is the original location the money crate of nod07a spawns at when the refinery is destroyed:
grafik
I chose to not offset the location to be where the building explodes, as the AI will otherwise build over the crate. (This is not an issue with the original location as seen in the screenshot.)

**Review by pchote — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/f99770e26b862d576eadf30fee10719e26e54831...8c3c486ae1f64eb619e71437f058e6e48106fa1c

e8084ad
32b241e
82a98ae
97ecfa5
0a9aa48

**Pull request merged**
