### PR TITLE
Ant Missions

### PR DESCRIPTION
**Pull request by Cheesy0314**
Outdated

### CODE REVIEW

**Comment by Cheesy0314** [comment]
Closed this, already close to done with Lua script for mission two

**Comment by Cheesy0314** [comment]
Reopened with ant mission 2 included

**Comment by GraionDilach** [comment]
Ungh.

IMO keep this limited to a single mission only.

**Comment by Cheesy0314** [comment]
Ok, so you want me to close this and open two requests, one per mission? I’m

**Comment by GraionDilach** [comment]
Split off the second one to a new mission. You will need to squash the commits longterm anyway.

I'll try to review the content properly during the weekend but notsure if I'll get there. :S.

**Comment by Cheesy0314** [comment]
@GraionDilach I messed this PR up, I'll just create two new ones that are separate

**Pull request closed without merging**
