### PR TITLE
Fix endgame unpause

### LINKED ISSUE #14655: 'unpause' a game after game has finished
A TD Player (GDave) unpaused a game with `/pause` command after the game was over. 
Game continued, units followed last command but it wasn't possible to order them around.

On current playtest

### PR DESCRIPTION
**Pull request by pchote**
Closes #14655.
Supersedes #14657.

### CODE REVIEW

**Review by GraionDilach — APPROVED** [review]
:+1:

**Review by abcdefg30 — CHANGES_REQUESTED** [review]
You can't change the pause state after game end anymore. However, the game doesn't pause at all now.

**Comment by pchote** [comment]
Try again now.

**Review by abcdefg30 — APPROVED** [review]

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/6d19b05acb5c7dfe42e2c44605f3a0f8d0f589bf...d811178a84d49d21a35af20b5e77dd887ed54e5a

**Pull request merged**
