### PR TITLE
Fix d2k walls being always visible through f.o.w.

### PR DESCRIPTION
**Pull request by CH4Code**

### CODE REVIEW

**Comment by CH4Code** [comment]
When scouting the walls with a unit and then returning out of vision they were visibly redrawn on top of the fog of war. Did not notice a similar effect on the release version for RA. It's a minor visual glitch. Could not find the reason for it.

**Review by MustaphaTR — APPROVED** [review]

**Comment by MustaphaTR** [comment]
> When scouting the walls with a unit and then returning out of vision they were visibly redrawn on top of the fog of war. Did not notice a similar effect on the release version for RA. It's a minor visual glitch. Could not find the reason for it.

This should be #14645 , which is already fixed.

**Review by ltem — APPROVED** [review]

**Comment by ltem** [comment]
It is a nice fix so I'll add this to the next playtest.

**Comment by ltem** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(Next-Playtest)/_compare/712506782db31beee1479296617266514940883f...0b67f4e82cdd29b4acf1ec51aad812f4351cd623)

[73413a4e2](https://github.com/OpenRA/OpenRA/commit/73413a4e20f53d9663d2deac5b1ed7dae086eb4a)

**Pull request merged**
