### PR TITLE
Exponentially scale the volume value

### PR DESCRIPTION
**Pull request by netnazgul**
Applies to #14696 

[rationale](https://www.dr-lex.be/info-stuff/volumecontrols.html)
x^4 is a close enough approximation of e^x for the slider setting range of [0.0, 1.0]:

https://www.dr-lex.be/info-stuff/infoimages/volume_curves.gif
image
image

Value stored in settings.yaml will now have different meanings between game versions - new version will be [much] more quiet. Due to this fact I would still prefer implementing separate **ExpSliderWidget** for sound control (the beta of it is https://github.com/netnazgul/OpenRA/commit/735927c65dd34f0bdc2c7be89cdc35077aeb6feb).

### CODE REVIEW

**Comment by netnazgul** [comment]
Another idea which allows exponential volume control is to reimplement the slider so that it gives already rescaled values.
Realization is here https://github.com/netnazgul/OpenRA/commit/b1eb835245e8a31dd5c4bf2e83835581d6c22630
Also tweaked the ticks display so that it visually gives the impression of logarithmic scale.
Possible issues - mods that reimplemented settings.yaml and/or lobby-music.yaml - will need them to be updated to use the new ExpSliderWidget.

**Comment by Unit158** [comment]
Reading the OpenAL docs, the volume is actually already on an exponential scale based on power. If you want to make it based on human perception of loudness, just divide all the values by two.

**Comment by netnazgul** [comment]
@Unit158 
"AL_GAIN defines a scalar amplitude multiplier. As a source attribute, it applies to that particular source only. As a listener attribute, it effectively applies to all sources in the current context. The default 1.0 means that the sound is unattenuated. An AL_GAIN value of 0.5 is equivalent to an attenuation of 6 dB. The value zero equals silence (nocontribution to the output mix). "
The exact exerpt from spec. Well, this means exactly that it **IS** linear - 0.5 of value is 2 times less than 1, and 6dB states exactly that for amplitude values. 0.25 is 4 times less than 1, which is 12 dB for amplitudes, and so on.

What the PR actually does is making it so that we are reducing the volume power/amplitude **exponentially** - f.e. for 60 dB scale (which this PR approximates to) you will have 
1 = 0 dB, 
5/6 = -10 dB
4/6 = -20 dB
3/6 = -30 dB
...

Difference between exact exponential scale and x^4 approximation is that at 0 we want to have -INF dB, having -60 dB would have been enough for most "ideal" home audio systems which have noise threshold at approx. ~55-60 dB, but in real applications setting volume to -60dB won't be the same as no sound. And `f(x) = a*exp^(b*x)` only reaches 0 at `x = -INF`

**Comment by Unit158** [comment]
Right. I'm still convinced that this is a UI issue, not a back-end issue. If you want to control the sound exponentially, then all the audio loading settings should be changed to dB as well. This lets you set the slider value to 0 when it is all the way to the left.

**Comment by netnazgul** [comment]
The PR applies to all the sounds in the engine, so all sounds are covered this way.

As for the UI, I've [semi-successfully] tried also to implement it right at the UI level. It would have been a better solution, because the settings stored in settings.yaml would stay the same between old and new versions of the game. There is though a slight problem in a way setting values are applied from slider property to `Game.Settings.Sound.*Volume` - it is mostly done through directly binding slider get/set to these properties, which means that you can't easily modify the way slider works unless you either add new slider properties (f.e. "exponential = true" or something) or morph to a new slider. I've done the latter, here you can see the result and test it https://github.com/netnazgul/OpenRA/commit/b1eb835245e8a31dd5c4bf2e83835581d6c22630 . For it to work any custom *.yaml file in user mods needs to be modified to use new sliders, because SettingsLogic specifically binds ExpSliderWidget to required settings.

**Comment by pchote** [comment]
Modify the bindings instead.

**Comment by netnazgul** [comment]
It's done not only in the binding, but in several other places. Actually these are all of them I think:
https://github.com/OpenRA/OpenRA/blob/8a6091884127ea2c6706662332ee70097c81885e/OpenRA.Mods.Common/Widgets/Logic/MusicPlayerLogic.cs#L103-L105
https://github.com/OpenRA/OpenRA/blob/8a6091884127ea2c6706662332ee70097c81885e/OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs#L116-L125
https://github.com/OpenRA/OpenRA/blob/8a6091884127ea2c6706662332ee70097c81885e/OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs#L331-L333
https://github.com/OpenRA/OpenRA/blob/8a6091884127ea2c6706662332ee70097c81885e/OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs#L366-L371

So, copy of BindSliderPref to reimplement on desired settings, and modify all the places where value is transfered between slider position and game setting property.
If it's ok to apply conversion here, I'll try a third solution today.

**Comment by netnazgul** [comment]
Next iteration is here https://github.com/OpenRA/OpenRA/pull/14875

**Pull request closed without merging**
