### PR TITLE
Move weapons factory exit and waypoint closer to the building

### PR DESCRIPTION
**Pull request by teees**
Imgur

Fixes this glitch: http://gfycat.com/InfiniteCreepyHagfish

The visual drop in #9678 still persists though

### CODE REVIEW

**Comment by pchote** [comment]
To be completely correct these should have `ExitCell: 2,1` and `Footprint: xx== xx== xx==`.

**Comment by teees** [comment]
I don't think that Footprint would work:
Imgur

**Comment by pchote** [comment]
Looks good to me :+1:

**Comment by abcdefg30** [comment]
:+1:

**Pull request merged**
