### PR TITLE
Account for terrain height in AttackBomber.

### LINKED ISSUE #11820: Airstrike Power broken on targets with elevation.
On the first case I aim at powerplants on elevated ground, on the second I aim at targets at the lowest elevation possible, the map was A river runs near. Weapon code http://pastebin.com/i5rCHk1D .
meteor1
meteor2

### PR DESCRIPTION
**Pull request by pchote**
Fixes #11820.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Thought this was legacy code not worthing any effort to fix - since D2k ornithopters require an airstrikepower which truly attacks and not just "attack".

The code works though, so  :+1:.

**Comment by pchote** [comment]
It would be rather disappointing for modders if this didn't make it in for the playtest feature freeze, although I personally don't mind either way.

**Comment by Mailaender** [comment]
@ABrandau Are you interested in this and care to test this pull request?

**Comment by reaperrr** [comment]
Encountered no regressions in shipping mods and worked as advertised in my own TS testcase. :+1:

**Comment by reaperrr** [comment]
[changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/adf73c8a1ee66167653bfed1feaa9e468bb0dbd8...cafbf01aee0cb5af5b9f8c3a6dfc66ceaba09f5c)

**Pull request merged**
