### PR TITLE
Remove unused methods in MiniYaml

### PR DESCRIPTION
**Pull request by phrohdoh**
```
tmba:openra thill $ git rev-parse head
4660b7156d9a57790d4eadb8486b863f7232d8d0

tmba:openra thill $ ag FromDictionary
OpenRA.Game/MiniYaml.cs
131:            public static MiniYaml FromDictionary<K, V>(Dictionary<K, V> dict)
```

### CODE REVIEW

**Comment by RoosterDragon** [comment]
There's several unused public methods in this class, are we going to slice them out too? Why this method in particular?

**Comment by Phrohdoh** [comment]
I only noticed this method because code I am writing referenced it (based on bogus code in the past), if you know of more I'm fine with adding their removal to this PR.

**Comment by RoosterDragon** [comment]
`FromList`.

**Comment by Phrohdoh** [comment]
Now includes the removal of `FromList`.

**Comment by pchote** [comment]
:+1:

**Comment by pchote** [comment]
:+1:

**Comment by RoosterDragon** [comment]
:+1:

**Pull request merged**
