### PR TITLE
Extract common campaign rules for d2k and ra

### PR DESCRIPTION
**Pull request by obrakmann**

### CODE REVIEW

**Comment by HenrytheSlav** [comment]
Good to see this trend on, Placeholder and remider for me to test it when I get home.

**Comment by HenrytheSlav** [comment]
OK, I am not sure if I done everything right, but I get (same) crashes for example in sov1, 3 and 4a:
Exception of type `System.InvalidOperationException`: :0: Sequence v04.damaged-active uses frames [3..3], but only 0..2 actually exist

It seems some civ building (v04) has badly set frames?

**Comment by obrakmann** [comment]
This PR doesn't touch any sequences at all. On bleed, v04 does indeed use frame 3 for the damaged-active sequence, but the frame actually exists in the shp. Check the asset browser to see how many frames your v04.sno file has. Maybe you've got a corrupted install or something.

**Comment by HenrytheSlav** [comment]
That was an error on my side, tested many maps in both RA and D2k, no issues encountered. :+1:

**Comment by obrakmann** [comment]
Added `Demolishable` to tanks and vehicles by default.

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Pull request merged**
