### PR TITLE
Fix exceptions while loading mods

### LINKED ISSUE #9975: Error in debug.log because of missing mods/common/mod.yaml
```
An exception occured while trying to load mod all:
System.Collections.Generic.KeyNotFoundException: The key was not present in the dictonary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Manifest..ctor(String mod) in \OpenRA\OpenRA.Game\Manifest.cs:Zeile 104.
   at OpenRA.Manifest.LoadMods() in \OpenRA\OpenRA.Game\Manifest.cs:Zeile 194.
An exception occured while trying to load mod common:
System.IO.FileNotFoundException: The file "\OpenRA\mods\common\mod.yaml" could not be found.
Filename: "\OpenRA\mods\common\mod.yaml"
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at OpenRA.MiniYaml.FromFile(String path) in \OpenRA\OpenRA.Game\MiniYaml.cs:Zeile 251.
   at OpenRA.Manifest..ctor(String mod) in \OpenRA\OpenRA.Game\Manifest.cs:Zeile 65.
   at OpenRA.Manifest.LoadMods() in \OpenRA\OpenRA.Game\Manifest.cs:Zeile 194.
```

EDIT:
```
(antares79) abcdefg30: the first exception is because mods/all/mod.yaml is missing an RequiresMods: entry
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28201921-error-in-debug-log-because-of-missing-mods-common-mod-yaml?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by obrakmann**
Fixes #9975

### CODE REVIEW

**Comment by abcdefg30** [comment]
:+1: / :white_check_mark:

**Comment by penev92** [comment]
>(antares79) abcdefg30: the first exception is because mods/all/mod.yaml is missing an RequiresMods: entry

That was completely by design. Something apparently broke (probably during all the rebasing of that branch. I'd like to know what before we merge this like that.

**Comment by obrakmann** [comment]
Well, all I can say is that [this line](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Manifest.cs#L104) doesn't look like a `RequiresMods` entry would be optional.

**Comment by penev92** [comment]
No, more like I decided to skip in in `all`, but then @chrisforbes requested I log all exceptions there, and that resulted in this mixup.

**Pull request merged**
