### PR TITLE
Use 3rd damage level of TS buildings for death instead of critical

### PR DESCRIPTION
**Pull request by reaperrr**

### CODE REVIEW

**Comment by Mailaender** [comment]
As discussed in https://github.com/OpenRA/OpenRA/pull/7626 this is much more consistent. :+1: It also looks good in-game and I tested all buildings. Looks you missed nothing. :white_check_mark:

**Comment by pchote** [comment]
I don't like this idea.  It might make some sense, but detracts from the original feel of the game without (IMO) a sufficiently good reason behind it.  One of the development goals we had agreed on for TS was to not make this kind of arbitrary change before an initial release.

**Comment by Mailaender** [comment]
You should have placed your objection days ago at https://github.com/OpenRA/OpenRA/pull/7626#issuecomment-81356529 instead of mourning after the work has already been done.

**Comment by reaperrr** [comment]
The original game simply didn't use the 3rd frame/damage stage at all, neither as death anim nor as critical stage. If we want to reproduce the original feel, it would mean simply cutting everything Westwood disabled for whatever unknown reasons.
I'm quite sure it would only be a matter of time before people would start complaining why we don't fix WW's bugs/omissions.

**Comment by pchote** [comment]
> The original game simply didn't use the 3rd frame/damage stage at all, neither as death anim nor as critical stage.

I just tested this, and you're right.  I could have sworn that TS did this, but I guess it was RA2 only?
Given that, I fully support this pr.  It brings us closer to the original behavior, but also adds additional polish without any negative or subjective side-effects as far as I can see.

**Pull request merged**
