### PR TITLE
Replaced the gem mine artwork

### PR DESCRIPTION
**Pull request by Mailaender**
Railmine does not work well together with the resource layer. This keeps it as a decorative element, but replaces the gem mine with new 1x1 artwork created by @MicroJOo.

gem-mine

### CODE REVIEW

**Comment by pchote** [comment]
Any progress on this @MicroJOo?

**Comment by MicroJOo** [comment]
https://www.dropbox.com/s/srv95mzckw8l0on/gem-minex3.rar?dl=0

**Comment by Mailaender** [comment]
Thanks. Updated.

**Comment by MicroJOo** [comment]
:+1:

new gem mines

**Comment by cjshmyr** [comment]
Nice!

**Comment by obrakmann** [comment]
Could we not keep the old gem mine for backwards compatibility and just add this new one? Then we could have our cake and eat it, too.

**Comment by Mailaender** [comment]
I kept it, but not as seeding resources, because that glitched and is one of the reason for this replacement.

**Comment by obrakmann** [comment]
Yeah, I meant keeping it as a seeding actor so that we don't silently break existing maps. That would mean that there would be two different types of gem mines, I know.

An alternative solution could be to retire the `RAILMINE` name and call it something different, . Then maps would at least break noticeably and the resource site would also complain.

**Comment by obrakmann** [comment]
I dislike silent breakage, but it seems no one else cares, so :+1:

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/9b603ceeae5f66b61c07d3d3742e9c0450d67cfa%5E...9b603ceeae5f66b61c07d3d3742e9c0450d67cfa)

**Pull request merged**
