### PR TITLE
Fixed Juggernaut being invisible on map editor and carryall

### LINKED ISSUE #16098: Juggernauts are invisible when carried by a Carryall and in the map editor
Something is causing the ActorPreview to not render -- probably related to the default conditions state.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenRA/OpenRA/issues/16098.

### CODE REVIEW

**Review by Smittytron — DISMISSED** [review]
Works

**Review by deleted-user-1 — DISMISSED** [review]

**Review by abcdefg30 — COMMENTED** [review]
The shadow is duplicated now while (un)deploying.

**Comment by reaperrr** [comment]
@abcdefg30 is right.

**Comment by reaperrr** [comment]
You need to change `WithSpriteBody@deployed` to `RequiresCondition: deployed && real-actor` now, because otherwise it already shows up while the other body still plays the make anim.

**Comment by Mailaender** [comment]
Thanks. That does indeed fix it.

**Review by reaperrr — APPROVED** [review]

**Pull request merged**
