### PR TITLE
D2K - Add Ordos Mission 3a

### PR DESCRIPTION
**Pull request by MustaphaTR**

### CODE REVIEW

**Comment by ltem** [comment]
:+1: 
- No errors in the map found
- Plays itself quite similar to the original

**Comment by reaperrr** [comment]
I know this is basically our engine's fault, but could you please move the Harkonnen silos and CYard to the right by 1 cell and the wind trap up or right by 1 cell? I bet most players won't notice the difference and it won't hurt gameplay, either.
👍 after that.

**Comment by MustaphaTR** [comment]
Updated.

**Review by reaperrr — APPROVED** [review]

**Comment by reaperrr** [comment]
https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/ae5d2444ee2a8149662da3720847d82f3cf0c142...9548470652d7ee47dfe371e73bc7d0d4b5bce2c8

**Pull request merged**
