### PR TITLE
Changed make.ps1 test order

### PR DESCRIPTION
**Pull request by reaperrr**
- changed make.ps1 yaml test order to match makefile/Travis
- shortened `dependencies` command to `deps`

### CODE REVIEW

**Comment by penev92** [comment]
I guess you need to update the AppVeyor build script, because it tried to `make dependencies`.

**Comment by Phrohdoh** [comment]
This introduces inconsistency between `make.ps1` and `Makefile`.

**Comment by reaperrr** [comment]
Removed the dep shortening, the changed test order was more important anyway.

**Comment by Mailaender** [comment]
:+1:

**Pull request merged**
